### ISSUE TITLE
Incorrect prompt on delete with no repos

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1]
Prompts with:

```
Delete simulation "{{ simulations.selected.name }}"?
```

<img width="882" alt="screen shot 2015-08-03 at 3 58 01 pm" src="https://cloud.githubusercontent.com/assets/5495179/9048714/82b47bac-39f8-11e5-8732-1d3d1397d4e6.png">

**Comment by moellep** [comment]
This error only occurs if angular fails to initialize. The change which sets the json dataType when loading the application schema fixes the problem.
