### ISSUE TITLE
undulator UI -- add option to specify more harmonics

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#10]
It should be possible to specify higher-order harmonics in the case of an idealized undulator.
This is not relevant to the undulator UI for 'real world' magnets.
However, in the case of real world magnets, it would be very convenient for users if one could request a calculation of the higher-order harmonics.

**Comment by bruhwile** [comment]
This is important and needs to be addressed.

**Comment by mrakitin** [comment]
There are the `sm_hi` and `sm_hf` parameters, so need to show them in the Flux report. I'll implement it within #177.
