### ISSUE TITLE
Wiki for creation of new reports in Sirepo for SRW

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#100]
Hi Paul & Rob,

I would like to have a documentation for new reports creation in Sirepo for SRW. As an example, please provide the steps how to implement a new report for Multi-Electron Intensity on http://alpha.sirepo.com/find-by-name/srw/calculator/Undulator%20Radiation.

Thank you in advance,
Maksim

**Comment by mrakitin** [comment]
This issue is important for educational purposes. Let's consider 1st/2nd priority for it.

**Comment by mrakitin** [comment]
The documentation would be helpful for the new report creation, e.g. for the upcoming Brightness report implementation.

**Comment by moellep** [comment]
Added new wiki page with instructions and example:

 https://github.com/radiasoft/sirepo/wiki/Dev-NewReportExample

**Comment by mrakitin** [comment]
Thanks Paul! I'll check it out.

**Comment by mrakitin** [comment]
@moellep, thank you for the detailed description. I was able to create a new Trajectory report. Closing.
