### ISSUE TITLE
turn off trace on sirepo beta

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1000]
pkdc() messages appear in the logs on beta and are too noisy.

**Comment by moellep** [comment]
I commented out the noisy pkdc() calls for now.

**Comment by robnagler** [comment]
I edited system/sirepo/etc/sysconfig/sirepo to not have: PYKERN_PKDEBUG_CONTROL=sirepo. Need to build system.beta-sirepo and system.alpha-sirepo for them to have effect. Not bothering right now just documenting here.

We should use `pkdlog` for logging if there is any.
