### ISSUE TITLE
heavy disk reads in front-end can lock out other uwsgi requests

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1012]
If the uwsgi front end process is reading a lot of data from simulation error log, it can make the whole server unresponsive. This doesn't appear to be a locking issue, because when a sleep() is used to replace the log parsing, the server is still available.

To reproduce, import an elegant simulation which produces a lot of errors, for example, elegantExamples/cwiggler1/parTrack.ele and the run a simulation. End the simulation after a minute and the elegant.log file will be very large. Removed the prev_line bug fix in template/elegant.parse_elegant_log() to cause the log parsing to take several minutes. During the time runStatus is being processed, the server will be unavailable for new requests.

**Comment by robnagler** [comment]
Makes sense. I imagine the GIL is locked for thread I/O. There's a lot to address here. 

* uwsgi shouldn't do any work. All I/O ops should be in celery/containers.
* uwsgi should be async, not sync with these operations.
* Containers should get timeouts if they are doing too much work unexpectedly. In this case, we would never want to parse a 100MB log this way. There's something seriously wrong, we should bail on the first few errors.
* All web calls should be asynchronous so the client can check status.

**Comment by robnagler** [comment]
Obsolete, because job cmd reads error log, which is asynchronous.
