### ISSUE TITLE
elegant: beta functions in rings aren't periodic

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/sirepo#1016]
This is a science problem, but the beta functions being computed for the rings isn't periodic. I've attached the beta function image generated from the SPEAR3 example.

![twiss-output](https://user-images.githubusercontent.com/7430829/34893709-afb27ee8-f79b-11e7-9ba1-788c2eb0e99d.png)

**Comment by bnash** [comment]
Why is it so irregular?  What kinds of errors are there in the lattice?

**Comment by bnash** [comment]
Looks like no periodicity maybe.  But without errors there shouldn't be closed orbit.  Looks like some microns of horizontal closed orbit.

**Comment by bnash** [comment]
Re. the beta function, it could be just that the final point isn't the same as the initial point.  Probably the beta function is computed at the beginning of each element, so the beginning and end differ by the change in beta of the last drift at the end of the lattice.

**Comment by cchall** [comment]
@sdwebb This simulation was not set to run with matched twiss parameters, it is just using the default twiss parameters and thus is not periodic.

@moellep It might be good to update the SPEAR3 example to have twiss_output.matched=True and bunched_beam.use_twiss_command_values=True to give a more expected result. My modified SPEAR3 simulation: https://alpha.sirepo.com/elegant#/control/VF5LOjAg

**Comment by moellep** [comment]
Thanks @cchall - I've updated the SPEAR3 example (on alpha) and the results looks better:
![twiss-output-2](https://user-images.githubusercontent.com/6516910/37849683-4034179a-2e9e-11e8-8150-a1556d01e886.png)
