### ISSUE TITLE
elegant: fatal error with rpn window

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#1037]
After clearing the value of an rpn value the 'save change' button grays out until a new value is entered. However, if you click the 'save change' button anyway the empty variable is still saved and the simulation instance is ruined, resulting in '502 gateway error' displayed.

See: https://beta.sirepo.com/elegant#/lattice/x7WhOPht for an example

**Comment by bruhwiler** [comment]
This is a serious bug. A complex simulation can be ruined.
