### ISSUE TITLE
Input arguments for importer

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#104]
Please add possibility to provide input arguments for an imported script, so the import can be tunable based on the provided options. Ideally, we need to have a text field in the pop-up window "Import Python Beamline File" to provide the options like:
```console
--sm --und_g=6.72 --sm_ei=7700 --sm_ef=8250 --sm_ne=200 --sm_mag=2 --ebm_ens=0.7e-03 --ebm_emx=1.5e-09
```
Then they can be passed to `SRWParser` class and parsed inside of it.

**Comment by robnagler** [comment]
Wouldn't somebody just modify the file?

**Comment by mrakitin** [comment]
If a user has a "universal" virtual beamline script with multiple conditional options for different beamlines, modification would be the last option. Consider the code from https://github.com/radiasoft/sirepo/blob/master/tests/importer_data/SRWLIB_VirtBL_LCLS_SXR_01.py:
```python
    arElNamesAllOpt = [#Beamline Options
        ['M1', 'M1_G', 'G1', 'G_S1', 'S1', 'S1_AUX', 'S1_M2', 'M2', 'M2_M3', 'M3', 'M3_SMP'], #1
        ['M1', 'M1_G', 'G2', 'G_S1', 'S1', 'S1_AUX', 'S1_M2', 'M2', 'M2_M3', 'M3', 'M3_SMP'], #2
    ]
    arElNamesAll = arElNamesAllOpt[int(round(_v.op_BL - 1))]
```
By simply providing different `op_BL` options it's trivial to get different beamlines with the same script without modification. It will also work for other parameters. That should make the import more flexible. Are there any concerns about the functionality?

**Comment by mrakitin** [comment]
Merged in 547178e54cfaa3e960fe466484755aa6fe1272a9, thanks to Paul. Please let me know about any issues regarding the code.

Please also note that this will require to have updated `srwl_bl.py` from https://github.com/mrakitin/SRW/commit/ff0fecf3f67eec183ef246e237e7c09d3fc4d2cb to make the optional arguments have any effect.

**Comment by robnagler** [comment]
I need to update the tarball, which is used to build the container. We
don't pull directly from the repo, because we've had issues with the build,
since it is so large.

If you expect to do active development, we'll have to discuss purging the
old stuff in the SRW repo. There's a lot of checked in binaries and old
files which aren't used.

**Comment by robnagler** [comment]
You can update your VM with:

```bash
cd ~/src/radiasoft/containers/radiasoft/beamsim
git pull
bash -l codes.sh srw
```
