### ISSUE TITLE
elegant: Beamlines report on Lattice tab cannot be expanded

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1041]
This problem is seen with Chrome (latest version) running on Win10.
There is no problem with Microsoft Edge on Win10.

The URL of the simulation is here, but the problem can be observed in any Sirepo/elegant simulation:
https://beta.sirepo.com/elegant#/lattice/CYz5nkpX

Here's a screenshot,
![image](https://user-images.githubusercontent.com/3825435/35194514-0f3a223a-fe72-11e7-8372-3df09983b9a5.png)

**Comment by moellep** [comment]
This was fixed with 5cb4f72 which changed this split pane library.
