### ISSUE TITLE
elegant: giving beamline and element the same name breaks a simulation

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1044]
It is possible to name an element with the same string that is used for a beamline. The result is a simulation that won't run, generating an error message that is not especially meaningful. 

The UI should prevent users from doing this.

**Comment by Linhardt02** [comment]
This did happen to me. The program does try to change the name on you to make sure it does not have double names. I forcibly changed this, because I didn't know about this trait.

**Comment by moellep** [comment]
This fix has introduced a new problem - when you edit a beamline element, it appends a "-1" to the name. To reproduce, create a new elegant simulation and select "New Element" and create a DRIF named D1. Then select "edit" next to D1 and select "Save Changes". Then name will change to D1-1. Editing the element a second time will change the name to D-1-1.
