### ISSUE TITLE
Source intensity report in calculator mode

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#105]
When the app is in the "calculator" mode, hide the "Initial Wavefront Simulation Grid" option from the settings cog and instead show the fields on the Intensity Report settings.

**Comment by bruhwile** [comment]
Paul -- do you need clarification of what's wanted here?

**Comment by moellep** [comment]
I think I understand what needs to happen for this ticket.

**Comment by mrakitin** [comment]
After discussion with @ochubar there are some clarifications for this issue. We need to have these independent options for all reports in ALL Source tabs, not only in the "calculator" mode, but for other examples. The "Initial Wavefront Simulation Grid" should be renamed to "Wavefront Simulation Grid" and moved to the properties of the reports.

On the Beamline tab the parameters should remain in the settings cog.

**Comment by bruhwile** [comment]
Closing this issue, per today's telecon.
