### ISSUE TITLE
Elegant: Application Error: RangeError: Maximum call stack size exceeded.. A report was sent to the server.

### ISSUE THREAD

**Issue by mliza1191** [radiasoft/sirepo#1051]
Hello, 

I have been getting this error a few times already. Please see attachment, thank you!  

<img width="1149" alt="screen shot 2018-01-24 at 1 16 59 am" src="https://user-images.githubusercontent.com/15283103/35336336-18094eb0-00e6-11e8-8eee-af2d57bff7e3.png">

**Comment by bruhwiler** [comment]
Hi Martin @mliza1191 
Sorry for the error and thanks for creating an issue to report it.

Please post the URL for your simulation.

**Comment by mliza1191** [comment]
David, here is the URL link. 

https://uspas-sirepo.radiasoft.org/elegant#/lattice/eL5kwWK1 

Thank you

**Comment by moellep** [comment]
If you remove the BL beamline element from the end of the BC1 beamline, the recursion error will go away. We have a fix for this with issue #999 which will prevent this error in a future software release.
