### ISSUE TITLE
SRW: link to 'light' page is not available

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1056]
I was trying to go to https://beta.sirepo.com/light, but wasn't able to find any links on the main Sirepo page at https://beta.sirepo.com/ -- what I can do is to go to https://beta.sirepo.com/srw simulations page, and clicking on the "Synchrotron Radiation Workshop" link in the top bar does not forward to the former Landing page.

**Comment by bruhwiler** [comment]
We aren't sure how to integrate https://beta.sirepo.com/light into the new Sirepo home page. We are open to suggestions. 

With regard to clicking on the "Synchrotron Radiation Workshop" in the upper left of the window, I agree that it seems intuitive this should be a link to something.

At present, none of the Sirepo apps seem to be using this upper-left name as a link.

**Comment by mrakitin** [comment]
With the current implementation the concept of "Demo" mode and the "Expert" mode is lost (which re are discussing in the paper, and it was presented on a few conferences and meetings). On that page https://beta.sirepo.com/#/srw I would suggest to have both links - to the old "light" page and to the "expert" mode. The upper-left link's behavior can be restored as it worked previously.

**Comment by bruhwiler** [comment]
I suggest the following changes, which I think will address Maxim's concerns without strongly impacting the new Sirepo landing pages:

1) Clicking on the highlighted "Synchrotron Radiation Workshop" text in the upper-left region of the app should redirect the user to:  https://sirepo.com/#/srw   (i.e. the new Sirepo/SRW home page)

2) This new Sirepo/SRW home page is to be modified to have two 'launch' buttons, similar to the one we have now:
       [   Launch SRW in demo mode   ]
       [ (examples, existing beamlines) ]

       [Launch SRW]

where the upper button links to  https://sirepo.com/light#/home

Additional problem:  this link must correctly redirect to the corresponding 'beta' page.
Now, it incorrectly redirects to https://beta.sirepo.comlight/#/home which is not valid.

...and the lower button is the existing button, with the same behavior.

3) The old SRW home page is the same as it was before, except we delete the   [Expert users only]  button at the bottom

**Comment by mkeilman** [comment]
Per 1): The app name text **is** a link, to the root app level -- so if that's where you are it does nothing. Click a simulation and then "Synchrotron Radiation Workshop" and you'll pop back to the simulations list. If that behavior changes I think the user needs a clue, hover text or some other distinction between the app and its "home". 

Per 2): I can start with two launch buttons, but seems clunky to me - maybe a switch with explanatory text that changes the destination?

I'd like @messamer 's guidance on this stuff as well...
