### ISSUE TITLE
reducing disk usage

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1064]
We need to reduce disk usage. I wrote two utilities to share library files (misc/dedup.sh) and remove simulations older than N days (misc/expunge.sh).

On alpha, dedup reduced disk usage from 64GB to 59GB. Expunging reports older than 3 days reduced to 2GB. 

I wrote them in bash for now and will run manually. I wanted to get it done and tested so I could reduce beta (200GB) prior to migration.

**Comment by robnagler** [comment]
TODO items:

- [ ] dedup shouldn't be necessary. It should be handled by the code. @moellep was going to work on this
- [ ] expunging should be run regularly in cron

**Comment by robnagler** [comment]
Implemented [db trim script](https://github.com/radiasoft/rsconf/blob/596f9a2b3dd3e2e2b4e801bbdb76295b6e8714e6/rsconf/package_data/sirepo/db_bkp.sh.jinja) which runs nightly and expunges users every 30 days

**Comment by mrakitin** [comment]
Is it for beta server?

**Comment by robnagler** [comment]
This is for all servers configured by rsconf. 

It doesn't remove users who have registered with GitHub.

**Comment by robnagler** [comment]
Sorry, this removes simulation directories.

**Comment by robnagler** [comment]
not the simulations themselves, just the output directories

**Comment by robnagler** [comment]
I added a registered user check

**Comment by robnagler** [comment]
We are still having problems with 10GB simulations just hanging around. It's pretty easy to blow up a simulation.

I think we need to compress simulation results after X days, and sirepo.simulation_db should know how to read those files by either decompressing them or opening them in a pipe. I'll create a ticket for that.

**Comment by robnagler** [comment]
Just another data point. We ran out of disk space so we expunged guest users over 90 days old as well as manually deleted some big (+10GB) report directories.

**Comment by robnagler** [comment]
no longer an issue
