### ISSUE TITLE
SRW: changing simulation from idealized undulator to tabulated needs to update flux and trajectory params

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1065]
When you change an idealized undulator simulation to tabulated, the trajectory and flux reports need to set the magneticField values to tabulated (2). When reversing the change, it should be set to approximate (1).

**Comment by mrakitin** [comment]
Thanks for documenting this issue, @moellep.

**Comment by moellep** [comment]
I've fixed the case where the trajectory report was using the incorrect magneticField value when the undulator was changed from idealized to tabulated. I didn't find an easy fix to updated the flux report, because we offer both approximate and accurate options for that report when a tabulated undulator is used.

**Comment by mrakitin** [comment]
Thanks, @moellep!
