### ISSUE TITLE
Copy values from 2D-plots

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#107]
Hi Paul,

It's highly desirable if the values on 2D-plots in Sirepo could be copied when clicking on them.
Some hints from http://stackoverflow.com/questions/22581345/click-button-copy-to-clipboard-using-jquery can be used to implement it.

Thanks,
Maksim

**Comment by mrakitin** [comment]
Closing since it's implemented.

**Comment by robnagler** [comment]
Please link to a commit

**Comment by mrakitin** [comment]
Merged in 28abfaecc2adf436efae84ccd7f69abe2c37c0d2, cleaned up by Paul in 4156bfac9520c5d88ffb4b16884c25a7a7c2f185.
