### ISSUE TITLE
SRW: share results of partially-coherent simulations

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1070]
It's now extremely inconvenient to share the results of long-running simulations within one server with other users. When a user tries to reproduce a partially-coherent simulation using the provided link, the results of the simulations are not copied, which makes usage of the sharing feature useless for this important case. Please consider sharing such simulations with corresponding calculated results, so that the report can be readily viewed by a colleague/collaborator.

**Comment by robnagler** [comment]
We have a general problem of storing results, which would maybe help this. Results are big, but they compress well (3-5x with gzip -5). This would make sharing results easier.

We should understand which results take a long time to generate, and share the results based on some threshold for time vs space.

**Comment by mrakitin** [comment]
Good idea, Rob! Maybe at the moment we can hardcode just this partially coherent report data to be copied, but in the futer we may consider hdf5 with compression or some other tools like https://github.com/Blosc/bcolz.

**Comment by moellep** [comment]
We have a hook for this - when you share elegant simulations, the output data is copied for the results. (template.elegant->copy_related_files() does the work). Adding that hook to template.srw so the flux and partially-coherent files get copied over would be trivial.

**Comment by mrakitin** [comment]
Nice, thanks for the hint, Paul.

**Comment by mrakitin** [comment]
Within this issue we have to handle exporting/importing of those files as well. That would make sense if the simulation is exported from an internal server and is intended to be shared via beta.sirepo.com.
