### ISSUE TITLE
rslinac:  Twiss 'beta' is misspelled

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1072]
On the visualization page, in the 'Simulation Status' report, the word "beta" is misspelled as "betta" 3 times.

**Comment by bruhwiler** [comment]
Same problem in the 'Beam Report' report on the Source page.

**Comment by moellep** [comment]
I think this bug should get moved radiasoft/rslinac - the text is originating in the simulation output.

**Comment by bruhwiler** [comment]
Done.
