### ISSUE TITLE
beaker directory has too many files

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1080]
136825 files in beta's sirepo directory. Need to figure out how to garbage collect.

**Comment by robnagler** [comment]
a user writes: 

> Quick question - db/run/run/beaker/container_file contains Many Many .cache files - under what circumstances is it safe to purge those, and are there any associated other files that would need to be purged, e.g. files under db/run/run/beaker/container_file

**Comment by robnagler** [comment]
ran a little test on alpha (removing all cache files) and i was logged out.

**Comment by robnagler** [comment]
Beaker stores state for every connection, even if the server (sirepo) doesn't set anything in the cookie. The "empty" cache files look like:

```text
(dp1
S'session'
p2
(dp3
S'_accessed_time'
p4
F1528610135.6918399
sS'_creation_time'
p5
F1528610135.6918399
```

A file with a session in them is:

```text
(dp1
S'session'
p2
(dp3
S'oauth_login_state'
p4
S'anonymous'
p5
sS'oauth_user_name'
p6
S''
sS'_accessed_time'
p7
F1528421743.6573069
sS'uid'
p8
S'XXXXXXXXXX'
p9
sS'_creation_time'
p10
F1528379131.4263141
```

On alpha, there are 97 files, but only 5 of them have a login state. In order to use Sirepo, you have to have a uid, so the other 92 files can be cleared.

There doesn't seem to be a utility to convert to another database format. We should use Redis or DBM. Redis has the disadvantage of requiring another server. DBM has the disadvantage of not scaling. We already have a radiasoft/redis docker image (prepared for ownCloud, but unnecessary) so probably should just configure that. Don't have a redis backup configured, though.

The big problem is writing a converter for the existing software. We should do that when we go from beta to prod, which technically could happen any time.

**Comment by robnagler** [comment]
There are 93K lock files. Need to add something to remove old locks.

**Comment by bwakely** [comment]
*cough*
Putting the application behind a load balancer does tend to inflate the number of files here.
I'll see your 93K lock and cache files and raise you 17,000,000.

I'm now simply deleting .cache files older than n days as per 
https://github.com/radiasoft/rsconf/blob/f5f29b8f3ac39b0fed4f061ab9ef4e1913f50e11/rsconf/package_data/sirepo/db_bkp.sh.jinja

...Is it safe to also delete .lock files under the 
  sirepo/db/run/run/beaker/lock/*
hierarchy if there are no currently running jobs that might be associated with those lock files?

Cheers,
--Benji

**Comment by robnagler** [comment]
@bwakely that's really great data. I wouldn't have any idea why a load balancer would change anything.

If you need more capacity, fire up celery parallel workers. 

Are you running multiple instances of the sirepo server? That won't work. It assumes it is a single app and uses thread locking. The sirepo server itself doesn't do any real work so it shouldn't be necessary to balance its load. 

I imagine you can kill the locks that are older than some time. I don't actually know what they do.

We are looking into migrating to redis for the beaker backend. This would solve the files problem, but not the session garbage collection problem, which seems serious if you have 17M files...

**Comment by bwakely** [comment]
> I wouldn't have any idea why a load balancer would change anything.
It's not the load balancer as such, it's the health-checking that the (two) load balancers do every 30 seconds.

The load balancer is simply front-ending a single sirepo instance, not actually balancing the load across multiple nodes.

The accumulation of files is a factor of not having cleaned it for Many Moons,
we should be ok cleaning files older than +n days once a day now that we've identified the issues.

https://github.com/radiasoft/sirepo/issues/1272#issuecomment-406139350
will fix the issue by giving the load balancers something to monitor that won't accumulate lock/cache files.

Cheers,
--Benji

**Comment by bwakely** [comment]
Directly to the docker container, process:
/home/vagrant/.pyenv/versions/py2/bin/python /home/vagrant/.pyenv/versions/py2/bin/sirepo service http

We'll hang tight with cleaning up misc. lock and cache files for now - it's ok if there's an accumulation of them, as long as we've
got a cleanup method.

If/when a non-lock-and-cache producing "/status" endpoint is created, it'll resolve it properly.

Cheers,

--Benji

**Comment by robnagler** [comment]
@bwakely For the upgrade, you will need to create some configuration in advance so the migration proceeds smoothly. Please contact me offline so we can establish exactly what needs to change.
