### ISSUE TITLE
all apps:   use scientific notation when appropriate

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1103]
A JSPEC beta tester just requested this.
It was also a problem with 'elegant' for the recent USPAS course.

Sometimes, the Sirepo UI presents numbers in standard floating point notation with many zeros.
These are difficult to read.

It would be much better to use scientific notation.

**Comment by moellep** [comment]
This issue is for data entry fields, for example, in the screenshot below, the values should be shown as 6e-4, 6.58e+13, 2.2e-6. This applies to all apps.

![screen shot 2018-03-16 at 11 14 56 am](https://user-images.githubusercontent.com/6516910/37534768-4a1b4d84-290b-11e8-8114-14e180d6953e.png)
