### ISSUE TITLE
jspec:  UI needs option to specify cooling and IBS algorithms

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1110]
This should be on the Visualization tab
It could be part of the "Simulation Settings" report

We need an input called "Cooling algorithm", which should probably be a drop down menu. At present, there will only be two options:
    'Parkhomchuk'
    'off'

We need an input called "IBS algorithm", which should probably be a drop down menu. At present, there will only be two options:
    'Martini'
    'off'

The Parkhomchuk and Martini algorithms are chosen by default. In the future, there will be more choices. To turn the respective calculations off, you have to specify the following in the JSPEC input file:
    e_cool = off    (it is on by default, I think)
    ibs = off         (it is on by default, I think)

**Comment by moellep** [comment]
Cooling and IBS can now be turned on independently on the Visualization page. The algorithms will be select-able on the Rate Calculation settings on the source page. Currently there is no selector for the IBS, but this can be easily added when different choices become available.
