### ISSUE TITLE
Failing Docker container

### ISSUE THREAD

**Issue by RemiLehe** [radiasoft/sirepo#1113]
Hi,
First of all, thanks for developing Sirepo, and having it open-source!

I was trying to run Sirepo locally using the Docker container.
As explained on the README, I tried:
```
docker run -p 8000:8000 -v "$PWD:/sirepo" radiasoft/sirepo 
```
However, I am getting an error:
```
/home/vagrant/.radia-run/start: line 11: exec: sirepo: not found
```
Is there something I did not set up properly?

**Comment by robnagler** [comment]
Hi Reme, thanks for checking out Sirepo, and for reporting the bug.

The README was incorrect. The correct docker incantation is:

```sh
docker run --rm -u vagrant -p 8000:8000 -v "$PWD:/sirepo" radiasoft/sirepo
```

Note that this will create a `run` subdirectory on your laptop/server that contains the Sirepo database so the data are persistent across invocations. Please let us know if you have any other issues.

**Comment by RemiLehe** [comment]
Thanks for the prompt answer (and for fixing the README)! 
I am now able to run Sirepo locally ; nice!!

I'll close the issue.

**Comment by robnagler** [comment]
Hi Remi, just to follow up. The latest Docker image doesn't require you pass `-u vagrant`. The db directory changed to `db` so if you started doing real work, rename `run/run` to `db` before starting the newest container.

**Comment by RemiLehe** [comment]
Great! Thanks for the info.
