### ISSUE TITLE
SRW: resize of intitial intensity report

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#1115]
I'd like to expand the range for the initial intensity report and it seems that I couldn't do it.  I have an example where the photon beam is bigger than the given range.
![screenshot-2018-3-21 boaz undulator flux - srw - radiasoft](https://user-images.githubusercontent.com/1112276/37690116-b6a6cefe-2c6e-11e8-923c-d0e9af45cffd.png)

**Comment by bruhwiler** [comment]
Please provide a link to the simulation.
Thanks,
D.

**Comment by bnash** [comment]
Sure, here is the link:
https://beta.sirepo.com/srw#/beamline/L0tY4Jre

**Comment by bruhwiler** [comment]
I think you have uncovered a bug, which I've tried to explain in Issue #1117.

I think the following is a work around that might recover correct behavior for your simulation:
1) On the Beamline tab, add a Watchpoint with position 4 m
2) You'll see that the wavefront looks physical at 4 m, but still looks unphysical at 31 m.
3) Edit the propagation parameters. You'll see the first element is "Drift 16 m", which corresponds to propagation from the watchpoint at 4 m to the lens at 20 m.
4) In that first row, increase the values of "Horizontal range modification factor at resizing" and "Vertical range modification factor at resizing".  You can experiment with the optimal value, but 3 seems to work OK.
5) Now the behavior seems correct.

My simulation (slight modification of yours, as described above) can be found here,
https://beta.sirepo.com/srw#/beamline/6umAIJML

**Comment by mrakitin** [comment]
Thanks @bruhwiler for clarifying the resizing. Indeed, the range of the intensity report can be varied by the mentioned parameters in SRW/Sirepo.

**Comment by bnash** [comment]
Talking to @moellep, I learned that one can resize the grid using the "Initial Wavefront Simulation Grid" in the gear menu on the beamline page.

**Comment by moellep** [comment]
I see how this would be confusing because the initial beamline settings are hidden away. It might be better to move the "Initial Wavefront Simulation Grid" fields to a tab on the beamline's Initial Intensity Report editor. That is probably the place a user would look first.

**Comment by bnash** [comment]
Another idea is to put a button next to the "propagation" button in the beamline definition area.  One could also select whether to do single electron coherent calculations, or convoluted multi-electron, or many electron simulation, replacing the "partially coherent" tab.  The button could be called "starting photon beam" or something like that.

**Comment by bruhwiler** [comment]
This has been clarified as a UI issue.
I'm closing.
@moellep is aware and can open a new issue.
