### ISSUE TITLE
SRW:  "Initial Intensity Report" on Beamline tab must have same position as "Intensity Report" on Source tab

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1117]
This is related to #1115

The simulation URL is https://beta.sirepo.com/srw#/beamline/L0tY4Jre 

If the user sets the position of the "Intensity Report" on the source tab, from it's default value (I think) of 20 m to something smaller like 4 m, then this creates a problem.

In this situation, the "Initial Intensity Report" on the visualization tab remains at 20 m, and there is no way to modify the propagation parameters for the wavefront propagation, as it moves from 4 m to 20 m.

Hence, if the beam is too large for the mesh size at 20 m, the wavefront will be clipped and all subsequent wavefront propagation will be physically incorrect.

I think the solution is that, whenever the position of the "Intensity Report" on the Source tab is smaller than the position of the first optical element on the Beamline tab, a Watchpoint element should be added to the beamline definition, at a position equal to that of the "Intensity Report" on the Source tab.

**Comment by bruhwiler** [comment]
As noted in the related issue, my suggested fix (above) doesn't fix the entire problem, because the propagation parameters must be correctly modified in order obtain physically correct wavefront propagation.

**Comment by moellep** [comment]
I may not understand the issue correctly, but the Intensity Report on the source page is completely independent of the simulation on the beamline page. The initial aperture for the source page Intensity Report can be set using the "Range of Position" field. On the beamline page, the initial aperture is set using the "Initial Wavefront Simulation Grid" menu item and the selecting the "Range of Position" field. Setting the initial apertures the same in the two places and the Intensity Report should be identical to the Initial Intensity report on the beamline page.

**Comment by bruhwiler** [comment]
Thanks for explaining that @moellep -- that's helpful.
I understand the bug better now.
I'm closing this issue, and I'll open a new one.
