### ISSUE TITLE
warpvnd and comsol homepage images

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1119]
1) Replace the cavity image with WarpVND.png on https://beta.sirepo.com/#/warpvnd
2) Replace the cavity image with multipactor1.png on https://beta.sirepo.com/#/comsol

![multipactor1](https://user-images.githubusercontent.com/6516910/37727505-9c3b9664-2cfd-11e8-807b-7ffea362f64b.png)
<img width="648" alt="warpvnd" src="https://user-images.githubusercontent.com/6516910/37727556-c0b2edd0-2cfd-11e8-9fc4-e62eab0bb560.png">

**Comment by messamer** [comment]
If possible can we use this .gif?
![multipactormeshrotation1](https://user-images.githubusercontent.com/29441306/37729443-9bd3ce4e-2d02-11e8-8775-c19519b1a485.gif)

**Comment by mkeilman** [comment]
Neither Chrome nor Firefox display the .tiff file - can we get this in .png format?  The .gif looks fine (may want to trim that "gray flash")

**Comment by messamer** [comment]
Alternate .gif without fade to black at end and PNG to replace TIFF
<img width="648" alt="warpvnd" src="https://user-images.githubusercontent.com/29441306/37734938-3b726564-2d12-11e8-90d6-1ed7f745528b.png">


![multipactormeshrotation3](https://user-images.githubusercontent.com/29441306/37734923-2febc5b4-2d12-11e8-9389-be482a594c8f.gif)
