### ISSUE TITLE
all apps:  "Discard Changes to Example" breaks if the simulation name has been changed

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1128]
If you open an example simulation and make some changes, then you can recover the original state by clicking on the cogwheel to select "Discard Changes to Example"

However, if you have also changed the name of the simulation, then you get an error that the simulation cannot be found.

At this point, you have lost both the original example and also your modification -- neither simulation can be found.

**Comment by moellep** [comment]
By chance, this bug was just fixed with 6875b6b - example simulations no longer allow renaming or deleting.
