### ISSUE TITLE
loading examples didn't refresh

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1138]
I started a fresh installation, clicked on elegant to load the examples, and it stayed in the loading state. I refreshed the browser after a minute, and the files were there. Probably reproducible so LMK, and I can show you how to reproduce.

**Comment by moellep** [comment]
I tried to reproduce it by removing the sirepo/run directory but couldn't reproduce it. I've seen a similar problem on alpha and beta where the simulationList request times out occasionally.

If you can reproduce it again, let me know the steps.

**Comment by robnagler** [comment]
I can reproduce it by creating a new VM and loading a full-stack sirepo with rsconf. It's probably good I show you how to do this anyway. I'll be in Thu afternoon so we can do it side by side.

**Comment by moellep** [comment]
Fixed with issue #1151
