### ISSUE TITLE
JSPEC:  specify ion species by name.

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1146]
This request comes from a JSPEC beta tester, but I agree strongly with it.

At present, the Ion Beam report asks the user to specify the mass of the ion in units of Mev/c^2

![image](https://user-images.githubusercontent.com/3825435/38511994-224d0722-3be7-11e8-95eb-1fd36448ae59.png)

This is not intuitive. 

It also makes it hard to implement corrective logic. For example, the ion charge can be specified as 72 (or whatever), with the mass of a proton, which makes no sense.

Also, users can easily put in a value that is incorrect by a little (or a lot) and there is no way to implement robust error correction.

It would be better to specify the ions by name (a drop down list would probably make the most sense. Then the mass could be correctly specified and reported to the user, without bothering them to look it up.

When the time comes, I can specify a list of ion names and masses.

**Comment by moellep** [comment]
I can add this soon if you let me know which ion name/mass values to show in a pick list.

**Comment by bruhwiler** [comment]
@sjcrs -- please review this issue.
If you concur, then please provide @moellep with a table of particle names and properties.

**Comment by sjcrs** [comment]
I supplied a list including all species I could find from RHIC papers and the eHRIC pre-conceptual design report

**Comment by moellep** [comment]
The list of species:
```
Species,Mass (MeV),Ion Charges,A (Z+N),AMU of stable isotope
Proton,938.2720882,1,1
Deuteron,1875.612928,1,2
Helium,3755.675436,2,4,4.00260325
Aluminum,25126.4878,13,27,26.98153863
Copper,58603.6989,29,63,62.9295975
Zirconium,83725.21758,40,90,89.9047044
Ruthenium,94900.76612,44,96,101.9043493
Gold,183432.7312,79,197,196.966569
Lead,193687.0203,82,204,207.9766521
Uranium,221695.7759,92,238,238.0507882
```
