### ISSUE TITLE
plot full screen option

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1148]
Add a full-screen icon to the report panel. Selecting it will show the plot using the full display, fitting either screen width or height to the plot. The font size should be large, as if the plot were being displayed in a power point presentation. Several javascript libraries are available, such as jquery.fullscreen and fullscreen.js.

**Comment by bruhwiler** [comment]
Great idea!

**Comment by moellep** [comment]
Looks great! Some improvements are needed to show the graph on really wide monitors. Also showing the elegant lattice fullscreen needs to use full dimensions.

**Comment by bruhwiler** [comment]
In the Synergia app, in the Beam Evolution report on the Visualization tab, you can see that there is gray vertical line along the right edge of the graph.

![image](https://user-images.githubusercontent.com/3825435/40580622-459f047c-60ff-11e8-8d39-9941f721d075.png)

When you go to full screen, this gray vertical line is no longer rendered, which is confusing. At first, it seems like the plot has been clipped.
