### ISSUE TITLE
h5py causes initial server request to hang

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1151]
When running on freshly installed server software, if a new user loads an app, the simulation list response never makes it back to the client. Reloading the browser works OK. 
The cause is somewhere in the h5py init code. Importing h5py from server.py works around the problem for now. We use h5py 2.7.1 - it looks like this problem may not happen with h5py 2.8.0

Closes #1168.

**Comment by moellep** [comment]
Latest version of h5py doesn't fix it if HDF5_MPI=ON is enabled.

**Comment by robnagler** [comment]
Maybe there's a way to turn off MPI dynamically. Would be good to submit an issue to h5py.

**Comment by mrakitin** [comment]
Closes #1168.

**Comment by robnagler** [comment]
Resolved by server.py import but also by avoiding template imports by server.
