### ISSUE TITLE
SRW: always evaulate watchpoints in beamline order

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1155]
When a new watchpoint is dragged into the beamline, the execution order of the plots should remain in beamline order. Current execute order seems random.

**Comment by moellep** [comment]
This fix has a side effect of causing some reports not render this first time:

To reproduce, open the "Young's Double Slit Experiment" srw example, select "Discard Changes to Example", then visit the beamline tab. The last report shows a blank panel. The problem is in the initPlot() requestQueue.getCurrentQI() check.

**Comment by robnagler** [comment]
@moellep I think this is fixed. Reopen if not.
