### ISSUE TITLE
JSPEC:  improved treatment of time step

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1158]
At present, JSPEC users can input an overly large time step, generating bad results without knowing it.
They can also input an overly small time step, resulting in unnecessarily long run times.

This problem came up with a JSPEC beta tester.

The 'Simulation Settings' report asks for 'total simulation time', which I'll call T_total and 'total number of steps', which I'll call N_steps.

![image](https://user-images.githubusercontent.com/3825435/38642055-198a8da2-3d96-11e8-8b72-519206cbaabc.png)

The time step is defined by dt = T_total / N_steps

Here is a proposed algorithm for choosing the default time step:

The 'Rate Calculation' report calculates 3 IBS rates and 3 electron cooling rates.

![image](https://user-images.githubusercontent.com/3825435/38642276-d41c4dc2-3d96-11e8-907c-494a6d585c3b.png)

The GUI should select the maximum absolute value of these six numbers, which I'll call R_max.

The default value of the time step should be
   dt = 0.05 / R_max

Any time the 'Rate Calculation' report is updated, this should trigger a new calculation for the default value of dt.  If the user has never manually changed dt, then the *actual* value of dt should be automatically updated. If the user *has* manually edited the value of dt, then their choice should not be automatically modified.

This brings up another, closely related issue.  The GUI can manage logic associated with dt under the hood and modify the N_steps value accordingly. However, it would be much more intuitive to make 'dt' or 'Time step [s]' the input parameter. Then N_steps can be calculated accordingly.

The GUI also needs to warn the user, whenever dt exceeds a threshold.
If the user-specified value of dt is more than 4x larger than the default value, the input cell should be highlighted in some way and the user should be warned about possibly inaccurate simulation results.
If the user-specified value of dt is more than 4x *smaller* than the default value, the input cell should be highlighted in some way and the user should be warned about the possibility of excessive run times.

Any time there is a new calculation for the default value of dt, the logic for warning the user should be reapplied.

**Comment by bruhwiler** [comment]
@sjcrs -- please review this issue.
Do you think the priority should be increased?
Should the issue be modified?

**Comment by sjcrs** [comment]
To help a user debug if they're stuck in a difficult configuration, I think there should be a greyed-out window displaying some information calculated from total simulation time and number of steps. That should make explicit what's going on.  That window could display either dt or the # of rate cycles, as calculated from the rate calculation window.  I think dt would be simplest.

**Comment by bruhwiler** [comment]
Based on recent discussions, it seems the information being requested from the user is not well chosen and the results are potentially error prone.  Some thought is required to improve the situation.

**Comment by moellep** [comment]
JSPEC time step improvements

Several things can be done to improve this independently:

* Add a new model field simulationSettings.time_step "Time Step (s)". Show this on the Visualization tab under the "Total Number of Steps" field. Whenever total simulation time or total number of steps are updated, update the time_step field (total time / steps). If time step is edited, update the total number of steps (total time / time step). Avoid update loops in the\
 UI by using something like srw.js isActiveField() to see which field is currently being edited. Consider moving isActiveField() into the panelState factory for sharing with other apps.

* When a JSPEC simulation is run on the Visualization page, include a rate calculation (some field must control this - look at the rateCalculationReport). When the simulation completes, add some extra result validation described in the #1158 issue - verify that dt < 4 * (0.05 / max(abs(R))) and dt > 1/4 * (0.05 / max(abs(R))). If dt is out of the desired range, show a warning in the Simulation Status panel.

**Comment by e-carlin** [comment]
The alerts for when the time step is out of range will be handled in #2351
