### ISSUE TITLE
No module named 'h5py'

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1168]
When starting Sirepo on a fresh environment, there is an error message about missing h5py package:
```py
Traceback (most recent call last):
  File "/home/vagrant/miniconda3/envs/test_py36/bin/sirepo", line 11, in <module>
    load_entry_point('sirepo', 'console_scripts', 'sirepo')()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 98, in main
    argh.dispatch(parser, argv=argv)
  File "/home/vagrant/miniconda3/envs/test_py36/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/miniconda3/envs/test_py36/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/miniconda3/envs/test_py36/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/service.py", line 62, in http
    from sirepo import server
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 32, in <module>
    import h5py
ModuleNotFoundError: No module named 'h5py'
```

Used here: https://github.com/radiasoft/sirepo/blob/362e33b92696e45f98c969e31c1f6cbbd9bf6acf/sirepo/server.py#L32

**Comment by robnagler** [comment]
In order for Sirepo to run, the codes have to be installed. Installing the codes is complex. For a trivial example, h5py has to be compiled specially (with MPI) so you can't just `pip install h5py`, which requires mpi to be properly installed.

I don't think we can support `pip install sirepo` except for the hello world app, which is useless.

**Comment by mrakitin** [comment]
I see. That's sad... `pip install sirepo` takes 5 minutes to configure (+2 minutes of SRW's `make all`). How about separating the base code `sirepo`, and make separate plug-able packages like `sirepo-srw`, `sirepo-warp`, `sirepo-shadow`, etc? Matplotlib seems to be moving to this direction. Also, having a conda recipe may be a good addition, since all necessary pieces/versions can be found there (even [openmpi](https://anaconda.org/mpi4py/openmpi/files) for different platforms)

**Comment by robnagler** [comment]
I think we have to look at the user base. I don't understand who is using pip install besides you.

**Comment by moellep** [comment]
I think the "import h5py" should be wrapped somehow like this (pseudo-code):

if cfg.enabled_codes['warp']:
    import h5py

The h5py is being imported at server start for a work-around to issue #1151. It will be removed from there when the bug is fixed.

**Comment by moellep** [comment]
It was easy enough to fix. Now it will only import h5py if necessary. For example, if you only want SRW and shadow, you can run:
```
$ export SIREPO_FEATURE_CONFIG_SIM_TYPES=srw:shadow
$ sirepo service http
```
And h5py won't get imported.

**Comment by mrakitin** [comment]
Great! I also noticed that when a part of packages is selected, the tests still assume that the all packages are available. Can it be solved? I don't have bandwidth for this work, sorry.
