### ISSUE TITLE
Ignore tests for unavailable packages

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1169]
If the variable `SIREPO_FEATURE_CONFIG_SIM_TYPES` is set and specifies not all packages (e.g., `srw` only), only those tests should be executed which cover corresponding codes from `SIREPO_FEATURE_CONFIG_SIM_TYPES` + all general tests. Currently, all tests are executed, and many of them fail due to the packages (e.g., warppba) are not found. That would significantly ease the experience with contribution to specific codes.

**Comment by robnagler** [comment]
Need to add something like this to tests:

```python
pytest.importorskip('srwl_bl')
```

**Comment by robnagler** [comment]
conftest.py handles this
