### ISSUE TITLE
SRW: number of macroparticles requested not equal to number used

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#1183]
In the Partially Coherent tab on the beamline page, using either the general 5-D macroparticle sampling calculation, or the approximate method where only energy is sampled (on alpha server), there's a discrepancy in the number of macroparticles.  For example, when 100,000 are requested,  99,990 are given.  Requesting 100 results in 90, which is a more significant difference.
Requesting 62 results in 45... I didn't figure out the general formula yet.

**Comment by mrakitin** [comment]
All the logic is here: https://github.com/ochubar/SRW/blob/master/env/work/srw_python/srwlib.py#L4556-L4571. It uses some rounding to evenly distribute tasks on given nodes. I don't think we have anything to do with this at the moment.

**Comment by bnash** [comment]
Thanks, now I remember that you explained this to me, Maksim.
Still, as a user of the software, its a bit confusing.  I'd say its better to err on the side of being a little slower and giving the user what they request.  One may want to do studies with different numbers of macroparticles, for example.
So it looks like this isn't an issue with Sirepo, but with the SRW library function
srwl_wfr_emit_prop_multi_e()
