### ISSUE TITLE
Example folder for all apps

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1194]
All apps should have an Examples folder - existing examples should be moved into the folder via a db-upgrade. SRW examples should remain in their current locations. 

- [x] elegant
- [x] JSPEC
- [x] hellweg
- [x] shadow
- [x] Synergia
- [x] Warp PBA
- [x] Warp VND
- [x] zgoubi

**Comment by messamer** [comment]
Can we please add the example folder for elegant?  I need it for work with Vermilion.
