### ISSUE TITLE
SRW: "MMM" string appears on the landing page

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1203]
![image](https://user-images.githubusercontent.com/13209176/40519219-7c40fc34-5f8c-11e8-948f-a6774348b04e.png)

This code is responsible for that:
https://github.com/radiasoft/sirepo/blob/0e1de1dd69d9c8981e4d7689d7cc62f4aecd2f0b/sirepo/package_data/static/js/landing-page.js#L73

**Comment by robnagler** [comment]
It's a latex trick.

We had cookies in the office today. Maybe someone was expressing gratitude.
