### ISSUE TITLE
Synergia: show the user the initial beam Twiss parameters

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1206]
![image](https://user-images.githubusercontent.com/3825435/40580070-54d2c15a-60f4-11e8-881f-85ac9829815c.png)

The Bunch input report allows users to specify horizontal and vertical emittance. In general, that's not enough information. 

In the typical workflow, Synergia finds the matched Twiss parameters for the specified lattice, which is assumed to be periodic. The GUI should show the initial values of alpha and beta (both horizontal and vertical) to the user, on this same panel with the emittances. The values should be grayed out and should not be changeable.

This is an important change. We may want to allow users to overrule the matched Twiss values so that they have the flexibility to mismatch the beam, or to consider non-periodic beamlines.   Input from @ncook882 and @cchall would be valuable for deciding the next step.

**Comment by ncook882** [comment]
Some further updates.

I have added a NonlinearBunch class to the [bunch](https://github.com/radiasoft/rsbeams/blob/master/rsbeams/rsptcls/bunch.py) module. This class permits the fitting of nonlinear K-V, Gaussian, and waterbag distributions for use with the Danilov-Nagaitsev integrable insert.

I've also made a few additional updates to both bunch classes to fix small bugs, and to add the option for a zero-centroid "quiet start" feature.

The corresponding jupyter [notebook](https://github.com/radiasoft/rssynergia/blob/master/examples/synergia_basics/example-synergia_bunch_methods.ipynb) has been updated to demonstrate these features.

**Comment by moellep** [comment]
The various bunch distributions from Nathan's jupyter notebook have been implemented. 

- Computed From Beamline (the normal synergia way to create a bunch)
- Standard - Gaussian/K-V 
- Nonlinear - Gaussian/K-V/Waterbag
- From Input File (hdf5 format only for now)

A bunch can be downloaded as hdf5 and then used in a different simulation. Below are some examples.

![screen shot 2018-07-10 at 11 07 05 am](https://user-images.githubusercontent.com/6516910/42525965-c9698570-8431-11e8-9738-baf2e90d81ca.png)
![screen shot 2018-07-10 at 11 07 48 am](https://user-images.githubusercontent.com/6516910/42525970-cc7cd38e-8431-11e8-8b42-67d0a011c7db.png)
![screen shot 2018-07-10 at 11 08 14 am](https://user-images.githubusercontent.com/6516910/42525982-ce3aaca0-8431-11e8-8983-cdae093dacb4.png)
![screen shot 2018-07-10 at 11 09 02 am](https://user-images.githubusercontent.com/6516910/42525984-cf7d8ede-8431-11e8-8bce-20e0c32fc456.png)
