### ISSUE TITLE
Synergia:  enable conversion from MAD-X to elegant lattice files and vice versa

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1209]
1) enable the Sirepo/Synergia app to read elegant syntax *.lte lattice files
2) enable the Sirepo/elegant app to read MAD-X syntax lattice files

@cchall has experience in this specific type of input file conversion, and he has some Python scripts to assist.

**Comment by moellep** [comment]
Part 1 is now implemented with 7b5cb4d
