### ISSUE TITLE
Synergia:  the "Simulation Settings" input report should specify type of particle push

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1210]
@cchall has experience in this specific type of input file conversion, and he has some Python scripts to assist.
![image](https://user-images.githubusercontent.com/3825435/40580462-c966319e-60fb-11e8-956d-90a284486d88.png)

Synergia enables users to specify multiple types of particle tracking:
a) linear
b) 2nd-order
c) 3rd-order
d) higher-order....?  I'm not sure.
e) symplectic

@ncook882 and @cchall  should be consulted for the details

**Comment by cchall** [comment]
I've created a notebook describing the various options for particle pushes in Synergia and how to set them globally and for specific elements. See:
https://github.com/radiasoft/rssynergia/tree/master/examples/synergia_basics

**Comment by moellep** [comment]
The default extractor type for all lattice elements can now be set on the Simulation Settings panel. Individual elements can override this by setting the extractor type for the element directly in the lattice. The map order can be set between 1-4 and is used by the chef_map and chef_mixed type.

![screen shot 2018-06-05 at 3 24 33 pm](https://user-images.githubusercontent.com/6516910/41003780-e99510c6-68d4-11e8-8353-3915294237e7.png)
