### ISSUE TITLE
Beam waist and divergence

### ISSUE THREAD

**Issue by CFGrote** [radiasoft/sirepo#1221]
I got confused about the following:

I entered coherent beam rms waist = 40 um as shown below
![image](https://user-images.githubusercontent.com/15476807/41095883-3764a4ae-6a53-11e8-910d-ef141e8f0af3.png)

-> rms beam divergence = 1.54 urad

and then compared to  beam divergence from  https://www.rp-photonics.com
-> beam divergence =  6.18 urad (factor 4 of above)
![image](https://user-images.githubusercontent.com/15476807/41095943-5b8de868-6a53-11e8-8dcf-08f415d4b46a.png)

Is this a feature (e.g. different definitions of beam radius, which I suggest be better documented) or a bug?

Thanks!

**Comment by mrakitin** [comment]
Thanks for the report. Here is the corresponding code for recalculation in Sirepo:
https://github.com/radiasoft/sirepo/blob/3fbf1844c38fdd0743fdc556d7257b5f5a59e351/sirepo/package_data/static/js/srw.js#L680-L691
which is much more simplistic that from https://www.rp-photonics.com, assuming that the beam is ideal Gaussian.

**Comment by bnash** [comment]
Hi @CFGrote and @mrakitin 
I think I understand the issue.  First of all there is a factor of two between 'RMS waist' in Sirepo and 'beam waist radius' in the rp-photonics site.  In the terminology of the [Gaussian beam wikipedia page](https://en.wikipedia.org/wiki/Gaussian_beam), we would say that w_0 = 2*sig_r with sig_r the RMS beam size at the waist and w_0 the waist radius.

Next, assuming that 'divergence half-angle' is the same as Theta [here](https://en.wikipedia.org/wiki/Beam_divergence), then one can show that Theta=2 sig_r', with sig_r' the rms beam divergence.
Together this gives the factor of 4.
The formula that Sirepo is using: sig_r sig_r' = lam/(4pi) is correct, I believe.

**Comment by bruhwiler** [comment]
Thanks for the report @CFGrote 
Thanks for the clarification @bnash 

We need to document this convention in the UI.

**Comment by CFGrote** [comment]
Hi all,
thanks for the feedback. I suspected sth. like this (accumulation of factors due to different conventions).

**Comment by bruhwiler** [comment]
@bnash -- how do you recommend that we proceed?

**Comment by bnash** [comment]
We could document this in the wiki help pages, although the ability to include mathematical formulas is limited.
I made a first effort for the Gaussian beam:
https://github.com/radiasoft/sirepo/wiki/SRW-Coherent-Gaussian-Beam
