### ISSUE TITLE
enable multiple UI changes without asking server for simulations prematurely

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#123]
Use case is that a scientist wants to update several parameters, without waiting for multiple, unnecessary updates of the plots inbetween.

**Comment by bruhwile** [comment]
Other issues need to be created to address underlying technical design problems:
1) GUI should run all jobs asynchronously (run in background)
2) see 1st Priority ticket regarding celery tasks

**Comment by bruhwile** [comment]
Tickets #148 and #32 need to be closed first.

Suggestion for the UI:  as soon as user begins editing, all short-running reports should be canceled.

**Comment by mrakitin** [comment]
I think it's related to #549.

**Comment by robnagler** [comment]
I think this works correctly now. If you Save changes, reports are canceled. Not in the case of long running animations though, where the user must explicitly click end simulation which is handled by #355.
