### ISSUE TITLE
elegant: commenting out commands

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#1232]
Sirepo does not allow import of files .ele which contain commands with just the command start/end commented out (commenting the whole thing does work), which is a common shortcut in elegant for commenting out commands. For example this should comment out the twiss_ouput:

!&twiss_output
  filename = "twiss_output.filename.sdds",
  output_at_each_step = "1",
  statistics = "1",
!&end

**Comment by bruhwiler** [comment]
@moellep -- can you briefly describe how you resolved the issue?

**Comment by moellep** [comment]
I loosened the sirepo elegant parser to ignore any text between the &command &end tags, similar to the way elegant parses the file. If it is common practice to comment out a command like this:

```
!&twiss_output
  filename = 'twiss.sdds'
  ...
!&end
```
rather than this, which would have been allowed by the original sirepo parser:
```
!&twiss_output
!  filename = 'twiss.sdds'
!  ...
!&end
```
