### ISSUE TITLE
elegant: temporarily disable commands 

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#1233]
A feature request partially inspired by #1232. It would be convenient to be able to disable a command in the Control section so that it can be turned off without removing it and losing any of the values that have been changed. This would also let commented out commands be imported without being used.

**Comment by bruhwiler** [comment]
A customer has requested this feature -- it would make Sirepo - elegant much more usable for their application.

**Comment by robnagler** [comment]
Deadline?

**Comment by bruhwiler** [comment]
20230531
