### ISSUE TITLE
Replace Celery with queue and direct Docker execution

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1234]
There are many issues around Celery: #120, #691, #529, #348, #319, #149, #60, #979, #958, #820, and #1094. I think investing time in Celery is not the right solution. It has the following problems:

* No concept of contained execution (runaway "sub" jobs and security are not considered)
* No resource management (just queues with fixed allocations)
* No centralized db of what's going on (statelessness is a virtue in web apps but not HPC)

The issues listed above go into detail, but that's a quick summary.

We already have a queue called Background that allows developers to run without having to have Celery and Rabbit. It only allows one task at a time, but essentially, it manages a queue of tasks with thread-based locking. 

Sirepo already relies on a thread-based locking for the db. This means we can have only one process running the main server, and the work should be done by something else. We don't always do that. Some code executes directly, even going out over the web to other services. This is problematic, because the main server should not do any real work, just some management.

Docker provides contained execution, resource management, and secure remote execution (Celery is weak here, too). Constraints are easy to specify, e.g. limiting CPU and even disk bandwidth. We should make a queue manager like the Background queue that maintains the execution state on a collection of machines. This would be no worse than what we have now (lacking an overview), but would allow us to maintain the state and would fix many of the issues we have. The remote jobs would be started as they are now (there's only one Celery "task" anyway). We would have to probe the Docker daemons for their state, but the processes would be constrained. 

This would give us a solid basis for solving lots of problems like administration (what's running and where?), dynamic resource allocation, and even session management (allowing Docker containers to survive for a time after a request, like KeepAlive, and even "pre-fetch" of a user's container).

Also fixes #119, #89, #60, #698, #72, #406.

**Comment by mrakitin** [comment]
Can this project be considered? https://github.com/AustralianSynchrotron/lightflow. We have it deployed at a few NSLS-II beamlines already, but nothing limits it to work with Sirepo...

**Comment by robnagler** [comment]
@mrakitin can you explain how this project would solve the issues outlined? It seems to rely on Celery as the execution engine, and it doesn't seem to support Docker directly.

**Comment by mrakitin** [comment]
I don't think it will solve Docker issues itself, the framework is mostly used to conveniently build workflows. In case of Sirepo, it may be a consequent set of simulations. It was just a thought (maybe unrelated to the issue), that it can be used as a higher level package on top of Celery.

I wonder what kind of Docker management you will end up using. Will it be [Kubernetes](https://kubernetes.io/) or [Docker swarm](https://docs.docker.com/engine/swarm/)?

**Comment by robnagler** [comment]
Kubernetes is not appropriate for our workload. It's designed for preemtible tasks and stateless web apps where network isolation is important. It doesn't play nicely with MPI and batch queues as a result.

I had a lot of problems with "modern" Docker swarm with Jupyter. There's also "classic" swarm, but that's not supported. Swarm is designed for static orchestrations. It doesn't solve any of the problems that we have.

One of the additional problems is that we need dynamic resource allocations when we add billing to sirepo.com. We will want to allocate a fixed core-hours on a specific number of cores for the free jobs, and for users who want results faster or to run longer jobs, we'll allocate more cores and more core-hours based on a pricing model. Billing needs to be bound to Sirepo users. This type of resource management needs to be tightly coupled to Docker (giving appropriate `--ulimit` values). 

The point of this task is to remove layers. Docker itself is not a queue manager. SLURM, Torque, etc. are a different type of queue manager. Sirepo should always have resources available for people who want to pay, even if it means firing up resources in the public cloud (e.g. AWS) to handle the demand. Users shouldn't have to be notified that their job will run in a day, and rather, that the jobs run within seconds, always.  This would allow us a simpler queue. 

The sbatch style queue managers are for generic workloads, but we have a very clear understanding of what code is running and what it will be doing, which allows us to constrain execution with containers easily. This is also why we don't need the protection of orchestration tools like Kubernetes. We also need a direct interaction with the end user: they can kill a job at any time. This is not really what Kubernetes was designed for.

What we do need to protect is the user process having access only to its own files. That's why we need to start each Docker container dynamically and use KeepAlive-style connections to know that the user is active and we should keep their container around. This type of management is tightly coupled to the application, and will require management screens directly integrated into the app.

**Comment by mrakitin** [comment]
Thanks for the more detailed explanation, @robnagler. Yes, resource management screens would be really useful to understand workloads instead of currently used flower UI.

Did you consider [Dask](https://dask.pydata.org) at all? I'd like to hear what's your evaluation of the project...

**Comment by robnagler** [comment]
I have heard of Dask, but I don't really know much about it. My guess is that it wouldn't apply to what we do, since almost all of the computations are in other languages. I would think it might be useful if you were starting something from the ground up, but then, you might not choose Python at all.

**Comment by robnagler** [comment]
96fd265dcf05ca755acc57cec4a1cac3d224c140 adds complete decoupling of class from execution so  the job_map can have heterogenous instances.

**Comment by robnagler** [comment]
b7da2d53f42ad6377449d8d333afe888fda52aac adds Docker as a job_class. In the dev channel, it will mount ~/src and ~/.pyenv inside the container, which ensures the code inside the container is the same as the server. In other channels, it simply runs whatever is in radiasoft/sirepo:<channel>.

There are no changes to the radiasoft/sirepo Docker image. It works just like Celery mode.

I'm now working on TLS mode for Docker so we can distribute jobs.

**Comment by robnagler** [comment]
The importance of this is increasing. Some codes need different environments (#1271) so we need to be able to build and to execute codes in separate containers.

**Comment by robnagler** [comment]
As discussed yesterday with @mkeilman and @moellep: we need to monitor the simulation's progress on the execution node and report back with heartbeats. This could be done via a file or sending directly back to the server, which I think I prefer, as soon as the cookie issue with beaker is fixed. (Same problem as #1272 but in reverse -- the monitor will be setting status.)

**Comment by robnagler** [comment]
Merged into master. It should be completely backwards compatible, grabbing sirepo.server.cfg.job_queue to support Celery in the old mode.

The rsconf code is ready, too. 

For development with Docker executino, read: https://github.com/radiasoft/sirepo/wiki/Development#full-stack-development

**Comment by robnagler** [comment]
#311 will also be fixed by this, because we can dump the raw error log from the container.

**Comment by robnagler** [comment]
Will be fixed by #2097 so don't need to keep open.
