### ISSUE TITLE
SRW: add a link to Igor Pro documentation from Sirepo

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1238]
Igor Pro documentation about propagation parameters should be accessible via a link in Sirepo as a first step to provide clear explanation of the propagation parameters: https://github.com/ochubar/SRW/blob/master/literature/srw_pubs/SRW_Help.pdf (pages 43-48). It can be on the same page as https://github.com/radiasoft/sirepo/wiki/SRW-Propagation-Parameters.

Discussed over Skype with @ochubar and @bnash.

**Comment by bruhwiler** [comment]
There is great information here, which should definitely be made available to Sirepo/SRW users.
However, in its present form, it will be confusing to Sirepo users.
I think we need to reformat it.
