### ISSUE TITLE
SRW/Sirepo documentation

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1240]
After discussion over Skype with @ochubar and @bnash, we agreed we need better and more consistent online documentation. There are three places to take care of the documentation:
- [ ] Documentation of the fields in Sirepo itself (pop-up info box on hover-over mouse cursor). There is an existing issue https://github.com/radiasoft/sirepo/issues/367, assigned to me, but everybody else is welcome to contribute.
- [ ] Wiki documentation, which is poor now. It should somehow be generated automatically with all relevant snapshots of menus of optical elements and reports. #1239 partially covers it. It would be possible to achieve this point with TravisCI, but I'm not aware of the currently used CI system. @robnagler probably can comment on possibility to integrate those two systems.
- [ ] Better documentation at http://sirepo.readthedocs.io/. It can be much better, providing more details and screenshots, such as http://xrt.readthedocs.io.
- [ ] Understand the Igor Pro documentation and port it over to the wiki and/or read the docs with appropriate changes and updates. First priority is the propagation parameters.

**Comment by bruhwiler** [comment]
I assign box 4 above to myself -- making effective use of the Igor Pro documentation.

**Comment by bruhwiler** [comment]
I assign box 2 above to @robnagler

**Comment by mrakitin** [comment]
I'll repeat here what I suggested over a recent email conversation:

How hard would it be to publish a list of the current environment variables and the variables which are deprecated on each release of sirepo/pykern? This way it would be much easier to track the changes on the side of your users, including NSLS-II. As I suggested before, maybe it’s worth to publish it in the release notes at https://sirepo.readthedocs.io/en/latest/ with all the changes made, and having a corresponding tag at https://github.com/radiasoft/sirepo/releases. Filtering the GitHub issues is not the best way to get a quick hint what was changed. Many big projects invest a lot of efforts in good documentation:
- https://docs.dask.org/en/latest/changelog.html
- https://numpy.org/doc/1.17/release.html
- https://docs.scipy.org/doc/scipy/reference/release.1.4.1.html
- …

**Comment by bruhwiler** [comment]
RadiaSoft has hired a scientific technical writer, who starts on February 10.
Part of their duties will be to improve Sirepo documentation.
I will assign this issue to them, in the near future.

**Comment by mrakitin** [comment]
Thank you, David! That would greatly help.

**Comment by bruhwiler** [comment]
@remy278 -- please review this issue.
Then we can discuss.

**Comment by remy278** [comment]
I've pulled together a release notes page on the wiki, [here](https://github.com/radiasoft/sirepo/wiki/Release-Notes). I'll update this manually as we figure out how exactly we want to use RTD and the wiki itself.

**Comment by bruhwiler** [comment]
@mrakitin -- do you have suggestions for more info to be included on this new release page?

**Comment by mrakitin** [comment]
Thanks for the update, @remy278 and @bruhwiler! It's a very good start. Some of the releases are missing the description, which would be great to always have.

Also, I recently encountered the way the conda-forge community does it. They have a `news` directory, where each contributor places the description of the features or bug fixes, and then during the release process, a tool gets it all together and creates the release notes. For example, see this repo: https://github.com/conda-forge/conda-smithy/tree/master/news. And here is the page with the releases, which looks pretty nice: https://github.com/conda-forge/conda-smithy/releases. Can it be considered as an option?
