### ISSUE TITLE
URI formatting is decoupled from schema

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1244]
There's a slow creep of hardcoded assumptions between the client and the server which is making the code more and more brittle:

```python
        if application_mode == 'default':
            redirect_uri = '/{}#/source/{}'.format(simulation_type, rows[0]['simulationId'])
        elif application_mode == 'lattice':
            redirect_uri = '/{}#/lattice/{}'.format(simulation_type, rows[0]['simulationId'])
        elif application_mode == 'wavefront' or application_mode == 'light-sources':
            redirect_uri = '/{}#/beamline/{}?application_mode={}'.format(
                simulation_type, rows[0]['simulationId'], application_mode)
        else:
            redirect_uri = '/{}#/source/{}?application_mode={}'.format(
                simulation_type, rows[0]['simulationId'], application_mode)
```

This needs to be encapsulated in a library. The function formatUrl in sirepo.js does this already, but it needs to be on the python side as well. 

This is the type of copy-and-paste programming that is further copied by new programmers to Sirepo. Our code is becoming more and more public, and we need to be refactoring more and more, not less and less (as seems to be happening).

I assigned to @mkeilman assuming that he has time. I'll be happy to do this, too. However, I'm not in that code as much.

**Comment by robnagler** [comment]
The principles described in #1245 apply here, but I think the most important principle that's hard to explain is "explicitly couple relationships", which I know I go on and on about, but it's important for building development tolerant systems(tm). If you misspell "lattice" in the above, it will still error, but much later. The fast failure is where the misspelling occurs (in the above code) so by saying something like: raise_redirect(simulation_type=simulation_type, simulation_id=simulation_id, view='lattice') we can throw an exception in the format_uri call that's embedded in raise_redirect so that the developer knows there's no such thing as the lattice view. 

We have been programming sirepo for over three years now, and we are adding developers. The need for developer tolerant code is increasing. It's really important to think in terms of explicit coupling, even if the names are nonsense, it gives a label that can be fixed easily later with a fast-fail at the appropriate place: when the error occurs.

**Comment by mkeilman** [comment]
I wanted to check on my approach to see if this is along the right lines:

```
APP_MODE_TO_SECTION = {
    'default': {'section':'source', 'includeMode': False},
    'lattice': {'section':'lattice', 'includeMode': False},
    'wavefront': {'section':'beamline', 'includeMode': True},
    'light-sources': {'section':'beamline', 'includeMode': True}
}
...
def api_findByName(simulation_type, application_mode, simulation_name):
    if cfg.oauth_login:
        from sirepo import oauth
        oauth.set_default_state(logged_out_as_anonymous=True)
    # use the existing named simulation, or copy it from the examples
    rows = simulation_db.iterate_simulation_datafiles(simulation_type, simulation_db.process_simulation_list, {
        'simulation.name': simulation_name,
        'simulation.isExample': True,
    })
    if len(rows) == 0:
        for s in simulation_db.examples(simulation_type):
            if s['models']['simulation']['name'] == simulation_name:
                simulation_db.save_new_example(s)
                rows = simulation_db.iterate_simulation_datafiles(simulation_type, simulation_db.process_simulation_list, {
                    'simulation.name': simulation_name,
                })
                break
    assert len(rows) > 0, 'No simulation of type {} named {}'.format(simulation_type, simulation_name)
    return javascript_redirect(format_uri(simulation_type, application_mode, rows[0]['simulationId']))
app_find_by_name = api_findByName

def format_uri(simulation_type, application_mode, simulation_id):
    assert application_mode in APP_MODE_TO_SECTION, 'Invalid application mode {}'.format(application_mode)
    return '/{}#/{}/{}'.format(
        simulation_type, APP_MODE_TO_SECTION[application_mode]['section'], simulation_id, application_mode) + ('?application_mode={}'.format(application_mode) if APP_MODE_TO_SECTION[application_mode]['includeMode'] else '')
```

Here I use assertions since we're trying to catch the problem in development - in fact if you supply an illegal simulation type ('elegantX') you already get an assert error, so this continues the same idea.  BTW @moellep says the 'lattice'  case is no longer used so we can omit it.  Anyway, thoughts?

**Comment by robnagler** [comment]
Looks good. I have a few technical points:

* the `for s in` should get an `else` so that you can simply say `raise AssertionError(...)`
* The assert is not necessary in `format_uri`, because Python will tell you there's no such key as 'foo'
* error messages have been structured "object: error", not 'error object'. That's a standard Unix approach, and I'd like to see that encapsulated in some method: _err(obj, fmt, *args, **kargs). 
* the format line is too long in format_uri
* I think some of this should be based off the schema. Shouldn't the uri after `#/` be in the schema?

**Comment by mkeilman** [comment]
The schema do not contain any local routing - that's currently done in sirepo.js and each app's .js file.  I've played around with moving it to the schema, and it seems straightforward.

It looks like this is becoming a Thing, so maybe we should organize refactoring into its own issue with milestones etc.?  We have "format uri", "error message method", "move local routing to schema" so far, with presumably plenty to follow...

**Comment by robnagler** [comment]
Yes, I think we should create tickets which get scheduled along with other things so we can do this incrementally but consistently. We should drive all URIs off a schema and/or code that abstracts it. the '/#' is in a variety of places in the code. uri_router.py should probably control all of it.

There's also stuff in sr_unit.py and the tests themselves which should get shared.

Here are some other things:

* Right now we also do :foo vs <foo> for variables in the URIs, which I think should be one or the other.
* We need to encapsulate the params vs args for a post. We want to specify the api_ routine explicitly.
* I added bluesky.py which really should be an api. Right now, it is being delegated by server.py. uri_router.py understands "api_module" but it's not fully supported in the rendering of the URI+API. Thought needed here.

Start creating tickets, and we can talk through them tomorrow afternoon.
