### ISSUE TITLE
add a standard cookie warning

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1251]

**Comment by moellep** [comment]
Many sites use the bottom footer for the cookie notice (cnn.com, stackoverflow.com, etc). The cookie banner shows up both on the sirepo homepage app and within the individual sirepo apps. Dismissing it once will hide it everywhere. We'll want to link to the sirepo terms of service when it becomes available.

![screen shot 2018-07-11 at 12 08 14 pm](https://user-images.githubusercontent.com/6516910/42591156-1f57c754-8503-11e8-93bf-8f72add7f858.png)
