### ISSUE TITLE
Can't uploading new beam file when the input.sdds is too big (60MB)

### ISSUE THREAD

**Issue by biaobin** [radiasoft/sirepo#1253]
Hi, When I am uploading an input beam file for bigger than 60MB, it seems not working now.

**Comment by bruhwiler** [comment]
Hi @biaobin 
Thanks for the feedback.
What's the largest file size that you think you would like to import into the Sirepo/elegant GUI?

**Comment by biaobin** [comment]
Hi, is it possible for input file including 10E6 particles, which is about 600MB I think ?

**Comment by bruhwiler** [comment]
We will consider increasing the maximum allowable file size.

**Comment by biaobin** [comment]
Thanks, it will be really helpful for allowing larger input file size for simulations suppressing shot noise and for checking convergence.
