### ISSUE TITLE
3d particle report

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1260]
From @mkeilman pull request:

- vtk/Fete: I wanted to get something in place for folks to look at. Consequently I left in a lot of commented and far-from-final code. A few features so far:

- The number of particles can be selected just as in 2d. Also, the user can choose to connect every N points to speed up renders

- Users can toggle absorbed and reflected particle tracks, impact points, and conductors

- Zoom and pan are vtk default - double-click to get back to the starting position

- Tracks are colored according to the fieldReport

Tasks:
- [x] Axes #1292
- [x] Adjust spacing of conductors so faces don't bleed through
- [x] Add buttons to jump to straight-on camera positions in each direction
- [x] Allow selection of color map independent of field report
- [x] Research putting all point data into single actor (may make ```joinEvery``` moot)
- [x] Changes relevant to pull req comments

**Comment by moellep** [comment]
I like the particle 3d report - a good start and using vtk as well.

The main issue is performance when the "particles to render" is high and "join every N points" is 1. In some cases it causes firefox or chrome to become unresponsive for a minute or so. We should  estimate a good render time based on the number of points and particle count and set a limit - for example if 100 particles are selected, then maybe the "join every N points" needs to have a lower bounds of 5.

![screen shot 2018-07-17 at 9 38 41 am](https://user-images.githubusercontent.com/6516910/42828105-351f81e8-89a5-11e8-986b-8012763efc85.png)

**Comment by robnagler** [comment]
Very cool @mkeilman!!!
