### ISSUE TITLE
SRW: CDI simulation takes too long

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1271]
Reported by @ochubar. The attached `.zip` file with the simulation takes too long. it's reported to take ~30 seconds when run locally in the command line, but on NSLS-II Sirepo installation and on beta it takes ~20 minutes to run. A link to my simulation is: https://beta.sirepo.com/srw#/beamline/5zhJpw89?coherence=full.

[CDI Conc. 2 Long as Short 1mic 03.zip](https://github.com/radiasoft/sirepo/files/2206964/CDI.Conc.2.Long.as.Short.1mic.03.zip)

**Comment by mrakitin** [comment]
Another originally reported link: https://beta.sirepo.com/srw#/beamline/5S4PUFFV?coherence=full

**Comment by mrakitin** [comment]
Some timing information for local execution on my Mac:
```bash
$ time python cdi.py
Single-electron SR calculation ... completed (lasted 0.454141 s)
Extracting intensity and saving it to a file ... completed (lasted 0.005066 s)
Propagation ... completed (lasted 22.80818 s)
Saving Propagation Results ... completed (lasted 0 s)

real	0m33.453s
user	0m29.616s
sys	0m1.818s
```

**Comment by moellep** [comment]
@mrakitin could you email me the cdi.py file, just so I'm sure I'm debugging the same thing. Also, is the time above when running directly on the Mac, or within the VM? If it is directly on the Mac, could you also time it within the VM running in the sirepo environment?

**Comment by moellep** [comment]
It looks like the sirepo SRW is taking all of its time srwlib.srwlib.srwl_opt_setup_surf_height_1d() when _dim='x'. There are 4 mirror error files in the simulation - the vertical mirrors finish the profile in about 3 seconds, but the horizontal mirrors take about 5 minutes:

```
$ time python parameters.py

real    4m55.603s
user    4m53.755s
sys     0m0.360s
```
```
$ cat parameters.py
#!/usr/bin/env python

import srwlib

srwlib.srwl_opt_setup_surf_height_1d(
    srwlib.srwl_uti_read_data_cols('LCLS_SOMS_height_prof_1d_3x_ns.dat', "\t", 0, 1),
    _dim='x',
    #_dim='y',
    _ang=1.75 / 1e3,
    _amp_coef=0.9999)
```

Is it possible that that method is different on the version you ran in 33 seconds?

**Comment by mrakitin** [comment]
OK, here is the test suite for the issue: https://github.com/mrakitin/sirepo_bugs/tree/master/issue_1271/nNbleC14_watchpointReport9.

**Steps to reproduce:**
- clone the repo: `git clone https://github.com/mrakitin/sirepo_bugs`
- cd to the issue dir: `cd sirepo_bugs/issue_1271/nNbleC14_watchpointReport9/`
- then run a system-specific test:


# Python 2.7

### Running on a [Fedora 27 Vagrant](https://github.com/radiasoft/sirepo/wiki/Development#mac-install) machine with a stock Python 2.7:
```bash
$ time python cdi.py
Single-electron SR calculation ... completed (lasted 0.453387 s)
Extracting intensity and saving it to a file ... completed (lasted 0.00328 s)
Propagation ... completed (lasted 17.580146 s)
Saving Propagation Results ... completed (lasted 0.0 s)
TkAgg: backend unavailable; plots will be saved to files
Saving figures to uti_plot-{}.png

real	8m39.206s
user	8m31.698s
sys	0m3.903s
```

### Running in a Docker container with a stock Python 2.7:
```bash
$ docker pull radiasoft/sirepo:latest
$ docker run --rm -it radiasoft/sirepo:latest bash
$ cd /tmp/
$ git clone https://github.com/mrakitin/sirepo_bugs
$ cd sirepo_bugs/issue_1271/nNbleC14_watchpointReport9/
$ time python cdi.py
Single-electron SR calculation ... completed (lasted 0.46481 s)
Extracting intensity and saving it to a file ... completed (lasted 0.005632 s)
Propagation ... completed (lasted 14.006112 s)
Saving Propagation Results ... completed (lasted 0.0 s)
Saving figures to uti_plot-{}.png

real	8m23.997s
user	8m21.890s
sys	0m1.200s
```

### Running on a local Mac laptop in a Python 2.7 conda environment:
```bash
$ time python cdi.py
Single-electron SR calculation ... completed (lasted 0.446781 s)
Extracting intensity and saving it to a file ... completed (lasted 0.005617 s)
Propagation ... completed (lasted 18.736392 s)
Saving Propagation Results ... completed (lasted 0.0 s)

real	8m59.202s
user	8m34.166s
sys	0m5.118s
```


# Python 3.6:

### Running on a [Fedora 27 Vagrant](https://github.com/radiasoft/sirepo/wiki/Development#mac-install) machine, Python 3.6 conda environment:
```bash
$ time python cdi.py
Single-electron SR calculation ... completed (lasted 0.474416 s)
Extracting intensity and saving it to a file ... completed (lasted 0.004721 s)
Propagation ... completed (lasted 13.817152 s)
Saving Propagation Results ... completed (lasted 0 s)
TkAgg: backend unavailable; plots will be saved to files
Saving figures to uti_plot-{}.png

real	0m23.262s
user	0m20.606s
sys	0m2.921s

```
### Running on a local Mac laptop in a Python 3.6 conda environment:
```bash
$ time python cdi.py
Single-electron SR calculation ... completed (lasted 0.402556 s)
Extracting intensity and saving it to a file ... completed (lasted 0.004273 s)
Propagation ... completed (lasted 18.310443 s)
Saving Propagation Results ... completed (lasted 0 s)

real	0m35.413s
user	0m27.474s
sys	0m1.249s
```

**Comment by mrakitin** [comment]
I also added 2 logs with the strace debug calls for both Python 2.7 and Python 3.6 (they are huge logs):
- [Python 2.7](https://raw.githubusercontent.com/mrakitin/sirepo_bugs/master/issue_1271/nNbleC14_watchpointReport9/py27.log)
- [Python 3.6](https://raw.githubusercontent.com/mrakitin/sirepo_bugs/master/issue_1271/nNbleC14_watchpointReport9/py36.log)

I hope this information will help to understand/debug the issue. It looks like it's a Python 2.7 issue. Should we revisit and reconsider [Python 3.x support](https://github.com/radiasoft/sirepo/pull/1167)?

**Comment by robnagler** [comment]
We cannot consider Python 3 at this time. We have too many other challenges to work through.

We can profile Python 2 and debug. It's probably something obvious. Thanks for narrowing it down.

**Comment by moellep** [comment]
I believe this has been corrected now with the change to srwlib.srwlib.srwl_opt_setup_surf_height_1d()
My guess is that python3 identified the loop invariant and computed it once, but python2 didn't make that optimization. The new code should run much faster on python2. The new code is on alpha and should go to beta this week.
