### ISSUE TITLE
Enhancement request: status monitoring endpoint 

### ISSUE THREAD

**Issue by bwakely** [radiasoft/sirepo#1272]
Currently when you access sirepo, a session is created even if it's from a web checking service
(see also: [https://github.com/radiasoft/sirepo/issues/904](url) )

It would be handy to have a page (e.g. '/status') that was a lightweight reflection of if the system/components are online or not that did not create any session/cache/lock files.

--Benji

**Comment by robnagler** [comment]
Just discussed this today. I agree.

**Comment by robnagler** [comment]
Duplicate #235
