### ISSUE TITLE
Replace Beaker with stateless cookies

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1273]
Beaker uses the "lazy" approach to cookies: store a cryptographically-secure token which is a key on the server to some global state. Switching to Redis (#1080) doesn't solve the garbage collection problem which is two-fold: session state and users.

In BOP, cookies are stateless. This has worked for 20 years very nicely. Moreover, visitor records are not created unless the cookie comes back. 20 years ago, you couldn't trust search robots to do intelligent things with cookies so you had to make sure the cookie was sent back before storing any server side state that might later need to be garbage collected.

There's already over hundred lines of code dealing with Beaker: managing sessions with Flask, ensuring the database is initialized, creating the secret (rsconf), garbage collecting, etc. We have a bunch of issues (17M [sic] files in #1272) This is the "Make Make" problem, which is another "lazy" trap. The Cookie module in BOP is 283 lines long, and solves all the same problems as Beaker but statelessly so we don't have any garbage collection or management issues. 

Therefore, if we replace Beaker with at most a couple hundred more lines (probably much less), we would eliminate the garbage collection problem and fix the above issues.

Here are some considerations:

* We can assume threading. We are running in Flask, which is threaded, and we can assume it works. This simplifies the db considerably.
* We aren't storing session state, just user IDs, since there are no passwords. This simplifies the user state management over BOP's.
* We should solve the user is a real-user problem by doing robot checks on the UA string and also requiring a cookie to be returned before creating a user.

There are more considerations. Nothing is going to happen. This will be a good project for @derrelldurrett (if he's listening before starting :).

**Comment by robnagler** [comment]
More thoughts:

* See if we can reauthenticate via GitHub behind he scenes, that is, see if the browser still has access to GitHub. If it can't be done behind the scenes, we shouldn't do it.

* Expiry is tricky, and there's no good solution, since you can never know when a user comes back. However, we can update the cookie frequently, and perhaps keep some server side state about last accesses to prevent reuse of a stolen stale cookie. If the app is active, an attacker could not reuse a cookie in the middle of a sequence of requests, because it would be invalidated by subsequent request. This limits the replay attacks to the last known cookie before the quiesces. Much trickier.

* Expiry is important, and we can roll keys more frequently than BOP does, because re-authenticating (even if not behind the scenes) via GitHub is fairly trivial.

* Do the obvious like HttpOnly to prevent XSS. I don't think we need two cookies.

**Comment by derrelldurrett** [comment]
First experiment: Using only Flask, we can identify and delete the cookies currently placed by Beaker (this was done in a trivial Flask app that had been created solely for this purpose).

I'm still trying to catch up on what the real distinction is between when we care about cookies and when we do not.
```    resp = flask.make_response('''<html>
    <body>
    <a href="/">bart</a>
    </body>
    </html>
    ''')
    resp.set_cookie('sirepo_dev','', expires=1)
    return resp
```
