### ISSUE TITLE
Elegant -Visualizations Request

### ISSUE THREAD

**Issue by atfetter** [radiasoft/sirepo#1279]
With sddsplot in a terminal window one can plot multiple data sets on one plot. Example, sddsplot -col=s,beta? filename.twi or sddsplot -col=s,"(betax,betay)" filename.twi. Currently on the visualisations tab the plots only allow for one data set to be plotted at a time. Can this be changed to plot more than one data set at a time? Also said and shown before on issue #1237 how the lattice quads and dipoles can be shown on the plot is a _necessary_ part of plots in using Elegant. If you need any help in accomplish any of these parts let me know (My experience is limited but I would be willing to help look into it). 

Thanks

**Comment by atfetter** [comment]
I neglected to leave this in the comment before, I see that on the lattice tab there is a twiss parameters button that plots betax and betay and etax. That's all well and good, but for some reason when I use it for my application it dosn't plot like I expect it to. I get zero's all along the length except for etax.

**Comment by bruhwiler** [comment]
Hi @atfetter 
Thanks for contributing to Sirepo.
Regarding the Twiss plot with unexpected zero values, please provide a URL for a simulation that demonstrates the problem.

**Comment by atfetter** [comment]
https://beta.sirepo.com/elegant#/lattice/RmLWZPzH

**Comment by moellep** [comment]
Hi @atfetter,

We've made some improvements to the application and multiple columns from the same file can be now plotted on one report. The lattice can also be shown on top of the twiss and similar reports. Select the "pencil" icon on the report to select the columns to plot and the "show lattice overlay" toggle.

Give the twiss report on the lattice page another try, and see if the output look more reasonable. The same report is also available for the Visualization tab on the twiss_output report.

![twiss-output-13](https://user-images.githubusercontent.com/6516910/44117585-f50889f0-9fd0-11e8-9993-7520d6e559ed.png)

You can use the mouse-wheel to zoom into the report and it should rescale the y axis:

![twiss-output-14](https://user-images.githubusercontent.com/6516910/44117636-1d795cf2-9fd1-11e8-9376-e5744c7ef163.png)

If you are seeing different results, let us know and include a screen shot if possible.

**Comment by bruhwiler** [comment]
@atfetter  --  have you had a chance to look at the new developments?

If so, does this address your concern?

**Comment by atfetter** [comment]
I have had a look at the new development and it does meet my concern. 
Thank you.
Aaron
