### ISSUE TITLE
Display build version/channel

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#128]
@mrakitin request: need to embed the version in the docker image and then display that version somewhere in the interface. Probably want to show the update channel (beta, alpha, etc.) even though in the host name, for completeness.

**Comment by robnagler** [comment]
@ahebnl @mrakitin I just added https://github.com/radiasoft/containers/commit/26cc3e276cf34e748ab725cb64ab47db78863f3f which will add the SHA and repo url to /rsmanifest.json. The next build (not today's alpha #1715) will contain this. You can view it as follows:

```sh
$ docker run --rm radiasoft/test cat /rsmanifest.json
```
```json
{
    "image": {
        "git_commit": "d1ce4ed0d8618251f85644c427d119d243711016",
        "git_remote_origin_url": "https://github.com/radiasoft/container-test",
        "name": "radiasoft/test",
        "type": "docker",
        "uri": "https://registry.hub.docker.com/radiasoft/test:20190612.180453",
        "version": "20190612.180453"
    },
    "version": "20190612.150000"
}
```

**Comment by mrakitin** [comment]
Thanks, @robnagler, that's a pretty useful update! I think it will also make sense to [display the current branch](https://stackoverflow.com/a/12142066/4143531) as well, such as `git rev-parse --abbrev-ref HEAD`. What do you think?
