### ISSUE TITLE
Generate new Sirepo docker image

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1281]
@robnagler, please generate a new Sirepo image. There was a large commit by @ochubar, which I synced in https://github.com/radiasoft/SRW-light/commit/d907bed1a16c068459e2a8bef1da3345f2b6cba7. Thanks.

**Comment by mrakitin** [comment]
FYI: the synchronization was done by a bash script in my repo: https://github.com/mrakitin/srw_sirepo_utils/blob/master/sync_ochubar_SRW.sh. I ported this script to https://github.com/radiasoft/SRW-light/blob/master/utils/sync_ochubar_SRW.sh.

**Comment by moellep** [comment]
The docker image has been built and is now available on alpha.sirepo.com. The CDI example from #127 now complete the whole beamline in around 45 seconds: https://alpha.sirepo.com/srw#/beamline/RC5WkwHg?coherence=full
