### ISSUE TITLE
LSRMDLTR output

### ISSUE THREAD

**Issue by ypark39** [radiasoft/sirepo#1289]
My lattice doesn't generate an output when I add LSRMDLTR. Here is the [link](https://beta.sirepo.com/elegant#/lattice/XzrmIrA0). Could you see what is causing the error?

**Comment by moellep** [comment]
I'm not an elegant expert, and others may chime in. The elegant log shows many "Integration failure: exit condition failure" messages. From other LSRMDLTR examples, it looks like adding the accuracy value and increasing the n_steps may be required. Below is a link to a modified simulation which produces output:

[https://beta.sirepo.com/elegant#/visualization/sepdUZIe](https://beta.sirepo.com/elegant#/visualization/sepdUZIe)
