### ISSUE TITLE
dynamic load on optional javascript modules

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1299]
Apps should load the required libraries dynamically. For example, vtk.js should only load if required. sirepo-lattice.js should only be loaded for lattice apps (elegant and synergia).

Tasks:
- [x] lattice
- [x] beamline
- [x] d3
- [x] vtk
- [x] remove leading ```static/js``` from file references in schema, to be handled in python
- [x] determine which files must stay in ```index.html```

**Comment by mkeilman** [comment]
Question for the group: Would it make sense to move all of the javascript from ```<script>``` tags in ```index.html``` to the dynamic model, except maybe the IE-specific ones?  I can experiment...

**Comment by robnagler** [comment]
Sounds good to me. Generating HTML doesn't seem to have any particular value to me.

**Comment by mkeilman** [comment]
The only files that seem to require living in the html are angular, jquery, cookieconsent, and sirepo, along with the  specific app's js file name (```elegant.js``` )  which is filled in...

**Comment by robnagler** [comment]
Kind of strange. The app can't be dynamically loaded?

**Comment by robnagler** [comment]
I would think that dynamically loading as many modules as possible would be better rather than having it in the html.

**Comment by mkeilman** [comment]
Removed tasks for moving to ```schema.py```, as that has its own issue #1333
