### ISSUE TITLE
import h5py starts orted

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1311]
orted is a process which controls MPI, but it is unnecessary in the sirepo container. It's only required if you are running an mpi program. h5py is initializing mpi4py.

**Comment by robnagler** [comment]
Fix is pending: https://github.com/h5py/h5py/pull/1117#issuecomment-429949746

**Comment by robnagler** [comment]
We are no longer using OpenMPI so a non-issue.

**Comment by rorour** [comment]
is test_no_h5py() still needed in test.sh? Asking because I ran into it when importing h5py for omega

**Comment by robnagler** [comment]
You could test to see if the latest h5py does the right thing. We special case the codes in server.py. You could remove that and see.
