### ISSUE TITLE
elegant: example simulation fails to run

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1315]
https://beta.sirepo.com/elegant#/visualization/aksGTieA

![image](https://user-images.githubusercontent.com/3825435/44433873-823b3b80-a565-11e8-92ec-68e168bf1f25.png)

**Comment by moellep** [comment]
Was this an older simulation? The watch element was missing the output file field. The watch elements now automatically sets the output file when it is added to a lattice. Below is a corrected simulation:

https://beta.sirepo.com/elegant#/visualization/REsCZJjo

**Comment by bruhwiler** [comment]
Yes, it was an old simulation that I randomly selected to demo something.
Thanks for fixing things on the server side to accommodate this problem.
I'll clean up the old simulations in my workspace.
