### ISSUE TITLE
sirepo-plotting.js is over 3k lines long

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1318]
warpvnd.js is another big module. Not sure how to modularize, but for Javascript, it's really hard to understand what's going on when you enter a 3kloc module.

**Comment by moellep** [comment]
One solution would be to separate out each directive into a separate file and then using something like webpack to bring all the files together for distribution.

**Comment by robnagler** [comment]
Yes, that's one aspect. I'm wondering about the amount of complexity in the code itself. Are there ways to pare down that?
