### ISSUE TITLE
Review cookie, auth, bluesky & oauth changes

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1334]
Tests are passing, and the application seems to work. #1332 needs to be fixed before release. #1329, #1273, #1245, #751, and #1080 should all be fixed with this commit.

server.py was broken out into parts. APIs are now registered. Authentication is centralized and asserted on each api_* function.

Configuration will have to be changed:

* SIREPO_SERVER_OAUTH_LOGIN => add 'oauth' to SIREPO_FEATURE_CONFIG_API_MODULES
* bluesky is enabled by adding 'bluesky' to SIREPO_FEATURE_CONFIG_API_MODULES
* SIREPO_SERVER_BEAKER_SESSION_KEY => SIREPO_BEAKER_COMPAT_KEY
* SIREPO_SERVER_BEAKER_SESSION_SECRET => SIREPO_BEAKER_COMPAT_SECRET

New modules:

* cookie - handles stateless cookies to avoid fix to 
* api_perm - has an enum and dynamically generated decorators that are required on every api
* api_auth - defines an authentication API. It's not much about authorization yet, but will. 
* http_request - request parsers
* http_reply - response generators (need to move out redirects)
* beaker_compat - reads old cookies and converts to new format

Significant changes to old modules:

* oauth - has its api_* functions, which do not get registered if oauth is not in $SIREPO_FEATURE_CONFIG_API_MODULES.
* bluesky - has its api_* routines. You enable bluesky by adding to $SIREPO_FEATURE_CONFIG_API_MODULES
* sr_unit => srunit

**Comment by robnagler** [comment]
Configuration for new cookie implementation:

* SIREPO_COOKIE_PRIVATE_KEY - created with `sirepo cookie gen_private_key`
* SIREPO_COOKIE_IS_SECURE - default is true except on dev. Server without certs should set to false

**Comment by robnagler** [comment]
Renamed the sr_* modules to be more specific and not prefixed with sr_*.  I updated https://github.com/radiasoft/sirepo/issues/1334#issue-356319789

**Comment by mrakitin** [comment]
It looks like a major change. I'd coordinate with @ochubar when the server is not used. Will all the existing custom simulations/folders be preserved?

**Comment by moellep** [comment]
Yes, it is a big change and old sessions are preserved - the beaker sessions get automatically converted the first time the user visits the site. I've verified that a simple bluesky app works OK.
We haven't pushed this to alpha yet. Wait until then before putting it on other servers in case issues with alpha come up.
