### ISSUE TITLE
JSPEC: link to manual is dead

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#1346]
From the home page
https://beta.sirepo.com/#/jspec
The link to 
https://github.com/zhanghe9704/electroncooling/blob/master/User%20manual.md
is dead.

**Comment by bnash** [comment]
The link should be
https://github.com/zhanghe9704/electroncooling/blob/master/JSPEC%20User%20Manual.pdf

**Comment by robnagler** [comment]
This one works:

https://github.com/zhanghe9704/electroncooling/blob/master/JSPEC%20User%20manual.md

**Comment by robnagler** [comment]
I think we should prefer markdown over PDF, because it will render properly in the browser.

**Comment by bnash** [comment]
Sure, sounds fine to me.  How does one change the link?

**Comment by robnagler** [comment]
grep is your friend. We have a "g" alias that does the right thing:

```bash
$ cd ~/src/radiasoft/sirepo
$ g /zhanghe9704/electroncooling/blob/master
./sirepo/package_data/static/html/landing-page-jspec.html:          <li>A detailed <a href="https://github.com/zhanghe9704/electroncooling/blob/m\
aster/User%20manual.md" "target="_blank">JSPEC User Manual</a> is provided.</li>
./sirepo/package_data/static/js/jspec.js:SIREPO.USER_MANUAL_URL = 'https://github.com/zhanghe9704/electroncooling/blob/master/JSPEC%20User%20Manu\
al.pdf';
```

You'll need to update these two files and issue a pull request.

**Comment by robnagler** [comment]
Ah, just noticed that the two places are different. That's why we don't like copy-and-paste. ;-)  You should only need to fix one of them. Or, perhaps @mkeilman could help by adding user manuals to the schema. :)

**Comment by bnash** [comment]
Ok, I made the changes and created a pull request... hopefully correctly.

**Comment by mkeilman** [comment]
Added a task for this purpose to #1304

**Comment by bruhwiler** [comment]
This problem was identified and (I think) addressed via issue #1287 
Not sure why it broke again...

**Comment by moellep** [comment]
#1287 updated the link from the question mark drop in the app. It didn't mention the link to the manual on the landing page.

**Comment by bruhwiler** [comment]
Since the problem has been added to another issue by @mkeilman, I will close this issue.
