### ISSUE TITLE
Different behavior for 3 and 4 enum fields

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1348]
I've been trying to work on #1345 with @ochubar and noticed that the behavior is different when I try to work 3 or 4 enum values. Here is an example what I try to add:
```json
        "DiffractionPlaneAngle": [
            [0, "0 (vertical, up)"],
            [1.57079632, "𝛑/2 (horizontal, left)"],
            [3.14159265, "𝛑 (vertical, down)"],
            [4.71238898, "3𝛑/2 (horizontal, right)"]
        ],
```
Here are the values propagated to SRW when I use three of them:
```
======= _ang_dif_pl: 0, type: <type 'int'> ======
======= _ang_dif_pl: 1.57079632, type: <type 'float'> ======
======= _ang_dif_pl: 3.14159265, type: <type 'float'> ======
```
and four of them:
```
======= _ang_dif_pl: 0, type: <type 'unicode'> ======
======= _ang_dif_pl: 1.57079632, type: <type 'unicode'> ======
======= _ang_dif_pl: 3.14159265, type: <type 'unicode'> ======
======= _ang_dif_pl: 4.71238898, type: <type 'unicode'> ======
```
The last set obviously breaks the code. Should there be any validation of the values in the second case?

**Comment by moellep** [comment]
Need to investigate why the types changed between the two cases. Changing enum values to strings should fix the problem. Need to add a schema validation case that enum value and description are both string values.

**Comment by mrakitin** [comment]
Great, thanks for the fix, @moellep! I'll check it out when I get back to #1349.
