### ISSUE TITLE
for dev, autoinstall jshint and karma

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1364]
When installing sirepo-dev, jshint and the karma npm packages should get installed by default.

**Comment by robnagler** [comment]
Is this everything?

```sh
npm install jshint karma
```

**Comment by moellep** [comment]
```
npm install jshint karma karma-jasmine karma-phantomjs-launcher jasmine-core
```

**Comment by robnagler** [comment]
fix https://github.com/radiasoft/download/commit/e5157be3541cf48c5a47d1506d6a1426ab33c605
