### ISSUE TITLE
too many client side cookies

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1368]
These are all client side:

* cookieconsent_status
* net.sirepo.first_visit
* net.sirepo.get_started_notify
* net.sirepo.sim_list_view
* sr_cookieconsent
* Database storage

- [x] Modularize into a single cookie string that's simple with short words and a mapping. 
- [x] delete old cookies
- [x] indicate that the cookie is client side, e.g. sirepo_cookie_js. (It doesn't need a channel, because it is client side.)

**Comment by robnagler** [comment]
Different timeouts are not what I expected. Maybe it would be good if we documented these somewhere?

**Comment by mkeilman** [comment]
Specifically, the "login to save" prompt cookie expires after 1 day.  Will the new non-github login process change that?  In any case, will moving such configuration to the schema be sufficient documentation or ???

**Comment by robnagler** [comment]
This stuff should be in the schema. It shouldn't just be buried in some JS. 

It seems to me that this should be in the server-side cookie anyway.  Now that we have a module for that, we could migrate some of this by asking the server to divulge that state in the userState object, which frankly is similar to logging in.

I think we will require a login (soonish). At that point, "login to save" will be moot. You'll have to login.

If there are no other timeouts, then maybe we shouldn't move the "login to save" timeout for now. It's
