### ISSUE TITLE
docker runner uwsgi and threads

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1380]

**Comment by robnagler** [comment]
`enable-threads: true` is important, even though the documentation says it is automatically on. Turning it on doesn't allow jobs to be started.

It seems that two (Unix) processes are started (master and worker). The master has the docker runner threads and the worker receives requests.

**Comment by robnagler** [comment]
There also is something funky that goes on with nginx. I had to restart nginx multiple times to get it to talk to uwsgi.

**Comment by robnagler** [comment]
Thinking about this more: I suspect we are having problems with the job table being stored in process memory. I suspect with long running jobs, we will lose them when a worker is restarted. This may have been part of the reason for #1369.

We may need to store in an ACID db. Sqllite is not it.

**Comment by robnagler** [comment]
trio is supposedly better than curio. The author of trio talks about curio here: https://vorpus.org/blog/timeouts-and-cancellation-for-humans/#cancel-tokens-are-level-triggered-and-can-be-scoped-to-match-your-program-s-needs

What I like about trio is that it manages cancelation at a "global" level. This a big win if you don't actually care why something went wrong, which we don't (generally). You want to make sure the server 1) doesn't hang and 2) doesn't exit. Both of these cases need a global boundary, and we'd have to write that. Trio takes care of that for us. The rest is all just syntax: how do you start a task, how do you set a time, etc., which is always a learning curve, unfortunately.

**Comment by robnagler** [comment]
Python 3 has some nice features.  I like f-strings, for example.

async/await makes threaded code readable (again :). I'm not fond of chasing promises around. Error management is a nightmare.

**Comment by mrakitin** [comment]
Yes, we use f-strings a lot on the floor.

**Comment by robnagler** [comment]
Giving up on trio, doesn't support subprocess (or docker API).

**Comment by mrakitin** [comment]
That's sad...

**Comment by robnagler** [comment]
We are in progress with this under other tickets.
