### ISSUE TITLE
Sirepo Support for USPAS in Knoxville, Tennessee

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#1389]
There's been a request to provide support for the upcoming USPAS being held in Knoxville, Tennessee. The details are to be determined, but I wanted to make this issue to give instructors as well as our support staff an opportunity to outline the interface and server needs during the course.

Dates: January 21 - February 1, 2019

Course: Fundamentals of Accelerator Physics and Technology with Simulations and Measurements Lab

Instructors: Sarah Cousineau, Jeff Holmes, Nick Evans and Kiersten Ruisard

Please feel free to use this issue to ask general questions about the interface, report problems, or request resources.

**Comment by robnagler** [comment]
* Will Jupyter servers be required?
* What Sirepo codes will be required?
* How many students? 
* Compute time requirements per student?

**Comment by kruisard** [comment]
Thanks Rob, Nathan.

I think our computing needs will be very minimal. We're planning on using Elegant for some simple beamline calculations (maybe closed orbit, envelope calculations, etc). Labs rotate, so there will only be one group of a few students (2-4 perhaps) assigned to this lab each day. 

We haven't worked out the lab yet, but I can share the simulation file once we have a better idea.

**Comment by robnagler** [comment]
Thanks @kruisard. Just one more question: are you planning on using Sirepo or Jupyter terminals to run Elegant?

**Comment by bruhwiler** [comment]
They'll be using Sirepo.

It's not yet convenient to run elegant on a Jupyter server, because the terminal window doesn't support X and we haven't yet got a Jupyter (aka IPython) notebook workflow in place yet.

**Comment by kruisard** [comment]
Thanks all, I've got a few questions:

1) Is there any flexibility in what is displayed in the visualization tab? It seems that one plot is made per sdds output file. In some cases it would be nice to display two plots (ie, from the sigma file, one could display beam envelope on one figure and emittance tracking on another) or take advantage of the sdds processing routines (ie, plotting centroid + envelope only at diagnostic locations). 

2) I'm not sure we'll use this module, but the output from the closed orbit calculation is plotted as a heatmap rather than a line plot. Just seems like a bug.

**Comment by robnagler** [comment]
@cchall would you please take a look at this?

**Comment by kruisard** [comment]
Thanks @moellep, that's good to know! Will let you know if anything else comes up.

**Comment by cchall** [comment]
@robnagler Is there something in particular you wanted me to do?

**Comment by robnagler** [comment]
@cchall: @moellep answered above.

**Comment by kruisard** [comment]
Would it be possible to add an option manually set plot scale? We're tracking a small number of particles and you get attometer-level (sometimes zeptometer) centroid oscillations that would really be nice if it could be displayed as a straight line. 

FYI, the simulation we're using is here: https://beta.sirepo.com/elegant#/visualization/LIq0KHJG. 
In terms of computational resources, right now the longest simulations we're asking them to do is propagate 5000 particles down a 20-cell FODO transport line to look at matching/mismatch.

**Comment by kruisard** [comment]
Re my last comment: Oops, realized I should probably @ someone; @robnagler @moellep

**Comment by moellep** [comment]
I've opened a new ticker #1447 for setting the plot scale. This should be implemented by early January.

**Comment by robnagler** [comment]
Since #1447 is open. We have enough backends configured for now, and we have spare capacity we can apply in an emergency.
