### ISSUE TITLE
isExample "1" vs true

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1399]
Some old users may have example simulations marked as "isExample": "1", rather than "isExample": true. This will cause the example to be duplicated when pkcli.admin create_examples() is run. Deleting the "isExample": "1" simulations on the back-end would fix the problem as users aren't allowed to delete examples.

**Comment by robnagler** [comment]
Is this still an issue?

**Comment by moellep** [comment]
I verified there is still data like this on production. Deleting the affected files and running "admin create-examples" would fix the problem.

**Comment by moellep** [comment]
Fixed with #2277
