### ISSUE TITLE
dipole source tab needs to provide 'flux through finite aperture' report

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#14]
The "flux through finite aperture" plot available for the undulator source should also be available for the dipole source.

In both cases, the title should be changed to "integrated spectrum"

**Comment by bruhwile** [comment]
First, Oleg will create a Python script.

**Comment by bruhwiler** [comment]
There is no longer a "flux through finite aperture" plot, so I believe this issue has become irrelevant.
