### ISSUE TITLE
plot overlay enhancements

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1400]
The plot overlay could be improved in a few ways:

* The FWHM feature should be turned off for most plots. Wavefront plots could ask this to be turned on in the report data from the server.

* The "X = ..." part should allow the plot to use a different value. For example, on the twiss parameters report, if "Horizontal beta" is selected, it could show "βx = 47.398m" instead of "X = 47.398". Including the units would be good as well.

![screen shot 2018-10-26 at 5 26 55 pm](https://user-images.githubusercontent.com/6516910/47596578-7a708c80-d944-11e8-8917-61ca524f7c74.png)

- [x] Plot-specific labels
- [x] Include units
- [x] Narrow use of fwhm
- [x] Copy to clipboard should have similar format

**Comment by mkeilman** [comment]
I'll take this one and #1401
