### ISSUE TITLE
SRW-light no longer in use

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1415]
@mrakitin @ochubar We are switching to use https://github.com/ochubar/SRW for Docker image builds. Some of the context is in https://github.com/radiasoft/devops/issues/160. Therefore, SRW-light will no longer need to be updated. 

I compared master of SRW-light and SRW and they are in sync so there shouldn't be any problems with this, just less work.

This is not yet on alpha, but it will be on Jupyter.

**Comment by robnagler** [comment]
Just for informational purposes, closing.

**Comment by mrakitin** [comment]
Thanks for the update, @robnagler! Please archive the SRW-light repo, so we cannot push to it anymore to avoid possible future confusions.

**Comment by robnagler** [comment]
Archived SRW-light.

**Comment by mrakitin** [comment]
The only inconvenience now is that the [SRW conda-package](https://github.com/NSLS-II/lightsource2-recipes/blob/master/recipes-tag/srw/meta.yaml#L8) (`lightsource2-tag` channel) should be build based on ochubar/SRW, which does not have any tags (with SRW-light I created a few tags to easier track code updates).

Also, there was 1 open PR and 6 open issues in SRW-light. Not sure we want to ignore them or not.
