### ISSUE TITLE
Sirepo: the problem on the surface error simulation

### ISSUE THREAD

**Issue by yangfg-bsrf** [radiasoft/sirepo#1417]
Hi, now I am simulating a very simple system: undulator-KB mirror-Detector, with the KB mirrors are given same surface error. For the single electron case, the detected vertical and horizontal profiles are different. In my opinion, they should be same. And I also compare the results with other tools. These work  indicate the problem may come from the Sirepo, would you please check it ? 
![problem 2](https://user-images.githubusercontent.com/41823786/47960485-b38db880-e038-11e8-8f9b-a9bbcbece88f.png)

**Comment by bruhwiler** [comment]
@goxrt -- thank you for reporting this issue.

Please provide a URL to your simulation, so that we can copy it and quickly diagnose the problem.

**Comment by goxrt** [comment]
@bruhwiler Hi, here is the URL:
https://beta.sirepo.com/srw#/beamline/o07ALkK4

**Comment by bruhwiler** [comment]
@moellep -- when I execute this simulation (chrome on Win10) I get a "bad gateway" error for the Watchpoint at 41 m.

![image](https://user-images.githubusercontent.com/3825435/47961162-f5801580-dfca-11e8-90ec-ef4c79f91543.png)

I can't diagnose the problem until this error is resolved.  Could you please have a look?

**Comment by moellep** [comment]
@bruhwiler I've found a problem in the "reproduce simulation" feature and opened ticket #1418. I copied the missing file to your nT5pXu80 simulation, so it should run OK for you in the time being.

**Comment by moellep** [comment]
@goxrt - I've found if you increase the Sampling Factor value from 1 to 2 on the "Initial Wavefront", the results look more symmetric.

![intensity-watchpoint-report-41m-2](https://user-images.githubusercontent.com/6516910/48010405-c48f0600-e0da-11e8-9a7e-29137637aca8.png)

**Comment by goxrt** [comment]
@moellep thanks for your work. would you please tell me how to determine the reasonable value for this factor.

**Comment by bruhwiler** [comment]
@goxrt -- at some level, it is up to the user to consider modification of the propagation parameters, if the observed simulation results appear suspicious.  The Sirepo GUI makes it easy to use SRW; however, physical optics remains a challenging domain and users are required to have some physical understanding of the processes that they are modeling.

That said, we do plan to continue improving and automating the choice of propagation parameters.

@bnash  --  do you have more to add?
