### ISSUE TITLE
warp - particle report striping

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#142]
Warp particle report show striping, possible due to problems with the histogram binning.

**Comment by bruhwile** [comment]
The striping seems to be primarily along the z-axis, so maybe a 1D
smoothing along that axis would solve the problem.
For example, the Python snippet here might be helpful

http://stackoverflow.com/questions/13476807/probability-density-function-from-histogram-in-python-to-fit-another-histrogram


However, I think it would be more accurate and more robust to treat each
particle as a rectangle, with a width equal to the bin size along each
axis. You could then allocate the fractional areas to whatever bin they
overlap. I'm pretty sure this would solve the problem.

David


On Fri, Apr 1, 2016 at 4:54 PM, Paul Moeller <notifications@github.com>
wrote:

> Warp particle report show striping, possible due to problems with the
> histogram binning.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/sirepo/issues/142>
>



-- 
David Bruhwiler
RadiaSoft LLC
+1 (720) 502-3928

**Comment by moellep** [comment]
The striping appear to happen because warp fills the plasma along fixed z
points and then bends them around during the simulation. Attached is a
scatter plot example, zoomed into the very far right of the plasma before
the beam gets near it. Farther to the left the graph looks good because the
points have been pulled off the line, but the far right appears with
striping unless the histogram bin matches the interval. Adding to the
problem is the number of bands increases over time, so the first frame has
far fewer bands, so setting a fixed histogram bin size doesn't look good
for the initial frames. Smoothing each point over the z axis should fix the
problem, but will blur the graph.

[image: Inline image 1]

**Comment by bruhwile** [comment]
Those are valid points.
I know the OpenPMD developers have struggled with this.

If one used the field mesh to create the particle histogram (don't give the
user any choice), and used my previous suggestion of treating the
macroparticles like square regions, so that they could be correctly
allocated proportionally to nearby squares, then I'm pretty sure this
problem would go away. This is essentially what's being done to create the
rho field plots, and you never see the striping there.

Best,
David

**Comment by robnagler** [comment]
I don't see the image. May need to upload via Issues UI?

I'm confused about how to set the grid size per Paul's recommendation:

> The histogram would need a different bin size for each frame - initially the range is small, so the bin size would be smaller than the grid size, then later when the full range is in the frame, the bin size should match the grid size. For a good image, let the simulation run through a long piece of plasma (like 1 mm, not the 0.25 default) and take the screen shot farther into the simulation, like iteration 600. 
> For the Electron Beam Animation, the bin size should be about 1/3 as big as the Plasma Animation bin size because it covers a smaller area. Or better yet, use the x/y, not x/z view for the beam animation.

Should the Domain Size be .33? Or do I use absolute grid?

**Comment by moellep** [comment]
I think you can set the histogram to domain_width / grid_width for now, as
long as you are 10 or so frames into the animation.

**Comment by robnagler** [comment]
I'm totally missing this. I don't see anything called "domain_width/domainWidth" or "grid_width" in the run dir or repo. I see Domain Size for R (4) & Z (2). What am I missing?

Also, I think "Frames per Second" is really iterations per frame.

**Comment by moellep** [comment]
Set the histogram bins to the "Z, number of cells" value from the
simulation grid for now. I'm looking into removing the histogram bins
completely and just setting it dynamically on the server.

**Comment by moellep** [comment]
I've got a good enough work-around for the problem now. The main problem
was the x-range on the warp file would change over time - short at the
beginning and end, and at the grid window in between. If the data gets zero
padded (on the left in the beginning and on the right for the end) and the
bin size is set to the zCount, then it looks good the whole time with no
striping.

The laser report looks horrible now that weighting is turned on.

**Comment by bruhwile** [comment]
Further improvements can be addressed in a new issue.
