### ISSUE TITLE
Stop job after timeout

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1435]
If the job takes too long to run, it should stop. Integrate with pkconfig so can pass environment vars.

**Comment by njsmith** [comment]
By "stop" do you mean "we issue a `docker stop`", or something else?

Who sets the timeout? Is it a field in the job request, a piece of global configuration, ...?

How are environment variables connected? Do we want to pass an envvar into the job so it knows what its timeout is?

**Comment by robnagler** [comment]
Partially implemented. Needs to send kill to remote process.

**Comment by robnagler** [comment]
Timeouts need to be adjusted for OP_ANALYSIS vs OP_RUN (sequential). Configuration should probably be max_hours.parallel/sequential/analysis. We don't need to deprecate the old configuration, just rename it. @e-carlin please take care of this, and add a case to job_timeout test. You may need to hack myapp to have a long analysis.

BTW, sequential is what background import uses (srw python). Since we execute arbitrary code in other cases, it's probably not as big a deal now that arbitrary code is always contained.
