### ISSUE TITLE
Changes for #1400 make y-axis label appear when it should be empty

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#1437]
The axis object associated with the focus point is the same as the one on the plot, so when the formatting occurs for the popup it happens for the plot as well.

**Comment by robnagler** [comment]
Let's not introduce the label complete. If something is complete, it should be closed. Can we close this?

**Comment by robnagler** [comment]
If it is a pull request, then just bind to the Issue with: Fix #N.
