### ISSUE TITLE
Allow app to stop jobs if running else ignore

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1438]
There needs to be a separate queue to stop jobs. Maybe call this `seq:job_cmd`, because there will be other commands (status). The status of the job should be set to `canceled`.

**Comment by njsmith** [comment]
This isn't a question, but just to note: we'll want to keep an eye on whether defining our own ad hoc RPC protocol over Redis remains simpler than adopting something prebuilt.

**Comment by robnagler** [comment]
Please suggest prebuilt RPCs.

**Comment by robnagler** [comment]
grpc is not right. We are working with Python only so anything that binds to Python-only is likely to be better/simpler. 

All messages are asynchronous, because we don't want the server blocking or holding state (unnecessarily). Any synchronous requests are directly to Redis, e.g. checking job status. Starting and stopping jobs is asynchronous.

The model of message passing most closely resembles Celery, but with Celery, we have too much overhead and not enough control.

**Comment by moellep** [comment]
Reopening this, mis-typed #1438 and #1428

**Comment by robnagler** [comment]
We are no longer queuing stops, just handling them via the server.
