### ISSUE TITLE
Support multiple docker hosts

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1441]
Configure a list of hosts using pkconfig just like [init_class](https://github.com/radiasoft/sirepo/blob/a64e277a9b3cd0e223bbb2e51aa452b10795bfa8/sirepo/runner/docker.py#L218) does now. You could just take all the slot initialization code verbatim.

**Comment by njsmith** [comment]
Can you elaborate on what the scope here is?

I assume that eventually we'll need to:

* Load the list of docker hosts from configuration
* Run a job on a selected host
* Track which host a job is running on, so status and cancellation operations can be directed appropriately
* Track the aggregate status of each host (e.g. how many jobs its running)
* Implement some scheduling algorithm that uses the above features to automatically assign jobs to hosts (also taking into account user account limits, sequential vs parallel, etc.)

Which parts of that are included here? There's a lot of code in that `docker.py` file and it isn't immediately obvious to me how it breaks into pieces...

**Comment by njsmith** [comment]
OK, cool. I just want to be careful not to overpromise for SOW1, since there are a lot of unknown unknowns associated with getting started and plumbing the scheduler and sirepo together. But if the scope in this issue is literally just "plug in the existing code", and we're going to wait until the next round to worry about stuff like robust multi-machine testing infrastructure and smoothing out any unexpected issues with slot scheduling, then that's fine.

**Comment by robnagler** [comment]
Good to be cautious. We don't need robust testing at this stage. Indeed, I'm willing to drop testing if we can get an end-to-end going.

**Comment by robnagler** [comment]
I have a fun time debugging multi-host docker execution with [rsdockerspawner](https://github.com/radiasoft/rsdockerspawner) for JupyterHub. There are big differences between the TLS implementation between the Go client (presumably a Go lib) and Python library (openssl). Things that work on the command line, don't work with openssl, e.g. self-signed certs as CAs and a CA can't have the same CN as the cert it is signing. Debugging urllib3 is hard, because error messages contain no information, and the docker daemon seems to report errors from the client in the server logs, which caused further confusion.

CA certs generated by [rsconf.component.docker](https://github.com/radiasoft/rsconf/blob/50eecd15656b037d147b70e77ade45ad0c6ec060/rsconf/component/docker.py#L101) work now. There's a command line utility, which can be used.

**Comment by njsmith** [comment]
BTW, this may be irrelevant if you already have it working, but using the openssl command line tools to work with certs is miserable, and the [cryptography](https://github.com/pyca/cryptography/) library lets you do it in-process with a real API. (This is how [trustme works](https://github.com/python-trio/trustme#cheat-sheet).)

**Comment by robnagler** [comment]
trustme seems handy. Thanks for letting me know.

**Comment by robnagler** [comment]
With celery, we can add and remove workers dynamically. This is a convenient feature, which we shouldn't lose. Now, restarting the runner is not a big deal if it can recover its state (has to), but it seems like it would be easier if the workers "checked in" dynamically and periodically. With RSDockerSpawner, it also works well enough to restart JuptyerHub. That has clear advantages, too.
