### ISSUE TITLE
Automate multi-host Docker execution

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1442]
RSConf automates this already, but not for development. We'll either have to integrate in RSConf or copy some of the code (probably preference). I'd say we should write curl installer that works on Linux or a Mac. One issue I've found is that running Docker on a multiple VMs on Darwin causes hangs. We may have fixed this with https://github.com/radiasoft/download/commit/cf0744baf24aa920f8b25c4bb0fc5bd38f62a6af but I'm still using a Linux box in the cloud. We can provide this if need be, because it's more stable.

**Comment by njsmith** [comment]
I think I understand the issue title, but I don't understand most of the issue body :-)

**Comment by robnagler** [comment]
You don't have to worry about Darwin, since your run Linux. :)

RSConf is configuration management system, whose [design is focused on our problems](https://github.com/radiasoft/rsconf/wiki/Design).

RSConf has a [multi-VM installer to develop itself](https://github.com/radiasoft/rsconf/wiki/Development).

You and I will work together to build a multi-host (VM) environment to start let's say three worker VMs and one controlling VM (that runs the runner service). This will entail configuring Docker on each host with TLS, gathering certificates for the runner, and then starting the runner service. This can be done via RSConf. 

I'll probably do all this work, but I wanted it included, since it's important for first SOW.

**Comment by njsmith** [comment]
So is this issue about scheduler support for automatically assigning jobs across multiple docker hosts, or about automatically setting up test environments that contain multiple docker hosts?

**Comment by robnagler** [comment]
Automatic test environs

**Comment by robnagler** [comment]
Could be added to run-supervisor.sh which currently does this for sbatch.
