### ISSUE TITLE
JSPEC - report returns "502 bad gateway"

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1449]
https://beta.sirepo.com/jspec#/source/EIxjhUIU

![image](https://user-images.githubusercontent.com/3825435/48983249-a731d400-f0a9-11e8-9e4b-7b2031fecd44.png)

Problem reported by beta testers.
I see it also.

**Comment by robnagler** [comment]
rabbitmq died. Not sure why, because journald was dead. 

There is 80% disk space on root so there's enough room. The journal.export failed last night, too. 

I'll add a check for journald on patrol.
