### ISSUE TITLE
JSPEC - questions regarding "Rate Calculation" report

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1452]
This is in regard to the example simulation:  "200 Ge V proton ibs"
My copy can be found here, https://beta.sirepo.com/jspec#/source/EIxjhUIU

This is the report that I find confusing:
![image](https://user-images.githubusercontent.com/3825435/48983613-3c36cc00-f0ae-11e8-942b-4517605c28db.png)

@moellep  --  why are their two rows with the same label and the same values?

@ilyapogorelov  --  can you please check whether it is correct for the cooling rates to all be zero?

**Comment by moellep** [comment]
I've verified the UI is showing the results from the simulation. For some reason in this case the electron cooling line is duplicated. The input twiss parameters seem pretty large - with the beta spiking up near 2500m. Is that a normal input file?

```
$ jspec jspec.in
Bunched ion beam created!
Ring created!
Electron beam created!
Cooler created!
IBS rate (1/s): 2.013e-03  -8.715e-07  2.141e-04
Electron cooling rate (1/s): 0.000e+00  0.000e+00  0.000e+00
Electron cooling rate (1/s): 0.000e+00  0.000e+00  0.000e+00
Total expansion rate (1/s): 2.013e-03  -8.715e-07  2.141e-04
```

**Comment by bruhwiler** [comment]
@ilyapogorelov  --  please export the files from this simulation and run it on the command line. Also, please have a look to see if the specified Twiss parameters are reasonable.

@moellep  --  please confirm whether this is a standard example for Sirepo/JSPEC.  If so, we need to make sure it has reasonable inputs.  If not, then I will delete it from my workspace.

**Comment by moellep** [comment]
The "200 Ge V proton ibs" isn't an an example simulation - but don't delete it or it will @ilyapogorelov will loose the link you provided in this ticket. One way to determine if a simulation is an example is if it appears in blue on the Simulations list. User simulations appear green:

![screen shot 2018-11-26 at 9 14 53 am](https://user-images.githubusercontent.com/6516910/49026869-27b10d00-f15c-11e8-971a-027b0079f077.png)

Also, if you select the drop down, user simulations have a "Delete" option, but example simulations do not.

**Comment by ilyapogorelov** [comment]
Will do.

**Comment by ilyapogorelov** [comment]
Hi David,

When I ran this example from the command line, I got the same output for
the rates as you got.  I think this is because the electron beam current is
set to zero.  With non-zero current, the electron cooling rates come out
non-zero, both in sirepo runs and command-line runs (although it's hard to
tell if the magnitudes are correct).  Regarding the Twiss parameters for
the lattice, the betas do look a bit crazy to me, staying at several
hundred meters for much of the lattice with the max beta ~2000 m and going
from .1 m to 2100 m over just 10 m traveled distance early in the lattice.

- Ilya

**Comment by bruhwiler** [comment]
OK, it seems to be a bad example, so I'll delete it.  Sorry for the bother.
I'll look to see if the double row appears whenever the current is set to zero.
Thanks!

**Comment by bruhwiler** [comment]
I think zero current is a legitimate choice, for which the cooling rate should be zero.
This is essentially a simulation of what happens when you turn the cooling system off.

**Comment by ilyapogorelov** [comment]
Well, zero current basically means that there is no electron beam that
otherwise would be used to cool the ions, so it's the same situation as not
cooling the ions.  Physically, nothing wrong with it.
