### ISSUE TITLE
warp.py.jinja: diag_period = {{incSteps}}?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#146]
I think diag_period has to be {{incSteps}}, because diag_period is the HDF5 file writing period. The graph doesn't update with diag_period = 50 and incSteps = 20.

**Comment by bruhwile** [comment]
Is this still open?

**Comment by robnagler** [comment]
Yes, it's a simple change, but I didn't know if should be made or not.

**Comment by bruhwile** [comment]
I suggest that incSteps should be rounded down to the nearest integer which
satisfies the condition.

**Comment by robnagler** [comment]
I just set `diag_period` to `incSteps` for fix f9819f786a97e363545c244233ca8ff95feb091e. Both diagnosticPeriod and incSteps are constants (50) in [template/warp.py](https://github.com/radiasoft/sirepo/blob/f9819f786a97e363545c244233ca8ff95feb091e/sirepo/template/warp.py#L237) so I thought it would be better to explicitly couple the value in warp.py.jinja.
