### ISSUE TITLE
SRW: unexpected error 

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#1466]
We create a Gaussian source, propagate it to the waist and then do an additional propagation.
We find that at the final watchpoint, one gets the message "unexpected error (see logs)"
How can I look at the logs to understand what is going on here?
The simulation URL is:
https://beta.sirepo.com/srw#/beamline/otJrLH7k
![unexpectederrorsrw_screenshot](https://user-images.githubusercontent.com/1112276/49772847-eb2cf780-fcab-11e8-8f68-be12a222dca9.png)

**Comment by robnagler** [comment]
The error at watchpoint4 is:

```txt
Gaussian beam electric field calculation ... completed (lasted 0.04 s)
Extracting intensity and saving it to a file ... completed (lasted 0.39 s)
Propagation ... terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

The parameters.py files is attached. You can run it, but you need to add a `main()` at the end of the file.

[parameters-py.txt](https://github.com/radiasoft/sirepo/files/2665674/parameters-py.txt)

**Comment by robnagler** [comment]
I suspect the output is invalid or at least partially complete. There's an allocation error. @ochubar wrote us privately, and I suspect when you don't set the parameters properly, you could get an allocation error.

**Comment by bnash** [comment]
The solution proposed here by @ochubar was to change the propagator for the drift from "0-Standard" to "3-From Waist".  If one makes this change directly, there is still an error, because auto-resize is still set which fails at a waist.  In addition, the auto-resize before and after propagation parameters are grayed out and cannot be changed.  I think that auto-resize should be automatically turned off if "From Waist" is selected, or at least one should have the option to turn those off.

**Comment by bruhwiler** [comment]
@bnash -- please create a separate issue regarding the automatic handling of "auto-resize" in special cases

The "from waist" situation is more difficult to address in the GUI.  Can we add some logic that detects a waist or near-waist condition and automatically changes the corresponding propagation parameters from "standard" to "from waist" ...?   If so, you could create a new issue on that topic.

**Comment by bnash** [comment]
@bruhwiler , yes, I'll create the issue for turning off "auto-resize" when using "From Waist" propagator.

For your point about identifying a near waist condition, we'll think about how hard that would be to implement, and then create an issue if it looks feasible.
