### ISSUE TITLE
making a copy should fail if there are too many (100) copies

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1471]
[copy should fail](https://github.com/radiasoft/sirepo/blob/82bdc848899a8d7bcd5e1ae73f91ca37d88f647c/sirepo/server.py#L115) if there are too many existing copies.

**Comment by mkeilman** [comment]
I've been looking at this and have a few questions:

1. How does one send a copy request without a name?  It does not seem like we can get to the highlighted code through the web interface
2. The client side does its own copy numbering which is different than the server ('<name> <count>' [or '<name> (<count>)' if you force it] vs. '<name> (copy <count>)'. Is there a preference?
3. The client counts occurrences of the name in a folder, while the server counts globally. Is there a preference here?
4. Would it be better to catch on the client so the user can't request such a copy in the first place?
