### ISSUE TITLE
NERSC NEWT agent prototype

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1472]
- [x] Use NEWT to connect to NERSC
- [x] See if sbatch process can report back to a public server
- [x] Interactive queue test
- [x] Batch queue test

**Comment by robnagler** [comment]
I've been playing around with NEWT. The API is missing a few things like mkdir and run a command with args. However, we can run a command without args, and then it can create ~/.sirepo, which we'll use for storing state. I'm running a test to see how long a process can run in background while polling an external server. If that works for a while, we can use that to start an agent that pings our servers when status changes in the queue for our jobs.

**Comment by robnagler** [comment]
@ncook882 ran the test script (new.py below).  The script creates `~/.sirepo` in the user's home with a command called `~/.sirepo/run`. When `run` is executed via NEWT's `command` API, it looks for a file `~/.sirepo/run-todo`. It renames it to `~/.sirepo/run-doing` and executes it, returning the output. This ran successfully on @ncook882's environment, even though sirepo-bootstrap was installed in my environment. 

The detached command is still running in my environment so I think we can reliably use an "agent" like this to check the queue for the user. This will run "for a while" so we can keep the state of the job up to date. If a user checks status, and the command hasn't reported back in a while, we can prompt the user for their NERSC credentials again, and restart the agent. This probably would only need to happen once a day. This will allow us to start jobs without continually asking the user for credentials.

Also tested that a job can "curl" back to the server periodically so we can have both an agent checking the queue and the job reporting back its status. The agent running inside the job will be the most reliable when a job is actually running. 

* [newt-py.txt](https://github.com/radiasoft/sirepo/files/2704526/newt-py.txt) talks NEWT protocol
* [sirepo-bootstrap-sh.txt](https://github.com/radiasoft/sirepo/files/2704528/sirepo-bootstrap-sh.txt) is installed on cori to setup ~/.sirepo
* [detach-sh.txt](https://github.com/radiasoft/sirepo/files/2704529/detach-sh.txt) sample "agent" program that detaches from session and tty that can send back status to the server.

**Comment by e-carlin** [comment]
I've built a centos7 vm with Slurm installed. I can submit sequential jobs through the job_agent and monitor their progress.

**Comment by robnagler** [comment]
We had a successful run of warppba on a single node with ntasks=4 on cori.nersc.gov:

![Screen Shot 2019-12-03 at 7 58 11 PM](https://user-images.githubusercontent.com/5495179/70108787-58494380-1607-11ea-99f8-81c20ea94dbb.png)

When run with 32 cores, it gets an error and hangs:

```txt
Multigrid2d: Error converged to   6.594E-07 in    43 v-cycles
```

@e-carlin it was h5py that was not importing correctly due to LD_LIBRARY_PATH being edited by shifter. We have to put /usr/lib64/mpich/lib in the path after shifter's.

**Comment by bruhwiler** [comment]
This seems like a major step forward -- congratulations!

**Comment by robnagler** [comment]
Ran Youngs on NERSC with 128 cores (4 nodes) in debug queue. Took a long time to start, but only took 15 minutes to run:

![Screen Shot 2019-12-04 at 3 47 53 PM](https://user-images.githubusercontent.com/5495179/70189346-4d96b900-16b0-11ea-9e17-02adc4fb902b.png)

**Comment by moellep** [comment]
🎉🎉🎉

**Comment by robnagler** [comment]
Working. Using ssh, not NEWT.
