### ISSUE TITLE
add BNL postdoc link to sirepo.com

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1473]
Our collaborators at Brookhaven National Laboratory have a postdoctoral position that will enable you to join a world class X-ray optics team and also become a Sirepo developer -- we encourage you to apply!
https://jobs.bnl.gov/job/upton/post-doctoral-associate-simulation-of-experiments-nsls-ii/3437/9350753

Please add the above text and link to the lower-left corner of the Sirepo landing page, https://sirepo.com

Please do the same for the Sirepo/SRW landing page, https://sirepo.com/#/srw
In this case, you can place it between the green bar and the first line of text (with an appropriate separator).

**Comment by mkeilman** [comment]
Is this to be an ongoing section like "opportunities" or the like?

**Comment by robnagler** [comment]
Let's do a one off and see what happens.

**Comment by mkeilman** [comment]
Something like this?

![screen shot 2018-12-17 at 1 50 07 pm](https://user-images.githubusercontent.com/30352290/50114913-1a3eee00-0203-11e9-8bd9-ca923cff0493.png)

**Comment by bruhwiler** [comment]
That looks good.
Minor quibble -- please prevent "X-ray" from wrapping. 
It needs to be seen as a single word.

**Comment by bruhwiler** [comment]
The issue has been closed, but the text is stuck on alpha and has not yet appeared on the beta page.
I assume this will be addressed on Monday, when Paul is back from vacation.
