### ISSUE TITLE
runner.process manages api_runSimulation/Status/Cancel end-to-end

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1482]
runner.process manages api_runSimulation, api_runStatus, api_runCancel end-to-end.

NOTE: the implementation will be 100% backwards compatible. We'll be able to test runner.process in parallel with runner.background. There will need to be some code in runner that controls the code in server.api_run*.

Relates to #1481.

**Comment by robnagler** [comment]
Work on NJS-SOW1 surfaced the problems we've known about: idempotent job ids and status management.  [server._simulation_run_status](https://github.com/radiasoft/sirepo/blob/c166c611c658bf1df00d11483ce5a92e807f00a9/sirepo/server.py#L831) is too complicated, and needs to be replaced with race-condition-free start/cancel/status ops. The prototype server supports this, but needs work on the control flow and some live testing in development, i.e. runner.background goes away in place of process runner.

**Comment by njsmith** [comment]
As part of this we'll also add the "background runner" functionality to the runner daemon, with an eye towards eventually switching over to using the runner daemon for development.
