### ISSUE TITLE
warpvnd: 3d conductor editor should allow moving conductor in y dimension

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1498]
Currently, in 3d mode, the conductor editor lets you move around items in the x/z grid. The lower grid should allow moving around items in the y/z grid (in green below).

![screen shot 2019-01-17 at 3 11 44 pm](https://user-images.githubusercontent.com/6516910/51352294-6bdcd180-1a6a-11e9-92e3-bd6646f10138.png)

**Comment by mkeilman** [comment]
I presume we also need to check the shape crossing grid lines when moved...
