### ISSUE TITLE
requests-oauthlib conflict with Flask-OAuthlib

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1507]
I thought this was fixed in https://github.com/requests/requests-oauthlib/issues/359, which worked in my dev env, but the sirepo build is failing:

```txt
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (oauthlib 3.0.1 (/rscontainers/sirepo/.eggs/oauthlib-3.0.1-py2.7.egg), Requirement.parse('oauthlib!=2.
0.3,!=2.0.4,!=2.0.5,<3.0.0,>=1.1.2'), set(['Flask-OAuthlib']))
```

**Comment by funcelotwork** [comment]
@robnagler why you closed this issue? some changes?

**Comment by robnagler** [comment]
@funcelotwork we just worked around it by hardwiring requests-oauthlib==1.1.0.
