### ISSUE TITLE
Toroid mirror bug in aperture

### ISSUE THREAD

**Issue by fish0909** [radiasoft/sirepo#1515]
Hello,

There is an error  happened when I tried to use toroid, from the python codes it shows the problem is the shape of aperture e or r should be a string type instead of float in the code.

One more question , could you please tell me which SRW version is used in SIREPO?

Thanks in advance.

**Comment by moellep** [comment]
Thank you for letting us know about the Toroid mirror bug. Another user had also encountered this and fix #1503 will be available early next week.

We use the most recent SRW version available from [ochubar/SRW](https://www.github.com/ochubar/SRW)
