### ISSUE TITLE
how to organize Height Profile Data File 

### ISSUE THREAD

**Issue by zhanglin** [radiasoft/sirepo#1518]
how to organize Height Profile Data Files?  I would like to clean up the fold to REMOVE some files.

Thanks,
Lin

**Comment by mrakitin** [comment]
Do you have your own installation of Sirepo or are you talking about the public server at https://beta.sirepo.com?

**Comment by zhanglin** [comment]
I’m talking about public server.

If I can have my own installation of Sirepo on my desktop, that’s great. Could you give some guidance for my own installation ?

Thanks,

Lin

**Comment by mrakitin** [comment]
You can remove unused mirror profile files via the corresponding menu of any mirror optical element, e.g.:
![image](https://user-images.githubusercontent.com/13209176/52231136-27816c00-2887-11e9-9a38-10eaaff27247.png)

Just click the `x` button in the drop-down menu. Does it answer your original question?

As for the local installation, please refer the instructions at https://github.com/radiasoft/sirepo/wiki/Development for your operating system.

**Comment by zhanglin** [comment]
It’s a bit too complicated for the own installation ☹

I have another question: in mirror profile, there are two boxes Horizontal Transverse Size [mm] , Vertical Transverse Size [mm]
Should these two numbers be consistent with the bounds of X and Y in the mirror profile file ?

Lin

**Comment by mrakitin** [comment]
According to the logic in [this SRW function](https://github.com/ochubar/SRW/blob/348c06ea6b553788d1e18f2c98669ece3d1cf5f9/env/work/srw_python/srwlib.py#L4489-L4617), used for construction of the corresponding transmission object, the height profile data will be re-scaled to the specified horizontal and vertical sizes (if they are positive).

**Comment by robnagler** [comment]
To install Sirepo on your desktop, please [follow these instructions](https://github.com/radiasoft/sirepo#manual-install-with-docker). It's a lot simpler than the development instructions.
