### ISSUE TITLE
multiple access to SDDS file causes read failure

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1523]
Currently sirepo apps for elegant and jspec use the sddsdata module to read output files. I've observed cases where simultaneous requests into different files causes the reads to either fail, or return incorrect data.

I think this is due to the sddsdata implementation which uses an index into a global data set which is shared across threads. In sirepo, the index is currently always set to 0. It looks like only 20 slots are available, so the resource would need to be locked in any case.

Implementation details can be seen here:
https://github.com/epicsdeb/sdds/blob/master/extensions/src/SDDS/python/sddsdatamodule.c

Sirepo only uses a small subset of the SDDS commands - it might be easiest to write a new python wrapper which tracks the data on an instance variable, rather than in a global array.

**Comment by moellep** [comment]
I wasn't able to reproduce the problem on beta, but below is a test case which reproduces it pretty reliably on dev.

https://beta.sirepo.com/elegant#/source/oyLrrTaO

Running the simulation on the Visualization page should cause one or more reports to fail when reading the SDDS data. It might take multiple runs to reproduce the error.

![screen shot 2019-02-12 at 12 09 58 pm](https://user-images.githubusercontent.com/6516910/52661381-2a034780-2ebf-11e9-9411-deea3a380f81.png)

**Comment by robnagler** [comment]
No longer issue job_cmd runs commands sequentially and as a separate process.

**Comment by moellep** [comment]
This is still a problem on dev and python3 seems to make it worse - possibly the timing is faster. I'll look at a work-around for dev (not always running with sdds index 0). An example, running jspec with python3 in dev, the "page not found" error happens about every-other frame on the Booster Ring example.

**Comment by robnagler** [comment]
simulation frames should run in a separate process so it's not that. I'm also sure that on master, there's only one "OP_ANALYSIS" going on at at time (there are two queues).

**Comment by moellep** [comment]
This happens on dev where everything is running in flask. With python3, the processing was different and sdds calls were clobbering each other. I added a work-around to the py3 branch.

**Comment by bruhwiler** [comment]
@moellep -- can this issue be closed?

**Comment by moellep** [comment]
This issue is still open on the master branch. There is a work-around in place on the py3 branch which will get merged in.

**Comment by moellep** [comment]
Fixed with 9bec55b
