### ISSUE TITLE
Sirepo SRW Beta Down

### ISSUE THREAD

**Issue by twguest** [radiasoft/sirepo#1524]
Hi All,
I'm currently experiencing issues running any of the provided srw examples on beta.sirepo.com/... .
Is there a particular reason for this failure?

**Comment by bruhwiler** [comment]
Hi @twguest -- thanks for reporting this issue.
I've tried a couple and they are working for me.

Can you please provide the URL for a simulation that is failing?

We will try to resolve this problem within 24 hours.

**Comment by twguest** [comment]
Hi @bruhwiler, @robnagler 
I'm currently having issues executing the following: 

https://beta.sirepo.com/srw#/source/t8OoEE7X

I am not having an issue in running this script on alpha: 
https://alpha.sirepo.com/srw#/source/7kN6XNbg

Thanks

**Comment by moellep** [comment]
Hi @twguest 

We've corrected the problem and you simulation should now run normally on beta.
