### ISSUE TITLE
Cylindrical Mirror  Auto-Compute function

### ISSUE THREAD

**Issue by faissaltbox** [radiasoft/sirepo#1529]
Dear All,

I am setting up a beamline which uses a cylindrical mirror, and would need first to understand the appropriate parametrization. 

1/ A look on the available systems on SIREPO shows that LCLS-SXR , for example,  has a **horizontal reflection plane** (in the **height profile** tab) with setting at "**Auto-Compute vertical** vectors" (in the **orientation** tab), while, for example, NSLS-II-FMX , has a cylindrical mirror that has also a **horizontal** plane of reflection, but this time, with an auto-compute set to **horizontal**, unlike LCLS-SXR.  

2/ In addition of auto-compute vertical and horizontal, there is the option of auto-compute "none". Is there a purpose for that functionality? Wouldn't it then ignore the grazing angle?

3/ If I chose a define "auto-compute", it seems that the output does not depends on whether the chosen plane of reflection is horizontal or vertical. VPR and HPR give me the same plot when the auto-compute section is the same (EDIT: only for small radius of surface curvature apparently)

4/ More generally, is there a sensible way to decide which option is the most appropriate in each case? When just trying different combination is is easy to end up with configurations where, instead of focusing the photon beam, one ends up with size that scales in meters (which is obviously wrong). This is particularly true when the cylindrical mirror has a very small radius of curvature. This suggest that the "radius of curvature" is actually describes actually the longitudinal curvature, and not the cross section, is it so?

Like for example, if I wanted a vertically focusing half-cylindrical mirror of 8 cm radius, I would take 8cm sagittal x 8 cm tangential x radius of curvature of 1e+5, is this correct?

thank you,

- Faissal

**Comment by robnagler** [comment]
Thanks @faissaltbox. Someone will help you shortly.

**Comment by faissaltbox** [comment]
Hello,

I am also wondering another question:

in NSLS II -FMX, we can see that the spot before propagation is (+/-200 )*(+/- 200), but after the HFM, the spot is actually..larger?? This gets me a bit confused on how the cylindrical mirror actually achieves the squeezing in one direction, as it should be normally expected. 

thanks again

**Comment by bnash** [comment]
Hi @faissaltbox, thanks for the question.  I'm looking into this.  I should be able to get back to you on this tomorrow.
Regards,
Boaz

**Comment by faissaltbox** [comment]
thanks @bnash for looking into this issue

regards,

- Faissal

**Comment by bnash** [comment]
Hello Faissal, just to let you know I haven't forgotten about this.
I wasn't previously so familiar with this logic for setting the mirror parameters, so I'm reading the code, and hopefully can be helpful.

The ellipsoid mirror is represented by the python object SRWLOptMirEl (defined [here](https://github.com/ochubar/SRW/blob/master/env/work/srw_python/srwlib.py)).  The normal vector is determined by the parameters _nvx, _nvy, and _nvz, which come from op_KBv_nvx, op_KBv_nvy, and op_KBv_nvz in the virtual beamline.  The auto-compute horizontal or vertical occurs in the Sirepo code to compute that vector.  

I'll look closer at the Sirepo calculation tomorrow.

**Comment by faissaltbox** [comment]
hello Boaz, just to let you know, to put things into context:

Many thanks for your initial feedback. I know that the behavior of a cylindrical mirror can be "emulated" by the macros for elliptical mirror or toroidal mirror (actually, toroidal mirror, since that's the one that most easily gives a cylindrical symmetry). In fact, we have been able to succesfully implement the behavior we wanted to show using these  command. The problem, in fact, is that I'm not able to reproduce the phenomena with the specific "cylindrical mirror" object in SIREPO, which suggest that I probably don't use it correctly...

**Comment by bnash** [comment]
Hi Faissal- if I understand correctly, you want to include a toroid mirror, but you think that a cylindrical mirror should be acceptable as well.

Regarding (1), its true that the orientation is set by **auto-compute vector**, in the orientation tab and not by **Orientation of Reflection Plane** in the Height profile tab.  **Orientation of Reflection Plane** is relevant in the case that errors are added.

If you want to dig into the Sirepo code that encapsulates the logic of the UI, you can find the setting of the code [here](https://github.com/radiasoft/sirepo/blob/master/sirepo/template/srw.py).  Have a look at the function _compute_grazing_angle.

For (2), yes, its true that the grazing angle will be ignored in the case that you select None for **auto-compute vector**.  This would allow you to, for example, set the normal vector somewhere between horizontal and vertical.

(3), yes, correct.

(4) The "radius of curvature" for a spherical mirror (SRWLOptMirSph) is the radius in both directions.
For the toroid mirror, one has the option to set the radius both tangentially and for the sagittal direction.

Can you give us a link to one of your simulations where the mirror is not doing what you expect?
We can continue the discussion from there.

**Comment by faissaltbox** [comment]
Hi @bnash , I have been away on annual leave, just came back. To answer your question, what we would have liked (because it's the actual design) was the cylindrical mirror. As we haven't been able to use the cylindrical mirror properly, we are currently doing a work-around with a toroidal mirror, and it works. But for the sake of understanding SRW, we were wondering why we struggle to obtain sensible output from the cylindrical mirror.

I shall design a mini-toy model for illustration and then share it with you later tonight.

**Comment by faissaltbox** [comment]
In the example below, the spot at 140 m has a dimensional size that scales in meters when the radious of curvature is 0.087 m (which is the actual value of the device in the experiment):

https://beta.sirepo.com/srw#/beamline/xBf6AT1Z

**Comment by ochubar** [comment]
Hi Faissal, 
The focal length of a circular mirror is 0.5*R*sin(grazing_angle), which gives ~0.0038 m (!) for your set of parameters. For X-ray beamlines, radius of curvature of (circular) cylindrical mirrors is usually in the range of kilometers, grazing angle in the range if milliradians, and the focal length in the range of meters.

**Comment by faissaltbox** [comment]
Hi @ochubar , thanks for the comment. I ought have mentioned, in fact, that we were aware that the parameters we use in this simulation are somewhat unusual, especially with respect with the typical scale of radius of curvatures in km. Basically the original motivation to investigate this particular set of parameters was the fact that they were coming with a SHADOW file using 0.087 m as radius of curvature (so those values are not a mistake from us but really the one that were explored by those who designed that beamline).

Having said that, I am grateful for the clarifications/confirmations you and @bnash  provided , it was helpful, and it is clear now that this particular set of values was a dead end.

regards,

- Faissal
