### ISSUE TITLE
warpvnd: optimizer errors

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1541]
When the optimizer fails or crashes, it should show an appropriate error message with possible corrections to the user.

**Comment by messamer** [comment]
I looked at optimization using the EGun example simulation-  I am not clear
what I am supposed to do based on this "Select fields for optimization on
the *Source* tab."

**Comment by moellep** [comment]
Look for the cog wheel next to the field you want to optimizer on the
Source page and check the box. Below is an example selecting Voltage to
appear on the list of optimize-able fields. I plan on hiding the
Optimization tab unless at least one field is selected for optimization.
Also, I'd recommend using the Two Poles simulation because it is the
fastest example.

Paul

[image: Screen Shot 2019-02-27 at 2.12.44 PM.png]
