### ISSUE TITLE
Idempotent extract_job and report_job identifiers

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1557]
This has been a TODO in the code for [three years now](https://github.com/radiasoft/sirepo/commit/fd6c6245d170a6249a090b726e54c0e1279ba503#diff-cd6e8d1b5f5e7bf54ed0e9d6c926c222R430). We need to fix it, because startTime is not sufficient, and anyway, it's not being passed.

I proposed a few things:

* Change reportParametersHash to rpid, since it identifies report parameters.
* Add it to all responses in server
* Add it to all requests.
* Always computed on the server (as is now)
* Remove startTime from animationArgs

This is not a big change, and I don't think it would break anything. The rpid is unique to the result being processed.

**Comment by moellep** [comment]
The background reportParametersHash needs to come from the input to the background job, not the current state of the client. That isn't unique enough if the simulation code uses random values - the client would have cached the results from the previous if the reportParametersHash didn't change. We need some sort of run identifier for background jobs.

**Comment by robnagler** [comment]
The reportParametersHash has to be unique, because requests should be idempotent with respect to the values in `sirepo-data.json`.

The word "background" shouldn't be used. Use parallel and sequential.

Both parallel or sequential reports have the same caching issue. When you create a bunch with a random seed, it will be different every time. The fact that parallel reports might run for a longer time, and diverge more, is not as important as the caching issue in general.

If we need a serial number included in the hash, then all reports need serial numbers. Once any parameter changes, the reports should no longer be valid. We still show the last calculated parallel report even though the parameters may have been changed. This is a cache invalidation problem that we haven't solved, but is a related issue: we don't know when/how to invalidate explicitly run (typically parallel) simulations.

We can add serial numbers to all reports with sirepo-data.json being updated on each save, that is, when a save happens, the result is a new serial number on each report that is changed as a result of the parameters. If certain reports have unspecified random inputs, i.e. the code randomizes the seed outside of the parameters.py file, then the serial number changes every save. If we can control the seeds, we should, and that's part of the serialized report.

All of this relates to https://github.com/radiasoft/sirepo/pull/1549#discussion_r267458993. If we introduce serial numbers, then `runSimulation` should accept a limited set of parameters: simulationType, simulationId, simulationSerial, report, and, reportSerial. If we guarantee ACID on `sirepo-dat.json`, we solve all race conditions: if a serial is less than the current simulationSerial and reportSerial in `sirepo-data.json`, then the report was already started. 

This would greatly simplify runSimulation and runStatus, which would be a big bonus.

Conflict management is the same as now so I think we're fine there. 

We do have to move the parameter changes into `save_simulation_json`, but that's probably better, since we already need to go through all of the fields already in validate_fields.

**Comment by moellep** [comment]
I think we need to walk through this on a whiteboard. The parallel tasks output could get marked as stale, but the reports  shouldn't get cleared.

**Comment by moellep** [comment]
The use-case I want to make sure is preserved is this:

The user runs a long parallel job and views the results, the browser has cached the viewed data.

The user changes some parameters on the source page and returns to the parallel job results. The client continues to use the browser's cache and doesn't make a new request for the unchanged parallel output data.

**Comment by robnagler** [comment]
This use case is incorrect. It can result in obviously strange output:

![Screen Shot 2019-03-27 at 10 34 43 AM](https://user-images.githubusercontent.com/5495179/55094446-0dd8f580-507c-11e9-80b7-fcded6d9a97d.png)

With more subtle parameter changes, it can (and probably will) result incorrect interpretation.

More importantly, once the user has changed the parameters, there is no way to reproduce them via the app. Therefore, even though the output may be "valuable" in  terms of high computational cost, it is no value from the perspective of reproducible science, which is one of the primary goals of Sirepo.

When a parallel report is invalid, it should show nothing but the Start Simulation button, just like it does when you discard changes.

**Comment by robnagler** [comment]
@moellep and I discussed the the problem. What wasn't clear is that the path through reports is not always obvious. There's a feature which allows [simulation_db to get the run_dir from the template](https://github.com/radiasoft/sirepo/blob/879429fd28b6c0b7137f63847b4ea10aa9c0c1bd/sirepo/simulation_db.py#L1110). For example, bunchReport1, bunchReport2, bunchReport3, and bunchReport4 all share `bunchReport` as a directory name. There is no model named `bunchReport` so [there's code](https://github.com/radiasoft/sirepo/blob/879429fd28b6c0b7137f63847b4ea10aa9c0c1bd/sirepo/template/synergia.py#L337) which checks `'bunch_report' in report_name`. This is denormalized, and will need to be modularized. 

A `report_job` is really a `simulation_job`, and an `extract_job` is a `report_job`. A `simulation_job` needs a distinct serial number from an `report_job`. If you minimize a window, the `report_job` changes but not materially so it's serial number doesn't change.

`simulationSerial` is currently incremented on every save. The client should always have the most current `simulationSerial`. If it doesn't, there's been a collision. However, just because a `simulationSerial` changes, doesn't mean that either the `simulation_job` or `report_job` has changed. Therefore, although we need to check `simulationSerial` on every request about a simulation (`runStatus`, `runSimulation`, etc.), we are only validating that `sirepo-data.json` is consistent with the clients model state. For example, a simulation name can change without affecting any of the graphs and the browser cache is still valid so simulationSerial should not appear in GET requests (animations). 

If a simulation_job needs to be updated, all the report_job serials that depend on it will have to be updated. I think, therefore, we can always rely on report_job instead of (report_job, simulation_job). This will simplify the client in some ways.

The end-to-end implementation will improve in a number of ways:

* Race conditions will be eliminated: saveSimulation is atomic and job names are idempotent.
* Instead of the client requesting runStatus for each report after saveSimulation, it will know which reports need to be updated based on serial numbers.
* The runner_daemon will now have a unique and idempotent id for simulation_jobs and report_jobs.
* parameter hashing will go away since everything happens locally, a simple, nested data structure comparison will work. This will be less computationally intensive and simpler to write. It can be part of the field validation, perhaps.

Some complications:

* Discard changes to example must keep the serial numbers, but that would have to be the case anyway.
* Client and server logic will need to be rewritten, non-trivially.

**Comment by robnagler** [comment]
We are running into this again with the job execution code. We will be addressing this possibly in the GUI. reportParametersHash (now called computeHash) and the startTime in the frame_id are sufficient to ensure the integrity of the computation (computeHash) and the uniqueness of random computational inputs (startTime).

**Comment by robnagler** [comment]
Right now, we don't have the compute_hash so things are messed up, since api_simulationFrame relies on reading `in.json` of the compute_job, which does not exist locally in the NERSC case, and is not part of the frame_id (integrity). We can add compute_hash to the frame_id while making it backwards compatible until it is added to the GUI.

**Comment by robnagler** [comment]
@moellep we should discuss today. There's a lot of confusion in the code about simulationStatus. I think simulationStatus should be a client-side value only. It should get deleted when we send the data back to the server (sort of does now).

The server should have something like computeJobStatus. That would be saved in in.json, and sent back to the client in runSimulation/runStatus. It would contain startTime (renamed to computeJobStart?), computeJobHash, lastUpdateTime, etc. This would be for all runs, even sequential reports. There would be additional information from background_percent_complete.

There would be a callback (could be setSimulationStatus) for handleStatus that would put computeJobStatus on appState.models.computeJobStatus in the client. 

frameId would be fixed to put the optional parameters last, joined on the same separator. This would simplify things in the code greatly. startTime is everywhere in animationsArgs, but it's unused. The new order could even have frameIndex first since that's hard to see in the mess of arguments, and the only real differentiator for different frames. There would be a version.

Right now computeJobHash is on data, which is the wrong place. That'll be fixed to.

**Comment by robnagler** [comment]
We enforce this now everywhere except getDataFile, which has non-cache.
