### ISSUE TITLE
Avoid unqualified function imports

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1562]
There should very few exceptions to the rule that you import modules, not module attributes. 

This task is to fix [this specific case](https://github.com/radiasoft/sirepo/blob/50d75e76ce03ca14681bc1458482bb79b334e64c/sirepo/simulation_db.py#L18), and look for other cases.

**Comment by mkeilman** [comment]
To clarify: this is to replace all ```from x import y``` with ```import x``` and qualify all the uses in the code (```y``` -> ```x.y```)?

**Comment by robnagler** [comment]
Not exactly. Replace all instances of `from sirepo.x import f1, f2` with `from sirepo import x` and qualify all uses to `x.f1()`. That is, you only need to qualify the import if it is a direct function execution.

Here's the reasoning: If I see `f1()` with this approach, I can know to look for the definition of `f1` inside the current module. If I see `x.f1()`, I know it is defined in module `x`. While one can use "etags" or other code traversal tools, it's still a cognitive load to know if a function is defined in one module (file) or not just by it's simple name. 

If you use always use qualified names, then you can change, say, `schema.validate_schema` to `schema.validate`, which is the same length as an unqualified `validate_schema`, but more informative and less cognitive load. I see `schema.validate`, and I know that there's a module that validates the schema (in general). That's valuable to me, at least, in thinking about how the application is put together.

In the WIP commit, there's this:

```py
import pykern as pk
import pykern.pkdebug
import sirepo as sr
import sirepo.template as tmplt
import sirepo.schema as sch
```

This is worse. First, always remember what [Ken Thompson said about `creat` in Unix](https://books.google.com/books?id=poFQAAAAMAAJ&q=%22spell+creat+with+an+e%22&dq=%22spell+creat+with+an+e%22&hl=en). Second, you've created a new name. There are [two problems in computer science](https://hilton.org.uk/blog/why-naming-things-is-hard), and naming is one of them. Aliasing creates problems both in program optimization and development time minimization. I now have to learn a new name. Third, this didn't pick up the gist of what this Issue is about: reducing cognitive load.

**Comment by mkeilman** [comment]
OK, I jumped the gun there - I'll start over

**Comment by mkeilman** [comment]
Latest commit is all I could find, except for:

- classes (like ```from flask_sqlalchemy import SQLAlchemy``` in oauth)
- lots of ```from pykern.pkdebug import pkdc, pkdexc, pkdlog, pkdp,...```

Not sure if those are exceptions - I did change simulation_db in the latter case as an exercise

**Comment by robnagler** [comment]
pykern.pkdebug is an exception. as is pkunit in tests.

classes should be imported qualified.

It's very difficult to figure this out. You have too many changes in your master. You should create a branch for each feature, or commit each feature and then work on the next one. You can't pile all this in one PR. It's too much to review.

When I set this to priority 1, I meant for it to be done after you were done with your current task.

**Comment by mkeilman** [comment]
To start addressing the problem of monolithic PRs, the latest, which concerns this issue, is in a new branch just for the schema attributes.  I'll start breaking up master into appropriate branches as well...

**Comment by robnagler** [comment]
I'm dropping priority. Didn't really want this to be a major project. It should still be here, and if you see more unqualified imports, fix lazily.
