### ISSUE TITLE
zgoubi: 3D spin report

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1570]
Currently zgoubi spin output can be viewed from xy, xz and yz plots, but a 3D view would be useful. Below are flat plots from the SATURNE example which could be used for reference.

![Energy-and-Spin-5](https://user-images.githubusercontent.com/6516910/55192765-e6ad2180-516a-11e9-890c-ea64f59118cb.png)

![Energy-and-Spin-6](https://user-images.githubusercontent.com/6516910/55192773-ea40a880-516a-11e9-8959-85f522326417.png)

**Comment by bnash** [comment]
Exciting to see the beginning of this development!
Yes, if these data could be visualized on a sphere in 3-D that could be rotated, that would be really nice.  Is this turn dependent spin data here?  Which file do you get this data from?

**Comment by moellep** [comment]
Yes - this is the SATURNE example, 3000 turns for 1 particle. SX, SY, SZ from the zgoubi.fai output file. I've added the SATURNE example to sirepo and will have it on alpha later today.

**Comment by moellep** [comment]
The SATURNE example is available on alpha.sirepo.com now in the "SATURNE 3 GeV Synchrotron" simulation.

**Comment by moellep** [comment]
Added a spin 3d report which shows the Saturne example, particle 1 as:

![Screen Shot 2019-07-18 at 10 34 58 AM](https://user-images.githubusercontent.com/6516910/61476495-6f361480-a94a-11e9-8502-fa829fbbf2e9.png)
