### ISSUE TITLE
numeric stack size overflow ?

### ISSUE THREAD

**Issue by sb215** [radiasoft/sirepo#1583]
Hello, I was playing with elegant in web version of sirepo.

https://beta.sirepo.com/elegant#/visualization/OrRtEPGb

But when I start simulation, it give me following error.

```
elegant Errors:
error: numeric stack size overflow (rpn).
Terminated by SIGABRT
```

I searched it over google but I cannot get an answer, even in elegant user forum.

**Comment by moellep** [comment]
Hi @sb215, 

Your simulation uncovered a problem in the way we generate the elegant lattice input file for large lattices. I've opened issue #1584 to track this bug. We should have the problem fixed next week.

**Comment by sb215** [comment]
Thank you for help.
I saw #1584 but it's closed. Actually i'm newbie at accelerator, so I cannot understand what "rpn" is. But one thing is certain that, when I run pelegant with the lattice, it works well even though it takes an hour to simulate. It give me almost same log file compare with sirepo.

So, I check the elegant log with different lattice file. Difference between lattice is like following.
```
!RFCW  
LL_BAND1_1_1 : RFCW, FREQ= 2.856000000E+09,L= 3.003304E+00, &   
                     VOLT=" 57062776  1.00 /", &     
                     PHASE="-11.60 90 +", &  
                     CHANGE_P0=1,END1_FOCUS=1,END2_FOCUS=1,CELL_LENGTH=0.03500, &
```
This is lattice that I uproad to sirepo. Numbers are written as scientific notation.

And this is other lattice, which didn't give `compute value for...` after `&run_setup`.
```
!RFCW
"LL_BAND1_1_1": RFCW,L=3.003304,CELL_LENGTH=0.035,VOLT=57062776,&
 HASE=78.48225491634653,FREQ=2856000000,CHANGE_P0=1,END1_FOCUS=1,END2_FOCUS=1,&
 N_KICKS=20,ZWAKEFILE="Sz_5um_10mm.sdds",TRWAKEFILE="Sx_5um_10mm.sdds",&
TCOLUMN="t",WXCOLUMN="W",WYCOLUMN="W",WZCOLUMN="W",INTERPOLATE=1,SMOOTHING=1
```
Numbers in this lattice are written as unformatted float.

I'll uproad other lattice or convert the previous lattice into float. Before that, I'm so thankful to you with your help.

**Comment by sb215** [comment]
Well, I tried with different lattice. It give a same error.
https://beta.sirepo.com/elegant#/lattice/Cy4Q9WD9

**Comment by robnagler** [comment]
This Issue is for the initial problem, and it's not closed. The other Issue is closed, because it is fixed in the master, but it is not yet on production. 

We will update this issue on the next production release.

**Comment by moellep** [comment]
This problem has been fixed and you should be able to run both simulations to completion. Be sure to select Execution "Serial" on the Visualization page or you will see an error related to SDDS_MPI (elegant can't read ASCII input files when run in parallel). The simulation takes about 20 minutes to complete before the output reports are available.
