### ISSUE TITLE
elegant: Import file

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#1587]
Test Case:
1) "Export as Zip" any existing simulation (Compact Storage Ring)
2) Mac automatically unzips the file creating a folder containing 2 files: run.py and sirepo.data.json
3) Rezip folder
4) Import .zip file into Sirepo
5) See "ERROR: _MACOSX/Compact Storage Ring/duplicate file in archive"
6) Change folder name to "Compact Storage Ring 2"
7) See "ERROR: _MACOSX/Compact Storage Ring 2/duplicate file in archive"

Should this method work?

**Comment by robnagler** [comment]
This is  a bug caused by _MACOSX not being ignored in the zip.

I would say it is low priority to fix, since it's not a common mode of operation.

**Comment by bruhwiler** [comment]
I was trying to demo that one could save a simulation, modify it on the command line, and then import the changes into a new simulation.

Is this a reasonable use case?

**Comment by robnagler** [comment]
I thought this was "Test Case", not an actual end-user failure.

@mkeilman please fix. Anything with _MACOSX should be ignored.
