### ISSUE TITLE
beaker_compat_test fails with build only

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1590]
The tests/beaker_compat_test.py is failing all cases, but not on dev, only when building sirepo. I've disabled the tests to do a release, but this should be debugged.

**Comment by robnagler** [comment]
It appears to be caused by Werkzeug-0.15.2. Installing Werkzeug-0.14.1 works fine.

**Comment by robnagler** [comment]
[Random change](https://github.com/pallets/werkzeug/commit/5d9de7815ab5a5184c804d1f9836504c64a4b483#diff-5b4ae3613a21038db9058042327fe63eR216) causing the problem. We are injecting a cookie the wrong way, apparently.
