### ISSUE TITLE
enforce consistency of photon energy throughout a simulation

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#16]
It is possible to change the photon energy for some plots/reports.
If a user changes this in one report, but not another, then the images in these two reports could lead to confusion.
To solve this problem, any time the photon energy is changed and saved in one report, the same change should be made in other relevant reports.

**Comment by moellep** [comment]
When the photon energy is changed in report, it is automatically applied to the other reports. Also, if the Gaussian Beam's photon energy is updated, all reports automatically use the same value.
