### ISSUE TITLE
fete: Run simulations with imported stl conductors

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#1606]
rswarp now supports STL files

- [x] Interface with rswarp
- [x] Show results in visualization tab
- [x] Field report
- [x] Field animation
- [x] Impact density

**Comment by ncook882** [comment]
Hi @mkeilman. Thanks for creating this issue. I apologize for not doing so earlier, and pointing you to our new code. As you noted, @yhu-radiasoft has created, tested, and deployed an [STLconductor class](https://github.com/radiasoft/rswarp/blob/master/rswarp/stlconductor/stlconductor.py) in rswarp which interfaces with Warp's native Assembly class structure.

For examples of the code in use, please see [rswarp/examples](https://github.com/radiasoft/rswarp/tree/master/examples/stlconductor). I recommend you consider the [simple grid example](https://github.com/radiasoft/rswarp/blob/master/examples/stlconductor/field_solver_test/simple_stl_tec_grid.ipynb) as a lightweight test of the visualization and simulation capabilities of the interface, and the [honeycomb grid example](https://github.com/radiasoft/rswarp/blob/master/examples/stlconductor/field_solver_test/honeycomb_tec_grid.ipynb) as a more robust test.

Regarding default configurations, I suggest that you stick to the Watertight algorithm (`raytri == 'watertight'`) for intersection finding, and keep the normalization factor as the longitudinal cell size `dz`.

**Comment by mkeilman** [comment]
I'm having some trouble with the field - when I run the simple grid notebook I get 0 potential everywhere:
![image](https://user-images.githubusercontent.com/30352290/56688979-44178e00-6697-11e9-98ee-4d508ca18589.png)

Maybe my version of warp is outdated?  I'm installing it with radia run (```curl radia.run | bash -s code warp```)...

**Comment by robnagler** [comment]
You can see what version of warp you have with:

```sh
rpm -qi rscode-warp
```

This will tell you the repo and SHA.


In general, use:

```sh
radia_run beamsim-codes
```

This will update everything, over TLS

**Comment by yhu-radiasoft** [comment]
I noticed the "raytri" scheme is the set to be "moller" in the current simple_stl_tec_grid.ipynb file. Please switch "moller" to "watertight".  Or you can leave the "raytri_scheme" option blank, like
conductor = STLconductor("../grid/simple_tec_grid.stl",  verbose="on", voltage=CONDUCTOR_VOLTS, normalization_factor=dz, condid=1). 
."moller" is much less robust than "watertight". "watertight" is the default "raytri_scheme" option.

**Comment by ncook882** [comment]
I agree with @yhu-radiasoft . It is better to stick with the default "watertight" scheme. That said, both options should work for the simple TEC grid as it has been setup in the example notebook. For more complex grids, the watertight scheme is necessary to avoid errors.

I re-ran the notebook on our Jupyter server and it produced the desired result:
![Screen Shot 2019-04-24 at 3 17 20 PM](https://user-images.githubusercontent.com/11053323/56694519-1f75e300-66a4-11e9-9588-7b539ef43b65.png)

Here's the rpm information for the Warp installation on Jupyter:

> rswarp$ rpm -qi rscode-warp
Name        : rscode-warp
Version     : 20190201.175921
Release     : 1
Architecture: x86_64
Install Date: Thu 28 Mar 2019 08:30:57 PM UCT
Group       : default
Size        : 37314836
License     : unknown
Signature   : (none)
Source RPM  : rscode-warp-20190201.175921-1.src.rpm
Build Date  : Fri 01 Feb 2019 06:07:15 PM UCT
Build Host  : fnl1b.bivio.biz
Relocations : /
Packager    : <vagrant@fnl1b.bivio.biz>
Vendor      : vagrant@fnl1b.bivio.biz
URL         : http://example.com/no-uri-given
Summary     : version: edef438ec66fb29d3b9021d38147e47156898ceb
Description :
version: edef438ec66fb29d3b9021d38147e47156898ceb
source: https://bitbucket.org/radiasoft/warp.git
build: /home/vagrant/src/radiasoft/codes/warp-20190201.175922/warp

When importing Warp from the notebook, I confirmed that the same install date/commit hash is being used:

> import warp
 Warp
 Origin date: Fri, 1 Feb 2019 10:07:46 -0700
 Local date: Fri, 1 Feb 2019 10:07:46 -0700
 Commit hash: edef438
 /home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/warp/warp.pyc
 /home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/warp/warpC.so
 Wed Apr 24 21:10:25 2019
 import warp time 0.77531003952 seconds
 For more help, type warphelp()

**Comment by mkeilman** [comment]
I got this:

[py2;@v ~]$ rpm -qi rscode-warp
Name        : rscode-warp
Version     : 20190201.175921
Release     : 1
Architecture: x86_64
Install Date: Wed 24 Apr 2019 08:34:59 PM UTC
Group       : default
Size        : 37314836
License     : unknown
Signature   : (none)
Source RPM  : rscode-warp-20190201.175921-1.src.rpm
Build Date  : Fri 01 Feb 2019 06:07:15 PM UTC
Build Host  : fnl1b.bivio.biz
Relocations : / 
Packager    : <vagrant@fnl1b.bivio.biz>
Vendor      : vagrant@fnl1b.bivio.biz
URL         : http://example.com/no-uri-given
Summary     : version: edef438ec66fb29d3b9021d38147e47156898ceb
Description :
version: **edef438e**c66fb29d3b9021d38147e47156898ceb
source: https://bitbucket.org/radiasoft/warp.git
build: /home/vagrant/src/radiasoft/codes/warp-20190201.175922/warp

and

Warp
Origin date: Thu, 4 Apr 2019 15:34:17 -0700
Local date: Thu, 4 Apr 2019 15:34:17 -0700
Commit hash: **e3bbe4c4**
/Users/mkeilman/Library/Python/2.7/lib/python/site-packages/warp/warp.pyc
/Users/mkeilman/Library/Python/2.7/lib/python/site-packages/warp/warpC.so
Wed Apr 24 16:30:16 2019
import warp time 0.155169963837 seconds
For more help, type warphelp()

So they don't match...???

**Comment by robnagler** [comment]
That's really strange. Did you build warp on your mac?

**Comment by mkeilman** [comment]
Yesss, I did that earlier and got confused, comparing the mac to the vm.  Now running jupyter on the vm and it works as expected.

**Comment by mkeilman** [comment]
Long completed, project over
