### ISSUE TITLE
Allow deactivation of beamline elements

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#162]
We need ability to allow deactivation of beamline elements without removing them from beamlines. We may have a button next to `x` button to disable the element. Disabled element may become greyed or transparent after disabling. Corresponding propagation parameters associated with the deactivated element should be shaded.

This request is from Lutz Wiegart (NSLS-II scientist).

Subtasks:
- [x] Add "disable" button to beamline elements on mouse over (4f749aa).
- [ ] Change image after clicking the "disable" button (gray it out).
- [ ] Remove the element from calculation.

**Comment by bruhwile** [comment]
It's great to have feature requests coming in from our users at NSLS-II !

**Comment by mrakitin** [comment]
Yes, I'll create several more tickets for Lutz's requests.

**Comment by mrakitin** [comment]
@moellep, I will try to implement it myself this week. I'll ask you if I have any questions regarding the issue.

**Comment by mrakitin** [comment]
I have to change priority to 2nd since there are more urgent issues #184 and #167.

**Comment by mrakitin** [comment]
I'm not sure I have time to finish this ticket in a timely manner. @moellep, do you mind to look at items 2 and 3? Thanks.

**Comment by mrakitin** [comment]
Looks great, @moellep! Thanks for implementing this feature.
