### ISSUE TITLE
webcon: improve beamline icons on controls tab

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1625]
webcon is currently using the standard sirepo lattice renderer which is very plain:

![Screen Shot 2019-04-30 at 10 28 58 AM](https://user-images.githubusercontent.com/6516910/56977683-f9809080-6b32-11e9-8850-b937a33b7442.png)

Below is an example from another application which has more interesting icons:

![Screen Shot 2019-04-30 at 10 28 47 AM](https://user-images.githubusercontent.com/6516910/56977794-41071c80-6b33-11e9-9462-02885dbf28ca.png)

**Comment by bruhwiler** [comment]
@moellep -- we can outsource this to our marketing contractor, if you like

**Comment by messamer** [comment]
Yes!

--
Paula Messamer
Product Manager - RadiaSoft LLC
1-720-502-3928   x719
radiasoft.net - sirepo.com

**Comment by moellep** [comment]
Yes, that would be fine. We'd need to provide them with a list of the element types (quad, bpm, bend, ...).

**Comment by messamer** [comment]
Paul-  Would you please provide an exhaustive list of the element types currently in use?

**Comment by moellep** [comment]
Here's a pic of the current icons:
![Lattice-BL1-5](https://user-images.githubusercontent.com/6516910/57388646-d9298500-7175-11e9-8bcf-10d50ae3d4d9.png)
Starting left-most:
(marker, alpha magnet, 6 bends, marker, aperture, quadrupole, sextupole, octopole, lens, mirror, recirculation, solenoid (light blue box), 6 bends, undulator, a zero-length element (black band), and rf cavity)

We also have stand-alone icons (not part of a beamline connected by drifts):
![All-optical-elements](https://user-images.githubusercontent.com/6516910/57388838-463d1a80-7176-11e9-8495-e3eb69632e5b.png)

To be used in the app, each element would need to be in SVG format. 

Below is another example of a beamline, rendered using the tikz-palattice latex package (with some nice gradients):

![Screen Shot 2019-05-07 at 4 45 51 PM](https://user-images.githubusercontent.com/6516910/57389091-b481dd00-7176-11e9-9657-8c91dcc95431.png)

**Comment by moellep** [comment]
Below is another example of a nicely rendered beamline, from the zgoubidoo project. Light blue quads, grey drifts leading to pink bending magnets and yellow scanning magnets. The particle trajectory is shown in blue lines (not needed for our case). The gradients might be a little more to @mkeilman's liking.

![Screen Shot 2019-05-15 at 2 07 25 PM](https://user-images.githubusercontent.com/6516910/57806311-16fd4f00-771c-11e9-87da-17dbf1426384.png)
