### ISSUE TITLE
Alpha release 5/1/19 11:15: non-backward compatible changes

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1626]
There are non-backwards compatible GUI changes so users will have to refresh their browsers. 

All users will then be prompted to enter their names, even if they are logged in as guests.

You will need to make non-backwards compatible configuration changes when you install the new alpha image. (Development mode is backwards compatible.) Brief summary follows:

* GitHub auth config has changed. Update the environment variables as follows:

| Old | New |
| - | - |
`SIREPO_FEATURE_CONFIG_API_MODULES=oauth` | `SIREPO_AUTH_METHODS=github:guest`
`SIREPO_OAUTH_GITHUB_KEY` | `SIREPO_AUTH_GITHUB_KEY`
`SIREPO_OAUTH_GITHUB_SECRET` | `SIREPO_AUTH_GITHUB_SECRET`

The default callback_uri is deprecated so you will either need to update your GitHub OAuth config to the following URI: 

`/auth-github-authorized` 

OR set the following environment variable to use the deprecated uri:

```sh
SIREPO_AUTH_GITHUB_CALLBACK_URI=https://<host-in-github-settings>/oauth-authorized/github
```

As noted, just copy and paste the value in your Organization's Settings > OAuth Apps > Authorization callback URL.

OR

* Bluesky auth config has changed. Add the following environment variables before installing:

| Old | New |
| - | - |
`SIREPO_FEATURE_CONFIG_API_MODULES=bluesky` | `SIREPO_AUTH_METHODS=bluesky:guest`
`SIREPO_BLUESKY_SECRET` | `SIREPO_AUTH_BLUESKY_SECRET`

Note that in t you have multiple authentication methods, e.g. github, bluesky, guest, you will need to combine them, e.g. 

```sh
export SIREPO_AUTH_METHODS=github:guest:bluesky
```

The order of the visible auth methods (github, guest, and email) in `SIREPO_AUTH_METHODS` is significant for the GUI, that is, they are the order of the buttons that allow people choose between the methods. 

If you are deprecating `github` auth (as RadiaSoft is), then set the methods as follows:

```sh
export SIREPO_AUTH_METHODS=email:guest
export SIREPO_AUTH_DEPRECATED_METHODS=github
```

**Comment by robnagler** [comment]
Delay due to JS errors: https://github.com/radiasoft/sirepo/issues/1627

**Comment by mrakitin** [comment]
Can these kinds of notifications be a part of the GitHub releases for those who is watching releases only? I personally missed the notification.

**Comment by robnagler** [comment]
We do not create GitHub releases so there's no way to notify you.

We always put "alpha" or "beta" or "prod" in issues so it is fairly easy to setup a filter in your mail client to highlight Issues about alpha, beta, or prod.

**Comment by mrakitin** [comment]
OK, I see. What if a release notes section existed in the documentation https://sirepo.readthedocs.io? Something like http://nsls-ii.github.io/bluesky/api_changes.html would help a lot. Otherwise I have no idea what and when was changed without careful looking at issues and filtering it as suggested.

**Comment by robnagler** [comment]
Here's [a handy link](https://github.com/search?o=desc&q=type%3Aissue+repo%3Aradiasoft%2Fsirepo+release&s=created&type=Issues) you can bookmark.

[Search, don't sort](http://www.nigeldobson.com/2012/12/search-dont-sort.html).

**Comment by mrakitin** [comment]
Thanks for the link, however it also returns irrelevant results, e.g. https://github.com/radiasoft/sirepo/issues/1658, https://github.com/radiasoft/sirepo/issues/1656, https://github.com/radiasoft/sirepo/issues/1633, ... Anyway, it's a good start.
