### ISSUE TITLE
Should logout as guest ask "Are you sure?"

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1630]
When you logout as guest, you lose all your work. So, should we ask "Are you sure?" 

Right now, I've left guest logins on alpha for testing, but we will be removing them, since we will be requiring email validation always on sirepo.com.

Therefore, it's not clear we should bother with "Are you sure?" as most (behind the firewall) installations will not want guest logins either. It's really only useful as a marketing feature and for development.

**Comment by bruhwiler** [comment]
Guest logins will be useful (as noted above) for the enticing examples that will be found on the upcoming Sirepo landing page.

I think an "are you sure" would be valuable for these (potential) users.

**Comment by robnagler** [comment]
I guess I was assuming we wanted no guest logins per our discussions (can't find them). However, I see now what you want is https://github.com/radiasoft/sirepo/issues/1173#issuecomment-449488386 so we'll leave guest in (it's a config change to take it out if we decide later).

I'll wait for @messamer's input before implementing Are You Sure.

**Comment by messamer** [comment]
Question: If I am logged in as a Guest can I switch that session to a Email
authorized user within that session?

**Comment by robnagler** [comment]
@messamer I think there's a missing link/button here. It probably should show up in the Logout menu.  The code can support this, but there's no way to get to it once logged in as guest.

I could use some help with a proposed workflow. I don't think "save your work with github" that we had before was good. Rather, I think we should maybe warn people when they logout as guest that they can "Save your work" or "Close your account". Those are the only two logical options. Maybe different wording.

**Comment by messamer** [comment]
This deserves some focused time.  I will review and propose something by
COB tomorrow.

**Comment by moellep** [comment]
This is fixed with #1779 - a "Save your work!" link is shown for guest accounts and "log out" is not shown.
