### ISSUE TITLE
Examples only guest login

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1632]
We haven't implemented "examples only guest login" per https://github.com/radiasoft/sirepo/issues/1173#issuecomment-449488386. That might not be too much work, but it would be ugly code. I would prefer not having that, and just having a guest login in general. We are requiring their names. 

Perhaps we should discuss. It relates to setting permissions on copying simulation, maybe.

**Comment by robnagler** [comment]
Is this relevant?

**Comment by bruhwiler** [comment]
We no longer support guest login, so this issue is no longer relevant.
