### ISSUE TITLE
Test login code on alpha

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1633]
Please let me know what you think about the workflow. It automatically migrates existing github logins so if you are logged in on alpha, you'll be able to see that workflow.

**Comment by bruhwiler** [comment]
I logged in as guest twice, ran elegant examples and logged out.
Then I started the email-based login.
You get this popup window:
![image](https://user-images.githubusercontent.com/3825435/57035550-931d7000-6c0f-11e9-9144-bcc747b41520.png)
It seems funky that it invites you to close the window, but there is no x and no 'close' button.
Maybe just remove that text about closing the window...?

**Comment by bruhwiler** [comment]
I guess it means that I can close the browser tab.
Maybe it should say that...?
Not a big deal.

**Comment by ncook882** [comment]
I agree with @bruhwiler  that it looks weird as is. If the user will need to close their browser, then I'd suggest the email submission takes you to a new page (in a new tab) that says "You've registered. Check your inbox, etc etc." This would be more in line with my experiences with other websites.

**Comment by robnagler** [comment]
@bruhwiler It would be fine to change to "tab", but some people don't use tabs, and instead use browser windows. It's a feature, not requirement. The "popup" is not a "window" in traditional parlance, but I see how you think it is. 

@ncook882 I don't think that workflow works in our case. You can literally do nothing with the app until you click on the link in your inbox. If you visit a page that requires a login, you will be presented with a new login prompt, because you might have mistyped your email address (which I did just this morning). This is a different workflow than medium.com which allows you to use the app even though you aren't logged in.

**Comment by robnagler** [comment]
I think all the text needs work, btw.

**Comment by bruhwiler** [comment]
I successfully logged in via email, using two different emails on two different browsers.
Modulo minor confusion with the popup window, I like the work flow.
It's very familiar from other websites who do the same sort of thing.

If I use the email associated with my Gravatar account, then my Gravatar image appears in the Sirepo app.  Kind of cool.

**Comment by robnagler** [comment]
Thanks for testing @bruhwiler @ncook882!

Did anybody else (besides @moellep) the GitHub conversion workflow? You would have to have logged in with GH on alpha before the release. Once in the cookie, if you were logged out, it would force you to login via GH and then refresh to login via Email or Guest.

**Comment by bruhwiler** [comment]
If I login with email, then logout, then log back in, I again see the "Welcome to Sirepo" popup.
![image](https://user-images.githubusercontent.com/3825435/57037691-20af8e80-6c15-11e9-8efc-df200b3f6c88.png)
Not sure if this is a problem, but it was somehow unexpected in my mind.

If I sign out with one app, it signs me out of all apps.
This is not unreasonable, but again I was a little surprised.
If I had been doing something important in the other app, I might be pissed.

Maybe an "Are you sure?  You will be logged out of all apps in this browser." or something along those lines is warranted?

**Comment by robnagler** [comment]
I don't think we should think of a "code" as an "app" (even though that's how it is implemented). Rather, Sirepo is the "app", and the simulation codes are "codes". I think that's how the new landing pages will work, right?

**Comment by bruhwiler** [comment]
Each Sirepo/xyz has a different UI and different capabilities, even if both
'xyz' codes are tracking particles through an accelerator. Also, there is
almost no interaction between the different codes, with possibly the only
exception being that JSPEC can grab an accelerator lattice from elegant.

So in my mind, each Sirepo/xyz is a separate app.

As for the upcoming Sirepo landing page, it will offer users to either
model a particle accelerator or an X-ray beamline.  Users who jump right in
will not be likely to see any text regarding 'elegant' or SRW.

Curious viewers of the landing page will have the opportunity to find
information about 'elegant' or SRW before clicking on a link to get
started. However, they may see only one of these and have no awareness of
the other.

Once a user is in the Sirepo/elegant app, they will see the 'elegant' name
in the upper left. At present, if they click on the 'elegant' text, it
takes them to the 'elegant' landing page.  I'm not sure we want this
behavior anymore.  Should have a conversation with Paula about it.

Similarly, if a user clicks on the "Sirepo" logo, then they are taken back
to the Sirepo landing page. Again, I don't think we necessarily want this
behavior anymore. It requires discussion.

How we handle the beta site landing page is a separate question. I'm
assuming that in the near term it will just look like the present sirepo.com
page, but with 'elegant' and SRW removed, and also with no reference to the
alpha-quality codes.

We will most like have Vermilion design an improved beta landing page in
the future.

David

**Comment by robnagler** [comment]
There are complex UI/UX issues here, which I think we should discuss this offline. I also think it is outside the context of this issue which is about testing the new authentication mechanisms.

Sirepo supports single sign-on (SSO), that is, once you are logged into a particular domain name, e.g. beta.sirepo.com, you don't have to login again. Do you agree we should have SSO? I think so, but I would like to clarify.

**Comment by messamer** [comment]
Yes, SSO is correct.

--
Paula Messamer
Product Manager - RadiaSoft LLC
1-720-502-3928   x719
radiasoft.net - sirepo.com

**Comment by moellep** [comment]
Closing this issue - if there are new email login problems we can create a new issue.
