### ISSUE TITLE
What to do on invalid email authorization link?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1635]
When a user clicks on an old or expired email authorization link, what should happen?

There are two cases:

1. The user is logged in, and they click on the link in the email. This might happen if they forget how to get to Sirepo, and then go to their email and find the old link and try to reuse it.
    i. I think the user should be presented with a button to ask them if they want to continue to the app.
    ii. Maybe they should just be redirected to the app. That's what @moellep had before I took over the code.
2. They user is logged out, and they click on the link in an email. This might happen if they click on the wrong email.
    i. I think the user should be directed to a login failed page with the opportunity for them to login via email. Should we autofill the email?
    ii. The user is told the link is invalid, and given an opportunity to login with all methods.

**Comment by moellep** [comment]
Currently if you follow an expired login link from your email, it will show a message stating the link is expired. If you were already logged it, it does not automatically log you out, which is good. The Medium website ignores expired links if you are already logged in and treats it as a normal link to the website. I think the current behavior is fine.
