### ISSUE TITLE
Make a Suggestion

### ISSUE THREAD

**Issue by dtabell** [radiasoft/sirepo#1642]
The (?) Help Button allows one to “Report a Bug”. I think a similar option to “Make a Suggestion” would be nice.

**Comment by messamer** [comment]
Let's change "Report a Bug" to "Submit an Issue"

- GitHub page uses "New Issue"
- Generally more positive and covers both Bug Reports and Enhancement Requests. 
- Icon can stay as it is

**Comment by bruhwiler** [comment]
This idea has resurfaced in the context of recent interviews with Sirepo users. We want a frictionless way for users to make a comment or request or complaint, when they are in the midst of using Sirepo.

The hope is to generate significantly more user feedback.

I have an action item to better define what is wanted and to then communicate that to @robnagler, before any Sirepo issues are created.

I will wait until after Sirepo Premium is on production, before I push on this issue.

**Comment by robnagler** [comment]
Adding slack links will help. Report a bug is there.
