### ISSUE TITLE
vagrant-sirepo-dev is broken at the moment

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1644]
Fedora removed fedora/27-cloud-base so you can't install VMs at the moment.

**Comment by dtabell** [comment]
Ugh! Perfect timing. I am helping Michael install a VM on his Mac.
Hope this is fixed soon.

**Comment by robnagler** [comment]
This will not be fixed soon.

**Comment by dtabell** [comment]
Any idea when it might get fixed?

**Comment by robnagler** [comment]
I have shifted my priorities to work on this now. This involves an upgrade from Fedora 27 to Fedora 29. There are about 10 or more scientific codes that have to run correctly, among other things (Jupyter, Sirepo, Docker, etc.) This is not a predictable process, unfortunately.

**Comment by robnagler** [comment]
Sirepo with SRW is running. All of Sirepo seems to work.

rpm-code/codes/common.sh is building, which includes radiasoft/fedora and radiasoft/rpm-code docker images. vagrant-dev works. Docker works.

SDDSPython rpm is no longer available, and anyway, we want py3 version, too. Spent time figuring out how AOP build works with EPICS build system. Building SDDS with Python, elegant, and Pelegant. Need to clean up and wrap properly for py2 & py3 builds.

**Comment by robnagler** [comment]
synergia and elegant are working

**Comment by robnagler** [comment]
jspec seems to be in an infinite loop. @moellep have you see this behavior before?

**Comment by robnagler** [comment]
rslinac seems to work

**Comment by robnagler** [comment]
shadow3 doesn't work https://github.com/radiasoft/download/issues/54

**Comment by robnagler** [comment]
pygist is failing https://github.com/radiasoft/download/issues/55

**Comment by moellep** [comment]
No, I haven't seen jspec get in an infinite loop. When I try to install the latest sirepo-dev I get this error:

```
$ radia_run sirepo-dev
Log: /Users/moeller/v3/radia-run-install.log
curl -L -s -S https://raw.githubusercontent.com/radiasoft/download/master/installers/sirepo-dev/radiasoft-download.sh
Source: /var/tmp/radia-run-35505-1812/20190509085125-radiasoft-download.sh
only works on Red Hat flavored Linux
```

**Comment by robnagler** [comment]
It's `radia_run vagrant-sirepo-dev`, not `sirepo-dev`. You might need to vssh first if you v3 is already instantiated. However, the subject of this Issue is "vagrant-sirepo-dev is broken" so it won't run at all.

sirepo-dev only works on Fedora so I'll change the error.

**Comment by mrakitin** [comment]
@awalter-bnl and I are 2 more interested parties in having it resolved ASAP as it's going to be used for simulations of a new NSLS-II beamlines with Sirepo-Bluesky interface. Thank you.

**Comment by robnagler** [comment]
@mrakitin are you going to use VirtualBox for Bluesky? Docker images still work.

**Comment by robnagler** [comment]
warpvnd and warpbpa seem to work

**Comment by moellep** [comment]
@robnagler, yes I was running the wrong command. I'm installing the latest on my mac using ```curl radia.run | vagrant_dev_no_nfs_src=1 bash -s vagrant-sirepo-dev``` and will debug the jspec problem.

**Comment by robnagler** [comment]
You should use `vagrant_dev_no_nfs_src=1 radia_run vagrant-sirepo-dev`, because it uses TLS. This will work on your Mac, because you already have an f27 box loaded.

**Comment by robnagler** [comment]
zgoubi seems to work

**Comment by mrakitin** [comment]
> @mrakitin are you going to use VirtualBox for Bluesky? Docker images still work.

@robnagler, for the development purposes we don't want to hit the public or facility-wide server. The interface is not stable enough yet, we are going to make it more stable after @awalter-bnl's feedback.

**Comment by mrakitin** [comment]
Sorry, mistakenly closed the issue. Reopened.

**Comment by robnagler** [comment]
`radia_run vagrant-sirepo-dev` is working again with fedora/29-cloud-base as the base box. 

You will need to upgrade to VirtualBox 6.x ([mac](https://download.virtualbox.org/virtualbox/6.0.6/VirtualBox-6.0.6-130049-OSX.dmg)) and Vagrant 2.2.x ([mac download](https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.dmg)).

Also, vbguest is broken so you'll get an error running vagrant-sirepo-dev [about setup not being found](https://github.com/radiasoft/download/issues/53). Once you get the error, run this:

```sh
$ perl -pi -e 's{(?=^end)}{    config.vbguest.auto_update = false\n}' Vagrantfile
$ vagrant reload
$ vssh
```

A couple of codes are completely broken at the moment: [pymesh](https://github.com/radiasoft/download/issues/59) and [shadow3](https://github.com/radiasoft/download/issues/54). jspec compiles but [seems to be in an infinite loop](https://github.com/radiasoft/download/issues/56). 

In order to work around #1655, you need to start the server this way:

```sh
SIREPO_FEATURE_CONFIG_SIM_TYPES=elegant:hellweg:jspec:myapp:srw:synergia:warppba:warpvnd:zgoubi sirepo service http
```

Obviously, if you are only working on one code, you only need to specify that code in `sim_types`.

I'm going to close this issue as there are other issues to covering the problems noted above.

**Comment by robnagler** [comment]
@mrakitinw writes:

> for the development purposes we don't want to hit the public or facility-wide server. The interface is not stable enough yet, we are going to make it more stable after @awalter-bnl's feedback.

I'm a little confused about this comment. Please open a new issue with a description of the instability.

**Comment by mrakitin** [comment]
@robnagler, I meant the API between Bluesky and Sirepo is instable, mostly on our side. Don't worry about it.
