### ISSUE TITLE
Icon choice

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#1647]
Revisit the icons for downloads (currently a cogwheel) and report abut/documentation (currently a question mark).

Current icons are taken from Bootstrap v3.4.1: https://getbootstrap.com/docs/3.4/components/

**Comment by remy278** [comment]
If we're adding the folder+cog icons to this issues, I recommend that we just use a plain folder icon for all folders. No need to add any other shapes on top of that.

**Comment by messamer** [comment]
We decided to change the icon for example folders and example simulations to glyphicon-star (replacing glyphic-cog).  See issue #2685

**Comment by remy278** [comment]
#2685 has been completed, so I'm going to close this issue as well.
