### ISSUE TITLE
Zgoubi, elegant, Synergia: Highlight element in Lattice when element is chosen

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#1652]
When a user clicks an element in the Beamline Editor, the element should be highlighted in the Lattice representation.

**Comment by moellep** [comment]
A similar request:

> Would it be possible to click (or command-click, or option-click, or ...) on an element in the lattice preview and have the corresponding element and/or beamline selected in the list of Beamline elements or Beamlines?

**Comment by moellep** [comment]
Selecting the item in the lattice preview or in the beamline editor will highlight the lattice and select the appropriate element in the beamline editor.

![Screen Shot 2019-10-04 at 1 55 17 PM](https://user-images.githubusercontent.com/6516910/66236289-5a4a6100-e6af-11e9-9825-8cc01644fdda.png)
