### ISSUE TITLE
webcon: epics integration review

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1653]
An end-to-end EPICS integration has been added to webcon which works for both a remote and a local EPICS instance.

The [code](https://github.com/radiasoft/sirepo/blob/master/sirepo/pkcli/webcon.py#L38) will need help from @robnagler.

For "local" it starts an epics program, an epics log monitor, both as subprocesses and then continually runs an elegant simulation in a loop. Calls to the epics database are also done as subprocesses.

For "remote", it only runs the epics log monitor.

The process cleanup is not good. The elegant simulation runner uses the pyepics module, and the longer it runs, the longer (really long) it takes to exit the python process at the end. Possibly python is cleaning up a lot of memory or file handles which aren't getting cleaned up.

**Comment by robnagler** [comment]
I think we clean up things well with Docker and Local drivers so no need to do this.
