### ISSUE TITLE
mailto: link does not work on Windows?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1665]
@moellep would you please see what happens when you click on the mailto link in chrome and edge?

**Comment by moellep** [comment]
I think the problem is the` target="_blank"` on the mailto link. In chrome on windows it opens a new tab. On IE Edge it shows the normal "How do you want to open this?" dialog.

**Comment by bruhwiler** [comment]
I tried it just now on Win10/Chrome and it's working fine.

I also tried Win10/Edge. I did not test this yesterday.
It works fine as well -- opens Chrome to actually send the email.

Today I'm working on a different laptop than I was using yesterday.
The other one is at home.

**Comment by robnagler** [comment]
I'll close now, but would be good for you to try on your other laptop.
