### ISSUE TITLE
new landing page:  fonts:  problems on Win10/Chrome

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1668]
This is with Win10 / Chrome on the alpha server, as of May 16, 2019

![image](https://user-images.githubusercontent.com/3825435/57874878-cb57ad80-77ce-11e9-943d-b47e5751967b.png)

**Comment by moellep** [comment]
I'm not seeing this on my Chrome/Windows setup. It could be the graphics card on your computer. As an experiment, could you put "chrome://flags" in your browser URL and then disable "Accelerated 2D canvas" (one of the items at the top) and then restart chrome.

From https://coderwall.com/p/9tecwq/fix-poor-font-rendering-in-chrome-on-windows

**Comment by bruhwiler** [comment]
Done.

This did not change the appearance of the fonts.

Also, if I go to a page without the animated background, I still see jagged text rendering.

**Comment by bruhwiler** [comment]
The fonts look fine on my newer laptop.

The font problems are on an older machine, so I'm closing this issue.

**Comment by robnagler** [comment]
FTR, my laptop is from 2013 is also older.
