### ISSUE TITLE
Cannot cleanly discard a simulation

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1672]
When I try to discard changes in the "Tabulated Undulator Example", I am redirected to the following URL: https://expdev.nsls2.bnl.gov/find-by-name/srw/default/Tabulated%20Undulator%20Example, and the "Not Found" page is displayed.

**Comment by robnagler** [comment]
The example names changed so old examples are not found. We need the ability to redirect to the new example in this case.

**Comment by moellep** [comment]
This sounds like #1629 
@robnagler are you sure that the tabulated undulator example name changed?

**Comment by robnagler** [comment]
You are right, it didn't change. Let's see if it happens with latest.
