### ISSUE TITLE
Error loading with numpy.load()

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#1673]
This is due to this [security issue](https://www.bleepingcomputer.com/news/security/numpy-is-awaiting-fix-for-critical-remote-code-execution-bug/).  Numpy 1.16.3 defaults ```allow_pickle``` to False which stops .npy files from loading.  Since we generate the files ourselves I believe it is safe to set ```allow_pickle``` to True.  

warpvnd is the primary victim

**Comment by robnagler** [comment]
Can we save in another format?

**Comment by mrakitin** [comment]
https://msgpack.org/ ?

**Comment by mrakitin** [comment]
We started using it at NSLS-II via https://github.com/bluesky/suitcase-msgpack, seems to be fine, but there are some issues.

**Comment by robnagler** [comment]
How big is the data?

**Comment by mrakitin** [comment]
In our case we tested 100s of megabytes for now, but should also handle larger datasets (multi-gigabytes HDF5 files from AreaDetector's).

**Comment by robnagler** [comment]
I meant for our load/store problem.

**Comment by moellep** [comment]
Saving as hdf5 now.
