### ISSUE TITLE
Alpha Release 12:55 MT 5/17/2109: back to master branch

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1676]
Returning to `master` for alpha. @mrakitin this will push all the most recent changes to Docker Hub as radiasoft/sirepo:alpha.

See #1626 for details about incompatible configuration changes.

**Comment by robnagler** [comment]
Ran into this

```txt
AssertionError: db file collision: old=/srv/sirepo/db/user.db and new=/srv/sirepo/db/auth.db both exist
```

We had run master, switched back to pre-auth.init (beta3), and back to master. Fix is to:

```sh
rm /srv/sirepo/db/auth.db
```

After startup you will see in logs:

```txt
auth_db.py:133:_migrate_db_file migrated user.db to auth.db
```

And the file `/srv/sirepo/db/user.db-migrated` will exist.

**Comment by mrakitin** [comment]
Thanks for mentioning me, @robnagler! Yes, when I ran the suggested tag in https://github.com/radiasoft/sirepo/issues/1669#issuecomment-493210331, I noticed that there are the following files in our case:
- `auth.db`
- `user.db-migrated`
(no `user.db`)

Seems to be fine, however we noticed that @ahebnl lost her simulations. Any easy way to check which ones she had before? @ochubar and I have all our previous simulations.

**Comment by robnagler** [comment]
The migration should be seamless. Was @ahebnl logged in? Was she registered with GitHub? Did she clear cookies?

**Comment by mrakitin** [comment]
Yes, she was logged in before the upgrade with her GitHub credentials. Maybe cleared, but it should not affect her simulations when logged in, right?

**Comment by robnagler** [comment]
The auth.db should have a record for her github credentials. You can check this with

```sh
echo 'select * from auth_github_user_t;' | sqlite3 auth.db
```

**Comment by mrakitin** [comment]
That's a handy command! It returned a list of users, and `ahebnl` is there:
```
<some integer id>|ahebnl|<UID>
```

**Comment by mrakitin** [comment]
What table was used in `user.db` (which is now `user.db-migrated`)?

**Comment by mrakitin** [comment]
OK, figured it out:
```
sqlite> select * from user_t;
<different UID>|ahebnl||github|<same integer id>
```
How can I update the `different UID` to be the old `UID`?

**Comment by mrakitin** [comment]
It turned out that the old UID folder disappeared from the server. Not sure why. Asked IT to recover it from backups.

**Comment by robnagler** [comment]
Very strange. It would be good to figure out her exact actions, because it may be a bug. Look for actions in the logs related to `<UID>` (the one that was in `auth.db`). 

To update the sql table to bind `<different UID>`, just do this:

```sh
echo "update auth_github_user_t set uid = '<different UID>';"  | sqlite3 auth.db
```

There is a `user_registeration_t`. It would be good to get the contents of this so you can see what may have happened:

```sh
echo 'select * from user_registration_t;' | sqlite3 auth.db
```

**Comment by robnagler** [comment]
We don't delete UID folders. The migration just updates the sqlite tables.

**Comment by mrakitin** [comment]
> Very strange. It would be good to figure out her exact actions, because it may be a bug. Look for actions in the logs related to `<UID>` (the one that was in `auth.db`).
> 
> To update the sql table to bind `<different UID>`, just do this:
> 
> ```shell
> echo "update auth_github_user_t set uid = '<different UID>';"  | sqlite3 auth.db
> ```
> 
> There is a `user_registeration_t`. It would be good to get the contents of this so you can see what may have happened:
> 
> ```shell
> echo 'select * from user_registration_t;' | sqlite3 auth.db
> ```

@robnagler, I replied in a private issue https://github.com/mrakitin/sirepo-services_cpu-001/issues/1. Please let me know if you can see it.

@ahebnl's actions were as follows:
- we got the beta image (which was associated with the `beta3` branch, but we didn't know about it)
- configured the auth using the vars from https://github.com/radiasoft/sirepo/issues/1626#issue-439235184
- she attempted to login, but she got an fresh set of default simulations
- then we figured out that we were using a wrong image (https://github.com/radiasoft/sirepo/issues/1669#issuecomment-493210331), changed to that image, and restarted the services. An still can't see her old simulations.

**Comment by robnagler** [comment]
I can't see the private repo.

We didn't plan for forward compatibility in the beta3 branch for the new auth, which has yet to make it out of alpha. This means that if @ahebnl was on the new auth, then went back to the old auth, it would have cleared cookies and given her a new login.

**Comment by mrakitin** [comment]
@robnagler, I added you as a collaborator to that private repo. Do you mind to try it again?

There was the old auth method used in beta3, however, the we attempted to use it with the new env vars, while image did not "know" about the new auth method. So, it reset the cookies due to the inconsistent set of env vars.

What happened with the missing user folder is another question, but we were able to recover it.
