### ISSUE TITLE
Light demo page of SRW

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1677]
@ochubar, @ahebnl and me are interested in getting the light page of SRW back to the landing page interface. Right now there is no link on the landing page, but I still can access it with https://beta.sirepo.com/light. For occasional users it may be the first place to check the possibilities of the package.

**Comment by bruhwiler** [comment]
We can maintain the presence of the SRW 'light' page at its present URL, but we won't link it from the new Sirepo landing pages.

It can be referenced from the Github wiki or other locations.

**Comment by ochubar** [comment]
That's very pity. I used this "light" mode every time to explain basics of Synchrotron Radiation and Wave Optics to visitors, candidates for positions, and even some beamline scientists. Right now the "landing" SRW pages shows some "boring" set of folders; and it's difficult to show in ~2 clicks what SRW / Sirepo can really do.
Also, images in this page: 
https://beta.sirepo.com/en/xray-beamlines.html
don't look physically "conventional" for someone who understands a Synchrotron / Undulator Radiation (UR) and X-ray optics:
- in the single-electron spectrum (upper image), spectral range does not cover the resonant photon energy of UR harmonic (whereas in the multi-electron spectrum it does);
- in the lower (CHX beamline) screen snapshot, the initial wavefront of Undulator Radiation is strongly off the resonance; nobody uses the UR this way (or one could think that the code is not calculating the UR correctly...);
- in the same image, NSLS-II CHX beamline guys usually don't place "Zone Plate" at sample position; normally, a simulation finished by some "viewpoint"; this "Zone Plate" it could be simply removed.

**Comment by bruhwiler** [comment]
Thanks very much for your comments, Oleg.

On Fri, May 17, 2019 at 3:34 PM Oleg Chubar wrote:

> That's very pity. I used this "light" mode every time to explain basics of
> Synchrotron Radiation and Wave Optics to visitors, candidates for
> positions, and even some beamline scientists. Right now the "landing" SRW
> pages shows some "boring" set of folders; and it's difficult to show in ~2
> clicks what SRW / Sirepo can really do.
>
The page will still be there for you to use.

We're happy to consider alternate examples, if you think the present
choices are uninteresting.
Can you please recommend the 3 most interesting examples, from your point
of view?

Also, images in this page:
> https://beta.sirepo.com/en/xray-beamlines.html
> don't look physically "conventional" for someone who understands a
> Synchrotron / Undulator Radiation (UR) and X-ray optics:
>
>    - in the single-electron spectrum (upper image), spectral range does
>    not cover the resonant photon energy of UR harmonic (whereas in the
>    multi-electron spectrum it does);
>    - in the lower (CHX beamline) screen snapshot, the initial wavefront
>    of Undulator Radiation is strongly off the resonance; nobody uses the UR
>    this way (or one could think that the code is not calculating the UR
>    correctly...);
>    - in the same image, NSLS-II CHX beamline guys usually don't place
>    "Zone Plate" at sample position; normally, a simulation finished by some
>    "viewpoint"; this "Zone Plate" it could be simply removed.
>
>
Thanks for these comments.
We will look into making the suggested improvements.

**Comment by bruhwiler** [comment]
@bnash -- please review this issue.  This request is not urgent, but it is important.

**Comment by bruhwiler** [comment]
These examples will soon be removed from the landing pages.
