### ISSUE TITLE
SRW: PNG Export images are distorted

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#1688]
The icons are appearing distorted in the png export of the beamline:
[Gaussian-X-ray-Beam-Through-Perfect-CRL.pdf](https://github.com/radiasoft/sirepo/files/3218647/Gaussian-X-ray-Beam-Through-Perfect-CRL.pdf)

**Comment by bruhwiler** [comment]
Please provide the URL for a simulation that demonstrates this behavior.

**Comment by messamer** [comment]
https://beta.sirepo.com/srw#/beamline/pcvm6Qg5

**Comment by messamer** [comment]
I am using Safari 12.1 on MacOS 10.14.4.

Another example:
https://beta.sirepo.com/srw#/beamline/Mw2xtDvk

![Focusing-Bending-Magnet-Radiation](https://user-images.githubusercontent.com/29441306/58360531-7955fe00-7e46-11e9-8b1d-d5059f808d25.png)

**Comment by nickgoldring** [comment]
The exported PNGs do not come out distorted for me.   I'm using Chrome (Version 74.0.3729.169) on Windows 10.

![Boron-Fiber-CRL-with-4-lenses-2](https://user-images.githubusercontent.com/32494032/58360728-9a6b1e80-7e47-11e9-82b7-677759903b5b.png)

![Focusing-Bending-Magnet-Radiation-2](https://user-images.githubusercontent.com/32494032/58360739-9f2fd280-7e47-11e9-85bd-e645911d6e24.png)

**Comment by bruhwiler** [comment]
The image is downloading correctly for me when using Win10 / chrome.

However, I have a different (but related) problem when using Win10 / edge:

![image](https://user-images.githubusercontent.com/3825435/58360840-1ebda180-7e48-11e9-8035-d911915b9e2d.png)

The simulation URL for the above image is here,
https://beta.sirepo.com/srw#/beamline/4BRVi3mh

**Comment by messamer** [comment]
More data: Looks fine with Chrome, Opera, and Firefox on on MacOS 10.14.4.

**Comment by moellep** [comment]
The download icon is intentionally hidden for Win10 / edge due to SVG bugs in that browser. 

I'm not able to reproduce the problem with Safari using Safari 12.1.1 on Mac 10.14.5.
