### ISSUE TITLE
SRW: Examples versus other pre-loaded simulations?

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#1689]
I suspect there is history on this that I just don't know: Why aren't all of the preloaded simulations for SRW filed under "examples"? 
![Screen Shot 2019-05-24 at 3 46 01 PM](https://user-images.githubusercontent.com/29441306/58358216-3c383e80-7e3b-11e9-8b31-2ddc0cfc159a.png)

**Comment by bruhwiler** [comment]
The other 3 directories correspond to what is linked from the "SRW light" page here,
https://beta.sirepo.com/light
