### ISSUE TITLE
link to rslinac on startup page

### ISSUE THREAD

**Issue by seregaxvm** [radiasoft/sirepo#1691]
Link to [rslinac](https://github.com/radiasoft/rslinac) is missing from [sirepo](https://beta.sirepo.com/) page. It seems that the only way to get to the interface is to jump to the [url](https://beta.sirepo.com/hellweg) directly.

**Comment by bruhwiler** [comment]
Thank you for reporting this problem @seregaxvm 

We are temporarily removing RsLinac / Hellweg from the suite of Sirepo-supported applications.
In the near future, the application will not be found on the public Sirepo server.

Users are recommended to build the latest version of Hellweg from it's native GitHub repository,
   https://github.com/radiasoft/rslinac
and compile it on Windows with Embarcadero's C++ Builder.
