### ISSUE TITLE
rslinak possible memory leak

### ISSUE THREAD

**Issue by seregaxvm** [radiasoft/sirepo#1692]
Application seem to have a memory leak.

Way to reproduce:
1. Run application locally
```bash
mkdir -p /tmp/sirepo_files
docker run --rm -p 8000:8000 -v "/tmp/sirepo_files:/sirepo" radiasoft/sirepo:latest
```
2. Go to the [http://0.0.0.0:8000/hellweg](http://0.0.0.0:8000/hellweg). Select `RF Fields` example.
3. In `Simulation setting` set `Number of Mesh Points` to high number (500).
4. Repeatedly click `Start simulation`

On my machine application consumed about 1Gb of memory per clink, never releasing it.

**Comment by bruhwiler** [comment]
Thank you for reporting this problem @seregaxvm 

This appears to be a bug in the version of rslinac / Hellweg that was ported to Linux and built with the GNU compiler.  This was a prototype effort for a short-lived project and we do not have the resources to update it.

Therefore, we will temporarily remove this code from the suite of Sirepo-supported applications.

If you build the latest version of Hellweg from it's native GitHub repository,
   https://github.com/radiasoft/rslinac
and compile it on Windows with Embarcadero's C++ Builder, then you will see correct behavior.
