### ISSUE TITLE
Provide support for optical element coatings

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#17]
For a horizontally deflecting mirror (HDM), and for mirrors in general, it's important to support the properties of coatings.

For example, a virtual beamline may only be valid up to ~9.8keV, because at higher energies the coated HDM will not reflect the beam.

**Comment by bruhwile** [comment]
First, this needs to be implemented in Python.
There might be an existing example.
Once this is understood, then Sirepo implementation would require upload of a file.
Necessary data would have to be extracted from a database.
XOP (ray optics framework from ANL) supports this feature.

**Comment by mrakitin** [comment]
This is far from implementation and probably it will not be addressed before April 2017. For tickets like this one we may want to create a separate milestone and take care of them if/when the project is extended.

**Comment by bruhwiler** [comment]
We no longer have the resources to complete this issue.
