### ISSUE TITLE
Circular Mode for EPU

### ISSUE THREAD

**Issue by dhidas** [radiasoft/sirepo#1709]
https://github.com/radiasoft/sirepo/blob/081595df256d40fbc7959614689d64ad2bc745d4/sirepo/template/srwl_uti_brightness.py#L101

Setting phix and phiz to zero does not give the correct flux when both kx and kz are nonzero.  These are the phase offsets for an EPU (+pi/4, -pi/4 for circular).  Commenting these two lines out (letting the input phi* propagate) seems to give the correct result for circular polarization.

I'll also note that when I add these parameters to the web interface it calculates the brightness/flux for many harmonics, but in circular mode there is only 1.  I'm not sure if there was a switch for "circular" mode that I may have missed.

**Comment by ochubar** [comment]
Thanks.
Yes, there is an issue with Flux / Brightness calculation for helical undulators in srwl_uti_brightness.py. This needs to be carefully debugged / compared with the corresponding calculation in the Igor version of SRW, which calculates this correctly (e.g. note that flux at fundamental of helical undulator is higher that of a planar undulator with same period and effective K).

There is also some ambiguity related to initial phases of the field harmonics (phix and phiy) and their symmetry states. E.g. if one defines Horizontal field in Sirepo as "anti-symmetric" and Vertical field as "symmetric" (as this is normally the case in APPLE-II type EPU), this automatically creates effective phase shift between the two field harmonics equal to Pi/2 even at phix=0 and phiy=0, which is formally correct, however is probably ambiguous / error-prone. If the symmetry states of the two field components are the same, than the phase shift between them is ~(phiy - phix).
Maybe we could add a non-editable box, same as "Effective Deflecting Parameter", right after it, for the "Effective Phase Shift between Vertical and Horizontal Fields", that would show a correct value respecting the field symmetry state(?).

Another (perhaps better?) possibility would be indeed to define only (one) phase shift between the vertical and horizontal field components (which won't depend of their symmetry states).

**Comment by dhidas** [comment]
Thanks.  I also wanted to ask, perhaps this is about nomenclature, but in the python brilliance calculation the "horizontalDeflectingParameter" is zero for a device where there is only a vertical field (the example in sirepo).  Bvert -> Khor.  Does horizontalDeflectingParameter here mean "caused by horizontal field" instead of deflection direction?  Is it correct in the example?

            (x, y) = srwl_und_bright_en(
                0.5, # electronBeam.current
                0.0, # undulator.horizontalDeflectingParameter
                1.65776086, # undulator.verticalDeflectingParameter
                0.0, # undulator.horizontalInitialPhase
                0.0, # undulator.verticalInitialPhase
                harmNum,
                3.0, # electronBeam.energy
                lam_u, # undulator period in cm
                nPer,
                0, # epeak not used
                0.0, # brillianceReport.detuning
                0.00089, # electronBeam.rmsSpread
                3.0, # undulator.length
                3.3331666625e-05 ** 2, # electronBeam.rmsSizeX
                2.91204395571e-06 ** 2, # electronBeam.rmsSizeY
                1.65008250619e-05 ** 2, # electronBeam.rmsDivergX
                2.74721127897e-06 ** 2, # electronBeam.rmsDivergY
                0.0, # undulator.horizontalDeflectingParameter
                1.65776086, # undulator.verticalDeflectingParameter
                0.2, # brillianceReport.minDeflection
                100, # brillianceReport.energyPointCount
            )

**Comment by bnash** [comment]
Hi @dhidas and @ochubar. Thanks a lot for looking at this and for the comments, @dhidas.  Apologies for slow response on this.
Yes, it looks like setting phix and phiz to zero is a bug.  

@moellep, can you fix this, please?  Lines 101 and 102 in [srwl_uti_brightness.py](https://github.com/radiasoft/sirepo/blob/081595df256d40fbc7959614689d64ad2bc745d4/sirepo/template/srwl_uti_brightness.py#L101) just need to be commented out, or deleted, as @dhidas mentions above.

Regarding other ways of defining the phases, I don't have a strong opinion at this time.

For the elliptical case, its not clear to me why there is only one harmonic.  Do either of you have a quick argument or reference?

**Comment by moellep** [comment]
I've removed the two lines in srwl_uti_brightness.py now with 35fbddc.

**Comment by bnash** [comment]
Thanks Paul!
