### ISSUE TITLE
warpvnd: red: Invalid color string

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1716]
The Two Poles example is now raising a javascript error on the Source tab:
```Possibly unhandled rejection: red: Invalid color string```

This is related to the new plotting modulateRGBA code. In cases like this where there is no color modulation, the text color name should be accepted.

**Comment by mkeilman** [comment]
Since this affects three strings in one line of code for one app, should we just use hex like everywhere else?

**Comment by moellep** [comment]
Whatever is easiest to fix, I think.
