### ISSUE TITLE
warpvnd: particle trace and impact density reports broken

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1717]
Two Poles example on the Visualization tab, two reports are failing on the server:

```ValueError: Object arrays cannot be loaded when allow_pickle=False```

**Comment by mkeilman** [comment]
See #1673.  I think for our purposes just allowing pickle is fine until numpy gets their act together - not sure it's worth it to craft a workaround (```savetext()``` does not work on 3d arrays).  It's a security issue though...

**Comment by mkeilman** [comment]
Actually since we are already using h5py elsewhere, might as well just do that.
