### ISSUE TITLE
SRW: Arbitrary magnetic source data files appear incorrect

### ISSUE THREAD

**Issue by nickgoldring** [radiasoft/sirepo#1729]
All except one (ivu21_srx_g6_2c.dat) of the data files available by default in the drop-down list for arbitrary magnetic sources are not valid magnetic field files.  They appear to be mirror slope error files and cause a "list index out of range" error when selected.

![sirepoArbitrarySourceSelection](https://user-images.githubusercontent.com/32494032/59952359-194c7a80-9439-11e9-824b-ac56a6816331.PNG)

**Comment by moellep** [comment]
closed with f461331
