### ISSUE TITLE
warpvnd: Field Comparison 3d slice position

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1734]
Introduce a feature which tells the user what coordinates the lineout is being taken from. One option discussed is adding an inset plot showing the cross-section of the domain and the location of the lineout coordinate. For example, a z lineout would show the x-y domain with a position at (xmiddle, ymiddle).

**Comment by robnagler** [comment]
Fix https://github.com/radiasoft/sirepo/pull/1762
