### ISSUE TITLE
SRW - Hide simulation grid link on source page

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#175]
The "Initial Wavefront Simulation Grid" setting should only be available on the beamline page.

**Comment by mrakitin** [comment]
The grid link should be removed from the source page and all the reports should have their unique parameters (#602 should take care of them).

**Comment by mrakitin** [comment]
Fixed in https://github.com/radiasoft/sirepo/commit/91d2abe2d1118213fdc7b19f81cee425b9100c74 for #602.
