### ISSUE TITLE
zgoubi: add support for fixed field accelerators in Zgobui

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#1757]
An example of the FFAG keyword is here
https://github.com/radiasoft/Zgoubi-Workshop/blob/master/Tutorials/Monday/TutMo3/Ex-0-lattices/kek_150MeV_radialFFA.dat

An example with the FFAG-SPI keyword is here
https://github.com/radiasoft/Zgoubi-Workshop/blob/master/Tutorials/Monday/TutMo3/Ex-0-lattices/raccam_spiralFFA.dat

Incidentally, although Zgoubi uses the keyword FFAG, there is an effort in the community to use FFA instead for an acronym describing fixed field accelerators.  If it is not difficult, I'd suggest using FFA and FFA-SPI in Sirepo.

**Comment by moellep** [comment]
Implemented with 926b9b8, 40ec9b9, and 2a214d3.
