### ISSUE TITLE
Add SIREPO_SERVER_CODES=srw:warp

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#176]
Want to be able to control which codes are loaded in the server to allow users to have only a few codes installed in their runtimes.

**Comment by mrakitin** [comment]
I think this feature should be accompanied by the correct `about` page with hidden descriptions of the codes which are not available.

Ideally, I would propose to have a separate description file (html?) for each code which will be inserted to the main page.

**Comment by mrakitin** [comment]
@robnagler, can you please have a look at d946fb1? I tried to implement it via `sirepo/template/__init__.py` since I don't know how to share cfg values between modules, so that it could be defined in `server.py`. Does it look like a reasonable solution?

**Comment by mrakitin** [comment]
Implemented in:
- d946fb1
- 95319be
- 771f8ec
- 33a259e

**Comment by mrakitin** [comment]
The build failed (https://travis-ci.org/radiasoft/sirepo/builds/211949800) due to http://x-server.gmca.aps.anl.gov/ is not available at the moment. I'll restart the build after some time.

**Comment by mrakitin** [comment]
The build is fixed - https://travis-ci.org/radiasoft/sirepo/builds/211949800.
