### ISSUE TITLE
simulation_db save_simulation_json() race condition

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1761]
Anytime the sirepo-data.json file gets updated, it should avoid a race condition by writing to a tmp file and then moving the file to the destination.

This would fix problems where the simulation list is being created while an individual simulation is being written.

I've seen this in zgoubi when a simulation is imported, then redirected to the main simulation page which loads the simulation list for related simulations, but at the same time the app is saving updated simulation data. That causes the list to show an exception when reading the new simulation data file. This problem doesn't appear to the user or cause a problem other than adding an exception stack trace to the logs.

**Comment by robnagler** [comment]
Atomic writes implemented.
