### ISSUE TITLE
elegant: running parameter optimization in Sirepo

### ISSUE THREAD

**Issue by tanweihou** [radiasoft/sirepo#1767]
Hi,

I tried running an optimization simulation with elegant in Sirepo but it did not work. The simulation was done without any problem but I could not see the optimization result, such as optimized parameters.

My optimization example is shown in the link below.
[https://beta.sirepo.com/elegant#/control/fVEN4GnV](https://beta.sirepo.com/elegant#/control/fVEN4GnV)

Thanks.

**Comment by moellep** [comment]
There are two places to see the optimized values. The values are printed at the end of the elegant log file which you can find by selecting the download icon on the Simulation Status window and then the Elegant Log File link.

![Screen Shot 2019-07-19 at 1 23 17 PM](https://user-images.githubusercontent.com/6516910/61560068-7a5f7200-aa28-11e9-853e-d095f2e0f50f.png)

Also, you can access the saved lattice with the optimized values by selecting the "save_lattice.filename.lte" from the File selector on the Output Parameters panel and then selecting the download icon.

![Screen Shot 2019-07-19 at 1 25 19 PM](https://user-images.githubusercontent.com/6516910/61560138-ac70d400-aa28-11e9-9eb8-b2685b187fc8.png)

**Comment by tanweihou** [comment]
Is it possible to view the output parameter or save_lattice directly in Sirepo instead of downloading them?

For example, after running the optimization, I might want to use optimized lattice parameters to rerun the simulation, and then view the output plot.

**Comment by bruhwiler** [comment]
Thanks for the good suggestion @tanweihou 

I've created a feature request here:  #1768

**Comment by tanweihou** [comment]
@bruhwiler Here's the example that I mentioned in previous post.
https://beta.sirepo.com/elegant#/control/HpMFR3Da
First run - optimization
Second run - tracking
(It does not work cus elegant in Sirepo cannot read the output from its first run.)

Thanks all for the help.
