### ISSUE TITLE
preserve Last Modified time

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1776]
When viewing the the simulation list using "View as List" on the Simulations page, the "Last Modified" column is very useful to sort on recently used simulations.

When a new release is done which requires a fix-up, the modified date gets reset on all simulations after the fix-up is applied, making the "Last Modified" useless.

Either the last modified should get moved to meta data within the sirepo-data.json file and updated in server saveSimulationData(), or the fix-up should restore the mtime on the file when it has completed.

I think I prefer moving the last modified into sirepo-data.json. @robnagler, do you see an advantage one way or the other?

**Comment by robnagler** [comment]
I think we should put it in the json. This will require modifying the write routine to update it on changes, but we already have to do that with serial number.
