### ISSUE TITLE
Broken Simulation Link

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#1788]
I had a simulation that was originally generated back around 07/17 and has been used by collaborators occasionally since then. It appears to have broken at some point, though I don't think I've touched it. 

Link was: https://beta.sirepo.com/elegant#/lattice/rYlxSDkT

**Comment by moellep** [comment]
I didn't find rYlxSDkT simulation in the online backups as far back as 5/18, but I did find many simulations which were a copy of it. I restored it from my copy and the link should work again now.
