### ISSUE TITLE
broken sirepo links

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1798]
The USPAS links for elegant and jupyter don't go to the right place anymore:

https://sirepo.com/#/elegant

https://sirepo.com/#/jupyter

From https://uspas.fnal.gov/materials/materials-downloads.shtml

**Comment by bruhwiler** [comment]
@messamer and I have started working on this.

**Comment by robnagler** [comment]
Duplicate https://github.com/radiasoft/ops/issues/380
