### ISSUE TITLE
Cannot sign in with Github account

### ISSUE THREAD

**Issue by tanweihou** [radiasoft/sirepo#1800]
Hi,

There is no option for me to sign in with my Github account.
Is this option not available anymore?
If so, how can I retrieve my previous works ?
Thanks.

**Comment by bruhwiler** [comment]
Hello @tanweihou 

Go through the new email login procedure, using the same browser that you worked with previously.

When the login procedure is complete, you will see your previous simulations.

**Comment by tanweihou** [comment]
I tried but it did not work.

**Comment by bruhwiler** [comment]
Sorry for the difficulty @tanweihou 

Our software team will have a look at the problem tomorrow and get back to you.

**Comment by moellep** [comment]
Hi @tanweihou 

It looks like you've registered twice with email - let us know which email to associate with your sirepo data and we'll restore your simulations. You can reply this this message or send a message to support@radiasoft.net with your email address.

**Comment by tanweihou** [comment]
Thanks, I just sent an email to radiasoft support.
Is this change of user authentication permanent ?

**Comment by bruhwiler** [comment]
Yes, the change in user authentication is permanent.
