### ISSUE TITLE
alpha release 8/15/19 15:40 MT

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1820]
alpha release at 1:30pm MST.

**Comment by moellep** [comment]
karma test NavController_test.js and py.test email_test.py is failing, preventing the release.

**Comment by robnagler** [comment]
* The workflow for guests includes a timeout if configured. Alpha has been configured with a 7 day timeout.
* A new guest will get an alert from #1805. NOTE: the alert  doesn't show up on all pages. We should decide first if the message is appropriate before fixing this bug.
* A guest expiry will force a page to be rendered with the text from #1805. The user must click the link to login, which will go to the normal login page without a "Sign is as guest" option. 
* If the login choice page only has one option, it goes directly to the only choice (login-with) page.

To test a guest timeout, you copy the URL in the browser, and open the `https://<host>/adjust-time/<days>` link in a new window with `<days>` set to, say, 8, which will move the time forward 8 days. Then refresh your original browser window. NOTE: **this sets the time for the whole server.**  Reset the time by calling `https://<host>/adjust-time` after you are done testing. This URL does not exist on beta or production, only on alpha and dev.
