### ISSUE TITLE
all codes:  clicking code name within the app redirects to old landing page

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1821]
When selecting the name of a Sirepo code, for example 'JSPEC' in the following screenshot:
![image](https://user-images.githubusercontent.com/3825435/63125757-aad4f600-bf6b-11e9-8651-47cd2c029586.png)
the user is redirected to one of the old landing pages, such as:
https://beta.sirepo.com/old#/jspec

This behavior is incorrect.
I suggest that the user should be redirected to
https://www.sirepo.com

**Comment by bruhwiler** [comment]
For 'elegant' and SRW, the behavior is different -- users are redirected to the relevant intermediate landing page of the new Sirepo.com

I think this behavior is correct.
However, this issue applies to all of the other codes.

**Comment by mkeilman** [comment]
Should we link to "/" so alpha users stay on alpha etc.?

Should we have links at all for these cases (the neighboring logo already links to the same place)?

**Comment by bruhwiler** [comment]
I think the best solution for now is that the code name should not be a link.

**Comment by robnagler** [comment]
Agreed.

@mkeilman we should never have absolute URLs, it should be "/", not https://www.sirepo.com.
