### ISSUE TITLE
remove question mark icon in pencil popups

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1837]
For all codes, when clicking on the pencil icon of a report, the corresponding popup window includes a question mark icon in the upper right, as seen in this screenshot:

![image](https://user-images.githubusercontent.com/3825435/63711758-6104cf00-c7f9-11e9-815a-0e5cf1e57512.png)

Clicking on these icons takes the user to a unique URL for a wiki page that doesn't exist.

I suggest that they be hidden by default. 

Perhaps some codes will want to take advantage of this capability in the future...?

**Comment by bruhwiler** [comment]
@robnagler -- I will be asking @remy278 to begin generating content for Sirepo apps in the relatively near future.

Therefore, you and I need to discuss how this type of documentation should be handled.

**Comment by robnagler** [comment]
This could be fixed to redirect through the server instead of directly to the wiki. The server could keep a list of known wiki pages and if a page didn't match, it would redirect to generic help. The GUI could also request this information from the server, and generate the link only if there was a valid wiki page. There's a caching issue so we need to maintain the list on the server so all GUIs don't have to track which pages are valid.

**Comment by bruhwiler** [comment]
Redirecting Sirepo users to a wiki page is very clunky.
Even grabbing the wiki page content and rendering it for the user within the Sirepo app would be a major improvement.
I assume there are a wide array of approaches and tools for handling interactive documentation within a browser-based app.

We should discuss during our next check-in.

**Comment by bruhwiler** [comment]
The original point of this issue should be addressed.
Pretty much every report in every Sirepo app has this question mark which, when clicked, takes the user to a blank wiki page.
This is not acceptable.

To whom should this issue be assigned?

The broader questions can be addressed systematically in new issues.

**Comment by robnagler** [comment]
Remove question mark link for now

**Comment by e-carlin** [comment]
@robnagler do you have thoughts for an implementation?

My ideas:
1. GUI makes an http request for the wiki page. If it gets a 200 back it shows the pencil icon.
2. Server stores a list of wikis (maybe in schema-common). GUI checks this list and decides.

**Comment by robnagler** [comment]
We'll address this in the ngui.
