### ISSUE TITLE
elegant: when should parallel vs serial execution be used

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1839]
With this example:

https://beta.sirepo.com/elegant#/visualization/dHI4LnPN

The simulation runs 10x faster in serial vs parallel. We need to verify that pelegant is being run correctly, and which cases pelegant scales correctly.

**Comment by robnagler** [comment]
#1864 is fixed so I think Pelegant will run fast so we should always be able to run in parallel(?)

**Comment by bruhwiler** [comment]
One can create examples where serial will be better, but I think parallel will almost always be better, so I agree -- run in parallel by default.  I would still keep the option for the user to force serial execution.

**Comment by robnagler** [comment]
@moellep sez: I think parallel execution is for advanced users. Most sims should probably use serial

**Comment by robnagler** [comment]
Advanced users can click the pencil to set it to parallel if they know what they are doing.

**Comment by cchall** [comment]
One thing to watch out for if we are going to always run in parallel is the Pelegant seems to not pass along some errors to the user properly. This will lead to simulations that mysteriously fail until you run with elegant to see what the error is.

**Comment by robnagler** [comment]
Thanks @cchall another reason to leave it as serial by default.
