### ISSUE TITLE
elegant: create beamline from selected items

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1842]
On the lattice page, it should be possible to select a range of items in the Beamline Editor panel and create a new beamline including those elements.

For example, for imported data, there may only be one really long beamline. The user should be able to select an item in the beamline and then shift-click to select and end-point and then be prompted to enter a name for the new beamline, replacing the selected elements with the new beamline.

**Comment by robnagler** [comment]
Fix 9c5c9706b33aef9690bcbcec01e0386338ce31cd
