### ISSUE TITLE
Elegant parallel not as fast as serial?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1864]
"bunchCompLSC - lattice" example ran a long time in parallel:

![Screen Shot 2019-09-02 at 12 55 34 PM](https://user-images.githubusercontent.com/5495179/64130928-9887f400-cd82-11e9-94b7-5c71301bece0.png)

I didn't let it finish, because the time wasn't updating, and I wanted to make sure the GUI was still alive (it was) and the server could cancel (it did). 

In serial it finished in 29 seconds:

![Screen Shot 2019-09-02 at 12 56 31 PM](https://user-images.githubusercontent.com/5495179/64130951-c40ade80-cd82-11e9-8e82-36e8cc382aa0.png)

One of the things I would expect is that parallel would run faster than serial or there would be no point in running in parallel. Is there a way to "know" this and not offer a parallel option?

**Comment by robnagler** [comment]
FTR, I let it finish, and it took 16:19:

![Screen Shot 2019-09-02 at 1 24 01 PM](https://user-images.githubusercontent.com/5495179/64131317-fd444e00-cd84-11e9-9759-6a42ceb06f86.png)

**Comment by moellep** [comment]
I think something is wrong with our Pelegant. See also #1839.

**Comment by moellep** [comment]
I wonder if this is related to the switch from OpenMPI to MPICH?

**Comment by robnagler** [comment]
Good point. I'll check it out.

**Comment by robnagler** [comment]
Tested with openmpi. Seemed to be the same speed.

**Comment by bruhwiler** [comment]
This bug keeps coming up.
Until it is resolved, we need to have the "Execution" input default to 'serial'

**Comment by cchall** [comment]
I tried investigating this with the first example from https://github.com/radiasoft/sirepo/issues/1839.  It appears that the poor scaling is coming from Watch elements -- which is why it doesn't show up in the second example presumably -- the two watch points take up almost the entirety of the run time.

While it is noted that Watch points don't scale well in parallel comparatively the problem seems suspiciously bad here. Running the example in parallel on Jupyter and within a beamsim container on my laptop reproduces the issue. However, running Pelegant (2019.1.1 with MPICH 3.3.2) natively on my laptop produces very different behavior with a serial runtime of 12s and parallel run time (n=4) of 5s.

**Comment by cchall** [comment]
Are there any suggestion on how this could be further investigated?

I think I am running into this problem trying to perform Pelegant simulations for fastfelo. In my case the serial run time for a simulation is >2 hours so Pelegant would be great to have working, but Pelegant is taking an incredibly long time to write watch point files. My Pelegant test has been going for over 15 minutes trying to write one file and does not appear to be complete.

Testing on my laptop shows very different timing for the Watch point file write when using Pelegant with a local install vs. inside a beamsim-jupyter container as noted previously.

**Comment by bruhwiler** [comment]
@robnagler -- please escalate the priority of this issue.
We can find resources to pay for the effort.

**Comment by robnagler** [comment]
I'm going out on a limb and going to say this is an NFS issue. alpha runs locally (no NFS), and it runs the Bunch Compression example in 9 seconds. On prod and beta I stopped them after a minute without finishing. 

I ran nfsiostat on beta, and well, that tells a pretty good story:

```txt
   op/s		rpc bklog
32313.00	   0.00
read:            ops/s		   kB/s		  kB/op		retrans		avg RTT (ms)	avg exe (ms)
		 12.000	 51.656	  4.305       0 (0.0%)	  0.083	  0.167
write:           ops/s		   kB/s		  kB/op		retrans		avg RTT (ms)	avg exe (ms)
		8083.000	3248.156	  0.402       0 (0.0%)	  0.100	  0.122
```

This is from just the one simulation. The `op/s` goes to 0, when the simulation isn't running. 

32313 operations in a second is insane. It must be fsyncing after each byte or something.

**Comment by robnagler** [comment]
This fixes it:

```txt
&global_settings                                                                                                                                      
  mpi_io_write_buffer_size = 1048576                                                                                                                  
&end 
```

@cchall please try on one of the simulations that takes a really long time and shouldn't.

The manual says "mpi_io_write_buffer_size — If non-zero, Pelegant will change the write buffer size to the given value. May allow improving write performance, but should be used with care."

I also tried these, but they had no effect:

*  inhibit_fsync = 1
* mpi_io_force_file_sync = 0
*  mpi_io_read_buffer_size = 1048576

**Comment by cchall** [comment]
That fixes it for my simulation that was giving me trouble.
The fix worked great on Jupyter. I also found the Watch write was slow on NERSC in my test today. @robnagler Should I just try setting the same size for `mpi_io_write_buffer_size` on NERSC or is there a special reason for using 1048576?

**Comment by robnagler** [comment]
I would try mpi_io_write_buffer_size to 1048576.

1048576 is 1MB. This would be a multiple of 4KB, which is often the page size for Unix file systems. It makes almost no sense to write smaller amounts nowadays. Infiniband has a 4KB MTU (probably). By writing 1MB at a time, the drive is in control of buffering, which will always give better performance.

It looks like the SDDS default is `static int32_t defaultWriteBufferSize = 0`, which means it doesn't buffer. It just writes row by row.

Obviously, buffered writes are a bad idea if there are multiple writers. From my light reading of elegant (do_tracking.c) and SDDS (SDDS_MPI_binary.c), it seems that there's a collection process (`isMaster`) so I don't think there's a big issue with buffered writes. 

The only question is if the writing will be "odd" for Sirepo. We might want to reduce the buffer size for that reason, but it should remain a multiple for 4KB. Perhaps 65536. I'll run experiments.

**Comment by bruhwiler** [comment]
In the old days at NERSC, it was sometimes necessary to specify the 'striping' for parallel I/O in some detail.  Probably different now.

@robnagler is Pelegant compiled natively at NERSC for the Shifter container?

**Comment by robnagler** [comment]
The Shifter *image* is created from the Docker image when we release so Pelegant is not natively compiled for NERSC. I don't know that this matters. I don't think elegant supports KNL. There is GPU support, which requires a special compile. There will be support for AVX-style (SIMD) x86_64 instructions, which will be generated with `-O`.

**Comment by robnagler** [comment]
[Striping is relevant](https://docs.nersc.gov/performance/io/lustre/) for greater than 1GB for shared I/O, but this is not our case either in size or the way writes happen.

You must set this on the file in advance:

> Striping must be set on a file before is written. For example, one could simultaneously create an empty file which will later > be 10-100 GB in size and set its striping appropriately with the command:
> 
> `nersc$ stripe_medium output_file`

**Comment by cchall** [comment]
Setting mpi_io_write_buffer_size to 1048576 seems to work well on NERSC.

**Comment by robnagler** [comment]
@moellep I'm not sure how we should add this to Sirepo. It doesn't seem global_settings.txt is written unless the values are different. We wouldn't want the value to be in every sirepo-data.json, but instead use 1MB if it wasn't set explicitly. Alternatively, we would always set it to what we wanted. What do you recommend?

**Comment by moellep** [comment]
At a minimum, we should add the new fields to the command_global_settings in the elegant schema. That would let the user override the defaults for sirepo simulations.

https://ops.aps.anl.gov/manuals/elegant_latest/elegantsu35.html#x43-420007.25

**Comment by robnagler** [comment]
How do we set the default differently from what is in elegant? I don't see where global_settings is written if the user doesn't add the command.
