### ISSUE TITLE
Elegant bunchCompLSC - lattice time not updating

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1865]
The time didn't update for about a minute:

![Screen Shot 2019-09-02 at 12 53 44 PM](https://user-images.githubusercontent.com/5495179/64131012-1c41e080-cd83-11e9-84ee-2d8c407ded92.png)

I see the posts to run-status every few seconds in the JS console so it seems that the GUI is running so shouldn't it be able to update the time?

**Comment by robnagler** [comment]
It seems to be updating every two minutes.

**Comment by moellep** [comment]
I believe it updates the time from the date on the output NFS file from the front-end.

I'm not currently seeing this behavior, but I have seen it in the past. We need a way to reproduce it.

**Comment by robnagler** [comment]
It probably should just use now().
