### ISSUE TITLE
webcon: improvements for talk

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1881]
Several items should be address for webcon prior to Oct. 1st:

- [x] Enable webcon on beta server
### Controls
- [x] Improve the beamline image. Add labels to the beamline items. Increase the image height to avoid the current smashed look.
- [x] Beam Settings labels should include Centroid prefix for all X and Y values. Ex. Centroid Y'
- [x] Running the Beam Steering features immediately after starting EPICS can cause an error. Instead, the Beam Steering should only get enabled for use after EPICS is verified to be fully initialized.
- [x] Responsiveness of the Controls panel is poor. Extracting data from the monitor log needs to be sped up.

Items are shown in priority order with a 40 hour cap for work. Responsiveness should be address last.

**Comment by j-edelen** [comment]
@moellep, are there any updates on this?

**Comment by moellep** [comment]
No updates on this issue yet - there should be progress made on it this week.

**Comment by j-edelen** [comment]
@moellep 

Can you change the display to read "Connected to EPICS" as opposed to "Connect to EPICS". This is causing some confusion. Same for "Use Steering", instead say "Steering On" or something to that effect.

**Comment by moellep** [comment]
Fixed and on alpha.
