### ISSUE TITLE
Deprecated GitHub user given choice to be Guest

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1883]
This happened to @bruhwiler. Tried to login, but was a GitHub login before, so validated with GitHub. Once validated, it gave two choices for (non-deprecated) login: email or guest. It shouldn't show guest at that point, because the user will lose connection with their simulations.

**Comment by bruhwiler** [comment]
I assume this issue is irrelevant now that we no longer support guest logins?

**Comment by robnagler** [comment]
Still a problem for sites that use GitHub and maybe want to deprecate some day...
