### ISSUE TITLE
2D Gaussian Beam R.M.S Divergence

### ISSUE THREAD

**Issue by twguest** [radiasoft/sirepo#1884]
Hi all,

Seeking an explanation on the current Sirepo implementation of a fully-coherent Gaussian beam, as given here:

https://beta.sirepo.com/srw#/source/nCb5mtYx

It seems that we are able to define a beam divergence along the x and y axis. As far as I am aware, this is not the case in the current SRW distribution where only a single beam-waist can be defined.

From what I can tell, the GsnBeam parameters used to generate a magnetic field.

Can anyone give me direction as to how this is implemented?

Thanks in advance
Trey

**Comment by bnash** [comment]
Hello Trey, 
Thanks for the question.  For a fully coherent Gaussian beam in the diffraction limit (M=0), the RMS size and divergence are related by sig_x sig_x' = lambda/(4*pi), where lambda is the wavelength (related to photon energy by E=hc/lambda).
Thus, by specifying either RMS size (at waist) or divergence, the other one is determined.  Sirepo has simply made it convenient to enter the one free parameter by allowing you to do so with either RMS waist or divergence using the diffraction limit condition.
Does this make sense?
Best regards,
Boaz

**Comment by bnash** [comment]
Also, @twguest, in case you want to see the interface to the Gaussian beam, this is in the python interface file srwlib.py.  The function SRWLGsnBm is [here](https://github.com/ochubar/SRW/blob/master/env/work/srw_python/srwlib.py#L700) in O. Chubar's SRW repository, which is what Sirepo works with.  As you can see, there are inputs for both the horizontal and vertical rms beam sizes at waist.  As mentioned in my answer above, if one enters divergences instead, they are translated into beam sizes via the diffraction limit condition.
