### ISSUE TITLE
Logged in with email, but still asking for login

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1885]
Here's what I see asking me to login, but note the logged in state the upper right corner:

![Screen Shot 2019-09-16 at 8 45 42 AM](https://user-images.githubusercontent.com/5495179/64967871-769c7000-d85e-11e9-963e-1ae42b184c06.png)

The auth-state is:

```js
// jshint ignore: start
SIREPO.authState = {"avatarUrl": "https://www.gravatar.com/avatar/3578ee63cedb3a9871bae2b4b278ce10?d=mp\u0026s=40", "displayName": "Rob Nagler", "guestIsOnlyMethod": false, "isGuestUser": false, "isLoggedIn": true, "isLoginExpired": false, "method": "email", "needCompleteRegistration": false, "userName": "<AVOID_SPAM>@radiasoft.net", "visibleMethods": ["email", "guest"]};
```

There are no error messages output in the log.

**Comment by robnagler** [comment]
I think this might be a history link in Firefox. I switched to FF recently, and it behaves differently from Chrome. I don't see the `#/login` in the server logs, but when I go to the address box in FF, it shows /srw#/login as the first hit. FF history is strange so I can't actually see what I did. Closing for now.

**Comment by robnagler** [comment]
Note this may be happening to users, because the link somehow got memorized. If you are logged in, /login maybe should not go to the login page, but instead redirect to the app page. @messamer what you say?

**Comment by moellep** [comment]
I haven't seen this bug, but I've heard similar complaints about logged in users being asked to log in over and over. We should bumpt the priority on this.
