### ISSUE TITLE
Find-by-name if not logged in fails

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1891]
If you are a student and not logged in and on the /light page:

https://beta.sirepo.com/light#/home

Then select a predefined example, you end up at a json output page instead of an html page:

https://beta.sirepo.com/find-by-name/srw/calculator/Undulator%20Radiation

{"state": "srException", "srException": {"routeName": "login", "params": null}}

**Comment by robnagler** [comment]
Is there a way to share code between light.js and sirepo.js?

**Comment by moellep** [comment]
The light page should probably be integrated into the srw app and not a stand-alone app. It would require a navigation to the "calculator" from the simulations page.

**Comment by robnagler** [comment]
More subtle than this. It doesn't necessarily need navigation. /light could be a normal schema entry point that renders the light page. There would be no way to navigate off that page. However, the business logic of handling requests would go through sirepo.js which would fix this particular Issue. We could add Calculator to the simulations list but I think that's a more complex question than refactoring the code to give the same behavior as it is today.
