### ISSUE TITLE
energy-dependence of CRLs does not appear to be handled correctly

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#19]
In a compound refractive lens (CRL), the energy-dependence of the refractive index increment and the attenuation length must be treated correctly.

X-ray focusing changes with energy at the observation point, but the values shown in the settings for the CRL element don’t change. It's not clear to the user how energy dependence is being handled or if it is being handled correctly.

**Comment by bruhwile** [comment]
The dependence can be weak.
Maxim and Oleg will discuss.

**Comment by mrakitin** [comment]
It's implemented in #203.
