### ISSUE TITLE
copy_related_files assumes shared file system, probably should be removed

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1901]
copy_related_files is used by api_copyNonSessionSimulation to copy "large" (animation) results from the source to target simulation directory. This works fine when all users and all results are in the same shared file system. This is an incorrect assumption for supercomputer or sbatch executions, because one user can't see another user's files. For sirepo.com, this works now, but when we switch to a tighter controlled job execution environment, it won't work. It will have to run in the server, which may or may not have access to all output files in a single file system view. (We are moving to a distributed model.)

The copy_related_files implementation was noted as problematic in #604. I also don't believe it handles staleness correctly. It simply copies results, even if they do not match the contents of a simulation's sirepo-data.json.

I think copy_related_files should go away, because it will be too hard to implement. It's not clear the feature is implemented correctly anyway.

**Comment by moellep** [comment]
It is fine to remove this feature, although it won't allow people to say "look at the simulation results I produced after 10 hours of simulation". Instead the person who receives the shared link will need to run the simulation from scratch to see any results.

**Comment by robnagler** [comment]
We could cache the graph data in sirepo-data.json, like jupyter notebooks do. The graph data will work with supercomputers, too, even with large simulations, because this has to be "transferrable".  If you change any graph parameters, the data will be lost, but the point is to solve this particular problem more generally so that it works for all graphs and all execution models.

The way it is implemented now, it only works for elegant, srw, and rs4pi.

**Comment by moellep** [comment]
See also #1070

**Comment by robnagler** [comment]
Removed copy_related_files see #2235
