### ISSUE TITLE
synergia requires elegant

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1902]
This doesn't work:

```sh
SIREPO_FEATURE_CONFIG_SIM_TYPES=synergia sirepo service http
```

You have to specify `elegant`. The elegant_lattice_importer needs the schema.

I suspect there's a larger issue here that the elegant_lattice_importer relies on elegant types being identical to synergia types.

**Comment by moellep** [comment]
The synergia app can import elegant lattice files. This feature could be guarded so it is turned off if elegant is not available. I wasn't able to reproduce the failure on dev using ```SIREPO_FEATURE_CONFIG_SIM_TYPES=synergia sirepo service http```.

**Comment by robnagler** [comment]
`rm -rf run` first, and it will run the fixups.
