### ISSUE TITLE
transverseEmittance & rmsRadius appears twice in warppba fixup

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1903]
I'm fixing up the fixups and ran into two sentinels rmsLength and beamRadiusMethod that trigger transverseEmittance & rmsRadius to be set to two different values on [line 206](https://github.com/radiasoft/sirepo/blob/b7a1e15a88e6bd93d20daf9a0ce83c4c34472aae/sirepo/template/warppba.py#L206)
and [217](https://github.com/radiasoft/sirepo/blob/b7a1e15a88e6bd93d20daf9a0ce83c4c34472aae/sirepo/template/warppba.py#L217).

My general question is if these are truly sentinels or if [all values could be setdefault](https://github.com/radiasoft/sirepo/blob/aaf42d7c828f87873efc8cc2395d5942958974e8/sirepo/sim_data/warppba.py#L75). 

And, then which values to choose, which now is the last one set.

**Comment by moellep** [comment]
warppba has old fixup code which hasn't evolved over time. I'd guess only the 2nd transverseEmittance value should be used. All the default values belong in the schema and should be set using the update_model_defaults() fixup method.
