### ISSUE TITLE
should srx beamline und_len = 2.500648?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1906]
Trying to debug a difference in the tests. The expected und_len for NSLS-II SRX beamline is 3.0 but it's producing 2.500648 in the python file. It rs_type is `'t'`, which means it is a tabulated undulator, and the [value in sirepo-data.json is 2.500648](https://github.com/radiasoft/sirepo/blob/30732a82f40552f062312e4b22fc327ce9571d53/sirepo/package_data/template/srw/examples/nsls-ii-srx-beamline.json#L669). The [new fixup seems to be doing the right thing](https://github.com/radiasoft/sirepo/blob/f81fa7da58b17fb145fa7c3c1ac5488c97cc0255/sirepo/template/srw_fixup.py#L65) by setting the tabulated value, and seems to be the same as [the old fixup](https://github.com/radiasoft/sirepo/blob/30732a82f40552f062312e4b22fc327ce9571d53/sirepo/template/srw.py#L420). 

I'm documenting here in case @moellep sees something. I'll keep debugging.

**Comment by moellep** [comment]
Yes, the correct answer is undulator.length = 2.500648

I checked and the srw_generate_test.py is running the fixup, but the tabulated zip file is not present in test dir:

srw_generate_work/db/user/x5XZwUiy/srw/lib/magnetic_measurements.zip

so _compute_undulator_length() is return an empty dict. If the zip file were present, then the result would be correct and the srw_generate_test.py would fail because it has the old 3.0 value.

**Comment by robnagler** [comment]
When I run srw_generate_test.py on master, the `lib` directory is not there so [the zipfile check in _compute_undulator_length](https://github.com/radiasoft/sirepo/blob/30732a82f40552f062312e4b22fc327ce9571d53/sirepo/template/srw.py#L1106) fails, and therefore the default value of 3.0 is used.

When run in feat/1895_refactor_fixup_old_data the zip file (and lib directory) are there, and produces the 2.500648, which is what I would expect.

The expected result (committed in srw_generate_data) is incorrect I believe, and the refactored fixup now doing the right thing. I suspect that the user wasn't being created correctly somehow in the unit test.

**Comment by robnagler** [comment]
OK, I'll debug the test on master to see why lib isn't being created.

**Comment by robnagler** [comment]
[_create_example_and_lib_files](https://github.com/radiasoft/sirepo/blob/30732a82f40552f062312e4b22fc327ce9571d53/sirepo/simulation_db.py#L999) does things in the wrong order (per its name): create examples and lib. It should create lib and examples.

The reason it works in feat/1895_refactor_fixup_old_data is that the reading of the lib directory is deferred to by `sim_data_template_fixup: true`.

**Comment by robnagler** [comment]
I'll change the code in the new branch to avoid conflicts. I'll fix the test output too.
