### ISSUE TITLE
400 BAD REQUEST error when loading simulation list

### ISSUE THREAD

**Issue by satogata** [radiasoft/sirepo#1909]
Heyos,

I just registered for sirepo with email address satogata@jlab.org, and
went to the JSPEC sirepo instance:

https://beta.sirepo.com/jspec#/simulations

It appears stuck on "Building simulation list, please wait" with a
continuous "flutter" in the address bar of the page indicating a
possible failure to load a resource. I am using Safari 12.1.2 on macOS Sierra
(10.12.6). Running web inspector indicates a continuous error message
of

[Error] Failed to load resource: the server responded with a status of
  400 (BAD REQUEST) (simulation-list, line 0)

while trying to load https://beta.sirepo.com/simulation-list. Attempting to wget this URL also results in a 400 (BAD REQUEST) error so there is something broken with this link.

**Comment by bruhwiler** [comment]
Hi @satogata -- sorry for the problems and thanks for reporting them via this issue. 

We will work to sort it out today.

My access to Sirepo/JSPEC is working fine with the latest version of Firefox on the latest version of Win10.

**Comment by moellep** [comment]
Hi @satogata,

We'll have a fix for your problem on beta.sirepo.com later today.

**Comment by satogata** [comment]
Dear Paul,

Many thanks -- checked and all works now. Cheers!

                                                 -Todd

======================================================================
Todd Satogata
Director, Center for Advanced Studies of Accelerators
Jefferson Lab
12000 Jefferson Avenue
Newport News, VA 23606
Cell: (631) 807-0674
======================================================================
