### ISSUE TITLE
Add a clear instruction for ruining sirepo in docker  

### ISSUE THREAD

**Issue by buzmakov** [radiasoft/sirepo#192]
I'll spend some time, but not find clear instruction how-to run sirepo in docker.
It will be nice to add following command in some readme file:
```
docker run -it --rm -p 8000:8000 -u vagrant radiasoft/sirepo bash -l -c "cd ~ && sirepo service http"
```

**Comment by robnagler** [comment]
Thanks @buzmakov for the suggestion. Please let me know if 
[this is a good description](https://github.com/radiasoft/sirepo#manual-install-with-docker).

Fix 973dea27eb9f1090426b32485ac1cac2fd8b6dcf

**Comment by buzmakov** [comment]
Thanks.

It will be nice also  tell user open browser at ```http://localhost:8000/light#/home```, because just  ```http://localhost:8000``` return **Not Found** page without any suggestions

**Comment by robnagler** [comment]
Done. Fixed in f4a26cd.

**Comment by mrakitin** [comment]
@robnagler, the link is not displayed correctly:
`[[http://localhost:8000/light]]`
Probably you need to use `[http://localhost:8000/light](http://localhost:8000/light)`:
[http://localhost:8000/light](http://localhost:8000/light)

**Comment by mrakitin** [comment]
I saw you changed it while I was writing my comment. Thanks.

**Comment by buzmakov** [comment]
Thanks @robnagler, 
link displayed good for me.
Who should close this ticket I'm or you ?

**Comment by robnagler** [comment]
:)
