### ISSUE TITLE
Loader shows when clicking on simulations "rapidly"

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1927]
This happens when the login page is showing. It seems that `$locationChangeStart` can happen without a `$viewContentLoaded`. This means `setPageLoaderVisible(false)` is never called.

**Comment by robnagler** [comment]
It happens every other time if you wait more than a second between clicks.

**Comment by moellep** [comment]
This is a bug with the cookie login redirect. Removing this line from sirepo.js and the problem no longer occurs:
```
$rootScope.$on('$routeChangeStart', checkCookieRedirect);
```
