### ISSUE TITLE
3D orientation mark with axis labels

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1933]
Currently the orientation mark is shown but it isn't clear what the rotation axis is:

![Screen Shot 2019-10-03 at 9 19 57 AM](https://user-images.githubusercontent.com/6516910/66140229-fb0d2380-e5be-11e9-826c-f19b5b4c468c.png)

Better would be this:

![image005](https://user-images.githubusercontent.com/6516910/66140281-124c1100-e5bf-11e9-8164-b84a9459cbb3.png)

The C++ vtk library supports this, so it may be worth waiting for vtk.js to add this. Alternatively, we would use the orientation cube instead:

https://kitware.github.io/vtk-js/examples/OrientationMarkerWidget.html

**Comment by bruhwiler** [comment]
I don't like the orientation cube.
I think the labeled arrows are great.

**Comment by mkeilman** [comment]
Three and a half years later kitware has still not implemented the axes labels in javascript so I will close this issue. The annotated cube will have to do for now. Also note that one can use any vtk Actor as the orientation widget, so presumably one could custom build something for this purpose; but I deem that out of scope here.
