### ISSUE TITLE
Avoid robots clicking confirmation links

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1937]
Outlook will automatically "click" on /auth-email-authorized links from another IP address (an MS server presumably) and this "logs in" the user and that discards the token.

We could look at the user agent string for BingPreview and ignore the request, and that would be good enough.

Alternatively, we can tell Bing not to preview with a robots.txt tag: https://blogs.msdn.microsoft.com/searchblog/2009/08/25/bing-seo-disable-hover-document-preview/

I think we should do the former, but wanted to discuss. Users who use Outlook cannot login at the moment without disabling this feature: https://support.office.com/en-us/article/use-link-preview-in-outlook-com-and-outlook-on-the-web-ebbfd8ce-d38e-40ef-bb8c-a5362e881163

**Comment by moellep** [comment]
I think this could also be a problem going forward with virus/spam scanners checking links in the email before showing them to the user. How about delay deleting the authorization token from the database until a simulation is visited, or similar user event?

**Comment by robnagler** [comment]
I think the safest approach is to put up a Javascript button that says "Login" if the cookie is not set. We are allowing "cookieless_login" at the point the link is clicked which allows for the fact that someone might go to a different browser. If they don't have a cookie sentinel, we render the button, and it's an extra step in this rare case. Bots aren't going to click the button. When the user clicks the button, the GUI sends a url with a "dammit" query string.

**Comment by robnagler** [comment]
Good enough fix 55cdb4f0043a55cc055b0733136ba4dfbd9473c2

**Comment by robnagler** [comment]
We need to try https://github.com/radiasoft/sirepo/issues/1937#issuecomment-538697416. I suspect that's why Google has the "Confirm" button on email confirmations.

**Comment by robnagler** [comment]
The confirmation page should ask for the user's name if the user hasn't registered yet. This is a bit of extra code, but would keep the user on boarding the same while verifying that the user is not a robot. I'll add this today.

**Comment by robnagler** [comment]
Implemented confirmation in 4d126b1c. @moellep please review and merge.
