### ISSUE TITLE
Denormalize srwl_uti_src.srwl_uti_src_e_beam_predef at init

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1945]
[srwl_uti_src.srwl_uti_src_e_beam_predef is called](https://github.com/radiasoft/sirepo/blob/a8b5006fdf7257820bd3f75a6e4a9538798acccf/sirepo/template/srw.py#L1482) at startup, and it requires importing srwl_uti_src, which does a lot of work, including [calling process_beam_parameters](https://github.com/radiasoft/sirepo/blob/a8b5006fdf7257820bd3f75a6e4a9538798acccf/sirepo/template/srw.py#L647), which calls srwlib.SRWLPartBeam to the the twiss params. 

The easiest way (I can think of) to untangle this is to add something like `predefined_beams` to `sirepo.pkcli.srw`, which is run at Docker image build time and adds a resource, say, `predefined_beams.json` to `package_data` before sirepo is installed. This file would then be read at startup. If not there, we could try to run the command which would work for installations that don't support Docker and for dev. For Docker, I don't think we should assume that any codes are in the Sirepo image so the file should be there (and might have to be committed at build time), but for now, we can do the build trick and/or run the command at startup.

**Comment by moellep** [comment]
Or just convert it to a static file which can be rebuilt manually when SRW changes and checked in.

**Comment by robnagler** [comment]
If SRW were to export such a file, it would be great, but this would require SRW to support some form of package_data, which it does not now. 

I think it will be easier if we keep the static file generator in Sirepo, and run it dynamically at build and/or startup time.

**Comment by robnagler** [comment]
@moellep @mkeilman @e-carlin I merged this, because it contains fixes for #1920, too. 

`sirepo srw create_predefined` is run by `container-conf/build.sh`.

If `template/srw/predefined.json` does not exist in dev, `sim_data.srw.srw_predefined` will call the above if it doesn't exist.
