### ISSUE TITLE
Various template_common.validate_model issues

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1948]
- [x] [raise Exception](https://github.com/radiasoft/sirepo/blob/1e45fb81d4f914455ca2da5ecbe798714d6022e1/sirepo/template/template_common.py#L481) should not be called. `Exception` is meaningless and is the base exception for all errors so even harder to catch in a `try`. Rather, use `AssertionError`, because this is a bug in the schema or database.
- [x] [str(value)](https://github.com/radiasoft/sirepo/blob/1e45fb81d4f914455ca2da5ecbe798714d6022e1/sirepo/template/template_common.py#L483) should protect against enum and other type errors. The enum should either be an integer or string, and only be stringified in the former case. 
- [x] [I suspect the `split` should `strip` first](https://github.com/radiasoft/sirepo/blob/1e45fb81d4f914455ca2da5ecbe798714d6022e1/sirepo/template/template_common.py#L485), because if there are spaces around the comma, there might be leading and trailing spaces (unless that is checked elsewhere).
- [x] [this `if` does nothing](https://github.com/radiasoft/sirepo/blob/1e45fb81d4f914455ca2da5ecbe798714d6022e1/sirepo/template/template_common.py#L486), just use the assert to throw the exception.
- [x] [`if not value`](https://github.com/radiasoft/sirepo/blob/1e45fb81d4f914455ca2da5ecbe798714d6022e1/sirepo/template/template_common.py#L490) is not robust against None, but probably should be, unless we treat None as 0.
- [x] [`value = 0`](https://github.com/radiasoft/sirepo/blob/1e45fb81d4f914455ca2da5ecbe798714d6022e1/sirepo/template/template_common.py#L491) is incorrect, it should be `0.` because the type is a float. This would save the conversion.
- [x] [`v /= 1000`](https://github.com/radiasoft/sirepo/blob/1e45fb81d4f914455ca2da5ecbe798714d6022e1/sirepo/template/template_common.py#L494) should be `1000.`. In py3, it's especially important not to mix types in division.
- [x] [final `float(v)`](https://github.com/radiasoft/sirepo/blob/1e45fb81d4f914455ca2da5ecbe798714d6022e1/sirepo/template/template_common.py#L502) is unnecessary, because `v` should already be a float by the first assignment.
- [x] [`if not value`](https://github.com/radiasoft/sirepo/blob/1e45fb81d4f914455ca2da5ecbe798714d6022e1/sirepo/template/template_common.py#L504) is not robust against None or other non-integer values (False, for example). I think we require the value to be a valid integer and not implicitly converted.

**Comment by mkeilman** [comment]
For ints, how forgiving do we want to be?  Do we want to generate an error if someone provides 1.0 instead of 1?

**Comment by robnagler** [comment]
I think on input in the GUI, we want to be flexible. Once it's in `data`, it should match the type of the schema.

If a field is optional, it could be null/None. However, we want then to leave it as null/None, or set it to the default value, or?

That's what I don't know.

**Comment by moellep** [comment]
I think we require a value for Integer, Float, String, but not for OptionalString for example.

Most of this is historical - most of the fixups should already be occurring to set missing values. There were some cases in earlier apps (SRW, warppba) where an enum might have a int value rather than a string value. It can be assumed that enum values are now always strings.

**Comment by robnagler** [comment]
@mkeilman @moellep you should get in agreement about this code. If you fix the None issue, that's fine, I'll just deal with the merge.
