### ISSUE TITLE
radia remove old print methods

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1958]
The printDoubleValues(), printIntValues(), printFloatValues() and floatToDouble() methods can all be removed from radapl6.cpp:

https://github.com/robnagler/Radia/blob/feat/objgeometry/cpp/src/core/radapl6.cpp#L169

**Comment by robnagler** [comment]
fix https://github.com/robnagler/Radia/commit/2a73384243c947792d40f108ad4a0c05f7af161b
