### ISSUE TITLE
JSPEC: New Force Formula option

### ISSUE THREAD

**Issue by sjcrs** [radiasoft/sirepo#1961]
![Screen Shot 2019-10-23 at 11 17 03 AM](https://user-images.githubusercontent.com/55888605/67417729-b0ac1080-f586-11e9-8dc4-ea50c4b2586b.png)

The DC Cooling Example for JSPEC code should include a new Derbenev-Skrinsky option for the force formula. This drop-down appears within the Rate Calculation -> Electron Cooling window in the example.  This should come after the pull request titled "Coleman dev" within radiasoft/electroncooling has been completed.

**Comment by bruhwiler** [comment]
Effort can be charged to MCOOL

**Comment by moellep** [comment]
Do we want to build sirepo's JSPEC from radiasoft/electroncooling, rather than zhanghe9704/electroncooling? If so, the radiasoft fork needs to be updated from zhanghe9704 - it looks like radiasoft is 6 commits behind.

**Comment by bruhwiler** [comment]
Yes, I think we agreed that we would start building from radiasoft/electroncooling

@sjcrs -- please update the RadiaSoft fork from zhanghe9704/electroncooling
Update this issue when that has been completed.

**Comment by sjcrs** [comment]
RadiaSoft master has been merged with upstream zhanghe9704/master

**Comment by moellep** [comment]
This is available on alpha now. Selecting Derbenev-Skrinsky for the DC Cooling example changes the Beam Evolution report:

![RMS-Ion-Beam-Evolution](https://user-images.githubusercontent.com/6516910/68231579-90357a80-ffb8-11e9-915a-548174cd458c.png)

![RMS-Ion-Beam-Evolution-1](https://user-images.githubusercontent.com/6516910/68231591-9297d480-ffb8-11e9-8db7-2d46bac28934.png)

If someone can create an good simulation using the new force method, I can add it to the list of predefined examples.

**Comment by sjcrs** [comment]
Hi Paul,
I want to cross-validate this new model against an external package, so
please do not let this out of alpha yet. Should I just reply to this email
chain when this model is OK'd for promotion?

Thanks,
-Stephen C

**Comment by moellep** [comment]
Yes, just comment on this issue with the status. We can keep the feature on alpha for now.

**Comment by sjcrs** [comment]
There is one small bug fix that will be coming soon that should bring these two trends into agreement. The plots you shared were the diagnostic that pointed to the problem, thanks! 
Along those lines, if I wanted to add another plot to the JSPEC visualization tab based on a new function within JSPEC, what should that function output look like and how do we define the new plot? It will be force values as a function of velocity.

**Comment by bruhwiler** [comment]
If you are making plots in a Jupyter notebook, then you can share screenshots and/or share a link to the notebook

**Comment by sjcrs** [comment]
I'm mostly trying to make sense of how the ecooling_rate function is being handled within the ui.cc file as an example. The function I have to calculate forces as a function of velocity needs to store a table somehow, most likely as arrays in memory, and I don't understand how the plot data is currently being stored for the existing plots.

**Comment by moellep** [comment]
If I understand the question correctly - jspec writes the out the cooling info to stdout, when you run, something like this:

```
$ jspec jspec.in
Coasting ion beam created!
Ring created!
Electron beam created!
Cooler created!
IBS rate (1/s): 4.934e-04  2.194e-04  2.078e-04
Electron cooling rate (1/s): -7.406e-03  -7.509e-03  -1.255e-02
Total expansion rate (1/s): -6.913e-03  -7.290e-03  -1.234e-02
```

Sirepo then reads the log file to get the info for the Rate Calculation panel. For the plots, Sirepo reads the output files, created using the output_file name from the section_simulation in the jspec ui file. That is written in the jspec file dynamic.cc as a SDDS file. JSPEC will also write out ionsXXX.txt SDDS files when the section_simulation.model is "particle".

**Comment by sjcrs** [comment]
Yes, thank you, you understood my question. I will create a new issue when a new pull request to JSPEC is successful and there are new output files ready to be read in for plots.

**Comment by bruhwiler** [comment]
@sjcrs -- can the new capabilities discussed above be released to production?

Can this issue be closed?

**Comment by sjcrs** [comment]
I would like to push the most recent electroncooling master to push to alpha to confirm this change is fixed before it all moves to production

**Comment by robnagler** [comment]
I will be building a new beamsim image this week, which can include jspec. We already build master (radiasoft fork) so should be a simple task. Shall I do this?

**Comment by sjcrs** [comment]
Will this be a new image for alpha only? If so, then yes please.

**Comment by robnagler** [comment]
Yes, alpha only. It will have to wait till the current alpha makes it to production.
