### ISSUE TITLE
Sirepo Interface Issues 

### ISSUE THREAD

**Issue by smlund** [radiasoft/sirepo#1977]
I tried making an elegant simulation and passing to another person via the link.  When the person clicks that link he or she first gets an account login (if cookie not loaded in the browser).  Then this stops.  If they click the link again they get the relevant files copied to their user space correlated with email.    This is confusing if they are new.   You might want to address it.  

Also, it would be nice if the jupyter server could directly see files from sirepo to ease cross use.  As students learn more they may want to make use of the setup files and run directly.  This would make that more seamless and benefits might occur from going back and forth. 

Thanks! Steve

Professor Steven M. Lund
Director, US Particle Accelerator School / FNAL
Michigan State University / FRIB
517-908-7291
lund@frib.msu.edu

**Comment by messamer** [comment]
There are two items in this issue: a bug in paragraph 1 and a feature request in paragraph 2,  Any objection to creating a separate issue for the feature request?

**Comment by bruhwiler** [comment]
@messamer -- yes, please create a separate issue for the feature request regarding interoperability between Sirepo and Jupyter. Something similar may already exist, so please look first.

Regarding the 'bug' for new users who are following a simulation link, this is not a software bug, strictly speaking. I consider this to be a feature request as well.

**Comment by smlund** [comment]
No objection to splitting.

Steve

**Comment by robnagler** [comment]
Covered by #4179
