### ISSUE TITLE
Sirepo/Elegent/Juypyter extension suggested 

### ISSUE THREAD

**Issue by smlund** [radiasoft/sirepo#1978]
Yue Hao at MSU could be coHao, Yue <haoy@frib.msu.edu>ntacted for python scripts he has to interface with elegant for improved lattice setup and diagnostic processing.  He said he would be happy to donate these to get started and they might be a significant bonus to the jupyter server capability for more advanced users.  He did a very nice job with these and we used them in our MSU and USPAS class on grad accelerator physics.  He said they would benefit from professional software user maintenance and extensions.  

Yue Hao's contact info from MSU:
Hao, Yue <haoy@frib.msu.edu>
517-908-7524

We would also likely use these in grad accel physics classes at USPAS including the class on simulations that David is involved in. 

Thanks! Steve

Professor Steven M. Lund
Director, US Particle Accelerator School / FNAL
Michigan State University / FRIB
517-908-7291
lund@frib.msu.edu

**Comment by bruhwiler** [comment]
Thanks for this suggestion @smlund 
I've emailed Yue to request his Python scripts.

I will continue tracking this issue here, but in the future it would be great if you could post issues related to the RadiaSoft JupyterHub server here:
https://github.com/radiasoft/jupyter.radiasoft.org/issues

**Comment by smlund** [comment]
Ok.  Will do on the separate jupyter server posts in the future.

**Comment by robnagler** [comment]
#4179
