### ISSUE TITLE
elegant: upgrade version to 2019.3.0

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/sirepo#1981]
elegant needs to be upgraded to version 2019.3.0 -- this contains a bug fix for backwards propagating through an SBEN, which has been an issue on a project.

**Comment by robnagler** [comment]
I assume this is also needed for jupyter?

**Comment by sdwebb** [comment]
If it's not hard it wouldn't hurt whenever you were planning the next update.

**Comment by robnagler** [comment]
Jupyter https://github.com/radiasoft/jupyter.radiasoft.org/issues/62

**Comment by robnagler** [comment]
On Sirepo alpha (#1988) but no date as yet to get on Prod.
