### ISSUE TITLE
Sirepo Elegant extension request 

### ISSUE THREAD

**Issue by smlund** [radiasoft/sirepo#1986]
It would be nice if Sirpeo/elegant could load a KV distribution.  I was loading uniform distribution in x and y and in this case if you look at things like x-y projections you get nonuniform square distributions.  It is easiest to interpret uniformly filled elliptical projections in all 2-d subspaces of 4d phase-space.  If this option could be made available, it could help students.  

I first thought uniform in x-x' and y-y' should load this but it does not.  

Thanks!
Steve

**Comment by bruhwiler** [comment]
Thanks for the input @smlund 
This is a very reasonable request.
elegant provides a real variety of particle distributions, but not KV

The Sirepo/elegant philosophy to date has been that the GUI should expose the native elegant capabilities and not try to extend them.

Of course, we could add a KV option that would invoke some Python code on the server to generate an SDDS file with this particle distribution. However, this feature doesn't really fit into any of our funded projects at the moment. 

I'll discuss this issue with our product manager and I'll look for an appropriate funding mechanism.

**Comment by smlund** [comment]
This is probably not important for most elegant code users and relates more for student applications.  I can understand not developing extensions in the interface.   Maybe the better thing could be to pass requests like this to Borland (give code example to implement even) and see if he will.
