### ISSUE TITLE
job execution can be parallel or serial based on data (not just report)

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1994]
Need to make jobs dynamic. For now, just relying on jobs being statically parallel. This works with #1993, because elegant's simulationMode is always "is_parallel" even when simulationMode is serial.

**Comment by moellep** [comment]
I think is_parallel really means is_background_job. It should probably get removed and all processing should be done off the report name instead.

**Comment by moellep** [comment]
Or maybe this is a different reference to is_parallel - I'm referring to template.write_parameters() which should remove is_parallel.

**Comment by robnagler** [comment]
we need to know when to run in a parallel (multi-core) environment. that should be used consistently whether it is OpenMP or MPI or possibly even CUDA/OpenCL. 

There is another problem, technically, that sequential (serial, one core) jobs can take some time to run, but I don't think that's solvable easily.

background should be renamed to parallel.

transient should be sequential.

persistent should be parallel.

while we're at it:

errors in background_percent_complete should be app_log_errors (or something like that).

**Comment by robnagler** [comment]
I'm working on this, and I think the value "serial" should be changed to "sequential" in the schema. We can still display Serial, but it's parallel and sequential in sirepo.job.

**Comment by robnagler** [comment]
sim_data.is_parallel answers the question, but it isn't implemented in the codes yet except for srw. Codes need to implement. It's something we should do when we run into it.
