### ISSUE TITLE
when compute_job != report, minimizing one report, cancels all

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1999]
A user gets the output `No output was generated for this report.` in four windows, say, when you cancel a long running elegant (sequential) simulation on the source page.

**Comment by e-carlin** [comment]
@robnagler I can't reproduce this. It seems to me that the simulation is run by one of the other reports and proceeds as normal.

**Comment by robnagler** [comment]
Not getting "cancel all", but I am seeing "ERROR: Terminated unexpectedly" when clicking around a lot. The agent is probably removing the run directory while it is being read.
