### ISSUE TITLE
Line graph should zoom with mouse

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2]
When you are over the line graphs, you should be able to zoom and pan with the mouse like you can with the 3d (heatmap) plots.

**Comment by bruhwile** [comment]
More generally, the zooming should emulate (at least to some extent) the matplotlib interface, unless D3 enables something even better.

Likewise, the UI should allow control for min/max of the axes.

**Comment by bruhwile** [comment]
Closing this to avoid confusion.
Will refer to it from related issue (# 45)

**Comment by moellep** [comment]
Re-opening this issue. Need matplotlib-like improvements to 2d plots. Zooming is especially important.
