### ISSUE TITLE
api_downloadDataFile needs startTime and computeJobHash?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2017]
@moellep how does api_downloadDataFile avoid caching issues? There isn't a startTime or computeJobHash as in #1557

**Comment by moellep** [comment]
It looks like there is a caching issue. It should probably be set as no-cache on the server.

**Comment by robnagler** [comment]
I think it would be good to standardize the frame_id here, too.

**Comment by robnagler** [comment]
We just turned off caching.
