### ISSUE TITLE
Background job reports probably should be queued

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2018]
When a background job completes, the GUI requests all reports simultaneously. This takes up N flask threads. If we allow users to make their own background reports (#1975), then we will be opening up the server to too many simultaneous requests from a single user.

Ideally, the GUI would use websockets, and then this wouldn't matter, because all requests would be queued by flask or job engine. We're going to add queuing in the job engine for reports (have to) so this is only a problem for flask right now.

**Comment by robnagler** [comment]
@moellep am I mistaken about this? Are the report requests serialized?

**Comment by moellep** [comment]
The behavior indicates that every request is being handled serially. One background report request completes and the next one begins.
