### ISSUE TITLE
Schema or app version change should cause GUI reload

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2023]
There are a lot of protocols to keep track of:

* computeJobHash is a value that depends on a number of things specific to the app (sim_data._compute_job_fields, how it is computed, etc.) (#1944)
* animationArgs depends on new parameters being added and parameter order
* frameId depends on new parameters being added and parameter order (#1557)
* fixup_old_data can cause report directories to be out of date (#1973)

And, the GUI itself depends on how the server responds. We aren't at the point where we have so many simultaneous users that we can't reload the page on a server release (in frequent in any event). 

I think therefore that if the app or schema version changes, it should cause the GUI to reload. This would solve a lot of code for dealing with varying versions of these parameters. 

@moellep @mkeilman @e-carlin please discuss

**Comment by robnagler** [comment]
The silence is deafening so I'm doing away with versions in query strings/paths without a discussion.

The GUI currently pings the server regularly with autoSaveTimer. I'm not sure if makes sense to put the check there, or to have an explicit ping.

**Comment by e-carlin** [comment]
I think doing a reload makes sense.

Regarding reload on save what do we do with running/pending simulations during a release? To the best of my knowledge a save doesn't happen between runSim and simulationFrame. I can imagine a scenario where we do a release in the time between runSim and simulationFrame. Params regarding simulationFrame could change in the release but the GUI won't be reloaded.

**Comment by robnagler** [comment]
Everything is restarted during a release. Releases are fast so we just wait for a quiescent period.

That is a good point about simulationFrame. It really has nothing to do with runSim. It has to do with the schema being cached in the browser, and api_simulationFrame using a different (new) schema. Cache invalidation is the hardest thing in computer science, next to naming. :)

I would say that we can get away with doing releases for a while before we run into this issue. We can fix it by issuing a challenge-response to the GUI after a release. The flask server can hold the state of all GUIs (for now) in memory.

For job support, this is going to need some thought in general, because we are going to have to retain job state between releases.

**Comment by robnagler** [comment]
Duplicate of #238, but I'll close the older one

**Comment by robnagler** [comment]
I've implemented this, but it needs a better UI. It renders a server upgraded page and redirects immediately. I didn't think it would be good to have a button that says "Reload". It should just reload. The probably is that it shouldn't return to the current location (that's kind of unknown, because saves happen in background) so it would be better to just go back to the simulations list. 

Also, first release will break apps, because there is no such route (serverUpgraded). I don't think this is a big deal, because people will just refresh, but would be good to test on alpha to see how the app behaves.
