### ISSUE TITLE
avoid login loops

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2024]
There are a few odd cases where login loops occur:

* User comes into the app with a cookie uid which isn't valid. The app tries to log them out which puts it into a login loop.

* User's user dir is deleted and visits the simulations page. 

In these cases the auth state should get reset.

**Comment by moellep** [comment]
This problem still occurs in this case:

User is logged in. Delete the user's user directory on the server. Navigate to the simulations page or to an simulation. This causes the client to get into a login loop where the client thinks the user is logged in, but the server sends back a login redirect which causes a request loop.

Changing the requestSender.handleSRException to reload the app would fix this problem.

**Comment by robnagler** [comment]
call_api is not saving the cookies when a response an exception. That's part of the problem.

**Comment by robnagler** [comment]
It seems that browsers don't follow [RFC 6265](https://tools.ietf.org/html/rfc6265) and do not save cookies when a 400 is returned. There's very clear text about this: 

> User agents MAY ignore Set-Cookie headers contained in responses with 100-level status codes but MUST process Set-Cookie headers contained in other responses (including responses with 400- and 500-level status codes). 

SRException was using 400, which is also a major cause of a login loop. When it returns 200, it works. I'll change the code.

**Comment by robnagler** [comment]
I don't think there are any more loops
