### ISSUE TITLE
webcon doesn't use get_simuation_frame?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2029]
There's correctorSettingAnimation in get_simulation_frame, but I don't think this exists as it is not referenced in webcon.js. There is a correctorSettingReport.

@moellep is there no need for get_simulation_frame?

**Comment by moellep** [comment]
It should exist, but doesn't. Currently the reports reach into the epicsServerAnimation directory for data, see template/webcon.py get_settings_report(). Instead they should be one-frame animations.

**Comment by robnagler** [comment]
I'm fixing get_simulation_frame so I'm going to remove it (or comment it out  if you like).
