### ISSUE TITLE
Monitor simulation disk usage

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2056]
If a simulation consumes over a configured amount of disk, stop the simulation, and report an error to the user that the simulation used more than the configured amount of disk space.

The job agent will have to monitor disk by polling. It can be implemented for the local agent for testing, but is only reasonable for the docker agent. It will not be implemented for the NERSC or SLURM agents, because those have Unix users bound to a Sirepo user, which allows for normal Unix quotas, which is outside the scope of this request.

It's like the configuration will be on a per job driver type basis

This will be implemented after the job code has gone into alpha.

**Comment by dtabell** [comment]
In some cases, it is possible to estimate—on the basis of various
parameters in the simulation—the amount of disk space a given
simulation will consume. Can we warn the user in advance if
that disk usage will put them over the line?

**Comment by robnagler** [comment]
This would be ideal, but I don't think we can do that for the 10(ish) codes we support so we need a more robust method.

**Comment by robnagler** [comment]
Duplicate of #1312
