### ISSUE TITLE
get_data_file reaches back to simulation_db 

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2065]
For example, get_data_file for beamlineReport needs "data", which comes from sirepo-data.json, which is "not there" on NERSC and sbatch-systems so need to ask for that remotely or use another entry point (not get_data_file).

**Comment by robnagler** [comment]
@moellep which code is this? I couldn't find beamlineReport.

**Comment by moellep** [comment]
I don't this would apply anywhere anymore - the reports all have the in.json available directly in their own directory.
