### ISSUE TITLE
Job execution and extraction speed

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2091]
The job execution code is slower than the old runner code. There are several reasons for this:

1. multiple serialize-deserialization hops
2. job_cmd process starts on each request
3. polling "moire" effects: the GUI polls the server, and job_cmd polls the simulations

I think (2) is fairly significant. We tried to mitigate (2) yesterday by increasing the polling frequency in job_cmd, but I'm not sure it made a difference.

I think (1) can be solved as we are solving for data files: sending the results directly to a file on the server, which is then returned to the client. There doesn't need to be any deserialization once it leaves job_cmd until it gets to the GUI.

(2) can be fixed by having job_cmd start once and communicate with the agent via domain sockets. I think job_agent should remain a separate process, and job_cmd can run multiple requests. Simulation executions still need to be separate processes.

(3) would be solved with IPC between job_cmd and job_agent and WebSockets between the server and the GUI. This has been known for some time.

There's little need to pass the simulation data through the supervisor/agent. The in.json file could be saved in an appropriate tmp directory, and requested like a lib file. Personally, I think in.json should not exist and instead, the simulation should be saved, computeJobHash is computed, and that info is passed on including the simulationSerial, report, etc. via the agent. The rest is requested remotely as a file.

The server and supervisor should be one process. The only reason it is two processes is due to py2/3 differences and the fact that the server still does things it shouldn't be doing. There should be no template calls in the server, just in job_cmd.

These are big architectural issues, which can't be solved now. I'm just noting to start a discussion.

**Comment by robnagler** [comment]
job_agent could run codes directly. It's in a secure user context so it's fine to run directly. We can't do that now, because job_agent is async py3, and job_cmd is stuck on py2. If we upgrade to py3, this becomes less of an issue.

Most of the codes (except synergia) already run in py3. This includes the SDDS functions.

We should still run compute jobs as separate processes, because they need to be monitored by a separate process for reliability. Any crashes (OOM, SEGV, etc.) need to be independent of agent, plus the compute process might need to be killed for usage reasons. This is best done by the agent. 

The assumption is that simulation outputs and get_application_data are not going to crash the agent and are not going to put an undue burden on resources. This is a reasonable assumption, and the agent can always be killed if this is not true. Having the codes run directly in the agent will improve performance.

So, I think the py3 upgrade is one of the most important things we can do right now.

**Comment by robnagler** [comment]
I implemented job_cmd for OP_ANALYSIS as a continuous process in 54708584. Performance improved dramatically. Slowest time was 0.12s and fastest was 0.018s. 

It's a rudimentary implementation, but it should even work at NERSC. It uses unix domain sockets to send messages between job_agent and job_cmd.

I'll work on it more tomorrow.

**Comment by robnagler** [comment]
Another approach I just tried is to get `job_cmd` working in py3. I got stuck on this:

```txt
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 246, in sim_frame_dispatch
    res = o(frame_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/elegant.py", line 355, in sim_frame
    page_count=page_count,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/elegant.py", line 541, in _extract_report_data
    title=_plot_title(xfield, yfield, page_index, page_count),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 291, in heatmap
    hist, edges = numpy.histogramdd(values, histogram_bins(model['histogramBins']), range=None)
  File "<__array_function__ internals>", line 6, in histogramdd
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/numpy/lib/histograms.py", line 1052, in histogramdd
    smin, smax = _get_outer_edges(sample[:,i], range[i])
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/numpy/lib/histograms.py", line 324, in _get_outer_edges
    first_edge, last_edge = a.min(), a.max()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/numpy/core/_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: '<=' not supported between instances of 'map' and 'map'
```

The error is being produced by `numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so`, and it doesn't make any sense to me. I didn't see anything obvious in google. 

Porting to py3 is forward looking, but it will take longer than making 5470858 reliable.

**Comment by robnagler** [comment]
alpha is still slower than prod for returning data, but only a "little bit". Just refresh a page with a lot of reports to see the difference. It's a few seconds for CHX source page vs a second. 

One thing we may want to consider is building in a graph cache in the supervisor. I would like to wait though until we see if eliminating job_api (by dropping Flask, removing one hope) will improve performance. That has to wait until py3, which is very important, and maybe we will want to eliminate fastcgi if we can reduce yet another hop.

**Comment by moellep** [comment]
The example from #2222 is running much better on alpha now. Frames are coming back under 100ms now rather than 3 seconds.
