### ISSUE TITLE
clarify how a user should download the Python source

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#21]
It's not clear to users how they download the Python source when they are done working with the GUI.

I wrote the following instructions for one user:

You can download a complete working Python script for executing SRW in exactly the way it is being executed on the cloud-based server:
   a) When you are done working with the GUI for a particular simulation, and you are ready to download the corresponding Python script, click on the "Simulations" link that you see near the upper left in your browser. Before clicking it, note the title of your simulation, which is written just to the right of this link.
   b) On the simulations page, look for the rectangle corresponding to your title. Don't click directly on the title, which is a hyperlink to open the simulation, but instead click anywhere else in the corresponding rectangle. You will see that the selected rectangle has been highlighted.
   c) When this rectangle is highlighted, the links along the top of the page are activated. Click on the button "Python Source" to download the SRW Python script.

This is not intuitive, and it greatly diminishes the value of a great feature.
More importantly, it's possible for users to accidentally download the Python script for a different simulation, which would be really bad. Hence, this is a real bug.

One suggested fix is to make the "Python Source" button available on all tabs.

Another suggestion is that the main simulation tab should highlight the simulation that has been used most recently.

**Comment by robnagler** [comment]
I would simply have a button or clear link: "Export Python Code" -- not
"Source" which can be confusing with "Source".  Lots of text is not going
to help users.

The download button shouldn't be on the management page imiho. We need a
concept of "management functions" on the simulation page. We could use the
traditional model of "File" (copy, delete, export python code") and
"Window" (to switch to source or beamline or other page). Not thrilled with
this, but this is a model people understand.

Rob
