### ISSUE TITLE
canceled sim can lead to frame server error

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2107]
When you cancel a simulation, further actions cause a server error which redirects to the sirepo home page rather than the server error page.

To reproduce: Run the Laser Pulse warppba simulation and cancel after 5 frames or so. Then select the editor on the field animation and change the mode from "1" to "0". After selecting Save Changes, a server error is caused with this info:

```
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sim_data/__init__.py", line 101, in parse_frame_id
    res.computeJobStart = int(res.computeJobStart)
../sirepo/http_reply.py:233:_gen_exception_error unsupported exception=<type 'exceptions.ValueError'> msg=invalid literal for int() with base 10: ''
10.10.10.1 - - [11/Dec/2019 21:46:48] "GET /simulation-frame/4*fieldAnimation*vRS3vsXg*warppba***E*x*0 HTTP/1.1" 200 -
```

The browser is then redirected to /#/error rather than /warpbpa/#/error

**Comment by robnagler** [comment]
Same as #355. If the parameters change, the reports are invalid so they shouldn't be requested, and the app should show "report not generated".

I can make this change, but I think @messamer and @bruhwiler should approve.

**Comment by messamer** [comment]
I am unable to replicate the original scenario you describe.

**Comment by bruhwiler** [comment]
I think this issue is fundamentally different from #355

If I'm correct, then this issue should be fixed without further discussion.

On the other hand, it might be a good idea to discuss #355.

**Comment by messamer** [comment]
Just chatted with Rob- I think he agrees they aren't the same.  Would be
good to talk through #355

**Comment by robnagler** [comment]
Technical: the computeJobStart is not getting into the frame id. Need to figure out why.
