### ISSUE TITLE
JSPEC: Promote force calculation to a primary window

### ISSUE THREAD

**Issue by sjcrs** [radiasoft/sirepo#2110]
Currently, the force formula drop-box is hidden within the edit (pencil) button of the rate calculation window, then in the second Electron Cooling tab. Since this choice has a large effect on the resulting visualizations, Ilya and I request that the drop-box be promoted to one of the main windows. I think the Cooler window would make sense, and does not currently have any drop-box options. 

Another option would be to place all of the IBS and electron cooling fields inside the rate calculation pencil in another primary window alongside Ion Beam, Cooler, Ring, etc.

**Comment by moellep** [comment]
I moved the fields from the Rate Calculation editor into a new panel, with the Force Formula on the first tab:

![Screen Shot 2019-12-12 at 11 40 26 AM](https://user-images.githubusercontent.com/6516910/70739542-500e9980-1cd4-11ea-9eca-6b0ee6065450.png)

This will be available on alpha in the next alpha release.
