### ISSUE TITLE
JSPEC: Add new plot the visualization tab

### ISSUE THREAD

**Issue by sjcrs** [radiasoft/sirepo#2112]
The recent pull request accepted to the master of https://github.com/radiasoft/electroncooling generates a new file in the run directory in SDDS format called force_table.txt.  This calculates force as a function of velocity for a fixed electron number density. One new figure should be generated in the Visualization tab to show two plots, with the values:

Plot    x-axis       y-axis
1 .       V_trans     f_x
2 .      V_long      f_long

By convention, the forces are multiplied by -1 prior to plotting. I can imagine this being controlled with a scale factor field in the "Edit" section of the plot, auto-filled with -1 so the user could change this if desired. This is how BETACOOL handles it.

An example of the values of two plots separated is shown here:
![image](https://user-images.githubusercontent.com/55888605/70736187-03739000-1ccd-11ea-8e73-e09d03592be9.png)

**Comment by moellep** [comment]
This is implemented as a single report and allows choosing the columns to plot, so transverse or longitudinal plots can be calculated. The Booster Ring example has been updated so it now uses a Bunched Beam cooling electron beam so the new report will be shown for that example.

This will be available on alpha soon.

![Screen Shot 2020-03-02 at 3 06 15 PM](https://user-images.githubusercontent.com/6516910/75728961-97d70880-5ca6-11ea-9180-a053c6325678.png)

![Screen Shot 2020-03-02 at 3 05 55 PM](https://user-images.githubusercontent.com/6516910/75728967-9ad1f900-5ca6-11ea-8c8b-89a49828ca0a.png)

It looks like the V_trans value isn't sequential, so the f_x/V_trans report jumps around:

![Screen Shot 2020-03-02 at 4 53 36 PM](https://user-images.githubusercontent.com/6516910/75728970-9c9bbc80-5ca6-11ea-9914-7b0026d886c2.png)

**Comment by sjcrs** [comment]
Great, thanks! To fix the issue with the non-sequential values, would it be easier to implement if the transverse and longitudinal values were in separate sorted files?

**Comment by moellep** [comment]
It is OK for the data to be out of order - I'll have sirepo resort the data. I just wanted to check if that was the correct thing to do. I also noticed the "Vtrans" label should be "Transverse Velocity" on the plot above.

**Comment by moellep** [comment]
I've corrected the order on the V_trans plot and changed the report parameters slightly. Instead of choosing the columns, you now choose between transverse and longitudinal plots:

![Screen Shot 2020-03-03 at 12 01 11 PM](https://user-images.githubusercontent.com/6516910/75809914-c60c2500-5d46-11ea-8ec0-a0e488ce2a26.png)

The transverse report now renders correctly:

![Screen Shot 2020-03-03 at 12 01 20 PM](https://user-images.githubusercontent.com/6516910/75809919-c99fac00-5d46-11ea-8e53-71bc800d23dd.png)

When #965 is implemented, it will be possible to view both plots simultaneously.

This will be on alpha.sirepo.com shortly.

**Comment by moellep** [comment]
This is available on alpha.sirepo.com now. You can try it on the Booster Ringer example by selecting Discard Changes to Example from the cog wheel menu. Or you can change any simulation to use a Bunched Beam for both the Ion Beam and Cooling Electron Beam.
