### ISSUE TITLE
zgoubi: interface goes non-responsive

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#2114]
After inserting a TOSCA element into the beamline I just see '502 gateway errors' for everything but the beamline setup. I cannot even get the Python source or export to zip.

Presumably there is problem with the field map uploaded, but it is hard to tell what is happening.

Simulation link: https://www.sirepo.com/zgoubi#/lattice/nDkp8lvC

**Comment by moellep** [comment]
This uncovered a bug in sirepo when dealing with single file tosca files. It also uncovered a limitation in zgoubi where the file header must be <= 9 lines.
