### ISSUE TITLE
SRW - autorun animated Flux report for fast cases

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#213]
Need to run the animated Flux report automatically without pressing the start button in the case when the calculation is fast, e.g., `Flux Computation Method` is set to `Use Approximate Method` (=`-1`).

For more details about fast/slow calculations please see #189.

**Comment by moellep** [comment]
When "Use Approximate Method" is selected, the report should behave like a normal, short-running report. The start button and elapsed time should not be displayed and the report should auto-run. The simulationStatusPanel directive will need special code to handle this.
