### ISSUE TITLE
SRW import fails with chx export file

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2131]
Export the idealized undulator CHX example python source, and then import the file into sirepo. Causes the server error:

```
sirepo: error: unrecognized arguments: srw run /home/vagrant/src/radiasoft/sirepo/run/user/X6K7SQXI/srw/koNuR2a8/backgroundImport
```

**Comment by moellep** [comment]
It looks like the srw import fails if main() is called directly, as the current code is, rather than the old generated code. Production exports the code with the "if", dev does not.

```python
if __name__ == '__main__':
    main()
```

**Comment by robnagler** [comment]
`use_sys_argv=True` is the problem. One fix would be to set sys.argv to empty before making the call in the importer. I think it should be false always.
