### ISSUE TITLE
improve job supervisor/agent logging

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2135]
The supervisor should log more, e.g. which runDir is being used.

**Comment by e-carlin** [comment]
With op_run log the run_dir on the supervisor side.

**Comment by robnagler** [comment]
I still think this is not good enough. I would like the agentId and other ids to be shortened as I think we have in job_supervisor. This can be most easily done by a pkdebug_str. I think we can shorten uids to. I think we should print a lot more of these ids on every request. 

I don't think we should not output run_status. it clutters and doesn't help.
