### ISSUE TITLE
Interoperability between Sirepo and Jupyter

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#2137]
Separating two requests previously documenting in Issue #1977.  This appears to be related to #723 and #648

"Also, it would be nice if the jupyter server could directly see files from sirepo to ease cross use. As students learn more they may want to make use of the setup files and run directly. This would make that more seamless and benefits might occur from going back and forth.

Thanks! Steve"

Professor Steven M. Lund
Director, US Particle Accelerator School / FNAL
Michigan State University / FRIB
517-908-7291
lund@frib.msu.edu

**Comment by robnagler** [comment]
Covered by https://github.com/radiasoft/sirepo/issues/4179
