### ISSUE TITLE
cancel sim causes "report not generated"

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2144]
In warppba, start a simulation on the Dynamics page, let a few frames complete and then select End Simulation. Then select the "first frame <<" button on either report.

```
../sirepo/http_reply.py:240:_gen_exception_error unsupported exception=<type 'exceptions.ValueError'> msg=invalid literal for int() with base 10: ''
10.10.10.1 - - [30/Dec/2019 22:55:40] "GET /simulation-frame/0*particleAnimation*4tCoM2V9*warppba***z*x*219*0*0*-5*5*0*0*0*0*0*0*0*0 HTTP/1.1" 200 -
```

**Comment by robnagler** [comment]
Regression of #2107?

**Comment by moellep** [comment]
Yes, the example from #2107 is also failing.

**Comment by robnagler** [comment]
There is a test for this, but it does [allow for `not generated`](https://github.com/radiasoft/sirepo/blob/c4c29a18ba82cd4e0953640246d7e301c78d3cb9/tests/partial_animation_test.py#L49), which may not be correct. Before it was throwing a server error.
