### ISSUE TITLE
run elegant under mpi in background

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#215]
This is added in 9e7e941 in "robnagler" branch. The progress bar doesn't update, because there is no output in mpi. Not sure we can trust stdout in the logs, especially over NFS.

**Comment by bruhwile** [comment]
I think the option to switch between Elegant and PElegant would be greatly
appreciated.

**Comment by robnagler** [comment]
Not sure I understand. Wouldn't they always want it to run in parallel?

**Comment by bruhwile** [comment]
As you noted, there is no diagnostic output from Pelegant, which is the
right thing to do when running in parallel.
There will be times when people want the diagnostic output.

Some people always use Elegant, not Pelegant.
They will likely want to switch back and forth before trusting Pelegant.

In any case, I agree that defaulting to Pelegant is the right choice.
We can wait for users to request access to Elegant running in serial.

**Comment by robnagler** [comment]
I think there is diagnostic output, but it doesn't come out in real time. I
don't think we show that real time output in the gui, but you can look at
the log after the run. I think the reason the output doesn't come out is
due to buffering. There may be a trick to turn off buffering in Pelegant
(FLUSH_INTERVAL), but it needs to be tried out, and it may not work on NFS
in any event. This will only affect the progress bar, not what the user
sees.

It would be good to hear from people who actually use elegant.

**Comment by bruhwile** [comment]
Agreed, we need user input.
The beta test site is being widely advertised via professional contacts.
