### ISSUE TITLE
SRW - Define propagation parameters outside of the set_optics() function

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#216]
It used to be a subtask of #85 - Define propagation parameters outside of the `set_optics()` function as it's done in virtual beamline scripts by @ochubar. Need a separate ticket to implement it.

**Comment by mrakitin** [comment]
This is an important issue and should be addressed soon.

**Comment by mrakitin** [comment]
Too many 1st priorities, reduce priority to 2nd. Will take care of it after other 1st priority issues are solved.

**Comment by moellep** [comment]
Fixed with #1052
