### ISSUE TITLE
GUI server upgrade redirect loop

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2160]
I just saw a redirect loop on a logged in screen with just a refresh. The server had upgraded, but it kept trying to upgrade. Was not able to reproduce in other windows.

Related: #2130 #2071

**Comment by robnagler** [comment]
Tricky to reproduce. The GUI should check for a change in the version after a save or get simulation data, and then call the server upgrade code. It currently only happens if you save a simulation that was with an old schema version after modifying some parameter.

**Comment by e-carlin** [comment]
I can't reproduce this. I've tried a variety of codes with no success. Any more insight into the cause?

**Comment by robnagler** [comment]
It doesn't happen in Firefox due to the [100ms lag on reload](https://github.com/radiasoft/sirepo/blob/feb3d8ffe9e51a5467abcb10858109a45a9d9f21/sirepo/package_data/static/js/sirepo.js#L1629). Changing it so that it is 100ms for Chrome, avoids the problem.

The issue is that window.location.hash [remains the same across reloads](https://stackoverflow.com/a/10612657). The localRoute is then `#/server-upgraded`, and it loops.

I think hash persistence may be the root of all the problems. With the following code, the page seems to reload (ignoring the cache) and there's no need for the call to `reload()`:

```txt
        var i = u.indexOf('#');
        if (i >= 0) {
            $window.location.hash = u.substring(i);
            u = u.substring(0, i);
        }
        else {
            $window.location.hash = '#';
        }
```
