### ISSUE TITLE
docker run parallel gets error in log but runs ok

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2163]
ENOENT on /home/vagrant/src/radiasoft/sirepo/run/user/OgYc1xQf/srw/z2JSQASj/multiElectronAnimation/in-zDQK6GWzhLReBigvr0g7RTVRXkUKNKWt.json.

To reproduce:
* Youngs Double Slit
* Start
* Run a bit
* Stop
* Start

**Comment by e-carlin** [comment]
Will be fixed by #2164
