### ISSUE TITLE
elegant: parallel execution not stopping at error

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#2168]
When a simulation is run with execution:parallel it appears that Sirepo does not automatically stop and report when elegant ends with an error. Stopping manually does display the error message from elegant. Running in serial automatically stops and displays the error.

See: https://www.sirepo.com/elegant#/source/EUPo9N5i

**Comment by cchall** [comment]
Has this been fixed?

**Comment by robnagler** [comment]
Seems to report errors:

```txt
*** Warning: Changing the particle type is not a fully tested feature---. Please be alert for results that don't make sense.
unknown token: (0.2e-6
error scanning value (0.2e-6 0.04133 / 4 /) for namelist member emit_ny
unknown token: /)
unknown token: (0.2e-6
unknown token: /)
unknown token: (0.2e-6
unknown token: /)
```
