### ISSUE TITLE
Agent start timeout

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2171]
If we start an agent but it never connects we will be blocked forever (stuck in '_agent_starting' state). We need to set a timeout between when we start the agent and receiving a websocket connection. If the timeout expires the misbehaving agent should be killed and a new one started.

**Comment by robnagler** [comment]
_AGENT_STARTING_TIMEOUT_SECS should be sirepo.job_driver.sbatch/docker/local.cfg.agent_starting_secs. The default should be job_driver as a constant (multiplied by 3 for sbatch). cfg should be initialized on the class (SBatchDrive.cfg) so it can be accessed easily from job_driver.

**Comment by robnagler** [comment]
@e-carlin get_supervisor_uri could then be pulled directly from cfg so that would simplify things.
