### ISSUE TITLE
Report not generated on top of simulation screen

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2199]
Not pretty:

![Screen Shot 2020-01-21 at 8 26 34 PM](https://user-images.githubusercontent.com/5495179/72863042-6ec95e00-3c8c-11ea-97c1-eaafe362eb94.png)

**Comment by robnagler** [comment]
Add jobRunMode to runStatus. Can call sbatchLogin to force agent start or will return immediately if  already started.

**Comment by moellep** [comment]
This appears to be fixed.

**Comment by robnagler** [comment]
Still happening on alpha:

![Screen Shot 2020-02-10 at 1 28 01 PM](https://user-images.githubusercontent.com/5495179/74187163-3f619d80-4c09-11ea-8b62-a367df74dff7.png)

I visited alpha, then went to an existing nersc simulation, and it asked to login. Then, it got this, because the sbatchlogin returned "error", and the GUI didn't retry. Refreshing worked.

**Comment by robnagler** [comment]
I think this has been fixed.
