### ISSUE TITLE
Login with email page for new users

### ISSUE THREAD

**Issue by sjcrs** [radiasoft/sirepo#2205]
When doing Sirepo demos between lectures at USPAS, I noticed some friction for new users at the email submission form. Something along the lines of "Oh no, what am I signing up for?"  This is a gentle suggestion for a change to the text above the email box with a little more context to alleviate that friction. Maybe like "We will start up your sandbox in the cloud and email you the link"

**Comment by bruhwiler** [comment]
@messamer -- what is the priority of this issue?

**Comment by messamer** [comment]
@bruhwiler  given it is easily addressed, I would rate it high.

Current Interface:
Enter your email address and we'll send an authorization link to your inbox.

Suggested Interface:
Your email address serves as the user ID for your workspace.  
Enter your email address and we'll send a link to your inbox.
