### ISSUE TITLE
Previously loaded source files not found

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#2212]
I imported a new elegant simulation, with a number of supporting files, and then decided I needed to change the lattice file and use a lattice I exported from another Sirepo simulation  so I started a new import.
The new import did not request any of the previously uploaded supporting files, though it does seem the name of the wakefield file in the lattice I downloaded from Sirepo was changed (to WAKE-inputfile.knsl45.liwake.sdds from knsl45.liwake.sdds) and I had to rename a copy of that file and re-upload it.
Finally, when trying to run the simulation fails with a complaint that it cannot find one of the previous source files (PCG.sdds) that appears to have been renamed to bunchFile-sourceFile.PCG.sdds in the excuted file.

See: https://www.sirepo.com/elegant#/control/4fsGkH9f

**Comment by moellep** [comment]
I verified the bug - the elegant import is broken if multiple input files are required. The software is crashing while the first file is being validated, which prevents the additional files from being uploaded. This bug is fixed in development and should go to production soon.
