### ISSUE TITLE
Application Error: TypeError: Cannot read property '_type' of null.

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#2213]
When trying to add new commands in the elegant control tab I keep seeing this message. The new command then often seems to disappear from the list.

**Comment by moellep** [comment]
I see those errors in the logs now. It looks like the client got into a bad state. The simulation data looks OK on the server. Please try reloading sirepo (Cmd-R in Firefox or Chrome) in the browser and see if the error continues. If you find the "_type" error is reproducible, reply to this comment with the steps.

**Comment by cchall** [comment]
Looks like the issue has disappeared.
I had tried refreshing previously before submitting and it seemed to go away for a moment but then returned so far so good right now.
When it first showed up I was setting up a new load_parameter command, but after it first showed up it seemed to just be constantly popping up.
