### ISSUE TITLE
animation frames query is 60 times slower on alpha

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2222]
On alpha, I've noticed the report frame requests take a lot longer, possibly related to the new execution engine. Response time is around 3 seconds vs 50ms for the same plot frame on beta2.

An example test case is elegant fourDipoleCSR example. Run the simulation and then on the B4 plot, adjust the Frames per Second from 2 to 10 and then play the animation. You can change the Vertical fields selection to avoid the browser cache on multiple tests.

**Comment by robnagler** [comment]
I'd say this was a duplicate of #2091.

**Comment by moellep** [comment]
I though #2091 was related to running a simulation, vs getting the data. This elegant frame could be a test case for this.
