### ISSUE TITLE
cookieRedirect is broken

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2223]
The cookie redirect code is broken on alpha. If a logged-out user follows a simulation link for another session, the "/simulations" url is being saved in the cookie, rather than the actual simulation link. So when the user logs in, they end up on the /simulations page rather than on the "copy simulation" page.

**Comment by robnagler** [comment]
`api_simulationData` is a GET, not a POST so `sirepo.http_reply._gen_exception_reply_SRException` does not know that it can safely return JSON so it returns a Javascript redirect to `#/login`.

It is possible to modify authState, and the app seems to work so we'll go to a dynamic model for logging in that doesn't require a refresh (reload).

Therefore, `saveCookieRedirect` needs to be called, and the javascript redirect can be a local redirect, like `#/error`. I think srException could add state into `javascript-redirect.html` that could be parsed as JSON, and that's probably the best approach.

**Comment by robnagler** [comment]
Fix f70f37f8
