### ISSUE TITLE
Can't get rid of `invalid jobRunMode=sbatch`

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2231]
In https://github.com/radiasoft/sirepo/pull/2229 we added the ability to configure the jobRunMode and alert the user if the server changes the valid set of run modes (ex no longer supports sbatch). If the server has sbatch enabled, the user runs a simulation using it, the server then disables sbatch support, then the user tries to run the same simulation they can never get past the `error invalid jobRunMode=sbatch`

Steps to reproduce:
1. run the server and supervisor with sbatch enabled
2. Run srw partially coherent results with sbatch (let a few frames come in then cancel)
3. run the server and supervisor with only local enabled
4. Try to run the same srw simulation. You will get back the invalid jobRunMode error but then no amount of refreshing or clicking `start new simulation` will let you run the sim again without sbatch.

**Comment by robnagler** [comment]
I think this should throw not found and log the fact it was sbatch.

This will only happen in the case of development or if a site turns off sbatch (unlikely).
