### ISSUE TITLE
sirepo.js:2290 list.sort is not a function

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2234]
```txt
list.sort is not a function. (In 'list.sort(function(a, b) {
                        return a.localeCompare(b);
                    })', 'list.sort' is undefined)
http://v.radia.run:8000/static/js/sirepo-components.js?20200203.230513:650 – "Possibly unhandled rejection: {\"line\":650,\"column\":30,\"sourceURL\":\"http://v.radia.run:8000/static/js/sirepo-components.js?20200203.230513\"}"
```

**Comment by robnagler** [comment]
I think the broader issue is that `heatplot.html` is making requests before the user is logged in. This happens when you visit a shared link and you aren't logged in (#2223). I don't think the app should request anything if the state is not logged in.

**Comment by moellep** [comment]
The app used to detect if it was logged out and wouldn't include any routes. Something like this might be a solution to this.

https://github.com/radiasoft/sirepo/blob/ff0e158b01c29c30153b8eb9382183bd246a2601/sirepo/package_data/static/js/sirepo.js#L78

**Comment by robnagler** [comment]
I am making authState dynamic so the checks need to be dynamic.
