### ISSUE TITLE
histogramdd range=range?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2237]
[This code](https://github.com/radiasoft/sirepo/blob/1a756136978da73042db34ef5d351970acc2d663/sirepo/template/template_common.py#L291) passes a function (`range`) where a sequence is expected:

```py
hist, edges = numpy.histogramdd(values, histogram_bins(model['histogramBins']), range=range)
```

I only noticed this, because histogramdd fails on py3.

**Comment by moellep** [comment]
In this case range is a variable. Should be renamed to a non keyword.

**Comment by robnagler** [comment]
I see now. Myopic, sorry. 

Then again, it advances [the case for single letter variables](https://github.com/radiasoft/pykern/wiki/DesignHints#locals-parameters-and-globals). :)

**Comment by bruhwiler** [comment]
2nd sentence in that section is:
"Global variables shuold be self explanatory, because they are used out of
constant."

'shuold' should be 'should'  :)

Instead of 'constant', I think you mean 'context' ...?

**Comment by robnagler** [comment]
Fixed

**Comment by moellep** [comment]
Back to the numpy.histogramdd() bug - it is actually because python3 map() returns something different than python2...

In template.sdds_util, the line:

` values=map(lambda v: _safe_sdds_value(v), values),`

needs to be:

` values=list(map(lambda v: _safe_sdds_value(v), values)),`

**Comment by robnagler** [comment]
Noted https://github.com/radiasoft/sirepo/issues/1560#issuecomment-582220812 that should use a list comprehension, e.g.:

```py
values=[_safe_sdds_value(v) for f in values],
```

This is more pythonic.
