### ISSUE TITLE
GitHub login broken multiple ways

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2261]
While The GitHub login authorized callback returns JSON. It needs to return a redirect.

After fixing that, I noticed that auth-github-login is being called twice:

```txt
10.10.10.1 - - [11/Feb/2020 03:04:14] "GET /auth-github-login/elegant HTTP/1.1" 302 -
10.10.10.1 - - [11/Feb/2020 03:04:14] "GET /auth-github-login/elegant HTTP/1.1" 302 -
```

The first and second call locations are [the same location](https://github.com/radiasoft/sirepo/blob/master/sirepo/package_data/static/js/sirepo.js#L2879):

```txt
VM2346 angular.min.js:127 Error: hello
    at Object.self.globalRedirect (VM2352 sirepo.js:1648)
    at new <anonymous> (VM2352 sirepo.js:2877)
    at Object.instantiate (VM2346 angular.min.js:45)
    at VM2346 angular.min.js:98
    at Object.link (VM2362 angular-route.min.js:8)
    at VM2346 angular.min.js:17
    at Ba (VM2346 angular.min.js:89)
    at p (VM2346 angular.min.js:73)
    at g (VM2346 angular.min.js:64)
    at VM2346 angular.min.js:64 "<div data-ng-view="" class="sr-view-content">"
```

The LoginWithController seems to be called twice or somethings wrong with doing a redirect in the middle of a controller initialization. Definitely something angular I don't understand.

**Comment by robnagler** [comment]
@moellep Need your help with issue/2248-flask-oauthlib branch. You need to `pip install -e .` to get `Authlib` to use it.

I don't know why the LoginWithController is being called twice when I click github login.

**Comment by moellep** [comment]
I'll look at this now.
