### ISSUE TITLE
Running codes on Jenkins

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#227]
[Build is failing](https://travis-ci.org/radiasoft/sirepo/builds/146471933), because server_test.py needs to have SRW to run. Need a way to run codes on Travis or other CI platform.

**Comment by robnagler** [comment]
See https://docs.travis-ci.com/user/docker/

**Comment by elventear** [comment]
@robnagler I have figured a way to run Vagrant within Travis, using qemu for virtualization. Maybe it would be helpful to leverage the same Vagrant environment that we use for development for testing?

**Comment by robnagler** [comment]
Thanks @eleventear! Let's discuss. I have some thoughts on how to improve
Travis, but it would be good to have your input.
