### ISSUE TITLE
auth-email link secret is not changing

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2274]
On alpha, when you login with email, the auth secret in the URL isn't changing between logins. So you can use an old login email to login.

To reproduce, login with email on alpha. Then logout and login again. Use the old email auth link to login the second time.

**Comment by moellep** [comment]
Looks like this is a feature for dev and test servers:

https://github.com/radiasoft/sirepo/blob/master/sirepo/util.py#L152

**Comment by robnagler** [comment]
Yes, so we can test alpha from an external test driver.

See 6079ebe04f888476a8be74b792480bd87c372b9d
