### ISSUE TITLE
NERSC: better UI for login

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#2278]
https://www.sirepo.com/warppba#/dynamics/jrr7Ybt8

The simulation ran fine locally.

Trying to execute at NERSC generated the following error:
![image](https://user-images.githubusercontent.com/3825435/74782279-5b47ed80-5260-11ea-99fc-cc5fb54eca14.png)

**Comment by e-carlin** [comment]
To be clear are the steps you took:
1. Click start new simulation
2. Be prompted to enter your NERSC credentials and submit them
3. End up back at this screen with the error message "please try again"

**Comment by bruhwiler** [comment]
Yes, the 3 steps above are what I followd.  

I haven't tried again, yet.

I did verify that my password+OTP is working correctly via the following login mechanism:
> ssh -Y user_name@cori.nersc.gov

**Comment by robnagler** [comment]
It says "please try again":

![unnamed](https://user-images.githubusercontent.com/5495179/74783419-dd391600-5262-11ea-878f-e08e48aa36ee.png)

This is how it works, unfortunately. There would need to be some GUI changes to make it work better.

**Comment by bruhwiler** [comment]
I tried a 2nd time, resulting in the same error message.

**Comment by e-carlin** [comment]
Did you have to login again the second time? If so then that is expected.

**Comment by bruhwiler** [comment]
Yes, I logged in again.

**Comment by robnagler** [comment]
To be clear, in between the two logins, NERSC shutdown the connection between sirepo.com and cori.nersc.gov. It seems to time out after an hour.

When you login again, you will need to click Start Simulation again. That's how the GUI works right now, unfortunately. There's no concept of "automatic retry" in the GUI. It would require significant restructuring the GUI to handle this case where it retries on error.

I can give a demo on Thu to show how it works.

**Comment by bruhwiler** [comment]
Oh, right -- I forgot about this behavior. 
Sorry about that.

I find the interaction with the GUI very non-intuitive.
I think a couple of small changes could improve the UX significantly.

1) When the user selects Execution mode:  cori.nersc.gov
    the text in the "Start New Simulation" button changes to:
    "Enter NERSC credentials"

2) After the login has completed and more user input is required,
    the text in the button changes back to "Start New Simulation"
    Also, the message "Error: Please try again." should be changed to:
    "Success:  you are logged in. Please press button below."

**Comment by robnagler** [comment]
Making these changes is going to require some effort. I don't know how much. 

Here are some issues:

* At the time Start Simulation is pressed, we do not know if you need to login to NERSC. As you noticed, your connection timed out so even though you had logged in, it required another login. There's no way for the server to tell the GUI that something is wrong until it makes a request to start the simulation. 

* Indeed, we only know that the user wants to use NERSC if the user selects cori.nersc.gov in the drop down. At that point, the button would need to change. The code is in two places, and would need to be consolidated (already quite a bit was copy-and-pasted to get this far).

* The "Error:" is output by the GUI, not the server. The server returns an error string ("please try again"), which then would have to be interpreted by the GUI. There are other errors, e.g. "Your credentials were invalid".

**Comment by robnagler** [comment]
I renamed this to better describe the problem. We need a better UI for logins via sbatch/NERSC.

**Comment by robnagler** [comment]
I think this still needs to be improved:

<img width="747" alt="Screen Shot 2020-05-24 at 7 24 19 AM" src="https://user-images.githubusercontent.com/5495179/82755237-99890780-9d8f-11ea-94ed-dec7334d8e1a.png">

I think it needs to be clear that the user has to press "Start Simulation".

There's a typo on "connected".
