### ISSUE TITLE
flashcap: show better message than Pending when waiting in user's queue

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2280]
If a user if running a long running job, any requests to run another long job will show "Pending" until the first job completes or is canceled.

For example, if you are running a partially-coherent SRW simulation and then try to run an elegant simulation at the same time, the elegant simulation will show "Pending". Reloading the elegant page shows no status, but the server still has the simulation pending. Stopping the SRW simulation and reloading the elegant page shows the simulation completed.

Ideally, the Pending message would say something like "Waiting for SRW simulation to complete" until the simulation is ready to run.

**Comment by moellep** [comment]
Actually for long-running jobs, it shouldn't add the job to the queue at all. Instead it should return an error message, something like "You are already running an XXX simulation."

**Comment by robnagler** [comment]
I'm not sure how it would know that. It would have to ask the server in advance "are there any jobs running?" Even then, it would be a race condition so it has to get on the queue, and then handle the error properly.

**Comment by robnagler** [comment]
Incorrectly said: handle the response from the server properly. There's always a response to runSimulation, which could include the number of jobs in the queue ahead of the current job.

**Comment by moellep** [comment]
It is OK it is a race condition. Even if the job has stopped, the user should be asked to try again. For example, if I try to run an elegant simulation but a long-running SRW simulation is still going (or even just stopped during the request), the UI should say a SRW simulation is currently running, along with the link to the running simulation.

**Comment by robnagler** [comment]
I was not being clear. I'm saying that the server needs to reply `status=pending`, but also `queuePosition=35`. This would be a reply to runSimulation. The GUI can then decide to ask information about the queue. There might be three jobs running or one or 25. That would be up to the server to know. For premium users, we will be allowing more than one job at a time.

**Comment by robnagler** [comment]
I think it would be useful to implement #60, and have it displayed an obvious link somewhere as well as a hint link when a simulation is pending.

**Comment by robnagler** [comment]
Related https://github.com/radiasoft/sirepo/issues/2057

**Comment by e-carlin** [comment]
@robnagler what exactly do we want the ui to be? A link to the jobs page when a job is pending waiting on another job to complete?

**Comment by robnagler** [comment]
I think we should like to the jobs page.

If it is waiting on resources, then we might show something else, but that won't happen really so let's not program that case just yet.

**Comment by robnagler** [comment]
Also, when running on sbatch/nersc, we should differentiate between waiting to start the agent and getting in the slurm queue. I don't think it is all that useful to show anything except maybe the job id from sbatch, which would at least give people some warm fuzzies that it actually got in the queue.

**Comment by robnagler** [comment]
Just got this:

```txt
Broadcast message from root@cori03 (somewhere) (Wed Mar 25 06:44:39 2020):

=====================================================================
A T T E N T I O N         A T T E N T I O N        A T T E N T I O N

                 Cori is going down for maintenance from
                   2020-03-25T07:00 - 2020-03-25T19:00

                         PLEASE LOG OFF!!

=====================================================================
```

We'll want to handle this case, too. If the host is not reachable, we'll want to say this explicitly.
