### ISSUE TITLE
JS Issue with an SRW simulation

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#2285]
Using the docker-based installation at NSLS-II, I got the following error in the interface. Is it a known issue which has already been fixed in a newer version?
```
Application Error: [Exception... "Failure" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: https://expdev.nsls2.bnl.gov/static/js/sirepo-plotting.js?20200219.212830 :: initImage :: line 452" data: no]. A report was sent to the server.
```

Observed at https://expdev.nsls2.bnl.gov/srw#/beamline/xuhX0oF2, comes from a copied simulation.

Cc @ahebnl

**Comment by moellep** [comment]
Hi @mrakitin,

It is possible the is a bug which was fixed, but I don't see anything directly related to it. Was the simulation being copied coming from a more recent version of sirepo, or within the same server? If you could email me the sirepo-data.json file, I could debug further.

**Comment by mrakitin** [comment]
Hi Paul, the simulation is from the same server. I'll email the zipped simulation shortly.

**Comment by moellep** [comment]
I've reproduced the bug with the current version of sirepo as well. It looks like a limitation in the Firefox browser. The plot is 54600x60 which crashes firefox. For now, the work-around is to set the "Maximum Plot Dimension" for the affected watchpoints to 1000. Chrome works OK. I'll see what the Firefox limit is and add some resampling on the client for this case.
