### ISSUE TITLE
Application Error: TypeError: Unable to get property '0' of undefined or null reference. A report was sent to the server.

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#2288]
This is a problem with a WarpVND example --

https://www.sirepo.com/warpvnd#/visualization/CTUzS2ME

![image](https://user-images.githubusercontent.com/3825435/74886062-62d8c680-5334-11ea-9ff3-6478439da18c.png)

**Comment by moellep** [comment]
I've reproduced a similar error on sirepo.com, but the simulation runs normally on dev. More debugging is required.

**Comment by robnagler** [comment]
Did you try with the job_supervisor enabled?

**Comment by moellep** [comment]
No, with the old runner. The simulation takes a long time to complete.

**Comment by robnagler** [comment]
I'll debug

**Comment by robnagler** [comment]
When I import the STL file via the GUI, I get:

```
Error: /download-file/warpvnd/UrTEou9H/stl-file.stl-file.lattice_gate.stl: Invalid or missing .stl: RangeError: Offset is outside the bounds of the DataView
```

I'll hack the db to test, but might be a clue(?).

**Comment by robnagler** [comment]
The fieldAnimation and currentAnimation are coming back fine. The impactDensityAnimation, particle3d, and particleAnimation are returning `{"state":"canceled"}`.

I'll continue debugging tomorrow.

**Comment by robnagler** [comment]
We are hitting [Tornado's default max_message_size]( https://www.tornadoweb.org/en/stable/websocket.html#tornado.websocket.WebSocketHandler) of  10MiB. There is a [TODO to configure it](https://github.com/radiasoft/sirepo/blob/4f7071d941e15fe8fd60dab25fcc694c7e978b66/sirepo/pkcli/job_agent.py#L150).
