### ISSUE TITLE
Zgoubi:  shared simulation fails to copy

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#2289]
Here's the original simulation:
https://www.sirepo.com/zgoubi#/visualization/WhatIIrF

Here's what I see when I try to make a copy from the above URL:
![image](https://user-images.githubusercontent.com/3825435/74887422-1f805700-5338-11ea-907b-b9e43545d8e3.png)

**Comment by moellep** [comment]
There was a bad value in the AGS Booster example which was fixed here: 3832c98 but there was no fix-up put in place for existing users. I'll add a fix-up for this.  The work-around is to select Discard Changes to Example for that simulation.
