### ISSUE TITLE
background job shows no errors unless exception raised

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2297]
When you run a background job, the process may catch the exception and format the info into an error message. For example, if you run the synergia example below, you would expect to see the error:

![Screen Shot 2020-02-20 at 11 40 57 AM](https://user-images.githubusercontent.com/6516910/74967272-e696bf80-53d5-11ea-8e06-805305cd68e4.png)

https://alpha.sirepo.com/synergia#/visualization/NZBtrvEW

The results get written using simulation_db.write_results(), but it looks like that info never makes it back to the client with the new server/supervisor code for background jobs.

**Comment by robnagler** [comment]
_do_compute needs to read the status file

**Comment by e-carlin** [comment]
Fixed by #2359
