### ISSUE TITLE
Add proper acknowledgments for Elegant and its use.

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#230]
We need to properly acknowledge Elegant and its developers.

For example, whenever one runs Elegant, there is a text message that suggests to reference the first Elegant paper, if the results are used in publication. This text should appear somewhere in the UI.

David will solicit input from Elegant developers.

**Comment by robnagler** [comment]
Can we have a link to notices? Alternatively, we could put it at the bottom of the page like we do with quote provider disclaimers on bivio.com

**Comment by bruhwile** [comment]
As far as I can tell, Elegant is distributed with the following license:
  http://www.aps.anl.gov/epics/license/open.php 

We need to obey the terms of this license, which means, in part, that we include a copy of the license in the Sirepo source. I'm not sure of the best way to do that.

We could include the above link on each page, labeled 'Elegant license'

As for the text message regarding reference to Elegant in publications, I got no response from the developers, so I think we can wait to figure that out.

**Comment by robnagler** [comment]
We don't redistribute elegant with sirepo. You have to install it yourself.
We don't modify elegant either.

If you install one of our containers, you get their RPM, which includes the
license documentation in the rpm:

rpm -qi elegant | grep -i license
License     : EPICS Open license http://www.aps.anl.gov/epics/
license/open.php

However, it does not include a license file itself, which means they are
violating the terms of their own license. (One thing about copyright
licenses is that you have to adhere to them yourself or nobody else does
:).  I will add it to the container build in /usr/share/doc/elegant.

**Comment by bruhwile** [comment]
Thanks @robnagler
