### ISSUE TITLE
Wiki: debugging job errors, especially with Docker

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2307]
For example, [using container name](journalctl CONTAINER_NAME=webserver
https://docs.docker.com/config/containers/logging/journald/#retrieve-log-messages-with-journalctl):

`journalctl CONTAINER_NAME=webserver`

I think this could be in the development wiki page until it gets too large.

* How do you find the run.log?
* How do you see the agent log on NERSC/sbatch?
* How do you reproduce a job_cmd (in.json, btw, might be left around in dev envs)

**Comment by e-carlin** [comment]
https://github.com/radiasoft/sirepo/wiki/Debugging-the-job-system

**Comment by robnagler** [comment]
Very good. Clear and well written.

I made a couple of small edits, then I thought a review would be better.  I don't know if you know, but you can clone radiasoft/sirepo.wiki to get at the wiki to see the git history. No good way to do reviews for the wiki.

I think "agent Ids" should be agentIds (or agentId's?) everywhere. Will make searching the text easier, and it is consistent naming with the code. Same with op ids.

Op ids are not uuids. They are generated by job.unique_key (sirepo.util.random_base62), and do not have the characteristics of uuids, which make them less repeatable, e.g.:

```txt
>>> import uuid
>>> uuid.uuid4()
UUID('eb239002-9f5a-4f22-8b80-46208f7b9863')
>>> uuid.uuid4()
UUID('6a27989b-d058-4a8f-92ef-0834bbbf7c62')
>>> uuid.uuid4()
UUID('473c29d3-3ee6-4c9e-a3d7-ba1fd307ea9c')
>>> uuid.uuid4()
UUID('3ed5868d-0071-4b77-8037-c81486f13b4d')
```

Note the repeated "4" in the middle component.

I think it is worth mentioning that agentIds are used for authentication. That's important, because an agentId is a secret, and shouldn't be visible on a ps ax line, for example. It's also good that we won't write them fully in the logs, even though they are emphemeral.

"You can use the runDir to go to the location in the db" is not quite true. runDirs are caches so we should not refer to them as part of the "db". They also are unique to the class of the agent so sbatch runDirs are not accessible at all when you are debugging real user directories on NERSC. They might be visible to an admin of a local sbatch cluster.

> they are written to journald (TODO rn how to find them?).

They are found with `journalctl -u sirepo_job_supervisor`. You could refer to https://github.com/radiasoft/rsconf/blob/2a3a0d895d72a9b4579747e7eccad4fc09d51019/rsconf/component/sirepo_job_supervisor.py#L30 which lets you know it is a systemd unit, which is logged to journald. It's probably useful to have links to rsconf, because people might want to know how the services are configured.

> written by the drivers (ex this) as a "supervisor" message

I don't think this description is necessary. A driver is a module, not an independent process, and it's intrinsically linked to how the supervisor works. Something like job_cmd is an independent process from the agent, which will have to be debugged, because it's logs are sometimes separate (run.log).

> Each agent writes their logs to different locations

Needs a period.

> for parallel) ( you can search the logs for cname to find container names)

Too many parens make this awkward. I would put the `journalctl CONTAINER_NAME=srj-s-vn9m3eZW` at this point, as an fenced block so it's clear what you have to do to read the logs of a particular agent.

> We don't aggregate logs to a single place

That's true and not true. We aggregate them, but not in real-time. I would leave it out, and simply say "You need to ssh into". One thing we might do is store the host in the supervisor db. We are certainly going to want to know it for the admin page.

> If you are debugging running as yourself

"If you are debugging a job you ran as yourself"

>  /global/cscratch1/sd/rms/sirepo-dev. A log file (job_agent.log) 

It's easier to combine this: The log file is /global/cscratch1/sd/rms/sirepo-dev/job_agent.log. Also, you can say `$SCRATCH/sirepo-dev/job_agent.log`, which is the canonical way to refer to the scratch dir.

> flak server

typo

> `Feb 24 21:39:10 15897     3 ../sirepo/job_api.py:183:_request api=api_runSimulation<snip>`

For the purposes of this document, let's strip date/time and file location. This makes it easier to read in GitHub wiki. You can have a prolog that explains these things are being stripped for technical rendering reasons.

**Comment by e-carlin** [comment]
Great! Thanks for doing a review.

I didn't know you could clone the wiki. Know I know where the images folder is that I searched around on the GUI for...

I've implemented all of your changes except stripping data/time and file location. I will once #2308 is merged because that will change some of the messages which I need to updated.

**Comment by robnagler** [comment]
Good enough
