### ISSUE TITLE
SRW: Reset examples to default?

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#2316]
The examples provide good starting points showing working propagation parameters in realistic beamlines.
When one makes changes to these examples, it is easy to get stuck in a bad configuration. One would like to have an option to restore the original examples.

**Comment by bruhwiler** [comment]
This feature has already been implemented.

Click on the cog wheel, then select "Discard Changes to Example".
Please see the screen shot below.

![image](https://user-images.githubusercontent.com/3825435/75727088-5001b280-5ca1-11ea-84fd-b5c4716c8443.png)

**Comment by bnash** [comment]
Thanks! Sorry I missed that.
