### ISSUE TITLE
JSPEC: Meshkov force model

### ISSUE THREAD

**Issue by sjcrs** [radiasoft/sirepo#2317]
Similar to issue #1961 , the current master of electroncooling has a new force formula called Meshkov. Please add this as a drop-down force formula option alongside Parkhomchuk and Derbenev & Skrinsky.

**Comment by e-carlin** [comment]
@sjcrs  this will be available on alpha once #2328 is merged and we do a release.

<img width="1120" alt="Screen Shot 2020-03-05 at 2 56 02 PM" src="https://user-images.githubusercontent.com/10264515/76032438-24780580-5ef7-11ea-9931-83cb32de8052.png">
