### ISSUE TITLE
Zgoubi: import error for eRHIC lattice

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#2326]
I try to import a zgoubi lattice file I have for eRHIC (erhic_rollerr.res) and I get the following error:
`('Element "MULTIPOL CMAG KICK": missing "B_10" value for line def: l R_0 B_1 B_2 B_3 B_4 B_5 B_6 B_7 B_8 B_9 B_10',)`

**Comment by moellep** [comment]
I think this is a case where an older zgoubi data file doesn't match the zgoubi user guide's specification. In this case, add an extra 0 at the end of the third line on the MULTIPOL:

```
 'MULTIPOL' HKIC      IJKDHD1                                                                                 8
0  .kicker
0.100000E-03 10.0000  0.000000E+00 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
.0 .0  1.00 0.00 0.00 0.00 0.00 0. 0. 0. 0.
4  .1455   2.2670  -.6395  1.1558  0. 0.  0.
.0 .0  1.00 0.00 0.00 0.00 0.00 0. 0. 0. 0.
4  .1455   2.2670  -.6395  1.1558  0. 0.  0.
0.000000000 0. 0. 0. 0. 0. 0. 0. 0. 0.
#20|20|20  Kick
1 0. 0. 0.
```

We could update sirepo/zgoubi to default missing multipole values to 0.
