### ISSUE TITLE
no beam position history and animation_test

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2337]
animation_test is failing on issue/2334 branch for webcon. When I run the simulation, it says 'no beam position history' both on dev and alpha. I suspect that in my environment, I'm getting back 'None' related to no beam position history, but not sure. 

Anybody have suggestions?

**Comment by moellep** [comment]
On alpha it will say "no beam position history" unless the EPICS has been started. So if you visit the Controls page for a new sim, it will show "no beam position history". After you start EPICS, it will have data to display.
