### ISSUE TITLE
"Save as" capability

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#2356]
If a user opens a simulation and makes edits, there should be a way to save their work into a new simulation (and avoid permanently changing the originating simulation).  The ability to copy at the beginning of the workflow is not helpful because you don't always know upfront that you want to make a change.

**Comment by robnagler** [comment]
Would you like to turn off the auto-save feature? Right now, many changes are saved to the original simulation automatically. Not all changes have a "save" button, e.g. minimizing or maximizing a report.

Google Docs operates like Sirepo, btw.

**Comment by messamer** [comment]
You raise a good question-  Do our users realize that it functions with
autosave?  I don't want to change anything that is currently in-place but
do feel it warrants further discussion and perhaps some usability testing.

*Paula Messamer*
Product Manager | RadiaSoft
1-720-502-3928   x719 | messamer@radiasoft.net
radiasoft.net | sirepo.com

**Comment by messamer** [comment]
Another difference to note is that Google Docs explicitly show the user that the file is being actively saved: "Saving"... "All changes saved in drive".  The Sirepo interface does not include this.
<img width="663" alt="Screen Shot 2020-03-13 at 12 10 24 PM" src="https://user-images.githubusercontent.com/29441306/76648243-ed6fa880-6523-11ea-8b6c-81b7ec7860f8.png">
