### ISSUE TITLE
synergia py3

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2358]
I'm building/testing synergia py3. The synergia build is failing, and I'm not sure why so I figured I'd just get a later version.

@ncook882 @cchall @ilyapogorelov do you see a problem with using the current "mac-native" version? (It's the branch that the build instructions tell you to checkout, and it seems to work on linux with certain tweaks.)

**Comment by ncook882** [comment]
@robnagler I see no reason why building the mac-native branch would be a problem, assuming it works reasonably well on linux. The commit history suggests that it's currently maintained,

**Comment by robnagler** [comment]
Fix 9eab965e
