### ISSUE TITLE
Create premium user role

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2360]
- [x] create role "premium"
- [x] job_supervisor._get_max_run_secs will check role of user and set accordingly to cfg.max_hours.premium_parallel or just parallel.
- [x] #2280 improve error messages when running out of time
- [ ] configure values for prod/alpha/beta

@e-carlin @moellep anything else?

**Comment by robnagler** [comment]
- [ ] Add premium to the admJobs list
- [ ] Add premium to simulation dump

**Comment by e-carlin** [comment]
@robnagler a few questions:
1. I left a comment regarding #22800 (comment [here](https://github.com/radiasoft/sirepo/issues/2280#issuecomment-600316956))
2. You say "add premium to simulation dump". What is simulation dump?

**Comment by robnagler** [comment]
I don't know that we need to work on #2280 just yet. That's not what I was thinking. When a user's job is killed for a timeout, then we have to put a different error message that indicates you can pay for premium.

The simulation dump is an admin script so it's my task.

**Comment by robnagler** [comment]
Setting roles on actual users handled separately
