### ISSUE TITLE
fastfelo: prune simulation results regularly

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2361]
- [ ] revive pruning pkcli
- [ ] Differentiate between premium and non-premium users.
- [ ] add to rsconf (run nightly)

**Comment by robnagler** [comment]
Related #2367

**Comment by e-carlin** [comment]
We've decided to move the pruning into the supervisor. Now that flask-sqlalchemy is removed work can resume on this because the supervisor can read the auth_db.
