### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#237]
Use something like [Solo](https://chibicode.github.io/solo/) (possibly proxied to github.io address) for the home page so can keep people abreast of updates without spending any time on design.

**Comment by robnagler** [comment]
Need content first

**Comment by robnagler** [comment]
@moellep please create structure for "/" route. Simple html for now that points to the home pages of the three codes with clear button links. I'll fill in some text with David's help.

**Comment by bruhwile** [comment]
Here's a first draft;

[SirepoSRW_LandingPage.pdf](https://github.com/radiasoft/sirepo/files/490819/SirepoSRW_LandingPage.pdf)

**Comment by bruhwile** [comment]
Here's a first draft;

[Uploading Sirepo_TopLevelLandingPage.pdf…]()

**Comment by bruhwile** [comment]
Here's a first draft;

[Sirepo_TopLevelLandingPage.pdf](https://github.com/radiasoft/sirepo/files/490821/Sirepo_TopLevelLandingPage.pdf)

**Comment by robnagler** [comment]
Thanks for doing this.

I was thinking we should do a more modern interface like continuum.io
<https://www.continuum.io/> without the extra picture, maybe even like
getbootstrap.com. Something that says what Sirepo is followed by three
buttons with a bit of description underneath. Ideally we'd have simple
logos for each entity, but I don't think that's possible.

I'd really like to avoid dealing with graphics this week. They are hard to
get right.

How about this for the intro line:

Sirepo lets you develop, run, and share particle accelerator simulations
using our intuitive UI executing in [containers] in the cloud or [on your
desktop].

It's FREE so you can try it out:

[ Youngs Double Slit ]        [  Laser Pulse ]    [ Compact Storage Ring ]

[ Synchrotron                 [ Warp ]             [ Elegant ]
Radiation Workshop ]

SRW is ....                   Warp is ....         Elegant is ....

Want to run on your computer? Install with [ Vagrant ] or [ Docker ].

Sirepo is provided as a free community service by [ RadiaSoft LLC ] under
grants XYZ... from the Department of Energy.

I think we could have a graphic or just use the Sirepo logo like the [B] of
bootstrap. No need for a menu right now.

The first row of links would go right to simulation pages, which would
start doing something (one graph), immediately. The second row would go to
/light, /warp, and /elegant.

My $.02. :)

Rob

**Comment by bruhwile** [comment]
My revised draft is attached.

David

**Comment by bruhwile** [comment]
Here's my 2nd draft.
[SirepoHomePage_20160924.pdf](https://github.com/radiasoft/sirepo/files/491253/SirepoHomePage_20160924.pdf)

**Comment by robnagler** [comment]
Looks great.
