### ISSUE TITLE
cancelled vs canceled

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2370]
We have both. Let's pick one. I think cancelled (two l's) is best because that is what Asyncio uses.

**Comment by robnagler** [comment]
What does the OED say?  ;)

**Comment by e-carlin** [comment]
Both are scrabble official...

https://scrabble.hasbro.com/en-us/tools#dictionary

**Comment by dtabell** [comment]
I had that question a long time ago. Here is what I found:

https://english.stackexchange.com/questions/338/when-is-l-doubled <https://english.stackexchange.com/questions/338/when-is-l-doubled>
https://english.stackexchange.com/questions/4791/focussed-or-focused-rules-for-doubling-the-last-consonant-when-adding-ed <https://english.stackexchange.com/questions/4791/focussed-or-focused-rules-for-doubling-the-last-consonant-when-adding-ed>

Dan

**Comment by messamer** [comment]
@remy  Please give your view on this

**Comment by remy278** [comment]
"Canceled" is American English spelling, while "cancelled" is British English spelling. As we are an American company, RadiaSoft will use American English spelling with one L for customer-facing communications, as I've noted in our content style guide: https://github.com/radiasoft/ops/wiki/RadiaSoft-Content-Style-Guide.

**Comment by remy** [comment]
@messamer As a Brit, I prefer the British spelling. Thanks for checking and at-ing me in 👍

**Comment by messamer** [comment]
> @messamer As a Brit, I prefer the British spelling. Thanks for checking and at-ing me in 👍

Sorry @remy-  I didn't mean to  loop you into this.  Thanks for responding though!
