### ISSUE TITLE
document requirement to use 'job system' for development

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#2374]
From @robnagler:
> You need to switch to the job system for development now. Here are the instructions:
> https://github.com/radiasoft/sirepo/wiki/Development#developing-with-the-job-execution-system
> You can use "local" for development, but you'll want to use "docker" for servers.

@robnagler -- on approximately what date did this change occur?
@remy278 -- when Rob responds, please document this in the release notes,
https://github.com/radiasoft/sirepo/wiki/Release-Notes

**Comment by robnagler** [comment]
It's already documented: https://github.com/radiasoft/sirepo/wiki/Release-Notes

**Comment by remy278** [comment]
For reference, I update the notes every Monday morning.

**Comment by remy278** [comment]
@robnagler which issue includes this "job system" thing? I can add a further note and direct people to the wiki page.

**Comment by robnagler** [comment]
https://github.com/radiasoft/sirepo/issues/2341

**Comment by remy278** [comment]
I've added extra explanation to **Alpha Release 11:20 MT 3/9/20 Deprecates runner / Celery / RabbitMQ**  notes and directed to the wiki Rob mentioned above in the release notes. Is there anything else we need to do to close this issue?
