### ISSUE TITLE
Improve Development instructions

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2378]
https://github.com/radiasoft/sirepo/wiki/Development

1. Need to: `PYENV_VERSION=py3 pyenv exec pip install -e .`
2. Explain the py2/py3 split in detail, and that it will be changing
3. `radia_run sirepo-dev` should be done relatively frequently, it's idempotent
4. Improve run-supervisor to verify that py3 install run (1) if not
5. Implement #2079

Anything else?

**Comment by ahebnl** [comment]
$ radia_run sirepo-dev
Log: /home/vagrant/src/radiasoft/sirepo/radia-run-install.log
curl -L -s -S https://raw.githubusercontent.com/radiasoft/download/master/installers/sirepo-dev/radiasoft-download.sh
Source: /var/tmp/radia-run-22622-27077/20200321021252-radiasoft-download.sh
curl -L -s -S https://raw.githubusercontent.com/radiasoft/download/master/installers/beamsim-codes/radiasoft-download.sh
Source: /var/tmp/radia-run-22622-17310/20200321021252-radiasoft-download.sh
dnf update
curl -L -s -S https://raw.githubusercontent.com/radiasoft/download/master/installers/code/radiasoft-download.sh
Source: /var/tmp/radia-run-22622-28606/20200321021256-radiasoft-download.sh
Installing: common elegant epics genesis jspec ml_for_py3 opal pydicom pymesh rsbeams shadow3 srw radia synergia warp zgoubi
dnf install rscode-genesis rscode-ml_for_py3
2020-03-21T02:12:52Z install_main
Unexpected error; Install failed.
If you don't know what to do, please contact support@radiasoft.net.



 /home/vagrant/src/radiasoft/sirepo/radia-run-install.log has the following message:

2020-03-21T02:12:52Z install_main
2020-03-21T02:13:03Z Error trap
(END)

**Comment by ahebnl** [comment]
running with debug:


++++ [main:333] sudo dnf -y --color=never install rscode-genesis rscode-ml_for_p                                                                     y3
Last metadata expiration check: 0:00:02 ago on Sat 21 Mar 2020 02:15:52 AM UTC.
No match for argument: rscode-genesis
No match for argument: rscode-ml_for_py3
Error: Unable to find a match
+ [main:1] install_err_trap
+ [main:109] set +e
+ [main:110] trap - EXIT
+ [main:111] [[ -z 1 ]]
+ [main:114] install_log 'Error trap'
++ [main:138] date -u +%Y-%m-%dT%H:%M:%SZ
+ [main:138] echo 2020-03-21T02:15:54Z 'Error trap'
+ [main:139] [[ -n 1 ]]
+ [main:140] install_msg 'Error trap'
+ [main:196] echo 'Error trap'
Error trap
+ [main:115] install_err 'Unexpected error; Install failed.'
+ [main:97] trap - EXIT
+ [main:98] [[ -n Unexpected error; Install failed. ]]
+ [main:100] install_msg 'Unexpected error; Install failed.
If you don'\''t know what to do, please contact support@radiasoft.net.'
+ [main:196] echo 'Unexpected error; Install failed.
If you don'\''t know what to do, please contact support@radiasoft.net.'
Unexpected error; Install failed.
If you don't know what to do, please contact support@radiasoft.net.
+ [main:102] [[ -z 1 ]]
+ [main:105] exit 1

**Comment by robnagler** [comment]
Thanks for the debug output @ahebnl. Please run the following commands. The output should be similar to this:

```txt
$ ls /etc/yum.repos.d
docker-ce.repo              fedora.repo                  fedora-updates-testing-modular.repo
fedora-cisco-openh264.repo  fedora-updates-modular.repo  fedora-updates-testing.repo
fedora-modular.repo         fedora-updates.repo          radiasoft.repo
$ cat /etc/yum.repos.d/radiasoft.repo
[radiasoft-dev]
name=RadiaSoft fedora/29/x86_64 dev
baseurl=https://depot.radiasoft.org/yum/fedora/$releasever/$basearch/dev
enabled=1
gpgcheck=0
metadata_expire=1m
```

**Comment by ahebnl** [comment]
I am still using fedora/27

```
[py3;@v ~]$ ls /etc/yum.repos.d/
fedora-cisco-openh264.repo  fedora.repo  fedora-updates.repo  fedora-updates-testing.repo  radiasoft.repo
[py3;@v ~]$ cat /etc/yum.repos.d/radiasoft.repo
[radiasoft-dev]
name=RadiaSoft fedora/27/x86_64 dev
baseurl=https://depot.radiasoft.org/yum/fedora/$releasever/$basearch/dev
enabled=1
gpgcheck=0
metadata_expire=1m
```

**Comment by robnagler** [comment]
You will need to upgrade to Fedora 29. We haven't supported F27 for some time. One of the things about Fedora is that each release is only maintained for 13 months after general availability so Fedora 29 is already out of maintenance. 

In order to migrate to F29 you'll need to recreate your VM. This will work [on a Mac](https://github.com/radiasoft/sirepo/wiki/Development#mac-install):

```sh
curl https://radia.run | bash -s vagrant-sirepo-dev
```

There's also [PC install instructions](https://github.com/radiasoft/sirepo/wiki/Development#pc-install).

**Comment by robnagler** [comment]
I don't think this issue is relevant now that we've removed the py2 dependency.
