### ISSUE TITLE
Encapsulate _RUNNING_PENDING 

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2379]
In #2346 I noted that the test fails on run_dir_mutex on master. Debugged this easily. Here's what happens:

1. runSim A sets computeJobSerial to X (e.g. 584718669)
2. runSim B starts in a thread and sets computeJobSerial to X + 2 (e.g. 1584718671)
3. runCancel for A includes computeJobSerial=X and [_req_is_valid is false](https://github.com/radiasoft/sirepo/blob/64a37db9cb587580f0cfd7070f4b05c9aaa23783/sirepo/job_supervisor.py#L426)
4. runCancel doesn't cancel anything so A is running and B is pending.
5. runSim C awaits on run_dir_mutex, because runSim B has acquired it.

[The defect] is obvious on its own line:

```py
if self.db.status == _RUNNING_PENDING:
```

This is why encapsulation is so important. If  _RUNNING_PENDING were _is_running_pending as follows:

```py
if _is_running_pending(self.db.status):
```

and:

```py
def _is_running_pending(status):
    return status in (job.RUNNING, job.PENDING)
```

**Comment by robnagler** [comment]
Found [another related issue](https://github.com/radiasoft/sirepo/blob/64a37db9cb587580f0cfd7070f4b05c9aaa23783/sirepo/job_supervisor.py#L256) as a part of this fix:

```py
#TODO(robnagler) when we reconnect with running processes at startup,
#  we'll need to change this
            if d.status in _RUNNING_PENDING:
                d.status = job.CANCELED
            return cls(req, db=d)
```

There's no db_write after the status is changed to `CANCELED`.

**Comment by e-carlin** [comment]
> Found [another related issue](https://github.com/radiasoft/sirepo/blob/64a37db9cb587580f0cfd7070f4b05c9aaa23783/sirepo/job_supervisor.py#L256) as a part of this fix:
> 
> ```python
> #TODO(robnagler) when we reconnect with running processes at startup,
> #  we'll need to change this
>             if d.status in _RUNNING_PENDING:
>                 d.status = job.CANCELED
>             return cls(req, db=d)
> ```
> 
> There's no db_write after the status is changed to `CANCELED`.

I believe [this](https://github.com/radiasoft/sirepo/blob/64a37db9cb587580f0cfd7070f4b05c9aaa23783/sirepo/job_supervisor.py#L530) is another place where I think we don't right. Maybe we need a better abstraction so we can't forget?
