### ISSUE TITLE
Issues with Vizualization of new OPAL simulations

### ISSUE THREAD

**Issue by aierides** [radiasoft/sirepo#2388]
I have been trying to run a simulation as a test for the OPAL GUI and many of the plots that were visible on the visualization tab for some of the examples aren't present anymore. Am I missing something? Is there a way to add those plots?

**Comment by bruhwiler** [comment]
@aierides -- Thank you for reporting this problem.

Please provide the URL for your simulation, so we can assist in debugging.

**Comment by aierides** [comment]
Hi David,
See the link below:
https://www.sirepo.com/opal#/source/hqSTDmdW
Thanks,

Anastasia

**Comment by bruhwiler** [comment]
I made a copy of the simulation and ran it.
After an hour, there was no indication of progress ... seems like it might be hung.

Here's a screen shot of the simulation page:
![image](https://user-images.githubusercontent.com/3825435/77271982-b0b75600-6c75-11ea-8307-9021f95ac1da.png)

MAXSTEPS has been set to the value '1'
I'm pretty sure this is wrong.
MAXSTEPS * DT * (average particle velocity) should be greater than ZSTOP

**Comment by aierides** [comment]
Hi David,

I had ran it with several different MAXSTEPS ranging from 1 to 1e10 and I still get the same behavior. Could something else be happening?

Thanks for your time and attention on this.

A

**Comment by bruhwiler** [comment]
The rf cavity element in OPAL is sophisticated and error prone.
I recommend that you review section 8.11 on p. 86 of the OPAL user guide here,
http://amas.web.psi.ch/docs/opal/opal_user_guide-1.1.9.pdf

Note that Sirepo/OPAL supports OPAL-T and not OPAL-CYCL.
This is the appropriate version of OPAL for simulating an electron gun.

If you look in the Examples/ folder of the Sirepo/OPAL simulation workspace, as shown here:

![image](https://user-images.githubusercontent.com/3825435/77276481-69829280-6c80-11ea-8ab0-05163b1778c4.png)

then you will see the example simulation named, "CTF3 RF Photoinjector"

If you open that simulation and go to the "Lattice" tab and mouse over the "FINSS_RFGUN" element to the lower-right portion of your browser, you can select the "Edit" button.

In the resulting popup window, select the "Page 2" tab. Then select the oval dropdown widget just to the right of the text "FMAPFN". You should see something like the following: 

![image](https://user-images.githubusercontent.com/3825435/77276424-3f30d500-6c80-11ea-90ff-5ac4db828eba.png)

You should see that the a field map named "CTF3_Ez_ASTRA.opal" has been specified for this rf cavity.

When I look at the 6 rf cavities from your simulation, in each case I see that a different file has been specified. I'm not sure if that was your intent.

I tried editing all 6 of your rf cavity elements to specify the "CTF3_Ez_ASTRA.opal" field map.
Also, on the Visualization tab, I changed ZSTOP to 0.274 which corresponds to the length of your cavity, and I increased the time step DT by 100x to be 1.e-11, which I think is small enough.

With these changes, the simulation runs.
You can grab a copy of my modified simulation via this URL,
https://www.sirepo.com/opal#/visualization/LX3HOShP

Please have a look.

Please note:  I'm not sure if my modifications are a correct or accurate representation of the system you want to simulate.  Perhaps you want to specify "No File Selected" for each of your cavities, so you get the simple rf cavity model provided by OPAL...?

Again, I recommend that you review the user manual.
For expert advice, you can ask for assistance from the OPAL development team, via the email list:
    opal@lists.psi.ch

**Comment by bruhwiler** [comment]
Hi @aierides -- is your simulation working now?

In my previous comment, I directed you to an older version of the OPAL user guide.
This is the best link to use, https://gitlab.psi.ch/OPAL/src/wikis/home

**Comment by bruhwiler** [comment]
Hi @aierides -- is your simulation working now?
