### ISSUE TITLE
Opal Examples

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#2397]
I am not seeing example simulations for Opal. I tested this in Safari and Opera.  

<img width="1331" alt="Screen Shot 2020-03-24 at 2 13 14 PM" src="https://user-images.githubusercontent.com/29441306/77472984-600d3d80-6dda-11ea-8d93-7d76f09b6c0f.png">

<img width="1563" alt="Screen Shot 2020-03-24 at 12 56 45 PM" src="https://user-images.githubusercontent.com/29441306/77472988-613e6a80-6dda-11ea-9b51-e5f670c58b43.png">

**Comment by bruhwiler** [comment]
I see this, too.
The examples folder was there yesterday, and today it is gone.

**Comment by moellep** [comment]
@bruhwiler  - can you verify that you are logged in as yourself and the opal simulations are missing. They appear to be in your user directory. I've verified that @messamer simulations are missing and were never present.

**Comment by bruhwiler** [comment]
When I'm logged in with my RadiaSoft email address (my usual account), I do see the examples.

When I'm logged in with another email address (an account I use for testing purposes), I do not see the examples.

**Comment by moellep** [comment]
I've reproduced the problem, related to #2390. If a user who has never used opal follows a link to another user's opal simulation the copy simulation fails and the user ends up with no examples.

**Comment by moellep** [comment]
@messamer, the opal simulations are now available for you and the other affected users. I'll fix the bug in #2390 next.
