### ISSUE TITLE
Exceeding cori maximum queue time should result in error

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2400]
We saw a timeout after 27 minutes so perhaps the 30 minutes on the debug queue is fuzzy.

**Comment by nickgoldring** [comment]
I'll just note that whenever I have submitted jobs to the debug queue in the past, the runtime limit has been respected by ±15 seconds.

**Comment by robnagler** [comment]
@nickgoldring did you set it to 30 minutes?

shifter may be different, because it transfers the image to the compute nodes.

**Comment by nickgoldring** [comment]
I usually set the runtime limit to 30 minutes in the batch script although sometimes I decrease it via

`#SBATCH -t HH:MM:SS`

**Comment by robnagler** [comment]
Did you set the hours explicitly when you ran the job? It defaults to .4 (24 minutes) so maybe that's what happened.

**Comment by nickgoldring** [comment]
I did not!  Thanks for pointing this out.  I will assign more hours and rerun the simulations in Sirepo.  I guess that the only time limit should be 48 hrs from the regular queue?

**Comment by robnagler** [comment]
The software toggles between the debug and batch queues based on the number of cores and hours. We don't have a maximum, but we should. I'll change this Issue.

**Comment by robnagler** [comment]
It does result in TIMEOUT so that's good enough
