### ISSUE TITLE
Configure and test premium users on beta

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2408]

**Comment by robnagler** [comment]
@e-carlin When we do #2505, I think we'll configure premium users on beta to validate. I'll want to walk through the configuration with you.

**Comment by robnagler** [comment]
@remy278 @messamer @bruhwiler The latest prod release (#2506) is complete. We can now configure premium users. You should send me (privately) the list. I'll assume all radiasoft.net users are premium. Once configured, we'll be able to dial down simulation run time and disk utilization.

**Comment by bruhwiler** [comment]
Awesome news!
I accept the action item to send the list of additional premium users to Rob (offline)

There are other activities that require some coordination, before prod is reconfigured.
These are being organized in a private RadiaSoft issue.

**Comment by robnagler** [comment]
I configured one user.
