### ISSUE TITLE
Use // for all URLs outside the app

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#241]
For external resources, we should specify // as the URL so we stay within https. This is any absolute URL that's out there, e.g. documentationUrl. I guess it is ok to specify https explicitly in this case, but any other references e.g. in [srw_crystal_x0h.py](https://github.com/radiasoft/sirepo/commit/085891f1138f7ac62f1f865abc0a53104a8b8552#diff-58864cc22b40a4664b03500ea7bc5fa9R10)

**Comment by mrakitin** [comment]
Hi Rob, do you mean I need to replace
```python
X0H_SERVER = 'http://x-server.gmca.aps.anl.gov/cgi/X0h_form.exe'
```
by
```python
X0H_SERVER = '//x-server.gmca.aps.anl.gov/cgi/X0h_form.exe'
```
?

**Comment by robnagler** [comment]
Yes.

**Comment by mrakitin** [comment]
I'm not sure https://x-server.gmca.aps.anl.gov/cgi/X0h_form.exe supports https... There is a certificate warning.

**Comment by robnagler** [comment]
Let's copy the file locally and distribute ourselves.

**Comment by mrakitin** [comment]
I'm not sure we can copy the executable from the server. I don't see any links to this compiled program at http://x-server.gmca.aps.anl.gov/x0h.html.

**Comment by robnagler** [comment]
Sorry. I made a mistake. You are sending requests off from the server to
ANL so this URL isn't going back to the user. Therefore, you can leave this
URL alone.

**Comment by mrakitin** [comment]
OK, sounds good. Thanks.
