### ISSUE TITLE
corrupted supervisor on dev

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2421]
On dev it seems the supervisor can get corrupted and start returning data for previous requests. Only restarting the supervisor corrects the problem once it gets in this state. The rcscon app reproduces the problem, although it is sporadic. To reproduce:

On dev run server and supervisor. Then open the rcscon app and create a new simulation. Select "Elegant Simulation" as the data source. Change the Iterations to a small number, like 3 and select "Start New SImulation". This will produce 21 reports. Refresh the page a few times, or after waiting a minute and the error should appear. Usually the supervisor prints something about an invalid message first such as "'error': 'Unterminated string starting at: line 1 column 36544". Then subsequent requests get either errors or data for the wrong reports:

![Screen Shot 2020-04-02 at 11 15 38 AM](https://user-images.githubusercontent.com/6516910/78278469-5323d480-74d3-11ea-9633-4f795fca71c9.png)

In the example above, the Input 1 report should always be titled "average phase".  "s6" is one of the reports farther down the page.

**Comment by moellep** [comment]
The problem seems to be that job_cmd _do_fastcgi() isn't receiving the whole message with "s.recv(int(1e8))".

**Comment by moellep** [comment]
Something like this seems to fix the problem on dev. I think the receiver needs to know the actual data size and then read that may bytes.

```python
        try:
            buf = s.recv(int(1e8))
            try:
                m = pkjson.load_any(buf)
            except Exception as e:
                buf += s.recv(int(1e8))
                m = pkjson.load_any(buf)
```

**Comment by robnagler** [comment]
There's a way to read until "done" in tornado. It's just more complicated so we opted for this thinking that since this was a unix socket...
