### ISSUE TITLE
OPAL: Raw data file download fails

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#2424]
I was trying out the CSR bend drift example and found that the Raw Data File button only works for the Beam statistics plot. All others just say URL not found.

This was also an issue for the plot from a Monitor element I added to the example

link: https://www.sirepo.com/opal#/visualization/RKd53VMI

**Comment by moellep** [comment]
Partially fixed with d0a59c0. Also related to issue #2429.
