### ISSUE TITLE
download data failure for large file

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2429]
On dev, I'm unable to download a large datafile even after adjusting SIREPO_JOB_MAX_MESSAGE_SIZE.

To reproduce, run the sirepo/opal "CTF3 RF Photoinjector" example and then select "Raw Data File" from the download option on the "Beam Variables" report. It results in a "Connection reset by peer" error and a "Not Found" page. 

Probably it should result in a server error, rather than not found.

The download works OK if the datafile is smaller, for example setting the opal MAXSTEPS to a smaller value and re-running the simulation.

**Comment by robnagler** [comment]
I'll debug this, since I'm working on #2427. I'll add a large data file to myapp.

**Comment by moellep** [comment]
I had to track the same issue down for IRAD which has data files > 100M. I found the missing spot in job_supervisor - it needs a max_buffer_size as well:
```
server = tornado.httpserver.HTTPServer(
    app, 
    xheaders=True, 
    max_buffer_size=sirepo.job.cfg.max_message_size,
)
```
I haven't checked in this change, just documenting.

**Comment by moellep** [comment]
I checked in the fix for max_message_size but left this issue open for addressing the misleading "Not Found" message rather than "Server Error" if the cmd/supervisor connection is aborted.
