### ISSUE TITLE
Include auxiliary files in export/import as zip (with JSON)

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#243]
That would be very useful to make it easier to exchange calculations between servers. Exporting/importing of Python files may lose some necessary information.

**Comment by robnagler** [comment]
We need to bundle all the related data (mirror files, for example).

For reproducibility, we will want to bundle the versions of codes and base system on the server. We need have version issues for containers (radiasoft/containers#4 and radiasoft/containers#18) to work on, and we have github installs to manage.

**Comment by mrakitin** [comment]
Yesterday we urgently had to transfer a calculation from alpha to our servers, but after exporting to Python file and importing it on our server we lost a watch point, so we need to implement this export/import as soon as possible, since such use cases will be more frequent in the future. At least export and import of just JSON file will be good enough for now. The bundles can be implemented later.

**Comment by mrakitin** [comment]
Thanks Paul! The export looks good so far. For import we probably need to rename the pop-up window:
![import](https://cloud.githubusercontent.com/assets/13209176/17705783/a1ca0974-63a7-11e6-8b81-7aaacb156f4f.png)
At least we should mention that both Python and JSON files can be imported.

Ultimately it would be nice to have a toggle button to:
- import Python file, command line options field is displayed;
- import JSON file, command line options field is hidden.

Could you please have a look at it as well?

**Comment by mrakitin** [comment]
ecbd15c addresses https://github.com/radiasoft/sirepo/issues/243#issuecomment-240147058 request. The header of the pop-up dialog mentions that JSON files can be imported as well. Also, it improves the behavior - the optional arguments field appears only when the selected file has `.py` extension, otherwise it's hidden.

**Comment by mrakitin** [comment]
![json](https://cloud.githubusercontent.com/assets/13209176/18453443/5d40d622-790d-11e6-90e3-f2b34d337f16.png)
![python](https://cloud.githubusercontent.com/assets/13209176/18453444/602c9970-790d-11e6-9bba-98ba492475c9.png)

**Comment by mrakitin** [comment]
Set 1st priority due to the related issue #511.

**Comment by robnagler** [comment]
Server side implemented with 48432b5cc56fbec1f5d2086a2c80930731ead231. You need latest pykern.

**Comment by robnagler** [comment]
srw.lib_files() working 0c2ff6e

**Comment by robnagler** [comment]
You'll need to pull out pykern.
