### ISSUE TITLE
clear simulation frame cache

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2430]
when debugging graph problems, it would be nice to be able to clear the browser cache.

**Comment by e-carlin** [comment]
Does a browser hard refresh do the trick?

https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache

**Comment by robnagler** [comment]
The "current frame" gets refreshed, but not the history. It seems like we could do something on our end either on the python side or javascript. For example, on python, we could set the timeout to 5min or something.

**Comment by robnagler** [comment]
I take that back: the current frame does not get refreshed.

**Comment by e-carlin** [comment]
You can also disable the cache but maybe that suffers from the same current frame only problem.

https://stackoverflow.com/questions/5690269/disabling-chrome-cache-for-website-development (can be done for FF too)

Also, the hard refresh may only work with the developer tools open. Not sure.

**Comment by robnagler** [comment]
@moellep is this fixed?

**Comment by moellep** [comment]
The frame cache is now using IndexedDB - you can clear it in the browser by selecting the Application tab, IndexedDB/srCache and "Delete database".

![Untitled](https://github.com/user-attachments/assets/5c6c4c72-371a-44c7-b061-b8c99b5c987f)
