### ISSUE TITLE
reload supervisor, job_agent and job_cmd

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2431]
If files change, job_cmd (at least) should get reloaded dynamically. It would be nice if supervisor and job_agent reloaded as well.

**Comment by e-carlin** [comment]
- [Supervisor is reloaded](https://github.com/radiasoft/sirepo/blob/2a7e531dad21fabab3af0905d775f794754e1ce7/sirepo/pkcli/job_supervisor.py#L47) when files relevant to it are changed.
- for job_cmd and job_agent could this be a feature of pykern.pkcli? We invoke job_agent and job_cmd using it.

**Comment by robnagler** [comment]
Probably when the supervisor reloads (or job_agent/cmd files change), the supervisor should kill all agents.

**Comment by e-carlin** [comment]
When the supervisor reloads it kills all agents. Agents then kill any running job_cmds. The known agentIds are stored in memory. On reload that memory is cleared and when the agent tries to reconnect the supervisor doesn't know it so [it responds with a kill](https://github.com/radiasoft/sirepo/blob/93a842a27caeabd58aa9469c7f0c6b165f34150b/sirepo/job_driver/__init__.py#L171).

**Comment by robnagler** [comment]
Alrighty, it should work. If it doesn't, this Issue will be back.

**Comment by e-carlin** [comment]
When template code is changed the job_agent should reload. The agent reload should force the fastcgi job_cmd to die (it should, confirm that it does).
