### ISSUE TITLE
fastfelo: jspec producing "-nan"

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2434]
This is reproducible on my newest VM, but not on other VMs:

[20200409-jspec-nan.tar.gz](https://github.com/radiasoft/sirepo/files/4462859/20200409-jspec-nan.tar.gz)

The output is in this tarball. The bad lines look like:

```txt
+1.8000000000e+02 -nan -nan -nan +0 -nan -nan -nan -nan -nan -nan -nan -nan -nan +0.0000000000e+00 +0.0000000000e+00
```

**Comment by sjcrs** [comment]
I have been unable to reproduce this on a jupyter instance, and unable to reproduce it locally in a VM on my macbook. When you reproduce the problem, does it always begin on the same line?

**Comment by robnagler** [comment]
No it doesn't begin on the same line. There doesn't seem to be a pattern.

**Comment by robnagler** [comment]
I created a new VM today on my Mac, and I can't reproduce so I'm going to close this.
