### ISSUE TITLE
mpmd: export results to file

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#2440]
Fields at points, field integrals, other?

**Comment by bnash** [comment]
A field map with a 3-D block of field values would be useful also. This can be used as an input to a particle tracking code. Elegant and Zgoubi both have the facility to import field maps and track particles through them.
 
In addition, we will want to output so-called "kick maps" which summarize the field maps by a single 2-D array. The python interface for this exists, but the examples of use have not be translated from mathematica. See FldFocKickPer() for example. We want to include the effects of radiation in the field map. I believe this is already implemented as a Radia function, but need to get more detail from O. Chubar about this.

**Comment by mkeilman** [comment]
@bnash  do you mean a regularly-spaced 3d grid of points? Would the user set the dimensions and number of points?  What format should be used for compatibility with elegant etc.?

**Comment by bnash** [comment]
Hi @mkeilman, yes it would be a regular spaced grid. Mainly this would be for the magnetic field.
I have most recently worked with field map examples from Zgoubi. I will find one.
I will ask about Elegant and try to get an example.

**Comment by bnash** [comment]
@mkeilman I raised this question in an internal forum. It was suggested that we use a file format(s) that is convenient for as many accelerator codes as possible. This may ultimately mean supporting several formats. The codes mentioned that may use these magnetic field maps are OPAL/Astra/TraceWin/Parmela. A format called SuperFish was mentioned. I will get a reference if I can find one.

**Comment by cchall** [comment]
For elegant the format description can be found here: https://ops.aps.anl.gov/manuals/elegant_latest/elegantsu109.html#x120-11900010.5
For an example of writing a field map from Radia to elegant you can look here: https://github.com/radiasoft/rsmoga/blob/master/rsmoga/field_map.py#L277

**Comment by mkeilman** [comment]
Field maps and kick maps are in place
