### ISSUE TITLE
webcon: tuning example seems broken

### ISSUE THREAD

**Issue by j-edelen** [radiasoft/sirepo#2446]
I was not able to run the controls example on production.

**Comment by moellep** [comment]
It looks like it is OK on production, but there are a few things which can make it unresponsive. For example, if you turn on epics on one simulation and leave it on, then if you try to turn it on on a different simulation, the Beam Steering panel will never display. We need to change it so it lets the user know another simulation is running and abort the current one.

**Comment by robnagler** [comment]
See https://github.com/radiasoft/sirepo/pull/2437 for work on showing simulation is running
