### ISSUE TITLE
SRW - Ellipsoid mirror "Distance from Source to Mirror Center" issue

### ISSUE THREAD

**Issue by DmitrySmalyuk** [radiasoft/sirepo#248]
**Description:** In beamline simulation, when using 2 ellipsoid mirrors, an ellipsoid mirror's user-defined "Distance from Source to Mirror Center (p)" value is sometimes automatically reset to the value of "Nominal Position" of that mirror, even though the Distance from Source was set to a specific value by user. This causes inconvenience in situations where, for an ellipsoid mirror, the Distance from Source value must be different from the Nominal Position.

**How to reproduce:**
- create New Simulation
- choose source type Electron Beam with Idealized Undulator
- do not alter any default parameters
- go to Beamline
- Drag and drop an ellipsoid mirror (1) at nominal position 50 m
- Drag an drop an ellipsoid mirror (2) at nominal position 70 m
- Set "Distance from Source to Mirror Center (p)" value for mirror (1) to 10 m
- Set "Distance from Source to Mirror Center (p)" value for mirror (2) to 30 m
- Without closing the parameters menu of mirror (2), click on mirror (1) to open its parameters menu. (when you open the parameters menu of mirror (1), the parameters menu of mirror (2) closes automatically, but the bug only occurs if you open the menu of mirror (1) without manually closing the menu of mirror (2).)
- Note that the "Distance from Source to Mirror Center (p)" value for mirror (1) is now 50 m, not 10 m, even though you just set it to 10 m.

Notes: 
- the same outcome occurs even if you "save changes" after entering the values of nominal position and distance from source, and then open the parameters menu of mirror (1), and, without closing it, open the parameters menu of mirror (2).

**Comment by mrakitin** [comment]
Paul, could you please have a look at the issue when you have time? Thanks.

**Comment by mrakitin** [comment]
Fixed by #497.
