### ISSUE TITLE
SRW - Cancel button and propagation parameters bug

### ISSUE THREAD

**Issue by DmitrySmalyuk** [radiasoft/sirepo#249]
**Description:** In beamline simulation, if you alter any parameters in the Propagation Parameters  menu, and then close the menu, the cancel button that is next to the save changes button does not respond to a click. If you manually return the parameters to their original state, the 'save  changes' and the 'cancel' buttons do go away, but clicking the cancel button does not produce the desired effect.

**Comment by mrakitin** [comment]
Paul, could you please have a look at the issue when you have time? Thanks.

**Comment by mrakitin** [comment]
Thanks Paul! We checked the fix with Dmitry and it works great. Closing.
