### ISSUE TITLE
20221130 SRW: output grid size at watchpoints

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#2492]
When tuning propagation parameters in SRW, it can be tricky to know exactly what effect a particular change has. Ideally, we would like to see the grid size (and ranges) at each of the optical elements so that one can view these as one tunes the propagation parameters.
This may be challenging to access those grid parameters in the midst of propagation. However, the grid size (and range) at the watchpoint is easily available when plotting the intensity from the file. The range is easy to see from the plot, but the grid size is less evident. Reporting that somewhere next to the plot would be helpful.

**Comment by moellep** [comment]
We discussed this today and it should be added.

**Comment by moellep** [comment]
I think we could add the grid size to the lower right portion of the SRW plots, something like the image below:
![srw](https://user-images.githubusercontent.com/6516910/200423023-0c9770f2-7cd0-4261-9cee-3d29ac7f6319.png)

**Comment by gurhar1133** [comment]
> I think we could add the grid size to the lower right portion of the SRW plots, something like the image below: ![srw](https://user-images.githubusercontent.com/6516910/200423023-0c9770f2-7cd0-4261-9cee-3d29ac7f6319.png)

where to do the grid sizes live?

**Comment by moellep** [comment]
It is the width/height of the z_matrix field returned to the client for plotting.
