### ISSUE TITLE
Add support for google analytics

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2497]
Add this to the head, only when google_tag_manager is configured (note jinja values below):

```js
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','{{google_tag_manager_id}}');</script>
```

**Comment by robnagler** [comment]
@mkeilman We'll need a condition in `api_staticFile` to detect whether a page is truly static or not. I think the regexp `en/.*html` should work. We will then need to render the file `en/*.html.jinja` and return it. There will be a conditional in these files to inject the google analytics code if the server is configured with a `google_tag_manager_id`.

**Comment by robnagler** [comment]
Please write a test for this.

**Comment by robnagler** [comment]
1. only the en/ pages
2. it is a configured value in server.py, it will be added to the context for flask.render_template
3. replacement: `git mv landing.html landing.html.jinja`
4. all the pages in `en/*.html` are truly static. We are just handling those as a special case.

**Comment by mkeilman** [comment]
5. What should the test test? The existence of the jinja files, something about the ```google_tag_manager_id```?  I'm not sure where to find purchase as it were

**Comment by robnagler** [comment]
You have to create two test cases. 

I would add the one test case to server_test.py test_srw, which could check that the landing page does not contain the google script. This would be a `pkok` with a `not re.search()` for the expression.

The other test case would provide configuration similar to how job_timeout_test.py provides it so it would be need to be in a different file, e.g. google_tag_manager_test.py. This file would set something like `SIREPO_SERVER_GOOGLE_TAG_MANAGER_ID=xyzzy`, which would then detecte on the landing page. `xyzzy` is just something that isn't going to be on the page otherwise. Here you'd run the same get of the home page. You might also want to get an non-landing html to make sure that it works ok. One of the bugs might be that it the regexp in `api_staticFile` would do the wrong thing and try to inject jinja on the page.
