### ISSUE TITLE
SRW: Install updated .svg icon files

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#2509]
Please install the updated SRW icons here: /Users/paulamessamer/ownCloud/Staff/Marketing/Updated SRW Icons/Sirepo_Software_Icons_May_2020

Kudos to Boaz and Remy for helping with the updated designs.

**Comment by moellep** [comment]
This will be on alpha in the next release.

![Screen Shot 2020-05-22 at 3 03 20 PM](https://user-images.githubusercontent.com/6516910/82709269-6a628100-9c3d-11ea-90b5-dcc41da89530.png)

**Comment by bruhwiler** [comment]
Very nice!

**Comment by messamer** [comment]
Thanks to Remy and Boaz for providing excellent guidance.
