### ISSUE TITLE
SRW - download of raw data file

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#251]
When I try to download raw data file, I get `res_int_se.dat`, but not the one used for plotting - `res_int_pr_se.dat`. There should be more intelligent way to process the files to download.

Also the name should be more meaningful than `-1`, which does not look good. Something like `intensity.dat` would be much better.

-
Steps to reproduce:
- go to the NSLS-II CHX beamline;
- discard changes to the example;
- go to the `Beamline` page;
- wait until the calculations for the both reports finish;
- download raw data for the `Initial Intensity Report, 20.5m` report first;
- then download raw data file for the `Intensity at Sample Report, 48.7m` report;
- compare the two files - they will be different in some cases (the issue is not 100% reproducible since glob.glob() can sort files differently in `sirepo.template.srw.get_data_file()`, so try several times).

**Comment by mrakitin** [comment]
@moellep, is it fixed?

**Comment by moellep** [comment]
No, this one is still open.

Paul

**Comment by moellep** [comment]
This one was fixed with the Aug 5th checkin.
