### ISSUE TITLE
Remove runner 

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2516]
It's obsolete.

**Comment by e-carlin** [comment]
Our runner -> job db upgrade [code is broken](https://github.com/radiasoft/sirepo/blob/master/sirepo/job_supervisor.py#L178) since we move to py3. Should this be removed when removing runner as well?

**Comment by robnagler** [comment]
Upgrade needs to work in py3. Added https://github.com/radiasoft/sirepo/issues/2517 and assigned it to you.
