### ISSUE TITLE
Inform non-premium users when run_dir is purged after x days.

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2520]
Currently the status is just set to Job_run_purged. We should tell users why it was purged and give them info on upgrading so it doesn't happen again.
![Screen Shot 2020-05-15 at 10 08 42 AM](https://user-images.githubusercontent.com/10264515/82072086-47136100-9694-11ea-8512-096ae0dc65f3.png)

**Comment by robnagler** [comment]
@bruhwiler do you want a better notice?

**Comment by bruhwiler** [comment]
"Simulation data purged on <time/date>."
"Upgrade to Sirepo Premium for persistent data."

Delete "Elapsed time: ..."

**Comment by robnagler** [comment]
@e-carlin I think that we should always update lastUpdateTime when __db_init_new is called. We could add another variable, e.g. dbUpdateTime.

**Comment by messamer** [comment]
Final wording:

"Simulation data purged on <time/date>."
"Upgrade to Sirepo Premium for persistent data storage."

Delete "Elapsed time: ..."
