### ISSUE TITLE
elegant: inconsistent negative element lengths

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#2554]
I have an edited version of the SPEAR 3 example https://www.sirepo.com/elegant#/lattice/KkXY42Ko with a new UKICKMAP element U1 added. On Sirepo all the elements have positive lengths however when I run just a beamline named TEST with U1 in it elegant performs backtracking, stating there are negative lengths.

If I download the Python source this appears to be true, all the element lengths in the file appear to be negative. Though this is not being reflected on Sirepo at all.

I haven't been able to reproduce this problem starting from a new simulation so far.

**Comment by moellep** [comment]
It looks like backtracking is turned on for that simulation - select the edit button on the Simulation Status panel on the Visualization tab and toggle the Backtracking field to turn it off. After that the python download will show the normal field lengths.

**Comment by cchall** [comment]
Ah so it looks like from the description the backtracking switch currently in Sirepo just reverses a few parameters manually in the lattice description. I was not aware we had this and was checking the backtracking flag in the elegant log which is turned off for this simulation.

Is there a reason we do this rather than support elegant's builtin backtracking?

**Comment by moellep** [comment]
Good question - I'm not aware of elegant's builtin backtracking, so it may have been a duplication of effort. If you have a good example, please send it my way.

**Comment by cchall** [comment]
It was first added in 2019.3.0 so it's relatively recent and there have been a large number of fixes and upgrades to it in recent elegant releases.
I think it's just adding the `back_tracking` option to `run_setup`. There is supposed to be an example called backtrack-bunchCompCSRLSCWake in the elegantExamples bundle but I don't see it after downloading a new copy. 
I can try to put together a simple example instead.

**Comment by moellep** [comment]
Thanks Chris! We should change sirepo to use the built-in support for backtracking if possible.

**Comment by cchall** [comment]
I've set up a quick test ([reverse.txt](https://github.com/radiasoft/sirepo/files/4726413/reverse.txt)) to verify that the basics of the `back_tracking` option for `run_setup` works as expected. The short answer is that it appears to be as simple as just including the `back_tracking` option. 

With `back_tracking` on running through the 'FORWARD' beamline produced the same results for both Twiss output and particle tracking as using the current Sirepo method of reversing element order and setting lengths negative (I didn't try testing any elements that change energy), tested by turning off `back_tracking` and using the 'REVERSE' beamline. 

As an aside it is a little surprising that the current Sirepo method works at all and seems to do so even for elements like KQUAD which were not supported by `back_tracking` in 2019.3.0. I couldn't find where the manual discusses a convention of inverting the matrix when length is negative, which would be necessary for this to give the right answer.
