### ISSUE TITLE
Optimize plot transfer to client

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#256]
Consider a tiling solution to allow faster download. An example of this is [Mapzen](http://bl.ocks.org/mbostock/5593150), which is a geotiling library for d3.  See #255 for motiviation.

Currently, 95MB output (24MB gzip) takes about 7.5s (25mbps) to download from the alpha server in Dallas to a home in Denver (Chrome speed test says 30 mbps even though I'm paying for 250mps).

**Comment by mrakitin** [comment]
I implemented resizing of the data transferred to the client. Now the default picture/data width is 400 pixels, but could be set in the simulation parameters to 100, 200, 400, 800, 1000, and to the original size.

**Comment by robnagler** [comment]
That's cool. What's the data size reduction? Speed difference?

**Comment by mrakitin** [comment]
It's much faster now. The JSON file with the compressed data with 400 px width is about 5MB. The client will not fail to visualize the data even if it's ~1GB after SRW calculation.

**Comment by bruhwile** [comment]
Very nice Maxim!
David

**Comment by mrakitin** [comment]
Thank you David! I'm also about to commit the implementation of the logarithmic scale for the heatmap plots (https://github.com/radiasoft/sirepo/issues/370).

**Comment by mrakitin** [comment]
I implemented the logarithmic scale in https://github.com/radiasoft/sirepo/issues/370, and fixed negative values of the intensity on the linear scale plots after applying `scipy.ndimage.zoom()`. I suggest we close the ticket and test the new plotting features on alpha/beta. If there are any issues with it, we could create another ticket and address those problems.
