### ISSUE TITLE
mad-x command schema missing default values

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2587]
In the madx-schema.json, many of the commands are missing the correct default values. To see the defaults, for example command "option", start madx and type "help, option".

```
X:> help, option;
command: option  module: control
parameter: echo   logical: true
parameter: echomacro   logical: false
parameter: echosystem   logical: false
...
```

In the madx-schema.json, the defaults for option should be set to these boolean values, replacing the TriStateBool value with regular Boolean in places where a default is present.

Also, the label on the command fields should be all upper-case, for example:

"rbarc": ["RBARC", "Boolean", "1", "Converts the RBEND straight length into the arc length"],

**Comment by e-carlin** [comment]
I don't think the TristateBool can be replaced. Take for example the `trace` flag for the `option` command. Its default value is false.
```
X:> option; //trace is false, there should be no info
option;
X:> option, trace; //set trace to true
option, trace;
X:> option; // we expect trace info
option;
sec.s since start: 11   since last call: 11 //trace info exists
X:> option; //trace default value is false. Not specifying it should set it to false...
option;
sec.s since start: 33   since last call: 7
X:> option; // We expect no trace info
option;
sec.s since start: 35   since last call: 2 // Hmm should be turned off?
```
When a value is set to its default value we don't add it to the command string. But, if a user turns on some functionality that defaults to false (ex trace) then they won't be able to turn it off. 

In my limited testing it seems only the `option` command is effected by this. For example, the `clear` flag of the `select` command is false (its default value) when not specified after setting it to true.

**Comment by e-carlin** [comment]
The help command is also confusing. For example:
```
X:> help ptc_normal;
command: ptc_normal  module: ptc_normal
parameter: icase   integer:          4
parameter: no   integer:          1
parameter: normal   logical: false
parameter: closed_orbit   logical: false
parameter: maptable   logical: false
parameter: time   logical: false
parameter: deltap   double value:                  0
parameter: x   double value:                  0
parameter: px   double value:                  0
parameter: y   double value:                  0
parameter: py   double value:                  0
parameter: t   double value:                  0
parameter: pt   double value:                  0
```
[The documentation](https://mad.web.cern.ch/mad/webguide/manual.html#Ch33.S2) only list 6 parameters. @moellep any idea which one is right or which one we should support?

**Comment by moellep** [comment]
Yes, I see what you mean with the option command. Leaving the TristateBool is fine for that case.

For the help question - only add the documented parameters to the schema. Often the other ones are internal values, or deprecated ones which we don't care about.
