### ISSUE TITLE
Firefox - Cookie will soon be rejected

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2596]
When visiting Sirepo for the first time this warning appears in the Firefox console.

`Cookie “sirepo_cookie_js” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

**Comment by robnagler** [comment]
We can set it for the javascript-only cookies.

We need to reconcile with #2066 if this also blocks server-side cookies.

**Comment by moellep** [comment]
This will be fixed with #4839
