### ISSUE TITLE
SRW - tabulated undulator and measured height profiles in FMX example

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#260]
@DmitrySmalyuk's task.

**Comment by mrakitin** [comment]
Here is the result of partially-coherent calculation with the tabulated undulator:
![partially-coherent-intensity-report](https://cloud.githubusercontent.com/assets/13209176/17481630/2ddaf6ba-5d4c-11e6-8306-805be23be8b9.png)

**Comment by DmitrySmalyuk** [comment]
Results of partially coherent FMX simulation with idealized undulator.

![idealized_undulator_fmx_partially-coherent-intensity-report 3](https://cloud.githubusercontent.com/assets/20563531/17484389/9049ac1e-5d57-11e6-83d4-05feb05ea629.png)

**Comment by mrakitin** [comment]
Implemented in 529415f.
