### ISSUE TITLE
OPAL: aps linac lattice import fails

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#2600]
I came across a large section of the APS linac lattice that I converted from elegant to OPAL a couple of years ago and thought it might be useful for https://github.com/radiasoft/sirepo/issues/2464. 

After editing it to remove CALL statement and some IFs and updating to be valid for OPAL 2.2 it seems to be executed by OPAL without issue. However, the import to Sirepo does not currently work. I just get an error during the import:
> unknown token: l1q5sc4->l

Lattice file:
[aps_linac_sirepo_version.in.zip](https://github.com/radiasoft/sirepo/files/4799191/aps_linac_sirepo_version.in.zip)

**Comment by moellep** [comment]
Thanks for submitting this bug, @cchall. It uncovered several bugs. The fix will be available in the next alpha release. The (hopefully) correct imported lattice can be found here:

https://www.sirepo.com/opal#/lattice/Q349mGGo
