### ISSUE TITLE
download file size max 1M

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2605]
On alpha and prod, the max download file size seems to be 1M. This is too small and I don't see where this is configured.

To reproduce: 

Open the Compact Storage Ring example in elegant, set the particles to 17500 and then download "Raw Data File" on the first phase space report.

**Comment by moellep** [comment]
This appears to be a nginx config problem. In the alpha /var/log/nginx/error.log:

```
2020/06/19 17:56:57 [error] 36202#0: *493955 client intended to send too large body: 1051981 bytes, client: 10.1.2.6, server: docker-job-supervisor-alpha.sirepo.com, request: "PUT /job-cmd-data-file/2EbiAnwl8NsTtyu3mLskwuISPHOUQUyi/elegant.bun HTTP/1.1", host: "docker-job-supervisor-alpha.sirepo.com"
```

The nginx default client_max_body_size is 1m. In alpha.sirepo.com/conf, the size is overridden:

```
client_max_body_size 200m;
```
but this doesn't seem to be taking effect.

**Comment by moellep** [comment]
I verified the problem is a missing "client_max_body_size" setting in the docker-job-supervisor-alpha.sirepo.com.conf file. I've temporarily added an entry to this on alpha, restart nginx and the file can be download.

**Comment by robnagler** [comment]
I updated alpha. beta and prod will update automatically.
