### ISSUE TITLE
Alpha Release 4pm MT 7/2/20

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2607]
- PR Check for an error response from the supervisor. #2609
  - max message size limit should not cause Not Found error #2604
- PR Add species selection panel. #2590 
  - Allow selecting fill species from list (hydrogen, helium, argon)
- PR caplaser negative internal energy #2581 
  - uses new IONMIX table files
- PR madx particle tracking #2602 
  - added MAD-X bunch reports
- PR Control when auth_db is initialized. #2608
  - auth_db init fails for job_agent #2606
- PR Fixes for importing APS linac #2600 
  - Fixes problems for lattices with values which reference other lattice elements
  - Fixed generated code problem relating to integer overflow
- PR Fix #2616 rescale SRW report data if doo large
- PR Fix #2617 Added new min/max intensity selectors to SRW reports
- PR Fix #2618 set IOStream max_message_size
- job.cfg.max_message_bytes shared everywhere #2627
- PR #2631 new SRW features implemented by BNL:
  - Crystal geometry option for Bragg Refraction or Bragg Transmission
  - Added Grating height profile input file.
  - New Grating parameters for energy, CFF, and roll angle.
  - New propagation parameters for shifting the horizontal/vertical position.
- PR New Plans & Pricing page #2630
- irad: many new features implemented
  - trim and rescale demo rtstruct, dvh, ct, roi, dose
  - select multiple 3d ROIs
  - rt dose dropdown panel with dose color ranges
  - ct dropdown panel with hu ranges
  - mouse-over ct and dose values
  - save expanded component state

**Comment by moellep** [comment]
Alpha release at 4pm MT.

**Comment by moellep** [comment]
Current alpha release is failing at random points when trying to connect to github.com or api.github.com:
```
...
Source: /var/tmp/radia-run-5643-18192/20200702222440-radiasoft-download.sh
curl -L -s -S https://api.github.com/repos/radiasoft/containers/contents/radiasoft-download.sh
curl: (7) Failed connect to api.github.com:443; Connection timed out
```

**Comment by robnagler** [comment]
Done, finally.

@messamer you will need to refresh your browser with shift-click on the refresh button in Chrome.

GitHub played nicely on the build after a few tries, but then I got repeated timeouts on the deploy. status.github.com thinks everything is fine.

I don't understand the timeouts. [This guy uses ssh](https://bengsfort.github.io/articles/fixing-git-push-pull-timeout/), which wouldn't work in all cases, but would be a bit of work, and possibly less secure:

```sh
$ git push
Warning: Permanently added the RSA host key for IP address '[192.30.252.151]:443' to the list of known hosts.
Counting objects: 59, done.
```

It is implicitly adding IP addresses, which is dangerous.
