### ISSUE TITLE
"drift" type inconsistency; subtle Python issue; 

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#263]
I'm working on #148 (async execution of all jobs). This changes the dynamics of how the server and client interact with regards to cached reports. In the current synchronous implementation, the client manages a queue of requests. Each request contains the reports parameters, and the response always contains the result (or an error).

In the new model, the request to start the simulation runs, and then the client polls (for now) the server every second to find out if the job is complete. Some of these "short" jobs can take several minutes so this could be a lot of requests. 

The server currently has a check to see if the report's parameters have changed. If so, the report job is restarted. However, this check makes sense if you are sending the parameters only once, not multiple times. Rather, we want to send a signature of the parameters back to the server so it can simple compare that signature with the one stored for the report. 

Unfortunately, there's a small type consistency issue with SRW's "drift". The client is sending an "int" in the parameters, but during the computation on the server, it converts the drift to a float. I suspect [the conversion happens here](https://github.com/radiasoft/sirepo/blob/80556a952849b0483c28101e2d081eb02abf21a9/sirepo/template/srw.py#L222). 

This works fine when you are comparing all the data, because `0.0 == 0` is true in Python, but it doesn't work for a message digest, which needs the serialization of the parameters to be 100% exact. Therefore, the client needs to make sure it sets the type for all values it sends to the server so that the data is serialized and deserialized in a type consistent manner.

I think the Javascript needs to validate the data before it sends to the server and/or the server needs to validate the data, forcing the types. I suspect both have to be done. On the server, it will throw an exception if a type is incorrect. On the client, it should force the types.

This is beyond the scope of what I planned to take on. We need to discuss the best solution. For now, I can continue to have the client send all the data to the server on every poll.

**Comment by mrakitin** [comment]
The type for the drift is set to float in the [_process_beam_drift()](https://github.com/radiasoft/sirepo/blob/master/sirepo/template/srw.py#L1128) function. The type should be float according to the [schema](https://github.com/radiasoft/sirepo/blob/master/sirepo/package_data/static/json/srw-schema.json#L254).

**Comment by robnagler** [comment]
I fixed this in my thread. It was a bug, I believe, in the server side. It actually validates/fixes up values, but that function wasn't being called before all data saves and also didn't have a `float()`. I may patch this separately as my code is fixing up runSimulation.

**Comment by robnagler** [comment]
Fixed in 823adfa
