### ISSUE TITLE
Log message structure

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#264]
I would like to standardize the log messages. A log message is already structured by the module and line and function so you can assume they will they be there in the logs. In general, you want to give more, not less, information. For example, I changed

```python
pkdp('\n{}', traceback.format_exc())
```

to

```python
pkdp('{}: error: e={} {}', material_str, e, traceback.format_exc())
```

This gives the user a clue about the data in error. I prefer the `{obj}: {state}: {data}` format that is found in classical Unix error messages, where `obj` is the object in error or being operated on, 
`state` is a what's going on (e.g. error or `started`), and `data` is whatever information you need (e.g. exception and traceback).

Log messages should be easily parseable by log parsers. Once we are in production, we'll need them, and we'd like to keep them simple. Here's 
[an example](https://github.com/biviosoftware/perl-Bivio/blob/855183ad58e89d20fdf057b13342669b6b97eb7f/BConf.pm#L414)
of a log regular expressions at Bivio. Therefore, you want to avoid putting in formatting like "\n" or "\t", because that just makes it harder to write these logging expressions. We are writing operational server-based code so it's quite different from command line logging. 

We might make an API, e.g.

```python
def log(target, state, kwargs):
     pkdp('{}: {}: {}', target, state, kwargs)
```

**Comment by mrakitin** [comment]
I like the idea of the suggested API. This way we don't need to remember the format of the message, we just need to remember to use this function.

**Comment by robnagler** [comment]
@moellep @mrakitin I added:

```javascript
SIREPO.srlog = console.log;
SIREPO.srdbug = console.log;
```

At the top of every javascript file:

``javascript
var srlog = SIREPO.srlog;
var srdbg = SIREPO.srdbg;
```

* __srdbg__ is used for debugging statements. We can turn them off with: srdbg = function () {}
* __srlog__ is for logging. For now goes to the console, but maybe eventually will also hit a log server.

Please use these. Thanks!

**Comment by mrakitin** [comment]
Sounds good. Thanks Rob!

**Comment by robnagler** [comment]
For javascript, we should use srlog  (free form messages) or exceptionLoggingService, which is structured.

For Python, we are adopting classical unix error messages style: `{}: <description>`.  Use `pkdlog` for all error messages.
