### ISSUE TITLE
'plans' page on alpha is not dynamic

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#2642]
https://alpha.sirepo.com/en/plans.html

Using latest version of Firefox on Win10

The background is static and looks a bit munged as shown in the screenshot below.
I'm assuming it should be dynamic...?

![image](https://user-images.githubusercontent.com/3825435/86428666-8df00100-bcaa-11ea-9caf-5d3cd722d398.png)

**Comment by messamer** [comment]
The graphic should be static.  The website design company is working on an
improved graphic and will check it in on GitHub.

**Comment by robnagler** [comment]
Fix #2644
