### ISSUE TITLE
mad-x lattice export

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#2651]
The export as mad-x lattice button currently seems to just gives a server error on sirepo.com.
Is this expected?

**Comment by moellep** [comment]
Not expected, but I've verified it is also a problem on alpha.

**Comment by moellep** [comment]
This works on alpha, but not beta or prod because the madx app isn't enabled on non-alpha yet.

**Comment by moellep** [comment]
I've enabled the mad-x app for the next production release.
