### ISSUE TITLE
Simple top-level URLs for marketing materials

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2652]
@messamer requests: Top level URLs for marketing materials, e.g. `/plans` should redirect to `/en/plans.html`.

**Comment by robnagler** [comment]
I think these should be redirects, because it will add complexity. We need to add them to the schema or some lookup table to ensure we don't have collisions.

**Comment by e-carlin** [comment]
@messamer we now have top-level marketing urls. So sirepo.com/plans goes to sirepo.com/en/plans (well it will be on alpha once #2790 is closed). Others can be added if you wish.
