### ISSUE TITLE
elegant: Examples/bunchComp - fourDipoleCSR  incorrect dipole setting

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#2660]
It looks like one of the default examples bunchComp - fourDipoleCSR the csrcsbend 'B1' has the wrong settings for the edge angles 'e1' and 'e2'. 

After I use 'discard changes to example' they currently default to e1=e2=0.07. 
They should be e1=0 and e2=0.146607657167524.

**Comment by moellep** [comment]
This fix will be in the next alpha release. You'll need to "discard changes to example" to see the corrected settings.
