### ISSUE TITLE
JSPEC: Plot of Twiss functions not working

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#2671]
Here is an example using the eRHIC lattice from a tfs file:
https://www.sirepo.com/jspec#/source/Csw1I70R

The error messsage when pressing on the "View Twiss Parameter" button is:
` max() arg is an empty sequence`

**Comment by moellep** [comment]
I've verified this bug occurs with any MAD-X lattice. This is related to our switch from python2 to python3.
