### ISSUE TITLE
clear referencing of Sirepo and Sirepo contributors

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#2678]
The wiki should prominently
- list contributors
- explain how interested developers should contact the team
- tell people how to reference the Sirepo team in publications and presentations

The Sirepo apps need to clearly communicate how users should reference their use of that particular app (and in some cases, the underlying community code) when they publish or present results generated from that app

**Comment by remy278** [comment]
@bruhwiler. For contributors: perhaps the list of contributors and contact info for the team could live in a page modeled after https://github.com/rails/rails/blob/master/CONTRIBUTING.md?

Citations: I've looked at various software citation styles, and modeled the below off some guidelines for R.
> Sirepo/[app name], a scientific gateway. RadiaSoft LLC, Boulder, CO. Version X.X.X, as developed on GitHub. Accessed: [date]. URL http://www.sirepo.com/[name].

Feel free to edit. We could use whatever we settle on as the suggested citation and post it on the wiki as well as in the app.

**Comment by robnagler** [comment]
We don't publish versions so I don't think we should expect people to publish them.

What about on premises Sirepo use?

**Comment by remy278** [comment]
Good to know. With that in mind, what about the following?

> **For online GUI**
> Sirepo/[code], a scientific gateway. RadiaSoft LLC, Boulder, CO. Accessed: [date]. URL http://www.sirepo.com/[code].
> 
> **For on-premise**
> Sirepo/[code], a scientific gateway. RadiaSoft LLC, Boulder, CO. As developed on GitHub and installed at [institution name] server. Accessed: [date].

**Comment by robnagler** [comment]
Looks good, thanks.

> For the on-premise instance, should we perhaps link to the github page, as that is where they'd find the code itself?

I guess that's as good as anything.

**Comment by remy278** [comment]
Okay, so we'll go with these for now, unless anyone has an additions to make:

> For online GUI
> Sirepo/[code], a scientific gateway. RadiaSoft LLC, Boulder, CO. Accessed: [date]. URL http://www.sirepo.com/[code].
> For on-premise
> Sirepo/[code], a scientific gateway. RadiaSoft LLC, Boulder, CO. As developed on GitHub (https://github.com/radiasoft/sirepo) and installed at [institution name] server. Accessed: [date].

Next items are contributors list and contact info. I was going to use the Contributors list on the GH side bar to inform the list. Is this correct or should we add others? As for contact info for interested devs, @robnagler should we use sw@radiasoft.net or something else?

**Comment by builder-radiasoft** [comment]
We should always create an external alias. We have support@sirepo.com. Is that good enough?

**Comment by remy278** [comment]
Sure, that works for the contact route.

**Comment by remy278** [comment]
Since the issues we've discussed here apply to Sirepo as a whole, I've added these to the Sirepo wiki home page under FAQs. If we need to make more changes, feel free to reopen this issue. 

As for citation format being visible in-app or somehow automatic from the app, it's a bigger undertaking and @messamer and I will be working on that separately.
