### ISSUE TITLE
JSPEC: Unmagnetized force formula options

### ISSUE THREAD

**Issue by sjcrs** [radiasoft/sirepo#2682]
The most recent changes to the electroncooling repo (https://github.com/radiasoft/electroncooling/commit/7e2bc0008f2f8698a61fb30e4021f9f8cb4b76ef) include new force formula options. Please add "DERBENEVSKRINSKY" "UNMAGNETIZED" and "BUDKER" to the JSPEC interface on Alpha.

**Comment by robnagler** [comment]
@radiasoft/sw I rebuilt rscode-jspec rpm so `radia_run sirepo-dev` should do the trick or just a `dnf update -y` to update your VMs.

I'm building beamsim so the next alpha release will have it.

**Comment by moellep** [comment]
This will be available on the alpha server in the next release. When any of the options are ready for production, open a new issue and we can remove the alpha-only setting.
