### ISSUE TITLE
Clean up language for cancelation of simulations

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2684]
- [ ] Use one L in canceled.

**Comment by messamer** [comment]
**Canceled: Maximum runtime exceeded**
Your runtime limit is 00:00:30. To increase your maximum runtime, upgrade to Sirepo Premium.

NOTE:  "Canceled" is with one l.

**Comment by e-carlin** [comment]
Not to throw a wrench in things but, cancelled (two l's) is what is used in [Python](https://docs.python.org/3.8/library/asyncio-exceptions.html#asyncio.CancelledError) (as well as libraries [like trio](https://trio.readthedocs.io/en/stable/reference-core.html#trio.Cancelled)). It seems cancellation (two l's) is [much more accepted](https://books.google.com/ngrams/graph?corpus=0&smoothing=3&content=cancelation%2Ccancellation&year_end=2000&year_start=1800&direct_url=t1%3B%2Ccancelation%3B%2Cc0%3B.t1%3B%2Ccancellation%3B%2Cc0). We've had some debate previously #2370. I have a slight preference for two l's so we don't get confused with what we write in code vs what is presented to users. 

[Other companies](https://www.schwab.com/legal/schwab-one-account-agreement) can't decide...

**Comment by remy278** [comment]
"Canceled" for all customer-facing comms or anything a user would read. See #2370 for more deets.

**Comment by robnagler** [comment]
The [code is implemented](https://github.com/radiasoft/sirepo/blob/11cc0fe27bed45e4edcb92b98352449e243e5adb/sirepo/package_data/static/js/sirepo-components.js#L313), but I think the other bugs are causing that message from being displayed. We're working on it.
