### ISSUE TITLE
Indicate Plan Level in Profile information

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#2686]
For Profile information (drop down)

> **Paula Messamer**
> Basic
> pmessamer@gmail.com
> 
> Jobs
> Sign out

NOTE: deleted "via email" on the email line

**Comment by e-carlin** [comment]
@messamer is it ok if it says "Sirepo Basic" instead of just "Basic". My understanding is the [plan names have "Sirepo" in them](https://github.com/radiasoft/sirepo/pull/2690#discussion_r460407088) and that is how we have it setup in the application right now.

**Comment by messamer** [comment]
Yes that is fine
