### ISSUE TITLE
Never output "null" or "epoch" to user

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2688]
If there is no data, the output should be n/a or blank. I guess @remy278 may have a comment about this. I saw this on the jobs page just now for a simulation that I hadn't run before:

<img width="796" alt="Screen Shot 2020-07-24 at 2 05 35 PM" src="https://user-images.githubusercontent.com/5495179/88431057-d173f180-cdb6-11ea-8065-e340525d5ffb.png">

**Comment by remy278** [comment]
I lean towards "n/a" to describe such a status. Blank might make users thing it's still pending or cause other confusion.
