### ISSUE TITLE
Zgoubi AGS Booster example can't finish on alpha

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2689]
The default AGS Booster example on Alpha can't complete due to maximum runtime exceeded.

<img width="1144" alt="Screen Shot 2020-07-24 at 7 13 50 PM" src="https://user-images.githubusercontent.com/10264515/88445750-15302080-cde2-11ea-8588-0a2e52ea67d4.png">

**Comment by robnagler** [comment]
I had dialed alpha down to demonstrate what happens when things get purged and stopped. I turned it back up to 1 day (purge) and 10 mins/1 hour (run).

We'll be doing the same thing with beta next week.
