### ISSUE TITLE
missing out.json should recompute report

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2697]
If the out.json file is missing, the whole directory should be deleted and the report should be re-run. Instead, the application gets stuck showing a "No such file or directory" error on the report panel.

To reproduce, open the SRW "Undulator Radiation" example and go to the beamline tab. Let the reports complete, and then remove the out.json file from the simulation's initialIntensityReport directory. Reload the web page and it will show the error message rather than re-running the report.

**Comment by e-carlin** [comment]
We had a [somewhat similar problem](https://github.com/radiasoft/sirepo/issues/2518) with the run_dir being deleted. We need to check for existence of the out.json in the agent and send back a message saying the out.json is missing and the supervisor will run the job again.

**Comment by robnagler** [comment]
I think a more robust solution is: if an exception occurs while trying to get runStatus, remove the run directory and change the state to missing.

**Comment by e-carlin** [comment]
Re-run or just send "missing" back to the gui?

**Comment by robnagler** [comment]
rerun if it is automatic or force.

**Comment by moellep** [comment]
This one happens to me a lot in dev. If a sequential result calc fails, the out.json doesn't get written. Rather than retry on the next visit, fastcgi gets stuck showing "file not found" forever. Only changing the sim which forces the report to recalc from scratch fixes the problem.

This is a hack, but fixes the problem (pkcli/job_cmd.py):
```python
def _do_sequential_result(msg, template):
    try:
        r = template_common.read_sequential_result(msg.runDir)
    except IOError as e:
        # e is actually py.error.ENOENT
        import sirepo.pkcli.job_agent
        raise sirepo.pkcli.job_agent._RunDirNotFound()
    # Read this first: https://github.com/radiasoft/sirepo/issues/2007
    if (hasattr(template, 'prepare_sequential_output_file') and 'models' in msg.data):
        template.prepare_sequential_output_file(msg.runDir, msg.data)
        r = template_common.read_sequential_result(msg.runDir)
    return r
```
