### ISSUE TITLE
Change job_status to job_situation

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2702]
[Running was set](https://github.com/radiasoft/sirepo/blob/467924ccfb4ce3f59afead568569b45824d1cf30/sirepo/job_supervisor.py#L789) when it should be running. set_job_status should assert that it is in the valid set of statuses.

**Comment by e-carlin** [comment]
That job status is [just a message](https://github.com/radiasoft/sirepo/blob/467924ccfb4ce3f59afead568569b45824d1cf30/sirepo/job_supervisor.py#L345) for debugging and can be anything (ex when we [alloc a SlotProxy](https://github.com/radiasoft/sirepo/blob/467924ccfb4ce3f59afead568569b45824d1cf30/sirepo/job_supervisor.py#L107) we set the status to [a deubg message](https://github.com/radiasoft/sirepo/blob/467924ccfb4ce3f59afead568569b45824d1cf30/sirepo/job_driver/__init__.py#L340)). Maybe the function name should be changed to make this clear?

**Comment by robnagler** [comment]
cancel_delay_test.py failed when it ran via test.sh:

```txt
Jul 29 13:48:01 11267     0 ../../sirepo/job_supervisor.py:817:_run error=Trying to overwrite existing jobStatusMessage="Exception: , while Waiting for\
 another simulation to complete" with status="Running" stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 789, in _run
    with op.set_job_status('Running'):
```

This is very confusing, because it looks like an error in capitalization. It's even more confusing, because job.STATUSES is what we are calling state in the job_supervisor. The name "status" in this context should be changed. I picked "situation" in the title of this Issue.

I ran cancel_delay_test.py again, and it passed so I don't know if I can reproduce it. I saved the log.
