### ISSUE TITLE
Elapsed time doesn't update as time increases

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#2703]
As a simulation is running, the "Elapsed time" clock does not reflect the actual run time.  
![IMG_6702](https://user-images.githubusercontent.com/29441306/88822850-a3f5c200-d181-11ea-9bd6-3e5afceff82e.png)
![IMG_6701](https://user-images.githubusercontent.com/29441306/88822867-a8ba7600-d181-11ea-85df-5eb147738fab.png)
![IMG_6703](https://user-images.githubusercontent.com/29441306/88822869-aa843980-d181-11ea-9b2c-d8940962080e.png)

**Comment by robnagler** [comment]
@e-carlin is this an angular thing with the new elapsedTime filter?

**Comment by e-carlin** [comment]
Do you mean [this](https://github.com/radiasoft/sirepo/pull/2690/files#diff-4700cc17d0bc603c0c85d5b5dbbba738R462)? That isn't in master yet.

**Comment by e-carlin** [comment]
This is happening on production so I doubt it it anything too recent. I'm looking into it more.

**Comment by robnagler** [comment]
I meant [this](https://github.com/radiasoft/sirepo/blob/467924ccfb4ce3f59afead568569b45824d1cf30/sirepo/package_data/static/js/sirepo-components.js#L2557):

```js
              'Elapsed time: {{ timeData.elapsedDays }} {{ timeData.elapsedTime | date:\'HH:mm:ss\' }}',
```

It might need to be a function call(?).
