### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#2736]
https://alpha.sirepo.com/elegant#/visualization/m7vSFZZc

I opened a simulation that I had not opened since the alpha release and got this error.
![Screen Shot 2020-08-04 at 11 50 33 AM](https://user-images.githubusercontent.com/29441306/89327417-20d4e000-d649-11ea-862a-d36d536457e8.png)

**Comment by e-carlin** [comment]
Fixed https://github.com/radiasoft/sirepo/commit/a80053802fa0356134e9729caf52a1de609a5ede

**Comment by robnagler** [comment]
@messamer please use a better title for issues. These get automatically added to release notes. "Application Error" is too generic. In this case, pick the more specific error, e.g. Error evaluating SIREOP.APP_SCHEMA.constants.plans[self.upgradeToPlan]"
