### ISSUE TITLE
OPAL: Twiss plot error - Parse error detected by function "Expressions::parseString()"

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#2756]
This error started showing up in the Twiss plot
![image](https://user-images.githubusercontent.com/17073688/89462021-0b83b280-d72a-11ea-944d-7087abd23d5f.png)
The plot was working until I added a variable to the quad K1 values for the lattice, but putting the K1's back didn't fix the issue so maybe this was a red herring. 

Simulation link: https://www.sirepo.com/opal#/lattice/OONZ0tWF

**Comment by moellep** [comment]
The OPAL variable editor needs show an error is an OPAL keyword is used for a variable name. In this case the variable name was "const" which is an OPAL keyword.
