### ISSUE TITLE
docker idle timeout not working

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2764]
There are 20 containers running on prod, some have been up for weeks. They should die. Maybe there was a bug in the idle timer that has been fixed since last prod release (20200508.222615)?

**Comment by e-carlin** [comment]
Not much has changed with the idle code since the last prod release. I don't see any problems and I'm unable to reproduce. Can we look at the logs and see if the kill was ever sent? One hunch is some issue with docker daemon communication.
