### ISSUE TITLE
Jobs page start date format for un-started job

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2768]
On the Jobs page, jobs which haven't started yet are being shown with a Start and Last Update time of "1969-12-31 17:00:00". It would be better to not show anything in those fields in this case.

![Screen Shot 2020-08-10 at 10 40 25 AM](https://user-images.githubusercontent.com/6516910/89807481-eca06a00-daf5-11ea-9f39-ecb88a2bdd82.png)

**Comment by e-carlin** [comment]
Will be fixed when #2730 is merged.
