### ISSUE TITLE
Separate simulation data (models) from operational state

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#277]
Currently models hold both operational data (e.g. simulationStatus) and models (e.g. watchpointReport). This causes confusion about what is required to be saved in the simulation db. This should be models and a few other fields. Operational data shouldn't be saved with a simulation. It might be saved in a run directory's data for a particular report execution. 

While we talked about this on our call, I think we should mark operational data separately and delete before it is saved to the main db. I'll look at modularizing this.

**Comment by robnagler** [comment]
@moellep I'm not seeing rpnCache in master is this in your branch?

**Comment by moellep** [comment]
rpnCache isn't checked in yet. It should be ready by the end of this week.

Paul

**Comment by robnagler** [comment]
@moellep so get_animation_name() returns 'animation' for warp and elegant, because they output multiple reports per run. I had to special case 'animation' in the report parameter hash computation, because it is operational state. 

I think we need to separate out the "report" from the simulation. You run a simulation. The output is zero or more reports. The parameters hashed are for the simulation, not the report. 

I've got a workaround for this issue for now. I'm going to demote to second priority and change to a refactoring.

**Comment by moellep** [comment]
Initially all the apps had just one background task. Warp had this
implemented first and it happened to be called "animation". The same
process was used for elegant and srw. Then srw added a second background
process, so the apps needed a way to track them by name. "animation" is
really just a name for the background task output - it could be one large
file with a set of frames (like warp), a single output file (srw), or a
combination of multiple output files, some of which have frames (elegant).

Paul

**Comment by robnagler** [comment]
Server side is complete in 6cef30f
