### ISSUE TITLE
Failed asset gets on sirepo.com

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2781]
Many errors for failed assets on sirepo.com
<img width="1576" alt="Screen Shot 2020-08-11 at 3 29 48 PM" src="https://user-images.githubusercontent.com/10264515/89950761-80059800-dbe7-11ea-88c9-b7dffc04158f.png">

**Comment by robnagler** [comment]
I'm not seeing this on FF or Chrome.

**Comment by e-carlin** [comment]
Hmm I'm seeing it on FF. When I hover over it it says "blocked by devtools" so maybe it is some configuration on my end. Investigating...

**Comment by e-carlin** [comment]
This seems to be a bug in FF. There is a feature to "enable request blocking" which allows a developer to block certain urls. I had no urls blocked but the feature was on (maybe by default, I don't remember selecting it). I toggled it off and on and when I refresh the page nothing is blocked. If I open a new tab then the blocking occurs again.

**Comment by e-carlin** [comment]
Sorry for the false alarm.
