### ISSUE TITLE
Increase time limit on beta.sirepo.com

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#279]
Currently there is time limit of 1 hour for parallel jobs on https://beta.sirepo.com/light. Can it be increased to 6 or even 12 hours, if possible? @ochubar was interested in this to share the "real" calculations using external resource.

**Comment by robnagler** [comment]
I increased time limit to 12 hours. We'll see what happens.

**Comment by mrakitin** [comment]
Great, thanks Rob!
