### ISSUE TITLE
Saving transform when creating object closes all dialogs and fails to create object 

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#2798]
Related to #2715 I imagine

**Comment by robnagler** [comment]
It would be good to have a reference to the file that's problematic. "Saving transform when creating object" means nothing to me outside that context.

**Comment by mkeilman** [comment]
> It would be good to have a reference to the file that's problematic. "Saving transform when creating object" means nothing to me outside that context.

Cool - this is for multiple open ```modalEditor``` directives in ```sirepo-components.js```
