### ISSUE TITLE
save incremental images during multiple electron simulations

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#28]
Multiple electron images run for an extended time period, perhaps hours.
The criterion for convergence depends sensitively on details of the problem.
In practice, the user looks at the images every so often (e.g. every 15 minutes).

It would be helpful if the user could specify that a plot/report should be saved to disk at a regular time interval, and then scroll through the full sequence at any time, until the simulation is ended.

**Comment by bruhwile** [comment]
Paul and David should further discuss this in the context of today's meeting.

**Comment by bruhwile** [comment]
Solve this by creating a new page, listed to the right of the "Beamline" link along the top, named "Partially Coherent" or something.

It will be analogous to the Warp "Dynamics" page, in that the user cannot modify the beamline or much else, but can only run the simulations, stop it, look at results, etc.

**Comment by bruhwile** [comment]
Has this issue been overtaken by other events?
Paul -- please comment.

**Comment by moellep** [comment]
This issue is still open - it would be a nice report, but fine that it
remain a 2nd priority for now.

**Comment by robnagler** [comment]
Do we want to keep this open for another 6 years?
