### ISSUE TITLE
Display running parallel calculations for user

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#280]
Currently it's hard to find which calculations are running in background. If I use several browsers, it may be even harder to remember what and where I started. It would be really useful to see the active calculations at the expert mode page or on a separate page. The style of Travis-CI can be used to show running calculations and recently finished ones:
![travisci](https://cloud.githubusercontent.com/assets/13209176/17593752/ef26927e-5fb4-11e6-98bf-57238fb1be3a.png)

**Comment by robnagler** [comment]
@mkeilman let's talk about this

**Comment by mkeilman** [comment]
OK, it looks deep
