### ISSUE TITLE
karma tests should always be run on dev

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2806]
In test.sh it has the line in test_main():
```
    if [[ -x ./node_modules/karma/bin/karma ]]; then
        npm run test
    fi
```
If someone doesn't have karma installed on dev the javascript doesn't get tested and you wouldn't know it. If possible test.sh should know it is on dev as always run the karma tests.

**Comment by robnagler** [comment]
Why wouldn't you always install karma? Is it large?

**Comment by moellep** [comment]
That would be fine too - the karma check could be removed and "npm run test" should always get run.
