### ISSUE TITLE
self-extracting simulation error with chrome

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2832]
Running a self-extracting archive from production to dev (and other servers) will sometimes fail in chrome and causes the target server to get logged out. Only seems to happen in chrome - below is the error messages.

![Screen Shot 2020-08-20 at 11 50 14 AM](https://user-images.githubusercontent.com/6516910/90807194-57625a00-e2db-11ea-9d20-f71c991e0c3a.png)

**Comment by e-carlin** [comment]
Related https://github.com/radiasoft/sirepo/issues/2596

**Comment by moellep** [comment]
This bug is still present, but we are removing the /import-archive feature because /import-file is the preferred method.
