### ISSUE TITLE
Decouple import_text from import_file

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2864]
@cchall wants to be able to use sirepo importers without needing to create requests or accessing simulation_db.

Tested on elegant, seems to work.

**Comment by robnagler** [comment]
@cchall do you have data files, and what format are they in?

**Comment by cchall** [comment]
For elegant some good examples that I would want to use right away are:
lte: https://github.com/radiasoft/fastFELO/blob/master/fastfelo/tessa_optimization/input_files/linac/PClinac_TESSA_LSC.lte
ele: https://github.com/radiasoft/fastFELO/blob/master/fastfelo/tessa_optimization/input_files/linac/PClinac_TESSA.ele

For OPAL:
https://github.com/radiasoft/fastFELO/blob/master/fastfelo/tessa_optimization/input_files/injector/aps_linac.in

**Comment by robnagler** [comment]
So we need to take care that knsl45.liwake.sdds name will not get munged. @moellep mentioned that this would happen when we imported an lte.

**Comment by robnagler** [comment]
The software team discussed the issue, and we came to the conclusion that we'll create a library that can be called. It will look something like: `sirepo.lib.importer('elegant').parse_file('elegant.ele')`. The lookup of an importer gives us flexibility on how to find the code to do the work, which is decoupled from the current `template` structure, which we want to change.

**Comment by robnagler** [comment]
@cchall You now say:

```py
import sirepo.lib

d = sirepo.lib.Importer('elegant').parse_file('elegant.ele')
```

`d` is a PKDict (sirepo.lib.SimData). There is [a simple test](https://github.com/radiasoft/sirepo/blob/e6baf594a40305bd4c7a2abbb2bf44bcb4d26244/tests/lib_importer_test.py), which I'll expand as I work on #2865 (export). 

There's a constraint that all files referenced by the .ele have to be in the same directory as the ele.

**Comment by robnagler** [comment]
One other thing: we may want to build an interface to modify parameters. Once you know which parameters you'll be modifying, show me the code, and we'll see if it makes sense to encapsulate that in lib.SimData as opposed to exposing a lot of internals of the data structures. Our goal is to make the interface robust to changes to the internals of Sirepo.
