### ISSUE TITLE
running zgoubi twiss fails with py2 missing

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2873]
Running the twiss report for zgoubi Los Alamos Proton Storage Ring example fails on alpha. Related to this, the sirepo tests/report_test.py is failing. I don't understand how this made it to alpha if the test should have failed.

No such file or directory: '/home/vagrant/.pyenv/versions/py2/bin/python': '/home/vagrant/.pyenv/versions/py2/bin/python'

**Comment by robnagler** [comment]
report_test is not run due to timeout issues during build: https://github.com/radiasoft/sirepo/blob/679fca548cdc44801827931fc24fb6bedd42e2eb/container-conf/build.sh#L54
