### ISSUE TITLE
what happened to the CHX beamline example?

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#288]
Since the move to a folder-based organization of simulations, I no longer see the CHX beamline under Light Source Facilities / NSLS II

Was this intentional?

If not, could it be moved back at the same level as the SMI beamline?

**Comment by robnagler** [comment]
It is there. Did you perhaps delete it?

**Comment by bruhwile** [comment]
I see it now. I was confused, because the SMI beamline appears as a folder, while the CHX and FMX beamlines appear as files. Sorry for the noise.

**Comment by mrakitin** [comment]
In the recent version of the code I moved CHX example to a separate folder since I added CHX with the tabulated undulator (see #167). If you use a new browser or clean your cache, you can see it on alpha.
