### ISSUE TITLE
self-extracting simulations

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#289]
I would like to propose that we bundle simulations as HTML, which would run anywhere. There is a site called [HTML Executable](https://www.htmlexe.com/help/sfxpublication) that has a compiler to make a self-extracting HTML file. You can also [compress data into a PNG](http://www.bitsnbites.eu/?p=20) which can be an embedded image (data uri). Here's a [live example](http://www.p01.org/matraka/matraka.png.html) with audio unfortunately.  

The purpose of this is to allow for self-executing simulations via Jupyter or any other platform that allows you to render HTML. The HTML would redirect to one of our servers, login, send the simulation data (including aux files), and then run in a container. This is different from IPython notebooks, because you don't need to teach operating systems or browsers how to interpret *.ipynb files. These files would just open. They could even hold the plot data (just like ipynb files), but in a compressed format (PNGs or otherwise). 

Inside the simulation, once could specify a docker image, which would either be loaded on our system, or we could download and run.

I am thinking about this, because I'm about to write an abstract for a SIAM CSE mini-symposium about software sustainability. I think it's important to say something different. This would, btw, allow people to use GitHub, Bit Bucket or whatever repo they wanted. The execution would happen on our systems initially, but could be redirected to any compatible Sirepo server.

**Comment by bruhwile** [comment]
Sounds like a good idea to me.

David

**Comment by robnagler** [comment]
The phrase [self-extracting simulations](https://www.google.com/#q=%22self-extracting+simulations%22) does not exist on the interwebs except for this Issue. :)

**Comment by robnagler** [comment]
Very primitive version of this is checked in 5c3d41a. 

Instead of storing the data in javascript, a base64 encoded attribute value containing the zip was used. The form submits to a hardwired URL for now. 

The interface has  "Export as HTML" or "Export as Zip". 

You can't import the HTML directly, but that could be done.

**Comment by robnagler** [comment]
I'm calling this done for now. I implemented a different codec, but I was mistaken about the efficiency of base64 (75%) so the new codec is not that much more efficient, and it makes the file hard to edit. I even left the newlines in the base64, because it makes it possible to edit the file in a text editor.
