### ISSUE TITLE
ml classification argmin bug

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2896]
When selecting the lowest error with np.argmin() be sure to only select the error column, similar to the fixed knn.py.jinja:
```
k_best = {{ knnClassification_kmin }} + np.argmin(np.array(knn_error)[:,1])
```
This is probably wrong in logistic-regression.py.jinja.
```
c_best = {{ logisticRegressionClassification_toleranceMin }} + np.argmin(error)
```

**Comment by e-carlin** [comment]
Fixed by http://v.radia.run:8000/ml#/classification/xPcdGK73
