### ISSUE TITLE
ML wrong label position on heatmap

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2912]
It looks like the confusion matrix heatmap labels are not quite right - the plot below shows the "1" value with the "0" color and one of the "0" values with a "1" color.

![Screen Shot 2020-09-03 at 4 51 08 PM](https://user-images.githubusercontent.com/6516910/92181113-b9f04580-ee05-11ea-89ab-d90a5a1c9340.png)

**Comment by e-carlin** [comment]
@moellep what dataset did you use for this?

**Comment by moellep** [comment]
Here's a dataset which reproduces it:

https://alpha.sirepo.com/ml#/classification/bI2q2shZ
