### ISSUE TITLE
many deprecated unescaped re.search() calls

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2914]
Many of the re.search(), re.match() and re.sub() calls in sirepo/template aren't escaping the expression with r'' which results in deprecated warnings.

**Comment by robnagler** [comment]
I just ran into a few of these. I fixed some.

**Comment by robnagler** [comment]
It's more complicated, because you can't use r'' if there's a utf8

**Comment by moellep** [comment]
```pylint template/*.py | grep W1401``` is showing a lot of other occurances.
