### ISSUE TITLE
_field_type_for_field mpi_io_write_buffer_size: unknown field type for command_global_settings

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#2945]
Using `sirepo.lib.Importer('elegant').parse_file(...)` on a .ele file with global_settings.mpi_io_write_buffer_size seems to result in a warning:

>../../../../.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/template/elegant_lattice_importer.py:136:_field_type_for_field mpi_io_write_buffer_size: unknown field type for command_global_settings

**Comment by robnagler** [comment]
@moellep sez: in elegant_lattice_importer.py, you might try adding it to `_IGNORE_FIELD = ['rootname', 'search_path', 'semaphore_file']`

**Comment by cchall** [comment]
Adding `mpi_io_write_buffer_size` to `_IGNORE_FIELD` gets rid of the warning for me
