### ISSUE TITLE
SimData should provide list of output files

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2947]
See https://github.com/radiasoft/rsopt/issues/20#issuecomment-692231409

@cchall  Do you want the field names that identify the files along with the paths themselves?

**Comment by cchall** [comment]
Providing the corresponding field names could definitely be useful, but is not absolutely required.

**Comment by robnagler** [comment]
@cchall the list is available as `writefile(dest).output_files`. I don't know if the list of files will change with each write, but they might.
