### ISSUE TITLE
Moving jupyterhub users from github oauth to sirepo auth

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2979]
We can get the email with github oauth. Just need to set scope user:email, which should be an easy change to JupyterHub (maybe even config). 

We modify jupyterhub oauth to store the user:email and time, and then redirect to sirepo.com/jupyterlogin. If the user is already in the db, we just redirect, skipping oauth.

If the user is already logged into sirepo, we rename the jupyterhub user appropriately, and redirect to /jupyter. If not, the user will be forced to login. 

A fair bit of state will be stored to make the migration work, but I think the cases should be obvious.

**Comment by moellep** [comment]
I don't think the email shows up with github oauth unless the user has set their public email address in github settings. Most users don't do this.

**Comment by robnagler** [comment]
https://docs.github.com/en/github/authenticating-to-github/authorizing-oauth-apps#user-data

> For example, if you want to use an app that requests user:email scope, the app will have read-only access to your private email addresses.

**Comment by moellep** [comment]
The sirepo github oauth requests "scope user:email" but it returns "email: None" for my account on dev.

**Comment by robnagler** [comment]
So much for documentation. Anyway, we don't need the email, since the user for this scheme, because we can set state in the uri.
