### ISSUE TITLE
Plot refresh button?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#303]
I added some code to allow a plot (panel) to refresh when it gets bad data from the server. This probably should be done server side, but it was easiest if it was from the client to protect against request loops.

Anyway, it would be easy to add a refresh button to the panel. I don't like the idea, because the state should be managed correctly. However, it might be easier than changing a trivial parameter to force a refresh. 

Not important, just thinking about.

**Comment by mrakitin** [comment]
I think it's a good idea to have such a button.

**Comment by robnagler** [comment]
I think we have a good enough solution to this problem. For sequential reports, we ensure the plot is correct. For parallel reports (animations), there's a start/stop simulation button.
