### ISSUE TITLE
Pop-up menu disappears when the animated reports are running

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#304]
If you start the animated report (e.g., long-running Flux animated report for the tabulated undulator), it's causing a pop-up menu to disappear for its own menu and for any other report's menu. This is quite inconvenient when a user wants to change the parameters of this particular report or any other reports.

**Comment by robnagler** [comment]
I'm a little confused. Is this the problem we discussed on the call this morning?

**Comment by mrakitin** [comment]
Yes.
