### ISSUE TITLE
configuration to open /light page for root requests

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3045]
A config value should be added which allows setting the default page for requests to /.

Note: there is already a config parameter SIREPO_FEATURE_CONFIG_SRW_APP_URL which controls the "home" link in the SRW application. Both this and the new parameter should be set at BNL to keep the app within the /light space.

**Comment by robnagler** [comment]
SIREPO_SERVER_HOME_PAGE_URI
