### ISSUE TITLE
srw: last modified on simulations list is confusing

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3046]
The Last Modified column (when viewing the simulations as a list) will show the last date a fixup was run. So when you visit the app after a schema change, all the Last Modified dates are set to the same value.

Instead, the Last Modified should be a special field which is the time the user actually modified the simulation, not the time the sirepo-data.json file was last modified.

**Comment by robnagler** [comment]
We could denormalize that value into the mtime so you don't have to read all the JSON to get the metadata.
