### ISSUE TITLE
output from simulations to what file?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#305]
The elegant implementation monitors the output in a separate log file. The other services write to mpi_run.out. That file is not parsed at the moment. The server startup is run.log. 

It seems to me that we should probably coalesce all output to a single file, and have the simulation implementation parser figure things out. It has to be robust against random changes to the simulation codes anyway.

Thoughts?

**Comment by mrakitin** [comment]
If you decide to have a single log, we may probably need the identified of the process which writes data, something like 
```
[srw] ...
[elegant] ...
```

**Comment by robnagler** [comment]
I don't mean one log. Rather, one log per simulation "report". There are
several logs being written now.

**Comment by mrakitin** [comment]
During the conversation with @robnagler we decided to leave it as is since it's mostly related to elegant, since for SRW there is a single output with a couple of additional status files for multi-electron simulations.

**Comment by robnagler** [comment]
This is modularized well enough.
