### ISSUE TITLE
jspec canceled sim message

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3059]
Canceling a jspec simulation results in a message like this:

"Simulation Canceled: 1603233961 animation frames"

It should just show "Simulation Canceled".

**Comment by e-carlin** [comment]
Do you want the number of frames while the sim is running?

**Comment by moellep** [comment]
I think this problem only shows up in a "Model = RMS" JSPEC simulation. For the particle simulations, it has a frame count which is handled correctly. I think the frame count is correctly not shown during the RMS simulation, and at the end shows "1 frame". The problem is only in the canceled simulation case.
