### ISSUE TITLE
copy of HTML should always work

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#307]
If you get an error on a simulation, you should be able to copy the text. Right now you can't copy and past the error text in the report windows:

<img width="410" alt="screen shot 2016-08-19 at 10 33 47 am" src="https://cloud.githubusercontent.com/assets/5495179/17816829/74c193fe-65f8-11e6-877e-1100dd5dbe03.png">

**Comment by moellep** [comment]
I can't reproduce this anymore.
