### ISSUE TITLE
Constrain SDDS imports to functions that need it

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#3077]
Testing on NERSC has shown that running completely in Shifter may not be possible with libEnsemble. 
If rsopt is started within a Shifter container and the job requires MPI then libEnsemble will try to use mpirun, but it appears MPI commands cannot originate within a Shifter container and a command like:
```
mpirun -machinefile machinefile_autogen_for_worker_2_task_0 -np 1 --ppn 1 elegant fodo_opt.ele
```
gives the error:
```
[mpiexec@nid02304] HYDU_create_process (utils/launch/launch.c:75): execvp error on file srun (No such file or directory)
```

One possible solution is just to install rsopt and dependencies (Sirepo and libEnsemble) natively and have libEnsemble include shifter in the launch command. This shouldn't be hard to implement (though I haven't tried installing Sirepo at NERSC) but does mean users will need to install more software. 

Do you have any suggestions on this issue @robnagler ?

**Comment by robnagler** [comment]
I think we have to do:

```sh
SIREPO_FEATURE_CONFIG_SIM_TYPES=elegant sirepo 
```

And, to not have elegant import sdds unless necessary for the function.

**Comment by robnagler** [comment]
I take that back, you don't need to `SIREPO_FEATURE_CONFIG_SIM_TYPES=elegant` for this application (sirepo.lib).
