### ISSUE TITLE
Update config to  $SIREPO_MPI_CORES

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#308]
The old configuration should still work, but alpha and beta should be updated to set $SIREPO_MPI_CORES.

**Comment by robnagler** [comment]
@mrakitin You'll need to add SIREPO_MPI_CORES at some point. This code is backwards compatible so you don't have to do this right away, but might as well do this when you update for #309

**Comment by mrakitin** [comment]
Thanks for remembering about my installation :).
