### ISSUE TITLE
ml: New Dataset using existing resource file results in file not found

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#3080]
To reproduce:
1. Click on new dataset, enter a name and click save
2. Under Data File choose "iris.data.csv" (iris.data.csv is a resource file from package_data, that's important)
3. Click save changes and see the error

template.ml.py assumes that all files are in the lib dir. Resource files like iris.data.csv aren't.

**Comment by moellep** [comment]
Fixed with 10556286ef0ffe83f1924585d18362e68ddfd707
