### ISSUE TITLE
Radia: Issues with Building Undulator in Design Mode

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#3083]
Hi @mkeilman, I’m going through your tutorial for building the undulator in Radia Sirepo:
https://github.com/radiasoft/sirepo/wiki/How-to-build-an-undulator-in-Design-Mode
It was going really well until I got to the stage of creating the “Magnet-Pole Pair” group. I added the transforms with no problem, but when I tried to save the changes, the “save changes” button was off the screen, and I am not able to scroll down to make it visible. Scrolling with my mouse pad causes the background screen to scroll and not the foreground screen!
This scrolling issue wasn’t there in the “Group” dialogue until I added the transforms.

- [x] #3090
- [x] #3091

**Comment by bnash** [comment]
The next issue I find in going through the tutorial is the last step of creating the "Octant" group. I find that not all the objects are there to add to the group! See attached screen shot of my list of objects in the Design tab, and the objects that are available in Group creation dialogue.
<img width="466" alt="Screen Shot 2020-10-26 at 9 29 04 PM" src="https://user-images.githubusercontent.com/1112276/97254071-359dbb80-17d3-11eb-8d93-f881d2ca026f.png">
<img width="941" alt="Screen Shot 2020-10-26 at 9 29 28 PM" src="https://user-images.githubusercontent.com/1112276/97254076-3898ac00-17d3-11eb-8686-cfe041acfc9a.png">

**Comment by mkeilman** [comment]
Both sub-issues were closed so I'm closing this one
