### ISSUE TITLE
Configure two queues on alpha and beta

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#309]
__dev:__ You can start celery this way:

```bash
SIREPO_MPI_CORES=2 celery worker -A sirepo.celery_tasks -l info -c 2 -Q parallel,sequential
```

__alpha:__ Add `-Q parallel,sequential` to celery-worker config. If we want backwards compatibility, can add `-Q parallel,sequential,celery.`

__beta:__ Add `-Q parallel,celery` (backwards compatible) to apa14 celery worker systemd unit. On apa11 configure celery to start with `-c 4 -Q sequential`.

**Comment by robnagler** [comment]
Done. 
@mrakitin You need to do the same for cpu001. You should start two celery services. We can talk about updating the config at some point. This has to happen before pushing the next release.

**Comment by mrakitin** [comment]
Thank you for the info Rob, I'll contact you next week after the experiment.

**Comment by mrakitin** [comment]
Configured it on cpu-001. Thanks Rob!

As for beta config, do you think it will work with `-c 4`? Last week we figured out the parameter wasn't passed to celery...

**Comment by robnagler** [comment]
I think you need to set the parameter in /etc/default/celery-sirepo so that
it is set correctly.

**Comment by mrakitin** [comment]
OK, sounds good.
