### ISSUE TITLE
Post-angular topics

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#3097]
Not sure whether this has been explicitly laid out, so here are some possible items for discussion, at a higher level than specific issues like #2716 for example.  Once we have a plan we can close this issue.

- html5
- js 6
- jquery
- generate html etc. from classes
- apps become classes?
- schemas define not just views but as much of the UI as possible (app->[pages->[views]] ?). 

Other topics as they arise...

**Comment by robnagler** [comment]
Relegating to ngui
