### ISSUE TITLE
Hanging Warp dynamics computation with Warp on alpha

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#31]
Documenting that alpha1 is hanging right now when you start a Warp simulation. It might be the parameters, but it doesn't get past initializing laser pulse.

This is probably related to the uwsgi problem so we should switch to http proxying (which is ready to merged) to see if this goes away.

**Comment by bruhwile** [comment]
Is this still an issue, or should it be closed?

**Comment by robnagler** [comment]
Irrelevant.
