### ISSUE TITLE
Tests failing: Simulation library file "command_sdds_beam-input.forward-beam-output.sdds" does not exist

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#3103]
job_concurrency1_test.py and report_test.py are both failing on master due to missing lib file.

**Comment by robnagler** [comment]
https://github.com/radiasoft/sirepo/pull/3100 broke this.

I'm on other things so could @moellep or you fix?

**Comment by e-carlin** [comment]
Yes, fixing now.
