### ISSUE TITLE
py.error.EEXIST: [File exists]: symlink from sirepo.lib write_files when file name repeated in multiple fields

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#3113]
When a file is used multiple times in the elegant command file it looks like `write_files` tries to create a symlink to the same file multiple times. See the example where whruby.sdds is used by sdds_beam.input and run_setup.expand_for. The resulting error is:

```
  File "/global/cscratch1/sd/hallcc/warp_install/lib/python3.7/site-packages/rsopt/configuration/setup.py", line 246, in generate_input_file
    model.write_files(directory)
  File "/global/cscratch1/sd/hallcc/warp_install/lib/python3.7/site-packages/sirepo/lib.py", line 58, in write_files
    pykern.pkio.py_path(dest_dir),
  File "/global/cscratch1/sd/hallcc/warp_install/lib/python3.7/site-packages/sirepo/template/elegant.py", line 157, in write_files
    dest_dir.join(f).mksymlinkto(source_path.new(basename=f), absolute=False)
  File "/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/lib/python3.7/site-packages/py/_path/local.py", line 95, in mksymlinkto
    py.error.checked_call(os.symlink, target, self.strpath)
  File "/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/lib/python3.7/site-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.EEXIST: [File exists]: symlink('../../../whruby.sdds', '/global/cscratch1/sd/hallcc/TEST3/elegant_to_genesis_ruby/ensemble/worker1/sim0/whruby.sdds')
```

[ruby_result_ltotessa.txt](https://github.com/radiasoft/sirepo/files/5503544/ruby_result_ltotessa.txt)

**Comment by e-carlin** [comment]
I'll take a look at this @cchall. Can you send all of the files (ltopb_ruby_save.lte, whruby.sdds, etc)?

**Comment by cchall** [comment]
@e-carlin  I think this should be all the input files 
[ruby_files.tar.gz](https://github.com/radiasoft/sirepo/files/5550521/ruby_files.tar.gz)

**Comment by cchall** [comment]
This might be a slightly different issue, but it is related to the file existence checks in general.
When rsopt is using sirepo.lib we need to sometimes write files for multiple elegant simulations to the same directory. These simulations commonly may have shared resources (input distributions, wake files, etc.). Currently this is going to produce the same file exists error during the second write.

**Comment by e-carlin** [comment]
Thanks for the heads up. I'll make sure to protect both cases.

The tarball you sent had broken symlinks instead of the actual files for knsl45.liwake.sdds and whruby.sdds. Can you send those files?

**Comment by cchall** [comment]
Whoops, sorry. This should have the actual files.
[ruby_files_v2.tar.gz](https://github.com/radiasoft/sirepo/files/5555378/ruby_files_v2.tar.gz)

**Comment by e-carlin** [comment]
No worries. Thanks. Fix coming shortly.
