### ISSUE TITLE
example datasets outside of sirepo repo

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3121]
We need more examples for the ML app, but the input datafiles are usually quite large which prevents them from being added to the sirepo repo. We either need a separate sirepo examples repo, or add a way for examples to download an external datafile when needed.

**Comment by robnagler** [comment]
How big?

**Comment by moellep** [comment]
Not too big, maybe several megabytes. Too big to add to the main sirepo repo.

**Comment by robnagler** [comment]
Then we should definitely build them into docker. We can use submodules. We would need a fixup anyway to generate the examples for dev and docker. My guess is submodules are not all that useful, and we should have a tool to build the examples at startup for dev and at build time for docker (build.sh) that pulls in the examples over the net.

**Comment by robnagler** [comment]
I think we should use submodules.

I was thinking we could do something that's even more clever (who me?) that is completely dynamic. All lib names are known via [sim_data._lib_file_list](https://github.com/radiasoft/sirepo/blob/d70d087208dcdb9fd8299b326d7dc187c1a3d5cd/sirepo/sim_data/__init__.py#L588) and [job_driver.make_lib_dir_symlink](https://github.com/radiasoft/sirepo/blob/d70d087208dcdb9fd8299b326d7dc187c1a3d5cd/sirepo/job_driver/__init__.py#L126). If the lib_file_list could contain URIs as well as basenames, we could find the files by pulling them remotely. Initially, this could just be the uri to the github raw file. If we found performance issues, we could have the uri point locally.

However, that would complicate the code for little gain. If you forget to update the submodules in development, it may or may not be obvious, but it won't be problematic. We can add submodule updates to an alias for git pull in home-env so nobody needs to remember it. 

For Docker, it's just another line in the build.

I suggest the repo names be `sirepo-sim-lib-ml` for `ml` which is pointed to by template/ml/lib.

If agreed, I'll implement.

**Comment by moellep** [comment]
Yes, sounds good to me.
