### ISSUE TITLE
ml: csv files with quoted values

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3123]
Python's csv module correctly parses quoted values in a csv column but numpy.genfromtxt() does not. In some cases we use csv, in other numpy.

One solution would be to process the original csv file using the csv module and write out a new one which removes the quoted after removing embedded commas or newlines. Then numpy.genfromtxt() could be used as is.

**Comment by moellep** [comment]
Something like this:
```python
import csv
import re
from pykern import pkio

path = '<file path>'
res = []
with open(path) as f:
    for r in csv.reader(f):
        for idx in range(len(r)):
            r[idx] = re.sub(r'"|\n|\r|,', '', r[idx])
        res.append(r)
text = '\n'.join([','.join(r) for r in res])
pkio.write_text(path, text)

# verify numpy can read the data
import numpy as np
def read_data(path, **kwargs):
    return np.genfromtxt(
        path,
        delimiter=',',
        skip_header=1,
        **kwargs
    )
v = read_data(path, dtype=None, encoding='utf=8')
print(v)

```

**Comment by robnagler** [comment]
Why not parse with csv reader, and just create the ndarray?
