### ISSUE TITLE
SRW - pretty print of the exported JSON file

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#314]
Currently the exported JSON file for SRW simulations looks one-lined:
```JSON
{"models": {"fluxAnimation": {"finalHarmonic": 15, "verticalApertureSize": 1, "photonEnergyPointCount": 1000, "fluxType": 1, "initialHarmonic": 1, "azimuthalPrecision": 1, "longitudinalPrecision": 1, "verticalPosition": 0, "horizontalApertureSize": 1, "finalEnergy": 20000, "polarization": 6, "horizontalPosition": 0, "distanceFromSource": 29.5, "precision": 0.01, "numberOfMacroElectrons": 100000, "method": 1, "initialEnergy": 10000}, "electronBeam": {"horizontalAlpha": 0, "verticalBeta": 3.4, "energy": 3, "verticalAlpha": 0, "horizontalPosition": 0, "driftCalculationMethod": "auto", "beamSelector": "NSLS-II High Beta Day 1", "verticalPosition": 0, "isReadOnly": true, "verticalEmittance": 0.008, "current": 0..............
```

It would be much more useful to have it formatted with https://github.com/radiasoft/pykern/blob/master/pykern/pkunit.py#L115:
```python
def json_dumps(obj):
    """Formats `obj` as multi-line, sorted json
    Args:
        obj (object): to be converted
    Returns:
        str: formatted json
    """
return json.dumps(obj, sort_keys=True, indent=4, separators=(',', ': ')) + '\n'
```

**Comment by robnagler** [comment]
Pretty printing is available in simulation_db.

**Comment by mrakitin** [comment]
@robnagler, please see the fix in my branch - f06df62. Is it good enough, or you prefer to decorate only the exported data? I suppose `_json_response()` is used for internal data exchange which does not need to be human-readable.

**Comment by robnagler** [comment]
We don't want to pretty print all json responses. Rather, we just want to
pretty print the exported data. The opposite of save simulation:

https://github.com/radiasoft/sirepo/blob/fe3aa5b361908e7c4bccdf087b1367a04342b064/sirepo/simulation_db.py#L390

**Comment by mrakitin** [comment]
I created a separate function ` app_simulation_data_export()` and `_json_response_for_export()` in ce4dbe1, so the conversion is done for exported data only. In the mentioned `save_simulation_json()` function `write_json()` is used, which also formats JSON with `generate_pretty_json()`.

**Comment by mrakitin** [comment]
Looks great! http://localhost:8000/simulation/srw/7yZuXM8D/1 will export formatted data while http://localhost:8000/simulation/srw/7yZuXM8D/0 will export one-row data.
