### ISSUE TITLE
elegant: errors in shell command handling

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#3145]
There are two issues with handling of shell commands given in an elegant command file.
See example in `twiss_output.beta_x`: https://www.sirepo.com/elegant#/control/HnD5RV54
`beta_x = "{sddsanalyzebeam whruby.sdds -pipe=out | sdds2stream -pipe -column=betax}"`

- Importing into Sirepo the import of the command and write out seem to be handled just fine, but the input distribution `whruby.sdds` is also being used by `sdds_beam` and Sirepo is mangling the file's name without changing the shell command.

- If using `sirepo.lib.Importer` directly `parse_file fails`, I think because it tries to evaluate the shell command as an RPN command. 

```
/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/template/template_common.py:605:subprocess_output ['rpnl', ' {sddsanalyzebeam whruby.sdds -pipe=out | sdds2stream -pipe -column=betax}']: exit=1 err=b'unknown token: {sddsanalyzebeam
unknown token: whruby.sdds
unknown token: -pipe=out
unknown token: |
unknown token: sdds2stream
unknown token: -pipe
unknown token: -column=betax}
'
/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/template/elegant.py:210:_model model=command_twiss_output field=beta_x decl=['Beta X', 'RPNValue', '1', 'If matched is zero, the initial values for the X plane.'] value={sddsanalyzebeam whruby.sdds -pipe=out | sdds2stream -pipe -column=betax} exception=expr={sddsanalyzebeam whruby.sdds -pipe=out | sdds2stream -pipe -column=betax} err=invalid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/lib.py", line 27, in parse_file
    self.__adapter.parse_file(p),
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/template/elegant.py", line 129, in parse_file
    return self._convert(d)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/template/elegant.py", line 218, in _convert
    _model(m, LatticeUtil.model_name_for_data(m))
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/template/elegant.py", line 195, in _model
    if _rpn('RPNValue', 'Float'):
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/template/elegant.py", line 187, in _rpn
    model[k] = c.eval_var_with_assert(v)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/template/code_variable.py", line 69, in eval_var_with_assert
    assert not err, f'expr={expr} err={err}'
AssertionError: expr={sddsanalyzebeam whruby.sdds -pipe=out | sdds2stream -pipe -column=betax} err=invalid
```

For the Importer my first thought is that shell commands should be ignored and written out without evaluation. Pure RPN commands should be evaluated still, but this would mean that cases with shell commands inside RPN commands would also be left unevaluated. Though if the command is operating on a file that elegant will generate during the simulation this could still fail since `write_files` does still mangle the output file names.

**Comment by robnagler** [comment]
If sirepo.lib did not mangle file names, would this work ok? 

We just have to put more hooks in the elegant importer for sirepo.lib to make this happen. I don't think it is complicated.

**Comment by cchall** [comment]
I don't think the file name mangling is the initial issue with the sirepo.lib case. Though we maybe should talk about at least having the option to not mangle any file names.

**Comment by robnagler** [comment]
@e-carlin this issue, #2610, and a couple new issues. I'll discuss with you today maybe around 2p.

**Comment by e-carlin** [comment]
@cchall I [opened a PR](https://github.com/radiasoft/sirepo/pull/3183) that partially fixes this. It works in the sirepo.lib case. For the Sirepo web app the filename mangling issue still persists. Is that ok?

**Comment by cchall** [comment]
That's fine with me. The sirepo.lib case is the only one I really need working.
