### ISSUE TITLE
Remove name mangling in elegant

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3148]
Don't mangle any names, including the lattice from the original elegant input file.

**Comment by e-carlin** [comment]
What about output filenames? We have things like `final = %s.fin,` in the command file. Should we parse that statement and build the filename from it?

**Comment by e-carlin** [comment]
@robnagler from my reading of the code we don't mangle filenames when using sirepo lib (except for outputfiles, see above). I must be missing something so can you provide an example?

**Comment by robnagler** [comment]
We mangle the lattice, for sure. Try changing the name, and see what file gets created.

**Comment by robnagler** [comment]
We don't want to mangle output eitehr.
