### ISSUE TITLE
Data transfer to a plot times out after 60 seconds

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#317]
I tried to do SRW calculations for the SMI beamline, and noticed that there is a timeout of 10 seconds for data transfer. The calculation finishes fine and I can find the resulted intensity `res_int_pr_se.dat` file on the server, but it's not plotted:
![timeout](https://cloud.githubusercontent.com/assets/13209176/17942204/6fc80b52-6a04-11e6-84f7-b5086f930df0.png)
@robnagler, is there anything we can tune to allow longer transfer time?

**Comment by mrakitin** [comment]
Thanks Rob!

**Comment by mrakitin** [comment]
Here is the input file where we observe 60 seconds timeout: [sirepo-data.json.txt](https://github.com/radiasoft/sirepo/files/439646/sirepo-data.json.txt). Watchpoint report had data file of ~600MB.

**Comment by robnagler** [comment]
Need the mirror file "HFM_Rh7.6km.dat". However, I am removing the timeout for now since we really need to fix this another way.

**Comment by mrakitin** [comment]
Rob, the file could be found here - https://github.com/radiasoft/sirepo/blob/master/sirepo/package_data/static/dat/HFM_Rh7.6km.dat.
