### ISSUE TITLE
Make jupyterhublogin src_db_root and dst_db_root the same

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#3171]
Only offer one cfg option for db root.

**Comment by robnagler** [comment]
I was thinking about this. Why are we renaming the directories/users at all? Seems like we could just adopt the github name, and not move the directories.

**Comment by e-carlin** [comment]
We create the user when they first come to our site and then we ask them if they want to migrate. So we don't know their handle until after the user has been created. After we get their github handle we could change their username to be it and not do a rename?

**Comment by robnagler** [comment]
yes, that makes more sense to me, because we are doing too much work, and it is easier to update the db entry atomically than to coordinate the change of dirs and db.
