### ISSUE TITLE
Error in Authenticator.pre_spawn_start: Permission denied: '/srv/jupyterhub/scratch'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3203]
sirepo_jupyterhub.volumes not necessarily working.

**Comment by robnagler** [comment]
Fixed with config, but larger problem that /srv/jupyterhub/{user,scratch} must migrate to /srv/sirepo_juptyerhub/{user,scratch}. This will require a coordinated restart of all nodes.

**Comment by e-carlin** [comment]
We ended up mount /srv/jupyterhub/... in the container.
