### ISSUE TITLE
Updating variables in Sirepo does not update numeric values

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/sirepo#3237]
The attached image shows incorrect preview of the numeric value for V_1. It should be 40, not 66.6... This happened after setting L_1 to 1.5, then changing it to 2.5. The numeric value appears correctly in the individual elements when the variable name is used, but continues to list the original numeric value next to the expression in the Variables window.

<img width="592" alt="badmath" src="https://user-images.githubusercontent.com/7430829/102274580-5932d780-3ee1-11eb-83cd-f81f582c06fb.png">

**Comment by robnagler** [comment]
No longer happens
