### ISSUE TITLE
SRW: allow change of source type between Gaussian, undulator, and dipole

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#3241]
I've recently had two different cases where I want to switch the source type in my Sirepo simulation, once from dipole to Gaussian, and another case from Gaussian to undulator.
From what I can see, there isn't a way to do this directly in Sirepo (without editing the virtual beamline file and reimporting.)
If this isn't too difficult, it would be a useful feature. Or please let me know if there's a way to do this that I missed.

**Comment by moellep** [comment]
The feature is hidden away. You can change the source type by selecting the simulation name line at the top of the page. After changing the source type, you will need to refresh the browser to work-around the bug #3049.

**Comment by bnash** [comment]
Yes, I missed that. Thanks a lot! Great to see this is already available.
