### ISSUE TITLE
Jupyter 413 Error: Request Entity Too Large

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#3259]
While running a Jupyter notebook, I'm receiving the following error:
![Screen Shot 2020-12-21 at 12 11 14 PM](https://user-images.githubusercontent.com/11053323/102813717-8e7a7200-4386-11eb-9159-6201e85b288f.png)

A brief search suggests that this problem can be resolved by [increasing `client_max_body_size` in Nginx](https://github.com/jupyterlab/jupyterlab/issues/4214).

**Comment by robnagler** [comment]
It's now 200MB. We can change it.

**Comment by e-carlin** [comment]
Closing, I believe this was fixed through configuration.
