### ISSUE TITLE
case issue with jupyter migration

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3267]
The xYz (not real name) is in the database, but there are now two directories:

```txt
drwxr-x---   2 vagrant vagrant     6 Dec 22 21:12 xYz
drwxr-x---   7 vagrant vagrant   148 Dec 22 21:50 xyz
```

The second directory is empty.

Also the randomization is not always 5 chars. This seems odd.

**Comment by e-carlin** [comment]
Fixed by #3268
