### ISSUE TITLE
STL import

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#3270]
This may end up being part of the Phase 2a but the initial steps are not too complicated so I'll make this issue for it.  The plan is to copy the warpvnd interface

(edited to mention that approach won't work here, because we have to let Radia create the object and then display it, not feed an arbitrary stl file to Radia)

- [x] simple import (#4829)
- [x] GUI (#4848)
- [x] complex import with user feedback for invalid files or concave objects
- [x] tests for good and bad objects (#4849)

**Comment by mkeilman** [comment]
This issue should include using STL imports as individual magnet components, not just an entire simulation

**Comment by mkeilman** [comment]
I don't see a specific "import stl" function in Radia - the most generic thing is `RadObjMltExtPgn` which builds an object up from stacked convex polygons.

**Comment by mkeilman** [comment]
We have had problems getting `ObjPolyhdr` to work. For example here is some code to test the simplest possible polyhedron (a tetrahedron):
```python
import radia
import numpy
p = [[0, 0, 0], [1, 1, 0], [0, 1, 0], [0.5, 0.5, 1]]
f = [[0, 1, 2], [0, 1, 3], [0, 3, 2], [3, 1, 2]]
g_id = radia.ObjPolyhdr(p, f)
d = radia.ObjDrwVTK(g_id, "Axes->No")
numpy.array([round(x, 6) for x in d["polygons"]["vertices"]]).reshape(-1, 3).tolist()
[
    [1.0, 0.0, 0.0], [0.0, 0.0, 0.0], [1.0, 1.0, 0.0],
    [0.0, 1.0, 0.0], [0.0, 0.0, 0.0], [1.0, 0.0, 0.0],
    [1.0, 1.0, 0.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0],
    [1.0, 1.0, 0.0], [0.0, 0.0, 0.0], [0.0, 1.0, 0.0]
]
```
The generated vertices are missing points supplied to the function and include points not supplied. They are also all in the same plane. The function also sometimes causes a segfault. We are exploring using `ObjMltExtPgn` - which would be an approximation - as an alternative.

@cchall or @j-edelen, have you had success using `ObjPolyhdr`?

**Comment by cchall** [comment]
I've been able to use `ObjPolyhdr` in the past to do very similar things.
I'll take a look at this example and see what I can find.

**Comment by cchall** [comment]
I think it was just the face indexing. Radia uses 1-based indexing.

```python
import radia
import numpy
p = [[0, 0, 0], [1, 1, 0], [0, 1, 0], [0.5, 0.5, 1]]
f = numpy.array([[0, 1, 2], [0, 1, 3], [0, 3, 2], [3, 1, 2]]) + 1
g_id = radia.ObjPolyhdr(p, f.tolist())
d = radia.ObjDrwVTK(g_id, "Axes->No")
numpy.array([round(x, 6) for x in d["polygons"]["vertices"]]).reshape(-1, 3).tolist()
[[0.0, 1.0, 0.0],
 [1.0, 1.0, 0.0],
 [0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0],
 [1.0, 1.0, 0.0],
 [0.5, 0.5, 1.0],
 [0.0, 0.0, 0.0],
 [0.5, 0.5, 1.0],
 [0.0, 1.0, 0.0],
 [0.5, 0.5, 1.0],
 [1.0, 1.0, 0.0],
 [0.0, 1.0, 0.0]]
```

**Comment by mkeilman** [comment]
Oh, for goodness sake.  @Benbenbenin0 does that info help?

**Comment by Benbenbenin0** [comment]
Yup, feature works...
Thank you @cchall

**Comment by mkeilman** [comment]
All sub-tasks completed
