### ISSUE TITLE
add Accelerator Toolbox (AT) support

### ISSUE THREAD

**Issue by matsievskiysv** [radiasoft/sirepo#3326]
[AT](https://github.com/atcollab/at) now supports Octave and doesn't rely on commertal software which makes it eligible for adding to sirepo.
Its addition to Jupyter should be straightforward: build script may be copied from provided [octave.dockerfile](https://github.com/atcollab/at/blob/master/jupyter/octave.dockerfile).

**Comment by robnagler** [comment]
Thanks, Sergey. We will have a look.

**Comment by bruhwiler** [comment]
@matsievskiysv -- how many users do you think would be actively engaged in using AT on Sirepo/Jupyter?

Please email support@radiasoft.net if you would like to discuss further.

**Comment by matsievskiysv** [comment]
AFAIK AT is often used together with Elegant in order to double check calculations.
