### ISSUE TITLE
warpvnd: sirepo 2d impact density plot doesn't agree with rswarp plot

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#3327]
I noticed some strange behavior from the impact density plot when running the Gridded TEC 2D Opt. A link to the simulation is here: https://www.sirepo.com/warpvnd#/visualization/nGfGsMXE

Sirepo's impact density plot shows a very high of particles at the emitter (left side of figure) rather than on the collector (right side). 
![Impact-Density](https://user-images.githubusercontent.com/17073688/106638158-ce657500-6540-11eb-822c-7f1b8cfd8842.png)
Rerunning the downloaded script and plotting with:
```
from rswarp.diagnostics.ImpactDensity import PlotDensity
from matplotlib import gridspec
import matplotlib.pyplot as plt
fig = plt.figure(figsize = (12, 8))

gs = gridspec.GridSpec(1, 2, width_ratios=[1, 0.1])
ax1 = plt.subplot(gs[0])
ax2 = plt.subplot(gs[1])

myplot = PlotDensity(ax1, ax2, scraper=scraper, top=wp.top, w3d=wp.w3d, use_aura=True)
myplot.generate_plots_2d()
plt.show()
```

Gives a very different result which is more in line with the expected. The highest density regions are all on the right side on the collector. 
![mpl_impact_density](https://user-images.githubusercontent.com/17073688/106638542-3b790a80-6541-11eb-97f2-73ecc6ebfb20.png)

**Comment by moellep** [comment]
Yes, that simulation has always bothered me - in Sirepo, it looks like particles are reflecting off the anode and returning to the cathode:

![Particle-Trace](https://user-images.githubusercontent.com/6516910/106646892-708a5a80-654b-11eb-9b76-7e1d5aa34cf7.png)

I'll use your example in a jupyter notebooke to see if I can narrow down the problem.

**Comment by moellep** [comment]
I think the sirepo plot is actually correct for this simulation. The rswarp ImpactDensity isn't normalizing each scatterplot. The corrected plot matches sirepo:

![Screen Shot 2021-02-02 at 2 23 00 PM](https://user-images.githubusercontent.com/6516910/106664626-8fe0b200-6562-11eb-8823-b89c7ec57b3a.png)

Below is the code change to normalize generate_plots_2d():

```python
    def generate_plots_2d(self):
        # minS, maxS = maxsize, 0
        # scatter_plots = []
        # for cond in self.conductors.values():
        #     minS, maxS, face_data = self.generate_plot_data_for_faces_2d(cond, minS, maxS)
        #     for (x, z, s) in face_data:
        #         if np.min(s) < 0.0:
        #             scatter_plots.append(self.ax.scatter(z, x, c=s, s=1, linewidths=0, zorder=50))
        #         else:
        #             scatter_plots.append(self.ax.scatter(z, x, c=s, cmap=self.cmap, s=1, linewidths=0, zorder=50))
        # self.cmap_normalization = self.normalization(minS, maxS)
        # ColorbarBase(self.ax_colorbar, cmap=self.cmap, norm=self.cmap_normalization)
        minS, maxS = maxsize, 0
        scatter_plots = []
        faces = [];
        for cond in self.conductors.values():
            minS, maxS, face_data = self.generate_plot_data_for_faces_2d(cond, minS, maxS)
            faces.append(face_data)
        self.cmap_normalization = self.normalization(minS, maxS)
        for face_data in faces:
            for (x, z, s) in face_data:
                if np.min(s) < 0.0:
                    scatter_plots.append(self.ax.scatter(z, x, c=s, s=1, linewidths=0, zorder=50, norm=self.cmap_normalization))
                else:
                    scatter_plots.append(self.ax.scatter(z, x, c=s, cmap=self.cmap, s=1, linewidths=0, zorder=50, norm=self.cmap_normalization))
        ColorbarBase(self.ax_colorbar, cmap=self.cmap, norm=self.cmap_normalization)

```

**Comment by cchall** [comment]
Thanks for the investigation @moellep. It looks like neither the pure rswarp or the rswarp/sirepo plots are coming out quite correctly. I did a 2D histogram of the raw lost particle positions and get: 
![hist2d_impact_density](https://user-images.githubusercontent.com/17073688/106672331-1dc19a80-656d-11eb-999b-049ab4931756.png)
Which is probably shows what we really want pretty well given the ratios of lost particles  / total lost look like:
emitter(left side): 0.01
collector(right side): 0.91
grid(all center boxes):  0.07

I think the reason that the Sirepo plot doesn't reflect this (and that rswarp is not normalizing all the surfaces) is that the KDE calculation is done for each conductor independently and the extracted values can't be compared without some other normalization being performed. Though rswarp does try to convert the surface values to a current which is probably not correct given this fact.

Fixing this probably warrants a new issue in rswarp.

**Comment by moellep** [comment]
I've updated sirepo so it will now show the impact density as a heatmap. This can be switched back to the previous plot if the normalization problem is rswarp is corrected.

![Impact-Density (6)](https://user-images.githubusercontent.com/6516910/110674782-7947ff00-818f-11eb-9fe6-35be8ca74dee.png)
