### ISSUE TITLE
Opal TypeError: list.sort is not a function

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#3348]
I was clicking around the Opal CSR Bend Drift app on alpha with the dev tools open and saw this when I went to the source tab:
```
TypeError: list.sort is not a function
    sortList sirepo-components.js:773
    loadAuxiliaryData sirepo.js:2038
<Snip>
Error: [ngRepeat:dupes] http://errors.angularjs.org/1.7.8/ngRepeat/dupes?p0=item%20in%20itemList()&p1=string%3A%3C&p2=%3C
```

**Comment by moellep** [comment]
I think this could be related to the missing cookie error - I think the request to get the related simulation list is getting an auth exception and the software isn't expecting that.
