### ISSUE TITLE
Error: another browser is running the simulation

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#3403]
From the Gridded 2D Opt Simulation on WarpVND: https://www.sirepo.com/warpvnd#/optimization/alaNGnNc

After testing a few iterations I ran into the following error, which I've never seen before. Just prior to this I received a 504 Gateway, which I usually fix through restarting the simulation.

![Screen Shot 2021-03-15 at 1 50 38 PM](https://user-images.githubusercontent.com/11053323/111212646-738a5900-8595-11eb-95ba-490b73695096.png)

Is this normal behavior? If so, how should it be avoided?

**Comment by robnagler** [comment]
Too old. If you run into again, create another issue or reopen.
