### ISSUE TITLE
hard to track down compute model errors

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3418]
When a new report is added, the correct entry has to be made in the sim_data module and also in the javascript module for the compute_model(). If one is left out, it is very difficult to determine the problem based on the server error. It would be much nicer to have a way to define the compute model once in the app schema, possibly using a regular expression.

**Comment by robnagler** [comment]
Is there a way to add it to the schema?

**Comment by moellep** [comment]
Yes, in most cases it is a simple mapping. But I'd need to look at the special cases where reports are created on the fly.

**Comment by robnagler** [comment]
#2070
