### ISSUE TITLE
Client should watch for db updates and refresh

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#342]
The client should poll the server for changes to the simulation. This is related to autoSave, which will get collision detection once #341 is implemented.

Propose to make autoSave poll regularly with "no changes" updates. If the serial number updates, the client will get the new version of the data automatically in reply to the autoSave. The client will then refresh the state of all panels.

**Comment by mrakitin** [comment]
Closing since it's implemented previously.
