### ISSUE TITLE
api_errorLogging not logging always?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3425]
we had some authstate errors (which we could simulate by injecting errors) which caused the gui to post to /error-logging but nothing was logged.

**Comment by e-carlin** [comment]
I can't repeat this. I put a raise in authState and get the exact same error message we were seeing in the gui. The gui posts to /error-logging and I see the log. The [error logging code](https://github.com/radiasoft/sirepo/blob/9a42a0a32b644e87892a35bb2c419e37c4fea4f5/sirepo/server.py#L141) seems pretty robust.

One concern is the new srcontext code somehow messing with the flask.request object and causing a problem. I tried running with uwsgi to run with multiple threads and still found no issue.

Maybe whatever was causing authState to fail was also preventing errorLogging from working. Should I dig more or wait to see if it happens again?
