### ISSUE TITLE
Parse error detected by function

### ISSUE THREAD

**Issue by dikai-li** [radiasoft/sirepo#3437]
While loding "Source" tab in the OPAL of sirepo project, the error message shows up:
"
 Parse error detected by function "OpalParser::readStatement()"
in line 1 of file "opal.in" before token "Error token: String """ not terminated at end of line.":
Error token: String """ not terminated at end of line. SIMULATION NOTES:MAR. 25 WEBINAR Error token: String """ not terminated at end of line. REAL L_0=0.5;
aCommand should begin with a <name>.
"

Such error message shows up in all the 4 "phase space" window, and not any window shows expected plot.

What I did was just follow the tutorial at Youtube channel,
www.youtube.com/watch?v=pJSQgmmt-94

So any idea what's wrong here?

As a reminder: I get nothing wrong while following the tutorial of elegant.

**Comment by moellep** [comment]
Hi @dikai-li, 
You have encountered a bug in our software. The work-around is to select the simulation link at the top of the page "dikai_gun" and clear the text in the Notes fields, then change a parameter on the Distribution panel and the simulation should rerun successfully when you select Save Changes. That text was being added to the generated opal script in an incorrect manner. We'll have this problem fixed shortly.

**Comment by moellep** [comment]
Fixed with #3438
