### ISSUE TITLE
add Sirepo Slack organization to the ? dropdown list

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#3459]
In order to encourage more use of the Sirepo Slack organization, I would like have a link added to the end of the list of resources that users find when they click the ? dropdown icon:

![image](https://user-images.githubusercontent.com/3825435/113059246-74fa7a80-916c-11eb-9844-d94d6db155e8.png)

**Comment by robnagler** [comment]
I think that's too subtle.  Side label or even an annoying (configurable) popup. In general, if you want to drive traffic, you have to be aggressive. I've been actively updating slack.sirepo.com so we can use that link in the code.

**Comment by robnagler** [comment]
#4070 #4071 #4072
