### ISSUE TITLE
madx: allow element with '-' in name

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3473]
MAD-X lattices may have elements with '-' in the name. The sirepo parser doesn't seem to allow that.

**Comment by e-carlin** [comment]
https://github.com/radiasoft/sirepo/issues/2612

I seem to recall that something in the GUI code broke with '-' in a model name.

**Comment by e-carlin** [comment]
Maybe not though. Maybe it was just other special characters. I'll dig around some to try and find out...

**Comment by moellep** [comment]
I tried a lattice with '-' in element names and MAD-X failed unless the value was quoted. The original lattice I was testing with may not have been valid MAD-X to begin with.
