### ISSUE TITLE
SRW - statuses of persistent calculations

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#348]
There are a couple of confusing statuses with the persistent calculations, e.g. with the animated Flux report:
- `Simulation Error: ../../../../../../../pykern/pykern/pksubprocess.py:63:check_call_with_signals 24485: started: ['mpiexec', '--bind-to', 'none', '-n', '2', '/home/vagrant/.pyenv/versions/2.7.10/bin/python2.7', 'mpi_run.py']`:
  ![restart](https://cloud.githubusercontent.com/assets/13209176/18364420/4238e222-75dc-11e6-8965-0ef0c78a0479.png)
  **Steps to reproduce:**
  - go to Sirepo :arrow_right: <kbd>Expert users only</kbd> :arrow_right: :open_file_folder: `Examples` :arrow_right: :page_facing_up: `Tabulated Undulator Example`;
  - click <kbd>Start New Simulation</kbd> and wait a bit;
  - click <kbd>End Simulation</kbd> and immediately click <kbd>Start New Simulation</kbd> again - you will get the error.
## 
- `Simulation Error: error exit(1)`:
  ![finished](https://cloud.githubusercontent.com/assets/13209176/18365609/679ae682-75e1-11e6-825e-6f38ddecf9cb.png)
  **Steps to reproduce:**
  - for the same example go to the properties :pencil: of the `Spectral Flux for Finite Emittance Electron Beam, 20m` report and set `Number of Macro-Electrons` to 10;
  - click <kbd>Start New Simulation</kbd>;
  - wait until the end of the calculation (should finish fast) and observe the status.

**Comment by robnagler** [comment]
This has been fixed up a bit

**Comment by mrakitin** [comment]
Do you know commit numbers?

**Comment by mrakitin** [comment]
I still observe the both problems:
```
Simulation Error: ../../../../../../../pykern/pykern/pksubprocess.py:63:check_call_with_signals 16123: started: ['mpiexec', '--bind-to', 'none', '-n', '2', '/home/vagrant/.pyenv/versions/2.7.10/bin/python2.7', 'mpi_run.py']
```
```
Simulation Error: error exit(1)
Elapsed time: 0 00:00:13
```

**Comment by robnagler** [comment]
I think we should decide if we want to ignore this case. I think we do,
that is, if we see "error exit(1)", we should assume the simulation was
canceled. Do you have steps to reproduce this specific case?

**Comment by mrakitin** [comment]
**Steps to reproduce:**
 - for the same example go to the properties :pencil: of the `Spectral Flux for Finite Emittance Electron Beam, 20m` report and set `Number of Macro-Electrons` to 10;
 - click <kbd>Start New Simulation</kbd>;
 - wait until the end of the calculation (should finish fast) and observe the status.

**Comment by robnagler** [comment]
This shows "Simulation Completed". If I refresh, it still shows that. Canceling doesn't produce the error either. I tried both with Celery and Background jobs.

**Comment by mrakitin** [comment]
Did you fix anything? I don't see any associated commits...

**Comment by robnagler** [comment]
I have tried to make the processing and error handling more robust over
several commits. I didn't specifically address this issue.
