### ISSUE TITLE
opal: failed to parse field assignment: 2))

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#3502]
Loading a an OPAL input file produced by Sirepo that uses  `pow` in an expression like:
```
corrx=-sr_alpha_x/sqrt(1 + pow(sr_alpha_x, 2))
```
Gives an error during parsing:
```
failed to parse field assignment: 2))
```

**Comment by moellep** [comment]
This has been fixed by replacing "pow(sr_alpha_x, 2)" with "sr_alpha * sr_alpha" in the generated code. This has the advantage that it also works when exported to mad-x which doesn't have a pow() function, but instead uses ^.
