### ISSUE TITLE
Manage file updates atomically when possible

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#352]
For SRW, we can influence the design and control the way updates happen. File writes should be to temporary files then moved into place with `os.rename` (Windows has issues with atomic updates). Ideally, we would lock the directory, do the update, and then unlock it. This can be as simple as creating a directory `<report-name>.lock` then removing it when the write completes. The server would create the lock directory when it wants to read the files and release it. The advantage to lock directories is that they function across NFS atomically.

**Comment by mrakitin** [comment]
Does SRW need any update? I can take care of it.

**Comment by robnagler** [comment]
I believe it writes the same file over and over. If so, it should write a
temporary file and move it in place. For Windows, it will need to do
something slightly different, because Windows does not have an atomic
rename. This simple change would eliminate quite a few of the errors in the
logs. I think we should also have the code write the status in the json
file last. We can talk about this. Not urgent.

**Comment by mrakitin** [comment]
The part with JSON log is implemented in https://github.com/radiasoft/sirepo/issues/555.

**Comment by robnagler** [comment]
We do atomic updates in sirepo now.
