### ISSUE TITLE
Another isue with the radiasoft/sirepo:beta Docker image

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#3528]
We are trying to use the most recent version of the `radiasoft/sirepo:beta` Docker image in the sirepo-bluesky tests. It used to work ~12 days ago (see https://travis-ci.org/github/NSLS-II/sirepo-bluesky/jobs/766519225). However, the recent tests fail with the following [issue](https://travis-ci.org/github/mrakitin/sirepo-bluesky/jobs/767939488#L1347-L1360):
```py
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:318:receive ServerReq(api_runSimulation, testuser-00000001-watchpointReport3) error=no registered user with uid=testuser stack=Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py", line 314, in receive
    )(req)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py", line 690, in _receive_api_runSimulation
    o.make_lib_dir_symlink()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py", line 931, in make_lib_dir_symlink
    self.driver.make_lib_dir_symlink(self)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py", line 130, in make_lib_dir_symlink
    with sirepo.auth.set_user_outside_of_http_request(m.uid):
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/auth/__init__.py", line 429, in set_user_outside_of_http_request
    f'no registered user with uid={uid}'
AssertionError: no registered user with uid=testuser
```

We use this command to prepare the predefined simulation/user directory and to start sirepo:
https://github.com/NSLS-II/sirepo-bluesky/blob/fe4435cafbec3024153b34ba62b8bb44cdd9b508/.travis.yml#L58

Do I need to run an extra command (such as `sirepo admin ...` or something similar) to "register" this artificial "user"?
Or do I need to use a special environment variable to work it around?
Or is it a bug?

Maybe there is a better way to supply the predefined user name/dir.

Any feedback is appreciated. Thanks!

**Comment by e-carlin** [comment]
Hey @mrakitin sorry about this. I'm taking a look now and I'll get back to you today.

**Comment by robnagler** [comment]
@mrakitin all users have to be in auth_db. How is "testuser" created?

**Comment by mrakitin** [comment]
Hi @e-carlin, @robnagler!

@robnagler, I don't create the user. I am just copying the directory to the `$SIREPO_SRDB_ROOT` dir ([link](https://github.com/NSLS-II/sirepo-bluesky/blob/fe4435cafbec3024153b34ba62b8bb44cdd9b508/.travis.yml#L58)):

```bash
$ docker run -d -t --init --rm --name sirepo \
    -e SIREPO_AUTH_METHODS=bluesky:guest \
    -e SIREPO_AUTH_BLUESKY_SECRET=bluesky \
    -e SIREPO_SRDB_ROOT=/sirepo \ 
    -e SIREPO_COOKIE_IS_SECURE=false \
    -p 8000:8000
    -v $PWD/sirepo_bluesky/tests/SIREPO_SRDB_ROOT:/SIREPO_SRDB_ROOT:ro,z \
    radiasoft/sirepo:beta \
    bash -l -c "mkdir -v -p /sirepo/user/ && cp -Rv /SIREPO_SRDB_ROOT/* /sirepo/user/ && sirepo service http")
```

I mount the https://github.com/NSLS-II/sirepo-bluesky/tree/master/sirepo_bluesky/tests/SIREPO_SRDB_ROOT dir as `/SIREPO_SRDB_ROOT` and then in the contained copy the `testuser` dir to `/sirepo/user/` to have the predefined/expected user name and the simulation ids that we use in tests. What's the correct way to register a user? Thanks!

**Comment by robnagler** [comment]
https://github.com/NSLS-II/sirepo-bluesky/tree/master/sirepo_bluesky/tests/SIREPO_SRDB_ROOT needs to be updated to include auth.db, which is a file that would be created. The use of "testuser" is a hack. Rather, just start a sirepo server in a clean directory, and visit /srw. Then you will have a directory properly setup including directories for sirepo_job_supervisor.

**Comment by mrakitin** [comment]
Thanks for the suggestion, @robnagler! That indeed worked (https://github.com/jennmald/sirepo-bluesky/pull/3 will close this issue automatically once merged).

**Comment by robnagler** [comment]
Thanks for letting us know.

**Comment by mrakitin** [comment]
Thanks for the quick help!
