### ISSUE TITLE
Code coverage by https://codecov.io/

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#353]
It would be good to have code coverage (https://codecov.io/) metrics to estimate how much of Python (and maybe JS) code is covered by tests.

**Comment by robnagler** [comment]
Not a big fan of coverage. 
[Why Most Unit Testing is Waste](http://rbcs-us.com/documents/Why-Most-Unit-Testing-is-Waste.pdf)
discusses the problem of coverage.

**Comment by mrakitin** [comment]
Anyway we have the tests, and it would be useful to see which fraction of the code is covered by the tests to have some metrics (it's better than nothing). Many big projects use it, e.g.,
- https://github.com/NSLS-II/ophyd
- https://github.com/NSLS-II/databroker
- https://github.com/NSLS-II/bluesky
- ...

**Comment by robnagler** [comment]
My issue here is that "it's better than nothing" is actually not true.
Every tool you add has to add significant value, or it becomes a net
negative.

Given our current state of testing, we know we have not enough coverage (by
far). It will be months if not years before we have enough tests to warrant
a tool to see if we are adding features that need coverage.

Coplien's argument goes further in that he says that 100% coverage is
impossible. Even trying for a number is a waste of time. It's important to
understand his points before trying to adopt new tools.

**Comment by mrakitin** [comment]
OK, let's postpone it at the moment.
