### ISSUE TITLE
simulation => sim or s8n

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#354]
The word "simulation" appears everywhere in the code and is too long. I propose to replace it with sim or s8n (like i18n, k8s, etc.).

**Comment by moellep** [comment]
I prefer sim to s8n. So simulationId would become simId?

Paul

**Comment by robnagler** [comment]
Agreed. I think we would have simId, simType, simSerial, etc. I am also
thinking we want to rename "simulation" to "simMeta" instead of "sim" and
move "models" up a level so that the datastruct would look like:

{
    version: 1,
    simMeta: {
       simId: xx,
       simType: srw,
       simSerial: 999,
       simFolder: '/SR Calculator',
       simDocUrl: "",
       simName: "Bending Magnet Radiation",
       simIsExample: true,
    },
}

I think the rest should go in another model eg

     simParams: {
          appMode: calculator,
          sourceType: 'm',
          ...
     }

simMeta would be defined completely for each simulation. You have to have
all those elements, kind of like a directory entry. simParams would be
something that's application specific.

Given that Javascript is so flat, I think it is import to label entities
like in C with a prefix. I think this also helps Python, because duck
typing is really a global name space (any object could potentially be
checked for a specific attribute name).

What do you think?

**Comment by mrakitin** [comment]
I would vote for `sim` too. What does `s8m` stand for?

**Comment by robnagler** [comment]
s8m was modeled after i18n (internationalization), l10n (localization), k8s
(kubernetes), etc. It's the new rage: s8m => s followed 8 characters then m

**Comment by mrakitin** [comment]
Thanks Rob, it's clear now.

**Comment by robnagler** [comment]
@mkeilman This should be something to do as we go along with refactorings.

**Comment by robnagler** [comment]
Slowly migrating, no need for an issue.
