### ISSUE TITLE
Browser refresh causes jobs to be lost

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3544]
This is a bit complex, but @bnash ran into it tonight. If you start a sequential job that takes a long time and refresh the browser, the job can be lost. This depends on the parameter hash not being computed right so that the hash changes on the refresh. This was for the sourceIntensityReport for SRW.

**Comment by e-carlin** [comment]
@robnagler are you pretty confident it has to do with hash not being computed right? Were you seeing 400s with this bug? I just solved a similar sounding bug related to a malformed reply from the supervisor for running/pending jobs (https://github.com/radiasoft/sirepo/pull/3619/commits/2c79025cd565a024c6e3fdb967f0477b81315aa3)

**Comment by e-carlin** [comment]
Thanks for the details. https://github.com/radiasoft/sirepo/commit/2c79025cd565a024c6e3fdb967f0477b81315aa3 fixes it.
