### ISSUE TITLE
SRW - parameters change while running persistent calculations

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#355]
Request from @ochubar:
If a user has a long-running/persistent calculation (e.g., animated Flux report), and some of the parameters were changed, need to ask the user if to stop all running calculations and save the updated parameters, or discard the parameters and continue running the jobs.

**Comment by mrakitin** [comment]
Maybe we will need to split the parameters to two groups:
- unique parameters causing recalculation of a particular related report;
- common parameters causing recalculation of all reports.

It may be useful for #250.

**Comment by robnagler** [comment]
Currently this is how it works: Parameters changed that affect a report
will cause the report to be regenerated. There is a bug that the reports
aren't cleared from the cache in the "run simulation" type of reports.

I'm working on that related to the larger issue of out of sync clients
(#341, #342, #343)

**Comment by mrakitin** [comment]
Thanks for clarification Rob. I think along with the fix for the aforementioned issues the pop up window appearing in a browser and informing user about running jobs wouldn't hurt (and this ticket is about it).

**Comment by robnagler** [comment]
Good idea.
