### ISSUE TITLE
conslidate locking

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3558]
It looks like deadlock can occur during email authorization for new users because both the auth_db.thread_lock and util.SIMULATION_DB_LOCK are locked:

api_authEmailAuthorized() grabs auth_db.thread_lock and then calls auth.login() which calls simulation_db.user_create() which grabs the simulation_db lock to save the example files.

I found one case where the reverse can happen - the simulation_db lock is acquired followed by the auth_db lock. It is a contrived example, but something similar may happen on production:

User selects save-simulation, but the user dir is missing (deleted from under the user).
In this case the simulation_db lock is grabbed during simulation_db.validate_serial() which calls simulation_db.user_path() which finds the directory is missing so auth.user_dir_not_found() is called which grabs the auth lock.

A short term work-around could be to use a single lock for both auth and simulation_db.

**Comment by e-carlin** [comment]
Thanks for figuring this out @moellep 

@robnagler what are your thoughts? Should I implement using a single lock?

**Comment by robnagler** [comment]
Yes, single lock. It could be part of sirepo.util or something, and replace all thread locks with it.
