### ISSUE TITLE
Solver failed error with Radia example

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/sirepo#3562]
When I run [this](https://www.sirepo.com/radia#/visualization/wFU5zHyH) Dipole Example simulation I get the following error:

> Application Error: Error: Solver failed: [Errno 2] No such file or directory: '/srv/sirepo/db/user/EZ2f6Vl2/radia/wFU5zHyH/geometry/geometry.dat'. A report was sent to the server.

The only setting I've changed is the color map.

**Comment by e-carlin** [comment]
Orthogonal but we probably shouldn't expose the full path like this in errors. At the very least the UID should be somewhat private.

**Comment by robnagler** [comment]
We definitely need to do a better job of parsing errors for stuff like this....

**Comment by mkeilman** [comment]
When I try to open the link and reach the "Someone has shared a Sirepo simulation with you" page, then when I click "Open Simulation" I get a server error (the sim does not open).  I can't otherwise reproduce the issue.  Could you export to zip so I can examine it locally?

**Comment by sdwebb** [comment]
Unfortunately when I try to download the zip I also get a Server Error.

**Comment by mkeilman** [comment]
Fixed by #3574
