### ISSUE TITLE
all shadow sims failing with missing libgfortran.so.4

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3606]
All shadow sims are currently failing on alpha, beta, prod with the error:
```
import Shadow.ShadowLib as ShadowLib
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory
```

**Comment by robnagler** [comment]
It seems that devel-gfortran branch is not merged with master and pip install shadow3 is installing an older version. Therefore libgfortran4 is needed. Adding back into beamsim.
