### ISSUE TITLE
MCOOL:  improve Jupyter error message for no resources available

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#3622]
When a Sirepo/Jupyter user cannot obtain resources, they apparently see the following error message:

![jupyter_hub_no_resources_error_screenshot](https://user-images.githubusercontent.com/3825435/120003903-675a4900-bf93-11eb-8d42-7a58f39e5e2b.jpg)

When users see this, they are confused and think the system has failed.

We need a clear message that indicates the problem.
I would also like the message to refer users to the following link, with a statement that Sirepo Premium users will not encounter this problem.
https://www.sirepo.com/en/plans.html

**Comment by bruhwiler** [comment]
There is a "guaranteed access to cores" for Sirepo Premium users, as noted on the Plans page.
There can be a wait, of course, but it should not be a long wait and it definitely should not be of indefinite duration.

I think the most reasonable solution is to remove access from the Sirepo Basic user who has been active for the longest period of time.

When access is removed, there should be a clear message indicating why access is being removed, again with a link to the Plans page and a note that this does not happen to Sirepo Premium users.

For the Premium user who is waiting, there should be a message that resources are being made available for them and they will be available soon.

**Comment by robnagler** [comment]
The messages have been improved.
