### ISSUE TITLE
add genesis to gui

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3651]
Lots of sub-issues which we'll have to resolve. time independent simulation. time dependent will happen later. @sdwebb will provide jupyter notebook of reports. kickoff some time in july

**Comment by sdwebb** [comment]
[genesis_sirepo.tar.gz](https://github.com/radiasoft/sirepo/files/6903209/genesis_sirepo.tar.gz)
This is a tar file with an input file that can be run through Jupyter with `> genesis template.in` that will produce all the relevant output files. The Jupyter notebook has information for how to read in the key outputs. We'll need to discuss more about how exactly this will look, but I think it's a start.
