### ISSUE TITLE
Moderate JupyterHub user creations

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3654]
Create user now gives the jupyterhub_login role, but this needs to be moderated to avoid issues with cryptominers. 

- User is prompted with a box for why they want to use jupyter if they don't already have the role
- An email is sent from sirepo with IP, user-agent, email, display_name, etc. (simply key: value form "display_name: Jane Doe") with a link to approve
- The link to approve goes to the approvals list, and each user in the list can be approved or rejected
- Once approved or rejected, an email goes out to the user with the decision
- create pkcli stays the same: if we create a jupyterhub user they get the role automatically

related:
- https://github.com/radiasoft/sirepo/issues/960

**Comment by robnagler** [comment]
@rorour I would like to see a third state: approve/deny/clarify. clarify sends an email to the user from  the support address asking for clarification. Here's the email we send today:

```txt
You recently tried to login to Sirepo Jupyter. We need some more information in order to process your login request. 

Would you please let us know how you heard about Sirepo Jupyter? 

How do you intend to use Sirepo Jupyter?

We need this information to prevent abuse of our servers.

Thank you for your understanding.

Sincerely, 
```

We should have a long_name for the code being used and substitute that in a jinja template for the email.  We can substitute the display_name in the first line, e.g. `Dear {{ display_name }}`.

**Comment by rorour** [comment]
How should clarify be represented in UserRoleInvite? Should it be a new status that replaces pending for these users? 
How should the approval flow work? The user responds directly to the email and the admin manually navigates to the request list to approve/deny?

**Comment by robnagler** [comment]
Good questions. 

> How should clarify be represented in UserRoleInvite? 
> Should it be a new status that replaces pending for these users?

Yes, it should be like pending in the sense that it is not yet denied, but it is no longer waiting for someone to move it to denied. This way we track that an action has been taken. We should log this state transition in the server logs (pkdlog) so that we can mine it later if need be (server log acts as an audit log in this case). 

Once moved to clarify it either goes to approve or deny. From the user's perspective they see three choices: approve, deny, and clarify. Once in the clarify state, there will only be approve and deny for that user.

> How should the approval flow work? The user responds directly to the email and the admin manually navigates to the request list to approve/deny?

Yes, it should be manual for now. We don't have that many pending requests at any time so it should be easy to find the email in the list of outstanding requests.
