### ISSUE TITLE
radia: parallel solve does not work in distributed environment

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#3656]
Solves complete correctly but the attempt to run in a distributed manner fails silently.  Probably due to compute/analysis model confusion

**Comment by e-carlin** [comment]
@mkeilman lmk if you want to work on this together.

**Comment by mkeilman** [comment]
> @mkeilman lmk if you want to work on this together.

yes, but I need to get my environment back in shape first...

**Comment by mkeilman** [comment]
Fixed via PR #3661
