### ISSUE TITLE
SRW - Trajectory report disagreement for ESM beamline

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#366]
Request from @ochubar:

> Trajectory report for ESM beamline disagrees with the report from SRW calculations performed in console, and when the plot is produced by IgorPro.

Need to have steps to reproduce the issue and solve it.

**Comment by mrakitin** [comment]
Need to look at it closer since a similar issue is with simulations for the SMI beamline. Probably it's due to the fact that change of some of the undulator/beam parameters does not trigger the trajectory report to recalculate.

@moellep, I remember you changed something related to the cached values. Do you have any recommendations for the trajectory report? Thanks!

**Comment by moellep** [comment]
It looks like the trajectory report should recalculate on any model
changes, similar to the source intensity report. If you find a model change
which doesn't cause it, let me know a way to reproduce it.

def models_related_to_report(data):
    ...
    res = [
        'electronBeam', 'electronBeamPosition', 'gaussianBeam',
'multipole', 'simulation',
        'tabulatedUndulator', 'undulator',
    ]
    ...

**Comment by mrakitin** [comment]
The problem cannot be reproduced with the current build on beta. Closing.
