### ISSUE TITLE
elegant: parallel_optimization_setup should include optimize_setup fields

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#3665]
From the elegant manual:
"In addition to the optimization parameters used in the optimization setup command, several new parameters are added for parallel optimization. "

Right now when a command file with parallel_optimization_setup is loaded any fields from optimization_setup appear to be ignored. 
For an example from elegant's example library see: /matching/matchTwoEnergies/transverse1.ele

**Comment by moellep** [comment]
fixed with #3703
