### ISSUE TITLE
distributed jobs run on single MPI rank under slurm

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#3676]
This happens in ```mpy.restrict_op_to_first_rank()```  and its progenitor code in SRW ```parameters.py.jinja.setup_magnetic_measurement_files()```.  This can be seen with some logging:

```
...
    try:
        import mpi4py.MPI
        pkdp('MPI WORLD SIZE {}', mpi4py.MPI.COMM_WORLD.Get_size())
        if mpi4py.MPI.COMM_WORLD.Get_size() > 1:
            c = mpi4py.MPI.COMM_WORLD
            r = c.Get_rank()
    except Exception:
        pass
    pkdp('MPI RANK {} VS SBATCH RANK {}', r, os.environ['SLURM_PROCID'])
...
```

The "sbatch rank" goes from 0 to <num tasks> - 1, but the "mpi rank" is always 0, because ```COMM_WORLD.Get_size()``` returns 1.  The env variable ```$SIREPO_MPI_CORES``` looks correct. This does not happen when running under SMP - the mpi rank varies as expected.   I don't know what happens on NERSC.

**Comment by robnagler** [comment]
@e-carlin would you look into this?
