### ISSUE TITLE
stateless compute function name too long

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3701]
In template_common.py there is a check that the stateless compute name is under 30 characters:

https://github.com/radiasoft/sirepo/blob/master/sirepo/template/template_common.py#L576

SRW has a call "compute_delta_atten_characteristics" which violates this, which can be reproduced by selecting a material for the Sample beamline element.

Is there a reason the method length is checked?

**Comment by robnagler** [comment]
@e-carlin correct me if I'm wrong, but I think we limit the names, because they are used as part of job ids, which are part of file names and other places, which might cause issues.

**Comment by e-carlin** [comment]
stateless_compute blindly trust this value so I think it was a security measure to make sure it was something reasonable 

https://github.com/radiasoft/sirepo/pull/3565#discussion_r630462882
