### ISSUE TITLE
SRW - represent Gaussian beam via RMS divergence angle

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#371]
Request from SLAC:
> Need to add the representation of the Gaussian beam by `FWHM divergence angle (μrad)` along with `RMS waist (μm)` and allow dynamic conversion between them.

@ochubar's suggestion:
> We can implement `RMS divergence angle (μrad)`, and then, if needed, will implement `FWHM divergence angle (μrad)`.

**Comment by mrakitin** [comment]
We had a discussion with Lin and decided to implement it ASAP.

**Comment by mrakitin** [comment]
We had a discussion with Lin and decided to implement it ASAP.

**Comment by mrakitin** [comment]
`Gaussian Beam` needs to be renamed to `Fully Coherent Gaussian Beam`.

**Comment by ochubar** [comment]
Can be just “Coherent Gaussian Beam”, I think.
O.Chubar

**Comment by mrakitin** [comment]
Sure, I'll change it.

**Comment by mrakitin** [comment]
Implemented in b7a5626.
