### ISSUE TITLE
Parameters related to NERSC runs

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3713]
It would be good to document publicly (say in a wiki) the parameters we are using for cori. @ochubar would like to know how many concurrent simulations we allow on sirepo.com. I think he's running into problems with cori's execution limits (numbers of concurrent jobs). If we are limiting anything, he should know that.

**Comment by e-carlin** [comment]
https://github.com/radiasoft/sirepo/wiki/Running-at-NERSC here are the parameters. Of the options we provide we don't limit much when it comes to NERSC. If there is something specific lmk and I will add. 

@ochubar you should be able to run 5 concurrent simulations. Beyond that you will have to wait for a simulation to finish before another starts.
