### ISSUE TITLE
Cross-section at a given location

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#372]
Request from SLAC:
> Cursor should be more accurate.
![cursor](https://cloud.githubusercontent.com/assets/13209176/18522526/64172ec0-7a7e-11e6-9821-f28f00ac662e.png)

On the team meeting we concluded that the cross-section (blue cross) does not mach the grid for low resolution plots. However it is not clear if Lin means this problem or it's related to the focus point and the corresponding [X, Y] values.

**Comment by mrakitin** [comment]
@bruhwile, could you please clarify what Lin means under **"Cursor should be more accurate"**?

**Comment by moellep** [comment]
It fixes one issue where the plot could appear misaligned with the line-outs on low resolution plots. The issue with unbalanced low resolution plots is still open. Below is an example.

![screen shot 2016-09-15 at 1 15 22 pm](https://cloud.githubusercontent.com/assets/6516910/18563988/e8102f7e-7b46-11e6-8cd3-ee75dcec0697.png)

**Comment by mrakitin** [comment]
Thanks Paul.

**Comment by moellep** [comment]
The plot will now automatically zoom in and center if the initial plot is within 10% of a 0.0 midpoint. Below is an example, before/after.

![screen shot 2016-09-16 at 4 57 47 pm](https://cloud.githubusercontent.com/assets/6516910/18603465/018a2b60-7c2f-11e6-82b0-e30e3244b475.png)

![screen shot 2016-09-16 at 4 57 39 pm](https://cloud.githubusercontent.com/assets/6516910/18603471/082a29e8-7c2f-11e6-80f3-0aa215fc3eb3.png)

**Comment by mrakitin** [comment]
@moellep, is it fixed? Thanks.

**Comment by moellep** [comment]
Yes, I think it is fixed, unless I didn't understand the original ticket.

**Comment by mrakitin** [comment]
Thank you Paul. Closing.
