### ISSUE TITLE
SRW - allow uploading of .txt data files with height profile

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#373]
Request from SLAC:
> Error file type (.dat).  .txt is not recognized. Should be more tolerant in file types

**Comment by robnagler** [comment]
This is not an error message in Sirepo. Is it failing in the server or in
the browser?

**Comment by mrakitin** [comment]
On the server. It checks for .dat file extension:
https://github.com/radiasoft/sirepo/blob/master/sirepo/server.py#L220

**Comment by mrakitin** [comment]
It works fine for me. Thanks for implementing it, Paul!
