### ISSUE TITLE
Search path for resources and templates

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3732]
This will likely have to move to pykern, because pkresource needs to use it. We want to be able to configure a search path for loading modules, resources, and static files. This will help private cloud customers have custom home pages, for example.

**Comment by e-carlin** [comment]
Are resources any different than static files? They both live under package_data and will be found by pkresource correct?

Will the modules be installed (available in sys.path)?

**Comment by robnagler** [comment]
Let's assume the modules installed will be available in sys.path. They will be named something different at the root level, and the package hierarchy will parallel to `sirepo` that is, if the root package is xyzzy, templates will live in xyzzy.template.*.

static files are different because sirepo assumes RESOURCE_FOLDER is static. Therefore, that code needs changing so that it is a dynamic lookup at the time along the same path at pkresource uses.
