### ISSUE TITLE
Remove merge GitHub into Sirepo Jupyter

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3734]
Could leave the code and make it configurable.

**Comment by robnagler** [comment]
@e-carlin please do this when you are working on auth next.

**Comment by e-carlin** [comment]
Mind if we delete the code? It makes handling a variety of cases easier (ex different authorized callback urls for each different sim type).

**Comment by robnagler** [comment]
I am a little concerned about this, because I think we would like to switch BNL to email-based auth. I think we can do this now that we have SIREPO_SMTP_SEND_DIRECTLY. How much more work is it?

**Comment by e-carlin** [comment]
Couple places it adds confusion:
1. Sharing config. We made the assumption that each code that does oauth supplies its own oauth config (ex sirepo.sim_oauth.flash.cfg has redirect url, secret, etc). Or each auth method that does oauth (ex github) supplies its own config. jupyterhublogin is a sim type but it is going to be using the config from an auth method (github). This will add some confusion but can probably be managed by doing something like denormalizing the config or having jupyter import github and get it's config.
2. I don't know of a good way to say "we are doing oauth via github for sirepo auth" vs "we are doing github oauth for jupyter migration". As the code currently stands we can't have github auth and jupyter enabled. When the callback from github comes to us we [emit `github_authorized`](https://github.com/radiasoft/sirepo/blob/32f811d0eaa088eda1c2b07cb4fbc909af223fc7/sirepo/auth/github.py#L59) if jupyterhublogin is a sim_type then [we raise a redirect to /jupyter](https://github.com/radiasoft/sirepo/blob/32f811d0eaa088eda1c2b07cb4fbc909af223fc7/sirepo/sim_api/jupyterhublogin.py#L195). The redirect means we don't [finish the github auth](https://github.com/radiasoft/sirepo/blob/32f811d0eaa088eda1c2b07cb4fbc909af223fc7/sirepo/auth/github.py#L60). I think we might be able to use whether or not the user is logged in as a sentinel (if they are not logged in then we are doing github auth for sirepo). But, I'd need to test to confirm.


So, a doable amount of work but some confusion.

**Comment by robnagler** [comment]
I think auth.github should be split apart into a generic sirepo.oauth module (not an auth method) and the auth method github that uses sirepo.oauth. The configuration for sirepo.auth.github would stay the same, that is, sirepo.oauth would not have configuration. The api for sirepo.oauth will stay the same, too.

You will be creating a new module, e.g. sirepo.auth_moderate.oauth, that will use sirepo.oauth. It will add APIs for authentication in this way, because this will be authorizing a particular sim_type. There might be different oauth servers for different sym_types (highly likely).

We will have different id/key pairs for github: sirepo auth and flash auth.

You will also create sirepo.auth_moderate.email, too, which will handle the details of email moderation as distinct from github moderation. This is completely different from sirepo.auth.email, just like it is different for sirepo.auth.github, which, for example, tries to get the gravatar and display name. This is not important for moderation.

**Comment by e-carlin** [comment]
We left the code and made it work with the oauth changes in #4224.

 I don't think any new configuration has to be added. You can set [`rs_jupyter_migrate`](https://github.com/radiasoft/sirepo/blob/32f811d0eaa088eda1c2b07cb4fbc909af223fc7/sirepo/sim_api/jupyterhublogin.py#L152) to false and then remove configuration for github in auth methods and [`making it not visible`](https://github.com/radiasoft/sirepo/blob/32f811d0eaa088eda1c2b07cb4fbc909af223fc7/sirepo/auth/github.py#L161)

**Comment by robnagler** [comment]
Fix https://github.com/radiasoft/sirepo/pull/6921
