### ISSUE TITLE
create initial sirepo app

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3738]
Below is a mockup of the nuline app:

![nuline-sirepo-mockup](https://user-images.githubusercontent.com/6516910/128081670-6098550b-6203-4678-87ed-47e13c420986.png)

The "Image at Sample" panel is beamline output only. The Beamline Settings panel allows updating a value in the beamline and collecting new data which is then displayed in the Image at Sample panel. Eventually, updating a beamline value would update the actual beamline via EPICS or similar, but for now it will be stubbed out with an ML model. The Beamline Automation panel drives beamline settings in a variety of ways, described below.

A sim could be created by supplying a datafile which contains the list of all fields. Different beamline configurations would have a different field list, so the list of available fields needs to be dynamic for each simulation instance.  A useful datafile processor can be found here: https://github.com/abdoudiaw/nuline

Example beamline field list datafile. More examples can be found in the prop21_nuline repo.
```
# scan = 6
...
#   Pt.         m1     mtrans       coll     2theta   smpl_stk   pgfilter bottom_rot   camtrans  colltrans         s1 slit_pre_bt slit_pre_lf slit_pre_rt slit_pre_tp        stl        stu    z_stage        vti     sample       temp     temp_2       time    monitor   detector     anode1     anode2     anode3     anode4     anode5     anode6     anode7     anode8     anode9    anode10    anode11    anode12    anode13    anode14    anode15    anode16    anode17    anode18    anode19    anode20    anode21    anode22    anode23    anode24    anode25    anode26    anode27    anode28    anode29    anode30    anode31    anode32    anode33    anode34    anode35    anode36    anode37    anode38    anode39    anode40    anode41    anode42    anode43    anode44
      1     9.4500     7.0000     0.0000    24.0000   -59.9099    -0.0003    -0.0029   150.0000     0.0012   -19.9999    20.0000     7.0000     7.0000    30.0000     0.0000    -0.5000    14.9933    59.0361    73.1588     2.0000     2.000      1.000    263.000     59.000      0.000      3.000      1.000      2.000      0.000      3.000      0.000      2.000      1.000      2.000      1.000      1.000      1.000      2.000      4.000      1.000      2.000      1.000      3.000      2.000      3.000      0.000      0.000      2.000      2.000      1.000      0.000      4.000      3.000      1.000      2.000      0.000      0.000      0.000      1.000      1.000      1.000      2.000      1.000      1.000      0.000      1.000      1.000      0.000
...
```

The stats on the Image at Sample panel would come from the ML model stand-in for the real beamline (fields shown in mockup can be ignored). The beam plot can be stubbed out initially.

The Beamline Settings panel would allow selecting individual fields from the input file list. Selecting the Update Settings button would recompute the beam stats shown in the the Image at Sample panel.

The Beamline Automation panel has three functions
1) Run an activate ML model to recommend/update beam settings. 
2) Online Optimization - select an optimization method (ex. Nelder Mead) and apply weights to target values.
3) Scanning - select fields and ranges and run the beamline multiple times, creating a dataset which can be used to train an ML model.

**Comment by robnagler** [comment]
Done
