### ISSUE TITLE
enable show_rsopt_ml feature on production

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3746]
Update the production config so srw.show_rsopt_ml feature is enabled.

**Comment by moellep** [comment]
This config change is needed for blicon

**Comment by robnagler** [comment]
`sirepo.feature_config.srw.show_rsopt_ml = True`?

**Comment by moellep** [comment]
Yes, similar to how the "show_open_shadow" feature is set on production.

**Comment by robnagler** [comment]
show_open_shadow is set for everything (default). I did the same for show_rsopt_ml. Then ran `rsc.sh prod sirepo`.
