### ISSUE TITLE
SRW - Terminated unexpectedly error

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#375]
I worked with the CHX beamline example on alpha - https://alpha.sirepo.com/srw#/beamline/JNoBrDLt. When I add a watch point to somewhere in the beamline and save the beamline, the simulations run fine, but then when I decide to remove this watchpoint and save the beamline, there is an error:
![terminated](https://cloud.githubusercontent.com/assets/13209176/18530017/7af1f3a4-7a9d-11e6-82ea-59e3a0112e9c.png)

Server log may contain something like:
```
10.0.2.2 - - [14/Sep/2016 21:01:36] "POST /run-cancel HTTP/1.1" 200 -
../sirepo/server.py:657:_simulation_error error in read_result: /home/vagrant/src/radiasoft/sirepo/run/user/S0t4n8jH/srw/xm1DEHWf/watchpointReport11: error: ERROR: Terminated unexpectedly
```

**Comment by robnagler** [comment]
is this fixed?

**Comment by mrakitin** [comment]
Need to test it, I don't recall I had this recently.

**Comment by moellep** [comment]
It is still a problem. You can reproduce it by opening the NSLS-II CHX
beamline simulation, then going to the beamline page and let it finish
loading. Edit the "Intensity At Sample" report and change a setting, for
example, Polarization to Horizontal. Then, while the report is generating.
Change the sample watchpoint distance slightly and select save changes.
The Initial Intensity Report will run, but the Sample Watchpoint report
will fail with this entry in the server logs:

../sirepo/server.py:680:_simulation_error error in read_result:
/home/vagrant/src/radiasoft/sirepo/run/user/37UqUtm7/srw/2nJfLYhq/watchpointReport11:
error: ../sirepo/server.py:937:_start_job
37UqUtm7-2nJfLYhq-watchpointReport11: child will exec: ['sirepo', 'srw',
'run',
'/home/vagrant/src/radiasoft/sirepo/run/user/37UqUtm7/srw/2nJfLYhq/watchpointReport11']

**Comment by robnagler** [comment]
I wasn't able to reproduce. What does your log say around the error. Mine
says:

10.10.10.1 - - [21/Sep/2016 16:52:26] "POST /run-status HTTP/1.1" 200 -
../sirepo/server.py:908:sigchld_handler 7283: waitpid: status=0
../sirepo/server.py:913:sigchld_handler
hnua0L0T-HT2W0brU-watchpointReport11: deleted
10.10.10.1 - - [21/Sep/2016 16:52:27] "POST /run-status HTTP/1.1" 200 -
10.10.10.1 - - [21/Sep/2016 16:52:29] "POST /save-simulation HTTP/1.1" 200 -
../sirepo/server.py:933:_start_job hnua0L0T-HT2W0brU-watchpointReport11:
started: pid=7324 cmd=['sirepo', 'srw', 'run',
'/home/vagrant/src/radiasoft/sirepo/run/user/hnua0L0T/srw/HT2W0brU\
/watchpointReport11']
10.10.10.1 - - [21/Sep/2016 16:52:29] "POST /run-simulation HTTP/1.1" 200 -
10.10.10.1 - - [21/Sep/2016 16:52:30] "POST /run-status HTTP/1.1" 200 -

**Comment by robnagler** [comment]
Never mind. I got it.

**Comment by robnagler** [comment]
FTR, here's the log:

10.10.10.1 - - [21/Sep/2016 16:54:29] "POST /run-status HTTP/1.1" 200 -
10.10.10.1 - - [21/Sep/2016 16:54:30] "POST /run-status HTTP/1.1" 200 -
10.10.10.1 - - [21/Sep/2016 16:54:31] "POST /save-simulation HTTP/1.1" 200 -
../sirepo/server.py:882:kill hnua0L0T-HT2W0brU-watchpointReport11:
stopping: pid=7370
../sirepo/server.py:908:sigchld_handler 7370: waitpid: status=15
../sirepo/server.py:913:sigchld_handler
hnua0L0T-HT2W0brU-watchpointReport11: deleted
../sirepo/server.py:933:_start_job hnua0L0T-HT2W0brU-watchpointReport11:
started: pid=7389 cmd=['sirepo', 'srw', 'run',
'/home/vagrant/src/radiasoft/sirepo/run/user/hnua0L0T/srw/HT2W0brU\
/watchpointReport11']
10.10.10.1 - - [21/Sep/2016 16:54:31] "POST /run-simulation HTTP/1.1" 200 -
../sirepo/server.py:900:kill hnua0L0T-HT2W0brU-watchpointReport11: deleted
10.10.10.1 - - [21/Sep/2016 16:54:32] "POST /run-cancel HTTP/1.1" 200 -
../sirepo/server.py:696:_simulation_error error in read_result:
/home/vagrant/src/radiasoft/sirepo/run/user/hnua0L0T/srw/HT2W0brU/watchpointReport11:
error: ../sirepo/server.py:953:_star\
t_job hnua0L0T-HT2W0brU-watchpointReport11: child will exec: ['sirepo',
'srw', 'run',
'/home/vagrant/src/radiasoft/sirepo/run/user/hnua0L0T/srw/HT2W0brU/watchpointReport11']
10.10.10.1 - - [21/Sep/2016 16:54:32] "POST /run-status HTTP/1.1" 200 -
../sirepo/server.py:908:sigchld_handler 7389: waitpid: status=0
