### ISSUE TITLE
Support procedure

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#376]
Document a support procedure

**Comment by robnagler** [comment]
Please review [SupportProcedure](https://github.com/radiasoft/devops/wiki/SupportProcedure) in the radiasoft/devops wiki.

We may need to start with a ticket system. I would love it if we could get all customers to agree to use GitHub Issues so we don't have to track two systems.

**Comment by bruhwile** [comment]
The documented procedure looks good, Rob.

We can encourage customers to use Github, but many won't. Letting
individuals know how to follow issues might encourage them to create a
Github account.

I agree that we should not start using a separate tracking system, so I
agree with your suggestions:
  1) create issues for the customer
  2) label them 'Customer' so we don't forget about them

David

**Comment by mrakitin** [comment]
The procedure looks good for me too. I'm not sure why the milestones are not good? They look transparent and may contain as many issues for a customer as needed, and it's easy to set the due date. The milestones can be closed and even removed, the tickets won't be affected.

**Comment by mrakitin** [comment]
Project feature can be useful as well - https://github.com/radiasoft/sirepo/projects. There we can easily group the issues, but unfortunately without due date.

**Comment by robnagler** [comment]
I don't like milestones because they are cumbersome to create (you have to
give them a title, for example, when the issue already has a title). I
think we'll have a hard time managing them if we get more than a couple of
users.

The right solution is to have a trouble ticket system which manages contact
with the customer. There are plenty of these, but at the level we are
operating at, I think we can simply review all customer facing tickets
weekly to satisfy the deadline issue.

**Comment by mrakitin** [comment]
OK.

**Comment by robnagler** [comment]
I think this is being handled by @messamer
