### ISSUE TITLE
Release procedure

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#377]
Document release workflow

**Comment by robnagler** [comment]
Please review https://github.com/radiasoft/devops/wiki/ReleaseProcedure

**Comment by robnagler** [comment]
Let's make sure we follow this for releases going forward.

**Comment by bruhwile** [comment]
Thanks for writing these detailed procedures.

**Comment by robnagler** [comment]
Please see [ManualAlphaTest](wiki/ManualAlphaTest) for the checklist we follow to test the application on alpha.

**Comment by bruhwile** [comment]
Better link:
https://github.com/radiasoft/sirepo/wiki/ManualAlphaTest

**Comment by robnagler** [comment]
We have scripted procedures now.
