### ISSUE TITLE
mcool: New friction force models

### ISSUE THREAD

**Issue by sjcrs** [radiasoft/sirepo#3776]
On the Source tab, 'cooling and intrabeam scattering' window, 'force formula' sub-tab: Please add two new options to the Force Formula dropdown menu. "Pogorelov-Bruhwiler" and "Pogorelov-Bruhwiler warm electrons". They correspond to jspec.in friction_force text values of "POGORELOV" and "POGORELOV_WARM".

**Comment by sjcrs** [comment]
The full list of friction forces needs to include Derbenv-Skrinsky as well (DERBENEVSKRINSKY in the input text file).  This was in production at some point and now I don't see it.  This is an urgent change for the webinar on Wednesday.  Please contact me if I can help speed this along.

**Comment by moellep** [comment]
I'm looking at this now and #3775 and will have an alpha release later today.
