### ISSUE TITLE
Semi stable checkin

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#379]
I'm being a bit aggressive with my changes. I checked in the simulation synchronization code and the pkcollections.dict changes. 

In particular, pkcollections.dict uses an optimistic name collision strategy so that we can get maximum benefit. This means that at some point we may get a collision in the identifiers we choose for our schemas collide with existing attributes of Python's `dict` type. It's probably a bad idea in general to give names that are all lower case without underscores. camelCase names won't collide with dict and a middle underscore will prevent against collisions, too. If we do get a collision, it will be obvious, because we won't be able to read in the schema.

**Comment by robnagler** [comment]
Had to backout pkcollections.Dict, because elegant.py has some "values" and "items" attributes.

**Comment by moellep** [comment]
There still seems to be some problem - the copy.deepcopy() call in
simulation_db is failing with the error:

AssertionError: items: invalid key for Dict matches existing attribute

**Comment by moellep** [comment]
Never mind, when I pulled the latest pykern, the problem is gone.

**Comment by robnagler** [comment]
You need to pull out pykern

**Comment by robnagler** [comment]
Seems to be stable now. :)
