### ISSUE TITLE
SimDataBase.lib_file_exists() raises FileNotFoundError instead of returning False 

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#3799]
This is in turn causing ```server.api_uploadFile()``` to fail when trying to upload a new file

**Comment by e-carlin** [comment]
@mkeilman I'm not seeing this behavior. For example on the latest master trying:
- srw, nslsII, ESM beamline
- going to the beamline tab
- uploading a new mirror file
- lib_file_exists returns `False` (as expected)
- upload-file call succeeds

Can you give me some steps to see it?

**Comment by mkeilman** [comment]
Sorry, I figured it out.  The nuline template directory was missing the lib subdirectory and I got confused which directory it was complaining about.  I'll close this now
