### ISSUE TITLE
Controls app

### ISSUE THREAD

**Issue by j-edelen** [radiasoft/sirepo#3803]
The controls application is no longer being displayed on the landing page under "supported codes"

**Comment by robnagler** [comment]
This used to be "in the code", but now it's in WordPress. @LexiJess would you work with Vermilion to fix this?

**Comment by LexiJess** [comment]
Yep! :)

**Comment by LexiJess** [comment]
Email requesting update was sent to Vermilion on 9/2. Awaiting response. Will check with them again today.

**Comment by LexiJess** [comment]
Vermilion pushed to alpha and beta. Approved in beta by Rob. Pushed to production.
