### ISSUE TITLE
detect bot when throwing errors

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3827]
Use https://pypi.org/project/robot-detection/ to detect if user-agent is a bot, and then throw a real HTTP status instead of javascript redirect in sirepo.http_reply.

**Comment by mkeilman** [comment]
Is there a way to test this?  Do we have a local bot?

Also, ```http_request``` has ```is_spider()```  which  uses the user_agents package to test for bots.  Is this to replace that?

**Comment by robnagler** [comment]
I forgot about that. Good catch. I think when you make this change, all tests which use FlaskClient will get hit with this, that is, we can remove [the javascript redirect check in srunit](https://github.com/radiasoft/sirepo/blob/41ea0285d7906273628167dc6f905c15ac499461/sirepo/srunit.py#L624). OR, we can leave it in, and test for the case when we supply a valid non-bot user agent string.

Here's how you can pass the HTTP_USER_AGENT string: https://stackoverflow.com/a/15281179

We can then decide whether the default would be to fake a real browser (set HTTP_USER_AGENT to Chrome for all clients) or if we don't care, and test in the mode of being a bot ([default USER_AGENT is `werkzeug/<version>`](https://github.com/pallets/flask/blob/77237093da25438c88b0a74c374a397d4bf823eb/src/flask/testing.py#L116)).

We can chat about this if it isn't clear.

**Comment by robnagler** [comment]
I think this is fixed, correct?
