### ISSUE TITLE
save-simulation returning stale state

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#383]
New bug on dev, if you open the "Idealized Free Electron Laser Pulse" simulation in SRW, select "Discard Changes to Example", and then create a beamline with 1 watchpoint and select "Save Changes". The save-simulation is called, but the watchpoint disappears. Adding the watchpoint a second time and saving completes successfully.

**Comment by robnagler** [comment]
I'll work on these serial bugs now. I want to write tests so make take a
bit for time.

**Comment by robnagler** [comment]
Fix 467655ba9d9280eddf213b2ed8a735998580ccc4
