### ISSUE TITLE
SRW: adding too large mirror misalignments makes watchpoint disappear

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#3834]
I am trying to check if recent changes to the SRW source code have fixed the mirror misalignment problem where a cylindrical mirror causes misalignments in both directions rather than just one.

Here's a Gaussian beam source with a single mirror and a watchpoint for a beamline:
https://www.sirepo.com/srw#/beamline/Evxnccoo

If you put in 0.5 mm misalignments in both horizontal and vertical, it looks good and seems that the bug has been fixed, 
the mirror deflecting only in the horizontal.
However, if you misalign by 10 mm, then the watchpoint doesn't show up at all. Perhaps, this is due to the wavefront completely missing the mirror.

![Screen Shot 2021-09-21 at 9 46 18 AM](https://user-images.githubusercontent.com/1112276/134193029-343166a7-6a6c-4a59-bdc0-3612462636c7.png)

**Comment by moellep** [comment]
Fixed with cde4bf89
