### ISSUE TITLE
webcon: DeviceServer interface

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3844]
- The beamline optimizer should be able to operate on a mad-x
  simulation which it currently does, or against an actual control
  system, via the DeviceServer interface.
- Each element should have a (name, value) for the device value on the
  real system. This could reuse the (PV name, PV value) pair from the
  EPICS mapping, in issue #3842.
- For development, a dummy DeviceServer should be implemented which
  takes HTTP calls and returns XML (or JSON?) data.

**Comment by robnagler** [comment]
I think we will want a serverless and server-based mock interface for testing. The serverless interface would be created first to get the basic implementation going.
