### ISSUE TITLE
show error if output files will be too large

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3860]
In elegant, the particle files can get too big if there is a large run_control.npasses set on the simulation. elegant will append the particles to the file on each pass. For example, setting npasses=100000 on the Los Alamos PSR example.

In sirepo/zgoubi, we estimate the file sizes that ahead of time and show an error message if the output files will be too large: 
https://github.com/radiasoft/sirepo/blob/master/sirepo/pkcli/zgoubi.py#L123

Something like this should be added to elegant, if npasses and n_particles_per_bunch are large and there are particle watchpoints in the selected beamline.

**Comment by robnagler** [comment]
Will be fixed in #4156
