### ISSUE TITLE
invalidSerial for elegant reports

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#387]
If you visit the elegant Visualization page after reports have been run, an invalidSerial is returned and an alert "Another browser updated this simulation; refreshing local state" is shown.

For example, open the "bunchCompLSC - lattice", run the simulation on the Visualization page, then return to the Simulations page and open the simulation a second time and visit the Visualization page.

**Comment by robnagler** [comment]
This is the problem we discussed earlier. autoSave is getting called twice:

![console log](https://cloud.githubusercontent.com/assets/5495179/18652770/5533cf54-7e92-11e6-94d5-13cb0c40573f.png)

I'll add a queue.
