### ISSUE TITLE
math and functions

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3876]
https://github.com/radiasoft/sirepo/blob/aa5ca4ac7e09272e5a9c8851ebdc5d8ce284b939/sirepo/template/nuline.py#L172:

```py
    intensity = []
    max_intensity = 256 * 256 * 255 + 256 * 255 + 255
    for x in img_data:
        row = []
        for y in x:
            row.append((256 * 256 * int(y[0]) + 256 * int(y[1]) + int(y[2])) / max_intensity)
        intensity.append(row)
```

@e-carlin pointed to this code for other reasons, but it struck me as interesting. The first thing I saw was `256 * 256 * 255 + 256 * 255 + 255` is `2**24 - 1`. To me, this is much clearer, but I'm curious what others think.

The second thing I noticed was that there was a conversion going on which was identical a few lines lower. Some type of scaling is going on. 

I don't have time to think about this, but it seems like numpy or PIL should be able to help us more here.

**Comment by robnagler** [comment]
The code is scaling all values from 0 to 1 afaict. I agree that 2**24-1 is less clear in some ways. I see a lot of code like this, and I just skip it. This was something I could see, and it was a "smell" for me. We shouldn't have to use nested for loops to operate on images. There must be a better way.

**Comment by cchall** [comment]
I think you can use numpy broadcasting to get rid of the loop here
```
    intensity = []
    max_intensity = 256 * 256 * 255 + 256 * 255 + 255
    for x in img_data:
        row = []
        for y in x:
            row.append((256 * 256 * int(y[0]) + 256 * int(y[1]) + int(y[2])) / max_intensity)
        intensity.append(row)
```
to
```
intensity = numpy.sum(img_data * np.array([256 * 256, 256, 1, 0]), axis=2) / max_intensity
```
Which can be converted back to a list of lists if needed.

**Comment by robnagler** [comment]
Thanks @cchall! This is really helpful. I read about broadcasting, and it's what I was thinking about. 

I wanted to understand it a bit better. This is the refactoring I think that represents what I was thinking:

```py
m = numpy.iinfo(type(img_data[0][0][0])).max + 1
x = numpy.array([m * m, m, 1, 0])
i = numpy.sum(img_data * x, axis=2) / numpy.sum(x * (m - 1))
```

We talked about this in the software group meeting today, and I'm sure the other software people will not appreciate this as much as I do. :)

@mkeilman the type of img_data is `uint8` so you don't need all those `int` conversions. That's an implicit assumption. The reason I did the `iinfo` call above was to make the relationships explicit. There still is an assumption about it being an integer and fitting into the Python max int type.

There are other assumptions I would like to eliminate, but it would be too hard, I think. People just assume these things, and they are not going to make them explicit in the code, e.g. dimensionality.

**Comment by moellep** [comment]
In this case, the best way it to find the right library we are already importing, which produces exactly the same results:
```
from skimage.color import colorconv
intensity = colorconv.rgb2gray(colorconv.rgba2rgb(img_data))
```

**Comment by robnagler** [comment]
and still haven't solved the software testing problem....

**Comment by robnagler** [comment]
but the one pixel is very off:
```
mike  0.003005922019834639
rob  0.003005922019834639
evan  0.5647058823529412
paul  0.6219760784313726
```

**Comment by moellep** [comment]
Using colorconv.rgb2gray() would be only useful if the detector image was using color, which none probably use. For the nuline images, it is grayscale, and this code computes the same results as Mike's original algorithm:
```
return img_data[:,:,0] / 255.0
```
