### ISSUE TITLE
selecting serial execution mode still runs in parallel

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3886]
When running an SRW simulation with "Execution Mode" Serial, it is still running in parallel. On alpha, running this sim: 

https://alpha.sirepo.com/srw#/beamline/6rWDTEuO?tab=multi 

shows 8 mpi processes running and the srwl log shows "Calculation on 8 cores with averaging of 5 particles/iteration." which is the same message when running normally with 8 cores.

**Comment by e-carlin** [comment]
[This is the code](https://github.com/radiasoft/sirepo/blob/ec3a0ccc76d4be9819cd99ec1291fcee0712ac07/sirepo/sim_data/__init__.py#L251) we use to determine if we use `run` vs `run-background`. So anything with animation in the name will use run-background even if we set the jobRunMode to serial.  I think we may have other places in the code where we assume animation is parallel. Not sure off of the top of my head.

When deciding to send to a parallel or sequential agent we also use `sim_data.is_parallel` (not jobRunMode). 

jobRunMode should probably override inferring from the model name. Need to think more about how to implement and how this could impact sbatch run vs analysis.

**Comment by robnagler** [comment]
dup  #1874
