### ISSUE TITLE
SRW - need to click "Save Changes" button twice

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#389]
I use the most recent sirepo/pykern/SRW-light, and the behavior is strange. When I change any parameters (e.g., Photon Energy), I have to click on the <kbd>Save Changes</kbd> button twice. After the first click I observe the following error in the server log:
```js
../sirepo/server.py:192:app_error_logging 10.0.2.2: javascript error: {
    "cause": "",
    "message": "<no message>",
    "stackTrace": [
        "self.autoSave@http://nsls2expdev1:8000/static/js/sirepo.js?20160920.185620:157:9",
        "self.saveChanges@http://nsls2expdev1:8000/static/js/sirepo.js?20160920.185620:377:9",
        ".controller/$scope.saveChanges@http://nsls2expdev1:8000/static/js/sirepo-components.js?20160920.185620:210:21",
        "anonymous/fn@http://nsls2expdev1:8000/static/js/ext/angular-1.4.2.min.js?20160920.185620 line 212 > Function:2:221",
        "Kc[c]</<.compile/</</f@http://nsls2expdev1:8000/static/js/ext/angular-1.4.2.min.js?20160920.185620:252:74",
        "jf/this.$get</n.prototype.$eval@http://nsls2expdev1:8000/static/js/ext/angular-1.4.2.min.js?20160920.185620:134:489",
        "jf/this.$get</n.prototype.$apply@http://nsls2expdev1:8000/static/js/ext/angular-1.4.2.min.js?20160920.185620:135:212",
        "Kc[c]</<.compile/</<@http://nsls2expdev1:8000/static/js/ext/angular-1.4.2.min.js?20160920.185620:252:124",
        "Hf/c@http://nsls2expdev1:8000/static/js/ext/angular-1.4.2.min.js?20160920.185620:35:212"
    ],
    "type": "exception",
    "url": "http://nsls2expdev1:8000/srw#/source/wcYTRDP4"
}
```
The second click does not cause the reports to be recalculated.

It looks that the changed parameters are not passed to the server at all. When I export the JSON file, it contains old values. I observe the issue when I copy the old simulation or import previously saved JSON file.

**Comment by mrakitin** [comment]
The problem can be reproduced on this data set - [smi.zip](https://github.com/radiasoft/sirepo/files/483441/smi.zip).

**Comment by moellep** [comment]
I can reproduce it in firefox if I restart firefox, visit the simulations
page, open a "Ellipsoidal Undulator" example and change the photon energy
on the Intensity Report modal dialog.

The javascript error console shows this:

Error: 'log' called on an object that does not implement interface Console.
self.autoSave@
http://localhost:8000/static/js/sirepo.js?20160920.192044:157:9

This is similar to the other bug we saw where the srdbg() calls were
failing.

Paul

**Comment by moellep** [comment]
Seems related to this:

http://stackoverflow.com/questions/24339412/how-to-assign-builtin-methods-on-console-and-document-to-variables-in-javascript

**Comment by mrakitin** [comment]
Thanks a lot Paul! Your fix solves this problem.
