### ISSUE TITLE
add wm_nmm value to CMD panel

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3899]
Add the MPI groups value wm_nmm to the CMD panel. The value must be 2 or more.

**Comment by moellep** [comment]
The wm_nmm is defined here:

https://github.com/radiasoft/sirepo/blob/master/sirepo/package_data/template/srw/parameters.py.jinja#L244

and the user should be able to change the value. Current it defaults based on the mpi cores available:

https://github.com/radiasoft/sirepo/blob/master/sirepo/template/srw.py#L2067

I think a default of 2 would be OK in general. The field should be shown on the Main tab of the Coherent Modes panel editor. The value should have a minimum value of 2.

Also, change then name from mpiMasterCount to mpiGroupCount and the label text could be something derived from this: 

"number of independent groups of MPI processes"

**Comment by gurhar1133** [comment]
Milestone for this one @moellep  @robnagler
