### ISSUE TITLE
coherentModesAnimation writing too much too fast?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3900]
We had a pinger timeout on Jupyter last night, which I think was related to disk. Load average on the server was over 5 for 15 minutes. I saw a coherentModesAnimation running. Nothing else was going on afaict. I did see `xz` briefly pop up a couple of times, but that may have been unrelated. At least one nfsd was busy.

We can throttle writes via Docker, and that may be the only solution. We've seen large writes before lock up the server.

@moellep thoughts?

**Comment by moellep** [comment]
Or possibly the res_csd_*_mi.h5 files could be written somewhere outside of NFS in a really large tmp area?

**Comment by moellep** [comment]
It isn't necessary for sirepo, because the _md.h5 file is only created at the end of the run. If the simulation is canceled, no output is created.

**Comment by robnagler** [comment]
Do we ever need the intensity file?

**Comment by moellep** [comment]
The _mi files are used to create the _md.h5 file after all the macro particles have been sent through the simulation.

**Comment by robnagler** [comment]
Turns out the intensity file is always written at the end. Setting wm_ns to a large value breaks the progress bar, and this patch eliminates the intermediate saves:

```patch
diff --git a/env/work/srw_python/srwlib.py b/env/work/srw_python/srwlib.py
index 9e052df..0ab17fb 100644
--- a/env/work/srw_python/srwlib.py
+++ b/env/work/srw_python/srwlib.py
@@ -10267,6 +10267,8 @@ def srwl_wfr_emit_prop_multi_e(_e_beam, _mag, _mesh, _sr_meth, _sr_rel_prec, _n_
                         #srwl_uti_save_intens_ascii(resStokes2.to_deg_coh(), meshRes2, fpdc2, _n_stokes = 1, _arLabels = resLabelsToSaveDC, _arUnits = resUnitsToSaveDC, _mutual = doMutual, _cmplx = 0) #OC12072019 # Deg. of Coh. Cut vs Y
                         #srwl_uti_save_intens_ascii(resStokes2.to_deg_coh(), meshRes2, fpdc2, _n_stokes = 1, _arLabels = resLabelsToSaveDC, _arUnits = resUnitsToSaveDC, _mutual = 2, _cmplx = 0) #OC16072019 # Deg. of Coh. Cut vs Y
                         srwl_uti_save_intens(resStokes2.to_deg_coh(), meshRes2, fpdc2, _n_stokes = 1, _arLabels = resLabelsToSaveDC, _arUnits = resUnitsToSaveDC, _mutual = 2, _cmplx = 0, _form = _file_form) #OC17072021 # Deg. of Coh. Cut vs Y
+                elif _char == 61:
+                    pass
                 else:
                     #srwl_uti_save_intens_ascii(resStokes.arS, meshRes, file_path1, numComp, _arLabels = resLabelsToSave, _arUnits = resUnitsToSave, _mutual = doMutual, _cmplx = (1 if doMutual else 0)) #OC30052017
                     #srwl_uti_save_intens_ascii(resStokes.arS, meshRes, fp1, numComp, _arLabels = resLabelsToSave, _arUnits = resUnitsToSave, _mutual = doMutual, _cmplx = (1 if doMutual else 0)) #OC14082018
```

**Comment by moellep** [comment]
I'm glad the progress bar will still work - it is good to know when you have something running for many hours.
