### ISSUE TITLE
elegant app has an example that generates a warning

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#3914]
This is the Los Alamos Proton Storage Ring example.

This is the Warning message that I see,
![image](https://user-images.githubusercontent.com/3825435/139477145-d9bf1aa3-4b30-4380-a41a-d92f5a64f848.png)

It would be best if the examples do not create warnings like this.

**Comment by bruhwiler** [comment]
Other examples are also generating warnings.

**Comment by cchall** [comment]
The first warning on particle type is unavoidable as far as I know. It will always be produced by elegant if you use the `&change_particle` command. We would either have to specially filter it or choose an example that uses electrons.

For the `concat_order` I seem to have something strange happening. I think the default value was changed over a year ago:
https://github.com/radiasoft/sirepo/blob/304aa6863b29712a88aa1d8eef9d0f3833917250/sirepo/package_data/template/elegant/examples/psr.json#L177

When I first checked on Examples/Los Alamos Proton Storage Ring I also saw `concat_order=2`. I tried hitting discard changes, and it seemed like it remained `concat_order=2`. But it appears that when use discard changes Sirepo keeps taking me to a copy of Los Alamos Proton Storage Ring that I have in Demos/Los Alamos Proton Storage Ring.

**Comment by cchall** [comment]
I found an error from the Script Element Example that I'll open a separate issue for, no other examples produced warnings or errors for me.


> Other examples are also generating warnings.

Were there additional examples besides "Script Element Example" and "Los Alamos Proton Storage Ring" for you @bruhwiler ?

**Comment by bruhwiler** [comment]
Once I discarded changes to the Example simulations, I didn't see any other errors.

I guess the particle type warning should be left as is ... I didn't realize elegant always does this for non-electron simulations.

I'll close the issue.
