### ISSUE TITLE
Script Element Example sometimes exit with error

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#3915]
In Sirepo this example gives an error when run:
```
elegant Warnings:
Terminated by SIGABRT
```
When I ran it locally I often see at the end of the simulation that there is a memory error:
```
Dumping output beam data...done.
Dumping centroid data...done.
Post-tracking output completed.
Tracking step completed   ET:     00:00:00 CP:    0.00 BIO:0 DIO:0 PF:0 MEM:0


Saving lattice parameters to run_setup.parameters.sdds...done.
elegant(552,0x112bc5e00) malloc: *** error for object 0xc00007f8b1c60d13: pointer being freed was not allocated
elegant(552,0x112bc5e00) malloc: *** set a breakpoint in malloc_error_break to debug

Terminated by SIGABRT
```

This error doesn't always occur though and sometimes elegant exits successfully. It looks like this could just be elegant not handling the additional particles added by the script event though `no_new_particles=0` is set properly. 

For example purposes it might be better to change to a script that modifies the input distribution in some way. A trivial example might be:
`os.system('sddsprocess {} {} -redefine=col,x,\"x 5e-3 -\"'.format(infile1, outfile))`
in place of https://github.com/radiasoft/sirepo/blob/304aa6863b29712a88aa1d8eef9d0f3833917250/sirepo/package_data/template/elegant/lib/SCRIPT-commandFile.combine.py#L8

I tried using this a few dozen times and did not see any error.

**Comment by moellep** [comment]
I've verified the simulation still fails occasionally with a ```munmap_chunk(): invalid pointer``` error. I'll update the script to modify the existing particles rather than add new ones.
