### ISSUE TITLE
Shadow/SRW: SXN beamline not working in Shadow

### ISSUE THREAD

**Issue by bnash** [radiasoft/sirepo#3920]
Our collaborator at BNL wants to be able to use Sirepo-Bluesky with the ARI and SXN beamlines.
So I returned to our models of them in SRW. 
The SXN model is here:
https://www.sirepo.com/srw#/beamline/q49dua2G
When converting to Shadow, it opens up, but all the calculations give errors:
https://www.sirepo.com/shadow#/source/lZ552KUD

Is this because of the zone plate, or is there another issue? Apologies if this was discussed during phase I blicon, but I forgot the status here.

**Comment by moellep** [comment]
The zone plate was implemented, but it is missing a required library. We'll get this fixed.

**Comment by robnagler** [comment]
Fixed https://github.com/radiasoft/download/pull/186/commits/cd954ad39239909f15d3f5a0ac391aa430d9cbc7

**Comment by robnagler** [comment]
Probably fresnel_zone_plate_simulator.py line 67 imports `FigureCanvasQTAgg`. It probably doesn't need this. I'll look.

```txt
  File "parameters.py", line 8, in <module>
    from orangecontrib.shadow_advanced_tools.util.fresnel_zone_plates.fresnel_zone_plate_simulator import FZPAttributes, FZPSimulatorOptions, FresnelZonePlateSimulator
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/orangecontrib/shadow_advanced_tools/util/fresnel_zone_plates/fresnel_zone_plate_simulator.py", line 67, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 16, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/matplotlib/backends/qt_compat.py", line 175, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

**Comment by robnagler** [comment]
There were some new modules which caused problems plus they started to put try/except around imports that were problematic (go figure) so replaced with `pass #` to be more robust.

**Comment by moellep** [comment]
Hi Boaz, the zone plate now works in sirepo/shadow on alpha - this will go to production soon. The SRW SXN simulation needs to be tuned a bit - it doesn't seem to focus correctly.

Here is an example SRW Zone plate simulation which also works in Shadow:
https://alpha.sirepo.com/srw#/beamline/goka4mTL

**Comment by moellep** [comment]
And now it is on production - here is the simple SRW Zone Plate example, and the Shadow equivalent:

https://www.sirepo.com/srw#/beamline/2WTHhNvc

https://www.sirepo.com/shadow#/beamline/Ojrvpd03

**Comment by bnash** [comment]
The zone plate looks good. The grating in Shadow seems to be blocking out all rays, however, and the moment propagation is looking strange. It certainly could also be an issue with the original SRW simulation as mentioned above.
