### ISSUE TITLE
last modified time should not change with a release

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3931]
I think the fixup that adds last modified time uses "now" instead of the file's mtime.

**Comment by moellep** [comment]
I think the file's mtime won't be correct either because all files would have been rewritten for past fixups, so mtime was never the actual user modified time.

**Comment by moellep** [comment]
If a simulation still has simulation directories around, the mtime on the in.json would be a good guess.

**Comment by robnagler** [comment]
The most recent in.json.
