### ISSUE TITLE
OpalParser.__dedup_elements removes necessary elements

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#3954]
When an OPAL file is parsed necessary, duplicate elements (with different names) are being removed.
For instance the attached example starts with two RFCAVITY elements (CC1 and CC2) that are to be varied independently. However, deduplication replaces CC2 with CC1. 
[fast_injector_toX107.txt](https://github.com/radiasoft/sirepo/files/7530550/fast_injector_toX107.txt)

**Comment by cchall** [comment]
It looks like this is causing new issues with the upgrade to OPAL 2021.1.0 . There is now an additional check to ensure unique monitor filenames. Since monitors are being deduplicated some simulations will now refuse to run.
See monitors X107 in attached is replaced by X106: https://www.sirepo.com/opal#/visualization/uxnqZLMJ 

[example.txt](https://github.com/radiasoft/sirepo/files/7922420/example.txt)

**Comment by moellep** [comment]
Thanks for the example @cchall 
A fix for this will be available soon.

**Comment by sjcrs** [comment]
Possibly related, I see an opal error 
    
    User error detected by function "OpalData::define()"
    You cannot replace the object "GS".
    2}>     You cannot replace the object "GS".
    {0}> *** User error detected by function "OpalData::define()"  
    You cannot replace the object "GS".
    User error detected by function "OpalData::define()"
    You cannot replace the object "GS".

in the example here: 
https://www.sirepo.com/opal#/visualization/QiFt4I1Q

Can also confirm I saw this error when running the script on jupyter. The error was not triggered when I renamed the object `GS0`, at which point I found the monitor error Chris reports above. Maybe the name `GS` is protected in the new version?

**Comment by cchall** [comment]
Yes, `GS` is now a protected name in OPAL 2021.
From an OPAL mailing list thread:

> Since OPAL2021.1 we use predefined constants to declare command attributes (see https://gitlab.psi.ch/OPAL/src/-/issues/654). Thus, we avoid misassignment of these variables, but now some string names are not available to be used as label of elements or beamlines. In your case, GS is a fieldsolver attribute (AMR_MG_SMOOTHER), so you cannot use it.

**Comment by moellep** [comment]
The import-opal-with-monitors problem should be fixed now on alpha. Before it was condensing monitors (and other elements) into one unique element. So if you have an OPAL input file which has distinct monitors, you should be able to import it into sirepo (on alpha so far) and it will work.

**Comment by sjcrs** [comment]
I imported the configuration on alpha, renamed GS->GS0, and am encountering the dedup monitor issue: 
https://alpha.sirepo.com/opal#/lattice/ilVxQESI

**Comment by moellep** [comment]
Can you look at the file you imported and verify how many monitors were present - I'm guessing that there was only the EY1 monitor which was reused in multiple beamlines. That worked with old versions of OPAL, but the new one is requiring them to be unique.

Below is a file with your simulation using unique monitors which should import and run OK on alpha (on production sirepo.com this file won't import correctly until the next production release).

[VerticalBeamlets.in.txt](https://github.com/radiasoft/sirepo/files/7952301/VerticalBeamlets.in.txt)

**Comment by sjcrs** [comment]
Ah, I misunderstood, I thought the import-opal-with-monitors solution mentioned above was solving the backwards compatibility problem. I see now that I'll have to make new monitors for each beamline.
