### ISSUE TITLE
elegant: n_kicks and other Integer fields should be RPNValue

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#3956]
Integer fields in elegant should be changed to RPNValue. For example, having a variable name in CSBEND.n_kicks will cause a server error when trying to export the lattice.

**Comment by cchall** [comment]
#3770 related or maybe just the same issue?

**Comment by moellep** [comment]
Yes, it is related to #3770 and changing all the Integer fields in the schema should fix the problem. CSRCSBEND and CSRDRIFT slice_analysis_interval were already RPNValue types so the problem didn't appear with them. It looks like elegant will take the floor() of any float value for an integer field.
