### ISSUE TITLE
SRW - issue with folder

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#396]
When I try to go to NSLS-II simulations from the basic mode (not expert mode), I get the following error:
![folder_error](https://cloud.githubusercontent.com/assets/13209176/18718186/8b830ef8-7ff0-11e6-86a7-47a46b10a774.png)

**Comment by robnagler** [comment]
Not sure when this was introduced, but this is related to the fact that we don't update all the examples when the schema changes. I'll fix this, but the bigger problem is described in #357
