### ISSUE TITLE
SRW:  the 'Idealized Undulator' tab is too inconspicuous

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#3977]
This is what it looks like:
![image](https://user-images.githubusercontent.com/3825435/144123161-c52ea34e-1ee4-47bf-8f84-7fd64145daf0.png)

Comment from a Sirepo Premium customer:  "At first, I didn't realize one could change the undulator settings."

The feature request is to make the report more obvious to the user, perhaps by adding an undulator icon at the top, or else by listing some of the input variables within the body of the report.

**Comment by robnagler** [comment]
I agree. I don't think we should have panels with no parameters. Even having  "click the pencil icon" (which is also a link) would be useful.

**Comment by gurhar1133** [comment]
How about moving everything from the pencil icon into the panel:
![Screen Shot 2022-04-15 at 10 53 19 AM](https://user-images.githubusercontent.com/49498231/163598569-017f3e38-f470-4636-9989-71acf0f4335d.png)
 ?

**Comment by bruhwiler** [comment]
I suggest you keep 3 parameters in the top-level report:
- period
- length
- effective deflecting parameter

**Comment by gurhar1133** [comment]
> I suggest you keep 3 parameters in the top-level report:
> 
> * period
> * length
> * effective deflecting parameter

By top level, do you mean accessible through the pencil icon?

**Comment by e-carlin** [comment]
Not to be a pedant but we have names for these constructs: the panel you see without clicking on anything is called "basic editor panel" and the panel you see after clicking on the pencil icon is called the "advanced editor panel".

**Comment by gurhar1133** [comment]
> Not to be a pedant but we have names for these constructs: the panel you see without clicking on anything is called "basic editor panel" and the panel you see after clicking on the pencil icon is called the "advanced editor panel".

Helpful clarification of the terms @e-carlin

**Comment by gurhar1133** [comment]
Like this @bruhwiler 
![Screen Shot 2022-04-15 at 11 22 09 AM](https://user-images.githubusercontent.com/49498231/163601366-e88bd95f-05d7-4e03-b2c0-f4d7b80848d6.png)
?

**Comment by bruhwiler** [comment]
Yes, I believe this is the optimal choice for the basic editor panel.
