### ISSUE TITLE
Can't change simulation grid, KeyError simulationType

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#398]
Server error occurs with Key Error for the follow case:

Open "NSLS-II CHX beamline", and select "Discard Changes to Example". Then open the "Initial Wavefront Simulation Grid" and change the Sampling Factor slightly and select Save Changes. Causes a server error:

  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 399, in app_save_simulation_data
    data = _parse_data_input(validate=True)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 672, in _parse_data_input
    return simulation_db.fixup_old_data(data['simulationType'], data) if validate else data
KeyError: 'simulationType'

**Comment by robnagler** [comment]
I'm going to pull simulationType inside fixup_old_data. You can't know anything about the data at this point except perhaps the version so we'll have to figure that out from the data itself instead of having the caller pass it in
