### ISSUE TITLE
implement a Petra beamline

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#4]
In order to recruit users from DESY in Germany, we should implement one Petra beamline
   http://petraiii.desy.de/
The simulation should place limits on what users are allowed to change, so that the virtual model conforms to the real beamline.
Liuba will provide details of a relevant beamline.

**Comment by bruhwile** [comment]
David needs to follow up with Liuba.

**Comment by bruhwile** [comment]
Liuba is obtaining parameters for a selected beamline.

**Comment by samoylv** [comment]
how can one use 'user defined electron beams' option to try PIII [low beta / high beta ] electron beam?

**Comment by bruhwile** [comment]
From the 'Beam Name' drop down menu on the 'Source' tab, look to the very
bottom and select '+New'
Then you can enter the electron beam parameters.

If you would like to have PIII low beta and high beta beam parameters added
to the list of named beams, then please provide the beam parameters and we
will add them.

I hope this answers your question.

Best,
David


On Wed, May 25, 2016 at 7:06 AM, samoylv <notifications@github.com> wrote:

> how can one use 'user defined electron beams' option to try PIII [low beta
> / high beta ] electron beam?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/sirepo/issues/4#issuecomment-221569705>
>



-- 
David Bruhwiler
RadiaSoft LLC
+1 (720) 502-3928

**Comment by samoylv** [comment]
now I found it, thanks!

**Comment by bruhwiler** [comment]
We don't have the resources to pursue this issue further.
