### ISSUE TITLE
ML script import issue

### ISSUE THREAD

**Issue by jennmald** [radiasoft/sirepo#4009]
@jklynch and I have been working on using the ML scripts feature. We kept having an import issue where `srwl_bl`, `srwlib`, `srwlpy`, and` uti_plot_com` were not found. By changing all imports to `from srwpy import <package>` we were able to get the script for CSX to generate data. Not sure if this has something to do with the way we installed SRW or is something worth taking a look at.

Thank you!

**Comment by robnagler** [comment]
I posted on slack. I think this is caused by using the new pip install instead of the "standard" srw install.

**Comment by mrakitin** [comment]
Yes, the package's structure is in https://github.com/Synchrotron-Radiation-Workshop/SRW/tree/reorg (work-in-progress, should get it ready for production soon), that is indeed using the packages root as `srwpy`. The latest version of the conda-forge package is generated with this tag - https://github.com/Synchrotron-Radiation-Workshop/SRW/releases/tag/v0.2 (see https://github.com/conda-forge/srwpy-feedstock/blob/510aec87c289a8d98da42c4c4797cc7e17086cc1/recipe/meta.yaml#L10).

**Comment by robnagler** [comment]
We will need a "try/except" on all imports we generate. As much as I hate to do this, will `from srwpy import *` work?

**Comment by mrakitin** [comment]
Not yet, https://github.com/Synchrotron-Radiation-Workshop/SRW/blob/reorg/python/srwpy/__init__.py is empty, that's why it is not exposing the underlying modules. I can add the shortcuts.

**Comment by robnagler** [comment]
I think we'll end up doing something explicit then. I really don't like `import *`. 

@jennmald it would help to know: Are running the ML scripts in an environment where the `sirepo` package is also installed?

**Comment by jennmald** [comment]
We are running the docker container and running the ML scripts in that environment. Is there a different way I should install the `sirepo` package?

**Comment by robnagler** [comment]
Running in Docker is great. I'm just confused now why it was using the new `srwpy` install. Do you modify the container when it starts or did you create a new docker image?

**Comment by jennmald** [comment]
We haven't modified anything about the container. We tried to run the ML scripts and needed `srwpy` even inside the environment. This led to the use of Conda forge to install it.

**Comment by robnagler** [comment]
What's the name of the Docker image that you are invoking?

**Comment by jennmald** [comment]
It's Sirepo, here is some output when I started it this morning.

```
Creating Directory /home/vagrant/tmp/data/2021/12/21
beta: Pulling from radiasoft/sirepo
Digest: sha256:fba5aea955cda2807daf66443c010d12a22df237be18a39269908c1e4f3e9247
Status: Image is up to date for radiasoft/sirepo:beta
docker.io/radiasoft/sirepo:beta
REPOSITORY         TAG       IMAGE ID       CREATED       SIZE
radiasoft/sirepo   beta      5becae748c04   6 days ago    5.76GB
radiasoft/sirepo   <none>    d81121250f1e   13 days ago   5.76GB
radiasoft/sirepo   <none>    8117306ff3a6   3 weeks ago   5.76GB
Command to run:

docker run -it --init --rm --name sirepo        -e SIREPO_AUTH_METHODS=bluesky:guest        -e SIREPO_AUTH_BLUESKY_SECRET=bluesky        -e SIREPO_SRDB_ROOT=/sirepo        -e SIREPO_COOKIE_IS_SECURE=false        -p 8000:8000        radiasoft/sirepo:beta bash -l -c "mkdir -v -p /sirepo && sirepo service http"

```

**Comment by robnagler** [comment]
Yes, this is used to create the ML script. What I'm curious about is in which container (image) is the script being run?

**Comment by mrakitin** [comment]
@jennmald, did you run it with `docker -it --rm radiasoft/sirepo:beta <your-ml-script>.py` or directlyon your machine?

**Comment by jennmald** [comment]
Directly on my machine. The read me states to run the bash file first which then calls the .py file.

**Comment by robnagler** [comment]
This is fine. It's the reason the scripts don't work without modifications. We don't use srwpy. 

We rely on the Docker image to provide the proper environment for the script. I think you editing the script is fine when it is not run inside Docker. 

When srwpy is officially released, we'll adapt the generated scripts accordingly. I was hoping we could rely on some tools in sirepo, but we'll just generate a conditional inside the script. Probably better for these purposes.
