### ISSUE TITLE
webcon: controls screen vs bpm 

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4014]
In addition to BPM monitors, the controls app could show "screen" elements which show a plot of the beam cross-section. There is no elegant-like WATCH element in MAD-X, but this could be done by looking for the placeholder INSTRUMENT element in the lattice and adding a ptc_observe command to save particles for that element's name. When running the simulation which includes a screen element, the ptc_* commands should be added, similar to the FODO PTC MAD-X example

https://sirepo.com/find-by-name/madx/default/FODO%20PTC

Then in the UI, show a plot of the particles rather than a single BPM point. The screen elements could be included in the panel with the monitors, or in a new panel for screens.

**Comment by e-carlin** [comment]
Is screen an element type we'd want to make available to the user (and we'd convert them to instrument behind the scenes)? Or have them place instrument (which we already support)?

**Comment by moellep** [comment]
I think we want to assume any INSTRUMENT element in the sirepo/mad-x simulation would be interpreted as a screen in the controls app.
