### ISSUE TITLE
sbatch: using the cmd from simulation_db.prepare_simulation

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4024]
We have [this TODO](https://github.com/radiasoft/sirepo/blob/0207d5e62d0e25d2f85f8d45d688aa30d4af1df4/sirepo/pkcli/job_agent.py#L731) in the code for starting an sbatch job:

`#TODO(robnagler) need to get command from prepare_simulation`

[Currently in the sbatch](https://github.com/radiasoft/sirepo/blob/0207d5e62d0e25d2f85f8d45d688aa30d4af1df4/sirepo/pkcli/job_agent.py#L733) case we always just call `python parameters.py` to start the simulation. In non-sbatch cases we call the output of simulation_db.prepare_simulation (ex `sirepo srw run-background <path to run dir>`).

I have a feeling this is causing bugs in the system when running under sbatch. We do work in the pkcli run_background commands that is not being executed if we just run `python parameters.py` (ex [for srw](https://github.com/radiasoft/sirepo/blob/0207d5e62d0e25d2f85f8d45d688aa30d4af1df4/sirepo/pkcli/srw.py#L127))

In addition, we do work [in sirepo.mpi](https://github.com/radiasoft/sirepo/blob/0207d5e62d0e25d2f85f8d45d688aa30d4af1df4/sirepo/mpi.py#L74) that isn't happening for sbatch.

The bug of only calling `python parameters.py` was brought to my attention by flash where [there is no parameters.py](https://github.com/radiasoft/sirepo/blob/0207d5e62d0e25d2f85f8d45d688aa30d4af1df4/sirepo/pkcli/flash.py#L24).

I have implemented a solution to get the output of `prepare_simulation` and call that cmd. But, it leads to a couple of problems:

1. The cmd output by `prepare_simulation` is going to be executed in parallel for each core the user has allocated. In the srw case this isn't that big of a problem, inside of run_background [we are just deleting files](https://github.com/radiasoft/sirepo/blob/0207d5e62d0e25d2f85f8d45d688aa30d4af1df4/sirepo/pkcli/srw.py#L141). But, for other codes there may be problems doing things in parallel. For example, in elegant we [create files](https://github.com/radiasoft/sirepo/blob/0207d5e62d0e25d2f85f8d45d688aa30d4af1df4/sirepo/pkcli/elegant.py#L48). We don't currently run elegant on sbatch so maybe we don't need to worry about it quite yet.
2. Our current mode of running the jobs is not quite right for running an sbatch script that results in an mpiexec. The current flow is `sbatch` -> `srun (with configuration for mpi)` -> `python parameters.py`. I tried changing it to `sbatch` -> `srun` -> `sirepo srw run_background <run_dir>` -> `mpiexec ...`. This doesn't work because srun and mpiexec [don't play well together](https://slurm.schedmd.com/mpi_guide.html#mpich2). The proper way to do this, I think, is `sbatch` -> `salloc` -> `sirepo srw run_background ...` -> `mpiexec`. But, there is a bug in our version of mpich making it so the nodelists aren't passed properly between sbatch and mpi ([discussion](https://jira.lsstcorp.org/browse/DM-24746), [mpich changelog](https://github.com/pmodels/mpich/blob/44bcb53e6830fcda696ca62b1773a9c07f53875f/CHANGES#L153)).
3. sirepo.mpi sets mpi cores. This doesn't make sense for the sbatch case because slurm is managing allocations.

Solutions:
1. Update our version of mpich. This may require updating fedora version too. The latest version of mpich in f32 has the bug. 
2. For flash create a parameters.py and call it using our existing code. This leaves the bugs of not running code in `run_background` and sirepo.mpi but I don't think they are that severe.
3. Monkey around some more with slurm and try to find a way to call slurm/mpi that works. I have low confidence that this will work. 
4. Don't call mpiexec in the sbatch case. Somehow make sirepo.mpi aware when it is running in sbatch and just call the program w/o mpiexec.

Solutions 1, 3, and 4 will require solving problem 3 above as well.

@robnagler I'd like your thoughts.

**Comment by robnagler** [comment]
I think (4) would be a reasonable solution. We already control the environment. We want to call srun, not mpiexec. I don't see why this would require (3) would be fixed for (4).

**Comment by e-carlin** [comment]
Sounds good. You're right that 4 will fix 3.

**Comment by robnagler** [comment]
It can also "fix" the sirepo.mpi.cores issue in that it will be ignored.
