### ISSUE TITLE
NERSC: exec sirepo not found

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4038]
sirepo command is not found on NERSC. Likely related to changes in https://github.com/radiasoft/sirepo/pull/4031/commits/8508dd7960859f35295d70a720c5c6989cdd2ad1

**Comment by e-carlin** [comment]
Of course it doesn't work - sirepo is only available inside of shifter and this is invoking the command that will be run in shifter... Need to rethink the approach.

**Comment by robnagler** [comment]
It could be installed at NERSC in the pyenv. What's needed?

**Comment by e-carlin** [comment]
We need the sirepo command. So that would mean installing sirepo and pykern at a minimum. And we'd have to either be careful about imports or make sure that all of the dependencies that may be required by the pkcli commands are installed (ex [numpy in template_common](https://github.com/radiasoft/sirepo/blob/79e4ec03429c38516a4441357442d513b0c28eaf/sirepo/template/template_common.py#L15)).

**Comment by robnagler** [comment]
Is this because srun is the thing that starts shifter?

**Comment by e-carlin** [comment]
I'm not sure. I need to play with it and understand more how this works. Depending on when we are in shifter vs not there could be a problem because srun isn't available from within shifter.

**Comment by e-carlin** [comment]
@robnagler and I spoke. Decided we need to create some sort of `prepare_slurm` command that will create a python (or maybe shell) script that sbatch will then invoke.

The calling of prepare_slurm will happen where we call _SbatchPrepareSimulationCmd now so it will happen inside of shifter with our full environment. 

The still unclear part will be how we execute things before or after the run. For example, in srw we need to delete large intermediate h5 files that are left after the run.
