### ISSUE TITLE
Setup Celery server script

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#404]
Simple server config on Fedora without public IPs on AWS.

Needs NFS and Rabbit access to apa11.

**Comment by robnagler** [comment]
Make sure docker containers are named so can distinguish in job list.

**Comment by elventear** [comment]
Is the naming static or dynamic? If dynamic, how will I get it?

**Comment by robnagler** [comment]
Naming is static. We'll assign them once we have the private IPs for the
hosts. We'll map them to bivio.biz or radiasoft.* name space.

**Comment by elventear** [comment]
Deployment works as of commit radiasoft/ansible-conf@778c014fc2b8781c048c045f930ecd53e2feba36. See [`sirepo_workers`](https://github.com/radiasoft/ansible-conf/tree/778c014fc2b8781c048c045f930ecd53e2feba36/terraform/sirepo_workers) branch.
