### ISSUE TITLE
npx cannot find jasmine

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4045]
For @gurhar1133 running the tests through `bash test.sh` produced an error about karma being unable to find the jamine framework. A manual install of jasmine (`npm install jasmin`) fixed the issue. 

Running `./node_modules/karma/bin/karma start etc/karma-conf.js` worked so it is likely some problem to do with npx and the context it is using.

**Comment by e-carlin** [comment]
bump @rorour is running into this too

**Comment by rorour** [comment]
'npm install -g karma-cli' gets rid of the issue, but installing locally doesn't.

**Comment by e-carlin** [comment]
Fixed by #4143
