### ISSUE TITLE
Add report name to the Jobs panel

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4048]
When you look at the Jobs page, you can see the running and pending tasks, but do not know what process is actually running. For example, if you are running an SRW partially-coherent simulation and have an SRW beamline simulation pending, it isn't clear what needs to be stopped.

How about adding the report/animation name as a column, but also allow the app to override the display name. For example, SRW has a multiElectronAnimation report, but it should probably be displayed to the user as "Partially Coherent".

**Comment by garsuga** [comment]
Fixed in #4520
