### ISSUE TITLE
Controls: cannot import mad-x 

### ISSUE THREAD

**Issue by gurhar1133** [radiasoft/sirepo#4052]
Create new mad-x simulation from [this](https://github.com/radiasoft/sirepo/files/7892839/in.madx.txt) mad-x input file, then go to controls app, create new simulation using the mad-x simulation that you just made, you will see error like:
` Application Error: TypeError: Cannot read properties of undefined (reading 'models'). A report was sent to the server. `

**Comment by e-carlin** [comment]
False alarm - the export contained {sr_opt} for corrector replacement which is not valid madx so controls could not import it.
