### ISSUE TITLE
ML export remove sirepo dependency

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4058]
We had a request to remove the sirepo.template dependency so the ML script can be run using pip installable libraries. It looks like the only sirepo dependency is to write out the hdf5 file. I think we could generate a similar method inline in the parameters.py to work-around this.

**Comment by robnagler** [comment]
We just created more dependencies. sirepo is pip installable.

**Comment by e-carlin** [comment]
The dependency we created isn't included in the exported ml (only included on our server). But, I think we are trending towards requiring sirepo in the template so it would be good to decide whether or not sirepo is allowed to be a dep in templates or not.

**Comment by mkeilman** [comment]
How should I proceed?
