### ISSUE TITLE
lattice overlay incorrect when using multiple run_setup commands

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#4062]
If you run an elegant simulation with two run_setup commands that use different beamlines only the first beamline will be used for overlays on all the plots.

**Comment by moellep** [comment]
Here's a test case: https://www.sirepo.com/elegant#/visualization/kq0cNp3q

There are two run_setups and each uses a different beamline, but on the Visualization tab, the second one isn't showing the correct beamline.

![Screen Shot 2022-02-25 at 4 12 45 PM](https://user-images.githubusercontent.com/6516910/155815362-2e12cae5-ec59-44fb-8ed6-6f954607c467.png)

The second one should be showing the longer lattice with the markers, like this:

![Screen Shot 2022-02-25 at 4 13 55 PM](https://user-images.githubusercontent.com/6516910/155815430-a8de3430-d832-4f9d-a6eb-8399633d3346.png)
