### ISSUE TITLE
Rebuild vagrant images

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#407]
Need to run builds soon to verify still working (should be) then rebuild and push after freeze.

**Comment by robnagler** [comment]
I'm going to start rebuilding vagrant now.

**Comment by bruhwile** [comment]
Has this been done?
When I 'vagrant up' and run sirepo it doesn't look like the latest version.

This is important for hallway demos at SOS and for the demo day on Thursday.
People may want to install the container on their laptop.

**Comment by robnagler** [comment]
Released radiasoft/sirepo (beamsim, and python2) boxes to Atlas. You should be able to vagrant up and get the latest, which will include the SRW from #455. I tested this on my Mac. @bruhwile please test.

**Comment by bruhwile** [comment]
I think I've obtained the latest version:

bash-4.3$ vagrant box update
==> default: Checking for updates to 'radiasoft/sirepo'
    default: Latest installed version: 20161003.100837
    default: Version constraints:
    default: Provider: virtualbox
==> default: Box 'radiasoft/sirepo' (v20161003.100837) is running the
latest version.


However, when I execute the Sirepo server, I don't see the new hierarchical
structure, but instead the old flat listing of files:

[image: Inline image 1]

Best,
David

**Comment by bruhwile** [comment]
@robnagler solved the problem
One must do the following:
> vagrant box update
> vagrant destroy
> vagrant up

The vagrant container appears to be working well.
