### ISSUE TITLE
Add Slack link to JupyterLab

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4071]
On JupyterLab pages, we want a prominent link to Slack.

**Comment by gurhar1133** [comment]
![Screen Shot 2022-04-27 at 1 17 14 PM](https://user-images.githubusercontent.com/49498231/165603477-2b43966d-840f-43c9-b299-261ea8359a72.png)
Should the link be in the menu or command pallete (or elsewhere)?

**Comment by robnagler** [comment]
In the launcher if possible and in the command pallette.

**Comment by gurhar1133** [comment]
@robnagler We've moved this to rsjupyterlab, what are the next steps here? Or is this issue closed?

**Comment by gurhar1133** [comment]
> It needs to get added to radiasoft/container-beamsim-jupyter. This should be done today as there will be alpha tomorrow. Can you do this? Maybe with Evan's help. Look for the adding the rs-vtk components.

Blocked by https://github.com/radiasoft/sirepo/issues/4439

**Comment by robnagler** [comment]
But the update got added?

**Comment by gurhar1133** [comment]
> But the update got added?

rsjupyterlab was not added to containter-beamsim-jupyter build do to the block.

**Comment by robnagler** [comment]
It has to be added to radiasoft/container-beamsim-jupyter/container-conf/build.sh. Was this done?

**Comment by e-carlin** [comment]
I walked @gurhar1133 through some of the code for building image and showed him [the line](https://github.com/radiasoft/container-beamsim-jupyter/blob/master/container-conf/build.sh#L76) he'd need to change to add to the image. But, because of #4439 he can't install docker (`radia_run redhat-docker` fails with the same error). So he is blocked from testing the build.

**Comment by robnagler** [comment]
@4439 fixed itself.

**Comment by gurhar1133** [comment]
Do we close this now?

**Comment by robnagler** [comment]
Should have closed automatically. Was missing the Fix radiasoft/sirepo#4071 in the title of PR radiasoft/container-beamsim-jupyter#58
