### ISSUE TITLE
Add Slack link to JupyterHub

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4072]
On JupyterHub pages, we want a prominent link to Slack.

**Comment by gurhar1133** [comment]
Should we wait to close this until changes to rsconf/.../conf.py.jinja for production are done or should that be a separate rsconf issue since separate repo?

**Comment by robnagler** [comment]
Create a separate issue. This will be a good experience, because you'll have to make it backwards compatible, since rsconf feeds all systems.

**Comment by gurhar1133** [comment]
K 👍
