### ISSUE TITLE
animation_test.py and report_test.py cover all codes

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#4079]
That method has been removed, so we need to test that the codes do not reference it

**Comment by mkeilman** [comment]
Due to @e-carlin's clarification, I am guessing this issue is now moot?

**Comment by e-carlin** [comment]
As written yes. But, I believe what @robnagler wanted was a generic test of running radia. Had we had a test that exercised radia I would've caught my change typo when I ran the tests.

**Comment by robnagler** [comment]
Yes, animation_test.py and report_test.py should touch all codes.
