### ISSUE TITLE
Push to alpha 9/22/16 

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#409]
Build and push to alpha some time today.

**Comment by robnagler** [comment]
Should we push to alpha?

**Comment by moellep** [comment]
No, I'm not done testing yet. Should be done in a few hours.

**Comment by moellep** [comment]
I'll push to beta then alpha now. I'm guessing this is the ticket to track
this, rather than creating a new push to alpha ticket.

**Comment by moellep** [comment]
Release is done for beta and alpha. I verified that short and long running
tasks work for SRW and warp.

elegant is working on alpha, but on beta it is showing the error below for
long running simulations:

error: RPN_DEFNS environment variable undefined. Must define or provide
-rpnDefns commandline option
