### ISSUE TITLE
Enable KNL nodes

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4098]
This is pending on feedback from customer, but I think we'll want users to be able to select KNL vs Haswell in sbatch.

There's also a bigger change to support Perlmutter (GPU), but I think we should add KNL first to see how that goes. It's a relatively simple change in some sense, but the codes might have to be configured/compiled to use KNL.

**Comment by e-carlin** [comment]
related #3929

**Comment by robnagler** [comment]
Dup
