### ISSUE TITLE
use CalcIntFromElecField() method, rather than repeating full simulation

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#41]
Input from O.C. --

On a related, but different, important point. It looks like now, when one changes something in the “pencil” parameters of a report, entire re-calculation of the underlying radiation electric field takes place. One has to distinguish the main calculation of the radiation electric field (e.g. in the case of Gaussian beam or single-electron SR) and the “extraction” of some radiation characteristic from the electric field without re-calculating it.
E.g. if in the final “Intensity at Waist” report I decided to extract radiation phase instead of the intensity (by specifying this in its “pencil”) – the entire simulation should not be re-done, only another fast call to “CalcIntFromElecField” should happen. This will speed-up the corresponding “refresh”. To me, it is important to fix/implement this (if it really works now as I assume).
Also, “Sampling Factor” and “Relative Precision” may need to be removed from “reports” and added to the “wheel” (where you have propagation parameters, or in another “wheel”), because these are the parameters defining the accuracy of an entire simulation.
I would suggest to leave in a report “pencil” only those parameters that are available in “SRWE->Visualize…” dialog in SRW under IGOR Pro. I did it this way to minimize or avoid unnecessary re-calculations during the entire simulation process.

**Comment by bruhwile** [comment]
Paul and I should discuss this in the context of today's telecon.

**Comment by bruhwile** [comment]
This will be implemented on a report by report basis.

**Comment by mrakitin** [comment]
A similar request is for changing the scale/plot width - it should not cause recalculation of the report since it will not change the data from SRW (#593).

**Comment by bruhwiler** [comment]
@mrakitin -- is this ticket consistent with today's discussion regarding improved treatment of wavefront propagation?

Perhaps it's time to close this ticket?

**Comment by mrakitin** [comment]
I think it's related, but not implemented. @moellep implemented #593 (scaling and resizing without recalculation). It's a similar problem, but I need to learn how #593 was fixed.

**Comment by bruhwiler** [comment]
This issue has been overtaken by events, and some of the points addressed in the original text have been resolved.
