### ISSUE TITLE
SRW - new simulation cannot be created

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#412]
I tried to create a new simulation with <kbd>New Simulation</kbd>, but there is no reaction from both the client and the server after clicking on <kbd>Save Changes</kbd> button. No errors are thrown.

**Comment by robnagler** [comment]
@moellep not sure what's going on isLoaded is false in [entry to autoSave](https://github.com/radiasoft/sirepo/blob/1fa27e47a613d37fac68512706d11243f61e9ac7/sirepo/package_data/static/js/sirepo.js#L147). 

I changed the lastAuotSaveData check on that line to be after, but that didn't fix it. I don't know when isLoaded is set. Maybe we need a flag to autoSave that forces the save and/or refactor autoSave to be autoSave and saveSimulation that always sends the message (no comparisons)?

**Comment by robnagler** [comment]
newSimulation is not being called sirepo.js but saveSimulation is. When should newSimulation be called?

**Comment by moellep** [comment]
In SRW if you select new simulation, it will post to new-simulation.

**Comment by robnagler** [comment]
I just tried and it went right to saveSimulation
