### ISSUE TITLE
make animation_test and report_test faster

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4129]
These really should be run in the release so let's try to pick some simulations that run faster. All the cases (timeouts, errors, etc.) should be preserved, but there's no value in having longer tests.

**Comment by moellep** [comment]
I think in some cases we may not have a fast running example to use. How about giving some extra parameters to sr_animation_run() which updates the data.models with some new values. For example, setting the SRW simulation.sampleFactor to 0.001

**Comment by robnagler** [comment]
That's fine. Anything that makes it work faster. It doesn't have to be a canned simulation.
