### ISSUE TITLE
simulation link broken

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#413]
Selecting "Simulations" header link when viewing a simulation does nothing.

**Comment by robnagler** [comment]
This actually worked for me just now. Can you give me a use case?

**Comment by moellep** [comment]
Something related to console.log, I think. If you have a clean checkout
from master, the "simulations" link won't work on any simulation detail
page. If you enable a log statement to sirepo.js, it starts working.

**Comment by moellep** [comment]
Really odd - the very latest check in Rob made fixes the problem, but I
want to get to the bottom of why it has this behavior. I have a version of
sirepo.js which causes the bug, but if I place a console.log() in the file
(and it doesn't even get called), it causes different behavior.

**Comment by moellep** [comment]
This happens in both Firefox and Chrome on OS X.

**Comment by moellep** [comment]
Good - I figured it out. Related to the javascript style bug Pepe
pointed out with missing if brackets. I introduced this bug:

if (! self.isLoaded() || ! lastAutoSaveData)
    if ($.isFunction(callback)) {
        callback();
    }
    return;

All the more reason to always use if () {}, especially when moving
between javascript and python.
