### ISSUE TITLE
rename simulation broken

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#414]
Renaming a simulation on the simulation list page updates the name, but refreshing the browser shows the change did not make it to the server.

**Comment by mrakitin** [comment]
<kbd>Save Changes</kbd> button does not work at all now.

**Comment by robnagler** [comment]
This is working for me on Chrome/Mac with 1fa27e4

**Comment by robnagler** [comment]
There's a problem if you click save changes then go to simulations. The
page is blank.

I think this is related to the isLoaded and the broadcasting of changes.

**Comment by mrakitin** [comment]
For me it does not work in Firefox.
