### ISSUE TITLE
Better error message when analysis times out

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4156]
"Report not generated" is not very friendly.

**Comment by moellep** [comment]
If the error was related to a file being too big to be returned, something like "The output file was too large to view. You may download the raw datafile." With the "download the raw datafile" as a link to the same location as the download data file link in the report export menu. We should try to determine different error cases - for example if there is a bug in the server data processing, it should have a different error, possibly even "A server error was encountered while processing the datafile, please contact [support@radiasoft.net](mailto:support@radiasoft.net) if the problem persists". Or something along those lines

**Comment by moellep** [comment]
Determine what type of errors:
- browser time-out on a request. Can be reproduced by putting a big sleep() call in the server report processing
- out of memory on the server while processing the datafile
- file too big for either the job supervisor or nginx
For example, if nginx returns a generic 502 bad gateway for a "file too big" error, we will need to catch that case before the data is handed off to nginx and raise an exception with more information. The app will need to share the same config values as the nginx server if this is the case.

**Comment by moellep** [comment]
No, that would be a different case - this is the case where you run a scientific code and it creates a datafile which is many gigabytes and then the plotting request for data is transformed into a http response which is also several gigabytes.

**Comment by moellep** [comment]
In SRW, you can experiment with the values in the Propagation menu on the Beamline tab. For example, here is a simulation which crashes somewhere when retrieving report data because I made the final resolution change 50x.

https://www.sirepo.com/srw#/beamline/Ul1Qjtlv

You may get a different error if you change it to 100x or maybe 25x.

**Comment by gurhar1133** [comment]
Cool. I'll play with that
