### ISSUE TITLE
autoSave will not callback if invalidSerial

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#416]
Right now if there's an invalidSerial a separate call happens, and the original callback is not called. I noticed the fix recently that called back even if the data didn't have to be saved. There is an alert that's put up, and the new data gets saed with refreshSimulationData (formerly saveSimulationData). 

@moellep Do you think it's a problem that the callback is not called in this case?

**Comment by moellep** [comment]
I'm not sure it is the same thing, but when I get an invalid serial, the
client shows the "Another browser updated this simulation; refreshing local
state" but then doesn't accept any more input. I think it would be OK if
the alert message was changed to "ANother browser updated this simulation;
please reload your browser".

**Comment by robnagler** [comment]
We can put up a modal dialog. What do you think?

**Comment by robnagler** [comment]
The problem seems to be that refreshSimulationData doesn't refresh the entire page state so you can enter values but not saveChanges, because the one callback is lost. 

I think invalidSerial should redirect locally and reload the entire app showing an alert. I don't know how to do that. :)
