### ISSUE TITLE
auto save beamline if changed and "start simulation" selected

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4166]
On the SRW beamline page, it is easy to change a beamline element, but forget to select "Save Changes" before selecting "Start New SImulation", which will cause the simulation to run with the old values. Instead, selecting "Start New Simulation" should save the beamline values first, without requiring both "Save Changes" and "Start New SImulation" to be selected in order.

**Comment by gurhar1133** [comment]
Which milestone is this issue?
