### ISSUE TITLE
new CRL in beamline causes server error

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#418]
If you add a CRL to a beamline and select Save Changes, a server error occurs when running the reports. 

  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 335, in fixup_old_data
    'tipRadius': float(item['radius']) * 1e6,  # m -> um
KeyError: 'radius'

**Comment by mrakitin** [comment]
I checked srw.js and it turned out that I removed old `radius` and `wallThickness`. I'll reintroduce them.

**Comment by mrakitin** [comment]
Should be fixed in d71ae5c.
