### ISSUE TITLE
"collapse all" and more robust search for beamline elements

### ISSUE THREAD

**Issue by jeinstei** [radiasoft/sirepo#4188]
Sirepo Elegant lattice view
Beamline Elements section (bottom right)

It looks like the beamline elements section loads with every section expanded by default, so it is somewhat difficult to navigate initially for simulations with a lot of elements. Having it load collapsed by default (or with the collapsed categories of the previous state) would be nice. A "collapse all" and "expand all" would be nice as well.

Doing a browser text "find" on the page for a name in a collapsed category also doesn't open the category to the found beamline element, meaning I can't do a page search to find the element, even though it does report the text being found on the page.

I would also be all for a dynamic search box to filter elements by pattern matching above the elements

**Comment by moellep** [comment]
Thanks for the request, @jeinstei - that would be a good improvement.
