### ISSUE TITLE
Websocket communication to client

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4191]
See #4177.

Develop message protocol over websockets that can be deployed in the supervisor as tornado server, running inside the supervisor so that we can seamlessly support new clients. The protocol will work with a simple client that can render the progress of a simulation. This is not about the data model or UI. Rather, just the communication between client and server.

**Comment by robnagler** [comment]
Here's my current plan:

- Add websocket support to the server that will simply forward requests to APIs using JSON, URIs, etc.
- Modify the angular app  to use a new factory to replace `$http`, which is only used in a couple of places.
- Caching will need to be managed inside the angular app. For starters, we'll cache all frames until the app gets reloaded in RAM.
- WebSocket subprotocols will be used for versioning. This will allow asynchronous app upgrades.
- runStatus will be the first call to be mapped to asynchronous replies as a demonstration of what can be done. This will require a new Supervisor API or to have the API Server to connect to the supervisor via WebSockets. Not sure yet.

**Comment by e-carlin** [comment]
Looks good. How will authentication be handled?

**Comment by robnagler** [comment]
Good question. We'll somehow have to cookie, but it will go back as a message. I think Javascript can set the cookie so that it is returned to the server.
