### ISSUE TITLE
importing SRW py file for gaussian example causes server error

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#420]
If you export the python for a gaussian beam example (like Diffraction by an Aperture), and then try to import the file, you encounter a server error:

  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 247, in fixup_electron_beam
    float(data['models'][und]['length']),
TypeError: float() argument must be a string or a number

It works OK for idealized undulator simulations.

**Comment by mrakitin** [comment]
Fixed in  	3c6bd08 and  	e4bcb0d.
