### ISSUE TITLE
elegant RPN_DEFNS environment variable undefined

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#421]
Only happens on beta.

**Comment by robnagler** [comment]
This is broken on alpha now. There was an RPN_DEFNS=/dev/null in the config, which was masking the problem.

**Comment by bruhwile** [comment]
I've used
​
RPN_DEFNS=/dev/null     when running Elegant from the command line.
That might be the right thing to do.

David

**Comment by robnagler** [comment]
We need RPN_DEFNS, which we [pass correctly now](https://github.com/radiasoft/sirepo/commit/930508e5ec00d9f174409097ba54e70c7c6b2b3c#diff-08013e3781d7fe92e16e02d8df02f0d9)
