### ISSUE TITLE
start agent when user visits app

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4230]
Sometimes there is a lag when a person revisits the site after an absence and visits a page with reports. There is a noticeable delay waiting for the agent to start up to provide the report output. After the agent is running, everything works well.

It would be nice if the agent was started the first moment a logged-in user visits the site, rather than waiting for the first run-status to be called.

**Comment by robnagler** [comment]
@rorour this one is deep so you will need to understand how the supervisor works. 

* https://github.com/radiasoft/sirepo/wiki/Job-system-architecture-overview
* https://github.com/radiasoft/sirepo/wiki/JobManagement
* https://github.com/radiasoft/sirepo/wiki/Debugging-the-job-system

**Comment by robnagler** [comment]
@rorour This was the one I was thinking would be good to do, because it relates to job agents and drivers, which will be a big part of the k8s project.
