### ISSUE TITLE
adm_and_own_jobs_test.py: 'authlib.integrations.base_client' has no attribute 'RemoteApp'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4237]
@rorour do you recognize this as a recent change?

From https://github.com/radiasoft/sirepo/issues/4217#issuecomment-1068173920

The alpha release failed with test adm_and_own_jobs_test.py

class _Client(authlib.integrations.base_client.RemoteApp):
AttributeError: module 'authlib.integrations.base_client' has no attribute 'RemoteApp'
It doesn't fail on dev, so I'm guessing there is a missing package.

**Comment by rorour** [comment]
@robnagler Looks like authlib had a major update today and broke the api. @e-carlin and I will be working on it
