### ISSUE TITLE
feature_config.sim_common?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4240]
Just noticed this. Is sim_common simulation only or common to everything. If it is everything, it should just be called common. If it is simulation only, then the two items in it should get deprecated and moved to common.

Also I don't think we need `sim_common()` as `cfg()`.

**Comment by mkeilman** [comment]
I pushed a fix but I think I have conflated the two cases in the comment. sim_common is to be included in the schema of all simulations (goes with ```for_sim_type```) - but I'm not sure what "moved to common" means.

**Comment by robnagler** [comment]
That's a good idea. Would this show up in models.gui?

**Comment by mkeilman** [comment]
The feature_config items end up in ```SIREPO.APP_SCHEMA.feature_config``` right now

**Comment by robnagler** [comment]
OK, then I would call it common. We don't need to mention it is going to part of the schema, since feature_config in the schema is obviously that and the merge of common and an app.
