### ISSUE TITLE
Correct display orientation of dipole magnets.

### ISSUE THREAD

**Issue by dtabell** [radiasoft/sirepo#4241]
In the OPAL simulation at https://www.sirepo.com/opal#/lattice/scxAtTSU the dipole magnets are all tilted.
According to the OPAL magnet data, however, they should, in fact, all be _oriented vertically_.
I suspect the difficulty relates to the interpretation of `e1`.
In OPAL, the parameter `e1` means something different from what it means in many other accelerator
tracking codes, such as MAD or elegant.
See the OPAL documentation at http://amas.web.psi.ch/opal/Documentation/2021.1/#sec.elements.bend .
In particular, note that `e2` is “uniquely determined by the bend angle, α, and E1”.

So, another piece of this issue is that _the input data for the OPAL rbend should not include a parameter `e2`_.

**Comment by moellep** [comment]
Mad-X (and probably elegant's) rectangular bending orientation which is probably how sirepo is currently drawing the magent
![Screen Shot 2022-03-28 at 1 11 10 PM](https://user-images.githubusercontent.com/6516910/160469755-30eb5078-3dfe-453d-ba90-8d9d9272668f.png)


vs OPAL's RBEND orientation. We need to change the sirepo lattice to draw OPAL RBENDs differently.
![Screen Shot 2022-03-28 at 1 12 15 PM](https://user-images.githubusercontent.com/6516910/160469741-e2e50c11-0676-44c1-8feb-8d7bcd1f1bf4.png)

The 3D report generated by OPAL shows the correct flat orientation:

![Screen Shot 2022-03-28 at 1 03 05 PM](https://user-images.githubusercontent.com/6516910/160469858-cabf3ee3-d00c-4e86-be53-5b4def5f2f5c.png)
