### ISSUE TITLE
Get rid of Authlib?

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4244]
Authlib api changed [which caused us trouble](https://github.com/radiasoft/sirepo/issues/4237). While fixing the change we found bugs ([here](https://github.com/lepture/authlib/issues/444) and [here](https://github.com/lepture/authlib/issues/443)) in Authlib. We don't do much oauth stuff currently (ex don't deal with refresh tokens) so it may make sense to remove authlib and roll our own little oauth module that does just the bits we need.

**Comment by robnagler** [comment]
Agreed. I really don't like authlib. 

We will have to deal with expiry, but not on refresh tokens. The user will just have to reauthenticate.
