### ISSUE TITLE
fix animation and report tests

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4248]
fix failures for alpha release

**Comment by moellep** [comment]
@mkeilman could you look at animation_test.py and report_test.py. Both radia tests are failing - it looks like it is the same error on both tests. You can use the 4248-test-failures branch to check in your changes.

**Comment by mkeilman** [comment]
tests pass locally with this change.  FYI I get bunches of these warnings:
```
../../../.pyenv/versions/3.7.2/lib/python3.7/importlib/_bootstrap.py:219
  /home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: mpi4py.MPI.Status size changed, may indicate binary incompatibility. Expected 40 from C header, got 48 from PyObject
    return f(*args, **kwds)
```

???

**Comment by robnagler** [comment]
Different version of numpy?
