### ISSUE TITLE
getApplicationData calls too frequent

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#425]
I'm not sure what getApplicationData does, but it happens too often:

``` text
10.10.10.1 - - [23/Sep/2016 02:05:47] "POST /get-application-data HTTP/1.1" 200 -
10.10.10.1 - - [23/Sep/2016 02:05:58] "POST /get-application-data HTTP/1.1" 200 -
10.10.10.1 - - [23/Sep/2016 02:05:58] "POST /get-application-data HTTP/1.1" 200 -
```

**Comment by mrakitin** [comment]
It gets data for undulator from the server when you load a simulation. Then, if you open some reports, it also gets some data related to magnetic treatment from the server. It is not as intensive as run status though.

**Comment by robnagler** [comment]
It seems to run every time a modal is opened. Probably should only run if
data changes.

**Comment by mrakitin** [comment]
I'll have a look at this issue later to see if this can be improved.

**Comment by robnagler** [comment]
Not a priority. I'm just recording issues as I see them...

**Comment by robnagler** [comment]
I don't think this is an issue.
