### ISSUE TITLE
slack link not working?

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4253]
I saw the new slack link in dev and tried to click on it. I was taken to a slack.com page that said "there's been a glitch". Same thing on alpha.

Looks like [slack is having](https://status.slack.com/) an incident so maybe that is the cause. 

![Screen Shot 2022-03-23 at 8 58 48 AM](https://user-images.githubusercontent.com/10264515/159729205-d0f40e1b-52cd-4217-9cb6-ecfc2f1f01fe.png)

**Comment by robnagler** [comment]
The URI needs to be configured.

**Comment by robnagler** [comment]
Configured (for all systems). Also will handle schema_common change.
