### ISSUE TITLE
Use braces on all control flow in Javascript

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#428]
This is an ongoing change. If you are in some code, please put in braces in the function.

**Comment by mrakitin** [comment]
Give us an example, please.

**Comment by robnagler** [comment]
See [this comment](https://github.com/radiasoft/sirepo/issues/413#issuecomment-248974733).

**Comment by mrakitin** [comment]
OK, I see, thanks. I usually use `{}` with `if`s, `function`s, etc. Will make sure it's always used.
