### ISSUE TITLE
update opal's particlematterinteraction command

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#4285]
It looks like the TYPE parameter for the PARTICLEMATTERINTERACTION command has changed in version 2021.1 and the options are now either SCATTERING or BEAMSTRIPPING.
See: http://amas.web.psi.ch/opal/Documentation/2021.1/#chp.partmatter

**Comment by robnagler** [comment]
priority?

**Comment by cchall** [comment]
Low. 

I don't know of anyone actually trying to use this on sirepo, I just happened to run across it in testing. I can just fix up opal-schema.json to get sirepo.lib to be happy with it, so I don't really need the update.
