### ISSUE TITLE
ml regression broken with missing wrapt

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4339]
The 2019 World Happiness example fails when running the regression training with "No module named 'wrapt'".

**Comment by e-carlin** [comment]
Not clear to me how this happened. It was listed in the deps in [the build script](https://github.com/radiasoft/download/blob/dfc8946165045b9be5d25db4ae60589c2694c045/installers/rpm-code/codes/ml.sh). But, the rpm didn't contain wrapt. Rebuilding solved the issue...
