### ISSUE TITLE
Show additional info from srw mpi log file

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4347]
Provide more information from the SRW status file when running MPI jobs in the UI. Or provide a way to download the log file via a link.

**Comment by moellep** [comment]
Providing a link to the __srwl_logs__/*.log file for the three MPI jobs would be good enough, I think. 

To run an MPI simulation on dev, first set the environment variable "export SIREPO_MPI_CORES=4", then open any beamline sim and go to the beamline tab and select the "Partially Coherent Results" sub tab. Run the simulation - we should add a link to the log file somewhere in the status message. (The log link could be similar to the "View elegant log" link on the elegant Visualization page). 

Then, add similar log links on the Source tab's Spectral Flux and Coherent Modes panels (This is only shown for tabulated undulator examples).

**Comment by gurhar1133** [comment]
@moellep Is the partially coherent result log in user/.../intensityReport/run.log or user/.../sourceIntensityReport/run.log or elsewhere?

**Comment by gurhar1133** [comment]
Also, what is best way to set "SIREPO_MPI_CORES", back to default?

**Comment by moellep** [comment]
The partial coherent result will be in the directory named after the animation model: multiElectronAnimation

It looks like sirepo/mpi.py has the config for cores, and the default is 1, but I don't think MPI can run with just 1 core, so maybe not.

https://github.com/radiasoft/sirepo/blob/master/sirepo/mpi.py#L104

If you want to always have a set value, like 4, you can add this to your ~/.post_bivio_bashrc:
```
export SIREPO_MPI_CORES=4
```
and then logout and login to you vm.

**Comment by robnagler** [comment]
mpi can run with 1 core. Some codes can't, but that's code dependent.

**Comment by robnagler** [comment]
And  you don't need to logout/login, just run:

```sh
source ~/.bashrc
```
