### ISSUE TITLE
warp copy simulation causes bad gateway

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#436]
Something about this particular dataset causes a bad gateway:

https://alpha.sirepo.com/warp#/source/hTi59c9E

![screen shot 2016-09-26 at 4 43 16 pm](https://cloud.githubusercontent.com/assets/6516910/18854457/d6c0f706-8408-11e6-98c5-d0f495552012.png)

**Comment by robnagler** [comment]
I saw this on env and then I thought I fixed it. I'll poke around
