### ISSUE TITLE
Removing Vimeo videos from SRW app

### ISSUE THREAD

**Issue by LexiJess** [radiasoft/sirepo#4370]
Remove Vimeo instructional video from the SRW app. 
![vimeo_video](https://user-images.githubusercontent.com/32692730/165388339-0c568bb4-7dc0-4697-bd7c-593ce88707d7.png)

**Comment by gurhar1133** [comment]
There are video links in the undulator tabs as well. Do we want to remove those as well? @LexiJess @robnagler 

eg. 
<img width="889" alt="Screen Shot 2022-04-26 at 4 38 13 PM" src="https://user-images.githubusercontent.com/49498231/165404280-17bf9143-e35b-498f-aacc-538905b3d555.png">

**Comment by moellep** [comment]
If we want to remove the videos, we should add a config option to hide them. I'm guessing they will still want the video links on the local BNL server.
