### ISSUE TITLE
log time format

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#438]
It looks like the nginx logs are in local time and the sirepo/celery logs are in GMT. It would be nice if they could agree.

**Comment by robnagler** [comment]
Containers don't get the local time zone of the host. It would be easiest
to set the host's time to UTC (our vagrant boxes are already this way).
Given that Pepe is timezone-challenged wrt to the rest of the team, it
seems only fair. ;-)

**Comment by robnagler** [comment]
Is there an agreement to go to UCT? Our VMs are already in UCT.

**Comment by mrakitin** [comment]
It's fine for me if it's stated explicitly in the logs.

**Comment by robnagler** [comment]
We can't rely on the time formats including time zone. That's part of the
problem. For example, the UWSGI format is: [04/Oct/2016 14:34:04]. The
Python log format is: Oct 04 14:35:34. I think standardizing on UCT on the
servers means we don't have to ask the question, since it will be a
constant.

**Comment by mrakitin** [comment]
OK.
