### ISSUE TITLE
Replace Flask with Tornado

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4388]
Do not change supervisor structure. Just replace Flask in server.py.

**Comment by robnagler** [comment]
@rorour This is going to be an ongoing project. We'll first finish the class based API, which will give us a handle to start refactoring various components to allow a smooth migration to tornado from flask. Much of this can be scripted. 

We will use sreq 

This is a rough sketch:

1. Change http_request.parse_* self.parse_*
2. Add self.reply in request.Base init which will be an sirepo.reply.Base instance.
3. Change http_reply.gen_* to self.reply.* (class methods)
4. flask.request.data to self.content
5. flask.request.form to self.form
6. flask.Response() to self.reply.static() -- there's only one of these
7. flask.make_response self.reply.somethign (not sure)
8. http_reply.headers_for_cache to self.reply.cache()
9. heades_for_nocache to self.reply.no_cache()

This will go on until we've migrated all calls into sirepo.request or sirepo.reply.

**Comment by rorour** [comment]
1. https://github.com/radiasoft/sirepo/issues/4447
2. https://github.com/radiasoft/sirepo/issues/4481
3. -
4. -
5. -
6. -
7. -
8. -
9. -

**Comment by robnagler** [comment]
https://github.com/radiasoft/sirepo/pull/4880 is most of the way towards eliminating flask.g. simulation_db access needs work. auth_db needs to use qcalls (#4872). 

What is done is auth, srunit, supervisor, job_agent, and pkcli have been fixed. Many tests work.

**Comment by robnagler** [comment]
Most of the app is working (except file uploads):

![tornado-srw](https://user-images.githubusercontent.com/5495179/214475755-a5d3a23c-0723-4dea-84d0-c5086283017c.jpg)

#5326 is necessary before one can call it "done".
