### ISSUE TITLE
sirepo log clobbered?

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#439]
On alpha, the /var/lib/sirepo/init.log starts at 22:57:11 gmt, but there must have been activity prior to that. I was trying to debug the run-simulation 502 errors which happened at 16:04:52 in the nginx logs.

**Comment by robnagler** [comment]
Fix radiasoft/devops@3efabe02f61ac8c192cc8965fecd0fe28a2af37a
The log is now moved to a timestamped file. Before it was being removed.
