### ISSUE TITLE
Radia:  in wiggler example, the default "Field on Path" report is blank

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#4392]
This is very confusing for one of the official examples.
The default "Field on Path" parameters should be changed so that the user sees something meaningful.

![image](https://user-images.githubusercontent.com/3825435/167305662-7c308ee6-a280-4791-add5-bec3a2504d5d.png)

**Comment by mkeilman** [comment]
A fresh example works properly - the plot axis above is set to z when it should be y.

**Comment by robnagler** [comment]
Is this fixed?

**Comment by robnagler** [comment]
Discard changes is good enough.
