### ISSUE TITLE
Radia: in wiggler example, 'Fields' view in 'Magnet Viewer' report seems to be broken

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#4393]

**Comment by bruhwiler** [comment]
The 'Objects' view is the default and that looks great.

When I switch to the 'Fields' view, I see the following, which doesn't make sense to me:

![image](https://user-images.githubusercontent.com/3825435/167306048-ed85c7e1-5301-4c31-a5b5-71159abc6e1a.png)

Switching between 'Uniform', 'Linear' and 'Log' settings doesn't seem to have any effect.

**Comment by mkeilman** [comment]
Discarding changes to example clears this up (sensing a theme this morning) though I'm not sure what went wrong here. If you share the simulation I will see if anything deeper is going on.

**Comment by moellep** [comment]
We should add a tool to reset example simulations. I'll open another issue for this.
