### ISSUE TITLE
Radia: in Dipole example, it seems that the field solve is failing

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#4394]
In the 'Solver' report, I see two troublesome text messages:
* Error "
and
* No solution found

![image](https://user-images.githubusercontent.com/3825435/167306301-dd146a09-451f-4712-af48-697a43301ddd.png)

**Comment by mkeilman** [comment]
Share the simulation link and I will investigate. Does the error persist if you do a new solve?

**Comment by bruhwiler** [comment]
Here's the link,  https://www.sirepo.com/radia#/visualization/jWHjazAZ

Clicking 'Start New Solve' made the problem go away.

**Comment by mkeilman** [comment]
I get a server error when opening the simulation. @moellep can you get in to the server and zip it up for me? thx!

**Comment by moellep** [comment]
Here is the sirepo-data.json file. If you need more data, let me know and I can send you a zip file.
[sirepo-data.json.txt](https://github.com/radiasoft/sirepo/files/8653362/sirepo-data.json.txt)

The error on the server was:
```
exception=<class 'AssertionError'>
msg={
  ObjectType': [
                ['cuboid', 'Cuboid'],
		['cee', 'Extruded C-Bend'],
		['ell', 'Extruded L-Bend'],
		['jay', 'Extruded J-Bend'],
		['racetrack', 'RaceTrack'],
		['tee', 'Extruded Tee']
	       ],
enum ObjectType value box not in schema
```
