### ISSUE TITLE
Reset examples admin tool

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4395]
We should add a reset-examples method to pkcli/admin. This could be used to remove old examples which are no longer used and to freshen up really old example files.

**Comment by moellep** [comment]
This is similar to the pkcli.admin module's create_examples(). Instead, it should go through all simulations which have isExample=true and remove the ones which are no longer present in the example dataset (the list returned from simulation_db.examples(sim_type). It should also revert any examples to the original data if the example has an old simulation.lastModified date (say 6 months or older).

An extra bonus would be to implement it in a way that doesn't crash if the simulation data file is corrupted or unreadable. Instead, it should try/except and print the name of the simulation file which isn't readable and continue. Also, add the same try/except to create_examples().

**Comment by gurhar1133** [comment]
> An extra bonus would be to implement it in a way that doesn't crash if the simulation data file is corrupted or unreadable. Instead, it should try/except and print the name of the simulation file which isn't readable and continue. Also, add the same try/except to create_examples().

@robnagler do you have an example or an idea for creating an example of a corrupted or unreadable data file?

**Comment by gurhar1133** [comment]
> I think you could delete a required parameter from the json. Easiest way is to bring up sirepo and edit sirepo-data.json while trying to refresh simulations. I'm sure there are parameters that will cause a crash.

Thanks :)

**Comment by moellep** [comment]
Another corrupt example could be a partially written sirepo-data.json which doesn't parse as json. Another example would be an empty sirepo-data.json

**Comment by robnagler** [comment]
a partially written data file "can't" happen.

**Comment by robnagler** [comment]
[atomic_write should avoid this](https://github.com/radiasoft/sirepo/blob/7deba478a40a1dd52f47ea77c559858e3f5180c0/sirepo/util.py#L311). That's what I meant about "can't".

**Comment by gurhar1133** [comment]
Is this closed now?

**Comment by moellep** [comment]
Closed with #4611
