### ISSUE TITLE
Gaussian pulse source page: error for small value of distance

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#44]
In the Intensity Report on the source page of a Gaussian pulse, if the value for "Distance From Source [m]" is set to too small a value (for example 1.), then an error is generated, as seen in the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/3825435/11375529/01a5470e-9299-11e5-8f8b-9a022f2588b2.png)

**Comment by mrakitin** [comment]
This is still an issue.

**Comment by moellep** [comment]
I can't reproduce this anymore.
