### ISSUE TITLE
mpi_run.out needs to be a constant

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4400]
When running with sirepo.mpi, output is writted to mpi_run.out. Several apps parse that output for errors. There should be a constant sirepo.mpi.MPI_LOG or similar rather than hard-coding 'mpi_run.out' across the modules.

https://github.com/radiasoft/sirepo/blob/master/sirepo/mpi.py#L64

**Comment by robnagler** [comment]
Should this maybe be the same as run.log? There's no need to set output to something.

**Comment by moellep** [comment]
It looks like both run.log and mpi_run.out get written to - run.log has the exit result of the mpiexec command.

**Comment by gurhar1133** [comment]
Where should I set the constant? in template_common?

**Comment by moellep** [comment]
Yes, that seems like a good place.
