### ISSUE TITLE
VBoxHeadless cpu when running sirepo service http

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4401]
I notice when I have "sirepo service http" running on dev (even before a browser request has been made), it causes the VBoxHeadless to sit at a constant 30% usage. It stays there even though no requests are being handled. Is there polling or something similar which would cause the process to be working? It is annoying because it causes the laptop fan to be running constantly.

**Comment by robnagler** [comment]
I'm pretty sure there is a watcher running that is certainly watching all files. Try editing the config to turn off FLASK_DEBUG
