### ISSUE TITLE
20230115 missing 1 required positional argument: 'max workers'

### ISSUE THREAD

**Issue by rorour** [radiasoft/sirepo#4404]
![Screen Shot 2022-05-10 at 12 26 22 PM](https://user-images.githubusercontent.com/65698621/167927837-295638e3-4e5b-4d36-b6ff-03cb574a16d9.png)

**Comment by robnagler** [comment]
@rorour has this happened again? I forgot the context.

**Comment by rorour** [comment]
No, I haven't seen this recently
