### ISSUE TITLE
Add image processing to activait

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#4406]
Blicon will use this to analyze srw output. A couple of notes about the initial work:

- use regression only
- use convolution layers instead of neural net layers

**Comment by moellep** [comment]
A roadmap for the new features related to image processing
[Sirepo_activait Improvements.pdf](https://github.com/radiasoft/sirepo/files/9075557/Sirepo_activait.Improvements.pdf)

**Comment by mkeilman** [comment]
I believe @gurhar1133's efforts took care of this, correct?

**Comment by moellep** [comment]
Yes, this item is completed.
