### ISSUE TITLE
Delete old branches

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4418]
There are too many branches lying around that should be deleted. @moellep @e-carlin please make sure you delete branches when you merge PRs.

**Comment by robnagler** [comment]
Also delete in download, devops, etc. if there are any.

**Comment by moellep** [comment]
I've closed many of the merged branches in sirepo - @e-carlin I left ones with you names on them just in case.

**Comment by e-carlin** [comment]
Thanks. Done.
