### ISSUE TITLE
Normalize get_data_file arg use

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4428]
There is a single caller of get_data_file, which is:

```py
        r = template.get_data_file(
            msg.runDir,
            msg.analysisModel,
            msg.frame,
            options=PKDict(suffix=msg.suffix),
	)
```

There are N different ways of handling args. Since `options` was added, it is unnecessary to have `**kwargs`, because `options` is for handling this case. While I normally recommend `**kwargs` on APIs like this, I would say it confuses things.

Here are the 3 cases:

- `if options and options.suffix == _ZGOUBI_COMMAND_FILE:`
- `sfx = (options.suffix or default_sfx) if options and 'suffix' in options else default_sfx`
- `if options and options.get('suffix') == 'sr_long_analysis':`
- `if not options.suffix`

All of these need to be changed except the last one. `options.suffix` is always defined. It may be None, but comparisons to None are fine. It is sufficient to use options.suffix or default_sfx, for example.

The signature for all defs should be:

```py
def get_data_file(run_dir, model, frame, options):
```

suffix is a misnomer we'll have to live with.

**Comment by gurhar1133** [comment]
And we want to change the `get_data_file` signature to use options in this way across all sims, not just zgoubi, correct @robnagler

**Comment by robnagler** [comment]
Yes, all get_data_file defs should have the same definition.
