### ISSUE TITLE
Consider using ijk for ngui

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4434]
Moving from slack to here:

[Gurhar]  [5:19 PM](https://radiasoft.slack.com/archives/C014VU5RDPC/p1653002363385179)
Played around with react after the meeting today and found an interesting way to write react without jsx.  This [article](https://medium.com/geekculture/jsx-alternatives-5d06639a8ba4)  pointed me to a library called [ijk](https://github.com/lukejacksonn/ijk) that "does not try mimic HTML or JSON syntax but instead a series of nested arrays to represent user interfaces."
eg.
```
const tree = h('x', 'y', 'z')
(
  ['main', [
    ['h1', 'Hello World'],
    ['input', { type: 'range' }],
    ['button', { onclick: console.log }, 'Log Event'],
  ]]
)
This is an example of how ijk would interact with react
function render(structure) {
  return h('nodeName', 'attributes', 'children')(structure)
}
class MyDemo extends React.Component {
  render() {
    return render(
        ['main', [
            ['h1', 'Hello World'],
            ['input', { type: 'range' }],
            ['button', { onclick: console.log }, 'Log Event'],
            ]
        ]
    );
  }
}
```

[moellep] [5:23 PM](https://radiasoft.slack.com/archives/C014VU5RDPC/p1653002586187969)
it looks nice and declarative - does it let you have custom components, or just using existing dom elements

[Gurhar](https://app.slack.com/team/U02TBK9TVPT)  [5:25 PM](https://radiasoft.slack.com/archives/C014VU5RDPC/p1653002748853719)
Not sure. But maybe you could create a custom React.Component and pass it in to the nested list? It's such a tiny library that my guess is that you could

[ecarlin](https://app.slack.com/team/U013VMF4B33)  [5:27 PM](https://radiasoft.slack.com/archives/C014VU5RDPC/p1653002866736929)
I think that's the right direction. The library isn't much code https://github.com/lukejacksonn/ijk/blob/master/index.js will need to spend some time understanding how it works.
If you want an example using react.createElement I started an app a while back https://github.com/radiasoft/reactapp/blob/e-carlin/sirepo-components.js#L1
I think this lib still misses the mark for us a bit. That no lib can really provide. And that is how we talk about our domain. Whether we structure it as a list like this or as a series of nested react.createElement's I'm not sure which is better

[robnagler](https://app.slack.com/team/U0QGB1ERG)  [7:55 PM](https://radiasoft.slack.com/archives/C014VU5RDPC/p1653011751777999)
the list has an advantage that it doesn't require a "syntax" hook, i.e. no preprocessor. perhaps we can hook into the object model to make cals like h1('hello') work, but that is work with a little less syntax than ['h1', 'hello'].
what you don't want is things like "onclick" and instead a higher level abstraction. that's the part we need to think about

[Mike Keilman](https://app.slack.com/team/U015243825S)  [9:04 AM](https://radiasoft.slack.com/archives/C014VU5RDPC/p1653059061723179)
I confess I do not like using arrays where order is irrelevant, because you then have to define what each position means elsewhere, and it is pain if you want to rearrange things. To wit: the way we currently define fields in our schema. Nothing compels a label to come first, then a type, etc. In fact srw (of course) defines some higher slots differently than other apps. I much prefer explicit meaning ("this is a label and here is its value") to implicit ("this is a string, hope you guess correctly what it means when in position 2"). The views in the schema are a better use of arrays since they really are "field 1 then field 2".

[robnagler](https://app.slack.com/team/U0QGB1ERG)  [9:51 AM](https://radiasoft.slack.com/archives/C014VU5RDPC/p1653061869215019)
positional vs named arguments has a long history. the schema of our schema is schemaless, that is, it is defined by code, another long history. the fact that srw abuses the higher slots is a problem.
i do not think we want to write:
{method: h1, content: 'hello'}
however, we do want to refer to the object this way. this is important: repetitive declarations can be positional but referred to by name, this is the way most programming languages work, for a good reason.
for optional arguments (viz recent get_data_file changes) we can add options to the declaration, e.g.
['h1', 'hello', {category: 'report_title'}]
one can allow fully positional with the option to use keyword args (viz python calls) like this. it's not very hard, and we did it 23 years ago when we created BOP, almost exactly this way, for all these very reasons.
and this should not be a slack converation

**Comment by e-carlin** [comment]
> the list has an advantage that it doesn't require a "syntax" hook, i.e. no preprocessor

I don't think calling react.createElement requires a hook either. Correct?

> I confess I do not like using arrays where order is irrelevant, because you then have to define what each position means elsewhere, and it is pain if you want to rearrange things

+1. It makes the code harder for me to understand. Especially in a land where we're figuring out how we want to talk about things I think we "tie our hands" before we know what's going on.



Thoughts I had while walking this morning: The more I think about using this list structure the less I like it. My general feeling is using specific data structures we've defined will lead to better description of our domain than generic lists with strings. Imagine we have an 'h1' and we want to create a reportPanelH1 that is some specific type of h1. If we have object representing an h1 then we can more easily subclass and tailor the behavior for our reportPanelH1. If we have lists of string names it becomes harder to do that. At the lower level we could turn the list string h1 into an object and subclass but it strikes me as simpler to just work with object from the start and skip the list/string intermediary language.

**Comment by robnagler** [comment]
@e-carlin are you saying that we should use this `{method: h1, content: 'hello'}`?

The inheritance hierarchy is independent of the syntax. Lists of string names doesn't not preclude inheritance with where those names are defined.

> strikes me as simpler to just work with object from the start and skip the list/string intermediary language.

It is simpler. It would be even simpler to use JSX. However, the level of abstraction presented is insufficient.

Our goal is not to build a better way to say H1. Rather, we want to speak abstractly about the objects in our system: reports, graphs, notices, report inputs, etc. This is the danger of starting bottom up and not going top down. We actually know what we have today. When we started, we had no idea so starting bottom up made sense.

To my mind, we would want to avoid any Javascript except the bare minimum interpreter of a DSL that the server would send back. This was the idea behind Postscript (and NeWS) and the V window system. React, VTK, and D3 are fast, portable rendering engines. They don't understand our domain.

That being said, there's a significant cost to thinking this way. It may be much easier to go the simplistic route as we have done with Angular. The problem with Angular is not the copy-and-paste, it's understanding event management. This will only get more complex with unsolicited events coming from the server.

**Comment by e-carlin** [comment]
> @e-carlin are you saying that we should use this {method: h1, content: 'hello'}?

No I'm saying we should have `h1('hello')`. That h1 is probably a class but maybe a function. It has some api (ex a render method) that returns some data structure that we then call react.createElement on. Or maybe it calls react.createElement inside of itself (probably the base class would call it). Maybe for the base level html tags (h1, div, a, etc) we don't bother with making a function/class for them. But, for any of our stuff (ex reportPanel) we do.

> It is simpler. It would be even simpler to use JSX. However, the level of abstraction presented is insufficient.

I agree. See https://github.com/radiasoft/reactapp/blob/e-carlin/app.js#L36 for a start of some of the abstraction I'm thinking of. 

> The problem with Angular is not the copy-and-paste, it's understanding event management
Really? I agree that event management is important but the copy and paste is a bummer too. It is hard to say "this is a x type of report panel". Instead we just copy and paste. Eventually we pull out a directive to wrap up some things but sharing the business logic isn't easy. For example, srw has its own simStatusPanel that is mostly copy and paste of the sirepo-components one. I'd like our new system to provide a clear way to eliminate this. Another even more glaring example is the appHeader directive which every app has a copy of. 

> unsolicited events coming from the server.

This is a very important point I haven't been thinking about. We are going to add a whole new layer of complexity with websockets and the server pushing events.

**Comment by robnagler** [comment]
> No I'm saying we should have h1('hello').

That introduces the namespace problem: Where does the name "h1" come from? There will be dozens of these names. Do we inject them magically (viz py.test)? Do we look them up dynamically when they are not found (viz. BOP)? Put `$` or `_` in front of them (viz jquery and underscore)? Do we preprocess (viz JSX)?

The difference between: h1('hello') and ['h1','hello'] is three characters. The name "h1" exists somewhere, and it is found, and that's the magic. There's always magic unless you understand it, then it is just code. :)

> the copy and paste is a bummer too

That can be solved in any number of ways even with JSX. I see @gurhar1133's argument that you can't find the answer on stackoverflow.

> We are going to add a whole new layer of complexity with websockets and the server pushing events.

Also not solved by React. I did see a solution in WAMP many years ago, but it never caught on. I wasn't 100% thrilled anyway (which is why I didn't bother using it). Nobody seems to care about this problem, which is why, for example, when you add a contact in Gmail, it doesn't show up in autocomplete. (Even when you add a user in workspace, it doesn't show up in the list of users until you refresh.)

> https://github.com/radiasoft/reactapp/blob/e-carlin/app.js#L36

This uses positional notation:

```js
            model: {
                modelA: {
                    foo: ['Foo var', 'String', '']
                }
            },

```

You need to expand everything if you buy into what @mkeilman is saying.

And this is the crux of the event problem:

```js
        this.APP_STATE = {
            model: {
                modelA: {
                    foo: 'a default value for foo'
                }
            }
```

Where does this data come from and how does it get distributed?

```js
    render() {
        return this.app(
            this.panel('modelA'),
        );
    }
```

I don't like this particularly. The rendering could should be in super based on the relationships that have been established prior to rendering. Usually, you render the same relationships. Sometimes the relationships need to be dynamic, but even then, they are relationships that should be known and pre-declared.

modelA is a string. What is a panel?

```js
    panel(modelKey) {
        return this.div({
            props: {className: 'col-sm-12'},
            children: [
                this.div({
                    props: {className: 'panel panel-info'},
                    children: [
                        this.panelHeader(modelKey),
                        this.panelBody(modelKey)
                    ]
                })
            ]
        })
    }
```

This too needs a higher level of abstraction. For example, everything could be a div. I don't see why it can't be. props should be generated from a table or some type of name mapping.

**Comment by e-carlin** [comment]
> That introduces the namespace problem: Where does the name "h1" come from? There will be dozens of these names. Do we inject them magically (viz py.test)? Do we look them up dynamically when they are not found (viz. BOP)? Put $ or _ in front of them (viz jquery and underscore)? Do we preprocess (viz JSX)?

Good questions. I don't have a clue. They way I did it in my example was using a base class but I have no experience to guide me if this scales.

> h1('hello') and ['h1','hello'] is three characters

If that is the only difference then I am fine with it. In the ijk library h1 is just a string and we never get the object to use ourselves. As long as h1 either starts life as an object or resolves further down to an object we have control over then I don't have a strong opinion yet as to whether the list notation makes sense.


> This uses positional notation:

This is just a "copy" of our existing schema. Haven't solved all problems yet:)


> Where does this data come from and how does it get distributed?

Yes, I'm hoping to start understanding how to do that in the coming weeks.

> The rendering could should be in super based on the relationships that have been established prior to rendering

Can you say this another way? I'm not sure what "in super" means. Are you saying that the details of how the components are stitched together should come from the server?

> This too needs a higher level of abstraction. For example, everything could be a div.

How does everything being a div and creating a higher level of abstraction relate to eachother?

> I don't see why it can't be

The only arguments I've heard is the html then isn't "semantic" (not convincing). And that it creates a harder time for screen readers. I don't actually know if that argument holds water or that a11y is something we want/required to do.
