### ISSUE TITLE
"Lesson plan" for radia

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#4454]
Put together a resource to explain how radia (sirepo), Radia (oleg), vtk, etc. all tie together, to make it easier to hand off to other devs. Will require some refactoring to reduce the complexity

**Comment by mkeilman** [comment]
- [ ] vtk wiki
- [ ] sirepo radia wiki

**Comment by robnagler** [comment]
This is the type of issue that should be closed and two smaller issues for the wikis, and even then smaller issues for sections of the wikis to get completed.

**Comment by mkeilman** [comment]
Closing - see instead #4750 and #4751.
