### ISSUE TITLE
bad angular template text

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4479]
I think the change to smart quotes didn't work correctly for warpvnd's Conductor Grid 3D Preview - see the ' and // in the upper left of the report panel.

![Screen Shot 2022-06-01 at 3 33 07 PM](https://user-images.githubusercontent.com/6516910/171505710-b4f62437-ebb2-4288-845b-a5f171be497b.png)

**Comment by mkeilman** [comment]
Already addressed by https://github.com/radiasoft/sirepo/commit/ccda0ab8cc6072eadd4bc4bd7713751029c9eb54
