### ISSUE TITLE
Create an end-to-end test that runs in Docker

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4488]
Try using https://www.cypress.io/ for a simple test of a sirepo app. If a different testing library is easier or more familiar, use that instead.

An example test scenario:

Visit /srw
Click on "Light Source Facilities" folder, then "NSLS-II" then "NSLS-II CHX beamline"
Click "NSLS-II CHX beamline" simulation
Select "Discard Changes to Example" from the Cogwheel menu
Wait for the "Single-Electron Spectrum" report to complete and then select "Raw Data File" from that panel's.
Select the Beamline tab and then the "Start New SImulation" button.
Wait for the last report panel to finish, and then select Download as PNG.

**Comment by garsuga** [comment]
I submitted an issue to Cypress on the regex replacement bug [https://github.com/cypress-io/cypress/issues/22235](url)

**Comment by garsuga** [comment]
These tests seem somewhat easy to write in [Playwright](https://playwright.dev/). An example test can be seen here [https://github.com/radiasoft/sirepo/blob/b7efafd7b673a72c3eb19c67c03670273462d6be/tests/sirepo/example.spec.js](https://github.com/radiasoft/sirepo/blob/b7efafd7b673a72c3eb19c67c03670273462d6be/tests/sirepo/example.spec.js). Playwright can do E2E but we would need another framework for unit testing. Playwright has a feature that can record your actions on a page as testing code but I have found that our code needs more descriptive selectors for this to be effective on a page like a report in SRW.

**Comment by robnagler** [comment]
Looks nice. So even thought it doesn't have a playback feature, it seems like it does enough of what we want. Again the goal is just to get an end to end test going. What needs to be installed for this to work?

**Comment by garsuga** [comment]
The playwright package is on npm and then there is an npx command to have it install its own browsers. It has one for each of the main 3. It can record video / take screenshots on demand and I believe we could make this process automatic if needed.

**Comment by rorour** [comment]
@robnagler is the goal that this will be another check on prs using github actions?

**Comment by robnagler** [comment]
No, it will run on our server and test against alpha, beta, and prod to verify basic functioning of the GUI. It will likely be started automatically after the release process.

The docker image will need whatever is needed for playwright requires and nothing for sirepo, i.e. it can be based off of radiasoft/fedora or perhaps radiasoft/python3.

**Comment by robnagler** [comment]
@garsuga @rorour Let's get this moving next week. I'd like us to be able to deploy playwright. Schedule a meeting with me so we can work through the steps.

**Comment by robnagler** [comment]
@garsuga please list the steps that are required to finish this up.

**Comment by garsuga** [comment]
1. Test/finish the Docker container
2. Add a system to login and create account during testing
3. Deploy

**Comment by garsuga** [comment]
@robnagler I need some assistance on the login process. I will set up a meeting with you to handle that and to catch up on this issue.

**Comment by robnagler** [comment]
@garsuga I bumped the deadline to 11/17. I'd like to meet with you then so we can finish up the devops side of things. You should have a working e2e running with email logging in from your VM.

**Comment by robnagler** [comment]
I think the next step is to run this on a server.

**Comment by robnagler** [comment]
This is done. You can use @radiasoft/container-sirepo-e2e/run.sh (after you build the container) to test locally. One could also install playright locally and run the tests interactively.
