### ISSUE TITLE
srw: missing undulator field updates

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4500]
When the fields were moved to the main Idealized Undulator panel, some of the automatic update logic was lost.

For example, when the undulator period is changed, then should recalculate deflecting parameters and automatically update the "Effective Deflecting Parameter" value shown on the basic panel.

**Comment by gurhar1133** [comment]
@moellep are their fields other than effective deflecting parameter that I should expect to change when I change period? And should I also expect Effective Deflecting Parameter to change if Length is updated?

**Comment by moellep** [comment]
I think the period, length and effective deflecting parameter fields should be shown on both the basic and the advanced view. The advanced view is the best way to see how the fields interact.

In computeUndulatorDefinition() the inputs are:

horizontalDeflectingParameter
verticalDeflectingParameter
horizontalAmplitude
verticalAmplitude
period

once computed, this updates these fields:

horizontalDeflectingParameter
verticalDeflectingParameter
horizontalAmplitude
verticalAmplitude
effectiveDeflectingParameter
