### ISSUE TITLE
Application Error: Error: [$compile:tpload] http://errors.angularjs.org/1.4.2/$compile/tpload?...

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#451]
I got the following error when I try to run the examples on beta:
```Application Error: Error: [$compile:tpload] http://errors.angularjs.org/1.4.2/$compile/tpload?p0=%2Fstatic%2Fhtml%2Fheatmap.html%3F20160928.000000&p1=undefined&p2=undefined. A report was sent to the server.```

**Comment by mrakitin** [comment]
All the examples in the SR calculator have this error.

**Comment by robnagler** [comment]
@moellep did you ever figure this out?

**Comment by moellep** [comment]
This is the same template file which gave Pepe the error yesterday. I
wasn't able to reproduce it.

**Comment by mrakitin** [comment]
I understood the reason - AdBlock Plus causes this error. When I disable it in Firefox, there is no such error. In Chrome it works fine.

**Comment by elventear** [comment]
I use Adblock Plus. Maybe the name triggers a block?

**Comment by moellep** [comment]
Yes, that was it. I use AdBlock but wasn't getting the error until I
added the EasyPrivacy+EasyList filter. That filter has an entry for
"/heatmap.*?". I'll rename the file.

**Comment by mrakitin** [comment]
Good catch Paul!
