### ISSUE TITLE
3d plot changing as input typed in unrelated field

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4524]
In radia, if you type the letters 's', 'v', 'or 'w' in an input field (for example in the Max Iterations field), the Magnet View plot changes:

Type 's'  and the plot disappears. Type 'v' and it becomes dots. Type 'w' and it becomes wireframe:
![Screen Shot 2022-06-14 at 11 17 59 AM](https://user-images.githubusercontent.com/6516910/173637992-435d9075-1ea2-47c7-9aaa-c6a5575fab95.png)

This problem affects all apps with 3D plots, ex. warpvnd.

**Comment by moellep** [comment]
It looks like this is a vtk feature we'll have to disable. I notice typing w/v/s toggles between wireframe, points and solid on the vtk.js examples.

**Comment by mkeilman** [comment]
BTW my fixes were obviated last year - they used to have event listeners on the <body> but moved them to the [document](https://github.com/Kitware/vtk-js/commit/e96a6d3fe7910b5e2fa75b233fcf69895a1ccef9)
