### ISSUE TITLE
add standard materials

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4529]
Add a list of common materials, so the elements don't need to be entered by hand:

Concrete, Hanford Dry, density: 2.18
  H 0.004000
  O 0.482102
  Na 0.002168
  Mg 0.014094
  Al 0.069387
  Si 0.277549
  K 0.013010
  Ca 0.080229
  Fe 0.057461

Concrete, Los Alamos (MCNP), density: 2.25
  H 0.004530
  O 0.512600
  Na 0.015270
  Al 0.035550
  Si 0.360360
  Ca 0.057910
  Fe 0.013780

Concrete, Ordinary (NIST), density: 2.3
  H 0.022100
  C 0.002484
  O 0.574930
  Na 0.015208
  Mg 0.001266
  Al 0.019953
  Si 0.304627
  K 0.010045
  Ca 0.042951
  Fe 0.006435

Polyethylene, Borated, density: 1
  H 0.125355
  B 0.100000
  C 0.774645

Polyethylene, Non-borated, density: 0.93
  H 0.143716
  C 0.856284

Steel, Stainless 304, density: 8
  C 0.000400
  Si 0.005000
  P 0.000230
  S 0.000150
  Cr 0.190000
  Mn 0.010000
  Fe 0.701730
  Ni 0.092500

Steel, Stainless 316, density: 8
  C 0.000410
  Si 0.005070
  P 0.000230
  S 0.000150
  Cr 0.170000
  Mn 0.010140
  Fe 0.669000
  Ni 0.120000
  Mo 0.025000

**Comment by mkeilman** [comment]
Would the user then have a choice of "standard" and "custom" materials? Would the component selection be disabled?

**Comment by moellep** [comment]
How about if the Material dialog is opened, but no components have been assigned, there would be an option to select from a predefined list with "custom" as the default choice. If the user selects a predefined item from the list, the component list would auto-populate and the density would be set.
