### ISSUE TITLE
Hide client errors?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#453]
When I added the alerts, it was to surface problems. I don't know that we want to surface problems right now. We can hide the alerts except in dev mode or maybe just hide certain alerts. What do you think?

**Comment by mrakitin** [comment]
I agree.

**Comment by robnagler** [comment]
What I'm concerned about is javascript errors that may cause hangs, because
the app gets in a bad state and doesn't know how to recover (i.e. refresh
required).

What I think should happen is that all network related errors should be
caught, and if they fail, the app should continue but say "that something
is not avaialable".

Not sure how to solve this except that all code register an errorCallback
for the case where the state doesn't transition properly and would leave
the app waiting for input, eg. Start  Simulation will hang the app forever
if the call gets an exception.
