### ISSUE TITLE
SRW - use beams from SRW (srwl_uti_src.py)

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#454]
Currently the parameters of some beams differ from the ones stored in [sirepo/package_data/static/json/beams.json](https://github.com/radiasoft/sirepo/blob/master/sirepo/package_data/static/json/beams.json).
[](url)
Need to use predefined electron beams from a single source https://github.com/ochubar/SRW/blob/master/env/work/srw_python/srwl_uti_src.py.

Bound ticket - https://github.com/mrakitin/SRW/issues/11.

**Comment by mrakitin** [comment]
Paul (@moellep), I need your opinion on this request. The `static/json/beams.json` file is used in the following files:
```bash
20:17 $ grep beams.json * -r | grep -v '.pyc'
importer.py:        with open(str(static_json_dir + '/beams.json'), 'r') as f:
package_data/static/js/sirepo-components.js:                requestSender.loadAuxiliaryData('beams', '/static/json/beams.json');
template/srw.py:with open(str(_STATIC_FOLDER.join('json/beams.json'))) as f:
```
The last occurrence is associated with the `_PREDEFINED_BEAMS` variable, which is not used anywhere in the Python code:
```bash
20:23 $ grep _PREDEFINED_BEAMS * -r
template/srw.py:    _PREDEFINED_BEAMS = json.load(f)
```
so it's only used in `package_data/static/js/sirepo-components.js`.

What would be the best approach to get beams data from SRW? I have the `electronBeams` list in `env/work/srw_python/srwl_uti_src.py` (https://github.com/mrakitin/SRW/commit/ed44ae00a62f432fdb143fe771c79063cb9337fc). I plan to write the code to convert it to JSON acceptable by Sirepo. Where should I place this code? (`pkcli/srw.js`, `template/srw.js`, `server.py`?) How do I pass these dynamic values to the JS counterpart?

Also, we have a bunch of examples with the obsolete values of the electron beams, any suggestions how to update them?

Thanks! Of course, this will be merged after SOS2016.

**Comment by moellep** [comment]
I think srwl_uti_src.py could keep the beam definition in python, but add a utility method to get the full list. Then the javascript app could be changed to call getApplicationData({ method: 'electron_beams' }) and on the server, template/srw.py would get the beam list from srwl_uti_src.py and convert it to json for the response.

For examples with old beam definitions, I think the fixup_old_data() could look through the beam info and add/remove fields.

**Comment by mrakitin** [comment]
Thanks Paul! I'll try to implement it later.

**Comment by mrakitin** [comment]
Thanks for implementing it, @moellep!
