### ISSUE TITLE
ENOENT static/js/ext/html2canvas.js.map

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4545]
Seeing this on dev currently (25da7f41e)

```
../sirepo/uri_router.py:108:call_api api={'base_uri': 'static', 'cls': <class 'sirepo.server.API'>, 'decl_uri': '/static/*<path_info>', 'func': <function API.api_staticFile at 0x7f95e5375950>, 'func_name': 'api_staticFile', 'name': 'stat\
icFile', 'params': [{'is_optional': True, 'is_path_info': True, 'name': 'path_info'}]} exception=[Errno 2] unable to locate in packages=['sirepo']: 'static/js/ext/html2canvas.js.map' stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 100, in call_api
    r = flask.make_response(getattr(f.cls(), f.func_name)(**kwargs))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 551, in api_staticFile
    p = sirepo.resource.static(sirepo.util.safe_path(path_info))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/resource.py", line 64, in static
    return file_path(static_url(*paths))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/resource.py", line 27, in file_path
    packages=sirepo.feature_config.cfg().package_path,
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkresource.py", line 33, in file_path
    return pkio.py_path(filename(relative_filename, caller_context, packages))
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkresource.py", line 54, in filename
    _raise_no_file_found(a, relative_filename)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkresource.py", line 104, in _raise_no_file_found
    raise IOError(errno.ENOENT, msg, path)
FileNotFoundError: [Errno 2] unable to locate in packages=['sirepo']: 'static/js/ext/html2canvas.js.map'
```

**Comment by garsuga** [comment]
I cannot find any reference to the path `static/js/ext/html2canvas.js.map` where it ends in `.map`. It also does not appear like the other js files have source maps included with them in the source code. Is this an issue during the webpack process? @robnagler

**Comment by robnagler** [comment]
We do not webpack. We store the unminified and the minified versions. I see that html2canvas is the minified version, but it does not come with a map like it should. You can't reverse generate the map. You should download the unminified version and minify with, e.g. uglifyjs (npm), which will create a source map. Save all three files with the version number like bootstrap.

**Comment by garsuga** [comment]
Is that the minified version that is in the repo right now? I thought I grabbed the normal version and canvg was also the unminified version

**Comment by robnagler** [comment]
It is not minified. I don't know why the browser is asking for a map then. Maybe it always does. I actually don't think we are very consistent.

**Comment by e-carlin** [comment]
Looks like this is probably a ["feature" of Chrome](https://developer.chrome.com/docs/devtools/javascript/source-maps/#sourceurl_and_displayname). It seems I only get this error when i have the devtools open.

If I remove [this line](https://github.com/radiasoft/sirepo/blob/master/sirepo/package_data/static/js/ext/html2canvas.js#L7830) then the error goes away. The code isn't minified so that line can probably be removed. Why Chrome is reading comments is a question I'll save for another day...

**Comment by robnagler** [comment]
https://developer.chrome.com/blog/sourcemaps/#how-does-the-source-map-work explains the comment parsing. This is a favorite of language implementers which I abhorred in the 80s and still do....

> Python was raising this error though, right? 

Yes, because it is a not found on the source map so it shows up in the server logs. I don't think it breaks anything, but it is annoying to see.

We should probably filter not founds like this so they don't show up as stack traces. A task for when we are moved to Tornado.

**Comment by e-carlin** [comment]
Can we still at least remove that line? This will help reduce clutter in dev right now (both in dev tools and in server logs).

**Comment by robnagler** [comment]
Sure.
