### ISSUE TITLE
FLASH "Cap Laser 3D" example does not have proper problem files

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#4546]
Navigating to the "Cap Laser 3D" example on alpha brings me to the Setup tab per usual [deleted].

However, no files are extracted and no setup panel is produced. When I try to download the problem files I see the following error:

`{"state":"error","error":"Simulation library file \"problemFiles-archive.CapLaser3D.zip\" does not exist"}`

The couple other test problems I have explored did not result in the same issue (although I haven't tried every single one).

**Comment by moellep** [comment]
Adding to previous comment with a correct sim link: https://alpha.sirepo.com/flash#/setup/xt5mDbSv

**Comment by ncook882** [comment]
Thanks @moellep . I'll try uploading a new configuration and testing it out.
