### ISSUE TITLE
New version of SRW

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#455]
@robnagler, @moellep, we with @ochubar will have a new version of SRW uploaded to https://github.com/ochubar/SRW later today or early tomorrow, then I will test how it works with Sirepo. I'm sure I will have to rework srw jinja template, so that Sirepo processes new `ebm_*` variables correctly. We came up with the better solution of how to pass the Twiss parameters and moments directly to `.calc_all()` function, so that there will be no need in the "user-defined" beams and the related `v.ebm_ud*` parameters in the template.

If everything works fine after Oleg's and my tests, I'll update both Sirepo and SRW-light. Do you mind to rebuild alpha- and beta-servers after that by the end of Friday? I'll let you know when I'm done. Thanks.

**Comment by robnagler** [comment]
Let's build alpha first. See how it goes. We are down to the wire here...

**Comment by mrakitin** [comment]
Sounds good. New SRW will appear in about an hour. Then I'll check how it works with Sirepo and correct if necessary. I suppose I'll be ready by ~5 pm EST.

**Comment by mrakitin** [comment]
New version is synchronized with https://github.com/ochubar/SRW/commit/087ce511950156b7f499539eb45e36595c425b06 in https://github.com/radiasoft/SRW-light/commit/aabaa25533982482c37acae1afe756dca7fe9fdd. Starting testing/adapting Sirepo to be compatible with new SRW.

**Comment by mrakitin** [comment]
First issue - https://github.com/radiasoft/sirepo/issues/457

**Comment by mrakitin** [comment]
Fixed bending magnet example (#457).

**Comment by mrakitin** [comment]
Another issue with custom beam - #458.

**Comment by mrakitin** [comment]
Fixed custom electron beam (#458).

**Comment by mrakitin** [comment]
One more issue with importer - #460.

**Comment by mrakitin** [comment]
Fixed importer of SRW .py files (#460).

**Comment by mrakitin** [comment]
Starting revision with Oleg.

**Comment by mrakitin** [comment]
Hi Rob, we have tested the code, and it looks good so far. Could you please rebuild alpha with the new SRW-light? Thanks!

**Comment by mrakitin** [comment]
Paul released alpha - #462.

**Comment by mrakitin** [comment]
We would need to try it, and if everything goes well, it can be pushed to beta.

**Comment by mrakitin** [comment]
Alpha looks good for me, I checked all the basic examples. Please give it a try.

**Comment by mrakitin** [comment]
I will be testing alpha and our installation using the same container as on alpha during today's shift. After that if there is no issues, it can be pushed to beta. I'll give a note here later today.

**Comment by mrakitin** [comment]
I think it's ready to be pushed to beta. We have tested it during demonstration of Sirepo to ESM beamline scientists, and it worked smoothly.

**Comment by mrakitin** [comment]
Thanks @robnagler and @moellep for the assistance! Closing.
