### ISSUE TITLE
Release dates for apps

### ISSUE THREAD

**Issue by LexiJess** [radiasoft/sirepo#4563]
Wondering what dates (approximately) each app in Sirepo was released. Year of release is detailed enough for my nefarious purposes.

**Comment by robnagler** [comment]
@rorour this will be some archeology on feature_config to see when sim_types moved to PROD_FOSS_CODES. This name may have changed over the years so you might have to look at those changes. I think feature_config.py is the only file that would have this information.

**Comment by robnagler** [comment]
@LexiJess is this sufficient?
