### ISSUE TITLE
Need to run sirepo-ci image before alpha build

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4566]
Need to assert that sirepo-ci is based off the same beamsim that will be used for alpha.

Need to flesh out this issue.

**Comment by robnagler** [comment]
We are missing at least one action: [Run a build when a PR is merged](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges)

We should run sirepo tests after sirepo-ci is built. This is a reasonable sanity check. This requires a new installer to setup the environment properly. If the test fails, beamsim and sirepo-ci should not be pushed and local labels (dev) should get removed (or never assigned in the first place).

We don't know is if sirepo-ci was built after the last PR had CI run on it. This could be asserted in the build along with the last sirepo-ci build/test. 

We also need to fix sirepo/container-conf/build.sh not to run the tests.

**Comment by robnagler** [comment]
https://github.com/radiasoft/pykern/issues/234
https://github.com/radiasoft/download/issues/262

**Comment by e-carlin** [comment]
Is this needed so ci for PRs will run in a "new enough" environment? It seems to me that the real blocker will be that beamsim is up to date. To solve that why don't we do some ci for radiasoft/download?

**Comment by robnagler** [comment]
sirepo-ci-build installer builds beamsim and sirepo-ci and runs the tests before pushing them.

We are waiting on radiasoft/pykern#234 which will allow us to wrap it in update.sh

**Comment by robnagler** [comment]
I think we are ready to go with sirepo-ci-build. We will use radiasoft/pykern#234 to determine if the build should go through. 

To build beamsim, we would:

```sh
build_push=1 radia_run sirepo-ci-build
```

To build sirepo:

```sh
if not pykern github ci_check sirepo:
    err commit did not run tests successfully
build sirepo as we do now
```

We may need to make sure that the main commit sha of sirepo is "well ahead" of sirepo-ci. That's a finesse which is usually true so we may be able to do without this check.

**Comment by robnagler** [comment]
This is on production rsconf, and first alpha release is happening.
