### ISSUE TITLE
Creating a new simulation does not make .par file available (user-uploaded or interface-generated)

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#4573]
When loading a pre-configured simulation example, the `flash.par` file is available to view/download under the "Problem Files" panel:

![RTFlame_ProblemFiles](https://user-images.githubusercontent.com/11053323/176790623-548ff405-f4d8-4f89-90a0-55ef5431325e.png)

However, when creating a new simulation and uploading problem files, the `flash.par` file is not made accessible. Even following simulation setup + compilation and parameter tuning, no `flash.par` is added to the Problem Files. 

![CapLaser_UserDefinedProblemFiles](https://user-images.githubusercontent.com/11053323/176791235-8afcd1b6-fbda-4ff1-8937-da0edb2f8f25.png)

It is also not available when subsequently downloading the simulation `.zip` files. This creates obstacles to users creating and debugging new simulations.

**Comment by moellep** [comment]
I'll add an error message if the Config or flash.par are not present in the root of the uploaded zip file.
