### ISSUE TITLE
requestSender.sendStatefulCompute interface update

### ISSUE THREAD

**Issue by gurhar1133** [radiasoft/sirepo#4591]
The current interface is 
```javascript
requestSender.sendStatefulCompute(
        appState,
        callback,
        {
                method,
                 ...appState.models,
         }
);
```
The python side should be changed to support 
```javascript
requestSender.sendStatefulCompute(
        appState,
        callback,
        {
                method,
                appState.models,
         }
);
```

It's not good to assume that there is no model named "method", implicitly.

Related see discussion [here](https://github.com/radiasoft/sirepo/pull/4574)

**Comment by gurhar1133** [comment]
@robnagler 

1) Would this be the preferred interface:
```javascript
requestSender.sendStatefulCompute(
            appState,
            callback,
            {
                method: ...,
                args: {
                    ...
                }
            }
        );
```
?

2) stateless and stateful compute have the same interface. Should I change stateless as part of this issue as well?

**Comment by robnagler** [comment]
yes

**Comment by gurhar1133** [comment]
Is there a better way to test this than to just trigger each api call and see if it works?

**Comment by robnagler** [comment]
There's no good way to test this, unfortunately. This will require a careful review. We don't have GUI tests.
