### ISSUE TITLE
Move "sampling factor" to global

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#46]
Move the "Sampling Factor" value from the individual reports to a global value, available from the source page.

**Comment by bruhwile** [comment]
This should be combined with the issue of making the grid resolution available to users.

**Comment by bruhwile** [comment]
Initial solution will be a popup accessed from the cog wheel, named "Simulation Grid" or "Mesh" or something like that. We'll put the "Sampling Factor" here, even though logically it might belong somewhere else. Maybe there should be a toggle (automatic vs manual or something) to hide this detail from non-experts.
