### ISSUE TITLE
Provide more details for NERSC execution error: Not connected to cori.nersc.gov

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#4625]
Submitting a test simulation to Cori from the FLASH interface returns the error message "Not connected to cori.nersc.gov".

![Screen Shot 2022-07-20 at 10 30 12 AM](https://user-images.githubusercontent.com/11053323/180035117-9cf77a6d-08b7-47d0-837e-ad3f95890894.png)

**Comment by ncook882** [comment]
@e-carlin yes I think it would be useful to distinguish between NERSC being down and there being some other error in the connection. This would have benefits across any app that connects to NERSC or another external service.

**Comment by e-carlin** [comment]
I'm going to cleanup the messages with this issue. In a follow on issue (https://github.com/radiasoft/sirepo/issues/7041) I'll handle the specific case of down for maintenance. Need to wait for perlmutter to be down to figure out what the error is.
