### ISSUE TITLE
raydata to alpha

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4626]
This is a collection of all things needed to get raydata to alpha. It will be split up into subtasks as needed

- [ ]  get chx and csx working on all dev machines
- [ ]  integrate replay component into sirepo (user can upload a set of scans, twiddle params to have them replayed, run replay and see stream of data incoming in other panel)
- [ ] deploy to alpha

**Comment by e-carlin** [comment]
@rorour first thing is to get raydata working on your machine again. I believe we had it working at one point. You'll need to setup databroker with the scans to get it working. reach out when you're ready to work on this and we can figure it out. I'll try to get it setup on my machine in the next couple of days

**Comment by rorour** [comment]
Minor UI ideas:

1. On the Data Source tab, clicking 'Today' on the date picker could update time to the current time as well. Currently, it sets it to the current time if there is no time selected, but subsequent presses of 'Today' only update the date. Not sure if this is the desired behavior but I found this a mild inconvenience when developing if I generated new scans after the app was opened. Users could set the time several hours in the future to avoid this I suppose.
2. Also on the Data Source tab, a refresh/re-search button would be nice for the case when the time interval is set into the future and new scans have been generated. Or should the scans appear in the list automatically? Currently you have to change start or stop time to get the 'save changes' button which gets the new scans.

**Comment by e-carlin** [comment]
Raydata is on alpha.
