### ISSUE TITLE
admin tool to remove/restore corrupted simulations

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4632]
Many of the admin tasks will crash if it tries to open a corrupted (partially written, empty or invalid JSON) datafile. We could add a new utility which iterates all existing simulations, and if it finds a corrupted one, it checks for the most recent in.json file in a subdirectory and restores the data from that file. If no in.json is found, it should log the problem and delete the simulation directory.

**Comment by robnagler** [comment]
I would skip the in.json step. It could identify the files and output them, and we could look at them, or just check how old they are.

We should never have a corrupt sirepo-data.json from writing unless there is a bad fixup.

**Comment by gurhar1133** [comment]
And do we want this to handle all sims in db or all example sims in db?

**Comment by gurhar1133** [comment]
Did we decide this is non-issue?

**Comment by moellep** [comment]
Yes, I think we can close this issue.
