### ISSUE TITLE
Jspec in React

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4635]
Jspec will be the first React app. It's less used, and it's a simple code. React will use the existing Sirepo API. 

This is a "bundled" issue. The first step is to come up with a plan of action of how this will happen. 

This will be the third deliverable for Afcloud at the end of Sep.

Plan:
- [x] Animations
- [x] Writing back data to server with forms (already a WIP)
- [x] Simulation folder view like all apps have
- [x] Some editors have tabs within the panels
- [x] Simulation start panel, the one with the 'start simulation' button and simulation status
- [x] Panels need to dynamically show/enter the view when a simulation completes

**Comment by garsuga** [comment]
I have made a list of things we need for JSPEC that are not already in the MyApp version of react.

1. Animations
2. Writing back data to server with forms (already a WIP)
3. Simulation folder view like all apps have
4. Some editors have tabs within the panels
5. Simulation start panel, the one with the 'start simulation' button and simulation status
6. Panels need to dynamically show/enter the view when a simulation completes

**Comment by garsuga** [comment]
I can get started on the simulation folder view and getting the forms to send data back to the server for now since these are universal.

**Comment by robnagler** [comment]
Please break down into smaller issues so we can track them with PRs.
