### ISSUE TITLE
add `__srwl_logs__/*.log` to download for a simulation

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4648]
This is is similar to the run.log. The name of the log varies by the simulation so may need a specific api for this.

Here's where should be added:

![Screen Shot 2022-07-28 at 11 13 54 AM](https://user-images.githubusercontent.com/5495179/181597950-fc0a2163-95d4-40e2-a580-b5e45621a4d2.png)

I would could the current link "Download run log" and the new link "SRW internal log". Maybe @moellep has better suggestions.

**Comment by moellep** [comment]
How about "SRW run log file" and "SRW progress log file"? The links could be shown side by side in the UI.

The "SRW progress log file" show return the contents of the most recently updated *.log file in the __srwl_logs__ subdirectory.
