### ISSUE TITLE
raydata: should not be able to "start new poll" w/o supplying a value for minutes

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4658]

**Comment by rorour** [comment]
Do you want me to remove the button when there is no minutes supplied? There's already some error handling because it shows Error: 'PKDict' object has no attribute 'minutes' when polling is started without minutes

**Comment by e-carlin** [comment]
Yes, I think the button should be hidden (or grayed out) until the user enters a value for minutes
