### ISSUE TITLE
first LCLS II 500 eV example fails on source page

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#467]
In the LCLS directory, I see three examples with the same name, all containing 500 eV.

I opened the first one to this URL
https://beta.sirepo.com/srw#/source/JiH1vslq
and it immediately failed as follows:

![image](https://cloud.githubusercontent.com/assets/3825435/19023768/a1efd164-88b3-11e6-9770-714b14ddb30a.png)

**Comment by bruhwile** [comment]
If there isn't time to fix this issue on Monday, then maybe these three '500 eV' examples could be removed from beta?

The other two examples seem to run fine.

**Comment by moellep** [comment]
I think that may be a left-over from your previous testing. There only LCLS
beamlines examples are "LCLS SXR beamline" and "LCLS SXR beamline -
Simplified". You can delete the ones from your session from the simulations
page. If you want a fresh set of examples, you can clear your browser
cookies for beta.sirepo.com. That will clear out any other your other test
simulations though.

**Comment by bruhwile** [comment]
Thanks.
