### ISSUE TITLE
flower: drill down on worker fails

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#468]
Here's what I see:

<img width="439" alt="screen shot 2016-10-03 at 10 47 11 am" src="https://cloud.githubusercontent.com/assets/5495179/19031862/d009beae-8956-11e6-8a19-9e858b3b8be7.png">

**Comment by robnagler** [comment]
Tried what was recommended in mher/flower#438, but that still doesn't fix the problem. Looking at the code now.

**Comment by moellep** [comment]
Did you try stopping all processes and restarting, including rabbit?

**Comment by robnagler** [comment]
It's failing on my desktop. Only happens when I run Celery in a container. The log error is:

```txt
```

**Comment by Xepe** [comment]
I have the same issue. I did a clean installation, and I am using flower 0.9.1, I did the "inspect ping" and I got "pong"

**Comment by Xepe** [comment]
Hello, 

I reviewed my packages and I found that I was using kombu 3.0.36, I downgraded it to previous version 3.0.35 and with that I solved my issue. 

Hope this help you @robnagler

**Comment by robnagler** [comment]
Thanks @Xepe! That worked perfectly.
