### ISSUE TITLE
missing ML fixup for layer change

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4707]
I noticed my existing regression ML simulations have lost their layer Dimensionality. I think a fixup is missing if the schema changed.

Below is an example.

https://www.sirepo.com/ml#/regression/oFklRQMN

![Screen Shot 2022-08-10 at 3 57 59 PM](https://user-images.githubusercontent.com/6516910/184027720-152bc744-092b-4ef9-a081-ad6f5d64e5d7.png)

**Comment by gurhar1133** [comment]
@moellep I am having trouble reproducing this one, has it been fixed? if so, should i close it?

**Comment by moellep** [comment]
Try replacing the happiness.json example with a non-fixed-up (older) version here:

https://github.com/radiasoft/sirepo/blob/52e382d24b28f711ff6b04f2dff34736f3a8ce41/sirepo/package_data/template/ml/examples/happiness.json

Copy over the examples/happiness.json with that file and then select "Discard Changes to Example" to recreate it.
