### ISSUE TITLE
20221206 Eliminate nested dialogs

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#4711]
Editing objects can currently open dialogs nested several levels deep, which can be confusing. 
There are couple of side effects as well:
1. The screen darkens more with each successive level
2. The save/cancel buttons sometimes close only the most recent dialog, sometimes all of them

Here is a triply-nested example:
<img width="951" alt="Screen Shot 2022-08-11 at 11 06 00 AM" src="https://user-images.githubusercontent.com/30352290/184192504-dff9a047-2baa-4fd8-a1a5-58bdaa7704c6.png">

We should present a single dialog, perhaps moving what would be another level into a tab (the Shape button is a good candidate)

**Comment by moellep** [comment]
I think that is a great idea. Avoid dialogs on top of dialogs is a good goal. Moving Shape and Modifications into tabs on the Object panel would be start. Also removing the Bevel dialog by placing the items in a tabular editor would help, something similar to Layer editor in the Activait app:

From this:
![Screen Shot 2022-08-12 at 10 58 40 AM](https://user-images.githubusercontent.com/6516910/184407508-ef24bdcd-7f67-44ad-b253-78e51f4bec9a.png)

To an in-place editor like this:
![Screen Shot 2022-08-12 at 10 53 08 AM](https://user-images.githubusercontent.com/6516910/184407212-c7853756-9c96-432e-b234-8c3412924e77.png)
