### ISSUE TITLE
rename ml to activait

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#4712]
Pulling this out of #4406 - most of it is done but it should not wait on the image stuff.

**Comment by robnagler** [comment]
@mkeilman status?

**Comment by mkeilman** [comment]
> @mkeilman status?

I brought this up on the activait call yesterday. @moellep posed the question of whether to bother renaming everything or just change the url, if that's possible. I lean toward renaming for consistency's sake (also I presume there are essentially 0 uses of this in the wild). Any opinion on that? In any case this is waiting on #4723 so things don't shift underneath me

**Comment by robnagler** [comment]
I think it will be problematic if the module is template/ml.py and the url is /activait. However, I think it would also be good to decouple the two of these.
