### ISSUE TITLE
Recent docker images FileNotFoundError

### ISSUE THREAD

**Issue by AbbyGi** [radiasoft/sirepo#4749]
@mrakitin and I were trying to start up the beta Sirepo docker image locally and hit this error: `FileNotFoundError: [Errno 2] No such file or directory: '/react': '/react'`. We also noticed the [same issue](https://github.com/NSLS-II/sirepo-bluesky/runs/7959224606?check_suite_focus=true#step:8:81) in the CI for the sirepo-bluesky library we're working on. We had to switch back to the [20220806.215448 tag](https://registry.hub.docker.com/layers/sirepo/radiasoft/sirepo/20220806.215448/images/sha256-21563e7d2a8392f8d0cfa48b16aa0f1c7f0fa69e0933139cd5bbdfb69dbc763b?context=explore) to get the image to start up.

The problem is reproducible with this command: `docker run --rm -p 8000:8000 -v "$PWD:/sirepo" radiasoft/sirepo:beta` and here is the traceback:
```py
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main("sirepo")
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 148, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/service.py", line 120, in http
    extra_environ=PKDict(PORT=str(_cfg().react_port)),
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/service.py", line 102, in _start
    env=PKDict(os.environ).pkupdate(extra_environ),
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/react': '/react'
```

**Comment by robnagler** [comment]
This will go to production next Monday.

**Comment by mrakitin** [comment]
@robnagler, did it end up in the beta tag? I've just tried to run the `radiasoft/sirepo:beta`, but am still [observing the issue](https://github.com/mrakitin/sirepo-bluesky/actions/runs/3086283586/jobs/4990479578).

**Comment by mrakitin** [comment]
It's still an issue in the `prod` tag ([logs](https://github.com/mrakitin/sirepo-bluesky/actions/runs/3086311687/jobs/4990535161)).

**Comment by robnagler** [comment]
This just ran fine for me:

```sh
docker pull radiasoft/sirepo:prod
docker run --rm -p 8000:8000 -v "$PWD:/sirepo" radiasoft/sirepo:prod
```

The image id is 70ba8f3ea0b8, you can get the version here: 

```sh
docker run --rm radiasoft/sirepo:prod cat /rsmanifest.json | grep version | head -1
        "version": "20220913.162900"
```

**Comment by robnagler** [comment]
I see that there's a script that calls `sirepo service http`. It might be better to run something like: `bash -l -c '~/.radia-run/start'`. This will pick up the the environment variables required. You want this one to avoid the react problem:

```sh
export SIREPO_PKCLI_SERVICE_REACT_PORT=
```

And you probably want this:

```sh
export SIREPO_PKCLI_SERVICE_USE_RELOADER=false
```

If you just use `~/.radia-run/start`, it'll be more robust to config changes. I see you do override some vars, but maybe there's a way to be flexible about this in the config.

**Comment by mrakitin** [comment]
@robnagler, I got time to get around the issue. We updated our scripts to use the suggested approach of using `~/.radia-run/start` (https://github.com/NSLS-II/sirepo-bluesky/pull/113) with on-the-fly patching to update the `SIREPO_SRDB_ROOT` var.

I've encountered an error while using the deprecated API: https://github.com/radiasoft/sirepo/blob/c48c14f542f0ecf7223eeb1299137690452a6d55/sirepo/auth/bluesky.py#L64

I got the following error:
```py
# client side:
SirepoBlueskyClientException: bluesky-auth request failed, status: 500

# server side:
/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/sirepo/uri_router.py:325: RuntimeWarning: coroutine 'API.api_authBlueskyLogin' was never awaited
```

I think this code should include `await`:
```py
await self.api_authBlueskyLogin()
# or
return (await self.api_authBlueskyLogin())
```

Switching to the latest API `/auth-bluesky-login` helped to solve the issue.
