### ISSUE TITLE
add view rotation field to 3D plots

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4783]
The x/y/z plane buttons are very useful, but we don't allow viewing X at 90 degrees or X at 45 degrees. A CloudMC reviewer requested that a field be added to the main panel which allows rotating the current view by a variable degree. Currently, you need to control-mouse to rotate in that plane, and it isn't precise.

For example, if you were viewing the Fuel Pin example in X and wanted to see it at 90 degree rotation:

![Screen Shot 2022-08-31 at 9 59 46 AM](https://user-images.githubusercontent.com/6516910/187725631-852b912a-1bf8-4524-b8d5-0d48833b634d.png)

**Comment by mkeilman** [comment]
Is the intent to rotate around the axis pointing out of the screen?

**Comment by moellep** [comment]
Yes, the same rotation as if you control-moused on the layout. It is mainly useful when you are looking at a fixed x/y/z axis.
