### ISSUE TITLE
'Export Python Code' should open a file browser

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#479]
When choosing 'Export Python Code' from the cogwheel, the code appears in a new tab.
There have been multiple complaints about this behavior.

It is requested that instead a file browser should be opened, and a filename should be suggested to the user ... something like  my_simulation_name.py

**Comment by mrakitin** [comment]
Related to #463.

**Comment by bruhwile** [comment]
Thanks @mrakitin 
I elevated #463 to 1st priority.
Closing this issue.
