### ISSUE TITLE
Draw Source(s)

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#4791]
Request from a potential customer:

For a fixed source simulation, with [point,box] sources, It would be nice to have an indication of where the source is relative to the tally visualization. For Example, in the Aurora example, there should be a point labeled with the source to the right. Likewise, for a box source, a wire frame box would be a nice-to-have.

It's more difficult to indicate angle and energy. For a point source, a mono-directional source could have a dashed vector indicating the direction. A polar azimuthal source could show a dashed-line cone. But how do we indicate these things from a box? Or from a user-defined distribution?

I recommend we limit these visualizations to point source and box, and only draw angular information from the center of the box case.

- [ ] box source
- [ ] point source

We'll have to ponder how to display angle and energy without the plot getting too crowded...

**Comment by moellep** [comment]
Also see this repo which provides a way to render the openmc sources:

https://github.com/fusion-energy/openmc_source_plotter
