### ISSUE TITLE
two-dipole source

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#48]
There is interest at BNL and RadiaBeam in using the edge radiation from two consecutive bending magnets to diagnose the properties of an electron beam. This requires a new source type, where the single dipole is replaced by two dipoles with a drift space between them.

**Comment by bruhwile** [comment]
This has now been implemented in the Python/Qt UI for RadTrack.
That can be used as an example for the Sirepo implementation.

**Comment by mrakitin** [comment]
It seems related to #601.

**Comment by bruhwiler** [comment]
Nobody has asked for this in 4 1/2  years, so closing.
