### ISSUE TITLE
20220930 Convert oauth mockup to standalone html

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4801]
@LexiJess created [a mockup](https://github.com/radiasoft/sirepo/files/9508439/Sirepo_FLASH_OAuth_mockup.1.pdf) for the flash center's oauth page. We need to convert this into standalone HTML to hand to the flash center. The flash logo should be pulled from the flash site. You'll have to find the URL of that. They may be able to host it on the oauth server. The sirepo image can be pulled from our server but don't include the "by RadaiSoft", that is, just use the standard Sirepo logo and name.

The fields don't have to look pretty, but rounded corners are nice. You'll need to pull from the flash oauth form to see the field names and such.

Deadline 9/30/22

**Comment by LexiJess** [comment]
![FLASH-logo](https://user-images.githubusercontent.com/32692730/188971602-04a1a9d8-01e4-446e-934b-db8b063cfa1f.png)
![Sirepo-Logo-RGB-transparent](https://user-images.githubusercontent.com/32692730/188971650-f88dedb1-2368-4259-8a8e-4acbaa96c6e7.png)
Here are the logos, if that helps.

**Comment by LexiJess** [comment]
Other options for the Sirepo logo can be found in the [Drive](https://drive.google.com/drive/folders/1OYj79mDxHu_9DvZYrIlHFhzQQ5gV-Gmo?usp=sharing).

**Comment by rorour** [comment]
> You'll need to pull from the flash oauth form to see the field names and such.

@robnagler Where is this form located?

**Comment by robnagler** [comment]
The form is on Rochester's server. You'll need to sign up for flash and inspect the page.

**Comment by rorour** [comment]
[flash-oauth.html.zip](https://github.com/radiasoft/sirepo/files/9609895/flash-oauth.html.zip)
Zipped because Github doesn't allow attaching html

**Comment by robnagler** [comment]
@rorour thanks. I see that the mockup didn't have input hints. Please add placeholder values Email and Password for the two fields. Thanks.

**Comment by rorour** [comment]
[flash-oauth.zip](https://github.com/radiasoft/sirepo/files/9611547/flash-oauth.zip)

**Comment by robnagler** [comment]
Thanks @rorour!

**Comment by LexiJess** [comment]
Thanks, folks! Much appreciated!
