### ISSUE TITLE
20230228 switch nersc to perlmutter

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4803]
Prerequisite https://github.com/radiasoft/containers/issues/106

**Comment by robnagler** [comment]
SRW runs just fine on F36 on Perlmutter. I have not run it under Sirepo. I will do that now.

@e-carlin have you tested F36 on Cori? If not, we might just want to "big bang" this switch.

**Comment by e-carlin** [comment]
I haven't

**Comment by robnagler** [comment]
Fedora 36 Perlmutter SRW works with only minor changes:

<img width="785" alt="Screen Shot 2023-04-05 at 4 26 36 PM" src="https://user-images.githubusercontent.com/5495179/230225401-c358acd8-1297-48d9-9bb9-9b8f1c902e0f.png">
