### ISSUE TITLE
cloudmc colormap and voxel changes should apply after save

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4822]
When editing a plot in CloudMC, the plot is re-rendering as the color map and voxel inset values are changed. The render should only use the new values when the "Save Changes" is selected. The 3d plot should use appState.applicationState() (saved values) rather than appState.models (non-saved values).

**Comment by mkeilman** [comment]
That was on purpose, so the user can see what it looks like live. Based on your comment about the time to build voxels,  I agree that can wait until save. I like seeing the color change right away though. However I see the voxels being rebuilt after saving only a color change, which is unnecessary - I will work on that as well.

**Comment by mkeilman** [comment]
@moellep can you confirm this can be closed? I'm not sure when the fix went in, but I see the color changing live and the voxel inset changing after save.

**Comment by moellep** [comment]
It looks like anytime you change the colormap, it automatically saves the form data, so if you change the alpha, followed by the colormap, and then select Cancel, it doesn't revert changes because it was already saved.

**Comment by moellep** [comment]
No, I was wrong, it does revert OK when you cancel. It is odd that there is a save-changes call immediately after you change the colormap, so something is being saved.

**Comment by mkeilman** [comment]
If you mean
```javascript
function setTallyColors() {
    appState.models.tallyReport.colorMap = appState.models.voxels.colorMap;
    appState.saveChanges('tallyReport');
...
```
that can be removed - the heatmap and the voxels use the same field.

**Comment by moellep** [comment]
I think this issue has been resolved.
