### ISSUE TITLE
20220916 end_api_call should be save_cookie

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4825]
The event end_api_call should be moved to save_cookie. An API can call another API, and an API can be called from a pkcli. The only time end_api_call is used is to update the cookie.

**Comment by e-carlin** [comment]
It is used to update the session too https://github.com/radiasoft/sirepo/blob/b2acdebf16b727913374c4711da91dae3ff41682/sirepo/session.py#L71

**Comment by robnagler** [comment]
save_cookie could be "end_request", which is equivalent. You would only save on non-errors.

**Comment by robnagler** [comment]
I changed this so cookie registers for end_api_call.
