### ISSUE TITLE
Remove job_supervisor._AgentMsg.check_origin

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4826]
[check_origin](https://github.com/radiasoft/sirepo/blob/b2acdebf16b727913374c4711da91dae3ff41682/sirepo/pkcli/job_supervisor.py#L84) always returns true. It seems like this is not necessary, since the Origin header is not necessarily sent? Has this been tested?

**Comment by e-carlin** [comment]
https://www.tornadoweb.org/en/stable/websocket.html#tornado.websocket.WebSocketHandler.check_origin
> This method is not called for clients that do not send this header; such requests are always allowed (because all browsers that implement WebSockets support this header, and non-browser clients do not have the same cross-site security concerns).

The origin header is most likely not sent. I've never tested.

**Comment by robnagler** [comment]
I think we should remove it and rely on tornado to do the right thing.
