### ISSUE TITLE
20221130 Should all send_file responses be conditional?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4830]
static_file is conditional but not favicon.ico. Would it matter if all responses were conditional?

**Comment by robnagler** [comment]
@moellep any thoughts on this?

**Comment by robnagler** [comment]
Simplifying the APIs. I think we can always send conditionally, but I don't understand why we are sending conditionally in some places and not others.

**Comment by moellep** [comment]
What is a case where we send unconditionally vs conditionally? And what is conditional sending?

**Comment by robnagler** [comment]
Setting `conditional=true` on a flask response enables [conditional requets](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests), otherwise the whole file is sent. If the response is large, it can be resent.

I went ahead and made the change to [conditional=true everywhere](https://github.com/radiasoft/sirepo/commit/6f029a942cf28bf62784788d24fdd4a391252f26#diff-eed34e40f3132ccc89adffc5fc7321e438a31109808d9ba64bbe5ed30d7bafbeR814). Here's what was the code was before that commit:

Weren't conditional:
- https://github.com/radiasoft/sirepo/blob/7c46c0e17735401cbf8a7e4f44a6a3c7eced63b3/sirepo/server.py#L188
- https://github.com/radiasoft/sirepo/blob/7c46c0e17735401cbf8a7e4f44a6a3c7eced63b3/sirepo/server.py#L778

conditional=true:
- https://github.com/radiasoft/sirepo/blob/7c46c0e17735401cbf8a7e4f44a6a3c7eced63b3/sirepo/server.py#L590

**Comment by moellep** [comment]
That sounds fine. I don't think it was intentionally left off on those cases.

**Comment by robnagler** [comment]
Fixed 7c46c0e
