### ISSUE TITLE
3d axes not showing correct width

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4834]
The 3d axes look off by a small factor. The cube below has the dimensions 6.5 x 7.0 m in x and z, but the axes show it closer to 7.5 x 8.

![Screen Shot 2022-09-13 at 11 05 41 AM](https://user-images.githubusercontent.com/6516910/189963502-d8129c52-0746-4d47-9a20-7ce82137b75b.png)

To reproduce, run a cloudmc simulation with a tally mesh of 1x1x1.

**Comment by mkeilman** [comment]
I'll wait for #4719 but there are likely two sources, alone or in combination:
1. There is configurable padding between the object and the axes (2% right now)
2. The d3 axes are "niced" which can make them deceptive as a measuring tool

**Comment by mkeilman** [comment]
@moellep can you confirm that the "de-nicing" has fixed this issue to your satisfaction?

**Comment by moellep** [comment]
Yes, de-nicing fixed the problem.
