### ISSUE TITLE
20220924 conftest needs a configured port                                    

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4836]
This is for devbox environments. conftest has a hardwired port. I suggest adding SIREPO_CONFTEST_PORT and have conftest create all ports based off of this (+1, +2, etc.).

**Comment by mkeilman** [comment]
Can I confirm that this is in `_subprocess_start()`?

**Comment by robnagler** [comment]
There may be other places. Understand all the port numbering, but I think it will all be in conftest.py.
