### ISSUE TITLE
20221115 set_cookie samesite=Strict

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4839]
sirepo.cookie should set samesite=strict There's a [note by @moellep](https://github.com/radiasoft/sirepo/blob/b2acdebf16b727913374c4711da91dae3ff41682/sirepo/cookie.py#L151) saying that is breaks self-extracting simulations. I don't know this is a feature users actually use. If we set it to strict for production, would that be ok?

see also #2596

**Comment by moellep** [comment]
I think we should remove the "self-extracting simulation" feature and use strict cookies.

**Comment by robnagler** [comment]
Let's figure out how many times it has been used. I'll create a task
