### ISSUE TITLE
Tooltip over point values

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#484]
When you have a point value in a graph, the numbers should have tooltips. It's not clear what the values are.

**Comment by mrakitin** [comment]
Do you mean [X=..., Y=...]?

**Comment by robnagler** [comment]
The numbers at the top should have a tool tip when you hover over them for some time. Oleg has some trouble in the talks remember which number was which:

<img width="317" alt="screen shot 2016-10-07 at 12 04 29 am" src="https://cloud.githubusercontent.com/assets/5495179/19172343/b7104576-8c21-11e6-8708-21999d2bb014.png">

**Comment by mrakitin** [comment]
Thanks for the explanation Rob. It's a reasonable request and should be relatively easy to implement (I hope).

**Comment by mrakitin** [comment]
I'll have a look at it within #544.

**Comment by mrakitin** [comment]
@moellep, I tried to do something similar to http://getbootstrap.com/javascript/#tooltips, but it did not work for the `<text></text>` element. Could you please implement it?

**Comment by moellep** [comment]
It looks like the values are now more explicitly, ex. "X=12600.440, Y=1.013e+16, FWHM=10.613 eV" so I don't think a tooltip is required.

If you do need to add a tooltip to an SVG element, you can do this by adding a "title" child element  to the text element. See lattice.html for a static example, or use d3.select(...).append('title').text('tooltip text')
