### ISSUE TITLE
Avoid blank pages when switching apps

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#485]
When you click on a simulation in the calculator, the page switch results in a blank page. If there's latency (we're in Trieste), it stays up for a couple of seconds.

**Comment by moellep** [comment]
A good way to simulate this is Firefox's built-in Responsive Design Mode:

https://blog.nightly.mozilla.org/2016/11/07/simulate-slow-connections-with-the-network-throttling-tool/

I found I could reproduce the problem by selecting "Amazon Kindle Fire" along with "Regular 2G" settings. Rather than showing a blank page, a "page loading" or similar animation would be nice. It shouldn't show up if the app is loading quickly (wait a few seconds or something similar).

Possibly something similar to http://pathgather.github.io/please-wait/ would be useful.

**Comment by mrakitin** [comment]
Good idea Paul.

**Comment by mkeilman** [comment]
I've pushed an initial try on this to my branch; I don't think worth a pull request yet. Some notes:

I placed a script reference to a new file into the header of index.html, so it gets loaded early. I don't know whether it's better to put the code in directly to avoid a file fetch, or whether it needs to be "minified"

Other than an initial call in the html (so we don't wait for all the angular stuff to load), the show/hide lives in one spot in the nav controller. It has covered every case I've seen, but asynch has tricked me before...

FYI Chrome can also throttle network speed, under its developer tools

I took the liberty of whipping up a quick animated gif of the sirepo logo, just as a demo

**Comment by moellep** [comment]
I like it - and it isn't much code which is good. One thing would be to get rid of the global values and instead put them on the SIREPO variable, something like this:

```
// sirepo-pageLoad.js
SIREPO.pageLoader = function() {
    var pageLoaderTimeout = null;
    var showPageLoader = function () {
        var pageLoader = document.getElementsByClassName('sr-page-load')[0];
        if (pageLoaderTimeout) {
            return;
        }
        console.log('starting timer to show page loader');
        pageLoaderTimeout = setTimeout(function () {
            pageLoader.style.display = 'block';
        }, 1000);
    };
    var hidePageLoader = function () {
        clearTimeout(pageLoaderTimeout);
        pageLoaderTimeout = null;
        var pageLoader = document.getElementsByClassName('sr-page-load')[0];
        pageLoader.style.display = 'none';
    };
    return {
        'show': showPageLoader,
        'hide': hidePageLoader,
    };
}();
```

Then the code in sirepo.js can be simplified to:
```
    $scope.$on('$locationChangeStart', SIREPO.pageLoader.show);
    $scope.$on('$viewContentLoaded', SIREPO.pageLoader.hide);
```

For this to work, the `var SIREPO` value would need to get moved up into the html head in index.html

**Comment by robnagler** [comment]
It would be nice to put all of it in index.html including a data url for the gif. I know it may seem silly, but there are three extra files to be pulled, and if the goal is to show a nice pic while loading, better to get that all in the initial pull. It doesn't need to be minified per se, but shouldn't be full of comments.

**Comment by robnagler** [comment]
I'd argue this would be a general tool so it should be a separate global.

**Comment by mkeilman** [comment]
For context, this is the image tag using a data url (base64 string is about 9k):

`
      <img class="sr-page-load-image"
           src="data:image/gif;charset=utf-8;base64,R0lGODdhMAAwANUAAAAAAAAAVQAAfwAqfwAzZgA4jQA/fwBDhgBFiwBLhwBMfwBNjQBOkgFQk39/
AGaZM3+fP1WqAHGqOH+qKn+sP3WwOn+0NH61P222JIS3PXO5Lne7M3i7NX+7PIS8PoW8N4a/Qf//
/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQJ
CgAiACwAAAAAMAAwAAAG80CRcEgsGo/IpHLJbDqZoCjoSWV6pCBPdXu8Yo8MRqMR5iqxUaN4zGaY
k+jimt1+YrXItJzOJzfRU1RzfX5QgFSEfG5LgIFOiXSLZ2h4j5BjTV5RlU6DfZJWWVueim+CiaCm
TWGRqapOC2Gur2YetrRbmlJGtqK4Q42+QpS/w8F4jcXBuyLBv8t6jZyq0IHJv7qHxlLTr8ucXt3e
zsVL2eLlSFfp7NjooabZVNpV5KH0TtB/0vPL+9eZoL0Dxs/IJoP6GAEk+IVIQnMLmy3Mxi3fnSIU
mW2LQyujniHycHl01I4hoIHljpXkFXGlSZQuY8YMAgAh+QQJCgAiACwBAAIALgAsAAAG6UCRcEgs
GkUekPLIbDqPyuhzSi1GpdWqx3ldFhngcLbLJH8b6DSD2gVtj8k3kZGuN9bPNigrotvreE16fH5/
aIFlbXyGdohQV3wijIBTbnJZhYyOkU+Zf5ucTp6NoYSapZFggKBCHpeoc3SsSFevsFNJZrdGua5D
era3gyJ6e7u/xcTDx8VRuZDHQs1Lz8Gw08bRj83aTM9t1t3c3YLg5FzQULnnebqhvlXJnIqV8mPL
3uPx+onm9/b93A1xZQtbO3rI3BmshyUhQmUAQ/GbJmwivlIUiXQJx4cfEY6cvqVjp/EhSY29bgUB
ACH5BAkKACIALAEAAgAuACwAAAboQJFwSCwahx4Q6MhsOplKpedJNU6byeiyWs2CrlbtlusUf6FR
MJHBZpDNY2PUyG7YG+wqnCxk3P94VHtkfoB/bk9ifCKFhnaIT1mLIo6Ak3yVh5dcmXeQm06Njp+g
TaKGpGmla5Wpiqt9qEVwcaVtbXKDsFReWrt6ur+9ccO/SHBqScZDtErLaM3PudHSRM3O1czX2ce0
Ydi71NpaaqVm5d7Gc9Ni5W+1Zenvr4nIfOJN8lzb9b7f8MPoOUniwV3AONfgLdJ3cN2mhmMSloJo
Td8lfkIOuluIT0i7cMG4eRQoEknBjZOCAAAh+QQJCgAiACwBAAIALgAsAAAG6ECRcEgsGosez3HJ
bDJBUKVzSoRCn9YrdZrVGrugrdMDXpKtUvESDEoXs8sFQy0q0xmMhh4vPkfveoF7c1RnblQLgoqE
dGp5ioKMjVSQi5Nbj5WBSEmXRZmaDVVwnkOhe0NspUKgkIRsYatymoywq6ytDXypdrcieINGfla+
Yl3FyLeGyVPDxMxHzs/Qb7Cx1Ly22ELSx9xZh5fdpHVd4ZPW17DndOnZvaXaQuvFw4f0jUnXzart
5lvwALJhF61NwT/V5Hnq944huoGjrMVTmI4gP4ruFmJU+NChiG7KPM4bVu/ftoLJggAAIfkECQoA
IgAsAgADACwAKgAABt9AkXBIFIGOoKISqWw6iR7k8SlNPq/E6lQZlWK/Rq2zCsZqrUtv+dllUrfr
a9QTJzLu+LpedG/4/wx7a31/hYGCXwyFiw2HaohCioyGYY+IkpN+DGd0kJiZm1qdl5mAZ2ikpQxt
bpB8qkKso66fgIexs66Rn3e6ZXi3vsLDxHtVucWxp1ldw6dWZ76sYpy6z0fTrYjZ19qC3c/W19zI
xsuVlq7ZUEjlX6xLHu5vIO7Z82ViRc/4ZtFZ4fZwg9Pt26lRA+HUuTYkIao4CQGeM6ev4cFtorhk
dJWuSJd+QoIAACH5BAkKACIALAEAAgAuACwAAAbuQJFwSCyCjp6icslsKo9QkHNKXUaRTVCyyr0e
mdEt1+mVPq/jqReMTpOxTE/bTSfKv+lofS9c8913c39CDIUMDUqBeoMihQ2Pj4V2ZYwLh5CYDERe
YnyXmJibgnufoJCak2aDpaYNqIxLrKavsEWyoLS1RK2ZurG8rr5Mt5JDUMKNuK+KWsiGtMx4yIll
ndN91bXMRmWqf92ilIPRx8ZX1nvd0tjljOrN1yLkUOjC7/Vn8HnqVNlLch6sdcMXbpQ8P+YM5uNU
cJSWdU7meXv3jZ8Qid7oUGQHriLCgxY9tksobhCSevMI+vIXr6GbIAAh+QQJCgAiACwAAAEAMAAu
AAAG9ECRcEgsFkEej3HJbDqJoGj0Sa0apVirloqVbr/M7hRMHoqVSySojGx2w9mtuImGx6ueM3lu
zXfrW35jVmKDX36AXIVljHyMZYKPkpNLDJYMC5Rblg2dnQyaVQyepA2goU2jpaSnqEaqq59EkaGw
saZCjpO3rCKFa5S2sQyCb8G8nb6/mgvIoMV3k8Kercu1wq0i0MCul5ZpXq7iX1GJ40vQ5ue5hepM
gu5Ov4byulXz9OB6WvjcbtaE8D3ZFm4WFkD44gkhSK+dmXn3ACpb9HDfE4gLBVYsF0gXw3yM8iRJ
1G8dFI0m2TlMqdJeynQs0SV5FAQAIfkECQoAIgAsAAABADAALgAABupAkXBILBqFnuRxyWw2PaAo
yEmtGqVYq5aKlW6rUJBn2Y1+neVjeXpmlsfGsLm9lGfrTuV2zT7ftWttaYBddHZ9hHCChXSNIn+O
kZKTlJVFdpZWh4iVDJ4MV2+Wng2lDZ5DfJyODKaup0Kqna+uoJtzkq20pqCPgZO6u6W9g5PCtalh
o8fDmUbBws7PzA3S07u91kXQw9mhXsCfqHW/2kV8ioSQTaqraOVPslq3uG7yVu1U9JyMQ/tiXOCh
89cunb1193zx2ZKE079UCem0Q7RQ0kQimwwaUqUxiZ5JBc0RiSjykEaRsT46CgIAIfkECQoAIgAs
AQACAC4ALAAABuRAkXBIJHpAIE9xyWw6l0ck0hkFPa9LqZZZnWKxXSlTK/4+yeUiWmk+o8dkdrsZ
ppPnWKQc7sX7/01bgH9oSYN4hVaHbYmKi0JpQ2FSe4d3aoWPQ29EiZqQl52hmqOiHpWkfZ+rrK2u
r3+nqJoMDHZas3+1DbwNtaJrj7u9vbagmYsMxMvGjcnLzCKTkbrQy8ecg9bRzofbxM3Zg8rfxtiO
h+Tb5lenhnPq0WDiRlVE8by/7Z6Y2cP6ebqdwzVoWqRG6BAhlLQQEEJHBvUMaiiNIqFEeyxepGcw
15w4fErBEtKlTRAAIfkECQoAIgAsAgABACwALgAABuRAkXBILBpBSJBxyWw2k0mndEr0QJEeqvZ5
RW6/xa4XbLQms0UzFE0eipXp9VLN5naZVnvU+a5T1Xt6V2BiUm9kgGNNiYpfgH5Ld20iZo4gkJOZ
mpucnZ6XHpiecYOjgoGmoCJvcKmspZ6MrK6vZ6ara4e3triwt2Vqv8LDxIuZDAwNyshTiWTJytEN
DHyFW9DS0dRzfdfZ2dths1QL3+CRrKJF2ObK6N1VqOzt79ZCuvPf4USvQ7KXQvJJ28fPXi9rApc5
cVYQnkCCTACSgicCmTaIX2pBYsapHzGPH7uoM/WITBAAIfkECQoAIgAsAgABACwALgAABulAkXBI
LIpASI/HyGw6m8goaPmsWoVSqVNJvTqz2iLY+wUjjWYy03wmetJqMZzIjhvf0u6wbg3LlWV+T3Nq
eCBXfHZkbG2KiIyOXoZjkVaTeZV0UXqJmYRgepWER0mZclmmj5ipfYKsg1N3sa9Vl4e0a2ahuIy3
uHuMu6+9vr+9wqzHrHinlKaTbqOiqEOXtFnITNmqjVXYTgzhDLmz3tIMDenpDAuRwUTo6urhisRD
8fLz9b1D+f7jceyJwOdvnR2BBAsCDAhpYEF5C9U0dPhQnSNbRRJCzMSFSbiHEX99zBfylxBx9K4E
AQAh+QQJCgAiACwCAAEALAAuAAAG50CRcEgsGokekBJ0bDqHII9zSX1aoVSmMbu8PrnKYhLsbYLD
xLO2XFSvRWr29ixNk+X2s5iL39/nUX1GY1mCVV5UHnV4fIKMf3BLi455iUKEh5RYWXVxmkJgUm6T
lJygbp9DimiRnqlHbm+vSK6zgI22sLi5uqy8v2VdwGaZw5vFu59/mEqkpY1qzoLMnbWahHXMpsCx
0q+xxq2QDOQMs9rC5A3r6+ap2nUM7PMN7m3CXqtv8vTs9qfF8PDr1+5eQDkDCdar5AuPwnn/xHnz
kpBgxEifKvYbphGisY4Lw2m8CKxcuU9BAAAh+QQJCgAiACwBAAIALgAsAAAG6ECRcEgsGj2gJMjI
bDqfyqjnSa0SkVGldfvEZpPccPGrnIqZWfOQnFSf12QiG+QWecHUu1Qe56epc0t+WmN9TYGCV3hF
eoRNjXtbc4CTXJCJh5VcZHVohmFfkpFvInRnHp2kqqubqaxVX66vRpqzQlhml5izeqVzsm+In6y6
tazCw8exxq+9dmy2iqZwo9F5qNakDNsL2VTbDeEN295MDOLo4+VE5+noDKfT3+7vYnfAIvTpYY1P
7frhQIVy8g+gwCzzAMI72CahvoV8nNyxUrDeoF2rKqorFCUauHEQL+LLdm+dk45vggAAIfkECQoA
IgAsAQACAC4ALAAABuxAkXBILApBSKRxyWw2Pcmoc0olQqNJz9JzrVKxWCPY6wRHtUMziMxUJ9Nu
ttiNFrnXcuJdH68ioUV9QldmX2N8Z3OHToRhVlB1RY1vU3tyhFWTjnlkmomcXp6UoIhKpYukdqh0
qUdqp6Opgq5ZrUOitplmkblNu0QMwQy9Vlh1wQ3JycPEtMAMytHMzUbQ0dLURdbX0dnA3NfT2dvg
DeLU5ODnoH/a5crreZNE7+a2mt/qC7a/Q8jS8fL0oycsICdNvLzBkaKwTSw/7RouQRXooaxPiiyy
2wQLzz2GGTWSAsQEn8SKtU5KErkkCAAh+QQJCgAiACwBAAIALgAsAAAG6kCRcEgsGosekNJzbDqJ
S6dyGn1ahUkqyKilXq1ZLXPY1X6lZSU5rT4bw+U12/1mb4X2O12ehqbHe3h2fnGBhIV8U0heX3BT
gEWPi2ZfXZCVfUQMmw2bSJdnc0MMDaWmnoaHXUKkpq6dqYlUTK2vp7FYmbW2pQy4jooiu7y+uIjD
tsW4IiBJRcivystH0K7TVtWw10/Q0ttNu6jfzB6grOLfwONWZebrzJnvkfHyssHzetPAbarfiLLj
KE26V48Lo4J1+CF8d3AhwG1hmuy75ujIxGn/BK3CuFEVwVgZNX4EKfBNuXz6RhoKAgAh+QQJCgAi
ACwCAAEALAAuAAAG6ECRcEgsDj2gJMhjbDqfTaRSCa1ahdMs88o1ZrNdKINhlH6p4eK4wR4fz8ot
EXllsO9toflc1IrxgGQicElEcE52gHiCe1NyhCBNiYp3godDkE2UgYZJcnqZRpuLV41gRpObC1yh
aqMNgqVwn0SpnF2XiJSxuI5Wa228abRpxcbHyMlXccTKT3wiZs5eZ43Tc5Cn19na09xo11iHHnTh
mNDmTV/N6Xrkke3x8vP0ZUthnshfVnvsVdX//KTJ5QQdK4LqBHYxVQjKvoLsECbMZy8OtYfITBHr
50xiO4b1oq0LOahbvSnIggAAIfkECQoAIgAsAwACACoALAAABuFAkXBIZBiNxKTHA1omn9ChsUGl
IolMkHYb7QoZ1XDjKtyam94oWFxlDM9nTzq5ZrfLcPO8aA+7RXl6e199d4CBWoOEhWN4gXKKdX1E
iIpShX+OZ5ZSkoZJm5SCXQuemXuVXkdkg6mce1l5cqOvoIh5tU+3cJC5b7uhvr+Bh4nCorhlvcfD
W8vMXUzP0NTV1tfQWkzYULzczaPS1bFwxcbMwMHC6bS+7FzZuOTnx/NoIuTX7d/8WU7H8LqVc2dm
mjlnuZJhIVaLIbh9rRQKsUfPksSH9xqqG2IPYMAnS7TNCQIAIfkECQoAIgAsAQAAAC4AMAAABuxA
kXBILBIZSKNyyWyKGI1olOGsWoVQqZR67Rqz2q13LFqEz1yyFXyeFkFwj7rIbqc98DxIPn+2tVx4
enl9fn9uIoN6fHN1gEKCinBXk3SHXJJ6VouWaEOZhE6KX0gNSAtvoFWRlV6sg1WDjF6ZlKFqo4W6
u7y9ZJy+Tq+twUbDccVKoCDJRst8ebO8z4mwvs/DwceTw9K6mXKSyeJCucUegs63zezt7uyv70S1
8tveSuh7uKrC1rTgsczZosfk2Bh7osilWldO0T11wOYJbKhpk79PBImgO5gO4kR2/N5tk0exIslq
0U5iZDYnCAAh+QQJCgAiACwBAAAALgAwAAAG7kCRcEgsGkWM5HHJbB6TjWjUSa0KGdKs0sotYrPa
rvgKBjPG3G9ZekZX1etG2+2Er+dCj2cM6nvjbEN9gyBchIVEdmZCh4N7Th6Hf3FtkY1+kJJeinOX
jlSaRlBJeJ59j04gkWimqnRWraivTa2zsJeytk2Wg7pier7BRITCVY3FjKeovL3CzM3PrsGee9HC
tSLMubOxyZjTptvFrYjIgqbmRtTpRZ7sR5ar727E8+2hv/WgjeKpx/v/DLnzF/DWQCbWxIQD2KwI
M3XrqsiDiE8EOm4HvVVklTFbQToR20Xqx6cju0v2hjxLeY8klyAAIfkECQoAIgAsAgABACwALgAA
BudAkXBILBqFjKTyyGw6h4yGdMp4Wq3RqbZ67Raz2q13LAqbuWSix2MEm6XotAdEB33f4fSwXie6
33FkfHR3eA2BY4N2foZxdGtefEd/VEJzg2x6hVRcinWZmn5Le56EoValfadNl6mrrKkgmXygq7GW
mK8irYpCnrq7iqC/wL2kg8CoksnKi8zPgqrQRsTTx8bWIqm1z7HO0N6kkLrh2sivvLnppraluNjt
ucHwq7xE7tnX7GNry83cXTwBlCOtSKmBkeTpO6cH35B1BaNVM+cwzUGDFSUq9DXRYkeO/kJ9fPgt
nixdQQAAIfkECQoAIgAsAgABACwALgAABuNAkXBILBqPDMZxyWwWk41o0kmtMqJYqbLaBIGQ2fCW
e/R6jddwdkwems1FtbhdfJ+HaTmWTrR/8XpZfH1wcYENbINMeXKJikiMa49WkYhFHksgHpiDUIhj
Hn6EhZNufnenpaapIqylp2+toqqwcKF2qrK1QreauSK9rr9EwXacw3WwyJnGy02bx87S09RMscjN
q6S0rMW+3KeYyqXeseOTtWfeueWFwdGP7Xe8f7/p1e1c33zrVMVL/y7NoyKM3ixFsODtQhiO2MJB
D4FFpBNRHrqD2nA9wjik3C94ya5Vu9QmCAAh+QQJCgAiACwBAAIALgAsAAAG60CRcEgsGo8MRqOR
ZByf0KEH5Hkql1hmdEsEeanGaxbr5G6/3uJ4XTY/p+iieL1su41okJyetd+LX2F8ZH+Fc3R+hVuH
Y4lPXlWGg454X5F/jFpceWCGYklEHpeAeaOYfpyVaKaKQ5xpXXmtR3Ccpquzqq+5brWvrLxGvrvB
Z6+wxVHHyMlQx81mpdB3U0e408ay2M6p09XCxMndsdrFz+RxxcOWRbXArct6wtDr6dtS8fek55uB
hfn97NFixU9ZuFDlhPh6166gkF/BACo8xjCaw2UVLY57uCzYOl3SzPlreFDfxJAmEQrkEgQAIfkE
CQoAIgAsAQACAC4ALAAABu1AkXBILA5BHiOR0WA4ldAoEUQFKZ2NbPYp7R6r1CJWS2Z4veDwksw2
n6We9JpNf0vBYnrbzhcy9VpuXR6EfX+ATYNydoeAglBpVnyNe12Rkox6XHeRfSKUm5x4nn5Oj4VR
YEmkSpGrrHyXarBncbK0b7JVuGi6mLyQvsCil6+ow0K2l8mLyMqLy8giz0hCt9LJr9bR2K3c3Uad
znHaRaPA1LPgU8XrROm77tuy5d2+v8HxscLE+rm6ir5NOcasXb9zX1S9c9VLID12VAhGgYcPIC6D
BQWySlOOIj5YtvKJkyfCIsmSI09Oq1LPSxAAIfkECQoAIgAsAQACAC4ALAAABudAkXBILBJBSKNy
yWwKkdAlg9FoTJ3YIzRJnFa/1mx2yx1SwV+G2OnZFs/o9LrZ9hjjaLXTPYfjq2xkfX9ge2Qgc4RV
ekttZHZrfnGMS4eIkYSUlYJzIpKLmo2OnWZ+oaSkV6irTFuQrJ2Wl7BjsrRZjpavt5uyiLmzvCK+
SMBlvMautsLEvsJPtsvPlkLJz0SOHrvAu9d03d7hbKPirY/lRs61q8RY57G+4EXUc81NsvLm+Pe6
SnXBw9TpO1TE2pB2dPppITgkGcBefBpKq+ZKjLF0+4Tli4fuYMaODh+Wo9dx4bE5QQAAIfkECQoA
IgAsAQACAC4ALAAABulAkXBILBZBSJBxyWw6RZ4kyPOsWolR6ZLBaDS4V6sUaex6z4xwdVw0n9Hi
JJVJbr/v3+dYqXbj8057fFd/d2lNgmqFb4d0Y3OEi15PWUiQV354jU5Rl5iSm2phmXCipiJcjKGn
agtcq6yxUB6esleVSVidtkuCU0KPvEe+uLnCwL7Jg7zKxMcizYnPxWzBz9DOUJbXyNLcS8W130ZR
4+axtKbl6GxxWqa+VdTL7t6Oe+KIyXrxt8r53awNq9UskL2AdYYoo3Swn5B5v/jJKQJxmUN2F7W9
s1XxnMJsHrHhC/nwYEgpAKsEAQA7" />
`

**Comment by mkeilman** [comment]
CSS animation of a (much smaller) static image also works (for browsers that support it)...

As for the global, something analogous to `SIREPO` like

```
  <script>
      var NEWGLOBAL = {};
      NEWGLOBAL.pageLoaderTimeout  = null;
      NEWGLOBAL.setPageLoaderVisible = function () {...}
      ...
  </script>
```

(name TBD). Is that the idea?
