### ISSUE TITLE
20220930 template_common.analysis_job_dispatch should include run_dir

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4850]
So we can remove code like https://github.com/radiasoft/sirepo/pull/4842/files#diff-24496517cc6cc5369fc69a13a07158c876115ef9eec8ceb098a25b374b083f7fR1462

similar methods like sim_frame_dispatch do this.

**Comment by robnagler** [comment]
Fix https://github.com/radiasoft/sirepo/pull/4842

**Comment by robnagler** [comment]
@gurhar1133 you want to look for other calls to simulation_db.run_dir and remove them. The analysis_jobs should get rundir as a parameter. This might turn into a big task, but you can fix all future compatibilities by adding `**kwargs` at the end of all the functions you are modifying. When run_dir is passed, it should be passed as a kw arg.
