### ISSUE TITLE
Please test robnagler branch

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#488]
I want to merge my branch which fixes a bug or so and also separates out the running of the jobs. Trying to modularize the code better. Thanks.

**Comment by moellep** [comment]
I'm having a problem getting it running on a new source tree. When I run "python setup.py develop" it gives the error:

raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (kombu 3.0.29 (/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages), Requirement.parse('kombu==3.0.35
'))

**Comment by moellep** [comment]
I was able to work-around it by manually running pip for each case, ex. "pip install 'tornado==4.2.0'". Is there a way setup.py could force this?

**Comment by mrakitin** [comment]
Works fine for me.

**Comment by moellep** [comment]
I tested it with the Background and Celery workers and it worked fine.

**Comment by robnagler** [comment]
Thanks for testing. For pip issues, you might be able to do:

```txt
pip install -U -r requirements.txt
```

The problem with -U is that it will upgrade everything, and that may be too much...
