### ISSUE TITLE
Alpha release?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#489]
Should we upgrade alpha to beta, and build a new alpha?

**Comment by moellep** [comment]
Sure, I'll do a beta release at 10:30 MST followed by an alpha release.

**Comment by moellep** [comment]
Beta did not restart well. apa25b is not available on flower and short-term
simulations are not running. I'm debugging now.

**Comment by moellep** [comment]
Rob helped out with a stuck docker container on apa25 and beta is now
running again. Alpha will be released shortly.

**Comment by moellep** [comment]
Alpha release is done.
