### ISSUE TITLE
detect disabled font-download for MSIE

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#49]
MSIE may have the "Font download" security feature disabled, in which case the icons do not appear correctly. We need to detect this case and recommend the user use Chrome/Firefox/Safari when using sirepo.

![screenshot](https://cloud.githubusercontent.com/assets/6516910/11486113/28515ebc-9774-11e5-9724-d6f89943915e.png)

**Comment by mrakitin** [comment]
Is it still an issue?

**Comment by moellep** [comment]
I think this is still an issue - if the MSIE font-download item is disabled
(usually by a company's IT default browser), then the icons in the app
don't appear.

Paul

**Comment by moellep** [comment]
Shows an error message if the glyphicons font is missing:

![screen-shot](https://cloud.githubusercontent.com/assets/6516910/22948992/d8977cac-f2bd-11e6-9feb-8b9ffc3aa27b.png)
