### ISSUE TITLE
Crystal Element Definition

### ISSUE THREAD

**Issue by Angelrf86** [radiasoft/sirepo#494]
Hi,

I am trying to define a crystal as Monochromator or sample in the the LCLS example.

While defining it have been ask to give the Energy, the reflection and the compound "Diamond (X0h server)" while doing it I will expect that the program is calculation (or copying from the X0h server) the values for the real and imaginary parts of the 0-th Fourier component and H-th Fourier component. Is this not supposed to happen, should I introduce these values by hand?

Thanks in advance.

**Comment by mrakitin** [comment]
Hello, the real and imaginary parts of the 0-th and H-th Fourier components are either calculated by SRW, or taken from http://x-server.gmca.aps.anl.gov/x0h.html. If you prefer to use your values, feel free to input them to the corresponding fields, and they will be used instead. You may want to change the material of the crystal to `Unknown` to avoid replacing your input values by the values from SRW of the server in case you update the energy or Miller's indices.

Is it answering your question?

**Comment by mrakitin** [comment]
I guess it's solved. Closing.
