### ISSUE TITLE
20221231 Recreate Sirepo Hellweg

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#4940]

**Comment by robnagler** [comment]
@bruhwiler Should this be called Sirepo RSLinac?

**Comment by bruhwiler** [comment]
There are multiple journal articles describing the capabilities and advantages of the Hellweg code. I believe we should be consistent with how we handle other community accelerator codes, like elegant, opal, synergia, etc.

For these reasons, I prefer to use Sirepo Hellweg as the name of the app.

**Comment by robnagler** [comment]
Dup #5142
