### ISSUE TITLE
20221018 pyisemail is broken

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4952]
See https://github.com/radiasoft/sirepo/actions/runs/3275227745/jobs/5389800783#step:3:386

```sh
$ python -c 'import pyisemail'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyisemail'
```

2.0 was released, and we were on 1.3.2. I think the pyIsEmail install of the package was unintentional so I'll peg 1.3.2.

**Comment by e-carlin** [comment]
Can the fix be moved to master? It is breaking the alpha build

**Comment by robnagler** [comment]
yes i'll create a pr. Also created https://github.com/michaelherold/pyIsEmail/issues/30

**Comment by e-carlin** [comment]
Thanks
