### ISSUE TITLE
SRW - allow editing of pre-defined electron beams

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#496]
Need to make the fields of pre-defined electron beams editable.
- [x] Implement the code.
- [x] Test if the beam definition works fine with the new implementation.
- [x] Test on IE11.
- [ ] Expand the implementation so that the created user beams are available for all user's simulations.
- [ ] Need to have `Delete` or `-` or `x` button next to a user-defined beam in the beam selector to allow deletion of unnecessary beams.

**Comment by mrakitin** [comment]
Need to disable the `Name` field in the basic menu on load.

@moellep, do you have an idea how to disable it on page load? I tried different ways, but it didn't work. Please see c634335 in my branch.

**Comment by mrakitin** [comment]
@moellep, I'll also need the API to save the user-defined beams (`appState.models.electronBeams`) to a file (possibly in user's `lib/` dir), so that it could be accessible in all user's calculations. I.e. there should be the way to easy writing to the file, and reading from it. Could you please help me with it? Thanks!

**Comment by mrakitin** [comment]
Disable eBeam name in the basic menu implemented in 0d48aa6. @moellep, don't worry about this item.

**Comment by mrakitin** [comment]
The new implementation works fine in IE11.

**Comment by mrakitin** [comment]
Also need to implement `Delete` button next to user-defined beams in the beam selector.

**Comment by mrakitin** [comment]
@moellep, I saw a number of your commits:
- https://github.com/radiasoft/sirepo/commit/a1ad6315ffd5c6b0243b85f2121dcb8178684a66
- https://github.com/radiasoft/sirepo/commit/3ee7c6048e3ec0f61a45f8af9107ab3dc4be2110
- https://github.com/radiasoft/sirepo/commit/9387466d1b2e5dcf57bb6faa7097f3ee20a627cf
- https://github.com/radiasoft/sirepo/commit/2b6438daa2bef86f5b9e481b5ae76e3e51676606

Did you implement sharing the electron beams across the user's simulations? I tried it and it looks like it's not done yet.

**Comment by moellep** [comment]
The beam sharing part is in development and will be checked in soon.

**Comment by mrakitin** [comment]
Thanks Paul!

**Comment by mrakitin** [comment]
@moellep, the simulations now can exchange the customized beams - great improvement, thanks!
