### ISSUE TITLE
20221024 Imported point table causes TypeError

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#4966]
Specifically, `o.referencePoints is not defined`.

**Comment by mkeilman** [comment]
I'm having trouble reproducing this error. The simulation that failed is https://www.sirepo.com/radia#/source/kp3RMOWk. @moellep can you get me that sim? I get server errors when trying to export from my copy.

**Comment by moellep** [comment]
I've just sent you and email with the kp3RMOWk datafile.

**Comment by mkeilman** [comment]
It appears that Radia does not like it if the path is closed. @j-edelen can you get the table to load if you remove the last point? I'll have the code remove the redundant point.

**Comment by j-edelen** [comment]
I think the issue went away but I am still not seeing the shape on the 2-D visualization

**Comment by j-edelen** [comment]
https://www.sirepo.com/radia#/source/cnU5Glw3

**Comment by mkeilman** [comment]
I just tested the "prefab" extruded shapes and they also broke at some point - I'll cover that in this issue since it's related

**Comment by mkeilman** [comment]
Note: @j-edelen consistently gets this error, but nobody else can reproduce it so far. @moellep, can you find anything in the production logs from yesterday around 16:15 regarding simulation https://www.sirepo.com/radia#/source/S4j2S41T?  It's very odd...
