### ISSUE TITLE
20221025 Workspace does not expand to accommodate large objects 

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#4984]
For freehand magnets, if you drop an object into the workspace that is larger than it, the scale of the workspace does not change to enable you to see the whole object. Clicking one of the axes buttons cleans it up, but it should do so on drop

**Comment by mkeilman** [comment]
Not sure why the PR comment did not close this...

**Comment by robnagler** [comment]
I deleted the branch. The merge commit didn't have "Fix #nnn" but instead just "#nnn".
