### ISSUE TITLE
Setting watchpoint title to blank causes server error when saving

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#50]
If a beamline watchpoint title is cleared and the "Save Changes" is selected, the server will return a "server error" response for all reports.

**Comment by mrakitin** [comment]
That's still an issue.

**Comment by moellep** [comment]
A simple fix for this might be adding the code below to the beamlineBuilder directive.
```
            $scope.$on('beamline.changed', function(evt, name) {
                appState.models.beamline.forEach(function(m) {
                    if (m.type == 'watch') {
                        if (! m.title) {
                            // fix the title before the save is committed
                            appState.setModelDefaults(m, 'watch');
                            appState.saveQuietly('beamline');
                        }
                    }
                });
            });
```
It doesn't solve the general case. For example, a similar error can occur if any beamline item has an invalid field (such as 'x' in a Float field) and the beamline is saved.

A better fix would be to detect if one of the beamline elements is invalid and prevent "Save Changes" from being selected.

A test case would be: Open an empty beamline, drop an aperture and a watchpoint, select the aperture and enter 'x' in the Horizontal Size field (the Close button will appear disabled). Dismiss the aperture editor by clicking on the aperture icon and select the "Save Changes" button.
