### ISSUE TITLE
Elegant: Import fails when .ele file constructs and references external files

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#503]
I was testing the import function for the a pair of files (run file and lattice file) and ran into the following issue.

I did the following:
- Upload elegant run file (.ele)
- Upload lattice file (.lte)

I then received the following error:

> Please upload the files below which are referenced in the elegant file.
>      %s.paramOpt (load_parameters: filename)

The reason for the issue is that the elegant file I was trying to upload optimizes lattice parameters and spits them out into a separate file. This separate file is called later to change element parameters before the final run. How to adjust Sirepo import feature to allow for this sort of self-consistent file creation and referencing?

**Comment by robnagler** [comment]
Fixed, I'm pretty sure.
