### ISSUE TITLE
compute_undulator_length requires magnet file?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5040]
fixup_package_data_json calls fixup_old_data, which ends up hitting compute_undulator_length which requires a uid in order to check lib files. I suspect fixup_package_data_json does not do the right thing. LMK what you think.

**Comment by moellep** [comment]
We should probably remove all the srw fixups which are 5 years or older. That would probably include that check.

**Comment by robnagler** [comment]
I don't know enough to know if that's ok. We may want an assert in this case to terminate the fixup if the case is hit.

**Comment by robnagler** [comment]
@moellep could you look at this?
