### ISSUE TITLE
20221230 Radia server error with new sim

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5049]
When you create a new simulation and have not yet set a geometry, the fieldLineoutAnimation still tries to run and causes an error with a stack trace on the server:
```
AttributeErrorAttributeError: 'PKDict' object has no attribute 'type': 'PKDict' object has no attribute 'type'
    res.extend(_FIELD_PT_BUILDERS[p.type](p))
```

**Comment by mkeilman** [comment]
Duplicate of #4973 I believe
