### ISSUE TITLE
20221123 Cannot find module 'typescript'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5063]
How do we upgrade our local react build environments?

`Error: Cannot find module 'typescript' from '/home/vagrant/src/radiasoft/sirepo/react/node_modules'`

**Comment by garsuga** [comment]
I think we need to run `npm install` when switching branches. Normally this would need to be done every time since node_modules is untracked.

**Comment by garsuga** [comment]
I have been placing all of the packages in react/node_modules so try running `npm install` from the react folder

**Comment by robnagler** [comment]
npm install worked. Perhaps we could have a sentinel that figures out if npm install needs to be called again inside pkcli.service.http. It's only necessary for that. I changed this issue title to reflect that. It might be that it could be run every time, since webpack is the slow part.

**Comment by robnagler** [comment]
@garsuga did you see this from @gurhar1133?

```txt
/home/vagrant/src/radiasoft/sirepo/react/node_modules/react-scripts/scripts/start.js:19
  throw err;
```

**Comment by garsuga** [comment]
No, I did not, what is this referring to?

**Comment by gurhar1133** [comment]
When I run `sirepo service http` I run into that error. I've been using the workaround Paul gave me: 
"One work-around is to disable react when you start the server:
```SIREPO_PKCLI_SERVICE_REACT_PORT= sirepo service http```"

**Comment by garsuga** [comment]
I cloned into a new directory on master and ran `npm install` in both the root and `react` directory (that's important since they are different node projects) and I cannot recreate this error

**Comment by robnagler** [comment]
There may be a problem with cloning a new repo as opposed to git pull on an existing one that is out of date.

**Comment by garsuga** [comment]
Is this still an issue on latest?

**Comment by gurhar1133** [comment]
> Is this still an issue on latest?

this is working now
