### ISSUE TITLE
calendar popup needs border sometimes

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5081]
In Chrome (at least) in the raydata app, the calendar popup has no border (sometimes) which makes it look odd:
![x](https://user-images.githubusercontent.com/6516910/200034019-cc3a7292-6630-4226-aee0-9a1b034d8988.png)

Very odd - the border shows some of the times, but clicking on the same Start calendar icon multiple times, and most of the times it has no border.

**Comment by moellep** [comment]
I can't reproduce this one, closing.

**Comment by e-carlin** [comment]
The date picker is something we've struggled with. It takes quite a few clicks to enter all of the fields and do a search. Currently we are just using the barebones html5 picker. Hiran (a collaborator at BNL) has mentioned that we could use one from bootstrap. But, we haven't investigated it. As you're working please keep an eye out for ways to improve. Or maybe you already know of a better date picker...
