### ISSUE TITLE
20230731 omega Code coupling workflow

### ISSUE THREAD

**Issue by j-edelen** [radiasoft/sirepo#5089]
Build tools that enable export of beam distribution from OPAL and import into elegant or MAD-X without downloading the files. The user should be able to spawn a new simulation in MAD-X/elegant or load into an existing simulation. This is in support of fastfelo.

**Comment by moellep** [comment]
Some notes for this
```python
from rsbeams.rsdata import switchyard    
sw = switchyard.Switchyard()
sw.read('distribution_in.name', 'elegant')
sw.write('distribution_out.name', 'opal')
```

And opal to elegant rsopt config:

[config_s2e_single_obj.tar.gz](https://github.com/radiasoft/sirepo/files/9975770/config_s2e_single_obj.tar.gz)

**Comment by robnagler** [comment]
See also #3652

**Comment by moellep** [comment]
Rough slide of the new "omega" app which allows chaining apps together. 
![IMG_5016](https://user-images.githubusercontent.com/6516910/204922442-da7659b5-8664-44c6-8948-d067c520555f.png)
The app would allow chaining a series of existing simulations together, taking output from the previous and converting to the format used by the next app. Output plots for each step would be shown. When running, the input file for each simulation would be updated - so visiting the simulation directly in the original app will produce the same output. 
When sharing an omega app, it would create copies of all the subapps within the user's database (essentially calling api_copyNonSessionSimulation() on all the parts and linking them in the new omega simulation).

**Comment by moellep** [comment]
Initial mockup of the omega app - it would be on a a single Sirepo tab, with the app order selection at the top and a section for each app’s output further down the page. Selecting “Start Simulation” would run each code in turn, chaining the output to input.
![omega app mockup pg1](https://user-images.githubusercontent.com/6516910/207714246-3faa3cd1-1201-429d-ba47-0010b81aeb81.png)
![omega app mockup pg2](https://user-images.githubusercontent.com/6516910/207714263-6d6ab52b-ad99-4d80-acfc-ba563fa6d819.png)

**Comment by moellep** [comment]
Feedback from Jon:

Do not include the "Particle Input File" field - instead use the source as specified in the first application. For example, if OPAL is the first selection, the link could be used to visit that application and configure a FLATTOP or other initial beam.

Showing the 2x2 plots of the phase space is good. Showing the additional plots about the beam: emittance, beam envelope, twiss parameters is also good. For genesis, the field output should also be shown.

At a later point, it would be nice to have a rendering of the lattice at each step.
