### ISSUE TITLE
Allow changing the "distance from source" offset for ellipsoid mirrors

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#51]
The "distance from source" is automatically set to the position of the beamline element. Allow for an out-of-alignment mirror to be simulation by adding a new ellipsoid mirror property, named something like "Longitudinal Alignment Error [m]".

**Comment by bruhwile** [comment]
A different solution was requested.
As far as I understand, the lens should be characterized by two parameters:
1) p, ideal distance from source
2) q, ideal distance from image

It would be reasonable that, when a user places an ellipsoid mirror in the
beamline, the value of 'p' should default to the actual distance from the
source, and probably 'q' should by default be the same value as 'p'.

Users are then free to change 'p' and 'q' as they like.
The motivating use case is a free-electron laser, where the source location
is somewhere inside the last undulator and depends on the photon energy by
as much as +/- 20 m at LCLS.



On Mon, Nov 30, 2015 at 3:16 PM, Paul Moeller <notifications@github.com>
wrote:

> The "distance from source" is automatically set to the position of the
> beamline element. Allow for an out-of-alignment mirror to be simulation by
> adding a new ellipsoid mirror property, named something like "Longitudinal
> Alignment Error [m]".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/sirepo/issues/51>.
>



-- 
David Bruhwiler
RadiaSoft LLC
+1 (720) 502-3928

**Comment by moellep** [comment]
Right now p is always set to the distance from the source (the element
position). q is the "Focal Length [m]" value and can be changed by the user.

Originally p was present in the UI as the "Distance from Source" value and
defaulted to the element position. It becomes confusing when you change the
element position to a new value and forget to also update the "Distance
from Source". I think having an offset which defaults to 0 would be better
to avoid data entry problems.

Paul

**Comment by bruhwile** [comment]
A modified implementation has been pushed to alpha.
We'll request input from SLAC users.
