### ISSUE TITLE
20221118 Remove top-level translation transform

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#5101]
Since users can drag objects around the workspace, adding a translation is redundant and confusing. It's still meaningful for clones however. @cchall @j-edelen is this a sensible change?

**Comment by j-edelen** [comment]
If you want to be precise about the positioning then it can be useful to do exact translations as opposed to dragging objects around.

**Comment by mkeilman** [comment]
> If you want to be precise about the positioning then it can be useful to do exact translations as opposed to dragging objects around.

You can enter the center coordinates of an object by hand - the translate transform would then move the object from that point. Which you could just do directly by entering the new coordinates directly...

**Comment by j-edelen** [comment]
Makes sense. If @cchall doesn't object then we can remove.
