### ISSUE TITLE
20221116 add email login support to e2e testing

### ISSUE THREAD

**Issue by garsuga** [radiasoft/sirepo#5111]
* handle ui differences: login with guest vs login with email vs email only login prompt like on beta
* read mail from ~/mail and parse for login link
* make request to login link
* refresh page? and perform tests

**Comment by robnagler** [comment]
> refresh page? and perform tests

This should load the app again. I don't know how playright deals with this.

**Comment by robnagler** [comment]
Fix https://github.com/radiasoft/container-sirepo-e2e/pull/2#pullrequestreview-1246757076
