### ISSUE TITLE
20221123 diagram of template and sim_data services

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5116]

**Comment by robnagler** [comment]
It would be useful to include the path for simulation_db which goes through prepare_simulation and prepare_for_save.

**Comment by robnagler** [comment]
@moellep did you get a chance to work on this?

**Comment by moellep** [comment]
No, I'll try to have something done by Wednesday

**Comment by moellep** [comment]
This isn't quite what you asked for but I think it clarifies what the current sirepo/template is trying to accomplish.

![Sirepo Imp API](https://user-images.githubusercontent.com/6516910/203653545-2d5c5f42-963c-4326-b9ea-37852d677aa9.png)

We should move all the "util" and "prep" modules out, and the "hull" should be just the application specific implementation of the blue APIs.

As for naming, it could be app_imp, app_impl, app_biz or even app_app. This is the part of the software which is very specific to each app - ie. how the code input file is generated, how the simulation output is processed.

**Comment by robnagler** [comment]
Make sense, mostly. I don't understand Business Logic, which is about Results, e.g. analysis_job. I don't think we have such clean breaks. I would like to see a separation around what happens in the server and what happens in job_cmd (today). For example, validate_file happens in the front-end server (Flask), and write_parameters runs in job_cmd (inside the agent).

I think a simple list is probably better, and include things like python_source_for_model.

The code is going to be pretty hard to separate given the way it is written, e.g. python_source_for_model is essentially write_parameters, but they are called from very different places. I will work on a complete list.

I think we need app_hull (sticking to this name for now) to wrap the code itself, which would contain a class for each app (to start). I think the class would have a defined interface for all these calls with an ABC to define them all.

**Comment by robnagler** [comment]
I documented the [Template API](https://github.com/radiasoft/sirepo/wiki/Template-API). I tried to describe all references to templates, not pkcli, sim_data, sim_api, etc. @radiasoft/software LMK what you think.

**Comment by e-carlin** [comment]
lgtm. I made a of couple minor edits.

**Comment by robnagler** [comment]
I think this is enough for now.
