### ISSUE TITLE
20221114 save-simulation posts should not be queued

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5119]
I'm less concerned about this for angular and more for react. @garsuga please lmk what will happen in this case.

warpvnd > Lattice Gate 3D > Field Calculation Status > Start Simulation > Field Report > hold down slider and move back and forth for a few seconds then let go:

```txt
10.10.10.1 - - [11/Nov/2022 22:34:21] "GET /simulation-frame/0*fieldCalcAnimation*fN4ITSdO*warpvnd*HashIsUnused*1668205982*xz*3d*-1.078125 HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:22] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
10.10.10.1 - - [11/Nov/2022 22:34:23] "POST /save-simulation HTTP/1.1" 200 -
```

**Comment by garsuga** [comment]
This seems like an issue that only happens in visuals like this where edits need to be live. Most forms require 'Save Changes' to be clicked to write to the models while this visual writes directly. This is similar with what you mentioned with schema probably needing to be separated into more pieces since it includes too much. Models probably shouldn't contain things like display parameters since they behave a little differently.

In React this would be debounced using some generic debounce method and the logic would be something along the lines of "queue latest save simulation and only run this queued callback when updates have not occurred for x milliseconds". Seems like these "live edits" need a separate handler outside of the typical form controller used in React.

**Comment by garsuga** [comment]
If I understand correctly, this is saving a display parameter (the last selected slice) and also requesting the newly selected slice each time the bar moves. It is a little tricky to make this feel smooth since the server needs to see and respond to each of these changes for the slider to work correctly. Perhaps we should choose a different UI to do this that does not give the user the impression that these changes should be smooth and instant

**Comment by robnagler** [comment]
> Perhaps we should choose a different UI to do this that does not give the user the impression that these changes should be smooth and instant

I think the UI is fine. The problem is the saving. I agree with your https://github.com/radiasoft/sirepo/issues/5119#issuecomment-1312251018. 

I think if we sent "edits" instead of the whole blob every time, we would be much better off with the saving.

Also, the save changes would be posted asynchronously. You wouldn't send an update until you got the reply back from the previous state. If we are sending edits, we could be intelligent about the queue, but that would be an optimization. 

I do think we need to keep all this state in a single blob in a db. I don't think we want to coordinate values across multiple blobs ("models" and "preferences"). Rather, we might have models that are just preferences, and again, they would be updated asynchronously.

Debouncing all things like this is critical. If we are doing "autosaves", they should not fire until a move is complete. Saves should not be sent on the scale of milliseconds, but rather could be every few seconds. If movement is still happening, we don't save.

**Comment by robnagler** [comment]
Will be handled better in ngui.
