### ISSUE TITLE
20221231 improve flash redirect

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5128]
When a user gets redirected back from the flash center, it goes to the sirepo home page instead of /flash.

**Comment by e-carlin** [comment]
This is not the behavior I see when using the app. It redirects me to the simulation list page. Can you reproduce?

**Comment by robnagler** [comment]
This was due to the cookie problem. Fixed in https://github.com/radiasoft/sirepo/issues/5137
