### ISSUE TITLE
twiss_output parameters erased at import

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#5135]
When importing a command file with multiple twiss_output commands it looks like the the Twiss parameters in the first command are set to their default values instead of those in the file.

I can provide an example if needed.

**Comment by bruhwiler** [comment]
This is for a customer.

**Comment by cchall** [comment]
I tested this a little more and I think the issue really is just that the command file I was importing uses bunched_beam.Use_Twiss_Command_Values. So it expects to set the initial beam conditions from twiss_output, but sirepo normally sets twiss_output values from bunched_beam, which had default values in my file.
I'm guessing this is just applied to the first twiss_output command, which is why the rest looked alright in my simulation.
