### ISSUE TITLE
20221230 util.import_submodule exception hides real error

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5146]
The exception handling in util.import_submodule() can hide other errors. For example, I didn't have the "trimesh" module installed, but the error shown was: 

```AssertionError: cannot find submodule=template for sim_type=radia in package_path=('sirepo',)```

Which then leads to debugging the SIREPO_FEATURE_CONFIG_SIM_TYPES and similar routes, rather than the actual error, which is coming from ```import sirepo.template.radia``` which is ```ModuleNotFoundError: No module named 'trimesh'```

**Comment by robnagler** [comment]
Dup #3933
