### ISSUE TITLE
20221118 LDAP: Get server working on machine (1 day)

### ISSUE THREAD

**Issue by Benbenbenin0** [radiasoft/sirepo#5149]
Get LDAP server installed on your machine. [Many options for this](https://ldap.com/directory-servers/). It looks like many tutorials use OpenLDAP ([example](https://www.golinuxcloud.com/ldap-tutorial-for-beginners-configure-linux/)) so I'd start with it but if you find something better feel free to switch.

Take notes about your process so other people can follow them. Don't worry about security or making it robust. Just get it working as quickly and simply as possible. It is just for local development. Add a user to the system we can try to authenticate as.

**Comment by robnagler** [comment]
I have setup openldap before so feel free to ping me if you need help.

**Comment by Benbenbenin0** [comment]
Notes from email chain:
- Folks at NSLS-II:
I recommend using LDAP with DuoProxy. DuoProxy presents a drop-in replacement for LDAP but, just before completing the transaction, insists on two-factor. Conveniently, it accepts YubiKey OTP appended to the password prompt like "PASSWORD,OPT" or it else it performs a Duo Push to mobile. You can find Python code that works again our LDAP in https://github.com/bluesky/tiled/blob/main/tiled/authenticators.py#L335. The CI for that project includes a container you could test your own implementation against. Once that works, Maksim can easily set it up with our DuoProxy instance.

- Might not need Duo at all. We can just code to LDAP like was noted above.

- Response ("just before completing the transaction, insists on two-factor"):
I don't think LDAP can "insist" on anything. It has no "push" notification. Rather, enter a password and then select duo push and that's the thing that does the work of getting the OTP. You can enter that manually instead of via the app. It's just that the sshd uses the proxy which only allows a push.
In any event, I think what we need to do is support OTP entry like we do for NERSC. We don't particularly care where it comes from. We can test that with any type of OTP (ours can be[ TOTP with openldap/slapd](https://github.com/openldap/openldap/blob/master/contrib/slapd-modules/passwd/totp/slapo-totp.5)). We could use the duo proxy to handle this, but I bet it accepts a passcode entry just like Yubi key. Of course this will be less convenient so maybe we'll have to figure out that API, but the first step is just talking to ldap (slapd) as another auth method with just a username and password.
