### ISSUE TITLE
20221205 LDAP: Install Duo (1 day)

### ISSUE THREAD

**Issue by Benbenbenin0** [radiasoft/sirepo#5152]
Install Duo

**Comment by Benbenbenin0** [comment]
Installed

**Comment by e-carlin** [comment]
Can you provide instructions for installation?

**Comment by Benbenbenin0** [comment]
Backtracking on this, realized I installed and configured Duo instead of Duo Proxy.

**Comment by Benbenbenin0** [comment]
No longer relevant to project
