### ISSUE TITLE
20221118 double-click to edit broken

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#5161]
Trying to double-click objects in the design tab viewer now seems to be zooming in rather than bringing up the object edit menu. Double clicking does seem to still work for the extruded object in my test case though.

**Comment by cchall** [comment]
I played with this some and had the behavior stop for a while. I think I've been able to reproduce the problem now though.

It seems like when the double-click selection breaks going to the visualization tab and back to the design tab fixes it. After I drop in a new object (I only tested with cube) the double click breaks again for the racetrack in my example.

**Comment by mkeilman** [comment]
Weird. I wonder if we should even enable double-click zoom...

**Comment by cchall** [comment]
I think it's fine to just disable double-click to zoom if that helps to simplify things.
I certainly always default to scroll wheel or gestures on a mousepad.

**Comment by mkeilman** [comment]
I think I've got the zoom problem fixed, but there is another problem where 2x-clicking built-in extruded shapes opens the editor and then immediately closes it. I'll use this issue for that.

**Comment by mkeilman** [comment]
> I think I've got the zoom problem fixed, but there is another problem where 2x-clicking built-in extruded shapes opens the editor and then immediately closes it. I'll use this issue for that.

Changed my mind - separate issue
