### ISSUE TITLE
20221121 React deps confusion

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#5177]
On the branch `4872-auth-db-models`  I tried `sirepo service http`. I got the below error. I then tried to resolve it with an `npm install` which didn't work.

```
Failed to compile.

Module not found: Error: Can't resolve 'react-useportal' in '/home/vagrant/src/radiasoft/sirepo/react/src/component'
ERROR in ./src/component/simbrowser.js 25:0-40
Module not found: Error: Can't resolve 'react-useportal' in '/home/vagrant/src/radiasoft/sirepo/react/src/component'

ERROR in ./src/layout/download.js 5:0-40
Module not found: Error: Can't resolve 'react-useportal' in '/home/vagrant/src/radiasoft/sirepo/react/src/layout'

ERROR in ./src/layout/download.js 10:0-38
Module not found: Error: Can't resolve 'html2canvas' in '/home/vagrant/src/radiasoft/sirepo/react/src/layout'

ERROR in ./src/layout/navbar.js 11:0-40
Module not found: Error: Can't resolve 'react-useportal' in '/home/vagrant/src/radiasoft/sirepo/react/src/layout'

webpack compiled with 4 errors
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
No issues found.
  C-c C-c^C
sirepo (4872-auth-db-models)$
sirepo (4872-auth-db-models)$ sirepo (4872-auth-db-models)$ cd react/
react (4872-auth-db-models)$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: sirepo@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6 || ^17.0.0" from react-useportal@1.0.17
npm ERR! node_modules/react-useportal
npm ERR!   react-useportal@"^1.0.17" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/vagrant/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2022-11-08T13_57_34_141Z-debug-0.log
```

Any idea how to resolve?

FWIW I'm running on f36. I'm using node version 16.14.0. Not sure if that is different than f32.

**Comment by garsuga** [comment]
I am not sure how to resolve this error. I will send you my package-lock.json, lets see if that fixes it.

**Comment by garsuga** [comment]
Try running `npm i --force` this first time. It seems to be that react-useportal thinks it needs an old version of React but it has been working fine with the latest in my installation. Future installs shouldnt need --force

**Comment by e-carlin** [comment]
I did that and it worked. Strange to have to use `--force`...

**Comment by garsuga** [comment]
`--force` force is only needed because we want React 18 but react-useportal does not want to install on anything except React 16 and 17. Once you have react-useportal installed it will not require --force for other `npm i` calls

**Comment by e-carlin** [comment]
Looks like it is a known issue https://github.com/alex-cory/react-useportal/issues/81 . That has been open since July with no comment by a maintainer. If it is as simple as the PR to fix it claims it to be (https://github.com/alex-cory/react-useportal/pull/84/files) then --force is fine. If there are actual reasons why the lib isn't compatible with react 18 then we need to be wary of --force. Do you know if the lib is compatible with react 18?

**Comment by garsuga** [comment]
The package does not contain many features. I was able to use all of the 'portal' features without any issues

**Comment by robnagler** [comment]
Is there harm in using `--force`? I would like to put this pkcli.service so that it is automatic.

**Comment by e-carlin** [comment]
I deleted all node_modules and ran `npm install` again. This time it worked without complaint. [The meme remains true](https://i.redd.it/m0rbqdwirdf01.jpg)

According to [the docs](https://docs.npmjs.com/cli/v6/commands/npm-install) force installs all deps from remote. So, I guess that has the same effect as `rm -rf node_modules && npm install`. I think that could create a slow startup if we have to re-download all deps from remote each time we start the server.

**Comment by robnagler** [comment]
Good point. Perhaps we can print a message if this happens:

> webpack compiled with 4 errors
> Files successfully emitted, waiting for typecheck results...

webpack should never have errors. @garsuga will this screw up development?

**Comment by garsuga** [comment]
webpack has an error here because it is called with / calling `npm install` and the errors it lists are missing packages. These will go away after the fix I suggested above.

**Comment by garsuga** [comment]
>  I think that could create a slow startup if we have to re-download all deps from remote each time we start the server.

This is exactly why we would not be doing any work with `npm` on start. Installing packages should only need to be done if:

- You're checking out a new branch (which has a different package.json)
- You're pulling changes that modified package.json
- You're cloning the repository

The reason you are able to install without errors the second time is because you did not delete `package-lock.json` with your node_modules folder. package-lock.json contains all the resolved dependencies and their exact version so I suspect the override is not needed unless that list needs to be generated again.

**Comment by e-carlin** [comment]
> The reason you are able to install without errors the second time is because you did not delete package-lock.json

Ah right, thanks.

> A better solution would be to include package-lock.json on git

Agreed. Then the person installing the dependency can decide if force is needed (and safe). If they decide it is then they can add it to the lock file with --force and everyone else will get it the dep with a normal `npm install`

**Comment by robnagler** [comment]
Let's commit package-lock.json, it's the most expedient fix. Do not modify .gitignore globally, just add it locally.
