### ISSUE TITLE
Javascript array push chokes on large inputs

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#5190]
Similar to `Math.max()` etc., `<array>.push(...<array 2>)` can exceeds the stack size. Discovered in radia but a universal problem.

**Comment by moellep** [comment]
Do you know what the limit is for the pushed values? Is the error in the ... operator or push()? If you have an example sim which reproduces this I'd like to take a look.

**Comment by mkeilman** [comment]
> Do you know what the limit is for the pushed values? Is the error in the ... operator or push()? If you have an example sim which reproduces this I'd like to take a look.

In this case the problem is with `...` ("spread operator"), which I thought was just sugar around a simple loop but which I guess is actually recursive. The limit is (at least) browser-dependent: e.g. for me chrome is 2^17, safari is 2^16. In the console you can enter
```javascript
Math.max(Array(<big number>).fill(0))
```
to play with it

**Comment by robnagler** [comment]
Spread operator is not recursive, but it does a shallow copy and dumps that on the stack in the case of push. 2^16 is a lot of arguments to pass to any function call. I can't imagine a scenario where that would make sense.
