### ISSUE TITLE
20221128 opal.get_application_data code_var

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5200]
@moellep is this cruft?

[This code](https://github.com/radiasoft/sirepo/blob/727043e5e6e06755d746f3deedeccdb6a0058aeb/sirepo/template/opal.py#L462) does not seem callable:

```py
def get_application_data(data, qcall, **kwargs):
    <snip>
    if code_var(data.variables).get_application_data(
        data, SCHEMA, ignore_array_values=True
    ):
        return data
```

There is no get_application_data on code_variable.PurePythonEval afaict.

**Comment by moellep** [comment]
code_variable get_application_data() was renamed in https://github.com/radiasoft/sirepo/pull/5064/files#diff-63eafcb3de3a01e96c1d4635b788e49e0a374df5f1fb2349931d48db48ac0c1d
elegant, madx, etc. don't have that call, so I think it must be cruft which can be removed.

**Comment by robnagler** [comment]
Thanks
