### ISSUE TITLE
20221128 activait getApplicationData invalid?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5201]
@gurhar1133 is this cruft? There is a [call to compute_column_info](https://github.com/radiasoft/sirepo/blob/727043e5e6e06755d746f3deedeccdb6a0058aeb/sirepo/package_data/static/js/activait.js#L2131).

[This call to getApplicationData](https://github.com/radiasoft/sirepo/blob/727043e5e6e06755d746f3deedeccdb6a0058aeb/sirepo/package_data/static/js/activait.js#L282) does not have a corresponding get_application_data call [in template.activate](https://github.com/radiasoft/sirepo/blob/727043e5e6e06755d746f3deedeccdb6a0058aeb/sirepo/template/activait.py):

```js
function updateAnalysisParameters() {
        requestSender.getApplicationData(
            {
                method: 'column_info',
                dataFile: appState.models.dataFile,
            },
            data => {
                if (appState.isLoaded() && data.columnInfo) {
                    appState.models.columnInfo = data.columnInfo;
                    appState.saveChanges('columnInfo');
                }
            });
    }
```

**Comment by moellep** [comment]
This is cruft and a call to "compute_column_info" has replaced it. Much of this should be removed from AnalysisController which doesn't have a dataFile editor on the page (I think this code came over from the conversion from rcscon)

**Comment by robnagler** [comment]
I'll leave this open. @gurhar1133 do you think you could remove it? Trying to trace all get_application_data calls.

**Comment by gurhar1133** [comment]
and remove the calls to `updateAnalysisParameters()` as well?

**Comment by robnagler** [comment]
I don't actually know. Just remove all cruft. It seemed like there was a lot of it. Consult with @moellep as he knows what's supposed to be there.
