### ISSUE TITLE
Transform editor appears behind object editor

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#5238]
When opening the editing window for an existing transform applied to a racetrack element the editor opens behind another window and is not accessible.

You can see the edge of the editor that opened on the right hand side.
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/17073688/206005385-12d265cf-d679-4def-8fd6-9954d2b97151.png">

**Comment by mkeilman** [comment]
#4711 (in progress) will take care of this by eliminating the second dialog

**Comment by mkeilman** [comment]
Fixed by #5307
