### ISSUE TITLE
Add function to redirect to specific sim id of another app

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#5257]
`requestSender.globalRedirect()` strips everything after the hash so `<app>#/<section>/...` becomes `<app>`. Add a new function or modify this one so we can go directly to a simulation.

**Comment by mkeilman** [comment]
A couple of notes: findByNameWithAuth only works with examples, and findByName does not include auth. I lean toward adapting the former to allow non-examples with an optional parameter

**Comment by robnagler** [comment]
I think if findByNameWithAuth is broken, it can be fixed. It doesn't need an optional parameter. This is a public API but it is not published. I think find-by-name is the only one that is published.

**Comment by moellep** [comment]
JSPEC does this when an elegant sim is selected on the Ring panel. The button next to the elegant sim list opens a new window to the elegant app. See sirepo-components.js simList directive and requestSender.newLocalWindow()

**Comment by mkeilman** [comment]
SRW -> Shadow conversion does not - it creates a raw link of the format above. That's what I used to open a new activait app and what led to this issue. I also note this:
```javascript
 //TODO(e-carlin): this depends on the visualization route
// being present in both the caller and callee apps.
// Need meta data for a page in another app
requestSender.newLocalWindow(
    $scope.route || 'visualization',
    {':simulationId': $scope.model[$scope.field]},
    $scope.code
);
```
I think then we can encapsulate this in a new function on requestSender. I'm glad we don't need to fiddle with the api
