### ISSUE TITLE
/jspec is not redirecting to /react/jspec

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5266]

**Comment by garsuga** [comment]
Is this an issue still? I designed the routing so that it would not do a redirect from /jspec to /react/jspec. Honestly with the progress in the react proxying that we have made we probably no longer need to have /react in the client url space.

**Comment by robnagler** [comment]
Let's drop /react and verify it works.

**Comment by garsuga** [comment]
Ok I will bundle that work with https://github.com/radiasoft/sirepo/issues/5355
