### ISSUE TITLE
fedora36: warpvnd  EGun example doesn't work

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#5278]
source:
`Simulation Error: Out of range float values are not JSON compliant: 1 animation frames`

Visualization:
Same underlying error but it results in a "report not generated" in the gui

**Comment by e-carlin** [comment]
The underlying cause is that we are getting back some nan's and None's where we are expecting floats. 

One value where we get a nan is e_cross. Tracing it back the cause seems to be the warp.getphi() function. In f36 it returns an array where some values are nan. In f32 all values are floats. Looking at just the getphi function between f32 and f36 there are no changes. I'm struggling to decide whether I want to dive down into the warp source to find the difference or to try and resurrect our old version of warp (or something close to it) that doesn't have the problem.

**Comment by robnagler** [comment]
Let's chat about this. Maybe I can help understand what changed.

**Comment by e-carlin** [comment]
We are going to try to use an older commit of warp (probably the one we used to build from) and to run py2to3 over it to try and get it working.
