### ISSUE TITLE
beta and alpha centos upgrades

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#528]
I'll be upgrading alpha today. beta will be upgraded tomorrow morning. With beta, only apa11 will be updated. The blades are running fedora.

**Comment by mrakitin** [comment]
What's the reason of the update? Isn't the fedora images stable enough? Will I have to change anything on cpu-001?

**Comment by robnagler** [comment]
Normal security update for CentOS. It's actually overdue. :)  This is the base operating system for apa11 (not docker images), which is a bare metal server. 

Docker images and cpu-001 will not be affected.

**Comment by mrakitin** [comment]
I see Rob, thanks for the explanation.

**Comment by robnagler** [comment]
alpha is upgraded. Note that the server didn't come up on reboot. I suspect it was the celery check. Need to put a loop in.
