### ISSUE TITLE
20230110 USPAS Radia Demo

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#5281]
There will be a demo, given by @j-edelen at the Winter USPAS,  of the Sirepo interface for Radia. The demo will most likely be on  Friday, January 27th. From discussion with @mkeilman, ideally any changes that need to be made should be completed by January 20th.

This issue should be used to collect any issues that need be completed and on production for the demo. 

Key Issues:
- [x] https://github.com/radiasoft/sirepo/issues/5271 
- [x] https://github.com/radiasoft/sirepo/issues/5238 - For this I know the plan is to resolve it with a larger rework of the interface. If that rework can't comfortably be completed in time it's probably best just to make sure the demo avoids this issue if possible.
- [x] #5282 - Same as above

**Comment by cchall** [comment]
I'm not sure if this is what we will use, but the quadrupole magnet demo is almost fully functional on production (just needs #5237):
https://www.sirepo.com/radia#/source/IaQzs5SS

**Comment by robnagler** [comment]
I changed the target to 1/10/23, because that would the last alpha before 1/16, which is the last prod before 1/20.
