### ISSUE TITLE
Apply symmetry sometimes has  no save/cancel button

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#5282]
This normally seems to occur the first time you try to apply a symmetry to a group, in my experience.
I think this will probably be fixed by #4711. I think it's still important to note since it could come up during the USPAS demo if not (#5281)

![image](https://user-images.githubusercontent.com/17073688/208750045-c3973682-41a1-49d0-af69-1e33764b40ed.png)

**Comment by mkeilman** [comment]
Fixed via https://github.com/radiasoft/sirepo/pull/5307
