### ISSUE TITLE
Polarization of Bending Magnet: realloc failed for wavefront

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#53]
I got this when running http://alpha.sirepo.com/srw#/beamline/hXzdfTHA

```text
External (callback) function falied[sic] to modify (/ reallocate memory for) wavefront data
```

**Comment by moellep** [comment]
This was caused by a bug introduced in fix for #16. Now the photonEnergy field no longer requires updates across models and only exists on the "simulation" model.
