### ISSUE TITLE
20221230 cache max-age=31536000?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5306]
template_common.sim_frame sets max-age to a year. I consider unreasonably large. http_reply.CACHE_MAX_AGE is 43200, which seems more reasonable.

@moellep is there a problem with getting new frames after a day?

**Comment by moellep** [comment]
How about 1 week? It is a unique cache, so it shouldn't cause stale data.

**Comment by robnagler** [comment]
What's the use case?

**Comment by moellep** [comment]
The use case would be a physicist has created a simulation with an animation which they want to share in a webinar in the coming days, and avoid waiting for the frames to be recalculated on the server during the demonstration.

**Comment by robnagler** [comment]
> avoid waiting for the frames to be recalculated on the server during the demonstration.

I just did this:

- visited warppba laser pulse dynamics
- clicked start simulation
- waited it for it to finish
- cleared all history and quit the browser
- visited warppba laser pulse
- all the images were there quite quickly (over a hot spot)

I do not think the browser cache inhibits this use case at all. There's a delay on playback which has enough time to fetch the images. Most demos are done over faster links than I'm on right now. Even if none of the images are cached, it will still play back just fine.

**Comment by robnagler** [comment]
will be fixed along with #5296
