### ISSUE TITLE
20230105 template/jspec.py:241:sim_frame_particleAnimation 1672952983

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5334]
The value of page_index is a timestamp, which is causing this exception:

```txt
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 249, in _do_get_simulation_frame
    msg.data.copy().pkupdate(run_dir=msg.runDir),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 662, in sim_frame_dispatch
    res = o(frame_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/jspec.py", line 242, in sim_frame_particleAnimation
    filename = _ion_files(frame_args.run_dir)[page_index]
IndexError: list index out of range

Exception was printed at:

IndexError: list index out of range
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 33, in <module>
    sys.exit(load_entry_point('sirepo', 'console_scripts', 'sirepo')())
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main("sirepo")
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 158, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 51, in default_command
    msg, sirepo.template.import_module(msg.simulationType)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 231, in _do_fastcgi
    m, sirepo.template.import_module(m.simulationType)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 252, in _do_get_simulation_frame
    return _maybe_parse_user_alert(e, error="report not generated")
', 'state': 'error'}}
```

**Comment by moellep** [comment]
This ties in with replacing singleFrameAnimation. I think the server should not just return frameCount, but something more descriptive.

The server should return a list of report model names which are available to plot, and for each of them either a frameCount or a lastModifiedTime.

In this particular case, the client should not be requesting the particle plot because the "DC Cooling Example" does not produce that report.

**Comment by garsuga** [comment]
We can solve the need to have "frameCountFieldName" in the schema with this too. Server should return one object for each of the reports. We can place all of the description needed for each of these in an object so we do not need to keep track of names.

**Comment by robnagler** [comment]
Great, thanks. #4177 is relevant as well as https://github.com/radiasoft/sirepo/pull/5301#discussion_r1061844334

**Comment by moellep** [comment]
Here's an example of what genesis currently returns.
```json
{
    "state": "completed",
    "dbUpdateTime": 1672954104,
    "elapsedTime": 5,
    "computeJobHash": "HashIsUnused",
    "percentComplete": 100,
    "frameCount": 1,
    "lastUpdateTime": 1672954103,
    "computeJobStart": 0,
    "particleFrameCount": 23,
    "fieldFrameCount": 16,
    "computeJobSerial": 1672954096,
    "computeModel": "animation"
}
```

Instead, it could be something like this.  I don't have a preference for the format, so if different names, or structure would be better, please suggest it.
```json
{
    "state": "completed",
    "dbUpdateTime": 1672954104,
    "elapsedTime": 5,
    "computeJobHash": "HashIsUnused",
    "percentComplete": 100,
    "lastUpdateTime": 1672954103,
    "computeJobStart": 0,
    "computeJobSerial": 1672954096,
    "computeModel": "animation",
    "reports": [
        {
            "modelName": "fieldDistributionAnimation",
            "frameCount": 16
        },
        {
            "modelName": "parameterAnimation",
            "lastUpdateTime": 1672954103
        },
        {
            "modelName": "particleAnimation",
            "frameCount": 23
        }
    ]
}
```

**Comment by robnagler** [comment]
I think we should have `state` at the outer level and `result` or `error` and `version`. `result` and `error` would be typed entities. We could even have `resultType` to be verified. There might be other values at the outer level like `inReplyTo`. 

Requests should be similarly structured.

**Comment by moellep** [comment]
I've made an example branch which implements this for jspec:
https://github.com/radiasoft/sirepo/tree/5334-sim-status

This removes the frameCountFieldName and singleFrameAnimation config and uses values compute on the server instead. 

The values come back as

```json
  "result": {
        "reports": [
            {
                "modelName": "beamEvolutionAnimation",
                "lastUpdateTime": 1673040835
            },
            {
                "modelName": "coolingRatesAnimation",
                "lastUpdateTime": 1673040835
            },
            {
                "modelName": "particleAnimation",
                "frameCount": 5
            }
        ]
    },
```

and are stored on each report's AnimationReader as frameCount and hasAnimationControls.

**Comment by robnagler** [comment]
How do you know that a report is updated if all you have is frameCount?

Each report needs some sort of hash that lets the UI know it needs to be refreshed. There are report parameters and then there's the hash for the computeJob.

"result" should not come from template.jspec. That word is part of the protocol. APIs (for better or worse) raise an exception when there is an error.

**Comment by moellep** [comment]
Each frame request includes a last update time from the server. That value + the frameCount determines whether to get a new plot.

The "result" part in jspec is just to model the reply for the client for future server changes.

**Comment by robnagler** [comment]
This needs to include lastUpdate.

```
            {
                "modelName": "particleAnimation",
                "frameCount": 5
            }
```

Also since we are changing the protocol, can we call it lastUpdate and not lastUpdateTime?

**Comment by moellep** [comment]
The lastUpdateTime is at the outer level already, so it shouldn't be included in each report. I don't know how it is computed on the server. For individual reports, it uses either frameCount or provides the last time a specific data file was updated.

**Comment by robnagler** [comment]
It's not in the example you provided. What do you mean by "outer level"?

**Comment by moellep** [comment]
The full response which is used by the client is below. I think we should be taking baby steps to get the response to all be within the "result" part.
```json
{
    "state": "completed",
    "dbUpdateTime": 1673287682,
    "elapsedTime": 17,
    "percentComplete": 100.0,
    "computeJobHash": "HashIsUnused",
    "computeJobStart": 0,
    "lastUpdateTime": 1673287682,
    "result": {
        "reports": [
            {
                "modelName": "forceTableAnimation",
                "lastUpdateTime": 1673287682
            },
            {
                "modelName": "beamEvolutionAnimation",
                "lastUpdateTime": 1673287682
            },
            {
                "modelName": "coolingRatesAnimation",
                "lastUpdateTime": 1673287682
            },
            {
                "modelName": "particleAnimation",
                "frameCount": 7
            }
        ]
    },
    "computeJobSerial": 1673287664,
    "computeModel": "animation"
}
```
