### ISSUE TITLE
20220109 cloudmc to prod with paramak example

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5337]
Cloudmc is ready to enable on production, but needs at least one example, the paramak reactor. The external lib file problem needs to be solved for this.

**Comment by robnagler** [comment]
geometryInput-dagmcFile.reactor.h5m should be [compresssed with h5py](https://docs.h5py.org/en/stable/high/dataset.html#filter-pipeline). The file is small enough to be added to the repo. 

Oddly, the default compression (-4) is better than the best (-9):

```txt
$ ls -sk geometryInput-dagmcFile.reactor.h5m
2396 geometryInput-dagmcFile.reactor.h5m
$ gzip -9 geometryInput-dagmcFile.reactor.h5m
$ ls -sk geometryInput-dagmcFile.reactor.h5m.gz
576 geometryInput-dagmcFile.reactor.h5m.gz
$ gunzip geometryInput-dagmcFile.reactor.h5m.gz
$ gzip -4 geometryInput-dagmcFile.reactor.h5m
$ ls -sk geometryInput-dagmcFile.reactor.h5m.gz
568 geometryInput-dagmcFile.reactor.h5m.gz
```

**Comment by moellep** [comment]
Using "h5repack -f GZIP=9" seems to work best in this case:
```shell
$ h5repack -f GZIP=4 geometryInput-dagmcFile.reactor.h5m out4.h5m
$ ls -sk out4.h5m
632 out4.h5m
$ h5repack -f GZIP=9 geometryInput-dagmcFile.reactor.h5m out9.h5m
$ ls -sk out9.h5m
620 out9.h5m
```

```
