### ISSUE TITLE
Reading csv files is not robust

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#5389]
radia uses the python csv package to read and parse e.g. points files. This often fails, probably due to encoding variations in the files. We should handle this properly, perhaps by using pandas.

**Comment by mkeilman** [comment]
Attaching the troublesome file that engendered this issue
[quad_pole2_bad.csv](https://github.com/radiasoft/sirepo/files/10524404/quad_pole2_bad.csv)

**Comment by mkeilman** [comment]
Another note that the primary failure mode is converting csv contents to float, e.g.
```python
   pts = []
    with open(path, "rt") as f:
        for r in csv.reader(f):
            pts.append([float(x) for x in r])

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
```
For the attached file this is from trying to convert a leading EFBB to float. The codecs snippet above gives a similar error.

**Comment by robnagler** [comment]
You might also try to open in utf8. `rt` doesn't assume unicode afaik.

**Comment by mkeilman** [comment]
> Did you try `codecs.open(str(path), "rb", "cp1252")`?

Yes:
```
ValueError: could not convert string to float: 'ï»50'
```
I've tried utf-8 and utf-8-sig, the latter of which is supposed to skip the BOM. Both fail. Actually I think the example file may just be corrupt, because the BOM is EFBBBF, not just EFBB. When I add the "missing" BF then utf-8-sig works (cp1252 still does not).

btw I also tried using charset_normalizer but it returned the Chinese Big5 encoding...

**Comment by robnagler** [comment]
Then, Radia has a bug you should report that. Maybe look at the code first to see if it is obvious how to fix it.

**Comment by mkeilman** [comment]
> Then, Radia has a bug you should report that. Maybe look at the code first to see if it is obvious how to fix it.

Oh, to clarify, this has nothing to do with Radia. Jon supplied the offending file. I think he said he wrote it from a notebook - I'll ask at the mpmd meeting.

**Comment by robnagler** [comment]
Got it. Then, we should provide a better UX by catching the exception and reporting: corrupt file.
