### ISSUE TITLE
20230118 database is locked

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5390]
Many requests are failing on production with the error:
``` “sqlite3.OperationalError: database is locked”```

**Comment by moellep** [comment]
Of the options from this post, our best short-term option might be to increase the timeout until the problem can be isolated:
https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked

**Comment by robnagler** [comment]
Related #5393. I can't reproduce the locking problem at all. Here's an example: http://richard.to/programming/db-locks-on-long-reads-with-sqlite3.html  but the record counts are huge (cross joining across 5 x 1e6 tables). We have nothing like that. 

I just looked through all our transactions. There's only one that was potentially keeping [a connection with an open cursor](https://github.com/radiasoft/sirepo/blob/cbbca216564d62afad24f29193033270950f5c39/sirepo/auth_db/__init__.py#L158), and that was only used in a pkcli.

I'll add a timeout.

**Comment by robnagler** [comment]
We discovered session_t was 4M records. This was due to a bug in how it worked. It still isn't quite right so #5397 will remove spa_session_t until we have a real db server and websockets are in use (garbage collect sessions).
