### ISSUE TITLE
improve srw zip directory structure

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5406]
When exporting the srw zip file, create a directory structure like this (using the CHX tabulated undulator simulation as an example):
- sirepo-data.json
- run.py
- input_files/
    - mirror_1d.dat
     - magn_meas_chx.zip
- NSLS-II_CHX_beamline_tabulated/

In run.py, the "fdir" value should be set to something related to the simulation name, for example the "NSLS-II CHX beamline (tabulated)" would have this setting:
```
#---Data Folder
    ['fdir', 's', 'NSLS-II_CHX_beamline_tabulated', 'folder (directory) name for reading-in input and\
 saving output data files'],
```

Mirror files should have the "input_files" directory prepended, for example:
```
    # HDM: mirror
    ['op_HDM_hfn', 's', 'input_files/mirror_1d.dat', 'heightProfileFile'],
```

**Comment by ochubar** [comment]
In this example, can "input_files" directory simple be merged with the "NSLS-II_CHX_beamline_tabulated" directory, where all input and output files would be stored? This seems to be more compliant with how we use SRW under Python without Sirepo. I.e., I have "srw_python" directory where all SRW files and the simulation script (equivalent to "run.py"?) are located; and all input/output files of a given simulation are located in a corresponding sub-directory (*CHX*, etc.).
One may also need to asses how all this will have to work on Perlmutter (see comment of rnagler).
