### ISSUE TITLE
improve NERSC unavailable message

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5411]
When a simulation is using NERSC, and the user is asked to login and NERSC is unavailable, an appropriate error message should be displayed, and no reports should show "requesting data".

**Comment by ochubar** [comment]
Yes! 
Please also check / consider providing more clear explanations for other situations at NERSC, e.g. when a task is in the queue (not started yet), when a simulation has started, but no output file was yet generated, etc.
