### ISSUE TITLE
20230213 tally results minor issues

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5444]
The Tally Results panel has a few minor issues:

- [x] when the Visualization tab is first visited, the 3D view is shown, but neither the 2D or 3D tab is shown as selected. Clicking on the 2D and back to 3D shows how it should display initially
- [x] The 2D slice slider is showing 1 too many slides - the last two are the same value. For example, the Tokamak Reactor example, t1 tally has 2 mesh count in the y dim, but there are 3 choices in the slider for the y axis. Maybe it should show the axis slice at the middle of the row, ex. in this case it has 2 cells between 0cm and 20cm, so it should have a slider values of 5cm and 15cm, rather than 0, 10, 20.
- [x] The plot should use an aspect ratio for odd sizes, ex. the t1 tally on the x axis has a dimension of 2x150 and doesn't show well in the browser. The server can specify the aspectRatio to use in the reply to the heatmap. _MVK_: the aspect ratio is correct. It's the overall scaling that needs to adjust to fit better.
- [x] The user should be able to select the horizontal and vertical range to plot.

**Comment by mkeilman** [comment]
Are there hours for more cloudmc work, and actual calendar time?
