### ISSUE TITLE
SRW - create a new type of simulations with an arbitrary source

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#545]
Request from @ochubar:
> Need to create a new type of simulations with the source represented by an arbitrary magnetic field from a file.

**Comment by mrakitin** [comment]
This is an important issue, and should possibly attract more users.

**Comment by mrakitin** [comment]
I think this source can be implemented along with a dual undulator (#601).

**Comment by mrakitin** [comment]
Decrease the priority since the merge https://github.com/ochubar/SRW/pull/7/files hasn't been done yet.

**Comment by moellep** [comment]
Fixed with ee37fc2.
