### ISSUE TITLE
20230330 multipanel reports should have individual png download

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5462]
For a collection of reports displayed in a single panel, there should be an option to download each plot individually, or as a whole.

**Comment by robnagler** [comment]
They didn't want as a whole. That can just be a screenshot. The resolution will be good enough for the whole page.

**Comment by moellep** [comment]
I think they do want all reports as a whole as well - that is what their existing software produces.

**Comment by robnagler** [comment]
On the call, they said they would do that with a screenshot. It seems like a separate issue anyway, and a "nice to have" and unnecessary for the deadline.
