### ISSUE TITLE
shadow in react

### ISSUE THREAD

**Issue by garsuga** [radiasoft/sirepo#5464]
I may need to extend this issue depending on how creating the beamlines goes.

**Comment by moellep** [comment]
Rob and I were discussing this just now. Initially, we can defer the drag-and-drop part. If you click on an icon in the toolbar, it should add the element to the end of the beamline. Modifying the element's position field in the editor would reposition the items without requiring drag-and-drop. Adding a popup form editor would still be needed when editing the individual beamline elements.
