### ISSUE TITLE
20230630 nuline image + parameters to image example

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5477]
An interesting example could be:
- predict the output intensity of a beamline from the initial beam distribution + some parameter settings

For example, a shadow simulation with the initial beam data, the settings of several apertures and mirrors, and the final beam data.

**Comment by gurhar1133** [comment]
@moellep do we have a dataset for this one?

**Comment by moellep** [comment]
Here's a dataset which could be used:
https://alpha.sirepo.com/activait#/data/Rd5b1amo
We want to have the metadata/control_settings as the input and images as the output.
I don't know of a good ML model to perform this, so some searching will be needed.

**Comment by gurhar1133** [comment]
> Here's a dataset which could be used: https://alpha.sirepo.com/activait#/data/Rd5b1amo We want to have the metadata/control_settings as the input and images as the output. I don't know of a good ML model to perform this, so some searching will be needed.

to clarify

input = metadata/control_settings + initial beam position
output = beam position image
?

**Comment by moellep** [comment]
The inputs in this example would be the two control_settings values, and the output would be an image showing the expected result. The reverse of an image to settings training.
