### ISSUE TITLE
Check for NERSC account fails incorrectly

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#5491]
In `job_agent._sbatch_script()` this call is made:
```python
o = subprocess.check_output(["hpssquota"], text=True)
assert re.search(
    r"{}\s+\d+\.".format(p), o
), f"sbatchProject={p} is invalid. hpssquota={o}"
```
The `hpssquota` command on NERSC yields e.g.:
```bash
+-----------------------------------------+------------+-------------+----------------+------------+-------------+----------------+
|                             File system | Space used | Space quota | Space used (%) | Inode used | Inode quota | Inode used (%) |
+-----------------------------------------+------------+-------------+----------------+------------+-------------+----------------+
|                                    home |  822.75MiB |    40.00GiB |           2.0% |     30.84K |       1.00M |           3.1% |
|                                cscratch |    3.68MiB |    20.00TiB |           0.0% |     124.00 |      10.00M |           0.0% |
| mkeilman usage on HPSS charged to m4091 |      0.00B |     7.20TiB |           0.0% |          - |           - |              - |
+-----------------------------------------+------------+-------------+----------------+------------+-------------+----------------+
```
which does contain the valid account m4091 but is not found by the regex. The fancy table is new; `re.search(r"{}\s+\|?\s+\d+\.".format(p), o)` catching the pipe (optionally) works, or running `hpssquota --space` to output the old format and keep the regex the same. There are also options to output JSON (`hpssquota -J`) and other formats if that is more robust

**Comment by robnagler** [comment]
hpssquota -J may be the way to go even though more complex.

**Comment by mkeilman** [comment]
> hpssquota -J may be the way to go even though more complex.

One can also specify the account with "hpssquota <account>" which fails on an unknown account:
```
2023-02-17 08:15:52,153 [ERROR] Subprocess '/usr/lpp/mmfs/bin/mmlsquota -Y -j NO_SUCH_ACCOUNT cfs' failed: NO_SUCH_ACCOUNT: no such fileset in quota enabled file systems
mmlsquota: tslsquota  -Y -j NO_SUCH_ACCOUNT  cfs.nersc.gov:/dev/cfs failed. Error code 22.
mmlsquota: Command failed. Examine previous error messages to determine cause.
```
We can check for some portion of that error message ("no such fileset in quota enabled file systems" perhaps)

**Comment by mkeilman** [comment]
I've been reading the docs and showquota/hpssquota is actually a python script, and NERSC explicitly talks about [incorporating it ](https://docs.nersc.gov/filesystems/quotas/#quota-tools)

`showquota` is a Python script, and has been designed with composability in mind, so you can use it in your own Python scripts by making it available in your `$PYTHONPATH` variable, e.g.:
```bash
$ PYTHONPATH="$(dirname $(which showquota)):$PYTHONPATH"
```
Could be the best option?

**Comment by robnagler** [comment]
You can't just add something to a PYTHONPATH. This needs to match python and package versions, which is not likely.

We can use showquota if it's output is easier to parse. I kind of doubt that.

To test any of this, mock the system call by creating it as a separate method and writing a unit test that calls pkcli.job_agent.validate_nersc_project. Better yet, move the nersc_project code out into a separate module, e.g. sirepo.nersc.assert_project(project) as it should be pluggable and not hardwired like it is.

**Comment by mkeilman** [comment]
Turns out hpssquota and showquota are the same thing:
```
lrwxrwxrwx 1 swowner swowner        9 Oct  6 17:30 hpssquota -> showquota
-rwxrwxr-x 1 swowner swowner    41082 Nov 29 20:07 showquota
```
Anyway I'll proceed with parsing

**Comment by mkeilman** [comment]
Reopening as the fix generates a new error now that it's on alpha:
```
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 2
54, in _op
    return await getattr(self, "_op_" + m.opName)(m)
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 2
88, in _op_run
    return await self._cmd(msg)
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 3
24, in _cmd
    await p.start()
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 7
02, in start
    ("sbatch", self._sbatch_script()),
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 7
68, in _sbatch_script
    {sirepo.nersc.sbatch_project_option(self.msg.sbatchProject)}"""
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/nersc.py", line 21, in sbat
ch_project_option
    raise sirepo.util.UserAlert(f"Cannot determine quota for {project}; error={e}")
sirepo.util.UserAlert: UserAlert(error=Cannot determine quota for m4091; error=the JSON object must be str, bytes or bytearray, not C
ompletedProcess)
```
Similar to #5533 the user alert gets swallowed up - I had to check the job agent log to see the problem.
