### ISSUE TITLE
SRW - feedback options for full parallel queue

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#550]
If the parallel queue is full, provide feedback to the user, possibly allowing them to run the simulation in the serial queue.

**Comment by mrakitin** [comment]
A possible drawback in case of using the serial queue is that the simulation will be limited by the foreground time limit (5 minutes by default), which is not suitable for long-lasting Flux simulations. Need to think about it.

**Comment by robnagler** [comment]
Some simulations support sequential vs parallel. Job supervisor can route appropriately, but this has not been a user request for 3 years so closing.
