### ISSUE TITLE
SRW - convert fix-ups to a db-upgrade

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#551]
Rather than apply data fix-ups on demand, it would be better to have a db-upgrade which gets run (manually) with new releases. The db-upgrade would apply the necessary fix-ups to the files and could also do additional tasks, such as copy new example files into a user's repository or update the user's library files.

We have an existing "sirepo exec_bash" feature which allows entering into the container to run commands. This could be used to enter the container, and then apply the fix-ups across all user data files prior to restarting the service.

**Comment by robnagler** [comment]
Given that we have import/export, I don't think we can have a one-shot db upgrade. If a user imports a zip (self-extracting or regular), the data needs to be fixed up to the most recent db version. 

For fixups like renaming directories (warp => warppba), we need a db upgrade of a different along with a fixup.

**Comment by moellep** [comment]
The fixups need to remain because a user could import a dataset with an old schema. I'll open a new ticket for the "copy new example files" item.
