### ISSUE TITLE
don't "nice" the vtk axes domain

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5511]
The vtkAxes directive is calling "nice()" on the axis, but the vtk geometry isn't being adjusted to that new scale. Either the vtk geometry should be adjusted, or the axes should be normal.

For example, in OPAL, the "Los Alamos Proton Storage Ring" 3D Beamline on the Visualization page is displaying incorrectly. The beamline starts at (0, 0), but that point is not within the ring:
![bad](https://user-images.githubusercontent.com/6516910/221321829-908075aa-888d-4281-8fa9-6bdf3733f312.png)

With the nice() removed, the (0, 0) point is correctly at the start of the drift within the actual beamline.
![good](https://user-images.githubusercontent.com/6516910/221321840-cfcb18d0-0779-4831-b9c7-593aa9c13c7b.png)

**Comment by moellep** [comment]
This would probably fix #4834 as well.

**Comment by mkeilman** [comment]
@moellep can I get that simulation to use as a reference? I don't see it in the examples

**Comment by moellep** [comment]
It is a relatively new example - run "sirepo admin create-examples" on your dev system and it should show up.
