### ISSUE TITLE
inconsistent menu "Run Simulation as Shadow" not in source menu

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5515]
<img width="510" alt="Screen Shot 2023-02-27 at 4 09 44 PM" src="https://user-images.githubusercontent.com/5495179/221710122-95d421f3-b2c5-4ab2-aa4f-7d13e937a026.png">
<img width="518" alt="Screen Shot 2023-02-27 at 4 09 31 PM" src="https://user-images.githubusercontent.com/5495179/221710124-55297471-2c8d-426c-8ed4-edbd554ce31c.png">

**Comment by gurhar1133** [comment]
@robnagler just confirming we want 'Open as a New Shadow Simulation' in the source menu as well?

**Comment by moellep** [comment]
Yes, I think we want it both place. I think the menu item should be hidden if the beamline contains no items.

**Comment by gurhar1133** [comment]
> Yes, I think we want it both place. I think the menu item should be hidden if the beamline contains no items.

And do we want it on the machine learning tab too?

**Comment by moellep** [comment]
Yes, it is just a general menu item, and should always be there if the beamline has elements.
