### ISSUE TITLE
SRW - allow deleting unused magnetic measument and mirror files

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#552]
Provide a way to delete simulation data files, similar to the way user beams can be deleted. A confirmation dialog would be shown, and if the data file was in use by a different simulation, the simulation name would be shown and the file would not be delete-able.

**Comment by mrakitin** [comment]
I got a request from NSLS-II ID group scientist asking to implement this issue ASAP. They work intensively with the magnetic measurements, and it's inconvenient to upload new files instead of replacing them.

**Comment by mrakitin** [comment]
This may be a priority before the demo at NSLS-II if it's easy/fast to implement. Otherwise it can be addressed later.

**Comment by moellep** [comment]
Allow standard mirror and magnetic measurements files to be replaced by user, with a warning message. When "Discard Changes to Example" is selected, the standard file will be restored.
