### ISSUE TITLE
cylinder geometry setup

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#5534]
The setup for a cylinder gives independent fields for the size
<img width="934" alt="image" src="https://user-images.githubusercontent.com/17073688/223161028-b6aff381-3d43-405d-b98a-511d20829c10.png">

However the cylinder size is just parameterized by a single height along the extruded axis. It looks like the interface does correctly handle this in that only the size along the extruded axis actually changes anything, but this should probably just be reduced to a single field to avoid confusion here.

**Comment by mkeilman** [comment]
@cchall can you confirm this is fixed?

**Comment by cchall** [comment]
Looks good now!
