### ISSUE TITLE
react refresh doesn't work

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5561]
If you are on a page and refresh the browser, it tries to get the full URL which returns a filenotfound, and that redirects to the landing page. The server should probably just return index.html for anything matches some structure, e.g. /jspec/simulations. The problem is that we also get frames and other things the same way. This may be why anchor based local routes are used: the server doesn't see the local route.  We could solve this with some other tag, e.g. /jspec/ui/simulations, but this is not pretty. We can't change the existing URIs because they are widely used.

Not sure best way to solve this. @garsuga @moellep ideas?

**Comment by garsuga** [comment]
I thought I fixed this in #5545, I will check to see if its still an error

**Comment by robnagler** [comment]
Easily reproducible: bash etc/run-react-build.sh and refresh on the simulations page. 

It doesn't happen in dev mode. The react dev server seems to do too many clever things. We certainly need to run in production build mode more often.

**Comment by robnagler** [comment]
This is still a problem.
