### ISSUE TITLE
math bug in variable input field

### ISSUE THREAD

**Issue by phr0gger** [radiasoft/sirepo#5572]
I_to_K1 is not evaluated correctly here. It should be 2.71146!
Is it a RPN mixup or should I avoid E as a variable name?

![SirepoVariableInputBug](https://user-images.githubusercontent.com/47429373/225132510-a853e1ce-8062-48d4-8c07-16c96744be42.png)

**Comment by moellep** [comment]
Thanks for pointing this out. There is a bug with the variable editor which was also reported in #5564. The fix for this will be available next week on sirepo.com. I'll notify you via this issue when this is resolved.

**Comment by moellep** [comment]
This bug fix has now been released. @phr0gger, please let us know if you encounter any other problems.
