### ISSUE TITLE
unpin flask/werkzeug

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#5581]
See if it resolves the "Popped wrong request context" bug. https://github.com/radiasoft/sirepo/issues/5016

For reference this is why we originally pinned https://github.com/radiasoft/sirepo/issues/4320

**Comment by robnagler** [comment]
Did we actually turn off keep alives on http like it says in the last comment on #4320?

**Comment by e-carlin** [comment]
No, we pinned to 2.0.3 (last version before 2.1). So we were using http/1.0 which doesn't have keep-alive https://github.com/pallets/werkzeug/issues/2380#issuecomment-1089015855 . 

If we unpin the versions we will have to either disable keep-alive on requests or set flask config to use http/1.0. Do you have a preference?

**Comment by robnagler** [comment]
Since it is only development mode (and local installs), do what is easiest. Let's maybe run 2.1 in default mode to see what happens.

**Comment by e-carlin** [comment]
We haven't seen the popped wrong context bug in some time. So whatever we have now seems to work and we're making progress towards ditching Flask.
