### ISSUE TITLE
Fix rshellweg Parameter Report

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#5601]
```
The angularjs app works pretty well with the exception of the
Parameter Report on the Visualization tab. That report depends on
BeamSolver.load_bin() and that does not work, probably because the
dump file contains cpp pointer values. I verified that you can't
import a dump into the Windows app either.

One work-around would be to extract all the Parameter Report data
right after hellweg runs.
```

**Comment by e-carlin** [comment]
@moellep I have everything working except for 2 plots

## Energy
When showing energy on the parameter report Sirepo shows the difference between Maximum and Average Energy 
![Screen Shot 2023-03-23 at 2 22 31 PM](https://user-images.githubusercontent.com/10264515/227344365-7480327b-926f-482d-8e92-6c609cd0664f.png)

Whereas Hellweg.exe just shows a line for the average and maximum energy

![Screen Shot 2023-03-23 at 2 25 54 PM](https://user-images.githubusercontent.com/10264515/227345531-e70898fa-bb65-4d05-b1ad-14de11040d6a.png)

I'm not sure why Sirepo is doing this or if this behavior is desired?

## Radius
The plots have the same shape but the y-axis is different between Sirepo and Hellweg.exe. I verified that Sirepo gives the same numbers regardless of reading from all-data.bin or pulling the data from the solver after the simulation has run. I tried loading all-data.bin from Sirepo in Hellweg.exe but I got math errors and none of the plots looked right. I can't get Hellweg.exe to produce an output file that Sirepo is able to read. Any idea what's going on with the plot?
![Screen Shot 2023-03-23 at 4 17 40 PM](https://user-images.githubusercontent.com/10264515/227378079-eb83d8eb-3e15-4ae8-8a6d-076b33cc8d25.png)
![Screen Shot 2023-03-23 at 4 18 02 PM](https://user-images.githubusercontent.com/10264515/227378102-3d7a9cd9-0776-45c1-8bb3-fc2c785e7e24.png)

**Comment by e-carlin** [comment]
If it helps here is my working branch for the Sirepo changes https://github.com/radiasoft/sirepo/tree/5601-hellweg-parameter-report and here is the branch for my RSHellweg changes https://github.com/radiasoft/rshellweg/tree/158-load-bin-segfault (install with `CFLAGS=-I/home/vagrant/.local/include/ pip install .`).

**Comment by moellep** [comment]
Great - I'll take a look at these reports.

**Comment by moellep** [comment]
The Energy report in sirepo is correct - notice on the hellweg energy report all the y axis tick values are 0.03 - sirepo shows the differences from the average to avoid that.

The sirepo Radius report is off by 2x - I found the spot in hellweg where the adjustment is made:
https://github.com/radiasoft/rshellweg/blob/master/src/gui/ResultsForm.cpp#L451

I'll fix this and get the changes into the sirepo branch.
