### ISSUE TITLE
field on path displays wrong data after changing plot axis

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#5603]
Plotting field on a line (after running Solve) along the default z axis returns correct looking results. If the plotting axis is changed the fields shown change and seem to be taken from an unsolved magnet model.

**Comment by mkeilman** [comment]
@cchall do you have an example, with what you see vs what you expect?

**Comment by cchall** [comment]
It looks like this is still occurring. I just had it happen on a newly created simulation on Prod.

Solver was run, plot set up, plotting axis changed. Field is too low.
![after_solve_1](https://github.com/radiasoft/sirepo/assets/17073688/3dbf05f6-8bd7-4c3f-a1a7-7ec41a58374c)

Re-run solve, plot looks as expected now.
![solve_was_run_2](https://github.com/radiasoft/sirepo/assets/17073688/70ef4951-1755-446e-8cff-571abd24b7ea)

**Comment by cchall** [comment]
I just set up the simulation from scratch and saw the same problem.
- Completed geometry setup in the design tab. Switched to Viewer once in the middle of setup to check the setup of the elements. Switched back to Design until finished.
- Changed to Viewer, waited for 3D visualization to load.
- Ran solve and waited to finish.
- Set up line plot specification. Made sure Sirepo logo was not spinning on 3D visualization anymore (started after solve was run).
- Saved line parameters and waited for line plot. Result is not from solved model:
![image](https://github.com/radiasoft/sirepo/assets/17073688/7d9fe19b-c5e3-4a55-b1e6-b67c4cd0f344)

**Comment by mkeilman** [comment]
I can reproduce this with some regularity, and one thing I note is that the first solve does not "take"; if I view the magnetization I see that it is unchanged afterward. Subsequent solves work fine. This is irrespective of whether a field path has been defined.
