### ISSUE TITLE
Setting up a development environment /testing environment 

### ISSUE THREAD

**Issue by scawsome** [radiasoft/sirepo#561]
Hello all, I am a PBPL grad student who would like to contribute to the elegant part of sirepo. I have forked sirepo to my own account but I need help setting up a development environment /testing environment. I have a couple of small ideas for changes to start with but I'll create a separate issue for each one. Any guidance would be helpful.

**Comment by robnagler** [comment]
Welcome @scawsome! Do you have Vagrant/VirtualBox setup? If not, please try [these instructions](https://github.com/radiasoft/download/blob/master/README.md#requirements).

**Comment by bruhwiler** [comment]
@scawsome -- can we close this issue?

Thanks,
David

**Comment by scawsome** [comment]
Yes.
Ryan
