### ISSUE TITLE
raydata.file_reply_tmp_dir 

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#5612]
https://github.com/radiasoft/sirepo/issues/5590#issuecomment-1487471883

RequiredUnlessDev isn't the best choice for this configuration parameter. In cases where raydata isn't a configured sim_type it will still be a required bit of configuration. I think the logic in _tmp_dir (it's type) is enough.

**Comment by robnagler** [comment]
> raydata isn't a configured sim_type it will still be a required bit of configuration

This shouldn't be the case. If raydata isn't a sym_type, nothing should be imported.

**Comment by e-carlin** [comment]
> This shouldn't be the case. If raydata isn't a sym_type, nothing should be imported.

The configuration is in feature_config so it is before import of a sim_type. It is used through [feature_config.for_sim_type in job_cmd](https://github.com/radiasoft/sirepo/blob/master/sirepo/pkcli/job_cmd.py#L107). So, there is nowhere presently where we could put it behind an import. Any suggestion on where to put it that would be better?

**Comment by robnagler** [comment]
I don't understand the use. I left a comment
