### ISSUE TITLE
improve omega report headings and plotting calls

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5634]
Below is a good example which can be created on dev by running the OPAL AWA Photoinjector followed by the elegant PSR example.
![x](https://user-images.githubusercontent.com/6516910/229574735-5da76d91-3f50-4f26-9337-131de315e0a9.png)

The headings should be consistent across the plots - so instead of showing the OPAL-specific title "Step 0, SPOS 5.0m", it should show "Horizontal/Vertical/..." like the elegant reports. This could be done by calling opal to format the plot, but then changing the title before it is returned from the omega app.

Also part of this issue - currently the calls to format the plots for OPAL or elegant are invoking private methods on the templates, ex:
```python
    if sim_type == "opal":
        import sirepo.template.opal

        return sirepo.template.opal._bunch_plot(
            frame_args,
            frame_args.run_dir.join(run_dir),
            frame_args.frameIndex,
        )
    if sim_type == "elegant":
        import sirepo.template.elegant

        return sirepo.template.elegant._extract_report_data(
            str(frame_args.run_dir.join(f"{run_dir}/run_setup.output.sdds")),
            frame_args,
        )
```
Instead these plotting routines should be made public on the templates (bunch_plot() vs _bunch_plot()) and all the cases which call these methods should be updated.

**Comment by moellep** [comment]
Rather than "px (#beta#gamma)" labels:
Let's use units of beta_x gamma and beta_y gamma for the two transverse planes. I assume rendered using the greek letters.

**Comment by rorour** [comment]
Does this mean `px (#beta#gamma)` -> `β_x γ` and `py (#beta#gamma)` -> `β_y γ`? Does this also apply to `pz (#beta#gamma)`? Sorry, not sure what you mean by the two transverse planes
