### ISSUE TITLE
Beamline drop downs not opening on Firefox 43.0.4 on Windows 7

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#57]

**Comment by robnagler** [comment]
Seems to not work in Chrome either

**Comment by moellep** [comment]
I was able to use the beamline element dropdowns on Windows 7 Firefox 44.
It also worked on a much older version of Firefox (version 28). If it isn't
working on Chrome, I would guess that it is a data problem rather than a
general problem. If possible, let me know the simulation ID.

Paul

**Comment by robnagler** [comment]
Look for refreshes around the time of the original message in the logs. It
was probably Youngs Double Slit. I was accessing too from a Mac so Timur's
PC should be clear in the logs.

**Comment by moellep** [comment]
It was simulation ID V9hyV62a. I wasn't able to reproduce the problem. We
need to add javascript error logging to the server.

Paul

**Comment by robnagler** [comment]
Should have looked at his console sorry

Maybe we can debug next week

**Comment by mrakitin** [comment]
Fixed in 6493be3ba273a0a2c7a7d53bbc8a1a6b1c061c1d by Paul. Closing.
