### ISSUE TITLE
20230501 Eigenvalue reporting

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#5705]
When the eigenvalue run mode is selected, we should display the eigenvalue information from the log file in a new window.

The requested information should populate a new eigenvalue window with the text at the bottom of the log file, a la:

> ============================> RESULTS <============================
>
> k-effective (Collision) = 0.92282 +/- 0.00172
> k-effective (Track-length) = 0.92209 +/- 0.00142
> k-effective (Absorption) = 0.92309 +/- 0.00183
> Combined k-effective = 0.92230 +/- 0.00114
> Leakage Fraction = 0.60136 +/- 0.00077

**Comment by mkeilman** [comment]
I'm already seeing these lines, e.g. in the  [Zero Power Reactor Experiment example](https://www.sirepo.com/cloudmc#/geometry/vs4RrEXb). (I ran it with 2 batches, 100 particles). Can this be closed?

**Comment by moellep** [comment]
These lines are in the log file, but we want to see them displayed in the UI in realtime as the simulation progresses. Showing the values from K EIGENVALUE SIMULATION and below.

**Comment by mkeilman** [comment]
> These lines are in the log file, but we want to see them displayed in the UI in realtime as the simulation progresses. Showing the values from K EIGENVALUE SIMULATION and below.

OK...and it's just the text, not a plot?

**Comment by moellep** [comment]
Yes, it would just be displayed in a table, similar to the JSPEC Rate Calculation. An easy way to do this would be to return the data to simHandleStatus() from background_percent_complete() and display the table in the simulation status panel. So every call to background_percent_complete() would parse the openmc log file, extract the data as a table and return it to the client as it is executing. The code is already parsing that file to get the percent complete value.

![x](https://user-images.githubusercontent.com/6516910/234060703-1b402c9c-2b77-4eac-a88d-1adca7b2f5fd.png)

**Comment by mkeilman** [comment]
Questions for @sjcrs:

1. Is there always one and only one eigenvalue?
2. Is it always positive?
3. Can it be of arbitrary magnitude?

thx

**Comment by sjcrs** [comment]
The physical meaning is that it's the ratio of the neutrons produced by fission in one generation to the number of neutrons lost through absorption and leakage in the preceding generation.   So yes, it's always single valued, and it's always positive. The k factor for a failed fission reactor is 0 < k < 1, for a successful reactor around 1, and for a nuclear bomb around 2.  So a pretty narrow range.
