### ISSUE TITLE
Interface for Weight Windows

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#5711]
This depends on a particular external pull request (https://github.com/openmc-dev/openmc/pull/2359) passing all checks.

Using the new weight windows generation feature depends on a mesh definition, most likely defined in the "tallies" tab in Visualization/Settings.  I think it makes sense to define the new weight windows variables in a tab to the right of "tallies".

I've been testing the dev branch of the pull request mentioned above, there may be some additional information to display on screen from the output log.  So, not just just the current bunch status, but the bunch status within each iteration. 

This is a natural follow-up for whoever tackles #5705

**Comment by moellep** [comment]
Combining this issue with #6033
