### ISSUE TITLE
Create an "app" renaming utility

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5725]
The new accel app should be renamed to LLRF (sim_type llrf).

**Comment by robnagler** [comment]
No, don't rename it yet.

**Comment by moellep** [comment]
OK - we won't rename it yet. But I've asked Gurhar to write a rename utility which will be helpful for these cases.

**Comment by robnagler** [comment]
@gurhar1133 it would be good to write a test for this for two apps: myapp and elegant. The tricky part of elegant will be that the app is referenced by other apps and elegant has submodules. It might be sufficient to flag any references to elegant that are suspicious and throw an error.

**Comment by gurhar1133** [comment]
Do we want this to be a sirepo pkcli tool? Or maybe a pykern pkcli tool? 
`pykern rename <old_name> <new_name>` or `sirepo rename_app <old_name> <new_name>`?

**Comment by robnagler** [comment]
It's sirepo specific, and yes, pkcli.rename_app is great.
