### ISSUE TITLE
SRW - customized parameters of user-defined beams are discarded after selecting predefined beams

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#574]
The parameters of the user-defined beams are not kept after selecting the corresponding predefined electron beam.

Steps to reproduce:
- Select the APS predefined electron beam.
- Click `Edit Beam`.
- Change some parameters (e.g., set `Energy [GeV]` to 3) and click the <kbd>Save Changes</kbd> button.
- Reopen the parameters of the electron beam and select the predefined APS predefined electron beam, and then switch the the previously created copy - you will notice that the energy was changed to the default value for that beam.

**Comment by moellep** [comment]
This seems to be fixed.
