### ISSUE TITLE
Not Found => Copy Simulation

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#576]
When a "not found" error occurs on a simulation, it should render "copy", not "not found" as the heading. It's confusing otherwise. Mockup:

![reproduce-simulation](https://cloud.githubusercontent.com/assets/5495179/21187704/2afcf9a4-c1d6-11e6-89ab-335a3abbb208.png)

**Comment by mrakitin** [comment]
+1. We had this confusion several times at NSLS-II.
