### ISSUE TITLE
Broken NERSC integration 

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5798]
Shifter behavior changed on perlmutter in the last week which breaks sirepo.com integration. We are working with NERSC to resolve this.

**Comment by robnagler** [comment]
Shifter is broken, but podman-hpc integration works. Investigating https://docs.nersc.gov/development/podman-hpc/overview/

**Comment by robnagler** [comment]
After more discussion with NERSC, we will continue with Shifter. Perlmutter will be rebooted this week, which will fix the problem.

**Comment by e-carlin** [comment]
This was fixed in an update to Perlmutter.
