### ISSUE TITLE
Copy simulation needs to verify name is unique

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#58]
Copy a simulation from another user when already have the same name (Circular Aperture) will produce dual entries in the simulation list.

**Comment by mrakitin** [comment]
I think it's handled correctly now:
![copy](https://cloud.githubusercontent.com/assets/13209176/21820309/25172dee-d73d-11e6-963c-d369c1959757.png)

**Comment by mrakitin** [comment]
@robnagler, can it be closed?

**Comment by robnagler** [comment]
I don't think this is fixed @moellep?

**Comment by moellep** [comment]
It doesn't give the copied simulation a unique name, so this isn't fixed
yet.

**Comment by mrakitin** [comment]
OK, I see. I didn't understand the issue.

**Comment by robnagler** [comment]
This is not fixed. Not sure why it was closed.

**Comment by moellep** [comment]
Looks like this was fixed in 52f0ff3
