### ISSUE TITLE
 SRW - Move default parameters from srw.py to the schema

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#580]
Currently all the default values are distributed in the `srw.js` and `srw.py` files. We need to collect all the defaults values in one place - in SRW schema. This ticket will address the Python part.

**Comment by mrakitin** [comment]
Related to #579.

**Comment by mrakitin** [comment]
Too many 1st priorities, reduce priority to 2nd. Will take care of it after other 1st priority issues are solved.

**Comment by robnagler** [comment]
This is done for the most part.
