### ISSUE TITLE
elegant script example fails to find script on prod

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5808]
The elegant Script Element example works OK on dev, but fails on prod with the elegant error:
```sh: line 1: ./SCRIPT-commandFile.combine.py: cannot execute: required file not found```

When the elegant script is run, is it running within the run_dir?

**Comment by robnagler** [comment]
Yes, it is run in the run_dir.

**Comment by robnagler** [comment]
I'll debug in a bit

**Comment by robnagler** [comment]
There's a hardwired `/usr/bin/python` in the script, which should be `/usr/bin/env python`. The os.system should be fixed to not inline arguments (bad practice) and instead pass an array (the code would be simpler too). This should be fixed at the same time.
