### ISSUE TITLE
custom script element gets wrong script name in elegant.lte

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5812]
if you upload a script (combine1.py) it generates the wrong text in elegant.lte:
`"S1": SCRIPT,command="./combine.py %i SCRIPT-commandInputFile.beam.sdds %o",no_new_particles=0,use_csh=0`
when the file is `SCRIPT-commandFile.combine1.py`

**Comment by moellep** [comment]
If you change the script input name, you also need to update the "command" field to match.

![x](https://github.com/radiasoft/sirepo/assets/6516910/bad9db48-a750-4726-89ed-792fa10d3775)
