### ISSUE TITLE
srw-defaults and warp-defaults?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#586]
Where are these files used?

**Comment by mrakitin** [comment]
I don't think we use it anywhere, I don't see any occurrences.

**Comment by moellep** [comment]
In server.py:

def app_new_simulation():
    new_simulation_data = _parse_data_input()
    sim_type = new_simulation_data['simulationType']
    data = simulation_db.open_json_file(
        sim_type,
        simulation_db.STATIC_FOLDER.join('json',
'{}-default{}'.format(sim_type, simulation_db.JSON_SUFFIX)),
    )

**Comment by mrakitin** [comment]
Ah, I see. Thanks Paul!

**Comment by robnagler** [comment]
How is it related to [the use in elegant_lattice_importer](https://github.com/radiasoft/sirepo/blob/661dbbc7c2d3694f40f28e01d6dba472c190d8fa/sirepo/template/elegant_lattice_importer.py#L32). It seems that

**Comment by moellep** [comment]
If you select "new simulation" in elegant it will use elegant-default.json
for the default data.

If you import an elegant lattice file, it will use elegant-default.json for
the default commands. If you import an elegant lattice/command file pair,
the defaults won't be used.

**Comment by robnagler** [comment]
It uses these values from two different places, though. I'm going to align them.

**Comment by robnagler** [comment]
Fix ebd7576
