### ISSUE TITLE
wrong units on phase plot

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5860]
In silas, on the Laser Pulse and Beamline tabs, the Phase plots (by slice and total phase) is showing units [mm], but it should probably be [rad]. (check for units used in the rslaser_examples notebooks)

**Comment by bnash** [comment]
Phase may well be measured in units of length. The phase in radians is converted to a phase in length by multiplication by lambda/(2pi) where lambda is the wavelength. It might be worth having both options, but the output of the measurements from the wavefront sensor is a length.

**Comment by gurhar1133** [comment]
> Phase may well be measured in units of length. The phase in radians is converted to a phase in length by multiplication by lambda/(2pi) where lambda is the wavelength. It might be worth having both options, but the output of the measurements from the wavefront sensor is a length.

So is the current [mm] units correct? Or do we need to switch/convert to radians?

**Comment by gurhar1133** [comment]
Millimeters refers to horizontal and vertical dim of the mesh, which is correct
