### ISSUE TITLE
Hellweg - user feature request - 'Visualization' tab has a confusing name

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#5884]
Input from beta tester --

First email:
***
How do I run the simulation?

Second email, after receiving instructions:
***
This tab is called “Visualisation”, so it was a little confusing.

**Comment by gurhar1133** [comment]
What should the name be changed to? "Simulation"?

**Comment by gurhar1133** [comment]
> "Simulation" makes sense to me, but this would break away from a long standing convention. It seems to me that such a change requires a conversation.

Thoughts @robnagler

**Comment by robnagler** [comment]
This should be discussed in product management, not here. I'll forward.

**Comment by gurhar1133** [comment]
Should I change "Visualization" to "Simulation" in the meantime?

**Comment by bruhwiler** [comment]
Don't make any changes until a formal decision has been made.

**Comment by bruhwiler** [comment]
The product management team discussed this issue.
'Visualization' is a standard for the tab where the primary (although not all) simulation and visualization occur.
If we change the name for Hellweg, we would need to do the same for other apps, which would be very confusing for users.

In conclusion, we decided not to make any changes in response to this issue.
