### ISSUE TITLE
SRW - partially coherent intensity report broken on alpha

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#589]
The simulation below causes a "502 Bad Gateway" when trying to display the partially coherent report. Rerunning the report also causes a 502 error.

https://alpha.sirepo.com/srw#/beamline/P28tg9fO

**Comment by mrakitin** [comment]
It's related to #590.

**Comment by mrakitin** [comment]
I think it's fixed by  	9726f29. @moellep, could you please release alpha to check? Thanks.

**Comment by mrakitin** [comment]
Seems to be working fine on alpha after release #594.
