### ISSUE TITLE
Silas:  chirp needs to be specified differently

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#5928]
Beta tester:   this is not how people specify chirp

![image](https://github.com/radiasoft/sirepo/assets/3825435/db0ddb32-8fbc-46b6-b41a-499ce22cf6c6)

More specific guidance will be posted when available.

**Comment by k-wolfinger** [comment]
@gurhar1133 You may have already implemented this:

Instead of asking for a chirp value, we want to ask the user for the "chirped pulse length" (tau_fwhm, this is the intensity FWHM value) and the "Fourier-limited pulse length" (tau_0).

The default units should be picoseconds (ps) for both.

**Comment by moellep** [comment]
Chirp is now a calculated value, shown on the Laser Pulse panel, Longitudinal tab.
