### ISSUE TITLE
protected zip file extraction

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#596]
This is a [security issue](https://github.com/radiasoft/sirepo/blob/4adfeac133e2e643b4d5006676cb7539c21dba84/sirepo/template/srw.py#L572):

```python
zip_file.extractall(str(run_dir))
```

This could do just about anything. [ZipFile.extract()](https://docs.python.org/2/library/zipfile.html#zipfile.ZipFile.extract) has some protections, but it would be better to extract a member at a time with some checks such as file size, file type (no pyc, py, etc. files), and so on.

**Comment by mrakitin** [comment]
I think I did something similar in #607 - it extracts only the files listed in `*_sum.txt` file. Possibly need to improve the code to check the extensions.

**Comment by mkeilman** [comment]
A couple questions:

What is a reasonable file size limit?  I haven't seen anything approaching 10MB in existing magnetic data files but I don't know how big they could be

Should any suspicious file kill the extraction right away, or should any good files be extracted regardless?  It seems like the former is more sensible...

**Comment by robnagler** [comment]
100MB seems reasonable to handle the unexpected (other codes or perhaps Jupyter notebooks some day) while still not being overly generous.

The extraction should be binary: valid => extract, invalid => return error(s) to user.

**Comment by mkeilman** [comment]
How strict do we want to be with regards to existing files?  For example, magn_meas_chx.zip has a couple  of ".orig" files.  Does this file need to be cleaned up or should the validation be at least temporarily less restrictive?

**Comment by robnagler** [comment]
We shouldn't have examples that have junk in them. If you can make a pkcli that we can add to test.sh to validate these, it would be great.

**Comment by moellep** [comment]
Mike cleaned up the magn_meas_chx.zip file to remove the extra files, but I don't think it should crash the existing user's CHX beamline. We validate the zip on the way in, and only the dat and txt files are extracted before running, so re-validating isn't necessary when then simulation is being prepared. I'm going to remove that extra validation from template.srw.
