### ISSUE TITLE
Independent horizontal / vertical axis zoom-in 

### ISSUE THREAD

**Issue by ilyapogorelov** [radiasoft/sirepo#5980]
When viewing transverse phase space plots in Beam Report or Beam Animation, sometimes it may be useful to be able to zoom in along just one axis, as opposed to both axes at the same time.  I'm not sure what would be a good way to implement this as far as the interface goes: To have a box/field for setting the axis range?  To have a check-box to keep this axis frozen while the zoom-in along the other is allowed?

This is probably a low(er) priority improvement.

**Comment by gurhar1133** [comment]
Hi @ilyapogorelov, it appears that you already can zoom in along a single axis on the beam report and beam animation if you zoom on the field lineout.
![Screenshot 2023-06-20 at 3 38 11 PM](https://github.com/radiasoft/sirepo/assets/49498231/8c2d98cd-c7cb-4211-8c32-5ed6f870c49f)

![Screenshot 2023-06-20 at 3 38 35 PM](https://github.com/radiasoft/sirepo/assets/49498231/5b9022f7-f430-402a-9cfa-a0962a32c6f3)

**Comment by ilyapogorelov** [comment]
I see, that's right.
I missed it because I tried to do the zooming-in in the image field and not in the histogram field(s). 
I'm closing the issue.
