### ISSUE TITLE
Longitudinal Gaussian energy distribution in Hellweg

### ISSUE THREAD

**Issue by ilyapogorelov** [radiasoft/sirepo#5985]
In Hellweg's  Beam-->Longitudinal Distribution--> Gaussian  panel,  there are 3 inputs for specifying the energy distribution.  It is clear what 'Mean Energy' and 'Energy RMS Deviation' are, but what is then 'Energy Spread'? Don't we need only 2 parameters to specify a 1D Gaussian?

**Comment by gurhar1133** [comment]
Hi @ilyapogorelov, 
The Energy Spread param is the second param passed to NORM2D in input files. The screenshot below from the rshellweg user manual explains the use 'Energy Spread' or ∆W. Would you like us to change the name of 'Energy Spread' in the UI or include the '∆W' in the explanation/label or add some description to the UI in the info tab?

![Screenshot 2023-06-20 at 4 45 05 PM](https://github.com/radiasoft/sirepo/assets/49498231/669f641c-58eb-4921-ad74-479c8ea3676d)
