### ISSUE TITLE
out-of-sync rslaser repo and sirepo

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5990]
The current alpha release is ahead of the rslaser version.

![x](https://github.com/radiasoft/sirepo/assets/6516910/5bfd02db-9ab8-4840-9c7c-98000c20b516)

**Comment by e-carlin** [comment]
Should rslaser be rebuilt?

**Comment by moellep** [comment]
We have options - we could update the sirepo to the current rslaser version, or build a new rslaser.

**Comment by moellep** [comment]
This has been resolved.
