### ISSUE TITLE
Need to query running simulations

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#60]
If a simulation is running in celery and the front end is restarted, the celery task is "lost". At this point, you have to kill the rabbit db:

``` bash
service sirepo stop
service celery-sirepo stop
service rabbitmq stop
rm -rf /var/lib/rabbitmq/mnesia
service rabbitmq start
service celery-sirepo start
service sirepo start
```

**Comment by bruhwiler** [comment]
@robnagler   --  is this issue still relevant?

**Comment by robnagler** [comment]
yup

**Comment by robnagler** [comment]
#319 will produce the data for this. We have a start of an admin screen.

**Comment by bruhwiler** [comment]
We're no longer using celery.
