### ISSUE TITLE
Crystal n0 n2 options

### ISSUE THREAD

**Issue by gurhar1133** [radiasoft/sirepo#6008]
n0 and n2, would like a FEniCS option and an Innocenzi option, if keep the boxes, need to label them with either position in crystal or corresponding crystal slice

**Comment by moellep** [comment]
This issue has changed a bit. We want to always calculated n0 and n2 (using the rslaser calc_0n2() call we are currently using). The method could be "fenics", but we are currently only using the default method.

The crystal editor should have a plot of the n0 and n2 values based on the current settings on that form. This could be added as a new tab, "Summary" or similar. For ABCD propagators, this tab should also show the computed ABCD values.

**Comment by moellep** [comment]
This could possibly be implemented in a similar fashion to the SRW Sample beamline element. Where the last tab shows the computed sample. But in this case, we would want a n0 n2 graph.
![x](https://github.com/radiasoft/sirepo/assets/6516910/f5b27e9d-722b-4324-9d10-c0e51aaca884)
