### ISSUE TITLE
Mirror updates

### ISSUE THREAD

**Issue by gurhar1133** [radiasoft/sirepo#6009]
Mirror: confusing currently
- [ ] Clarify why it is there (to pass through the crystal from the other side)
- [ ] Two cases:
    - No symmetry inversion (single flat mirror)
    - Flipped symmetry (two 45 degree mirrors called “folding mirror pair”)

**Comment by moellep** [comment]
This was implemented as a new mirror icon which shows the pair of mirrors, and adding the descriptive text.

![x](https://github.com/radiasoft/sirepo/assets/6516910/b6f98c2d-c9ed-4528-ad69-44bcca9c0021)
