### ISSUE TITLE
Crystal choice

### ISSUE THREAD

**Issue by gurhar1133** [radiasoft/sirepo#6010]
User needs to be able to choose between different types of crystals on the thermal transport tab:
- a) A crystal initialized on the Amplifier Tab
    - don’t let the user play with the pre-defined parameters like diameter (or if you do, the changes are reflected on the Amplifier Tab)
- b) A crystal initialized on the thermal transport tab
    - All parameters adjustable

**Comment by moellep** [comment]
We've decided to allow updates to the crystal on either the amplifier or on the thermal transport tabs.
