### ISSUE TITLE
work-around for final z=0 frame in hellweg

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6013]
The RF Fields example ends with a bad point at z=0. This should be stripped out of the results before displayed.

**Comment by ilyapogorelov** [comment]
A possible fix is to modify TBeamSolver::Output() :
//int j=Npoints-1;
int j = Npoints -2;

**Comment by moellep** [comment]
Yes, that would fix the summary output. The bad data also exists in the last entry in the datafile created by TBeamSolver::SaveToFile().
