### ISSUE TITLE
improve cloudmc 3D toolbar

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6017]
I think there could be several changes to improve the toolbar in the cloudmc app:
<img width="697" alt="x" src="https://github.com/radiasoft/sirepo/assets/6516910/6bd99dd4-da12-4545-86c7-af1aff501403">

I think the first two buttons (arrow and pointer) could be removed, and change the text to "Click and drag to rotate. Double-click to reset camera. Control-click an object to select". When it is in the "arrow" mode, it seems to support all three, so just use that mode by default.

Replace the -90, -45 and 45, 90 buttons with two rotate buttons (forward and reverse), and rotate 45 degrees when clicked. Possibly change the "Reset" button to a home icon.

Move the perspective button inline with the other toolbar buttons.

Move the "Toggle Marker" checkbox to the panel's editor dialog.

When clicking on a dimension button (x, y, z), the buttons shift slightly due to the difference in the text size. Set a min-width on the button to prevent this.

**Comment by mkeilman** [comment]
See also #4902
