### ISSUE TITLE
get_data_file() should return a file-to-large error rather than not-found

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6021]
The simulation below creates very large output files which exceed the sirepo limit. When you try the "Raw Data File" option on the 1st watchpoint report, it results in a 404 "Not Found", but instead should respond with a 413 "Content Too Large" or similar error.

https://www.sirepo.com/srw#/beamline/D093hGau

**Comment by Benbenbenin0** [comment]
Could not reproduce, successfully downloaded 1st watchpoint report (604.9 mb).
