### ISSUE TITLE
Add "interactive" to list of available NERSC queues

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6024]
Test how interactive differs or if it works just like debug. There are some maximums.

**Comment by gurhar1133** [comment]
It doesn't look like [interactive](https://docs.nersc.gov/jobs/interactive/) works like debug. Interactive is used to spawn a shell that the user interacts with to `srun` parallel tasks.

**Comment by robnagler** [comment]
I think these are somewhat distinct. Did you try to run a batch job to the interactive QoS?

**Comment by gurhar1133** [comment]
We cannot submit sbatch jobs to the interactive queue`sbatch: error: Cannot submit batch jobs to interactive_ss11.`

Interactive queue works with `salloc`.

Do we want to investigate how to adapt sirepo to support `salloc`?

It seems like the interactive queue is supposed to be used interactively on NERSC and not by an agent like sirepo.

**Comment by robnagler** [comment]
I will contact the user who requested this.
