### ISSUE TITLE
Improve Tablet UI

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#6040]
Specifically Galaxy s6 lite. If this is a problem, we can get people iPads.

**Comment by k-wolfinger** [comment]
Attached is a photo of what Sirepo looks like on my tablet
![20230629_140306](https://github.com/radiasoft/sirepo/assets/51915265/5d603fbd-40dd-41b1-96fa-16581f471513)

**Comment by e-carlin** [comment]
This looks like the nginx /en vs /en/ problem

**Comment by moellep** [comment]
Yes, this problem has been fixed on alpha and beta, and will make it to production on Monday. This problem also happens in web browser if you follow this link:  https://sirepo.com/en

**Comment by robnagler** [comment]
@k-wolfinger please visit https://www.sirepo.com to see if it works properly when you have a chance. Or even "sirepo.com"  should work properly.

I suspect you visited by typing in "sirepo" into the search box, and google presented a list of answers, one of which is "wrong" (and we've fixed so it works but not released) .

**Comment by k-wolfinger** [comment]
Okay, you are right. I clicked on the first link, said RadiaSoft and all. 

When I went to RadiaSoft first, and then Sirepo from there, the page came up and looked great on the tablet.

**Comment by robnagler** [comment]
Thanks for checking and pointing out the problem. As Paul said, it should be fixed Monday.
