### ISSUE TITLE
Improve text for beamline simulation progress

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6046]
The beamline simulation progress shows "X animation frames". When it should show "X completed reports", or something similar. "Animation frames" isn't the right word to use in this case.

![x](https://github.com/radiasoft/sirepo/assets/6516910/b10dba87-78c1-4065-b84b-bd293e6a7f04)

**Comment by gurhar1133** [comment]
Just for silas or silas and srw?

**Comment by moellep** [comment]
Both - the "animation frames" is actually the plot completed count.
