### ISSUE TITLE
srw._copy_lib_files processing image file?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#605]
Is [this copy](https://github.com/radiasoft/sirepo/blob/2d811b97c2854fb128f67ee132ee2dc13578ed1d/sirepo/template/srw.py#L963) in _copy_lib_files, necessary?

I'd like to factor out the list of files from the copying operation. This one operation is a side effect to the function of calculating the file list, and seems like it could be postponed when the file is actually rendered in the new copy. It's not used by prepare_aux_files or for preparing an archive.

**Comment by mrakitin** [comment]
I'll check it a bit later. I remember that was necessary for a new user/browser. I have to recall why I did it this way.

**Comment by mrakitin** [comment]
OK, I've recalled. It's for downloading the processed image file, so it's available via the menu:
![sample](https://cloud.githubusercontent.com/assets/13209176/21865708/417ed274-d815-11e6-99ee-d5ed170608d5.png)

**Comment by robnagler** [comment]
This seems like the wrong place for this code. Shouldn't it ask for a downloadProcessedImage or something like that. It should be based on the currently selected image. If you upload a new image, it does not copy the file processed image to the current directory. It does add it to the library. 

I think this is a special function that should create the processed image when the user requests it.

**Comment by mrakitin** [comment]
I agree that this is not the best place for this code, but when I implemented it, there was no way to provide `run_dir` for the code, so that it was not possible to convert it per request.

**Comment by robnagler** [comment]
I think the new route should be something like: report-file/<simulation_type>/<simulation_id>/<report_name>/<beamline_element>/processed_image/<image_name>
where <image_name> is the name you'd like to download to. The <beamline_element> would be an index. This should be available, because it is in the modal for the element.

This should be a generic call into the template, which gets the argument "processed_image" as well. The function than can decide what to do. Another type of "sub argument" would be "raw_image", which would return the uploaded tif.

Right now I noticed that the sample_processed.tif gets copied to srw/lib, which seems wrong. It's an output of a specific beam line element so it should stay with the report.

Anyway, I'll work on this after fixing the #611.

**Comment by mrakitin** [comment]
I agree with the proposed route, looks great. Thanks!

**Comment by robnagler** [comment]
Removed in 0c2ff6e
