### ISSUE TITLE
raydata: start and stop date picker

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#6057]
Users suggested we find a better date picker to select the "start" and "stop" search fields. The current one requires 8 clicks to get enough fields set to do a search. They mostly use Firefox so we should make sure we test on it. The current date picker is just an html5 element so it works different across browsers.

Some ideas:
- Bootstrap date picker
- Use a library
- Build our own

One feature users mentioned they'd like to see is to be able to type in the date field. You can currently do this so we need to think about how to make it more intuitive. It may be we need to tell them it is possible but I'd like to consider options for making it clearer.

I think this issue deserves a clear plan before starting on the implementation.

@rorour please come up with a plan for what you think would make a better date picker. It may be you present multiple options. It also may be that our current one is the best we can do. Timebox this to 4 hours.

Run the plan by @moellep before starting implementation.

**Comment by rorour** [comment]
Closing after discussion in today's demo. The default buttons improve this issue, but we will want to add a "last week" button (#6737).
