### ISSUE TITLE
raydata: start and stop query easy selection

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#6059]
Give users the option to set the start and stop search fields to some pre-defined times. We can start with last hour and last day

**Comment by rorour** [comment]
Do you have any thoughts on what the UI will look like? I could see this as a few buttons ("Last Hour, Last Day") underneath the start/stop fields. Or possibly a drop down menu with those options.

**Comment by e-carlin** [comment]
I don't have ideas. But I think the few buttons below the start stop fields sounds fine. Coming up with layouts such as this is not my strong suit. Paul may have ideas.
