### ISSUE TITLE
raydata: better ordering of results columns

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#6061]
scan_id and plan_name should be included in the default results columns. The ordering should be:

run analysis, view log, status, scan id, plan name, start stop, suid

**Comment by rorour** [comment]
I don't see plan_name in chx scans. Maybe chx and csx should have different default columns?

**Comment by e-carlin** [comment]
Sounds good to me. It probably should live in the schema. I think that will make sharing between the server and gui easiest.
