### ISSUE TITLE
raydata: clearer way to show analysis output

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#6067]
It is not clear to users that they can click on a row in the results table to see the analysis results of a specific scan. We need to find a way to make this more apparent. It might mean adding another button instead of making the row clickable. If we go another button route I think we should create a way to group the run analysis, view log, and view analysis buttons together.

**Comment by jeinstei** [comment]
There's possibly adding an "open in new window" or "popup" icon at the end of the description text? https://www.ecosia.org/images?q=%22open%20in%20new%20window%22%20link%20icon#

**Comment by e-carlin** [comment]
This was accomplished by adding a button
