### ISSUE TITLE
sqlalchemy error on user registration

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6083]
The "enter your full name" portion of user registration causes a server error:

```
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required

 api_authEmailAuthorized
 model=m.unchecked_search_by(uid=i),
```

**Comment by moellep** [comment]
m.unchecked_search_by(uid=i) is returning multiple values when uid=None, which can happen if there a multiple pending registration rows.

**Comment by e-carlin** [comment]
I can reproduce on dev. The uid field is null which then yields multiple results.

```
vagrant@localhost.localdomain|||W7NMDRYOTHVA2BIB|2023-07-07 07:27:37.088842
x@x.x|||QS7MOBRSXMTWLJHB|2023-07-07 07:28:21.756780
```

**Comment by e-carlin** [comment]
This problem is happening on prod.

**Comment by e-carlin** [comment]
https://github.com/radiasoft/sirepo/pull/6084 will fix the issue. I'll release to alpha tonight.

**Comment by e-carlin** [comment]
The fix has been released to production.
