### ISSUE TITLE
copying a simulation with a mirror doesn't copy profile

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#610]
srw.copy_related_files does not provide a "report" so srw._copy_lib_files doesn't copy heightProfileFile when copying a non-session simulation.

I'm going to make the simulation copying like elegant so that it copies all related files.

The bigger issue is that a file shouldn't be assigned unless there is an element in the beamline that requires it. If there is no mirror, then there won't be a profie file. If there isn't a sample, there won't be a sample image. Similarly if a tabbed undulator is not selected, it shouldn't have a measurement file (#585). We should only fill in these values once they are selected.

**Comment by robnagler** [comment]
@mrakitin I'm coding lib_files() for template.srw so that it can be used by the zip archive code. I think the code should be something like this:

```python
    res = []
    dm = data.models
    if dm.simulation.sourceType == 't':
        if 'tabulatedUndulator' in dm and dm.tabulatedUndulator.magneticFile:
            res.append(dm.tabulatedUndulator.magneticFile)
    for m in dm.beamline:
        for k, v in _SCHEMA.model[m.type].items():
            ft = v[1]
            if m[f] and ft in ['MirrorFile', 'ImageFile']:
                if not report or (_is_watchpoint(report) or report in ('multiElectronAnimation', 'mirrorReport'):
                    res.append(m[f])
```

If there's no `report` (archive zip case), then all MirrorFile and ImageFile entries from the beamline are copied.

Does that seem right?

**Comment by robnagler** [comment]
Checked in fix 0c2ff6e

**Comment by mrakitin** [comment]
The code snipped looks fine to me, but needs to be tested.

**Comment by robnagler** [comment]
Yes, I debugged it before checking in.
