### ISSUE TITLE
Export dump, pythonSource, etc. should be links

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#6113]
It opens a new window, but I think it can be just like download data file and be an data-ng-href

**Comment by robnagler** [comment]
I think the problem is that the simulation id isn't loaded and the app header gets loaded dynamically? I tried it with pythonSource and it didn't work. @moellep what's the reason? Possibly document in the source.

**Comment by moellep** [comment]
It can be converted to a data-ng-href:
```html
<li><a href data-ng-if="::canExportArchive()" data-ng-href="{{exportArchive('zip')}}" target="_blank"><span class="glyphicon glyphicon-cloud-download"></span> Export as ZIP</a></li>
```
```javascript
            $scope.exportArchive = function(extension) {
                if ($scope.simulationId()) {
                    return requestSender.formatUrl('exportArchive', {
                        '<simulation_id>': $scope.simulationId(),
                        '<simulation_type>': SIREPO.APP_SCHEMA.simulationType,
                        '<filename>':  $scope.nav.simulationName() + '.' + extension,
                    });
                }
            };
```

**Comment by robnagler** [comment]
I meant without `target="_blank"`.  sample.tif can be downloaded without a target="_blank".

**Comment by moellep** [comment]
Yes, the ```target="_blank"``` can be removed and the exportArchive works OK.

**Comment by robnagler** [comment]
This should be changed for pythonSource as well. newWindow should be limited.
