### ISSUE TITLE
Imported file type validation should be case insensitive

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#6121]
When validating a file type, we should accept both .`STL` and `.stl` e.g.

**Comment by robnagler** [comment]
Does that mean we are not case insensitive for storage?

**Comment by mkeilman** [comment]
> Does that mean we are not case insensitive for storage?

I guess I don't actually know...<checks>...looks like it is case insensitive. I thought I had memory to the contrary but I'm probably conflating it with something else. I'll strike that from the comment.

**Comment by robnagler** [comment]
Would be good to make sure there isn't a case sensitive path here.
