### ISSUE TITLE
Investigate STL design vs visualization

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#6127]
There is an apparent discrepancy in imported STL objects between the 2d bounding boxes and the 3d visualization, for example an  unexpected intersection of a rotated clone with the original object. Bounds or centers may be miscalculated, or there could be other causes (including user error)

- [x] #6140
- [x] #6184

**Comment by dilhudson** [comment]
Hi Mike, I just posted in the slack about this before I found this issue. I'm pretty sure I traced it back to the y-coord of the STLs centroid being off. 
[centroid_bug.pdf](https://github.com/radiasoft/sirepo/files/12223138/centroid_bug.pdf)

**Comment by mkeilman** [comment]
> Hi Mike, I just posted in the slack about this before I found this issue. I'm pretty sure I traced it back to the y-coord of the STLs centroid being off. [centroid_bug.pdf](https://github.com/radiasoft/sirepo/files/12223138/centroid_bug.pdf)

Thanks very much.  I see the problem and will make a fresh issue for it (briefly, the "center" parameter is "center of the object's bounding box" for purposes of simplicity, but we are erroneously placing the stl's centroid there)

**Comment by mkeilman** [comment]
We found the root cause and completed the sub-tasks, so I'm closing this.
