### ISSUE TITLE
silas improvements

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6129]
- [ ] Change examples to use pump_rep_rate of 1000 Hz so calculated n0 n2 and ABCD values make sense
- [ ] Add help text to Laser Pulse Beam Size to indicate that they are RMS values
- [ ] Add assertion on ABCD results that AD - BC == 1
- [ ] Support the features in the notebook (lens.Telescope_lct for example). Create an sirepo example for this.
    https://github.com/radiasoft/rslaser-examples/blob/main/laser_propagation/amplifier_100TW_Bella.ipynb
- [ ] Compute and show chirp in the UI on the Laser Pulse panel, calculated from the FWHM Length & Fourier-limited pulse length
- [ ] Change the units on this from "Rad/s" to "rad/s". The G and P prefixes are automatically added, and are OK. Add a space between the amount and units at the top left of the plot.
![x](https://github.com/radiasoft/sirepo/assets/6516910/b701f739-4797-48af-b84c-5ecb5df451ea)
- [ ] Show the selected "Pump Pulse Profile" on the Thermal Transport tab.
- [ ] Set the crystal diameter on the Thermal Transport tab as the selected crystal radius * 2 and make it non-editable
- [ ] The Thermal Transport tab needs to generate a sim which uses the ThermoOptic class in rslaser, rather than a stand-alone fenics sim. See the rslaser_thermooptic.ipynb notebook in rslaser_scratch. There are many different ways to invoke, depending on the pump rep rate, the pump profile, and the method (analytic or fenics). Either a steady state calc, or an "over time" calculation should be used depending on the report rate <> 100.
- [ ] Determine the correct formula for crystal "length scale" value (based on a gaussian laser pulse) and hide that field.

**Comment by moellep** [comment]
@gurhar1133 please take a look at this group of issues and see if it makes sense.

**Comment by gurhar1133** [comment]
This has been split up into #6143 #6141 #6142 #6144
