### ISSUE TITLE
Energy filter breaks plotting

### ISSUE THREAD

**Issue by sjcrs** [radiasoft/sirepo#6132]
The EnergyFilter option actually multiplies the number of tally arrays in the statefile, based on the number of energy bins.  Currently, if a user employs the energy filter in addition to a mesh filter for a tally, it cannot be plotted within the visualization tab.  

- [ ] If the EnergyFilter is employed, there should be a drop box in the pencil menu to select which energy bin is shown.  This could be tricky, because some examples use ~500 bins (see https://nbviewer.org/github/openmc-dev/openmc-notebooks/blob/main/flux-spectrum.ipynb).  I'm open to suggestions for alternatives to a drop box.  Perhaps a double-sided sliding window that can sum adjacent energy bins? 

It would also be a useful feature if a user could select a bin and produce a 1d spectrum. Please see the notebook at `EFilterExample.ipynb` for an example. (Moved to #6527)

**Comment by moellep** [comment]
We discussed in the meeting and decided to use a range selector for the energies - selecting the upper and lower boundary. Then show a summed mesh in 2d and 3d.
