### ISSUE TITLE
(imported JSON)?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#614]
I'm not sure why we append "(imported JSON)" to simulations which are imported from JSON, but do nothing for imported Python.  If we are trying to disambiguate, we really should just do that.

**Comment by mrakitin** [comment]
Yes, I did it intentionally to distinguish between the different types of imported files. It's reasonable to add it for Python as well.

**Comment by robnagler** [comment]
The name collision changes in 5c3d41ab15cd8991b6c8358a4896ced7f4a49ab4 ensure simulations are unique within a folder.
