### ISSUE TITLE
SILAS Thermal transport crystal cylinder changes

### ISSUE THREAD

**Issue by gurhar1133** [radiasoft/sirepo#6141]
- [ ] Show the selected "Pump Pulse Profile" on the Thermal Transport tab.
- [ ] Set the crystal diameter on the Thermal Transport tab as the selected crystal radius * 2 and make it non-editable
- [ ] Determine the correct formula for crystal "length scale" value (based on a gaussian laser pulse) and hide that field.

**Comment by moellep** [comment]
These items have been fixed in previous commits.
