### ISSUE TITLE
zgoubi visualization widget broken

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6146]
The zgoubi visualization tab isn't populating the html.py widget, but instead showing the raw text. This bug isn't reproducible in a dev environment.

![x](https://github.com/radiasoft/sirepo/assets/6516910/91edcb0b-d94c-4363-8832-9d0c60f371ea)

**Comment by robnagler** [comment]
Could be tornado. Are you sure you are using tornado in dev?

**Comment by moellep** [comment]
I'm running tornado in dev, and I can't reproduce when running either "sirepo service http", or "bash etc/run-supervisor.sh local & bash etc/run-server.sh local"

**Comment by robnagler** [comment]
When https://github.com/radiasoft/rsconf/issues/362 is deployed, the cache needs to be emptied to fix the problem. A hard refresh doesn't force the requests to be cleared.

**Comment by moellep** [comment]
Is this the browser cache? If we updated the timestamp on zgoubi-visualization.html, would that fix this problem?

**Comment by robnagler** [comment]
This is the browser cache, and yes, if we update the timestamp it would probably get the new file.
