### ISSUE TITLE
Make static version in dev mode?

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#616]
Chrome has great developer tools that allow to edit and save the `*.js` files on the fly directly from the browser - https://developers.google.com/web/tools/setup/setup-workflow. It also has the possibility to map the network files to the corresponding file system resources:
![](https://developers.google.com/web/tools/setup/imgs/maptoresource.png)

Everything is cool and convenient except the names with dynamically incremented version following `.js` files, e.g. `sirepo.js?20170113.215643`. Every time I reload the page, Chrome understands the files as new and does not map them to the local file system files:
![chrome](https://cloud.githubusercontent.com/assets/13209176/21947836/4189ecd0-d9b5-11e6-8ea6-1e6b0cf06a87.png)

To avoid that issue it would be great to have an option to have an empty value (without `?`), so that the developer tools could map the files correctly.

**Comment by robnagler** [comment]
The reason dev mode renames the version is that there's no way to force a cache update otherwise.

In the way we develop at RadiaSoft we edit the files on the server-side in order to try changes. My text editor is far superior to Chrome's text editor. 

You can set up a server in alpha mode by setting: PYKERN_PKCONFIG_CHANNEL=alpha, which will turn off development mode.

I don't like adding configuration for very special cases (one person), because it then creates too many parameters and confusion for people coming into the system. The configuration should be minimal and clear, and for the most part, automatic.

**Comment by mrakitin** [comment]
Thanks for the reply, @robnagler. Does your editor allow you to change the source code so that it appears in the browser without reloading the page? What about breakpoints? Chrome's editor has these features.

If there is a static version in alpha channel, it won't help much since it will still have ?* symbols after the script, and the editor won't match the file in a browser with the local file.

@moellep, do you think it would be useful for development/debugging purposes to have this feature (I need one more person requesting it :smile:)?

**Comment by robnagler** [comment]
Are you saying you don't want a version at all? That will be more work to change, because the template hardwires that there is a version.

I don't use debuggers. I reload the page. We need to do a better job keeping the state in the URI so that a refresh works properly.

**Comment by mrakitin** [comment]
Yes, that's what I have in `index.html` to make it working for me:
```html
    <script src="/static/js/sirepo.js"></script>
    <script src="/static/js/sirepo-components.js"></script>
    <script src="/static/js/sirepo-plotting.js"></script>
    <script src="/static/js/{{ app_name }}.js"></script>
```
I just removed versions and the `?` symbol from the Sirepo JS files, all other external JS files have the version. It's about convenience of debugging and web development. I'm more satisfied when I can stop at some breakpoint and view the state of all the variables, change them, etc. I used to use FireBug in Firefox, but it does not have the option to synchronize with the local files. Chrome has this invaluable feature. I know @moellep also uses FireBug/FF Development Tools, so I feel we all will benefit from the Chrome's debugging features.

In any case, I can have `index.html` file stashed, and unstash it when I need to do web development/debugging. Just one extra step, which could be avoided by an additional channel like `web-dev` or something like this.

**Comment by moellep** [comment]
I've played with chrome and the local file editor and it is very
convenient. I'll add a server config which allows this to get enabled on
dev servers.

**Comment by mrakitin** [comment]
Thanks Paul, I appreciate the implementation of the new config.

**Comment by mrakitin** [comment]
For future references - the variable was renamed to `enable_source_cache_key`, so now it should be used as follows:
```bash
SIREPO_SERVER_ENABLE_SOURCE_CACHE_KEY= sirepo service http
```
