### ISSUE TITLE
additional decimation improvements

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6208]
The 10000 polygon limit per volume works well in most cases, but for very intricate volumes, some detail is lost. I wonder if setting one of the other flags (preserveboundary, targetperc) could improve the case below:

In the ZPRE example, the top of the "stainless" volume is being oversimplified.

original geometry:

![DAGMC-Geometry](https://github.com/radiasoft/sirepo/assets/6516910/bf9a8267-62b8-4cc9-aaf4-69c59acf3631)
![DAGMC-Geometry-3](https://github.com/radiasoft/sirepo/assets/6516910/031d76dc-363c-4ee0-ab29-9a125d1382dd)

decimated geometry:
![DAGMC-Geometry-2](https://github.com/radiasoft/sirepo/assets/6516910/97cc9d6b-e999-4fc2-a0e1-4b9480a53587)
![DAGMC-Geometry-4](https://github.com/radiasoft/sirepo/assets/6516910/c79d8121-2a7d-48fc-a066-e7be7e3152b2)

**Comment by moellep** [comment]
Here's an idea for decimation - check if the face count is less than the target, and do no decimation if so. Otherwise just reduce the faces by some percentage, ensuring it doesn't go below the max-facecount:

```python
        c = len(ms.current_mesh().face_matrix())
        if c > _DECIMATION_MAX_POLYGONS:
            ms.apply_filter(
                "meshing_decimation_quadric_edge_collapse",
                preservenormal=True,
                targetperc=max(0.5, _DECIMATION_MAX_POLYGONS / c),
            )
        m = ms.current_mesh()
        pkdp(
            "reduce faces: {} to {} ({}%)",
            c,
            len(m.face_matrix()),
            int(100 - len(m.face_matrix()) * 100 / c),
        )
```

**Comment by Benbenbenin0** [comment]
There doesn't seem to be a good "catch-all" configuration that decimates every volume to the same poly range without losing important mesh detail. Changing the quality threshold was promising but increased runtime exponentially (4x or more).

Went with your idea @moellep. For the ZPRE example I start losing important detail when decimating below 10%, I think simplifying to 20% leaves a good buffer for detail while decimating as much as possible.
