### ISSUE TITLE
20230922 update srw generated to to use srwpy

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6217]
The generated python should use the new srwpy library.
For example, 
```python
import srwpy
# ...
srwpy.srwl_bl.SRWLBeamline()
```
instead of
```python
import srwl_bl
# ...
srwl_bl.SRWLBeamline()
```

**Comment by moellep** [comment]
Possibly consider the export python to allow either case:
```
try:
    from srwpy import srwl_bl
except:
    import srwl_bl
```
@robnagler what do you think?

**Comment by robnagler** [comment]
I think we should just force the upgrade.

Also never use `except`. It should be `except Exception` (or more specific ImportError) so that it doesn't catch `SystemExit` and other `BaseException`s.

**Comment by robnagler** [comment]
@rorour I think we should move forward with this. srwpy has been on prod for a while.
