### ISSUE TITLE
standardize filename type checking

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#622]
I think [this code](https://github.com/radiasoft/sirepo/blob/b46709d3379eebc6c69a5f5681f2702fa317363f/sirepo/server.py#L519) is confused. I don't understand why secure_filename is called twice. 

I think this needs to be standardized so that we typecheck the filename once.

**Comment by robnagler** [comment]
@e-carlin do you think we have resolved this issue?

**Comment by e-carlin** [comment]
Yes, it is all done in [http_request.parse_params with util.secure_filename](https://github.com/radiasoft/sirepo/blob/0c8236f1c58a8333874c39b5b2e8cae54af6ddb9/sirepo/http_request.py#L77)
