### ISSUE TITLE
Input file field disappears after 1st import

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6226]
In opal, when you import a *.in file which has external files, it will prompt for the files. If you select cancel, and then select "Import" again, it shows the import dialog, but the input file is missing:

![x](https://github.com/radiasoft/sirepo/assets/6516910/dfbcb095-71b1-4008-b0d4-3604f03c0824)

Instead, it should reset its state when dismissed and show the correct fields when importing:

![x2](https://github.com/radiasoft/sirepo/assets/6516910/8035ea31-54e8-4c25-a3ea-36e948a80aac)

This issues could be looked at along with #6123

**Comment by gurhar1133** [comment]
@moellep I think this can be closed?
