### ISSUE TITLE
Add SIREPO.traceWS and better logging of ws messages

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#6250]
@e-carlin [writes](https://github.com/radiasoft/sirepo/pull/6092#pullrequestreview-1596418811):
> With websockets and a binary protocol that now doesn't work. What about adding a pkdc to parse_message and websocket_response that allows one to dump the message (with associated uri, seq num, etc)?

Add pkdc like feature called sr_trace or similar to sirepo.js. In the client, you can expand the object as opposed to cluttering a terminal window with all messages between client and server, which are often quite large. sr_trace could get the control regex from pkdebug. We could also set it dynamically in production from the js console.

```js
function sr_trace(...args) {
    if (sr_trace_re) {
        if (sr_trace.caller === null || sr_trace_re.match(sr_trace.caller) {
             // probably want better formatting of sr_trace.caller
             console.log(sr_trace.caller, ...args);
        }
    }
}
```

**Comment by moellep** [comment]
Here's a simple implementation, which can be enabled on the client by typing "SIREPO.traceWS = true" in the javascript console. It logs the sequence number, url and data on the send, and sequence number, and either json content or content-type on replies:

**Comment by moellep** [comment]
```diff
@@ -2093,6 +2093,15 @@ SIREPO.app.factory('msgRouter', ($http, $interval, $q, $window, errorService) =>
             wsreq.deferred.reject("invalid reply from server");
             return;
         }
+        if (SIREPO.traceWS) {
+            srlog(
+                'ws reply:',
+                header.reqSeq,
+                header.contentType == "application/json"
+                    ? JSON.parse(content)
+                    : `<${header.contentType} content>`,
+            );
+        }
         wsreq.deferred.resolve({
             data: header.contentType == "application/json" ? JSON.parse(content) : content,
             status: header.httpStatus
@@ -2207,6 +2216,9 @@ SIREPO.app.factory('msgRouter', ($http, $interval, $q, $window, errorService) =>
         if (wsreq.timeout) {
             wsreq.timeout.then(() => {_remove(wsreq);});
         }
+        if (SIREPO.traceWS) {
+            srlog('ws send:', wsreq.header.reqSeq, url, data);
+        }
         const c = (buffers) => {
```
