### ISSUE TITLE
job_agent support for configuring OpenMP/MPI

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#6266]
We need to configure cpus-per-task and OMP_NUM_THREADS when running openmc. We also should not run more than 8 tasks-per-node. see https://github.com/radiasoft/sirepo/issues/6220#issuecomment-1699609725

**Comment by moellep** [comment]
This was added with 6412e14
tasksPerNode and sbatchCores are fixed at 8 and 16. 
sbatchNodes is editable and defaults to 32.

**Comment by e-carlin** [comment]
This is done except for setting `$OMP_NUM_THREADS`. We don't have a great way to add app specific configuration like this to the sbatch script. I'll need to invent something.

**Comment by e-carlin** [comment]
NVM. We do add it directly to parameters.py https://github.com/radiasoft/sirepo/blob/0210c18c8b9074e800367e6a0094a3ceb6cc8d32/sirepo/package_data/template/openmc/openmc-sbatch.py.jinja#L3 . That's fine and plays well with the way openmc is run.

**Comment by robnagler** [comment]
Also note that this will vary with the codes.
