### ISSUE TITLE
sample_processed.tif looks funny

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#627]
When I download an image, it looks funny. I had to upload the image converted to jpg, because Issues doesn't support tif:

![sample_processed](https://cloud.githubusercontent.com/assets/5495179/21992449/bb39b5ae-dbd3-11e6-8aef-11aa5c4c5110.jpg)

The tif is valid so I think it is being transferred from the server correctly. This is from Sample from image example.

**Comment by mrakitin** [comment]
I don't have this problem on alpha. Do you have a link with the issue?

**Comment by robnagler** [comment]
Never mind. It's something that happens during the download. I'll debug further. The file on the server and the downloaded version only start to differ way into the file. This output is from an od -x:

```text
11c11
< 1326560      0000    0000    ef00     bdbf    bfef    00bd    0000    0000
---
> 1326560      0000    0000    8400    0083    0000    0000    0000    0000
```

The first line is from the downloaded file. Not obvious what the changes are.

Anyway, I'll debug further, but it is odd how it is getting corrupted, since you'd think the header would be messed up, but it isn't.
