### ISSUE TITLE
autoSave callback confusion

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#6273]
[autoSave](https://github.com/radiasoft/sirepo/blob/8fcc5e530387c9b31e4d0f6206ff3816dc339425/sirepo/package_data/static/js/sirepo.js#L398) has some code that doesn't quite make sense:

```js
                    successCallback: function (resp) {
                        if (resp.error && resp.error == 'invalidSerial') {
                            srlog("...snip...")
                            refreshSimulationData(resp.simulationData);
                            errorService.alertText("...snip...")
                        }
                        else {
                            lastAutoSaveData = self.clone(resp);
                            ['simulationSerial', 'name', 'lastModified'].forEach(f => {
                                savedModelValues.simulation[f] =
                                    self.models.simulation[f] = lastAutoSaveData.models.simulation[f];
                            });
                        }
                        if ($.isFunction(callback)) {
                            callback(resp);
                        }
                    },
                    errorCallback: function (resp) {
                        if ($.isFunction(errorCallback)) {
                            errorCallback(resp);
                        }
                    },
```

If there is an error and it is not invalidSerial, the data are saved even though the response was "error". I suspect that the only case error would be returned is invalidSerial in practice. However, I want to move invalidSerial to an srException, since it's an oddball case for util.Error.

The other thing that happens in an error case is that callback is called, not errorCallback. I'm not sure that makes sense either.

@moellep what do you think about calling errorCallback in an error case, always, and not saving the models.

**Comment by robnagler** [comment]
The situation is even worse. The resp.simulationData is not the data on disk, but is the [incoming data](https://github.com/radiasoft/sirepo/blob/8fcc5e530387c9b31e4d0f6206ff3816dc339425/sirepo/simulation_db.py#L588). `on_disk` is just [the simulation model](https://github.com/radiasoft/sirepo/blob/8fcc5e530387c9b31e4d0f6206ff3816dc339425/sirepo/simulation_db.py#L629). Therefore, refreshSimulationData is getting the old data.

I was testing the values in server1_test.py, because there were no tests for it, and discovered this issue. 

I'm going to take this out and refresh the entire app.

**Comment by moellep** [comment]
The errorCallback case is never actually used - it was there for a rename error, but that is handled on the server by creating a unique name and returning it (which is currently ignored on the client, but should not be). I'll see what the actual error cases are - this api is not called directly very often in the apps.
