### ISSUE TITLE
Clarify api names for downloads

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#6287]
- [ ] Replace "downloadFile" with "downloadLibFile"
- [ ] Replace "downloadDataFile" with "downloadRunFile"
 
This will touch a lot of files including tests.

**Comment by robnagler** [comment]
We could deprecate the usage, and just create an alias. There's also the URL issue. Do we want to rename that? It does show up in the browser with right click as both are GETs.

**Comment by mkeilman** [comment]
I doubt users even notice the url, but we will. I think they should match.
