### ISSUE TITLE
SRW - changed examples should be marked

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#634]
Request from @ochubar:
> Sometimes it's unclear if an example in Sirepo is changed or not. It would be very convenient to have some kind of a mark to show that the example is changed and the tooltip recommendation to discard changes to the example to restore it with the default parameters.

Something like http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_glyph_alert&stacked=h can be used.

**Comment by bruhwile** [comment]
I agree that this is a problem, which should be addressed.
An alternative solution would be to make the examples 'read only' and also
to prevent users from deleting them.
