### ISSUE TITLE
alpha release 1/20 5:15p

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#635]

**Comment by robnagler** [comment]
Actually, may be a little while, because another build going on.

**Comment by robnagler** [comment]
Built and pushed.

**Comment by mrakitin** [comment]
Thanks Rob!

-------- Исходное сообщение --------
Отправитель:Rob Nagler <notifications@github.com>
Отправленные:Fri, 20 Jan 2017 20:35:43 -0500
Получатель:radiasoft/sirepo <sirepo@noreply.github.com>
Копия:Subscribed <subscribed@noreply.github.com>
Тема:Re: [radiasoft/sirepo] alpha release 1/20 5:15p (#635)
