### ISSUE TITLE
20231115 Test all schema-common.json routes

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#6350]
We should have the ability to test all routes. I removed errorLogging accidentally, and we don't have a test for it. It's an important route to have a test for. I think we can make sure we have tests for all routes so this is an audit task at first and then we'll create tests for the missing routes.

**Comment by robnagler** [comment]
Add test for sirepo.template.srwpy.srwl_uti_brightness https://github.com/radiasoft/sirepo/issues/6351 (

**Comment by rorour** [comment]
How should this be tracked? Keep a list somewhere mapping tests to routes? Or make this a test in itself so we can make sure to add a test each time we add a new route?

**Comment by robnagler** [comment]
That's a good question. Maybe we could have srunit modify a common file that gets cleared by `pykern test` and maybe checked by pykern test. Another option is code analysis, which might be possible with strict policies on how we call the APIs.

**Comment by rorour** [comment]
Can you explain more what "code analysis" would be? Is there an existing example of this in Sirepo?

**Comment by robnagler** [comment]
> Can you explain more what "code analysis" would be? 

We could do this with true code analysis using Python's parser, or we could do hacky code analysis with regexes, e.g. this code golf:

`perl -n -e '$n && ($n=0,print); /sr_get(?:_json)?\((.*)$/ && ($1 ? print("$1\n") : $n++)' {,*/}*.py`

This is what I mean about "strict_policies". We always do a get via "sr_get", for example, so it is an easy pattern to match for. This probably would get us a long way there.

The problem with static analysis like this is that some values are dynamic. Run the above, and you'll see r.uri, but those are only a few cases so we could special case them statically. However, a better implementation would do in situ analysis.

> Is there an existing example of this in Sirepo?

A simple version is pykern.pkcli.ci.check_prints. More complex is `black` and linters.

**Comment by rorour** [comment]
67% coverage (50/74)

Routes not touched by tests:
```
admModerateRedirect
analysisJob
authGithubAuthorized
authGithubLogin
authState2
checkAuthJupyterhub
contentTooLarge
error
errorLogging
favicon
faviconPng
findByName
forbidden
jupyterHub
migrateJupyterhub
oauthAuthorized
proxyError
pythonSource2
redirectJupyterHub
runMulti
simOauthFlashAuthorized
simulationRedirect
simulationSchema
srwLight
```

**Comment by robnagler** [comment]
Good data. Many of these are errors, which are typically hard to produce. Some of these we could mock to test our workflow, e.g. github auth (see ldap_test). At least one API should be deleted, e.g. runMulti.

Next step: Please go through all of these and document how you would implement the test (e.g. mocking interfaces).

**Comment by rorour** [comment]
- **admModerateRedirect**
  - SIREPO_FEATURE_CONFIG_MODERATED_SIM_TYPES=jupyterhublogin SIREPO_AUTH_ROLE_MODERATION_MODERATOR_EMAIL=vagrant+moderator@localhost.localdomain
  - `fc.sr_get('admModerateRedirect', redirect=False).assert_http_redirect('adm-roles')`
- **errorLogging**
  - assert that it logs message containing javascript error? send a request similar to kind sent by errorService.logToServer
- **favicon & faviconPng**
  - are these used? I only see paths to the files in the code
- **pythonSource2, findByName**
  - test similarly to pythonSource & findByNameWithAuth in sim_list_test.py
- **redirectJupyterHub, jupyterHub**
  - SIREPO_FEATURE_CONFIG_MODERATED_SIM_TYPES=jupyterhublogin SIREPO_AUTH_ROLE_MODERATION_MODERATOR_EMAIL=vagrant+moderator@localhost.localdomain
  - `fc.sr_get('redirectJupyterHub', redirect=False).assert_http_redirect('jupyterHub')`
- **checkAuthJupyterhub**
  - check response status code?
- **migrateJupyterhub**
  - test that user gets migrated (similar to db_upgrade_test.py?)
- **simulationRedirect**
  - `fc.sr_get('simulationRedirect', redirect=False).assert_http_redirect('simulations')`
- **simulationSchema**
  - ```
        r = fc.sr_post_form(
        "simulationSchema",
        data=PKDict(simulationType=fc.sr_sim_type),
    )
    ```
  - test that response is dict and has certain items (model, view)?
- **srwLight**
  - assert returns expected file type/content
- **customerrors: contentTooLarge, proxyError, error, forbidden, notFound**
  - not sure exactly what we would want to test here
- **simOauthFlashAuthorized, authGithubAuthorized, oauthAuthorized**
  - came across github_srunit.py, which doesn't seem to be used anymore? 
  - not sure if we want to actually interact with flash/github or use something like MockOAuthClient
- **authGithubLogin**
  - previous test for this was removed
- **authState2**
  - pkre on response similar to authState call in auth1_test?
- **sirepo.template.srwpy.srwl_uti_brightness**
  - `from sirepo.template import srwl_uti_brightness`
- ~runMulti~
- ~analysisJob~ (test added)

**Comment by rorour** [comment]
> Change auth_role_moderation_test to use admModerateRedirect instead of admModerate.

Can you explain how to do this? I've gotten extraordinarily confused trying to do this, because `admModerateRedirect` redirects to `/adm-roles`, not `/adm-moderate`

**Comment by robnagler** [comment]
admRoles is local redirect. This should be verified that you can then request the app that comes back. (You can ignore the local part.) My mistake for saying "instead of". I think I meant "first" so we know that it redirects to the app page we expect.

**Comment by rorour** [comment]
Do we want to remove both `authGithubLogin` and `authGithubAuthorized`?

**Comment by robnagler** [comment]
Yes.

**Comment by robnagler** [comment]
Need to remove the auth method, too.

**Comment by rorour** [comment]
Can I remove everything related to jupyterhubmigrate?

**Comment by robnagler** [comment]
Yes, this will greatly simplify the code.

**Comment by robnagler** [comment]
Make a separate issue and PR.

**Comment by rorour** [comment]
Can auth_github_user_t be removed?

**Comment by robnagler** [comment]
Yes, we'll need a db upgrade.

**Comment by rorour** [comment]
What should be done with auth_db_test.py?

**Comment by robnagler** [comment]
Removed.

**Comment by rorour** [comment]
The idea for testing errorLogging was:

> assert that it logs message containing javascript error? send a request similar to kind sent by errorService.logToServer
> Agreed, and maybe add a karma test for the javascript side.

For the javascript side, appState_test.js passes through all errorService code.

For the server side - it seems that capsys cannot capture the writing to the log because the server that is doing the logging is a separate process from the test that posts to the api. Does that sound correct?

This is the best test I can come up with given the above, please let me know if you have any better ideas.

```
    r = fc.sr_post("errorLogging", PKDict(message="error message"))
    pkeq("ok", r.state)
```

**Comment by robnagler** [comment]
Of course! The test could be more complicated, but I fear diminishing returns. Let's leave it like this.

**Comment by rorour** [comment]
If we want to test api_simOauthFlashAuthorized, we will need to add env vars into ci such as SIREPO_SIM_OAUTH_FLASH_SECRET. I also don't see how we could really test a successful request to the API, but we could test that forbidden gets raised. What are your thoughts?

**Comment by robnagler** [comment]
CI already doesn't check a lot of things. We don't address this right now, but we should.

We could check for existing of the secret, and skip the test if not. We do this in other places.

We could setup the server to use an dummy oauth server that we could technically leave running somewhere. This would test our code, which is really the point of these tests. Our tests could handle the redirect, enter a login via json to the dummy oauth server. This would be convenient for development, too. I think we must have used our own oauth server for testing. This could be added to run.sh, since that's only used for dev, and we don't need always need to test with the flash server.

This obviously is also subject to diminishing returns. Let's have a discussion about the time required.

**Comment by e-carlin** [comment]
FWIW - In dev we use an oauth server hosted by our collaborators.

**Comment by robnagler** [comment]
yes, i'm thinking it is better to simply start the server in the test.

**Comment by robnagler** [comment]
An alternative is to mock like we did with github_srunit. This might be better, since the point of unit tests is to test just our code, not integration. (Although we do a lot of integration tests.) An integration test for oauth would be different should run off alpha, and would involve scraping and playright, which would be nice, but of low value.
