### ISSUE TITLE
Outline data is incorrectly generating server error

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#6370]
This is on master, not deployed yet. On the visualization tab, an error gets thrown:
```javascript
Error: a server error occurred: status=200
    at cloudmc.js?20230928.204225:408:23
    at thisErrorCallback (sirepo.js?20230928.204225:2730:13)
    at sirepo.js?20230928.204225:2743:21
    at angular.js:17945:37
    at m.$digest (angular.js:19112:15)
    at angular.js:19432:15
    at Tg.completeTask (angular.js:21231:7)
    at angular.js:6812:7 'Possibly unhandled rejection: {}'
```
The data coming back looks like:
```
"{\n    \"1\": {\n        \"x\": [\n            [\n                [\n                    [\n                        -0.02,\n                        0.05\n                    ],\n                    [\n                        0.02,\n                        0.05\n                    ],\n                    [\n                        0.025,\n                        0.05\n                    ],\n                    [\n                        0.025,\n                        0.043333333253860476\n                    ],\n                    [\n                        0.025,\n                        0.0033333332538604734\n                    ]...
```
which is the true data stringified.

**Comment by moellep** [comment]
This bug happens when web sockets are enabled with SIREPO_FEATURE_CONFIG_UI_WEBSOCKET, which is the default on dev.

**Comment by mkeilman** [comment]
Is there another issue for this? I'll close this as a dupe if so

**Comment by moellep** [comment]
No, I think this is the right issue - I'm guessing the bug is somewhere in the new websocket code. You can keep that feature turned off on dev when you work on cloudmc in the meantime.

**Comment by robnagler** [comment]
I'll fix this. downloadDataFile hasn't been used in this way before.

**Comment by robnagler** [comment]
BTW, I hadn't noticed this before [in `$http.request` doc](https://angular.io/api/common/http/HttpClient#request):

- The responseType value determines how a successful response body is parsed.
- If responseType is the default json, you can pass a type interface for the resulting object as a type parameter to the call.

That's why json gets parsed implicitly. It's angular, not the browser.
