### ISSUE TITLE
ws_id documentation

### ISSUE THREAD

**Issue by rorour** [radiasoft/sirepo#6396]
When running Sirepo I see a lot of messages like this in the logs:

```
../sirepo/uri_router.py:282:parse_msg start ws_id=1 req_seq=29 uri=/run-status
../sirepo/uri_router.py:246:on_message end ws_id=1 req_seq=29 uri=/run-status uid=li-Gng33EeR
../sirepo/uri_router.py:282:parse_msg start ws_id=1 req_seq=30 uri=/run-status
../sirepo/uri_router.py:246:on_message end ws_id=1 req_seq=30 uri=/run-status uid=li-Gng33EeR
../sirepo/uri_router.py:282:parse_msg start ws_id=1 req_seq=31 uri=/run-status
../sirepo/uri_router.py:246:on_message end ws_id=1 req_seq=31 uri=/run-status uid=li-Gng33EeR
```

Is this a bug for `ws_id` to always =1? Looking at the code in uri_router.py it's not clear to me.
I think the meaning of `ws_id` and its difference from `req_seq` should be documented in uri_router.py. @robnagler could you explain here?

**Comment by robnagler** [comment]
ws_id is the websocket identifier. Each client opens only one websocket so you'll see ws_id=1 in a typical dev environment.

req_seq is the request sequence number. This is used to match up requests and replies, and you'll see a lot of those.
