### ISSUE TITLE
scans tab layout improvement

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6426]
Moving the search controls into a smaller panel, and adding an additional panel which could show information on the selected row in the list and/or general system status, etc. For example, the plan_args json could appear in a formatted fashion. Below is a rough idea.
![layout](https://github.com/radiasoft/sirepo/assets/6516910/0e73f19f-f2ce-4d09-8d29-003a9502ba2a)

**Comment by rorour** [comment]
fixed by https://github.com/radiasoft/sirepo/pull/6889
