### ISSUE TITLE
20231130 Add full path to analysis files in log

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6431]
Paths in the scan logs are relative. It would be helpful to print the absolute path to the analysis directory at the top of the log file.

**Comment by rorour** [comment]
I am confused by this one as I see 3 absolute paths at the top of the log. What exactly do we want to add? 
None of the scans are currently passing for me so I don't have any analysis images but I'm pretty sure they should be in the same dir as the log file, which has the full path at the very top of the log modal.

```
/home/vagrant/src/radiasoft/raydata/run/chx/2023_2/commissioning/Results/e83fbb74-051c-4b39-b5d5-454d53576699/run.log

ERROR: This cross-compiler package contains no program /home/vagrant/miniconda/envs/analysis-2019-3.0.1-chx/bin/x86_64-conda_cos6-linux-gnu-c++
ERROR: activate-gxx_linux-64.sh failed, see above for details
Input Notebook:  /home/vagrant/src/radiasoft/raydata/dev_notebooks/chx/2023_2/AutoRuns/commissioning/XPCS_SAXS_2023_v2.ipynb
Output Notebook: /home/vagrant/src/radiasoft/raydata/run/chx/2023_2/commissioning/ResPipelines/XPCS_SAXS_2023_v2_e83fbb74-051c-4b39-b5d5-454d53576699.ipynb
```

**Comment by e-carlin** [comment]
It could be possible we just need to make it more clear in the output? Like put it in a box with a label?

I think in dev we should create a notebook that produces a couple of images and saves a pdf. That way we aren't constantly running into problem trying to get their notebooks to run in our env.

**Comment by rorour** [comment]
Closing after discussion in today's demo
