### ISSUE TITLE
SRW - add SRX virtual beamline

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#646]
This has been requested by T Shaftan

https://www.bnl.gov/ps/beamlines/beamline.php?r=5-ID

**Comment by mrakitin** [comment]
Thanks for creation a ticket for that issue David. I'll address it once I get new scripts from @ochubar.

**Comment by mrakitin** [comment]
Should be done along with the HXN beamline example (#600).

**Comment by mrakitin** [comment]
Added in c3a0385.
