### ISSUE TITLE
20231211 Make oauth work with websockets

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#6482]
We had an issue related to flash not working https://github.com/radiasoft/sirepo/issues/6378 . I [fixed that](https://github.com/radiasoft/sirepo/pull/6481) but noticed along the way that oauth only works when websockets are disabled (feature_config.ui_websocket=False). 

My hunch is that the oauth redirect response happens through a websocket message and we try to do Set-Cookie but this doesn't have any effect when operating in websockets. So, we'll need to find a way around this. 

Some possible ideas:
- Augment our websocket messages so they have a cookie field and have the browser update the cookie
- Don't use websockets for the oauth flow

**Comment by robnagler** [comment]
> Augment our websocket messages so they have a cookie field and have the browser update the cookie

Can't set cookies in a websocket.

> Don't use websockets for the oauth flow

Easy. There's a regex for this. See sirepo.js `_isAuthUrl`

**Comment by e-carlin** [comment]
>> Augment our websocket messages so they have a cookie field and have the browser update the cookie
> Can't set cookies in a websocket.

My point here was we could add the cookie to the body of the message. When our js in the browser receives the message it could grab the cookie and set it. 

> Easy. There's a regex for this. See sirepo.js _isAuthUrl

Perfect. Thanks.

**Comment by robnagler** [comment]
> My point here was we could add the cookie to the body of the message. When our js in the browser receives the message it could grab the cookie and set it.

This would work halfway. We then would need a "cookie header" equivalent to modify the state of the websocket. I've been avoiding this. Auth is something that works already with http, and the api server supports both http and websocket messages. I see no reason to change that flexibility. What we need is to add more flexibility to the route defs to say whether the message can be sent over websockets.

**Comment by e-carlin** [comment]
@rorour can you assign a deadline that works for you? Not a massive rush but needs to get done before we can deploy websockets to prod.
