### ISSUE TITLE
oauth does not work on alpha/beta/localhost

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#649]
I've tried to login to Sirepo using my GitHub credentials, but it failed on the callback_uri step:
![oauth](https://cloud.githubusercontent.com/assets/13209176/22312752/2f1a3714-e327-11e6-8cf6-b4adf42b12e2.png)

Reproducible on alpha, beta and local dev environment.

**Comment by robnagler** [comment]
This is the URL

```
https://alpha.sirepo.com/github/oauth-authorized?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=8sS1g83flEBPmUO1ZLUiuUgzDKuDYqkEyP2spC7fRTgZwJTAgigoMcHbT2rMY0Cr
```

**Comment by robnagler** [comment]
I've got this. It's a config issue

**Comment by robnagler** [comment]
Need to fix URL on beta when release is pushed: https://beta.sirepo.com/oauth-authorized/github

@mrakitin Note the URL change. You'll need to update your OAuth Application Settings for your server when you pull this release.

**Comment by robnagler** [comment]
Fixed on beta.

**Comment by mrakitin** [comment]
Thanks @robnagler, I updated the oauth settings and reconfigured our machines. Now it works fine.
