### ISSUE TITLE
problem running cloudmc on nersc

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6505]
Running cloudmc on nersc encounters this error:

[Errno 2] No such file or directory: '/pscratch/.../cloudmc/...-...-openmcAnimation/run.log'

Looking in that directory, it looks like it has successfully setup the simulation and run the cloudmc "prep-sbatch.py" successfully, but there is no run.log, or log file with a stack trace of what was executing when the error occurred.

**Comment by moellep** [comment]
@robnagler related to this, you could also review the merged PR which added cloudmc nersc support:
#6478

**Comment by robnagler** [comment]
More data: It failed the first time. I ran the sbatch script that was created, and it ran fine. On the second try via the UI it worked. The only difference I could see in the sacct is:

```diff
134c134
<        "kill_request_user": "<user>",
---
>        "kill_request_user": "",
```

There's no cancel in the agent, sirepo, or supervisor logs. 

I ran it again after reducing the batches to 3 and particles to 1000. Then it failed with:

```txt
slurmstepd: error: *** JOB <snip> ON nid004208 CANCELLED AT 2023-11-13T23:43:16 ***
srun: error: Unable to create step for job <snip>: Job/step already completing or completed
```

There was a run.log, but the UI reported that there was none. However, I could download the run.log from the UI and it was there when I looked in the shell. 

[NERSC doc](https://docs.nersc.gov/jobs/troubleshooting/) says: 

```txt
Possible causes/remedies:
This may be caused by a system issue. Please report to NERSC.
```

I ran it again, which worked.

Not sure what's going on. Just reporting here as a checkpoint.

**Comment by robnagler** [comment]
Submitted to NERSC. I can't see a pattern. The only odd one is that the run.log was not there when the job crashed but was there a few seconds later so that it could be downloaded. That may be a red herring. Let's see what NERSC says.

**Comment by moellep** [comment]
It could be that the template.cloudmc module is trying to read the run.log before it is available, and when it fails it ends up canceling the whole simulation. I'll add check that verifies that the run.log is present before reading.

**Comment by moellep** [comment]
7fddb21 appears to have fixed this on alpha and beta.
