### ISSUE TITLE
Add 1d plot of a specific energy bin when an energy filter is active

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#6527]
- [x] #6132
"See the notebook at EFilterExample.ipynb for an example."

**Comment by mkeilman** [comment]
Could someone point me to where EFilterExample.ipynb actually lives? thx!

**Comment by moellep** [comment]
You can login into jupyterhub, open a terminal and find it here:
$ ls ~/jupyter/StaffScratch/sjcrs/Sharing/OpenMC_EnergyFilter/EFilterExample.ipynb

**Comment by robnagler** [comment]
Sent over a private channel
