### ISSUE TITLE
elegant: RPN_DEFNS needs to be set to run python source

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#655]
You can't run the downloaded version without setting $RPN_DEFNS. For the archive version, we can include the file and set the variable dynamically in the source generator (or by detecting the existence of the file at run time).

Is this the right solution?

**Comment by moellep** [comment]
We use the standard defns.rpn provided by elegant. I don't think we should
bundle it with the download. Having the script exit and complain about the
missing environment variable is fine.
