### ISSUE TITLE
radia field path numPoints needs to have upper bound

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6563]
There is a memory issue in template.radia _build_field_map_pts() which can cause the sirepo server to crash with an out-of-memory error:

https://github.com/radiasoft/sirepo/blob/master/sirepo/template/radia.py#L479

If numPoints is something larger 100 or so, it will create an array which is too large. In one case a user set it to 5000 which crashed the server.

**Comment by mkeilman** [comment]
Oy - yes that's 125,000,000,000 points (5000^3)!
