### ISSUE TITLE
cancel a stateless-compute

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6578]
In raydata, if you move quickly between tabs, a queue of stale stateless-compute calls gets processed before the final one. If possible, there should be a call to cancel a stateless compute, or possibly the stateless-compute calls to get scan data should be changed to an analysis job which can be canceled when navigating between tabs.

**Comment by robnagler** [comment]
Stateless computes can't be canceled from the supervisor perspective, since they are a simple send-receive-reply. There's no job id returned to the caller. This could be added, but would introduce latency. This has to be managed client side, which wouldn't be hard, I don't think.

**Comment by moellep** [comment]
This issue is no longer a priority with the performance improvements with #6787
