### ISSUE TITLE
Recently reported issues in Sirepo

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#661]
Here is a raw list of the issues reported by Oleg today. It will be split to separate issues later.
SRW issues (02/03/2017):

1) Crystal:
  - Diffraction plane - make 0 by default and don't change automatically;
  - Round very small numbers obtained automatically.

~~2) Finite bandwidth (for partially-coherent calculations only). #708~~

~~3) Cosmetic change - white = passive, blue = active - it's opposite to Coherent/Partially Coherent tabs.~~ - implemented by Paul.

4) Double drifts for disabled elements should be combined (if propagators are identical).

~~5) New Folder pop-up window should be in the middle or movable/resizable.~~ - covered by #677

6) Values in CRL dissappear in IE (in a normal (not maximized) window).

~~7) Propagation parameters do not fit in a mobile screen.~~ - fixed in #880

8) CRL:
  - Focal plane -> The plane of focusing.
  - Delta does not correspond to Refractive index decrement. Need to make it more consistent.
  (Fiber defocuses!)

~~9) Toroidal mirror - add. #500~~

~~10) Communication timeout - many fast simulations does not finish, need to check what's going on (only restart of the browser helps).~~ - cannot reproduce the problem at the moment.

~~11) Flux report - methods (approx)/mag=2 (accurate) combinations don't work for tab. undulator
    For Accurate (tabulated) mag. field hide "Use approximate method". (NOT AN ISSUE)~~

    
~~Urgent:~~

~~12) Add beamlines (DONE)~~
~~13) Last version of Samples example (DONE)~~

**Comment by robnagler** [comment]
These should be separate issues. When they arise again, we'll make issues for them.
