### ISSUE TITLE
running scan on dev has odd directory structure

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6622]
When I run a CHX analysis on dev in raydata it runs in a directory something like this:
commissioning/Results/e5f6bf07-736c-42fd-8575-fc1f8c91cd92/

within that directory is the run.log. 

But after running the analysis, there is also a subdirectory oddly named "~":

```
./run.log
./raydata-execute-analysis.sh
./~/src/rorour/nsls2/data/chx/legacy/analysis/2023_2/commissioning/Results/XPCS_Analysis_Report2_for_uid=e5f6bf07_12-19-2023.pdf
```
Do I have my dev environment set up incorrectly, or is the a bug?

**Comment by robnagler** [comment]
env | grep rorour

**Comment by moellep** [comment]
The analysis scans are running within a miniconda environment. I don't see anything when I run "env | grep rorour" in the miniconda environment, or the penv one.

**Comment by moellep** [comment]
It looks like this is coming from the raydata dev_notebooks - there is this value within the notebook:

"default_dir = '~/src/rorour/nsls2/data/chx/legacy/analysis/'\n",

Should this get set differently when running papermill?

**Comment by rorour** [comment]
Yes, definitely a mistake on my part - looking into it

**Comment by rorour** [comment]
fixed by https://github.com/radiasoft/raydata/pull/142
