### ISSUE TITLE
SRW - no predefined electron beams

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#666]
In some cases the predefined list of beams is empty. This is the case when an old simulation existed, and then was accessed from the most recent of Sirepo when the new beam processing was implemented. Please see the attached zip-file with the problematic simulation (the size is reduced - irrelevant files were removed, but the user's `lib` directory is kept).

[esm_simulations.zip](https://github.com/radiasoft/sirepo/files/759349/esm_simulations.zip)

**Comment by moellep** [comment]
This appears to be fixed with 6b45fe4
