### ISSUE TITLE
Websockets set cookie

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#6689]
https://github.com/radiasoft/sirepo/pull/6683#issuecomment-1909065749

**Comment by robnagler** [comment]
@moellep @e-carlin in order for this to work, we have to turn off HttpOnly on the cookie. HttpOnly is to prevent cross-site scripting attacks. I don't know of anywhere we are embedding anything that isn't sanitized already. I feel like this change is safe. Thoughts?

**Comment by e-carlin** [comment]
I think that's fine.

**Comment by moellep** [comment]
We use $sce.trustAsHtml() in several places, but it looks like the source is always static text.

**Comment by robnagler** [comment]
Thanks.
