### ISSUE TITLE
Math.min.apply() Maximum call stack size exceeded

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6690]
There are many places where apply() is used to apply a function, but this may fail depending on the size of the array. 

For example, if the array has 200,000 points, this will fail:

```javascript
const N = 200000;
Math.min.apply(null, Array.from({ length: N }, () => 1));
// RangeError: Maximum call stack size exceeded
```

The spread operator is also problematic:
```javascript
const N = 200000;
Math.min(...Array.from({ length: N }, () => 1));
// RangeError: Maximum call stack size exceeded
``` 

Instead we should add a sirepo.util to compute this, using a for loop, or whatever is recommended, and replace all the min() and max() calls across the code.

**Comment by mkeilman** [comment]
sirepo-utils has this: `applyInChunks()` and `arrayMin()`, `arrayMax()`, originally made for warpvnd

**Comment by moellep** [comment]
I think applyInChunks() is the wrong approach. A for loop is much simpler - it doesn't need to check it or call slice() or apply().
```javascript:
function arrayMin2(array) {
    let m;
    for (const v of array) {
        if (m === undefined || v < m) {
            m = v;
        }
    }
    return m;
}
```
