### ISSUE TITLE
Hide source geometry if source particles is set to 0

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6706]
Related to #4791

If someone sets the source particles to display to zero, it should also hide the source geometry.

This is especially needed for box geometries which use "only fissionable" since the source is actually the volumes contained which are depletable. Possibly don't show the box for box geometries in this case. See the zpre example.

![Tally-Results-t1-flux-mean](https://github.com/radiasoft/sirepo/assets/6516910/56d38220-cc5b-459a-9f72-da42bd311763)

**Comment by mkeilman** [comment]
I had additional thoughts - maybe this would be better with a "show sources" toggle and an enum of number of source particles, by 10s or something. I don't think you learn anything by showing 16 vs 20 particles. A filter by particle type and energy range might also be nice. And now it's getting complicated so perhaps a tab in tally settings or a separate panel would make sense (in a new issue)
