### ISSUE TITLE
Improve activait image plots

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6720]
The current activait plots generate a static image set with headings on the server, and the results are shown as a single image in the output panels, for example, the petdb output:
![x](https://github.com/radiasoft/sirepo/assets/6516910/7f5b595c-bb26-4604-b2d6-92b97d48fa99)

This could be improved by having the server return a response with each image serialized separately, and use HTML to layout the text and images.

Current request looks like this:
```
args: {
    method: "sample_images",
    modelName: "animation",
   ...
}
```

And returns a structure with serialized jpeg pages:
```
{
    numPages: 5,
    uris: [
        "data:image/jpeg;base64,....",
        "data:image/jpeg;base64,....",
        "data:image/jpeg;base64,....",
        "data:image/jpeg;base64,....",
        "data:image/jpeg;base64,....",
    ],
}
```

Instead, it should return the images individually (9 images), and the UI can layout the data.
```
{
    image: [
        "data:image/jpeg;base64,....",
        "data:image/jpeg;base64,....",
        "data:image/jpeg;base64,....",
    ],
    contour: [
        "data:image/jpeg;base64,....",
        "data:image/jpeg;base64,....",
        "data:image/jpeg;base64,....",
    ],
    predicted: [
        "data:image/jpeg;base64,....",
        "data:image/jpeg;base64,....",
        "data:image/jpeg;base64,....",
    ],
}
```

Selecting the next/prev buttons would make a new request for an image set, passing a "pageCount" or similar argument. The current imagePreview is a statefulCompute call, but should be changed to an analysisJob or a simFrame depending on which would work best.

**Comment by moellep** [comment]
This change would apply to several of the activait plots, and could be split up into separate issues for each:
- Image Samples on the Data Source tab
- Segments Sample
- Best Loss Images
- Worst Loss Images

**Comment by gurhar1133** [comment]
This is done right?
