### ISSUE TITLE
Check against max_message_bytes in SimDbClient.put

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#6726]
If a large file is copied with `SimDataBase.put_sim_file()` via `SimDbClient.put()`, the user gets this error:
```
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
Instead we should check the file size against `max_message_bytes` so we can get an appropriate error message; cf `SimDbClient._sr_post_save_from_url()`

**Comment by robnagler** [comment]
Would be good to have all APIs that send data check this. The same is true for the server replies.
