### ISSUE TITLE
cancel of an analysis job also cancels compute job

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#6783]
This only happens (currently) on a timeout of the analysis job. 

A cancel of a compute job should not cancel an analysis job. It may be the compute job is canceled, because it hasn't converged, and still has valid data for the analysis job. 

The way job_supervisor.api_runCancel is written, one analysis job cancels other analysis jobs.

Simplify this to only cancel the requested job.

**Comment by robnagler** [comment]
@moellep @e-carlin your opinions are welcome.

**Comment by e-carlin** [comment]
> A cancel of a compute job should cancel an analysis job. It may be the compute job is canceled, because it hasn't converged, and still has valid data for the analysis job.

Should or should not? In the not too distant past I believe we changed the code so a canceled compute doesn't cancel the analysis. 

We've trended over time to reducing the "blast radius" of a cancel (reducing the ops canceled by another op being canceled). I'm wondering if we should just change the code so a canceled op only ever cancels itself? Hard to think of all of the cases but I don't know that there is a great argument for a scenario where an op being canceled should cancel another op.

**Comment by robnagler** [comment]
Sorry, "should not" (fixed above, too).

> we changed the code so a canceled compute doesn't cancel the analysis.

Yes, that looks right. This is the opposite case so the cancel of the analysis is canceling the compute.

>  I'm wondering if we should just change the code so a canceled op only ever cancels itself? 

This is subtle, because an "op" is not a "job". For timeouts, we use api_runCancel which is a mistake, I realize now. api_runCancel should be for client requests to cancel runSimulation (compute job). Timeouts should cancel the op and possibly the job (depending on the op).

**Comment by e-carlin** [comment]
> api_runCancel should be for client requests to cancel runSimulation

Agreed.

> Timeouts should cancel the op and possibly the job (depending on the op)

What do you mean by job in this context? ComputeJob? If so, what is an example of where a timeout should cancel a computeJob?

**Comment by robnagler** [comment]
> What do you mean by job in this context? ComputeJob? If so, what is an example of where a timeout should cancel a computeJob?

When the computeJob exceeds its time limit, it's what I'm calling a timeout.

**Comment by e-carlin** [comment]
> When the computeJob exceeds its time limit, it's what I'm calling a timeout.

Makes sense. I don't think a cancel in another op (analysis, io, etc) should cancel the associated compute.
