### ISSUE TITLE
openmc run_in_memory option

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6830]
The notebook below shows a different way to run openmc using `openmc.lib.run_in_memory()`.  I don't think this would work on NERSC, but when running on Sirepo servers, it would allow the partial reports to be viewed while the simulation is running. Something similar to SRW multi-electron plot which can run for a long time, but be stopped early if the results look good.

http://localhost:8086/notebooks/tasks/task_14_variance_reduction/3_sphere_iterative_per_run_ww.ipynb

**Comment by robnagler** [comment]
Do you know how much memory is required?

**Comment by moellep** [comment]
It seems to run with a bit more memory (0.6 % vs 0.2% for the example I was running on devbox).

**Comment by robnagler** [comment]
That will fit. It may be that we hit a memory limit, but we'll find that out on prod. Maybe good to make this feature configurable so we can switch if it has problems.

**Comment by moellep** [comment]
The run_in_memory() option should only be used when needed to refine weight windows. For other simulations, partial results should be implemented via #6855

**Comment by moellep** [comment]
This is included with #6033
