### ISSUE TITLE
energy filter label causes report offset

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6844]
When you add an energy filter to a tally, the energy will be displayed in the upper right corner of the plot. That text is somehow causing the tally to appear offset from the geometry.
![x](https://github.com/radiasoft/sirepo/assets/6516910/ad6052e6-a533-486f-909a-35d0058e4617)

Deleting the label and the plot layout is corrected.
![x2](https://github.com/radiasoft/sirepo/assets/6516910/1d2f0209-a24a-4b6e-8b9b-3983cdae9231)

**Comment by mkeilman** [comment]
I noticed this when working on #6819 and #6527 - I'll be putting in into the plot title
