### ISSUE TITLE
cache sim_frame results on client when using websockets

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6866]
Previous sim_frames were cached in the browser's http cache. With websockets that isn't available, so calls to frameCache will need to keep the data locally and then clear on "modelsUnloaded".

Also consider storing the result on the server and not recalculating unless a frame_arg has changed from the prior request.

**Comment by moellep** [comment]
We discussed and there should also be a cache of the most-recent request for the sim_frame in the animation directory.

**Comment by robnagler** [comment]
I think it should be all sim frames that have been requested. I don't think this data changes until your run a new animation. It could be compressed if we think it could get large.
