### ISSUE TITLE
delete file should return an error if the file is in use

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6867]
When you try to delete an InputFile for a simulation, it should validate that the file is not in use in another simulation. There appears to be some logic for this, but it is not working, at least with elegant.

To reproduce:
Open the elegant "bunchComp - fourDipoleCSR" example, edit the zwake element, download the INPUTFILE field to your computer and rename the file to test.sdds. Then open a copy of that simulation and change the zwake input field to a new file created previously, "test.sdds". Run the simulation and check that it completes successfully. Then open the original "bunchComp - fourDipoleCSR" example, edit the zwake element and delete the "test.sdds" file. It should show an error that the file is in use (preferably with a link to the simulation using the file). When you return to the simulation copy and run it, it will fail with a missing datafile error.

**Comment by robnagler** [comment]
Rename to deleteLibFile at the same time.

**Comment by mkeilman** [comment]
> Rename to deleteLibFile at the same time.

#6287 took care of this I think, unless it's in another place
