### ISSUE TITLE
Move source items in tally settings to their own tab

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#6872]
The tally settings are starting to get cluttered, and source display items are tally-independent. They should still live in the panel but in a new tab.

**Comment by moellep** [comment]
On the Tally Settings panel, add two tabs, "Tally" and "Source". Move the three fields below to the source tab.

![x](https://github.com/radiasoft/sirepo/assets/6516910/f7198054-2f3e-4d43-841a-f09c25236bf9)
