### ISSUE TITLE
Request failed: a server error occured: status=undefined

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#696]
When I tried to run an animated Flux report (Tabulated Undulator example), I got the following error in a browser:
![error](https://cloud.githubusercontent.com/assets/13209176/23865662/c0cd8622-07ec-11e7-9da0-0301f4dc461e.png)

No animated images are shown afterwards. I observed the issue on two independent servers (commit 98f0610e2a0cc899c0889dbc730f11029f7d4798).

**Comment by moellep** [comment]
I don't see this on dev, but I may have an older SRW code. When I released
the latest code to alpha, the error occurs. MPI is working OK on the other
codes.

/var/db/sirepo/user/NcaICuTj/srw/nVdeFvnc/fluxAnimation/run.log
>>
Mar 13 18:57:47   434     0
/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/pykern/pksubprocess.py:72:check_c
all_with_signals 445: exception: ['mpiexec', '--bind-to', 'none', '-n',
'2', '/home/vagrant/.pyenv/versions/py2/bin/python', 'mpi_run.py']
RuntimeError: error exit(1)
  File "/home/vagrant/.pyenv/versions/py2/bin/sirepo", line 11, in <module>
    load_entry_point('sirepo==20170312.180604', 'console_scripts',
'sirepo')()
  File
"/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/sirepo-20170312.180604-py2.7.egg/sirepo/sirepo_console.py",
line 18, in main
    return pkcli.main('sirepo')
  File
"/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/pykern/pkcli/__init__.py",
line 98, in main    argh.dispatch(parser, argv=argv)
  File
"/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/argh/dispatching.py",
line 174, in dispatch    for line in lines:
  File
"/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/argh/dispatching.py",
line 277, in _execute_command    for line in result:
  File
"/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/argh/dispatching.py",
line 260, in _call    result = function(*positional, **keywords)
  File
"/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/sirepo-20170312.180604-py2.7.egg/sirepo/pkcli/srw.py",
line 65, in run_background    mpi.run_script(script)
  File
"/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/sirepo-20170312.180604-py2.7.egg/sirepo/mpi.py",
line 67, in run_script
    return run_program([sys.executable or 'python', fn])
  File
"/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/sirepo-20170312.180604-py2.7.egg/sirepo/mpi.py",
line 41, in run_program    env=env,
  File
"/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/pykern/pksubprocess.py",
line 67, in check_call_with_signals
    raise RuntimeError('error exit({})'.format(rc))
<<

**Comment by moellep** [comment]
After I installed the latest SRW using "bash -l codes.sh srw" I can
reproduce the error on dev now.

**Comment by moellep** [comment]
It looks like the partially-coherent intensity report is producing an invalid result file, the data looks like this. I'll hand this back to @mrakitin

#Intensity [ph/s/.1%bw/mm^2] (C-aligned, inner loop is vs Photon Energy, outer loop vs Vertical Position)
#9000.0 #Initial Photon Energy [eV]
#9000.0 #Final Photon Energy [eV]
#1 #Number of points vs Photon Energy
#-0.00024912501773258265 #Initial Horizontal Position [m]
#0.0002488971200348886 #Final Horizontal Position [m]
#56 #Number of points vs Horizontal Position
#-0.00038000267361540336 #Initial Vertical Position [m]
#0.00038000267361540326 #Final Vertical Position [m]
#126 #Number of points vs Vertical Position
#1 #Number of components
 nan
 nan
 nan
 nan
 nan

**Comment by robnagler** [comment]
Please add a test so the container doesn't build if this error shows up. If you need help writing the test lmk.

**Comment by mrakitin** [comment]
@moellep, thanks for the thorough investigation of the reason of this issue!

It looks like the `nan` (or `inf` in my case) values are caused by the NumPy arrays implementation by Alexey Buzmakov - https://github.com/radiasoft/SRW-light/commit/289c984710ce2f1f7bdd10eefe07c7b8f852170b#diff-d8ea76648d23e6da5b2a0010abbede1dR3929. When I removed that part of the code, the problem disappeared. The difference between Alexey's and my implementation is that he used `dtype=float32`, but I used `dtype=float64`. I'll try to debug it to see where we get those strange values instead of numbers.

@robnagler, are you suggesting to add a test to radiasoft/SRW-light or radiasoft/sirepo?

**Comment by robnagler** [comment]
I think the best would be a test in SRW-light that stops the build if there's an error. The earlier in the process, the better.

**Comment by mrakitin** [comment]
The issue was caused by NumPy's `dtype='float64'`, which was inadequately processed by `srwl.CalcElecFieldSR(wfr, 0, _mag, arPrecParSR)` - https://github.com/radiasoft/SRW-light/blob/289c984710ce2f1f7bdd10eefe07c7b8f852170b/env/work/srw_python/srwlib.py#L4461-L4461.

Here are the results of different memory allocation:
- No NumPy:
![no_numpy](https://cloud.githubusercontent.com/assets/13209176/23932326/abcd2f26-090d-11e7-93dd-bbb96bd05992.png)
- NumPy's `dtype='float32'`:
![float32](https://cloud.githubusercontent.com/assets/13209176/23932363/df893896-090d-11e7-8cbf-e6f192939795.png)
- NumPy's `dtype='float64'`:
![float64](https://cloud.githubusercontent.com/assets/13209176/23932366/e50c9e5c-090d-11e7-938f-e363bbc7ac24.png)

As you can see from the last picture, `arEx` and `arEy` have enormous values (up to ~10<sup>56</sup>) when `dtype='float64'` is used, whereas `dtype='float32'` resultsmatch the results of the original allocation method.

Finally, the `nan`/`inf` values appeared in https://github.com/radiasoft/SRW-light/blob/d72e87b49d153a0dff9633460442bc7c4b6c11e2/env/work/srw_python/srwlib.py#L1598-L1611 after operations with these huge numbers:
![_stokes](https://cloud.githubusercontent.com/assets/13209176/23932596/6e75e378-090f-11e7-8d89-d08b9586b2be.png)

It's fixed on SRW side:
- https://github.com/radiasoft/SRW-light/commit/d72e87b49d153a0dff9633460442bc7c4b6c11e2
- https://github.com/mrakitin/SRW/commit/833a6b51e74e0d023f9606d7f59a6d441b1973cf

TODO:
- [ ] Add test in radiasoft/SRW-light.
- [ ] Build docker containers.

**Comment by mrakitin** [comment]
@robnagler, please have a look at the test for the problem -  	b18236b. `make all` should execute the test and interrupt if there is a non-zero exit code. Comments and suggestions are welcome.

**Comment by mrakitin** [comment]
It's implemented in SRW and SRW-light.
