### ISSUE TITLE
NERSC failing to start with reason=computeJobSerial-mismatch

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#6971]
On dev and prod I get `"reason":"computeJobSerial-mismatch"` and the simulation never starts.

**Comment by robnagler** [comment]
I tested alpha yesterday, and it worked. I'm running a NERSC simulation now.

**Comment by robnagler** [comment]
The output isn't quite right (below). The simulation wasn't canceled. It completed afaict from looking at sqs. The run log was empty, which I would expect. The SRW output log looked fine.

<img width="349" alt="Screen Shot 2024-04-03 at 11 19 00 AM" src="https://github.com/radiasoft/sirepo/assets/5495179/2df86343-8dd5-43a6-9d27-2ec0f8212b1b">

**Comment by robnagler** [comment]
I'm seeing a job agent failure prod trying to import concurrent.futures with the wrong syntax:

```txt
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
```

**Comment by robnagler** [comment]
This is fixed. It had to do with setup.py and pyproject.toml and some change to the environment two weeks ago. The pyproject.toml produces simpler stub for sirepo_console, which works around the problem here caused by the wrong concurrent futures being imported.
