### ISSUE TITLE
srunit._HTTPResponse vs _WebSocketResponse different behavior in _assert_not_exception

### ISSUE THREAD

**Issue by rorour** [radiasoft/sirepo#6975]
The `_assert_not_exception` methods on `srunit._HTTPResponse` and `srunit._WebSocketResponse` behave differently.

I wrote a test that includes a pkexcept:
```python3
    with pkexcept("unexpected status"):
        fc.sr_post_form(
            "simulationSchema",
            data=PKDict(simulationType="xyzzy"),
        )
```
This test passes with websockets enabled and fails without websockets, though both responses have a status code of 500.

Is this expected? Should `_HTTPResponse._assert_not_exception` check status code?

**Comment by robnagler** [comment]
I'm not sure what the issue is here, but you're right the behavior has to be the same. I have been trying to reconcile the two paths, but it's a bit tricky. I'll take a look.
