### ISSUE TITLE
Sbatch failing to start with reason=computeJobSerial-mismatch

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#6981]
This was closed but I'm still encountering the issue https://github.com/radiasoft/sirepo/issues/6971

The request never makes it to the driver (and on to the agent nersc/local). It is failing on the check for computeJobSerial https://github.com/radiasoft/sirepo/blob/c18e0b5fec632d53abac6e368ba5eb616a24cf7a/sirepo/job_supervisor.py#L1088

```
sirepo/job_supervisor.py:1093:_status_reply  self.db.computeJobSerial=0 req.content.computeJobSerial=1712249152
```

**Comment by e-carlin** [comment]
I've narrowed this down. The problem is with[ __db_restore() in the sbatchLogin case](https://github.com/radiasoft/sirepo/blob/f158bb01044ad8ed986b061928abb99131e7d755/sirepo/job_supervisor.py#L958).

__db_restore does what it says, restores the previous db. In the sbatchLogin case (the only place __db_restore is used) this happenns inside of [_run](https://github.com/radiasoft/sirepo/blob/f158bb01044ad8ed986b061928abb99131e7d755/sirepo/job_supervisor.py#L940) which is a an asyncio task. So, we restore the prev db inside of an async task which means the gui and the db are now out of sync. The gui has computeJobSerial xxx (returned from the creation of the run op) and the db has computeJobSerial yyy (whatever computeJobSerial was in prev db).  

Removing __db_restore makes things flow normally. I'm not sure why a restore is needed in the case of sbatchLogin. @robnagler can you shed some light?

**Comment by robnagler** [comment]
It was added by you https://github.com/radiasoft/sirepo/pull/2523. I don't understand exactly why.

I added the update collision to detect this exact problem (stomping on an updated db). I was curious if it happens, which apparently it does.

`_run` is executed after the db is updated with a new compute time, pending, etc. sbatch login is happening too late. Perhaps sbatch login needs to be an explicit gate. We know it is going to be an sbatch driver so this might be the first thing it does. It can then store its state (not/logged in) and just report that back to the user. This would help with the workflow anyway.

**Comment by robnagler** [comment]
I think we can make extra requests to determine if the connection is valid. If we get logged out, then we should handle that differently (go to an error page), because that's not the normal case.

**Comment by e-carlin** [comment]
Talked in person:

We are going to improve the whole log in flow for sbatch.

When a user switches from SMP to sbatch we should gray out the Run Simulation button and do a check for login status. If they need to log in then show them the login modal. Have them log in. Then they can click Run Simulation.

If they navigate straight to the page then same deal. Check before allowing them to click run sim.

In the case where there are sim frames to get we should hold off on getting the sim frames before checking their login status. Again, show the modal before we get sim frames and allow them to click run simulation.

For download data file we don't need to change anything. It opens in a new window and the current behavior is good enough.

The requests for login status will be a new API.

I'm going to think through other states we might need to handle and will draw up some mockups of the UI.
