### ISSUE TITLE
Reading hdf5 file while writes occurring needs to catch multiple exceptions

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#7020]
In the silas app with a sliced laser pulse (ex. 12 slices), if you change the "Number of Mesh Points in Slice" to a larger value, like 128, the plot may fail when the data is requested as the slice writes are occurring. The code is currently catching a BlockingIOError and retrying after a timeout, but in this case it was a regular IOError "Errno 11 Unable to open file (unable to lock file, errno = 11, error message = "Resource temporarily unavailable".

We should add a common hdf5 file reader which handles these cases. Something like adding a method to ```HDF5Util.read_while_writing(path, callback, retries=10, timeout=3)``` which catches BlockingIOError and IOError and retries.

Then this should be used where-ever hdf5 files are read while writes may be occurring. Alternatively, look into hdf5 read locks.

**Comment by moellep** [comment]
Also see https://stackoverflow.com/questions/50977839/locking-of-hdf-files-using-h5py

**Comment by robnagler** [comment]
Let's write this in a sirepo.util or even sirepo.hdf5

**Comment by moellep** [comment]
We have a library sirepo.template.hdf5_util and the companion sirepo.template.sdds_util.
