### ISSUE TITLE
Add mode to disable users

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#7050]
Should also come with a cli to do this. This would not delete the user, but simply prevent the user from accessing anything once logged in.

**Comment by robnagler** [comment]
A simple solution would be to add `api_perm.require_not_disabled` and `auth_role.DISABLED`. We would add the role to disable the user. Users without the role would pass the perm check.

**Comment by rorour** [comment]
> Should also come with a cli to do this. 

Something more than `sirepo roles add disabled` ?

**Comment by rorour** [comment]
what milestone?

**Comment by robnagler** [comment]
cloudmc
