### ISSUE TITLE
Change moderation Deny text

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#7051]
@bruhwiler will supply the text. The current text in {deny_email.jinja](https://github.com/radiasoft/sirepo/blob/c70d4401cb0315737b03f440f450a2f6c7fd3ec7/sirepo/package_data/auth_role_moderation/deny_email.jinja) is:

`Your request for {{ app_name }} access has been denied.`

**Comment by bruhwiler** [comment]
Your request for {{ app_name }} access has been denied. Community access requires an email address associated with a university, company or research institution. Access is not allowed from countries of particular concern, as designated by the U.S. Department of State, https://www.state.gov/countries-of-particular-concern-special-watch-list-countries-entities-of-particular-concern/
