### ISSUE TITLE
panelState loading timer needs to be bound to a frame/computeJobSerial 

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#7054]
https://github.com/radiasoft/sirepo/blob/5eecebd2b47618af00216849dfaf0488d781b20a/sirepo/package_data/static/js/sirepo.js#L1272

The frame returned may no longer be relevant to the panel being displayed. For example, refresh a page with frame reports, request for the frame is started, user clicks start simulation, then frame comes back. The frame is no longer relevant to the simulation being run so it shouldn't do anything to the panelState (ex set/clear loading states)

**Comment by robnagler** [comment]
See also:
- https://github.com/radiasoft/sirepo/issues/4004
- https://github.com/radiasoft/sirepo/issues/4818
