### ISSUE TITLE
report colormap selection

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#706]
Add a report setting for selecting the colormap for intensities.

**Comment by moellep** [comment]
Additionally, if the colormap selected is non-grayscale, then a colorbar should be shown which shows the color range.

**Comment by bruhwiler** [comment]
I suggest that the default should be viridis

**Comment by mrakitin** [comment]
Additional discussion was here - https://github.com/radiasoft/sirepo/commit/7a9ce3576b9a830b18775878e683fb8bb6308045. Probably we need to create a separate issue for general colormaps processing for all applications, not just Shadow3.

**Comment by moellep** [comment]
As a first step, the colormap should be selectable on a per-simulation basis. Possibly from a "Report Preferences" link in the cog wheel. Apps would continue to have a default colormap, but the user could override it from the preferences, which could be stored in a model which is common across all apps.

**Comment by mkeilman** [comment]
I'm wondering if setting the colormap per report is reasonable, as it doesn't pertain outside that context. Here it is as part of the cog wheel:
![colormapapp](https://user-images.githubusercontent.com/30352290/31914111-a1ab105a-b806-11e7-9cb3-b05a79531c7e.png)

I've been finding the multiple nested dropdown menus a bit hard to navigate...

Here it is as part of the report's model and view:
![colormapreport](https://user-images.githubusercontent.com/30352290/31914235-1cbea34c-b807-11e7-9493-bffc3bed9a0a.png)

In either case, is the displayed color range in line with what you were imagining?

**Comment by bruhwiler** [comment]
Looking good, Mike.
I think setting the color map independently for each report is the way to go.
I suggest they default to viridis in most cases.
I would put grayscale and viridis at the top of the list.
I see no reason to limit the number of options unless each option requires additional work. Why not list all that are available...?

**Comment by mkeilman** [comment]
Cool - btw it appears that is all of the color maps that sirepo knows about:
```
    var COLOR_MAP = {
        grayscale: ['#333', '#fff'],
        afmhot: colorsFromString('000000...ffffff'),
        coolwarm: colorsFromString('3b4cc0...b40426'),
        jet: colorsFromString('000080...800000'),
        viridis: colorsFromString('440154...fde725'),
    };
```
so I would need to know where to look to expand the list. I presume @moellep is the man.

viridis is set as the default - in addition, elegant currently uses afmhot, srw uses grayscale, and warpvnd uses coolwarm.

**Comment by mrakitin** [comment]
I like the both options! Probably we could have it in two places - per report and per simulation with the priority of per simulation. When any of the report on the page have a changed color map, the per-simulation menu could appear as `Custom` with no background color.
