### ISSUE TITLE
Upload python, prompt for mirror files

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#71]
If an uploaded python file refers to separate datafiles, prompt the user to upload and then post all data to server.

**Comment by mrakitin** [comment]
Should be synchronized with the implementation of #243.

**Comment by robnagler** [comment]
I think we'll end up dropping the simple json import/export. Rather, people will import/export zip files.

**Comment by mrakitin** [comment]
Let's try and see. Anyway, it's better to keep the code for Python importing. Sometimes simple files may need to be imported without any additional files. In this case zipping of a single file may be a redundant procedure.
