### ISSUE TITLE
add link to issues page in Sirepo/UI

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#711]
I'm frequently asked where people should provide feedback on Sirepo apps.
I encourage them to use the issues feature for this repository.

The Sirepo UI should include an obvious image/link for user feedback, which when clicked will bring them to this issues area in a new browser tab.

**Comment by mkeilman** [comment]
Should this be available always, or only when logged in to GitHub?

**Comment by bruhwiler** [comment]
It should always be available.

**Comment by moellep** [comment]
This looks good. One change I'd like to see is to hide the "github login" notification so it doesn't show up on the first visit along with the welcome notification. 

![screen shot 2018-01-02 at 10 31 32 am](https://user-images.githubusercontent.com/6516910/34493263-4eca7b6c-efa8-11e7-9bb3-33e515b9ec88.png)

If possible, the "github login" notification should get initially delayed, so it shows up hours or a day after the welcome notification. That way new user don't get overwhelmed with notifications.

On the coding side, we should use camelCase for javascript and underscores for python. Also, we don't need variable prefixes within the modules, so this:
```
var sr_get_started_notify_cookie = 'net.sirepo.get_started_notify';
```
would become this:
```
var getStartedNotifyCookie = 'net.sirepo.get_started_notify';
```
or better yet, don't use a variable if the value is only used in one place, so this could get moved from:
```
    notificationService.addNotification({
        name: sr_get_started_notify_cookie,
        ...
```
to:
```
    notificationService.addNotification({
        name: 'net.sirepo.get_started_notify',
        ...
   });
```

We only need the "sr_" prefix for anything which might be in a global namespace, like CSS tags.
