### ISSUE TITLE
/auth-email-authorized/<simulation_type> got unexpected kwarg

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#7111]
When we can't parse the url we default to api_notFound. api_notFound takes no args/kwargs but we call it with whatever args/kwargs were going to be used for the route we tried to call.

**Comment by e-carlin** [comment]
This brings up a larger question of how we want to handle malformed urls. This specific case is easy to fix so we don't get a stack trace in the logs and the user is taken to the 404 page. But, if instead they go to /auth-email-authorized//foo then they will get a server error. We [assert sim type]https://github.com/radiasoft/sirepo/blob/e6555962dae411dec0c288bab27e1da50ed0ae04/sirepo/http_request.py#L53). Maybe that sim type check should be converted to 404 instead of 500 (AssertionError). That url they'd have to craft specifically whereas /auth-email-authorized/ without the sim type or token is an easy copy/paste error. So, maybe it doesn't matter. I have to imagine there are other places where we raise AssertionError and return 500 when 404 probably makes more sense.

**Comment by robnagler** [comment]
We should define some exceptions in sirepo.util that get converted appropriately. The exceptions can take any arguments and they'll get cascaded to where they are handled. We can't just raise 404.
