### ISSUE TITLE
NERSC-specific fields missing from UI

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#7115]
In SRW when you select nersc for the execution mode, the additional fields are not being displayed (hours, cores, processes per node, queue, project).

Also in the openmc app, that apps has different fields, which also aren't displayed (hours, node, queue, project).
![x](https://github.com/radiasoft/sirepo/assets/6516910/ddc9fdb3-6d1d-477a-8847-e588634f5905)

**Comment by robnagler** [comment]
@e-carlin do you know what happened? I don't remember touching that part of the code.

**Comment by e-carlin** [comment]
Not sure but I'll figure it out.
