### ISSUE TITLE
elegant to madx  illegal expression

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#7132]
An element with an expression that includes minus a negative number in elegant is valid:
`PTBL10E: LSCDRIFT,LSC=1,BINS=1024, L="0.33543 -1.045700e-01 -"`
But the corresponding conversion to MAD-X:
`PTBL10E: DRIFT,l:=0.33543 - -1.045700e-01;`
Raises an error:
```

  ++++++++++++++++++++++++++++++++++++++++++++
  +     MAD-X 5.08.01  (64 bit, Linux)       +
  + Support: mad@cern.ch, http://cern.ch/mad +
  + Release   date: 2022.02.25               +
  + Execution date: 2024.06.19 15:01:35      +
  ++++++++++++++++++++++++++++++++++++++++++++
PTBL10E: DRIFT,l:=0.33543 - -1.045700e-01;
+=+=+= fatal: illegal format near: l
```

**Comment by moellep** [comment]
This will be fixed with 4493c10
MAD-X can't parse the double negative, but it can parse this:
0.33543 - (-1.045700e-01)
