### ISSUE TITLE
elegant: improve source page to include non-gaussian definition

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#716]
The elegant source page does not cover all the options in the bunched_beam command. The fields can be edited from the Control tab, but it would be nice to allow selecting and configuring non-gaussian beams from the source UI as well.

**Comment by robnagler** [comment]
To be clear, we should be able to set all these parameters (Pages 1-4) from the Source page when you click on the pencil from the bunch?

<img width="926" alt="bunch screen" src="https://cloud.githubusercontent.com/assets/5495179/26125721/5ef3ad42-3a40-11e7-9d6a-8ea89f53197e.png">

**Comment by moellep** [comment]
I don't think we want every parameter. But it would be nice to define a
uniform distribution beam, or to control the distribution of one axis. It
would be nice if the fields were displayed in a nice manner - for example,
rather than fields for  distribution_type "gaussian,gaussian,hard-edge"
with a distribution_cutoff "1,2,3", split them into a grid with x,y,z
columns (6 fields instead of 2).

See the bunched_beam description in the manual:
www.aps.anl.gov/asd/oag/manuals/elegant_latest/elegant.pdf

Also look at the bunched beam examples in the elegantExamples.tar.gz file.

**Comment by moellep** [comment]
@mkeilman 
One improvement needed for #716 is to separate out some of the elegant
beam fields. For example, elegant specifies the X/Y/Z distributions in
one comma-separated field. So instead of typing in "gaussian,
gaussian, uniform-ellipse", it should be displayed inline as three
drop-down elements, each with an enum value ("gaussian", "hard-edge",
"uniform-ellipse", ...).

A similar change was made to the InputFileXY field type - elegant
expects the value as a string in the format "<filename>=<x>+<y>", so
the schema separates it into three fields, for example "waveform",
"waveformX" and "waveformY".

Below is the elegant bunched_beam page and you can see several
combined fields such as "Distribution Cuttoff" and Centroid.

<img width="934" alt="screen shot 2017-08-14 at 9 16 05 am" src="https://user-images.githubusercontent.com/6516910/29289235-e525830a-80f8-11e7-9ecc-2253475bd6e2.png">

**Comment by moellep** [comment]
The new Bunch layout now allows setting many new parameters, including the x/y/z distributions, halton sequences and beam position. Below are some examples.

![screen shot 2017-09-07 at 5 09 01 pm](https://user-images.githubusercontent.com/6516910/30189141-751610ca-93ef-11e7-964e-f00ad7e6eb81.png)
![screen shot 2017-09-07 at 5 09 48 pm](https://user-images.githubusercontent.com/6516910/30189142-77ce0c96-93ef-11e7-9230-da554ab01503.png)
![screen shot 2017-09-07 at 5 09 09 pm](https://user-images.githubusercontent.com/6516910/30189145-7a1f8920-93ef-11e7-87d1-3c27ea121508.png)

**Comment by bruhwiler** [comment]
@sdwebb  and @cchall --  do you think meets the needs of your TESSA collaborators?

**Comment by moellep** [comment]
This is also available now on alpha.sirepo.com

**Comment by cchall** [comment]
That looks like just what we need. Thanks!
