### ISSUE TITLE
elegant: parameter view

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#718]
Elegant SDDS files have parameter and column data. It would be nice if the report page could display a tabular list of parameter name/value pairs.

**Comment by robnagler** [comment]
I need some input on how this will be used. #720 implies we are going to have multiple SDDS files per report. I was thinking of doing is having a parameters report that allows you to select the file to view the parameters. Unfortunately, the parameters vary (e.g. Kick and Angle) with each SDDS page so I'm thinking having a report of the form:

```
Parameters
Output: [run_setup.output.sdds]
Page: [1]

[Parameters show up here]
```

I am adding the parameters to outputInfo.

**Comment by robnagler** [comment]
Fix https://github.com/radiasoft/sirepo/commit/ed9fb2c2d8723756477f4a20f015f0a8e30fef38
