### ISSUE TITLE
add source code for https://beta.sirepo.com home page to the repo

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#721]
I would like to be able to edit the content for the beta server home page
  https://beta.sirepo.com

I suggest the source should be added to the repository.

Thanks,
David

**Comment by bruhwiler** [comment]
It doesn't seem that search engines are finding the content for this page. 

Perhaps the page is being rendered in a way that prevents search engines from finding the content?

**Comment by robnagler** [comment]
We don't want search engines finding the beta server.

You can edit the content in ~/src/radiasoft/sirepo/sirepo/package_data/static/html/landing-page-about.html

**Comment by bruhwiler** [comment]
I made significant changes to the HTML:
a) adding Shadow and Hellweg
b) changing the presentation of all the codes
c) added references

I tested all the links.
I didn't test the result in context.
