### ISSUE TITLE
Show better hint on NERSC login failure

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#7210]
When logging into NERSC, show a better error message if login fails:
  - login credentials incorrect
  - one-time-password value incorrect

Existing NERSC login forms may be an example for this - it may validate the credentials before the OTP is entered.

**Comment by robnagler** [comment]
There login is over ssh. The password+TOTP is entered together and there is a single response. We do not get information about invalid users either. This is normal protocol for computer logins.
