### ISSUE TITLE
Seamless transfer of SRW simulations from Sirepo to Jupiter

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#723]
Need an elegant way to transfer SRW simulations in Sirepo to Jupyter server(s).

**Comment by mrakitin** [comment]
That was discussed in today's telecon. We will eventually need a menu item (like the one for "Export as Python script") to transfer the Python code to the specified server (the list of servers could be provided by configuration of the server or by a user). Related to #648.

**Comment by robnagler** [comment]
Covered by #648
