### ISSUE TITLE
Need to support running packages without __version__

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#7238]
Sirepo expects there to be a __version__ on all configured sim types

https://github.com/radiasoft/sirepo/blob/59b71d01fd413e3e0bfb2db5776b4d83e81112f3/sirepo/simulation_db.py#L965

We are trying to run a sim type configured with package path that isn't installed. It is added via $PYTHONPATH.

I'm going to hack in a __version__ to the package for now but I think this should be fixed in sirepo.

**Comment by robnagler** [comment]
Version should be set dynamically if the package is pip installed (even pip install -e .)

**Comment by e-carlin** [comment]
Yes. But this package is not installed per se. It is set on $PYTHONPATH so version isn't set.

**Comment by robnagler** [comment]
It should be built at least. The building will create the meta data, which is needed for the version: `python -m build`

**Comment by e-carlin** [comment]
```
$ docker run --rm -it --user=6672 radiasoft/sirepo:alpha bash
bash-5.2$ python -m build
python -m build
/home/vagrant/.pyenv/versions/py3/bin/python: No module named build
```

This can be worked around by setting up the env enough for the user where we can pip install build and then build the project. Is this worth it? What else does build accomplish? 

One question is how we handle deps since we aren't installing? For example, if sirepo deps change we will be broken until a new alpha happens.

**Comment by robnagler** [comment]
The environment may not be set up right. Try source /home/vagrant/.bashrc and see what happens. This should be in the entry point though.

**Comment by e-carlin** [comment]
```
$ docker run --rm -it --user=6672 radiasoft/sirepo:alpha bash
bash-5.2$ source /home/vagrant/.bashrc
source /home/vagrant/.bashrc
bash-5.2$ python -m build
python -m build
/home/vagrant/.pyenv/versions/py3/bin/python: No module named build
```

**Comment by robnagler** [comment]
The problem is that build is missing from pyproject.toml in pykern. You can add this:

```toml
dependencies = [
    "build>=1.2",
```

I'll be adding this to my pr which I hope to get out today. It's up to you whether you want a separate pr.

**Comment by robnagler** [comment]
`pip install` installs the build dependencies from the pyproject.toml. However `python -m build` expects the dependencies to be there. It's kind of weird that it isn't in the basic Python. Maybe we should fix installer pyenv to install build, since it installs/upgrades setuptools (and tox?) and pip.

**Comment by e-carlin** [comment]
👍 I can wait. I'm working around it by just manually setting a __version__ for now.
