### ISSUE TITLE
Hellweg: Confusing error message regarding 'power' and 'cell' arrangement in beamline.

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#724]
Hellweg requires a 'power' element be placed prior to a 'cell' element when designing a beamline. Failure to do so produces the following error message in the visualization tab:

<img width="688" alt="hellweg_simulation-status" src="https://cloud.githubusercontent.com/assets/11053323/25027159/f2974a9c-2067-11e7-8c20-0af88d66c807.png">

This message could be more instructive for new users. Here's a simple suggestion: 

> A POWER element specifying input RF power must be defined prior to one or more CELL elements. Note that DRIFT elements terminate the defined RF power.

**Comment by robnagler** [comment]
No longer supported.
