### ISSUE TITLE
How to upload field maps to SRW?

### ISSUE THREAD

**Issue by benshep** [radiasoft/sirepo#728]
So I wanted to simulate the radiation output of an undulator using SRW. I've looked at the example code and downloaded the zip files with the magnetic field data. I tried to copy the format and upload my own [zip file](https://1drv.ms/u/s!Alk3I6oCxLRzg1q1wG2lSbjabhvc), but it doesn't seem to work. I get `Simulation Error: error exit(1)` in the "Spectral Flux" box and `list index out of range` in the others. How should I diagnose this error, and is there some documentation somewhere regarding field map formats? Thanks.

**Comment by robnagler** [comment]
There's no documentation on magnet file. [srwl_uti_read_mag_fld_3d](https://github.com/radiasoft/SRW-light/blob/d72e87b49d153a0dff9633460442bc7c4b6c11e2/env/work/srw_python/srwlib.py#L3891) describes the format briefly. The problem seems to be that the dat file is only one dimension, but the code is expecting three dimensions (columns).

FTR, the stack trace is:

```txt
  File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/srwl_bl.py", line 398, in set_und_tab
    curFldCnt = srwl_uti_read_mag_fld_3d(curFilePath, '#')
  File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/srwlib.py", line 3911, in srwl_uti_read_mag_fld_3d
    locArBy[i] = float(curLineParts[1])
IndexError: list index out of range
```

Thanks for using Sirepo. :)

**Comment by mrakitin** [comment]
You should have one `*_sum.txt` file in the archive which should look like:
```
6.2	p1	0	ivu21_srx_g6_2c.dat	1	1
6.8	p1	0	ivu21_srx_g6_8c.dat	1	1
7.0	p1	0	ivu21_srx_g7_0c.dat	1	1
7.2	p1	0	ivu21_srx_g7_2c.dat	1	1
8.0	p1	0	ivu21_srx_g8_0c.dat	1	1
8.5	p1	0	ivu21_srx_g8_5c.dat	1	1
9.0	p1	0	ivu21_srx_g9_0c.dat	1	1
9.5	p1	0	ivu21_srx_g9_5c.dat	1	1
10.0	p1	0	ivu21_srx_g10_0c.dat	1	1
11.0	p1	0	ivu21_srx_g11_0c.dat	1	1
13.0	p1	0	ivu21_srx_g13_0c.dat	1	1
14.0	p1	0	ivu21_srx_g14_0c.dat	1	1
15.0	p1	0	ivu21_srx_g15_0c.dat	1	1
20.0	p1	0	ivu21_srx_g20_0c.dat	1	1
25.0	p1	0	ivu21_srx_g25_0c.dat	1	1
30.0	p1	0	ivu21_srx_g30_0c.dat	1	1
35.0	p1	0	ivu21_srx_g35_0c.dat	1	1
40.0	p1	0	ivu21_srx_g40_0c.dat	1	1
```

The `*.dat` files should have a header and three columns of the X, Y and Z components of magnetic field, as @robnagler correctly mentioned:
```
#Bx [T], By [T], Bz [T] on 3D mesh: inmost loop vs X (horizontal transverse position), outmost loop vs Z (longitudinal position)
#0.0 #initial X position [m]
#0.0 #step of X [m]
#1 #number of points vs X
#0.0 #initial Y position [m]
#0.0 #step of Y [m]
#1 #number of points vs Y
#-1.25 #initial Z position [m]
#0.0006475006475006475 #step of Z [m]
#3862 #number of points vs Z
7.19073449022543e-08	-2.563648e-05	-7.79696877412529e-06
6.55982698185373e-05	-8.833768e-06	1.25090022710467e-05
4.83020836050239e-05	-3.922893e-05	-9.55702344267519e-06
6.26994341136484e-06	4.72979e-05	3.45571238985515e-05
-9.84714312155239e-05	-2.601114e-07	4.64440428545425e-05
-4.11255346058045e-06	-4.781813e-05	-3.20987065496642e-07
6.60247906750584e-05	-4.996608e-05	3.15234923070893e-05
.....................................
```

You may want to check [an example zip-archive](https://github.com/radiasoft/sirepo/blob/master/sirepo/package_data/template/srw/magnetic_measurements.zip?raw=true).

**Comment by mrakitin** [comment]
@benshep, I also noticed that your `scu_sum.txt` file contains only one row:
```
7.4	p1	0	scu_g7_4c.dat	1	1
```

With the current implementation of SRW it may fail, so it's better to have 2 identical rows. Otherwise the interpolation of the undulator gap won't work. It should be improved in the upcoming release of SRW.

**Comment by robnagler** [comment]
Sorry for the hassles, Ben. We greatly appreciate you reporting the errors.

We don't dump stack traces for security reasons. We need to put in a feature to trim them securely.

There is no delete or rename, sorry (see #552).

@mrakitin Here's an error in LP3SxRF1/fluxAnimation/mpi_run.out:

```
Warning: Computation of terminating terms of radiation integrals WAS NOT PERFORMED for some values of input parameters ^M because asymptotic expansion validity criterion was not satisfied. This may influence the accuracy of the computation. 
 One can try to fix the problem by modifying Magnetic Field definition range and/or Integration limits.
```

**Comment by benshep** [comment]
That's OK! I didn't know if I'd have to go through the hassle of installing SRW or some other code to do my (fairly simple) synchrotron radiation calculation, so it's really nice to have the option of doing it online. 

Sounds like I maybe need to extend the range of the field map?

**Comment by mrakitin** [comment]
@benshep, can you please share the new zip-archive so I could debug the issue? Thanks.

**Comment by benshep** [comment]
Yep, here you go: https://1drv.ms/u/s!Alk3I6oCxLRzg1sJTlhQUp29mnKm

**Comment by mrakitin** [comment]
I think I figured out what was going wrong. The two identical lines are the reason - you have to change the gap value for the second line to something different, e.g.:
```
7.4	p1	0	scu_g7_4c.dat	1	1
7.5	p1	0	scu_g7_4c.dat	1	1
```
SRW cannot interpolate the values of the gap if two equal gaps are provided, that's why it complained. With the different lines I got pretty reports:

![fireshot screen capture 001 - tabulated undulator example - srw - radiasoft - localhost_8000_srw _source_lnewrnat](https://cloud.githubusercontent.com/assets/13209176/25407069/f1031576-29d6-11e7-89b3-2c0d607e791d.png)

Updated zip-archive is attached here - [2017-04-24_KG_By_Field_on_axis-4.zip](https://github.com/radiasoft/sirepo/files/956508/2017-04-24_KG_By_Field_on_axis-4.zip) I hope this solved the problem.

**Comment by benshep** [comment]
Yes! Thanks very much. I should have thought of that really...

**Comment by mrakitin** [comment]
@benshep, I'm glad it worked for you. In the upcoming release of SRW we will include processing of a single `.dat` file with the magnetic measurements.

**Comment by mrakitin** [comment]
I assume this issue is solved. Closing.
