### ISSUE TITLE
SRW - make the name of the Flux reports dynamically changing

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#731]
The name of the Flux & animated Flux reports should dynamically change depending on the option of `Entity to Calculate` (`Flux` or `Flux per Unit Surface`).

**Comment by mrakitin** [comment]
Fixed in 626f9e0.

@moellep, do you mind to release it on alpha (alone with the fix for #730) once the build https://travis-ci.org/radiasoft/sirepo/builds/228421508 is finished?

**Comment by moellep** [comment]
I bumped the version number in schema-common.json and will do an alpha
release after that builds. The schema number needs to get incremented if a
javascript file changes or the browser may hold onto a cached copy.

**Comment by mrakitin** [comment]
Thanks for the reminder! I completely forgot about the schema version number. Maybe in the test.sh we can have some kind of check if the version was incremented if any `*.html` or `*.js` files were changed?

**Comment by robnagler** [comment]
We could probably always bump the version. We don't release that often. Eventually, we could optimize for changes, but then, if we are that successful (frequent releases) likely we'll need to bump the version frequently. :)
