### ISSUE TITLE
SRW - fontawesome spinner for waiting/simulating lations

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#732]
http://fontawesome.io/examples/ provides a number of interesting spinners, so it may look better than the current `glyphicon-hourglass` icon. @moellep, @robnagler, do we want to integrate it with Sirepo? I've implemented an initial version of it in 9377d89eb5f95366eb4466d2603908ffa757d8bb.

Useful links:
- http://chadkuehn.com/animated-font-spinners/
- http://jsfiddle.net/chadkuehn/1twpzLz8/

**Comment by mrakitin** [comment]
Any comments on the feature?

**Comment by moellep** [comment]
I think it is fine to add fontawesome - it has a better selection of icons
than glyphicons. It looks like bootstrap v4 drops glyphicons so we could
migrate all the icons to fontawesome to prepare.
