### ISSUE TITLE
Abort/stop/cancel report

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#74]
Allow any report to be aborted, killing the process and displaying an "aborted" message on the plot.

**Comment by mrakitin** [comment]
We had a conversation with Oleg about that again, and I'm increasing the priority to not forget about the request.

**Comment by bruhwiler** [comment]
Is this issue still relevant?
@robnagler  --  would it be difficult to implement?

**Comment by robnagler** [comment]
I think we have this mostly implemented. When you close the window, I think it kills the job. @moellep ?

**Comment by moellep** [comment]
Yes, leaving the page will cancel the short-running jobs. Or if a running report is minimized, it cancels the job and moves to the next one.
