### ISSUE TITLE
fete: field plots at a selected position

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#740]
Provide a way for the user to select a position and view the electric field components. Use Chris' notebook below for examples:

https://github.com/radiasoft/rswarp/blob/master/examples/Warp_Field_Comparison.ipynb

**Comment by ncook882** [comment]
Chris will write a Python script for extracting and plotting field lineout data given a single x/y coordinate. This will be used in conjunction with a drag/drop "ruler-type" line overlay on the conductor grid in the source panel. The lines will span the entire domain.

**Comment by cchall** [comment]
The example [notebook](https://github.com/radiasoft/rswarp/blob/master/examples/Warp_Field_Comparison.ipynb) has been updated with a new function for calculating array index given x/y coordinate data.

The notebook has also had a plotting widget added for interactive field plots along selected lines. See https://github.com/radiasoft/rswarp/commit/a8d1fdc5c2c657771eb0bf93938f0f03305c2514.

**Comment by moellep** [comment]
The Conductor Grid now has three ruler-type selectors on the x and z axis. Dragging the ruler location automatically updates the new Field Comparison Report. The Field Comparison Report also allows updating the thee positions on the "advanced" dialog.

![screen shot 2017-12-01 at 10 05 53 am](https://user-images.githubusercontent.com/6516910/33494710-66a83822-d681-11e7-948d-ea3cad31679d.png)
![screen shot 2017-12-01 at 10 06 02 am](https://user-images.githubusercontent.com/6516910/33494715-68a41812-d681-11e7-9d64-d165e0faee1f.png)

**Comment by bruhwiler** [comment]
Cool :)
