### ISSUE TITLE
job_cancel_test is timing sensitive, because agent_start_delay no longer works

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#7400]
The test sets `d.models.dog.favoriteTreat = "agent_start_delay=5"`, but beginSession is the first op so the agent starts without any data and the [job_driver](https://github.com/radiasoft/sirepo/blob/5e611a76a2f3701bdf2f7de9d27399ca4b06cceb/sirepo/job_driver/__init__.py#L345) doesn't delay start. 

@e-carlin do you remember why we had this specific of a test?

**Comment by e-carlin** [comment]
To test that we properly handled the case where an agent took too long to call back in. We wanted to test the `job_driver._websocket_ready_timeout_handler` path.

**Comment by robnagler** [comment]
This is going to be very hard to test now with beginSession. Maybe a new kind of flag could be passed. I noticed the change only because runSimulation actually sends the msg and waits for a "quick" reply. This should be inconsequential, but the test had a sleep of 1. Changing it to 2 works. 

I'll leave this open.

**Comment by robnagler** [comment]
Fix with #6914
