### ISSUE TITLE
Improve quality of server error page

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#743]
See #742 for when you might get a server error. It can't stay "in app", but it can render a prettier page than the default Flask server error. On production, it'll show "bad gateway". Probably need to catch all exceptions and render a custom server error page. On the proxy, we should add a special page for when the server is unreachable.

**Comment by mrakitin** [comment]
The first part can be easily done like [here](https://github.com/mrakitin/web/blob/master/server.py#L182), with a simple 404 page template:
```jinja
{% extends 'layout.html' %}
{% block content %}
<div class="centered">
    <h1>Page Not Found</h1>
    <p>What you were looking for is just not there</p>
    <p><a href="{{ url_for('index') }}">Go to home page</a></p>
</div>
{% endblock %}
```
resulting in the following:
![image](https://cloud.githubusercontent.com/assets/13209176/26136444/1599a92c-3a8a-11e7-91a8-896accb5f420.png)
