### ISSUE TITLE
SRW - close/disable buttons don't work in Firefox/Chrome (work in IE/Edge)

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#752]
In Chrome and Firefox in expert mode the close/disable buttons are not available. A sample simulation is https://alpha.sirepo.com/srw#/beamline/eopXmBJd.

**Comment by moellep** [comment]
I wasn't able to reproduce this with my computers, but I think the problem
is the call to isTouchscreen() in sirepo-beamline.js. Is the computer you
are using a mouse and tablet combo? Maksim, if you have computer to
reproduce the problem, could you try using a version of modernizr with
pointerevents also included:

https://modernizr.com/download?pointerevents-touchevents-setclasses

Then replace the "return Modernizr.touch" with "return !
Modernizr.pointerevents".

**Comment by mrakitin** [comment]
Hi Paul, good catch! Yes, the laptops we tried to use with Sirepo both have touch screens. I tried the suggested Modernizr version, but it still does not work with `return ! Modernizr.pointerevents`, but works with the opposite `return Modernizr.pointerevents`. When I leave the same condition (`return Modernizr.touch`), it works fine, but I could not test it on non-touch device.

**Comment by mrakitin** [comment]
OK, I tried to disable the touch screen, and then used the existing modernizr library, but with the new `return Modernizr.pointerevents` condition, and it worked in both cases - with the touch screen enabled and disabled.

**Comment by mrakitin** [comment]
@moellep, please review the proposed fix bd8c0ba, to make sure it does not conflict with the purpose of the `isTouchscreen` function. Thanks.

**Comment by moellep** [comment]
No - that doesn't work in my testing with an iPad. Unless the modernizr is
built with pointerevents, it always returns undefined. I think this is a
tricky problem - we want tablets to have a UI without depending on hover
for the disable and delete icons, but now PCs have both a touch-screen and
a mouse, we need a test to determine if there is a mouse available.

**Comment by mrakitin** [comment]
Interesting. Let's discuss it during tomorrow's meeting. Am I right that the original idea was to hide those control buttons on mobile devices?

**Comment by mrakitin** [comment]
Thanks for the fix @moellep, it works on my system.
