### ISSUE TITLE
underscore-min.map install

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#754]
Need to add underscore map to avoid error and make debugging easier.

```
https://beta.sirepo.com/static/js/ext/underscore-min.mapFailed to load resource: the server responded with a status of 404 (NOT FOUND)
```

**Comment by moellep** [comment]
This should be added, but first check if the underscore methods used have an equivalent method in jquery. If that is the case, we can replace it and remove underscore from the imports.

**Comment by mkeilman** [comment]
I see only one underscore function that does not have a counterpart in either angular or jquery: `_.isEmpty()` when checking errors in `sendRequest()` .  Seems like we can ditch underscore then?

**Comment by moellep** [comment]
Yes, I don't think underscore gives us enough to justify including it.
