### ISSUE TITLE
purge users on alpha?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#756]
I'd like to do an alpha release with the current code to purge unregistered users older than 180 days.  See [admin.purge_users](https://github.com/radiasoft/sirepo/commit/cc4ec0c9cc03ae21a410f364ccbc6d5df9632bbb#diff-05907a97c178a66d79820a99beb80abeR10) for how it will work.

#744 will require a renaming of directories (no easy way around this) so I'd like to limit the time of the update by renaming only those directories of reasonably active users.

If it's ok, I'll update alpha and then run the purge.

**Comment by bruhwiler** [comment]
I agree with the plan.

David

**Comment by mrakitin** [comment]
Sounds good to me.

**Comment by moellep** [comment]
I don't understand the line below - why is it looping on to_remove?

if not dry_run:
    for d in to_remove:
        pkio.unchecked_remove(*to_remove)

**Comment by robnagler** [comment]
Old code after I figured out unchecked_remove takes a list. :)

Fixed in edd8309.

Go ahead with the push?

**Comment by moellep** [comment]
Yes, looks good to push to alpha.

**Comment by mrakitin** [comment]
How to execute the code? Will it run automatically on server restart?

**Comment by robnagler** [comment]
You run it inside the container with "exec".  We have a command called: service sirepo exec_bash which sets up the environment. You should have that command with the Debian install.

There's a flag called "--confirm", which is required. There's also "--days=N" where N is a positive integer.

I'd recommend this:

```sh
service sirepo exec_bash
sirepo admin purge_users >& /vagrant/purge_users.out
echo 'select * from user_t;' | sqlite3 /var/db/sirepo/user.db > /vagrant/users.out
```

Then spot check the file. If any directories are younger than 180 days (default for --days), stop. If any the user IDs are in users.out, stop. If all is ok, then:

```sh
sirepo admin purge_users --confirm >& /vagrant/purge_users.out
```

I'd like to set this up as a regular cron entry so that the db doesn't get to big, but first I want to make sure it works manually. 

Please make sure your backups are working before you run this command. If your /var/db/sirepo directory is small, you might want to do this before running any commands:

```sh
tar czf /var/tmp/sirepo.tgz /var/db/sirepo
```

**Comment by robnagler** [comment]
Wait for me to run it though. I'll let you know when the alpha goes ok.

**Comment by mrakitin** [comment]
OK, thanks for the detailed explanation, Rob! I'll wait for your results.

**Comment by robnagler** [comment]
Some sanity checks you can run:

```
for f in $(cat users.out | colrm 9); do grep $f purge_users.out; done
for f in $(cat purge_users.out); do find $f -mtime -179 -type f; done
```

There should be no output from these commands.

**Comment by robnagler** [comment]
Alpha went from 59G to 27G. 1631 users were deleted. 87 users left. 

@mrakitin if you want help doing the upgrade, let me know.

**Comment by mrakitin** [comment]
Cool, I cleaned our server - the size of the directory reduced from 30G to 12G.

**Comment by robnagler** [comment]
Definitely want to setup a cron, but I need to code it to attach to the container.
