### ISSUE TITLE
Show selected characteristic in report title

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#76]
Show the selected characteristic on report title.

**Comment by mrakitin** [comment]
It's relatively easy to implement.

**Comment by moellep** [comment]
A mock-up example, is below - the Intensity Report on the source page with "Re(E): Real part of Single-Electron Electric Field" selected. Showing that extra info in the report, either in the title or below the title would be helpful. Similarly, on the Single-Electron Spectrum Report, the Polarization component should be displayed on the report.

![screen shot 2018-01-18 at 10 12 42 am](https://user-images.githubusercontent.com/6516910/35111765-41cb24fa-fc39-11e7-981b-1cbd571973ff.png)

**Comment by moellep** [comment]
The subtitles look good. We also want the characteristic to show up on the Beamline intensity reports. 
I think the subtitle assignment code should get moved out of the client (srw.js) and added as a parameter the server provides (template/srw.py), similar to the way the server is providing the title of the report. A new parameter "subtitle" could be added, and if present the plot could set during plot init(), rather than requiring each app controller to manage updateSubtitle().
