### ISSUE TITLE
SRW - download an image of beamline layout

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#763]
A beamline layout is frequently needed to be saved as an image to include to presentations/posters/publications/reports. I would be great if the picture could be saved the same way as a report can be downloaded as a picture of different resolutions, instead of taking a screenshot and cutting it.

**Comment by mrakitin** [comment]
As an advancement, the beamline layout can be represented in a 3D-like style keeping the scaling of the beamline, but it's rather a separate project. The two ideas are from Oleg.

Probably SVG or WebGL can be used for visualization.

**Comment by mrakitin** [comment]
During preparation for SPIE it appeared to be extremely necessary. It can be done by html2canvas library, as suggested in https://stackoverflow.com/a/18312898/4143531.

As a manual solution, I do it by the following command in the Firefox Developer Toolbar (<kbd>Shift</kbd>+<kbd>F2</kbd>):
```
screenshot --selector .srw-beamline-container
```

**Comment by robnagler** [comment]
We have a [PNG capturing solution](https://github.com/radiasoft/sirepo/blob/4b7a227cfa5fb222f1b5f857fe818aba40a4d5ba/sirepo/package_data/static/js/sirepo-components.js#L1155). Just need to apply it to the beamline element. It isn't much work.

**Comment by mrakitin** [comment]
Great!

**Comment by moellep** [comment]
There is some work involved because the beamline is html with some svg
elements contained in divs. One solution would be to add a (hidden) report
which renders the beamline in svg, including the position markers and then
use plotToPNG directive to download the image.

**Comment by mrakitin** [comment]
@bruhwiler, this ticket is a part of request from SLAC colleagues we discussed today.

**Comment by mrakitin** [comment]
A workaround can be Firefox screenshot functionality.
