### ISSUE TITLE
SRW - show optical element type in the list of parameters

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#764]
Need to display the element type in the parameters of optical elements on the beamline page. Otherwise, the pictograms can be confusing sometimes.

**Comment by moellep** [comment]
@mrakitin Would adding a title to the parameter list solve this? Something like this:

![beamline](https://user-images.githubusercontent.com/6516910/29847390-b48b3294-8cd8-11e7-8ef1-ba1b70224936.png)

**Comment by mrakitin** [comment]
Yes, that's perfect!
