### ISSUE TITLE
Slider on Windows 10

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#77]
The plot slider is broken on some Windows 10 browsers. Reimplement with a proper angular widget.

**Comment by mrakitin** [comment]
It looks to be a duplicate of https://github.com/radiasoft/sirepo/issues/59.

**Comment by mrakitin** [comment]
It works now in both Firefox and Chrome browsers on Windows 10.

**Comment by mrakitin** [comment]
Closing as a duplicate.
