### ISSUE TITLE
Update beta landing page to reflect Warp tools for vacuum nanoelectronic devices

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#770]
In conjunction with #769, the Sirepo beta landing page should be updated with a link to the new Warp capabilities developed for the FETE project, along with a corresponding description and funding acknowledgement. @ncook882 will provide the text.

**Comment by ncook882** [comment]
Draft text included below.

New subsection: **Vacuum Nanoelectronic Devices**

New link: **Warp-VND**

Warp is a particle-in-cell code designed to simulate high intensity charged particle beams and plasmas using state-of-the-art electrostatic and electromagnetic solvers. Warp's electrostatic capabilities include advanced treatments of conducting and dielectric structures. Sirepo leverages these electrostatic features for the modeling and simulation of thermionic energy converters, devices designed to generate electricity from the thermionic emission of electrons.  The Warp source code is available on [Bitbucket](https://bitbucket.org/berkeleylab/warp/src). The code is developed and supported at Lawrence Berkeley National Laboratory and Lawrence Livermore National Laboratory. Warp is part of the [Berkeley Lab Accelerator Simulation Toolkit](http://blast.lbl.gov/codes/).

D.P. Grote, A. Friedman, J.-L. Vay and I. Haber, "The WARP Code: Modeling High Intensity Ion Beams," in [AIP Conference Proceedings 749, 3 (2005)](http://aip.scitation.org/doi/abs/10.1063/1.1893366).

**Comment by robnagler** [comment]
On alpha
