### ISSUE TITLE
Broken Link for LPA example

### ISSUE THREAD

**Issue by astamm2** [radiasoft/sirepo#773]
In website:  https://beta.sirepo.com/#/about

Example 3, "Laser-Plasma Wakefield" Link address: "https://beta.sirepo.com/find-by-name/warppba/default/WARP%20example%20laser%20simulation"

Issue: The link doesn't lead to an example.

**Comment by bruhwiler** [comment]
Strangely, that URL does work for me.
Something is wrong -- most likely to do with the recent change in the naming of URLs for plasma-based accelerator simulation using Warp.

**Comment by robnagler** [comment]
@astamm2 the examples have been renamed for new users. We'll update this link. Thank you for letting us know.

**Comment by robnagler** [comment]
I'll write an upgrade to rename examples for existing users.

**Comment by robnagler** [comment]
Fixed on Alpha. The Warp laser example has been renamed to Laser-Plasma Wakefield. All examples were updated (not copies). The other example is Electron Beam.

We'll notify here when we push to beta (probably tomorrow).

**Comment by robnagler** [comment]
This is on beta.

**Comment by robnagler** [comment]
Just got another user complaint:

```text
(FYI the "Laser-Plasma Wakefield” link on your site is 404…)
```

**Comment by robnagler** [comment]
I think the db upgrade for the example renames was never run on beta.
