### ISSUE TITLE
elegant: add chirp to bunch definition

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#775]
There should be an additional method for specifying longitudinal properties in the source definition (bunched_beam):

sigma_s
sigma_dp
momentum_chirp (units=1/m)

**Comment by robnagler** [comment]
High priority?

**Comment by cchall** [comment]
Yes, this would be a very nice feature to have available for some of the
TESSA related work I'd like to try doing on Sirepo.

**Comment by moellep** [comment]
This is part of #716 but there is a work-around in the meantime:

On the Control tab, select the edit button next to the bunched_beam command. The sigma_s and sigma_dp values can be edited on page 3 and the momentum_chirp can be edited on page 4.

**Comment by moellep** [comment]
Fixed with d22a8dd
