### ISSUE TITLE
tessa: horizontal axis isn't changing with the data

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/sirepo#786]
The 't' data in this simulation is varying from the average at the sixth decimal place. I'm not sure how to handle this aside from automatically changing to and average +/- the particle data. We can discuss this later.

Attached are examples of this behavior and data. This comes from the LEA_Beamline example. 't' is the fifth column.

[run_setup.output.txt](https://github.com/radiasoft/sirepo/files/1090443/run_setup.output.txt)

<img width="685" alt="final_output" src="https://user-images.githubusercontent.com/7430829/27369315-a8874e06-5614-11e7-8124-54933b90dbc1.png">

**Comment by bruhwiler** [comment]
matplotlib handles this automatically by placing the average value (or min, or max) somewhere near the upper end of the axis and then printing the deviation along the axis. That can be confusing.

I think your suggestion is a good one. The plot could automatically replace the label "t" with something like:
     t - <t>  (<t>=545.36 ns)

**Comment by bruhwiler** [comment]
Github autoformatted my plain text in a confusing way.
I was trying to write:
   `t - <t>  ( <t> = 545.36 ns )`

**Comment by robnagler** [comment]
Just FYI, Google and Excel don't do anything good out of the box:

![google-scatter](https://user-images.githubusercontent.com/5495179/27390282-2383ba24-565e-11e7-9f08-69cf0d041d36.png)

![excel-scatter](https://user-images.githubusercontent.com/5495179/27390291-274c477a-565e-11e7-9a64-b4d8f7edfa64.png)

Personally, I think plots in domain specific cases like this should always be "right". I would like to avoid creating a plot controller that gives you a bunch of buttons and knobs. If people want that, they download into their favorite plotting tool.

David's idea is fine. I didn't see anybody discussing this online, which is interesting.

**Comment by moellep** [comment]
sddsplot solves this in an interesting way - it determines the necessary precision for the labels and then adjusts the font size to squeeze in the labels. Below is an example. The example below also shows the shortcoming - the font gets unreadable when a high precision is needed. I think the (t -&lt;t&gt;) format would be more readable.

![screen shot 2018-02-28 at 9 19 07 am](https://user-images.githubusercontent.com/6516910/36912144-128bfb88-1e03-11e8-980a-9b97790a0796.png)

**Comment by moellep** [comment]
I didn't find an acceptable (p-(p)) solution, but I did fix the problem using a similar layout to sddsplot, but adjusting the margins rather than the font size on large tick marks. Tick marks will now always use the appropriate precision, and zooming in will automatically update the margins. Below is an example, before and after zooming, which needs a lot of precision in the y axis.

![screen shot 2018-03-14 at 11 14 42 am](https://user-images.githubusercontent.com/6516910/37419312-cc4d9f66-2779-11e8-85fb-862a9d44b0ff.png)

**Comment by moellep** [comment]
After a discussion with Stephen, the (p - &lt;p&gt;) format should get enabled when the required precision is high (a rough guess > 4 digits). The "0" value should come from the central tick of the current zoom. Below is a mock-up:

![screen shot 2018-03-14 at 2 42 57 pm](https://user-images.githubusercontent.com/6516910/37429803-04ca2f8c-2796-11e8-8bf1-b0c053547205.png)
