### ISSUE TITLE
SRW - partially coherent and animated flux reports are not exported in zip-archive

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#789]
Partially-coherent and animated flux reports are not exported with a zip-archive and a self-extracting file. It's quite inconvenient since these simulations are the most important (=accurate) from scientific point of view. It would be great to have them exported.

**Comment by robnagler** [comment]
We don't export report data in the archive. What we do export is how those reports are run, i.e. the docker image. Therefore, one should be able to reproduce the reports.

We do have on our plate a larger reproducibility project which is based on our Data Management Plan. The data are stored with [pykern.pkcli.sim](https://github.com/radiasoft/pykern/blob/master/pykern/pkcli/sim.py)

**Comment by mrakitin** [comment]
OK, I see. That would be extremely useful to have the archive with complete set of files, since some simulations can run for a day or so, so there would be no need to recalculate the same stuff.

Also, those simulations are not copied via sharing a link to the simulation. Is it also expected behavior?

**Comment by robnagler** [comment]
That's correct. No reports are copied. Just the library files and sirepo-data.json.

**Comment by mrakitin** [comment]
OK, I see. Closing?

**Comment by robnagler** [comment]
Yes. I think it's better to talk about this in the larger context.
