### ISSUE TITLE
simulation errors with celery

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#79]
It would be nice if the server could report the same error message when running in celery or single-worker mode. Currently, the app shows a "simulation failed" message when the celery task fails, rather than something more descriptive which is shown in single-worker mode, such as "failed to allocation memory for wavefront".

**Comment by robnagler** [comment]
Fixed in 7d74995ebd6f89a35c17faf99284030e35afbda6. celery_tasks.start_simulation now creates a run.log just like server._Background does.
