### ISSUE TITLE
Where should reproduced simulation end up?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#797]
When a user reproduces (copies) a simulation, what folder should it be put into? Right now the simulation gets copied into a folder by the same name as the source simulation. It makes it a bit hard to find the simulation so I would suggest that we either ask the user, tell the user, put it at the top level, or some folder "reproductions".

Thoughts?

**Comment by bruhwiler** [comment]
We already have a simple algorithm for what happens when a user makes a copy of their own simulation. I'm not sure that algorithm is the best choice, but it seems we should be consistent and use a similar approach when copying someone else's simulation.

**Comment by mrakitin** [comment]
I would vote for asking a user where to put the simulation. It's indeed can be hard to find the copied simulation when one has many of them.

**Comment by robnagler** [comment]
No users are complaining so let's drop.
