### ISSUE TITLE
fete: server error on two-poles example

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#798]
When running the WarpVND two-poles example on beta, the following error sometimes occurs:

> "a server error occurred: status = undefined"

**Comment by moellep** [comment]
I looked at the beta logs and it looks like this may be a time-out problem, but it is hard to tell. The simulation run log gets overwritten when you run it again.

The next time it happens, leave that simulation alone and reply to this ticket with the simulation URL. That will let me check the logs. You can copy that simulation to a new one (using "Open as a New Copy" from the simulation list) if you would like to keep working on it while the original is debugged.

**Comment by ncook882** [comment]
I will try to recreate the error, and will follow your instructions when I do so.

It's possible this is another instance of conducting surfaces which do not lie on the mesh being incorrectly approximated by Warp, and resulting in NAN results for the fields.

**Comment by moellep** [comment]
Yes - it could be the NAN issue. I can reproduce that by selecting the Two Poles example and changing the Channel Width from 0.2 to 0.3. I'll improve the error message for this case, rather than "status=undefined".

**Comment by ncook882** [comment]
I'm trying to create a more sophisticated example using conducting plates with negative voltages to redirect particles away from the accelerating gate. See [here](https://alpha.sirepo.com/warpvnd#/source/iu3ewEWU) for the implementation on beta. I get the same server error for the field report, but when I download the Python source I'm able to run it successfully on my laptop. So it may not be the NAN issue...

**Comment by moellep** [comment]
I tried out the same simulation locally. The python source does run, but I don't think output hdf files have valid data. After running the python, I ran this program to check the output:

from rswarp.utilities.file_utils import readparticles
v = readparticles('diags/xzsolver/hdf5/data00000200.h5')
print(v['beam'][:,4])

[             nan              nan              nan ...,   1.24999996e-10
   1.24999996e-10   1.24999996e-10]

**Comment by ncook882** [comment]
I am running into an error as well when looking at the hdf5 particle output. However, I am still able to plot the fields and particle traces. I could not even produce an initial field report on beta. There may be two separate problems at work here? I will look into the output of the files later this afternoon.

**Comment by cchall** [comment]
I ran into this issue with a very simple single conductor setup:
https://beta.sirepo.com/warpvnd#/source/jwp0duEb

When I download the python script and run locally the simulation runs instantly and returns a reasonable looking plot for the potential.

![figure_1](https://user-images.githubusercontent.com/17073688/28380130-698a561a-6c73-11e7-8691-a97669db6fd9.png)

**Comment by moellep** [comment]
When you download the python code from sirepo, it is actually the code to run the reports on the Visualization page. the field report on the source page has a slightly different script (I've attached it for this example). That reports produces Nan values depending on where the conductor is placed.


[bad-field-report.py.txt](https://github.com/radiasoft/sirepo/files/1159946/bad-field-report.py.txt)

**Comment by cchall** [comment]
Looks like the root cause of this issue is the relaxation coefficient (omega) being set here:
```
#Adjusting the multigrid parameter here improves convergence speed
omega = 2./(1. + np.sin(np.pi/min(NUM_X+1,NUM_Z+1)))
solverE.mgparam = omega
```

This calculation for omega appears to not be very robust across different simulation parameters and is causing the solver to fail.
For now it seems like the best course of action is to not set solverE.mgparam in any of the run scripts on Sirepo. This will set the value back to Warp's default, which may be more robust.

**Comment by moellep** [comment]
Yes, removing that part seems to help. I'll check in this change.
