### ISSUE TITLE
improve comments in the downloaded Python script for running SRW

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#8]
The 'virtual beamline' Python scripts include text regarding the sequence of optical elements. 
In the Python source code that can be downloaded from the browser, such text is not provided. 
It is important to include it.

**Comment by bruhwile** [comment]
This is still relevant, and should not be too much work.

**Comment by mrakitin** [comment]
I'll address this issue along with #216.

**Comment by bruhwiler** [comment]
This issue is linked from another one, combining the two, so no need to keep it open.
