### ISSUE TITLE
Explicitly couple documentationUrl by name of example

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#80]
I think we should couple example documentation by name of the example. There should be a single url for the documentation, e.g. https://github.com/radiasoft/sirepo/wiki/{}, and then we would substitute the name of the example, e.g. https://github.com/radiasoft/sirepo/wiki/Diffraction-by-an-aperture-example.

**Comment by robnagler** [comment]
I don't think so. I think it is still a configuration parameter on each
simulation. @moellep?

**Comment by moellep** [comment]
I haven't change this.

Paul

**Comment by mrakitin** [comment]
It seems to be fixed. What about the configuration parameter?

**Comment by robnagler** [comment]
afaict, it is still an absolute path in each sirepo-data.json file
