### ISSUE TITLE
tessa: error messages at run time

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/sirepo#802]
When setting up the tessa example, a large number of errors pop up. Chris says he knows where this is coming from and not to worry about it, but it would be better not to have it appear at all if it isn't actually an error.

[SimulationError.pdf](https://github.com/radiasoft/sirepo/files/1136682/SimulationError.pdf)

**Comment by robnagler** [comment]
Filter messages for unknown parameters.

**Comment by moellep** [comment]
To document the fix: "Unknown parameter" warnings are not shown, and the summary error display box now formats the text correctly and allows scrolling through the messages.

![screen shot 2018-01-09 at 4 24 33 pm](https://user-images.githubusercontent.com/6516910/34748413-9c852ef4-f559-11e7-9ba9-1887acbfa7fc.png)
