### ISSUE TITLE
fete: runtime error exit(1)

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#808]
When running longer simulations with the FETE gui, the simulation may crash, with the following error in the simulation status tab:

> Simulation Error: error exit(1)

See this [simulation](https://alpha.sirepo.com/warpvnd#/visualization/VdT4no0d) which has crashed at frame 85.

**Comment by moellep** [comment]
I've reproduced this with that simulation (terminated at frame 81 for me). The alpha system has a 1 hour timeout on background tasks and the celery error log has a SoftTimeLimitExceeded entry. The same simulation should complete on beta which has faster CPUs and a longer time-out. I think it is good to keep the 1 hour timeout in place on alpha.
