### ISSUE TITLE
Don't allow slash (/) in filename

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#809]
Any other magic file chars shouldn't be allowed.

**Comment by robnagler** [comment]
I did a quick check of names on beta. I don't think there any '/' or other specials like &, :, \, etc. so we can restrict these to avoid unnecessarily complexity in downloaded file names.

**Comment by mkeilman** [comment]
I've been working on this and was wondering: should we keep offending characters from ever appearing in the input field? Also, I presume we need to inform the user of the restrictions somehow.

**Comment by moellep** [comment]
You could add a new field type "FileName" to the fieldEditor directive (in sirepo-components.js) and add a custom validator, similar to the stringToNumber directive used by Float and Integer types. The validator would return undefined if the value has invalid characters such as '/' and that will cause the field to highlight the error. Experiment with the stringToNumber directive to get an idea.

**Comment by mkeilman** [comment]
Good, I have been taking that approach
