### ISSUE TITLE
Add Ideal Crystal optical element

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#81]
Add SRWLOptCryst beamline element. See SRWLIB_Example14.py.

**Comment by mrakitin** [comment]
I started working on this task, I'll commit when it's ready.

**Comment by mrakitin** [comment]
Implemented in 3bb64f08a388227543e01288ad15cdf5df4aa042, merged with master in 81deb7fde6e24a12df9276c3354c7fce3372024c.
