### ISSUE TITLE
Unexpected token N in JSON at position 179

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#811]
When running a multielectron simulation for SRW https://alpha.sirepo.com/srw#/source/fmt9U5eb getting the following error:

```text
sirepo.js:1152 SyntaxError: Unexpected token N in JSON at position 179
    at JSON.parse (<anonymous>)
    at Ic (angular-1.6.1.min.js:16)
    at jc (angular-1.6.1.min.js:95)
    at angular-1.6.1.min.js:96
    at q (angular-1.6.1.min.js:7)
    at rd (angular-1.6.1.min.js:96)
    at f (angular-1.6.1.min.js:98)
    at angular-1.6.1.min.js:133
    at m.$eval (angular-1.6.1.min.js:147)
    at m.$digest (angular-1.6.1.min.js:144)
```

**Comment by robnagler** [comment]
@mrakitin Could you look at this simulation? It is getting NaNs in the output.

It's the NSLS-II ESM beamline (tabulated undulator) example run in partially coherent mode. I attached the run directory. It happens on beta, too.

[multiElectronAnimation.zip](https://github.com/radiasoft/sirepo/files/1159787/multiElectronAnimation.zip)

**Comment by mrakitin** [comment]
I was able to reproduce the error. I need to debug it in https://github.com/mrakitin/SRW/issues/38.
