### ISSUE TITLE
Don't generate invalid JSON when NaNs

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#813]
Python's json module apparently generates NaN as a literal in the JSON when it generates the JSON. Therefore, we need to validate the JSON output either by parsing it again (load) or running our own checker.

**Comment by mrakitin** [comment]
This checker can be used - https://github.com/mrakitin/SRW/blob/master/env/work/srw_python/multielectron_test.py#L97:L118.

**Comment by mrakitin** [comment]
@moellep's solution is shorter.

**Comment by robnagler** [comment]
Isn't always? ;-)
