### ISSUE TITLE
interactive plots in Jupyter for SRW

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#825]
@mrakitin asked if we could enable interactive plots in Juypter notebooks. I just tried this, and it seems to work, but it is really ugly:

![screen shot 2017-08-03 at 1 53 36 pm](https://user-images.githubusercontent.com/5495179/28940821-2dfe3a8a-7853-11e7-942e-82830481cba5.png)

I noticed that the lineout plots are not interactive. Not sure why that is, but it has something to do with uti_plot. 

@mrakitin, are you seeing the above graph?

**Comment by mrakitin** [comment]
Hi Rob! Thanks for enabling this feature! It looks great in my case - https://jupyter.radiasoft.org/user/mrakitin/notebooks/SPIE_demo/01_single_file/SPIE_demo_01.ipynb:
![image](https://user-images.githubusercontent.com/13209176/28951337-4cdf32ac-7898-11e7-8181-c185b8375a9e.png)

**Comment by robnagler** [comment]
@mrakitin OK to close?

**Comment by mrakitin** [comment]
Yes. Closing.
