### ISSUE TITLE
fete: e-gun mode option

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#828]
Add an option on the Simulation Status panel on the Visualization page to run the simulation in e-gun mode. This will use a new execution template which is currently being modeled by Nathan and Chris.

**Comment by ncook882** [comment]
I've uploaded an IPython notebook documenting both egun mode and the impact density report to the rswarp repository [here](https://github.com/radiasoft/rswarp/blob/master/examples/sirepo-egunmode.ipynb).

**Comment by ncook882** [comment]
The IPython notebook has been updated to document and demonstrate one way to construct a particle trace report within egun mode without using tracer particles.

**Comment by moellep** [comment]
I'm working through this example now and have a question about USER_INJECT. It looks like it will always use USER_INJECT mode 1 for egun mode. Is this stubbed out for later development, or will that always be the case? Should the UI only show the egun option if USER_INJECT mode 1 has been selected by the user?

**Comment by ncook882** [comment]
I would suggest that "egun-mode" be offered as a specific option, and that it automatically fix USER_INJECT=1. We have found that egun mode doesn't work well with user-specified injection (top.inject=6), leading to additional particles and memory issues. The workaround is to specify the thermal dynamics using static attributes for `top` and `beam`:

>         beam.vthz     = np.sqrt(CATHODE_TEMP*kb_J/beam.mass)
>         beam.vthperp  = np.sqrt(CATHODE_TEMP*kb_J/beam.mass)
>         top.lhalfmaxwellinject = 1

I've tried to document this adjustment as well as some other changes at the top of the IPython notebook `sirepo-egunmode.ipynb` linked in the original issue. Please let me know if I haven't been clear with these guidelines, or if there are other considerations that I've overlooked.
