### ISSUE TITLE
kill process should let file get written first

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#83]
Occasionally when a partially-coherent background task is killed, it happens while it is in the middle of writing the output file, which then makes the file invalid. It would be bad to run a simulation for 30 minutes, but then loose the file when you stop it because the kill happened in the middle of the file-write.

**Comment by robnagler** [comment]
There's no way to coordinate this except via signals. Both Slurm and the job agent send dual signals: TERM followed by a delay before KILL. We have fixed SRW so that it doesn't write partial files. We have also fixed Sirepo to do atomic writes of json files. We can't fix the codes themselves.
