### ISSUE TITLE
fete: dielectric components

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#830]
Add a new field to the conductor type for specifying a dielectric component. This feature is dependent on running with the radiasoft warp branch in the container.

**Comment by ncook882** [comment]
I've uploaded a [script](https://github.com/radiasoft/rswarp/blob/master/examples/broad_dielectric_box_charging.py) to rswarp demonstrating the implementation of dielectrics via the conductor handle. The main requirement is to specify the keyword argument `permittivity` when defining a box object. The permittivity is defined relative to the permittivity of free space (i.e. eps_r = epsilon/eps_0)


> epsn = 7.
> 
> box = Box(xsize=0.5*(w3d.xmmax-w3d.xmmin),
>           ysize=0.5*(w3d.ymmax-w3d.ymmin),
>           zsize=0.1*(w3d.zmmax-w3d.zmmin),
>           xcent=0.5*(w3d.xmmax+w3d.xmmin),
>           ycent=0.5*(w3d.ymmax+w3d.ymmin),
>           zcent=0.8*(w3d.zmmax+w3d.zmmin),
>           permittivity=epsn)

**Comment by ncook882** [comment]
As we discussed, users should be able to specify the permittivity as "N/A" or some other non-numeric value, which classifies the object as an ideal conductor for the purposes of the simulation.
