### ISSUE TITLE
SRW: download raw data for lineout plots

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#836]
The raw data download option is for the full 2D data set.

If a user has selected specific lineouts to show important features, they will then want direct access to the corresponding 1D data array, for post-processing or visualization in another context.

This is a request from an active user of Sirepo/SRW

**Comment by mrakitin** [comment]
It was previously requested in https://github.com/radiasoft/sirepo/issues/788.

**Comment by bruhwiler** [comment]
I increased the priority of the previous issue.
I will close this one.
