### ISSUE TITLE
SRW: implement a screenshot capability

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#842]
X-ray beamline scientists need to grab screenshots of the GUI to put in their log book or into informal progress reports for their team.

This is a user request from SLAC. One cannot predict which part of the screen will need to be copied. The user suggestion is to provide a screenshot widget, which when clicked will modify the appearance of the cursor.

The user would then be able to select a rectangular region via click-drag-release
The selected region would be copied and so would be available to paste into an arbitrary desktop application.

**Comment by mrakitin** [comment]
Related ticket #763.

**Comment by moellep** [comment]
I've experimented with some promising javascript libraries for this, in particular:

https://github.com/weihanchen/angular-screenshot

Unfortunately it only worked in the Chrome browser. I think there are other projects working on this feature and it may be available in the near future on other browsers, in particular MS Edge.

I'm going to reduce the priority on this ticket to "2nd Priority" and bump a similar ticket #763 up to priority 1 in the meantime.

**Comment by bruhwiler** [comment]
A work around is to use Firefox, which now has sophisticated capabilities for screenshots within the window.

**Comment by bruhwiler** [comment]
We do not have a general solution for now.
