### ISSUE TITLE
Build #691 broken 

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#850]
The build failed: https://travis-ci.org/radiasoft/sirepo/builds/266144476

```text
sirepo/package_data/static/js/elegant.js: line 2502, col 14, Missing semicolon.
sirepo/package_data/static/js/sirepo-components.js: line 394, col 14, Missing semicolon.
sirepo/package_data/static/js/sirepo-components.js: line 950, col 14, Missing semicolon.
```

I recommend running test.sh before checking in.

**Comment by mkeilman** [comment]
It would help if the browser would complain about such things

I ran test.sh just now but I don't understand the output. It did not seem to complain about the semicolons. It did fail elegant_import_test.py, the same way before and after correction, so I'm not sure what I'm looking for:

`
E       AssertionError: tests/template/elegant_import_test.py:73:test_importer expect=
E       &run_setup
E         semaphore_file = run_setup.semaphore,
E         default_order = "1",
E         final = "run_setup.final.sdds",
E         lattice = "elegant.lte",
E         p_central_mev = "100",
E         parameters = "run_setup.parameters.sdds",
E         use_beamline = "BL",
E       &end
E       
E       &twiss_output
E         alpha_x = "0",
E         alpha_y = "0",
E         matched = "0",
E         output_at_each_step = "1",
E       &end
E       
E       &run_control
E       &end
E       
E       &optimization_setup
E         log_file = "optimization_setup.log_file.sdds",
E         n_evaluations = "1500",
E         n_passes = "3",
E         n_restarts = "2",
E         output_sparsing_factor = "100",
E         target = "0",
E         tolerance = "1e-12",
E         verbose = "0",
E       &end
E       
E       &optimization_term
E         term = "betax etax sqr /",
E       &end
E       
E       &optimization_term
E         term = "max.betax 20 .1 segt",
E       &end
E       
E       &optimization_term
E         term = "max.betay 20 .1 segt",
E       &end
E       
E       &optimization_variable
E         item = "L",
E         lower_limit = "0",
E         name = "D0",
E         step_size = "1e-3",
E         upper_limit = "5.0",
E       &end
E       
E       &optimization_variable
E         item = "L",
E         lower_limit = "0.1",
E         name = "D1",
E         step_size = "1e-3",
E         upper_limit = "5.0",
E       &end
E       
E       &optimization_variable
E         item = "L",
E         lower_limit = "0.1",
E         name = "D2",
E         step_size = "1e-3",
E         upper_limit = "5.0",
E       &end
E       
E       &optimization_variable
E         item = "L",
E         lower_limit = "0.1",
E         name = "D3",
E         step_size = "1e-3",
E         upper_limit = "5.0",
E       &end
E       
E       &optimization_variable
E         item = "K1",
E         lower_limit = "0",
E         name = "Q1",
E         step_size = "1e-3",
E         upper_limit = "2.5",
E       &end
E       
E       &optimization_variable
E         item = "K1",
E         lower_limit = "-2.5",
E         name = "Q2",
E         step_size = "1e-3",
E       &end
E       
E       &bunched_beam
E       &end
E       
E       &optimize
E       &end
E       
E       &save_lattice
E         filename = "save_lattice.filename.lte",
E       &end
E       
E       &run_setup
E         semaphore_file = run_setup.semaphore,
E         lattice = "save_lattice.filename.lte",
E         magnets = "run_setup2.magnets.sdds",
E         output = "run_setup2.output.sdds",
E         p_central_mev = "100",
E         sigma = "run_setup2.sigma.sdds",
E         use_beamline = "BL",
E       &end
E       
E       &twiss_output
E         alpha_x = "0",
E         alpha_y = "0",
E         filename = "twiss_output2.filename.sdds",
E       &end
E       
E       &run_control
E       &end
E       
E       &bunched_beam
E         alpha_x = "0",
E         alpha_y = "0",
E         beta_x = "1",
E         beta_y = "1",
E         distribution_cutoff[0] = 3, 3, 3,
E         emit_nx = "1e-6",
E         emit_ny = "1e-6",
E         enforce_rms_values[0] = 1, 1, 1,
E         n_particles_per_bunch = "100000",
E         sigma_dp = "1e-3",
E       &end
E       
E       &track
E       &end
E        != actual=global name 'model_name' is not defined

../../radiasoft/pykern/pykern/pkunit.py:214: AssertionError
`

Semicolons are in place but now I don't trust myself - I can't tell from here whether the build will work

**Comment by robnagler** [comment]
Do you have "./node_modules/jshint/bin/jshint" installed? See the script. npm should be installed on your vagrant box so just npm install jshint.

The elegant import test shouldn't fail. We'll have to look at that together. 

BTW, you need triple backticks when you want to quote something as literal text. Your comment used one backtick.

**Comment by moellep** [comment]
This wasn't an obvious error message, but the problem was the elegant
importer was trying to validate the distribution_type field with the
DistributionType enum when the distribution_type is actually a collection
of DistributionType enum values. I'll check-in a work-around for now.
