### ISSUE TITLE
SRW: Spectral Flux Report fails with Accurate/Use Approximate Method setting

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#856]
When you create a new Tabulated Undulator simulation and edit the Spectral Flux report settings, changing the Flux Computation Method to "Use Approximate Method", the simulation will fail with an error log:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
If you also change the Magnetic Field Treatment field to Approximate, the simulation completes successfully. Possibly these two fields Accurate (tabulated)/Use Approximate Method are not compatible?

**Comment by mrakitin** [comment]
That's an incompatible combination. Probably, we should notify a user about it somehow. When I did processing of the combination, I didn't have a way to exclude this combination.

**Comment by mrakitin** [comment]
We will check the allowed combinations again with @ochubar.

**Comment by mrakitin** [comment]
The original discussion was in https://github.com/radiasoft/sirepo/issues/189#issue-154085679. There is no such an option there:
`Magnetic Field Treatment` = `Accurate (tabulated)` (`--sm_mag=2`) and
`Flux Computation Method` = `Use Approximate Method` (`--sm_meth=-1`).

**Comment by mrakitin** [comment]
When the accurate (tabulated) magnetic treatment is selected, the list of options for the flux computation method should hide the approximate method. This can be a solution.
