### ISSUE TITLE
Beta release 9/1 10a

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#860]
@moellep would you validate that alpha works to your satisfaction and push to beta? I'll be going to Boulder at 10a (or earlier).

**Comment by mrakitin** [comment]
I checked Shadow-CRL on alpha, and it's functioning properly. Main SRW examples work fine as well.
@moellep, please do your tests and push to beta. Thanks!

**Comment by moellep** [comment]
One of my fixes for #857 is causing problems with the PNG download. I'll do another alpha release now.

**Comment by moellep** [comment]
The latest code is now available on beta.

**Comment by mrakitin** [comment]
Thanks @moellep, I appreciate your help.
