### ISSUE TITLE
SRW - optional disabling of normal/tangential vectors update for mirrors

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#861]
This was requested by SLAC colleagues during the SPIE conference:
> Make an option to switch off the update of the normal and tangential vector components for mirrors.

One of the toggle options can be used:
- http://www.bootstraptoggle.com/
- https://www.w3schools.com/howto/howto_css_switch.asp

**Comment by bruhwiler** [comment]
This is closely related to issue #838 

I think its OK to address these as two separate issues.

**Comment by mrakitin** [comment]
Thanks David. I wasn't sure where to find the related request.
