### ISSUE TITLE
Inconsistency of the results in Sirepo with ShadowOui and SRW

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#865]
@lucarebuffi pointed out that the results in Sirepo/Shadow3 interface do not match ones in ShadowOui:

## Sirepo:
![sirepo](https://user-images.githubusercontent.com/13209176/30170238-8b67987c-93bc-11e7-9d77-d3aa509e9b78.png)

## ShadowOui:
![shadow](https://user-images.githubusercontent.com/13209176/30170255-98bb3038-93bc-11e7-997f-a4c732dca18e.png)

## SRW (for comparison purposes):
![srw](https://user-images.githubusercontent.com/13209176/30170277-aadd1074-93bc-11e7-861c-be47aeca2090.png)

I'll investigate the reason why we have different results in Sirepo.

**Comment by robnagler** [comment]
It is usually easiest to compare the generated python scripts when debugging problems between Sirepo and ShadowOUI.

**Comment by mrakitin** [comment]
Yes, that's what I'm doing.

**Comment by mrakitin** [comment]
Fixed in 5271d660297928b62af720b44e9b491bb3b7fcef (tests fixed in 97f62977e209a9426936e40f01fbf6ec8a6c84f0). Now the results are very similar to ShadowOui results:

# Sirepo:
![screen shot 2017-09-19 at 13 25 10-fullpage](https://user-images.githubusercontent.com/13209176/30605952-0a798d7a-9d3e-11e7-9a75-8c5dfdd7afb4.png)

# ShadowOui:
![20m](https://user-images.githubusercontent.com/13209176/30607605-9b61a4b2-9d43-11e7-92fa-c878b9e1aa41.png)
![50m](https://user-images.githubusercontent.com/13209176/30607614-a0938f22-9d43-11e7-91f8-8e2c93e4a2ab.png)
![88 9m](https://user-images.githubusercontent.com/13209176/30607619-a3848d8a-9d43-11e7-80f1-043ede88549c.png)
![90m](https://user-images.githubusercontent.com/13209176/30607621-a5c11f5a-9d43-11e7-9911-c3bf83250a0f.png)

---
The archive with the simulation is [Virtual Beamline.zip](https://github.com/radiasoft/sirepo/files/1315269/Virtual.Beamline.zip), the corresponding example added to the Shadow3 examples named "Virtual Beamline". ShadowOui simulation is available at https://github.com/mrakitin/shadow3_examples/blob/master/ShadowOui_example.ows.

**Comment by robnagler** [comment]
Cool. It's nice to have a working end-to-end example in both programs.

**Comment by mrakitin** [comment]
Thanks Rob! Your CRL implementation in Sirepo/Shadow interface looked great, I just corrected the final `T_IMAGE` in the CRL element which should correspond to the position of the CRL (not the next element) in the beamline, so that the proper distance between the next element and the CRL is controlled by the next element's `T_SOURCE`, not the CRL's `T_IMAGE`.
