### ISSUE TITLE
Exported Python file names

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#866]
It would be very useful if the exported Python name contain underscores instead of blank spaces for easier execution of the code from console. I think all lower-case letters would also improve the experience with the exported scripts.

**Comment by robnagler** [comment]
We may want to use '-', because it shows up better in URLs.

**Comment by mkeilman** [comment]
Would this combine with #1033 to yield (in that example) 'tabulated-undulator-example-power-density-report.py'?

**Comment by robnagler** [comment]
Yes.
