### ISSUE TITLE
Warp example not working

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#87]
The warp script doesn't work. The output is wrong and Dynamics simulations don't start. 

Nathan, I think the ball was in your court to get the basic script working. Would you be able to work on it this week? We had someone inquiring about using it in Sirepo. Thanks!

**Comment by robnagler** [comment]
@ncook882 wrote:

If you try plotting E_y with the laser preview, you should get a nice looking laser pulse, as shown in the "laser_preview_Ey" png. Plotting "E_r" does give you something along the lines of what you sent me (see "laser_preview_Er"). However, the domain seems to be a bit off. The simulation box varies in x/y/r from -30 to 30 microns (vertical axis), and along the z-axis from about -2 microns to + 38 microns (something similar to what your particle plot shows on the right side of the 2nd image).

I've also attached a picture of the electron distribution (z v. x) at about 200 fs. This isn't quite as far as your simulation seems to be running, but I am seeing the plasma spread much more broadly away from the r = 0 plane. I'm not sure what might be the problem here, unless you are running with different plasma parameters than were specified in the script I sent you.

<img width="548" alt="laser_preview_ey_640" src="https://cloud.githubusercontent.com/assets/5495179/14037156/3a8cbf4e-f206-11e5-8f42-b7db235a22b6.png">
<img width="552" alt="laser_preview_er_640" src="https://cloud.githubusercontent.com/assets/5495179/14037163/4f2fd382-f206-11e5-8a0e-75a6b9ed6f40.png">
<img width="533" alt="electrons_z_x_1000" src="https://cloud.githubusercontent.com/assets/5495179/14037164/5390e722-f206-11e5-8d68-3dbed565dad7.png">

**Comment by robnagler** [comment]
I've got it working using [openPMD](https://github.com/openPMD/openPMD-viewer). When
we first got it working, we made a lot of assumptions about the values in the h5 file, which
won't work if people do different types of computations. openPMD knows how Warp writes
the h5 files, and it extracts the information using the h5 attributes, which we weren't doing.

There will have to be a few patches to openPMD. It doesn't know how to handle checking
data in real-time. It also opens all files in the series, which doesn't make sense. However,
we can either monkey patch or ask the openPMD authors to accept some changes.

Let's discuss. For now, I think it works well enough for the final report.

Let me know if the graph looks right.

<img width="667" alt="laser_preview_ey_640_openpmd" src="https://cloud.githubusercontent.com/assets/5495179/14037188/96517126-f206-11e5-9b5d-cb8228c24993.png">
<img width="1350" alt="field_and_particle_animation" src="https://cloud.githubusercontent.com/assets/5495179/14037240/09d57f5c-f207-11e5-8b91-b027e69c8c40.png">

**Comment by robnagler** [comment]
I merged my branch into master. I had to make some fixups to the elegant and srw implementations.

To install openPMD-viewer, you can:

```bash
curl radia.run | bash -s containers/radiasoft/beamsim openPMD
```

Still need to:

* Fix the z axis
* Add fixup old data (just remove old examples would be best?)
* Paralellize (see #88)
* Implement PWFA script (see #134)

**Comment by bruhwile** [comment]
I think it would be fine to remove old examples.

David
