### ISSUE TITLE
Hellweg: drag and drop problems with many lattice elements

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#871]
A linac can have many cells. Once the display of icons reaches down to the bottom of the browser window, it is no longer possible to drag a new 'cell' element down to the end of the list. See the screenshot below.

The work around is to demagnify your browser window, but that's not acceptable in the long run.

![image](https://user-images.githubusercontent.com/3825435/30337098-80359ea4-97a4-11e7-93b8-c4ca1c19d501.png)

**Comment by robnagler** [comment]
No longer supported.
