### ISSUE TITLE
Hellweg:  "Beam Animation" report on Visualization tab cannot be resized

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#872]
It's not possible to change the axis limits for this report.
This renders the report useless for some simulations, possibly because 1 or 2 stray particles are forcing very large values for x_min, y_max, etc.

**Comment by bruhwiler** [comment]
The problem is different than I originally thought.
All the particles are lost at some point in the linac.
When there are no particles, the report reverts to default behavior, which I find confusing.
See the screen shot below.
It would be much better to get rid of the artificial data point at the center. The report claims there are 10^4 particles on axis, when in fact there are zero.

![image](https://user-images.githubusercontent.com/3825435/30337857-ddcc1dc0-97a6-11e7-9d45-dc0169bef204.png)

**Comment by moellep** [comment]
I've reproduced the problem with your TW Linac example. Hellweg is reporting that 100% of the particles were transmitted, but the Particle Report is showing they get abruptly cut off. I'll retest this simulation when we have sirepo running with the latest Hellweg code.

<img width="729" alt="screen shot 2017-09-20 at 1 19 26 pm" src="https://user-images.githubusercontent.com/6516910/30663085-b03f6b94-9e06-11e7-9546-687c2d5e8c8f.png">
