### ISSUE TITLE
Hellweg:  Sirepo results do not agree with console simulation results

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#874]
For a linac design, https://beta.sirepo.com/hellweg#/visualization/kDmzPdbM
the results still deviate from what is seen in the console version, using the latest code.

Perhaps the Sirepo container does not include the latest version of Hellweg...?
If so, this needs to be fixed.

**Comment by robnagler** [comment]
We are using the integration branch so I doubt it has been updated. It will be a process for me to learn how to do this.

What's the time frame?

**Comment by bruhwiler** [comment]
How about Thursday, September 21?

**Comment by robnagler** [comment]
Roger.

**Comment by robnagler** [comment]
No longer supported.
