### ISSUE TITLE
SRW - display multiple curves on XY plots

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#879]
Request from @ochubar:
> It would be more convenient to allow users to display multiple curves on XY plots.
> Plotting of the quantities with the same units (e.g., meters or radians) should be allowed and the corresponding legend should present.

An example at the moment could be the Trajectory Report with the tabulated undulator where users may need to display both horizontal and vertical positions of electrons at the same time (angles and other quantities to be added within #862). A report can look like one in the Hellweg app:
![image](https://user-images.githubusercontent.com/13209176/30401428-3a2e872c-98a8-11e7-9426-201d942f624e.png)

**Comment by moellep** [comment]
I'm bumping the priority on this after this discussion on today's telecon.
