### ISSUE TITLE
SRW - add missing propagation parameters

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#880]
There can be a few more fields in the propagation parameters. Need to add the missing fields (possibly in an additional tab or via horizontal scrollbar). Waiting details from @ochubar.

**Comment by mrakitin** [comment]
[SRW Example 12](https://github.com/ochubar/SRW/blob/master/env/work/srw_python/SRWLIB_Example12.py#L205) has additional parameters to be added:
```py
  #[ 9]: Type of wavefront Shift before Resizing (not yet implemented)
  #[10]: New Horizontal wavefront Center position after Shift (not yet implemented)
  #[11]: New Vertical wavefront Center position after Shift (not yet implemented)
  #[12]: Optional: Orientation of the Output Optical Axis vector in the Incident Beam Frame: Horizontal Coordinate
  #[13]: Optional: Orientation of the Output Optical Axis vector in the Incident Beam Frame: Vertical Coordinate
  #[14]: Optional: Orientation of the Output Optical Axis vector in the Incident Beam Frame: Longitudinal Coordinate
  #[15]: Optional: Orientation of the Horizontal Base vector of the Output Frame in the Incident Beam Frame: Horizontal Coordinate
  #[16]: Optional: Orientation of the Horizontal Base vector of the Output Frame in the Incident Beam Frame: Vertical Coordinate
```

**Comment by moellep** [comment]
We'll need to rethink how the propagation parameters are shown for input. I don't think the table will expand much farther. One way would be to separate it into several tables on separate tabs.

**Comment by mrakitin** [comment]
Tabs are a good idea. Another possible solution could be a toggle button on top of the groups of parameters, which would minimize columns like it's done for minimization of the reports. Frequently used columns will be maximized by default, the other ones - minimized.

**Comment by mrakitin** [comment]
@moellep, could you please assist me with the new propagation parameters? Thank you.
