### ISSUE TITLE
SRW - changeable distance for Initial Intensity Report

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#882]
The distance of the `Initial Intensity Report` on the Beamline page for Gaussian beam source should be changeable.

**Comment by mrakitin** [comment]
Fixed in 275ff76.

**Comment by mrakitin** [comment]
The distance field should appear in the `Initial Wavefront Simulation Grid` parameters, and should be synchronized with the position of the first element in the beamline, i.e.
- when the position of the first element changes, that should trigger update of the distance from source;
- when the distance from source changes, this should be a new position of the first element, and the rest of the beamline should be shifted accordingly.

**Comment by bruhwiler** [comment]
The first bullet seems reasonable.
The 2nd bullet seems like a side effect that might work in many cases, but could be a bad unexpected consequence for some users.

It seems to me this requires a little more thought.

**Comment by mrakitin** [comment]
Thanks for your feedback David. We discussed it today with Oleg, and he pointed out a user may need to shift the whole beamline relatively to the source position. The second bullet addresses this request. Anyway, I'll double check this feature does not change the existing beamlines without user's input.

**Comment by mrakitin** [comment]
The code is ready for review - 9d8de0db255f8a21c5c6b308602b27f07ee72f02 & f4189d05fae11353cc976b519fb4fcba52024ab4.

**Comment by mrakitin** [comment]
@moellep, please review the code. Thanks!

**Comment by moellep** [comment]
The code looks good. It lets the user shift the beamline by editing the "Distance From Source" value in the menu, but still allows repositioning the first element independently by directly editing from the beamline.

**Comment by mrakitin** [comment]
Thanks for the review Paul! I'll merge the code to master. The fix ac11cbe also assures the distances in the predefined beamlines are preserved.

**Comment by mrakitin** [comment]
Merged.
