### ISSUE TITLE
Discard changes feature should be available on all apps

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#888]
The "Discard changes" to example simulations which is available in the SRW app should be made available to all apps. Possibly the cog-wheel menu could be added as a general app feature.

**Comment by moellep** [comment]
@mkeilman, in srw.js the appHeader has several features, such as "Discard Changes to Example" which should be moved to sirepo-components.js and made available to all the apps. Possibly, the cog-wheel dropdown could be moved out, with a ng-transclude portion which allows apps to add custom items to the menu. SRW, for example, would have custom menu items for "Simulation Documentation URL" and "Initial Wavefront SImulation Grid". "Open as a New Copy" and "Discard/Delete" could be available in all apps. The "Export JSON Data File" should be replaced with "Export as Zip" and use the same functionality as "Export as Zip" on the simulation list drop-down menu.

![screen shot 2017-09-21 at 10 49 15 am](https://user-images.githubusercontent.com/6516910/30708190-33519250-9ebb-11e7-94d0-cc090f15d657.png)

**Comment by robnagler** [comment]
I think Simulation Documentation URL should be available to all apps, no?

**Comment by mkeilman** [comment]
The schema for Simulation Documentation exists only for srw, so it would have to be added to the other apps (is there a common area for views/models?)

Is this the time to pull some of the other repeated stuff out of the apps and into sirepo-components? I'm thinking of the new sim/folder functions by way of example...

**Comment by moellep** [comment]
Right now there is no common area for view/models - for example, each app schema has a copy of the "simulation" and "simulationFolder" models/views.
Yes, this would be a good time to also move any common code from the apps into sirepo-components.

**Comment by robnagler** [comment]
See also #354
