### ISSUE TITLE
Sirepo Landing Page 

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#893]
These are suggestions for changes (my ideas only)

- [ ] Add a description of Sirepo before the fun examples:  What is it, Why use it, who to write to with questions
- [ ] Make the clickable elements more obviously clickable (e.g. "buttons" labeled SRW, Shadow3 etc.; true on pages within SRW as well)
- [ ] On many of the descriptions, move the information about who created the code and who maintains it to a secondary page.  For example, move "The SRW source code is available on GitHub. The code is primarily supported by Oleg Chubar of NSLS-II at Brookhaven National Laboratory." under more.
- [ ] Provide a way other than opening a GitHub issue to provide a suggestion or feedback. GitHub is too public and too formal
- [ ] Change "Beta test the Sirepo apps below to explore the world" to say "above".

**Comment by bruhwiler** [comment]
This issue has been overtaken by events.
