### ISSUE TITLE
Add SPIE presentation to beta.sirepo.com

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#895]
We should add the link for this video to the GitHub Sirepo repository.  My suggestion is to add it near the top of beta.sirepo.com.

Perhaps with language such as: "This video provides an overview and demo of Sirepo". <<LINK TO VIDEO>>

Maksim S. Rakitin, Oleg Chubar, Paul Moeller, Robert Nagler, David L. Bruhwiler, "Sirepo: a web-based interface for physical optics simulations - its deployment and use at NSLS-II," Proc. SPIE 10388, Advances in Computational Methods for X-Ray Optics IV, 103880R (23 August 2017).

Someplace we need to include this copyright info:
Copyright 2017 Society of Photo Optical Instrumentation Engineers. One print or electronic copy may be made for personal use only. Systematic reproduction and distribution, duplication of any material in this paper for a fee or for commercial purposes, or modification of the content of the paper are prohibited.

The URL to view the presentation is:
https://players.brightcove.net/689254975001/8392bffb-4fa4-4c94-a7cb-68d17a1701a0_default/index.html?videoId=5581188865001
 
Sample code for embedding the video on a website would be:
 
<div style="position: relative; display: block; max-width: 100%;">
<div style="padding-top: 56.25%;">
<iframe src="//players.brightcove.net/689254975001/8392bffb-4fa4-4c94-a7cb-68d17a1701a0_default/index.html?videoId=5581188865001"
allowfullscreen
webkitallowfullscreen
mozallowfullscreen
style="position: absolute; top: 0px; right: 0px; bottom: 0px; left: 0px; width: 100%; height: 100%;">
</iframe>
</div>
</div>

**Comment by mrakitin** [comment]
@bnash was asking about the link. @bruhwiler, @moellep, is it worth to prioritize the integration?

**Comment by bruhwiler** [comment]
The copyright statement worries me.  Putting a link on the Sirepo landing page doesn't really qualify as "personal use".

@messamer  --  what do you think about the copyright issue?

**Comment by bruhwiler** [comment]
@messamer -- how do you suggest that we proceed?

**Comment by bruhwiler** [comment]
@messamer -- what is the status of this issue?

**Comment by messamer** [comment]
We decided that it was ok to include on GitHub but not RadiaSoft.net or Sirepo.com.  I suggest that we the link to GitHub but not in as prominent a place as first suggested-  the SRW interface has changed significantly since this was produced and we are working on newer videos to showcase an introduction to SRW

The link from SPIE is included below:

The URL to view the presentation is:
https://players.brightcove.net/689254975001/8392bffb-4fa4-4c94-a7cb-68d17a1701a0_default/index.html?videoId=5581188865001
 
Sample code for embedding the video on a website would be:
 
<div style="position: relative; display: block; max-width: 100%;">
<div style="padding-top: 56.25%;">
<iframe src="//players.brightcove.net/689254975001/8392bffb-4fa4-4c94-a7cb-68d17a1701a0_default/index.html?videoId=5581188865001"
allowfullscreen
webkitallowfullscreen
mozallowfullscreen
style="position: absolute; top: 0px; right: 0px; bottom: 0px; left: 0px; width: 100%; height: 100%;">
</iframe>
</div>
</div>
