### ISSUE TITLE
SRW: graphic artist for beamline icons

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#897]
Now people are including the beamline images in papers, it would be good to get them redone by a graphic artist. Preferably, the file format would be SVG because it scales nicely to any display size. Future icons, ex. toroidal mirror, should also be created with this item.

![screen shot 2017-09-29 at 9 37 58 am](https://user-images.githubusercontent.com/6516910/31023695-e8d8760e-a4f9-11e7-8b09-0fbbbb281370.png)

**Comment by bruhwiler** [comment]
Input from developers is that this would be a welcome improvement to the UI.

It was also noted that Sirepo screenshots in presentations and publications seem suboptimal -- maybe some of the border lines could be thicker, and maybe some less muted colors could be used. These are issues where advice from a graphic artist would be helpful.

**Comment by robnagler** [comment]
Spoke with Eli today. He'll do some research and get back to us.
