### ISSUE TITLE
undulator UI -- offer "k parameter" as alternative to B for idealized cases

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#9]
It would be very convenient for users, if the undulator UI would calculate and show the k parameter, when B is specified, with the option to specify k and see the resulting calculation for B.

Note that this is straightforward only in the case of an idealized undulator with only the fundamental harmonic, and including some other assumptions and approximations.

In general, for non-idealized undulators, the effective value of k must be calculated with some care. It would still be very convenient to perform this calculation for users. However, in this more general case, one cannot specify k as an input variable.

**Comment by bruhwile** [comment]
Oleg and Maxim will discuss how to implement this at the Python script level

**Comment by bruhwile** [comment]
This is still relevant.
Implementation should not be too difficult.
It could be done in Javascript; however, SRW directly supports the ability to specify B or k.

**Comment by mrakitin** [comment]
Fixed in 0f458e50f371c1e22e3ad57ffab62976c882471c. Will be merged later with the implementation of #184.

**Comment by mrakitin** [comment]
Need to get rid of the "Undulator Definition by" parameter.

**Comment by mrakitin** [comment]
`undulatorDefinition` removed in 920db73. Since there is no static reference to the way the undulator is defined now, need to identify if the field in focus/active, so it's not updated by automatic "watch" procedure. Waiting suggestion from @moellep.

**Comment by mrakitin** [comment]
ab12e67 - updates in the fields which are not in focus do not cause backward update of the field in focus. Closing.

**Comment by mrakitin** [comment]
Not all `undulatorDefinition` were cleaned in 920db73. Need to clean all of them and set the value of K on the server side before the page load.

**Comment by mrakitin** [comment]
Now it's fixed in c718cbf. Closing.

**Comment by mrakitin** [comment]
Undulator parameter was set to `None` on the server side, that caused the parameter on the client side to disappear after the advanced pop-up menu of the undulator was invoked and closed. Need to fix it.

**Comment by mrakitin** [comment]
The problem with an empty field fixed in 208c5c8.
I hope I'm done with this ticket. Closing.
