### ISSUE TITLE
Build issue related to plugin loading order

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#905]
I think the root cause is the plugin order is random (see pytest-dev/pytest#935). I thought I could force the order by reinstalling xdist and forked. That didn't fix things. We don't need xdist as "--boxed" has recently been forked to pytest-forked, which is what we need to run our tests in separate processes. 

Still failing https://travis-ci.org/radiasoft/sirepo/builds/284326211

**Comment by robnagler** [comment]
Well that was fun. I fixed this by adding a conftest.py. I updated all our pykern projects even though few have tests :). 

@mrakitin you'll need to update mrakitin/bnlcrl. Here's an example commit https://github.com/radiasoft/rscooler/commit/09d0883825cb81964671bc6524aa20bf88e016cb 

This is pretty much all you need to do:

```sh
cd ~/src/radiasoft/pykern
git pull 
cd ~/src/mrakitin/bnlcrl/tests
git pull
cp ~/src/radiasoft/pykern/tests/conftest.py .
git add conftest.py
git commit -m 'See radiasoft/pykern#18 and radiasoft/sirepo#905' conftest.py
git push
```

**Comment by mrakitin** [comment]
Thanks @robnagler, I've followed the steps and updated the package.
