### ISSUE TITLE
View settings should be preserved in the simulations list

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#907]
`View as List` viewing mode in the simulations list page (Expert mode) should be preserved during navigation through the folders. Currently when I switch to the list mode, it becomes the `View as Icons` mode once I select another folder, and even when I come back to the previous folder, the simulations are shown as icons.

**Comment by moellep** [comment]
This UI preference could be stored in a cookie value until we support a per-user json config file.

**Comment by robnagler** [comment]
It's actually not a cookie, but in the beaker session. This is a "per browser" data store.

**Comment by moellep** [comment]
We use the angularjs $cookies module for the notificationService. I'm not sure if that ties in with the beaker session or is separate.

**Comment by robnagler** [comment]
That probably stores in the browser local data store, which has the same semantics in terms of "per browser".  Angular itself has no access to the beaker session state. All that is available to Angular is the beaker session key.

**Comment by mkeilman** [comment]
Would this be set per app or globally?

**Comment by moellep** [comment]
I think keep it global. Basically it is a single user preference which affects all apps.

**Comment by moellep** [comment]
This bug has returned - when you select "view as list" adn click on the a folder, it returns to the icon view.
