### ISSUE TITLE
Boolean toggle UI

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#910]
Boolean values are currently displayed as an enum with two values:

![screen shot 2017-10-11 at 10 57 01 am](https://user-images.githubusercontent.com/6516910/31454517-ef761bb0-ae72-11e7-8642-10d14d4985e7.png)

A toggle switch would be a better choice in this case. Below are a few example implementations (taken from issue #861)

- http://www.bootstraptoggle.com/
- https://www.w3schools.com/howto/howto_css_switch.asp

**Comment by mrakitin** [comment]
Related to #936.
