### ISSUE TITLE
SRW - unexpected "Auto-undulator" in the animated Flux report

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#923]
The `Auto-undulator` note appeared again in the animated Flux report after the recent merge https://github.com/radiasoft/sirepo/commit/1707e92cdb4e6ca9e50fea1a02b8f1319a43ca89#diff-7f196f7b50bfc3dd252e10467928228cR1514:
![screenshot-2017-10-15 nsls-ii srx beamline - srw - radiasoft](https://user-images.githubusercontent.com/13209176/31593391-578b6822-b1fc-11e7-826e-d5e6aee74cb1.png)

I've already removed it previously (see https://github.com/radiasoft/sirepo/commit/83454fe7f7f173a94fe3ee9084a149d989e07ee0). It's rather a debug information than something expected by a user. To make sense, it should have the full description of the parameter, i.e. `Flux Computation Method: Auto-undulator`, but I prefer not to have this info in the widget, since it is already in the parameters.

Is there any reason this information should be in the widget?

**Comment by mkeilman** [comment]
My apologies - I didn't realize this got removed, and as I was addressing it myself I noticed that the partially coherent simulation was actually restarting immediately after being stopped! In the process of fixing that I replaced the label; so, I will remove it again.

**Comment by mrakitin** [comment]
Thank you Michael!

**Comment by mrakitin** [comment]
Seems to work fine with the latest code. Closing.
