### ISSUE TITLE
Self-extracting simulation to http://sirepo.com

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#924]
I've tried to import an exported simulation to http://sirepo.com, but it results in an unknown address:

https://beta.sirepo.comimport-archive/

Please fix the issue. Thanks.

**Comment by mrakitin** [comment]
There is a screenshot in the draft for that, I'd prefer to have sirepo.com rather than beta.sirepo.com there:
![self_extracting_simulation](https://user-images.githubusercontent.com/13209176/31593789-c40f9cc8-b1fe-11e7-8626-acbba43ba829.png)

**Comment by moellep** [comment]
I'll look at this issue, along with #852 now.
