### ISSUE TITLE
Too small font in the plots

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#930]
The font in the plots seems to be really small - on the exported plot for the publications the axes ticks and numbers are barely distinguishable. It would be better to have a bit larger font.

**Comment by moellep** [comment]
The work-around for this in the short-term is to make the browser window smaller before downloading the report. The software creates a PNG from report as it is currently displayed. For example, below is the same report, one downloaded from a small browser window, one from a large.

![single-electron-spectrum-report-20m-6](https://user-images.githubusercontent.com/6516910/31679048-3557593c-b32d-11e7-8792-094b971fb27a.png)

![single-electron-spectrum-report-20m-7](https://user-images.githubusercontent.com/6516910/31679054-39d5b5ee-b32d-11e7-9387-9cbef4261ae6.png)

**Comment by bruhwiler** [comment]
This is a ubiquitous problem with scientific graphics, and it would be great if Sirepo solved it for people. 

In a presentation, the plots are typically large and one is happy with a relatively small font size and lots of small'ish tick marks. 

However, in a paper, the plot is small, and so the fonts need to be significantly larger, and therefore you must use fewer tick marks/labels so the larger-font labels don't collide with each other. Also, the tick marks should be larger.

It would be great if one could toggle back and forth between these two options.

**Comment by mrakitin** [comment]
I've tried different fonts - 10pt (current option), 12pt, and 14pt:
![10pt](https://user-images.githubusercontent.com/13209176/31683079-e3310122-b349-11e7-88d9-4bd0b4811571.png)
![12pt](https://user-images.githubusercontent.com/13209176/31683082-e588a07e-b349-11e7-8a83-217270c90668.png)
![14pt](https://user-images.githubusercontent.com/13209176/31683085-e79713a0-b349-11e7-9bf8-32cb1f9f539b.png)

12pt image (second one) seems fine to me.

**Comment by mrakitin** [comment]
If one arranges 3 plots in one row on a letter paper, it's very hard to read the numbers, e.g. (the width is 8.5"):
![letter](https://user-images.githubusercontent.com/13209176/31683207-4f8be2ba-b34a-11e7-87f6-55e76da0a666.png)

**Comment by mrakitin** [comment]
For the plots in the paper draft I used 12 pt font.
