### ISSUE TITLE
memory leak in jquery bootstrap toggle

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#934]
Forms with the new bootstrap toggle cause a memory leak. This happens with every jquery plugin in angularjs apps and can be tricky to fix.

To reproduce memory leaks, open the app in Chrome with and open the developer tools to the Memory page:

![screen shot 2017-10-17 at 3 17 28 pm](https://user-images.githubusercontent.com/6516910/31690331-a790d8da-b34f-11e7-8f3b-c38d8f40c1a1.png)

Then before starting the profiler, switch between tabs so the base app gets loaded in memory. That way global app parts won't show up as new allocations.

Then start the profiler and switch between tabs, open a mirror item and switch to the "Grazing Angle" page (which has a toggle widget). Then switch back to the Source tab. Do this a few times, and the allocation bar at the bottom should show a few peaks over 5MB, but only the recent ones should be blue. Below is an example with no memory leaks:

![screen shot 2017-10-17 at 3 18 03 pm](https://user-images.githubusercontent.com/6516910/31690564-51060a2a-b350-11e7-8a7a-a26aeaa2bc5d.png)

And this examples shows a memory leak each time you leave the Beamline tab:

![screen shot 2017-10-17 at 3 18 51 pm](https://user-images.githubusercontent.com/6516910/31690585-64114fe4-b350-11e7-9b3b-5fec1a7ffb74.png)

The Chrome profiler lets you look at the memory leak object which appear as red elements in the inspector. You should change your javascript sources to non-minified before debugging (which I didn't do below).

![screen shot 2017-10-17 at 3 34 32 pm](https://user-images.githubusercontent.com/6516910/31690697-bf5cafe2-b350-11e7-8ec8-5aab136a660e.png)

Fixing memory leaks like this usually involves adding extra code to the directive's $destroy handler. Often the memory leaks require extra debugging due to bugs in the jquery destroy() methods.

I've got a fix for this particular case which I'll check-in next, but I wanted this ticket to document the debugging steps.

**Comment by mrakitin** [comment]
Great instructions, thanks Paul!
