### ISSUE TITLE
Application Error: TypeError: thisToggle.bootstrapToggle is not a function

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#936]
There is an error in one of my Shadow simulations:
```
Application Error: TypeError: thisToggle.bootstrapToggle is not a function. A report was sent to the server.
```
Server log:
```js
10.0.2.2 - - [19/Oct/2017 11:15:28] "POST /error-logging HTTP/1.1" 200 -
../sirepo/server.py:178:api_errorLogging 10.0.2.2: javascript error: {
    "cause": "<no cause>",
    "message": "TypeError: thisToggle.bootstrapToggle is not a function",
    "stackTrace": [
        "link/<@http://localhost:8000/static/js/sirepo-components.js?20171019.151527:1657:17",
        "e/q<@http://localhost:8000/static/js/ext/angular-1.6.1.min.js?20171019.151527:160:431",
        "f@http://localhost:8000/static/js/ext/angular-1.6.1.min.js?20171019.151527:47:146",
        "kg/k.defer/c<@http://localhost:8000/static/js/ext/angular-1.6.1.min.js?20171019.151527:50:68"
    ],
    "type": "clientException",
    "url": "http://localhost:8000/shadow#/beamline/07On1SJr"
}
../sirepo/server.py:178:api_errorLogging 10.0.2.2: javascript error: {
    "cause": "Possibly unhandled rejection: {}",
    "message": "TypeError: thisToggle.bootstrapToggle is not a function",
    "stackTrace": [
        "link/<@http://localhost:8000/static/js/sirepo-components.js?20171019.151527:1657:17",
        "e/q<@http://localhost:8000/static/js/ext/angular-1.6.1.min.js?20171019.151527:160:431",
        "f@http://localhost:8000/static/js/ext/angular-1.6.1.min.js?20171019.151527:47:146",
        "kg/k.defer/c<@http://localhost:8000/static/js/ext/angular-1.6.1.min.js?20171019.151527:50:68"
    ],
    "type": "clientException",
    "url": "http://localhost:8000/shadow#/beamline/07On1SJr"
}
```
A fancy toggle button does not appear, just a regular checkbox:
![screenshot-2017-10-19 sirepo paper - shadow beamline 2 - shadow - radiasoft](https://user-images.githubusercontent.com/13209176/31778743-6f5719b8-b4bf-11e7-9612-c681fd2d43a7.png)

**Comment by moellep** [comment]
I have a feeling this is related to the $timeout() call before the parent element is available. I don't have a working test case yet. @mrakitin let me know which broswer/operating system you are using and it will help reproduce it.

**Comment by mrakitin** [comment]
It's Windows/Firefox 57b.

**Comment by mrakitin** [comment]
I'm not sure what was going on there, but after restart of the VM, the problem disappeared (maybe the suspend mode caused the issue somehow), but it seems there is another problem associated with the new toggle button - in Shadow interface it does not hide the size fields if the override option is set to `No`:

![screenshot-2017-10-19 sirepo paper - shadow beamline 2 - shadow - radiasoft](https://user-images.githubusercontent.com/13209176/31784416-980329dc-b4cf-11e7-9e3e-831f223bcd8b.png)
--
![screenshot-2017-10-19 sirepo paper - shadow beamline 2 - shadow - radiasoft 1](https://user-images.githubusercontent.com/13209176/31784420-9adfbf6c-b4cf-11e7-86f9-05c9893a6ed9.png)

**Comment by mrakitin** [comment]
With the latest master code, I don't have the slider at all, just old-style buttons are displayed:
![screenshot-2017-10-25 sirepo paper - shadow beamline 2 - shadow - radiasoft](https://user-images.githubusercontent.com/13209176/32006971-3bc89ed0-b976-11e7-8ab3-b75e360b0eb1.png)

**Comment by moellep** [comment]
Yes, I disabled the boolean toggle for now. I found a case where it didn't render correctly when a page was reloaded in the warpvnd app.

**Comment by mrakitin** [comment]
I see, thanks for the update Paul.

**Comment by moellep** [comment]
On the warpvnd Visualization tab, the boolean toggle is always showing Electon Gun Mode "No" when you visit the page, even if the actual value is "Yes".
