### ISSUE TITLE
Shadow - source definition tabs

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#937]
In Shadow interface I have to frequently change the geometry parameters of the source, therefore it's frequently requires changing advanced parameters in the Geometry tab, which is not the default tab. It would be more convenient to have this tab first, and then the number of rays, etc., or just to merge the basic and geometry settings.

Another issue - it seems that either `Sigma (X/Z) [mrad]` or ` Divergence +/-X/Z [mrad]` can determine the divergence of the beam, therefore there should be a toggle setting one set of options or another.

**Comment by moellep** [comment]
I've moved combined the Basic and Geometry Settings tabs for the Geometrical Source which should help.

![screen shot 2017-11-14 at 3 34 25 pm](https://user-images.githubusercontent.com/6516910/32809025-87bb2e5c-c952-11e7-8c79-63441025f76e.png)

The Sigma X and Divergence +X fields seem to be independent for a geometric source with a gaussian distribution. The divergence values act like a filter on the rays, for example the graph below has a sigmax of 0.1 and a divergence of 0.08, -0.04 (using the settings from the screenshot above).

![plot-xy-1m](https://user-images.githubusercontent.com/6516910/32809090-cc2e2076-c952-11e7-9fad-e86436beba7e.png)

**Comment by mrakitin** [comment]
@moellep, thanks for the fix and for the explanation!
