### ISSUE TITLE
Keep units on report axis label

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#948]
Rather than showing the units on each axis tick mark, show the units on the axis label, but dynamically scale it to the range displayed (ex. m, mm, μm).

For example, the report below (in the old format) would dynamically show the axis label as "Horizontal Position (mm)" or when zoomed in "Horizontal Position (μm)".

![screen shot 2017-11-01 at 11 46 08 am](https://user-images.githubusercontent.com/6516910/32288971-13b1ec46-befb-11e7-90ac-29c05fe84df5.png)

**Comment by mrakitin** [comment]
I like the suggestion.
