### ISSUE TITLE
fete: Impact Density failure on small simulation steps setting

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#952]
The Impact Density report is failing when the selected "Simulation Steps" is set to a value less than the "expected steps" value. For example, running the Heat Engine example with 500 steps causes a "Internal Server Error" message.

https://beta.sirepo.com/warpvnd#/visualization/l8xtil7H

**Comment by robnagler** [comment]
I'll be rebuilding with rswarp shortly. See radiasoft/devops#124
