### ISSUE TITLE
elegant: support SDDS particle files with cylindrical coordinates

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#956]
I'm trying to import the official elegant example 'alphaMagnet' into Sirepo, https://github.com/radiasoft/elegant/tree/master/examples/alphaMagnet

The *.ele file and *.lte files are imported without error, after which I'm asked to upload the file rfgunBeam.sdds resulting in the following error message:

![image](https://user-images.githubusercontent.com/3825435/32701356-ff5452b8-c790-11e7-8716-c40a297aec2d.png)

Looking into the rfgunBeam.sdds file, one can see that the coordinates are cylindrical, rather than Cartesian.  This type of SDDS particle file should be supported.

My simulation can be found here, https://beta.sirepo.com/elegant#/source/nwZJDWHo

**Comment by moellep** [comment]
This should be fixed by checking the available columns and setting input_type="spiffe" automatically on the sdds_beam command if the r,pz,pr are present.

**Comment by moellep** [comment]
Fixed with 0a6a1ae

**Comment by bruhwiler** [comment]
Has this fix been pushed to alpha or beta?

**Comment by bruhwiler** [comment]
I see that they've been pushed to alpha.
Thanks.
