### ISSUE TITLE
run-away process from deleted simulation

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#958]
On beta, it looks like a run-away process may have caused major slowness to other users. beta was taking many seconds to respond when the user selected "New Simulation" on the elegant app.

flower showed 0 jobs running on celery, but when looking at apa19b, there were 4 python processes running:

```
27500 pts/2    Sl+    0:03 /home/vagrant/.pyenv/versions/py2/bin/python /home/vagrant/.pyenv/versions/py2/bin/
sirepo srw run-background /var/db/sirepo/user/CsCZcfiK/srw/6jLI7VAE/fluxAnimation
27537 pts/2    Sl+    0:00 mpiexec --bind-to none -n 4 /home/vagrant/.pyenv/versions/py2/bin/python mpi_run.py
27540 pts/2    Sl   113:19 /home/vagrant/.pyenv/versions/py2/bin/python mpi_run.py
27541 pts/2    Rl   6291:46 /home/vagrant/.pyenv/versions/py2/bin/python mpi_run.py
27543 pts/2    Rl   6291:45 /home/vagrant/.pyenv/versions/py2/bin/python mpi_run.py
27545 pts/2    Rl   6291:45 /home/vagrant/.pyenv/versions/py2/bin/python mpi_run.py
```

When listing the directory, it shows the simulation had been deleted:

```
# ls /var/db/sirepo/user/CsCZcfiK/srw/6jLI7VAE/fluxAnimation
ls: cannot access /var/db/sirepo/user/CsCZcfiK/srw/6jLI7VAE/fluxAnimation: No such file or directory
```

When the run-background process was killed, the server became responsive again. Possibly, the mpi process was flooding NFS? Or causing celery or another process to become overloaded?

**Comment by robnagler** [comment]
There may be locking issues with killing celery tasks. I don't think it was flooding NFS if the run time was so high. SRW has 50K particle reports that will basically run forever.

Flower is not reliable.

Next time, dump the entire process table with more info (don't publish here though because can contain secrets): ps axvwwe

**Comment by robnagler** [comment]
Obsolete and caused by #400 in any event.
