### ISSUE TITLE
elegant: enable users to write notes (for entire simulation and also per report)

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#963]
This should be useful for all Sirepo apps, but it is bothering me while I'm working with elegant.

I want to write some notes associated with specific reports, for future reference (to me) and also for the benefit of scientists who copy my simulation in the future.

I also want to be able to make notes about the simulation as a whole.

**Comment by bruhwiler** [comment]
This would have been very useful for teaching the US Particle Accelerator School Class, for the students especially.    

As the instructor, I'm creating many simulations in preparation for the class, and I try to organize them within folders and give each one a meaningful name; however, the ability to write some notes regarding the purpose of the simulation, when it was created, the URL of the simulation it was copied from, etc. would be very helpful.

**Comment by moellep** [comment]
When you create a new elegant simulation - new Notes field is shown, but if you enter notes and select Save Changes, the notes don't appear when you select the simulation link on the source page. Entering notes on the source page appears to work OK.

**Comment by moellep** [comment]
closed with 3bf166a
