### ISSUE TITLE
elegant: configure which reports appear on the 'Visualization' tab

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#964]
This should be useful for all Sirepo apps, but it is bothering me while I'm working with elegant.

The visualization tab can have a large number of reports. Sometimes only a couple of reports are useful. This is frustrating.

I know that unwanted reports can be partially minimized, but this can be ugly and error prone, especially when sharing a simulation with another scientist, who then might open up the unwanted reports and lose sight of which ones are actually important.

It should be possible to configure the visualization tab so that unwanted reports don't appear at all.

**Comment by moellep** [comment]
It would be nice to have an X in the report panel heading which would confirm if you remove the report.
For now, the work-around is to disable the report from the Control or Lattice tab. With the exception of WATCH elements, all reports can be turned off. For example, the run_setup.output, centroid, sigma reports can be turned of by editing the run_setup command and changing the appropriate fields to "None".

**Comment by bruhwiler** [comment]
Thanks for the pointer, Paul.  The work around is good enough for now. I'll close this issue and we'll see if other users have similar requests in the future.
