### ISSUE TITLE
Elegant:  import *.ele or *.lte file into existing simulation?

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#976]
I can import these files to create a new simulation, by selecting the 'Import' icon.

I don't see how to import them into an existing `elegant` simulation.

Is it possible?

**Comment by moellep** [comment]
No, it isn't possible to import into an existing simulation. If this was added, would it be used to replace the lattice or something similar?

**Comment by bruhwiler** [comment]
The use case I encountered, which prompted this ticket:
a) user creates a new simulation and defines the beam
b) the lattice page is empty; user decides to upload a lattice file
c) user realizes this is not possible;  must build lattice from scratch or start over :(

I understand the concern about what happens if a lattice file already exists.
I can imagine a few ways to deal with that situation.

For now, let's consider this a feature request.
