### ISSUE TITLE
elegant:  FTABLE element is missing two arguments in SDDS file

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#978]
When importing an SDDS file, there is an error, because the FTABLE element is missing two arguments: FACTOR and SIMPLE_INPUT

Here is the problematic simulation,
https://beta.sirepo.com/elegant#/source/kCMAoSkb 

Two SDDS files have been sent to the support@ email list.

I'm making this 1st priority because the problem is preventing a user from getting results.

**Comment by moellep** [comment]
These fields were added in a newer version of elegant. We are running an old version (28.1.0 from 2015). The container should get updated to a more recent version as part of this ticket.

**Comment by bruhwiler** [comment]
I think we should have a newer version than 2015.  I've added Rob to the ticket, because he will probably be the one to upgrade the container.
