### ISSUE TITLE
SRW: improve auto-compute vectors

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#980]
When the auto-compute vectors is selected, the computed fields should be disabled to show the user which fields are affected.

**Comment by moellep** [comment]
The vector angle UI should be clearer now. The auto-compute field offers a choice of (Horizontal, Vertical, None). Selecting horizontal or vertical computes the appropriate fields and disables field input. Selecting "None" allows the values to be changed to any value.
![screen shot 2017-12-15 at 3 39 43 pm](https://user-images.githubusercontent.com/6516910/34063299-7e1c8c32-e1ae-11e7-8f4c-148d327d0f89.png)
![screen shot 2017-12-15 at 3 39 55 pm](https://user-images.githubusercontent.com/6516910/34063301-80d5a134-e1ae-11e7-9070-27613a759cb8.png)
![screen shot 2017-12-15 at 3 40 05 pm](https://user-images.githubusercontent.com/6516910/34063303-8388e29c-e1ae-11e7-85b3-91d7aa9bd8cf.png)

**Comment by mrakitin** [comment]
I very like that, thanks a lot Paul!
