### ISSUE TITLE
Sirepo Code Page- Next step cue

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#986]
Once a user lands on a code page (e.g. https://alpha.sirepo.com/shadow#/simulations), it isn't immediately obvious what the next step should be. It might be good to provide a nudge.

Some thoughts we generated quickly included:
1) a read me
2) a cookie driven pop up suggesting that the user click on one of the existing simulations

Paul said he saw some interesting UI ideas on Basecamp.com

**Comment by moellep** [comment]
Below is an example from basecamp. When you visit the messages page the first time, it has a notification which give you a hint. Something similar on the simulation list page would help out. Text could be something like 

Welcome to Sirepo - (code name)! 
Below are some example simulations and folders containing simulations. Click on the simulation to open and view simulation results. You can create a new simulation by selecting the New Simulation link above.

![screen shot 2017-12-20 at 12 52 23 pm](https://user-images.githubusercontent.com/6516910/34225861-17fa685e-e585-11e7-8485-573682ad2eb4.png)

**Comment by bruhwiler** [comment]
This would be great.
The suggested text sounds good to me.
David

**Comment by messamer** [comment]
Agreed!

**Comment by moellep** [comment]
@mkeilman has implemented this. Below is a screenshot:

![screen shot 2018-01-03 at 9 09 25 am](https://user-images.githubusercontent.com/6516910/34528341-e319ffb4-f065-11e7-9272-bab51fdb9bbd.png)
