### ISSUE TITLE
Add new type of undulator source in Sirepo/SRW based on magnetic data measurements

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#99]
Users of SRW at NSLS-II highly desire to have a new type of undulator source calculation based on magnetic data measurements. The new source type should be selected in the list of sources, then a user should be able to upload an archive with `*.dat` files which should be placed to `data_X/magn_meas/` directory. Then in Sirepo we will need the ability to execute the calculation analogous to the following commands with the corresponding fields to specify the parameters:
`python SRWLIB_VirtBL_SRX_01.py --sm --und_g=6.72 --sm_ei=7700 --sm_ef=8250 --sm_ne=200 --sm_mag=2 --ebm_ens=0.7e-03 --ebm_emx=1.5e-09`
or
`mpiexec -np 15 python SRWLIB_VirtBL_SRX_01.py --sm --und_g=6.72 --sm_ei=7700 --sm_ef=8250 --sm_ne=200 --sm_mag=2 --ebm_ens=0.7e-03 --ebm_emx=1.5e-09`

Parallel calculation should be supported within a widget, so a user could specify which execution type to use - serial or parallel in a drop-down menu.

**Comment by bruhwile** [comment]
This ticket is overly prescriptive.
The issue of parallelism should be dealt with separately.
Most likely parallelism will be used to the extent possible, without input from users.

However, this feature is essential to NSLS-II users.

**Comment by bruhwile** [comment]
Paul -- please comment on the status of this ticket.

**Comment by bruhwile** [comment]
Probably some user testing is required.
More examples need to be added.
These should be new issues.

**Comment by moellep** [comment]
This ticket should be complete now the partially coherent flux report was
added on the source page.
