### ISSUE TITLE
fete: Update example templates for WarpVND

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#993]
The following changes should be made to the standard templates for WarpVND:

1. Remove the "Heat Engine" example

2. Add the "Gridded TEC" example: https://alpha.sirepo.com/warpvnd#/source/X1af3gUq

**Comment by cchall** [comment]
Here is an updated "Gridded TEC" example with better grid transparency.
This should be used instead: https://alpha.sirepo.com/warpvnd#/source/MQHx8g1h

**Comment by moellep** [comment]
The Heat Engine example has been removed - it won't show up for new users visiting the application. New users will also see the new Gridded TEC example. 

Existing users can view the Gridded TEC example using the link below:

https://alpha.sirepo.com/find-by-name/warpvnd/default/Gridded%20TEC
