### ISSUE TITLE
SRW error on SMI beamline example

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#994]
Watchpoint reports are causing "AttributeError: 'SRWLOptT' object has no attribute 'set_orient'" error.

**Comment by mrakitin** [comment]
`set_orient` method is supposed to call against the `srwlib.SRWLOptCryst` object.

**Comment by moellep** [comment]
This bug was caused by a change to the code generation in f21a5a4.  This change didn't properly handle a crystal element which includes a height profile data file. There are test cases in srw_generate_test.py, but it didn't include this particular case.

**Comment by mrakitin** [comment]
I see, thanks for letting us know! We need more tests.
